### ISSUE TITLE
Crash when trying to attach image

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10016]
Nightly users of 2021.02.14-NB report:

It crashes when trying to attach image (tried the button and the menu).

```
02-15 00:08:12.264 31224 31224 E AndroidRuntime: FATAL EXCEPTION: main
02-15 00:08:12.264 31224 31224 E AndroidRuntime: Process: cgeo.geocaching, PID: 31224
02-15 00:08:12.264 31224 31224 E AndroidRuntime: java.util.IllegalFormatConversionException: d != java.lang.String
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4403)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2885)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2839)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2530)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at java.util.Formatter.format(Formatter.java:2459)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at java.lang.String.format(String.java:2911)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.content.res.Resources.getString(Resources.java:605)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at androidx.fragment.app.Fragment.getString(Fragment.java:873)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at cgeo.geocaching.ui.ImageListFragment$ImageListAdapter.getImageInfo(ImageListFragment.java:214)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at cgeo.geocaching.ui.ImageListFragment$ImageListAdapter.fillViewHolder(ImageListFragment.java:185)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at cgeo.geocaching.ui.ImageListFragment$ImageListAdapter.onBindViewHolder(ImageListFragment.java:230)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at cgeo.geocaching.ui.ImageListFragment$ImageListAdapter.onBindViewHolder(ImageListFragment.java:171)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3540)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.View.measure(View.java:27128)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:735)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:481)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.View.measure(View.java:27128)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7340)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.View.measure(View.java:27128)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7340)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.View.measure(View.java:27128)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.ScrollView.measureChildWithMargins(ScrollView.java:2362)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.ScrollView.onMeasure(ScrollView.java:701)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.View.measure(View.java:27128)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7340)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:146)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.View.measure(View.java:27128)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7340)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at androidx.appcompat.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:490)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.View.measure(View.java:27128)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7340)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.View.measure(View.java:27128)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7340)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.View.measure(View.java:27128)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7340)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1147)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.View.measure(View.java:27128)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4067)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2829)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3092)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2511)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9689)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1010)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:809)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:744)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:995)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8419)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
02-15 00:08:12.264 31224 31224 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by eddiemuc** [comment]
I assume this is because of the major change I did to the Image-Info-Text, having a whole new set of parameters inside. I changed this only in default strings.xml and not in all the existing translations, assuming that those would be deleted by crowdin automatically (I asked the question beforehand whether I should use a new string key instead and got that info back).

Existing "legacy" translations will indeed fail with the observed exception. Should I delete them manually or wait for crowdin to do it?

**Comment by rsudev** [comment]
Just a small remark from my side: I don't know who advised to re-use an existing string in this context, but I personally would advise against it. My experience from quite some years of working with internationalized applications is rather:

- If the meaning stays the same, but you correct spellings or clarifiy, keep the 'translation-id' (or key in our case)
- In all other cases create a new translation-id.

Why that? It helps translators, as they recognize it as a new entity. It also eases the transition from old to new, as the keys from the previous version can stick around until the new one gets released.

**Comment by bekuno** [comment]
The crowdin edit was merged yesterday.
So the 2021.02.16-NB is fine.

**Comment by Lineflyer** [comment]
I wasn't aware that parameter changes in the string might cause this. However as @bekuno mentioned it should be corrected by merging Crowdin translations by now.

**Comment by eddiemuc** [comment]
> Just a small remark from my side: I don't know who advised to re-use an existing string in this context, but I personally would advise against it. My experience from quite some years of working with internationalized applications is rather:
> 
> - If the meaning stays the same, but you correct spellings or clarifiy, keep the 'translation-id' (or key in our case)
> - In all other cases create a new translation-id.
> 
> Why that? It helps translators, as they recognize it as a new entity. It also eases the transition from old to new, as the keys from the previous version can stick around until the new one gets released.

In this case the meaning stayed kind of the same (contains information about an image), but parameters for display were different. Maybe a corner case.
