### ISSUE TITLE
NullPointerException in Geopoint.distanceTo

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#10071]
I saw this exception in the logcat while working on the Locus adapter.

**Describe the bug:**
~~~
2021-02-17 00:27:30.988 25428-25428/cgeo.geocaching W/cgeo: [main] Failed to update location
    java.lang.NullPointerException: Attempt to invoke virtual method 'float cgeo.geocaching.location.Geopoint.distanceTo(cgeo.geocaching.models.ICoordinates)' on a null object reference
        at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.getClosestDistanceInM(AbstractCachesOverlay.java:405)
        at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.getClosestDistanceInM(CachesBundle.java:341)
        at cgeo.geocaching.maps.mapsforge.v6.NewMap$UpdateLoc.repaintPositionOverlay(NewMap.java:1399)
        at cgeo.geocaching.maps.mapsforge.v6.NewMap$UpdateLoc.updateGeoDir(NewMap.java:1362)
        at cgeo.geocaching.sensors.GeoDirHandler.updateGeoDirData(GeoDirHandler.java:70)
        at cgeo.geocaching.sensors.GeoDirHandler.lambda$start$0(GeoDirHandler.java:109)
        at cgeo.geocaching.sensors.GeoDirHandler.lambda$start$0$GeoDirHandler(Unknown Source:0)
        at cgeo.geocaching.sensors.-$$Lambda$GeoDirHandler$iBu37b5fsSLKy3w8O-YfiBttMp8.accept(Unknown Source:4)
        at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
~~~

**To Reproduce:**

1. open map (tested with OSM.de),

**Actual behavior/state after performing these steps:**
No visual problem so far.

**Version of c:geo used:**
version from today master

**Is the problem reproducible:**
Yes

**Comment by bekuno** [comment]
Closing manually, auto close did not work.

**Comment by Lineflyer** [comment]
@bekuno 
Just for info: Auto close works as soon as the fix is on `master`, so it would have been triggered by my recent merge of branches.

**Comment by bekuno** [comment]
> 
> 
> @bekuno
> Just for info: Auto close works as soon as the fix is on `master`, so it would have been triggered by my recent merge of branches.

Sure. I forgot it.
