### ISSUE TITLE
Mass warnings: Cannot parse brouter output of length 29

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10095]
While working on a support ticket (possibly unrelated to this report) I have seen mass warning with the following text in users logfiles while the system information even states `BRouter connection available: false`.

Not sure, whether it is a real problem.

Just in case:
Could it be related to the users problem, that clicking on map cache icons does not open the popup?

```
03-01 10:14:36.274  6977 11747 W cgeo    : [RxCachedThreadScheduler-1] cannot parse brouter output of length 29
03-01 10:14:36.274  6977 11747 W cgeo    : org.apache.harmony.xml.ExpatParser$ParseException: At line 1, column 0: syntax error
03-01 10:14:36.274  6977 11747 W cgeo    : 	at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:512)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:497)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:317)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:275)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at android.util.Xml.parse(Xml.java:57)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at cgeo.geocaching.maps.routing.Routing.parseGpxTrack(Routing.java:217)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at cgeo.geocaching.maps.routing.Routing.calculateRouting(Routing.java:210)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at cgeo.geocaching.maps.routing.Routing.getTrackNoCaching(Routing.java:181)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at cgeo.geocaching.models.Route.calculateNavigationRoute(Route.java:145)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at cgeo.geocaching.models.ManualRoute.toggleItemInternal(ManualRoute.java:133)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at cgeo.geocaching.models.ManualRoute.loadRouteInternal(ManualRoute.java:99)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at cgeo.geocaching.models.ManualRoute.lambda$Zq5RjiHZa1mXEdSSrXm2UAJEDJU(Unknown Source:0)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at cgeo.geocaching.models.-$$Lambda$ManualRoute$Zq5RjiHZa1mXEdSSrXm2UAJEDJU.run(Unknown Source:2)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at cgeo.geocaching.utils.AndroidRxUtils.lambda$andThenOnUi$2(AndroidRxUtils.java:70)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at cgeo.geocaching.utils.-$$Lambda$AndroidRxUtils$bqzWo9nlvU86BvboB-9jhDWp5vc.run(Unknown Source:4)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-01 10:14:36.274  6977 11747 W cgeo    : 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by moving-bits** [comment]
nightly or release?

**Comment by Lineflyer** [comment]
@moving-bits 
As written initially, the system information shows `BRouter connection available: false`. therefore I wondered to see anything with respect to brouter in the log.

**Comment by moving-bits** [comment]
The error is thrown in `parseGpxTrack` which is called by `calculateRouting`, which itself is called by either `getTrack` or `getTrackNoCaching`. Both `getTrack` and `getTrackNoCaching` check for `brouter == null` first and don't call `calculateRouting` if so.

So I guess system information is wrong in this case (need to check why, though).

**Comment by moving-bits** [comment]
Regarding the info in Settings: Looks like it only shows a "true" if it has been initialized already (checks for `brouter != null`). Maybe we should change this to check whether BRouter is installed. I'll create a PR for this.

**Comment by Lineflyer** [comment]
@moving-bits I think we can close here, right?

**Comment by moving-bits** [comment]
> @moving-bits I think we can close here, right?

Yes
