### ISSUE TITLE
NPE in Routing logic should be safeguarded

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10138]
In preparation of a geocaching tour I imported a GPX yesterday, which was generated by https://www.project-gc.com
After that I notices, that c.geo keeps crashing under certain conditions. I am not 100% sure, that the GPX causes it but it seems likely as it happens on two devices, where c:geo was running stable until I imported the same GPX.

[20210312190043_Favaround.zip](https://github.com/cgeo/cgeo/files/6134583/20210312190043_Favaround.zip)

- Import the attached zipped GPX (in zipped format) into a new list "Fav around"
- Open the list
- Map the list (using OSM map)
- Leave the map, return to the list
- Leave the list to the mainscreen and either wait some seconds or do some other action (e.g. try to open the settings)

This procedure reproducibly crashes my c:geo 2021.03.12-NB

I am unsure about the corresponding error log, as somehow the logfile shows different problems or no exceptions logs at all while trying to produce this problem. Here is what I found so far, but you might want to try it yourself using the attached GPX. 
The problem might even be unrelated to these stacktraces.

```
03-13 11:44:34.106  6491  6491 E cgeo    : [main] Error requesting indeterminate progress
03-13 11:44:34.106  6491  6491 E cgeo    : android.util.AndroidRuntimeException: Window feature must be requested before adding content
03-13 11:44:34.106  6491  6491 E cgeo    : 	at androidx.appcompat.app.AppCompatDelegateImpl.throwFeatureRequestIfSubDecorInstalled(AppCompatDelegateImpl.java:2309)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at androidx.appcompat.app.AppCompatDelegateImpl.requestWindowFeature(AppCompatDelegateImpl.java:1085)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at androidx.appcompat.app.AppCompatActivity.supportRequestWindowFeature(AppCompatActivity.java:267)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at cgeo.geocaching.activity.AbstractActivity.onCreateCommon(AbstractActivity.java:150)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at cgeo.geocaching.activity.AbstractActivity.onCreate(AbstractActivity.java:131)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at cgeo.geocaching.CachePopup.onCreate(CachePopup.java:43)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at android.app.Activity.performCreate(Activity.java:7957)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at android.app.Activity.performCreate(Activity.java:7946)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3598)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at android.os.Looper.loop(Looper.java:237)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:8107)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
03-13 11:44:34.106  6491  6491 E cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
03-13 11:44:34.108  6491  6491 E cgeo    : [main] Error requesting no title feature
03-13 11:44:34.108  6491  6491 E cgeo    : android.util.AndroidRuntimeException: Window feature must be requested before adding content
03-13 11:44:34.108  6491  6491 E cgeo    : 	at androidx.appcompat.app.AppCompatDelegateImpl.throwFeatureRequestIfSubDecorInstalled(AppCompatDelegateImpl.java:2309)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at androidx.appcompat.app.AppCompatDelegateImpl.requestWindowFeature(AppCompatDelegateImpl.java:1089)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at androidx.appcompat.app.AppCompatActivity.supportRequestWindowFeature(AppCompatActivity.java:267)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at cgeo.geocaching.CachePopup.onCreate(CachePopup.java:45)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at android.app.Activity.performCreate(Activity.java:7957)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at android.app.Activity.performCreate(Activity.java:7946)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3598)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at android.os.Looper.loop(Looper.java:237)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:8107)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
03-13 11:44:34.108  6491  6491 E cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

```
3-12 21:00:16.053 25031 28302 E AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-3
03-12 21:00:16.053 25031 28302 E AndroidRuntime: Process: cgeo.geocaching, PID: 25031
03-12 21:00:16.053 25031 28302 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String cgeo.geocaching.maps.routing.BRouterServiceConnection.getTrackFromParams(android.os.Bundle)' on a null object reference
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at cgeo.geocaching.maps.routing.Routing.calculateRouting(Routing.java:203)
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at cgeo.geocaching.maps.routing.Routing.getTrackNoCaching(Routing.java:181)
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at cgeo.geocaching.models.Route.calculateNavigationRoute(Route.java:145)
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at cgeo.geocaching.models.IndividualRoute.toggleItemInternal(IndividualRoute.java:133)
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at cgeo.geocaching.models.IndividualRoute.loadRouteInternal(IndividualRoute.java:99)
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at cgeo.geocaching.models.IndividualRoute.lambda$_GNSf27WQYOP2dSZLbdIUw-Qclw(Unknown Source:0)
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at cgeo.geocaching.models.-$$Lambda$IndividualRoute$_GNSf27WQYOP2dSZLbdIUw-Qclw.run(Unknown Source:2)
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at cgeo.geocaching.utils.AndroidRxUtils.lambda$andThenOnUi$2(AndroidRxUtils.java:70)
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at cgeo.geocaching.utils.-$$Lambda$AndroidRxUtils$bqzWo9nlvU86BvboB-9jhDWp5vc.run(Unknown Source:4)
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-12 21:00:16.053 25031 28302 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
```

**Comment by Lineflyer** [comment]
Further observation:
From my feeling it might be not directly related to the GPX but triggered already by leaving the map before all tiles are loaded (offline map). Using Google or an OSM online map I can not reproduce the problem.

**Comment by Lineflyer** [comment]
Just checked another device where I did not import any caches from GPX or alike and see the same problem.
Let me close here and start over with a new issue after investigation is completed.
Sorry for the noise.

**Comment by Lineflyer** [comment]
#10139 seems to be the root cause here.

**Comment by eddiemuc** [comment]
Still you have a nasty NPE in your log which imho should be fixed/safeguarded

**Comment by eddiemuc** [comment]
I edited title and reopened, hope that's ok

**Comment by Lineflyer** [comment]
Thanks....maybe I should audit my logs from time to time to find such things.
