### ISSUE TITLE
Native crash when repeatedly opening/closing the OSM map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10139]
- 2021.03.12-NB on Google Pixel 3a, Android 11
- Use OSM offline map (might be the same also with OSM online map)
- Open live map and deactivate live mode (to avoid unrelated warnings in the log)
- Zoom out, so that rendering all tiles takes a bit longer
- Close the map
- Open the map and close it again before all tiles are rendered
- Open the map again

Crash

Log file shows
```
3-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #09 pc 000000000007862c  /system/lib64/libbinder.so (android::PoolThread::threadLoop()+24)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #10 pc 00000000000154d0  /system/lib64/libutils.so (android::Thread::_threadLoop(void*)+260)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #11 pc 00000000000a0be0  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::javaThreadShell(void*)+144)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #12 pc 0000000000014d94  /system/lib64/libutils.so (thread_data_t::trampoline(thread_data_t const*)+412)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #13 pc 00000000000afd4c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #14 pc 0000000000050288  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   (no managed stack frames)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655] 
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655] Aborting thread:
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655] "pool-5-thread-4" prio=5 tid=41 Native
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   | group="" sCount=0 dsCount=0 flags=0 obj=0x16083428 self=0x78505642e0
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   | sysTid=10069 nice=0 cgrp=default sched=0/0 handle=0x7668d8dcc0
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   | state=R schedstat=( 904004486 312009633 4417 ) utm=72 stm=17 core=7 HZ=100
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   | stack=0x7668c8a000-0x7668c8c000 stackSize=1043KB
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   | held mutexes= "abort lock"
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #00 pc 000000000049da74  /apex/com.android.art/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+140)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #01 pc 00000000005aabcc  /apex/com.android.art/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, bool, BacktraceMap*, bool) const+376)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #02 pc 00000000005702fc  /apex/com.android.art/lib64/libart.so (art::AbortState::DumpThread(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, art::Thread*) const+60)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #03 pc 000000000055bcd4  /apex/com.android.art/lib64/libart.so (art::Runtime::Abort(char const*)+2436)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #04 pc 0000000000013978  /system/lib64/libbase.so (android::base::SetAborter(std::__1::function<void (char const*)>&&)::$_3::__invoke(char const*)+76)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #05 pc 0000000000006e18  /system/lib64/liblog.so (__android_log_assert+336)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #06 pc 00000000001a8f04  /system/lib64/libhwui.so (android::CanvasJNI::drawBitmapMatrix(_JNIEnv*, _jobject*, long, long, long, long)+68)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #07 pc 00000000001f8a50  /system/framework/arm64/boot-framework.oat (art_jni_trampoline+176)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #08 pc 00000000004a4034  /system/framework/arm64/boot-framework.oat (android.graphics.Canvas.drawBitmap+196)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #09 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #10 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #11 pc 000000000031830c  /apex/com.android.art/lib64/libart.so (art::interpreter::ArtInterpreterToCompiledCodeBridge(art::Thread*, art::ArtMethod*, art::ShadowFrame*, unsigned short, art::JValue*)+376)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #12 pc 000000000030e638  /apex/com.android.art/lib64/libart.so (bool art::interpreter::DoCall<false, false>(art::ArtMethod*, art::Thread*, art::ShadowFrame&, art::Instruction const*, unsigned short, art::JValue*)+996)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #13 pc 0000000000681b5c  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtualQuick+672)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #14 pc 0000000000131594  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual_quick+20)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #15 pc 000000000051c792  /data/app/~~EseXpU68j9ZMKWa1_nipNA==/cgeo.geocaching-g63zL7zX3OS83O5T0pZSYg==/oat/arm64/base.vdex (org.mapsforge.map.android.graphics.AndroidCanvas.drawBitmap+74)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #16 pc 000000000067cdf0  /apex/com.android.art/lib64/libart.so (MterpInvokeInterface+1808)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #17 pc 000000000012da14  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_interface+20)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #18 pc 0000000000518c4c  /data/app/~~EseXpU68j9ZMKWa1_nipNA==/cgeo.geocaching-g63zL7zX3OS83O5T0pZSYg==/oat/arm64/base.vdex (org.mapsforge.core.mapelements.SymbolContainer.draw+108)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #19 pc 0000000000681dfc  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtualQuick+1344)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #20 pc 0000000000131594  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual_quick+20)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #21 pc 0000000000526c68  /data/app/~~EseXpU68j9ZMKWa1_nipNA==/cgeo.geocaching-g63zL7zX3OS83O5T0pZSYg==/oat/arm64/base.vdex (org.mapsforge.map.layer.renderer.CanvasRasterer.drawMapElements+68)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #22 pc 0000000000681dfc  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtualQuick+1344)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #23 pc 0000000000131594  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual_quick+20)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #24 pc 00000000005272e2  /data/app/~~EseXpU68j9ZMKWa1_nipNA==/cgeo.geocaching-g63zL7zX3OS83O5T0pZSYg==/oat/arm64/base.vdex (org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob+234)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #25 pc 0000000000681dfc  /apex/com.android.art/lib64/libart.so (MterpInvokeVirtualQuick+1344)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #26 pc 0000000000131594  /apex/com.android.art/lib64/libart.so (mterp_op_invoke_virtual_quick+20)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #27 pc 00000000005276d8  /data/app/~~EseXpU68j9ZMKWa1_nipNA==/cgeo.geocaching-g63zL7zX3OS83O5T0pZSYg==/oat/arm64/base.vdex (org.mapsforge.map.layer.renderer.MapWorkerPool$MapWorker.run+164)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #28 pc 0000000000305c34  /apex/com.android.art/lib64/libart.so (art::interpreter::Execute(art::Thread*, art::CodeItemDataAccessor const&, art::ShadowFrame&, art::JValue, bool, bool) (.llvm.4023174618862212076)+268)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #29 pc 0000000000669e20  /apex/com.android.art/lib64/libart.so (artQuickToInterpreterBridge+780)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #30 pc 000000000013cff8  /apex/com.android.art/lib64/libart.so (art_quick_to_interpreter_bridge+88)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #31 pc 000000000029d318  /apex/com.android.art/javalib/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+984)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #32 pc 000000000029a510  /apex/com.android.art/javalib/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+64)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #33 pc 000000000015ab08  /apex/com.android.art/javalib/arm64/boot.oat (java.lang.Thread.run+72)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #34 pc 0000000000133564  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+548)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #35 pc 00000000001a8a78  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+200)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #36 pc 0000000000553890  /apex/com.android.art/lib64/libart.so (art::JValue art::InvokeVirtualOrInterfaceWithJValues<art::ArtMethod*>(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, art::ArtMethod*, jvalue const*)+460)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #37 pc 00000000005a2c2c  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1308)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #38 pc 00000000000afd4c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   native: #39 pc 0000000000050288  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   at android.graphics.BaseCanvas.nDrawBitmapMatrix(Native method)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   at android.graphics.BaseCanvas.drawBitmap(BaseCanvas.java:122)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   at android.graphics.Canvas.drawBitmap(Canvas.java:1700)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   at org.mapsforge.map.android.graphics.AndroidCanvas.drawBitmap(AndroidCanvas.java:140)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   at org.mapsforge.core.mapelements.SymbolContainer.draw(SymbolContainer.java:76)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   at org.mapsforge.map.layer.renderer.CanvasRasterer.drawMapElements(CanvasRasterer.java:76)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:112)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   at org.mapsforge.map.layer.renderer.MapWorkerPool$MapWorker.run(MapWorkerPool.java:149)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655]   at java.lang.Thread.run(Thread.java:923)
03-13 12:11:17.970  7447 10069 F cgeo.geocachin: runtime.cc:655] 
03-13 12:11:18.895 10117 10117 E cgeo.geocachin: Not starting debugger since process cannot load the jdwp agent.
03-13 12:11:18.942 10117 10117 I cgeo.geocachin: The ClassLoaderContext is a special shared library.
03-13 12:11:18.986 10117 10117 W cgeo.geocachin: Accessing hidden field Landroid/view/ViewConfiguration;->sHasPermanentMenuKey:Z (greylist-max-p, reflection, denied)
03-13 12:11:19.059 10117 10117 I cgeo    : [Log] Logging set: minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=4, throwOnError=false
03-13 12:11:19.060 10117 10117 I cgeo    : [Log] No logging config file 'log-properties.txt' found at /cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles], using defaults
03-13 12:11:19.060 10117 10117 I cgeo    : [Log] Logging set: minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=4, throwOnError=false
03-13 12:11:19.072 10117 10117 I cgeo    : [main] [DB] Current Database Version: 94
03-13 12:11:19.273 10117 10117 I cgeo    : [main] LocalStorage: current Version: 2, expected Version: 2
03-13 12:11:22.386 10117 10117 W cgeo    : [main] Couldn't get active Locus version
03-13 12:11:23.957 10117 10137 I cgeo.geocachin: Waiting for a blocking GC ProfileSaver
03-13 12:11:28.059 10117 10152 I cgeo    : [RxCachedThreadScheduler-1] [LogCat]Issuing command: [logcat, -d, AndroidRuntime:E, cgeo:D, cgeo.geocachin:I, *:S, -f, /data/user/0/cgeo.geocaching/cache/cgeo_tempfile_2189776175617634408.tmp]
```

**Comment by fm-sys** [comment]
Was also discussed in #5155. The question is whether or not it has gotten worse through multithreading. Unfortunately I have no idea how this problem could be solved or if it needsto be solved at all...

**Comment by Lineflyer** [comment]
I tried with disabled multi threading and the problem still shows quite reproducible.

Then I tested with 2021.02.14 and I cannot reproduce it with that version.

**Comment by eddiemuc** [comment]
Teammeeting 19.11.23: issue can be closed when VTM/UnifiedMap is activated

**Comment by moving-bits** [comment]
Closed with "won't fix" as UnifiedMap is coming closer to being published in a beta version
