### ISSUE TITLE
SecurityException when trying to open GPX

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10133]
Reported by a user on support mail:

The user tries to open a GPX file (containing caches) recevied via Whatsapp or mail.
c:geo crashes when trying to import it.

I have asked the user to describe step-by-step how he tries to open the file and from what app he triggers to open it.

```
03-03 10:58:57.127 31663 31663 E AndroidRuntime: FATAL EXCEPTION: main
03-03 10:58:57.127 31663 31663 E AndroidRuntime: Process: cgeo.geocaching, PID: 31663
03-03 10:58:57.127 31663 31663 E AndroidRuntime: java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/all_downloads/4048 from pid=31663, uid=10333 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2088)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2056)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1694)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1510)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1194)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at cgeo.geocaching.files.FileTypeDetector.getFileType(FileTypeDetector.java:35)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at cgeo.geocaching.files.GPXImporter.importGPX(GPXImporter.java:89)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at cgeo.geocaching.files.GPXImporter.importGPX(GPXImporter.java:161)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at cgeo.geocaching.CacheListActivity.lambda$importGpxAttachement$4(CacheListActivity.java:618)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at cgeo.geocaching.CacheListActivity.lambda$importGpxAttachement$4$CacheListActivity(Unknown Source:0)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at cgeo.geocaching.-$$Lambda$CacheListActivity$ZyzHICuUWbvLhVk59vIUWp4yB_U.call(Unknown Source:4)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at cgeo.geocaching.list.StoredList$UserInterface.lambda$promptForListCreation$2(StoredList.java:218)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at cgeo.geocaching.list.StoredList$UserInterface.lambda$promptForListCreation$2$StoredList$UserInterface(Unknown Source:0)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at cgeo.geocaching.list.-$$Lambda$StoredList$UserInterface$YIzphoU0eIqsCTDRzzRd6EylFs0.call(Unknown Source:6)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at cgeo.geocaching.list.StoredList$UserInterface.lambda$handleListNameInput$4(StoredList.java:255)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at cgeo.geocaching.list.-$$Lambda$StoredList$UserInterface$iOXT_t24c3eCgRuhBTD_9SEPTYs.call(Unknown Source:4)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at cgeo.geocaching.ui.dialog.Dialogs.lambda$input$4(Dialogs.java:728)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at cgeo.geocaching.ui.dialog.-$$Lambda$Dialogs$d0V7wC_Pu8lZs1IM8WhUwUv1Lu0.onClick(Unknown Source:4)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:191)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
03-03 10:58:57.127 31663 31663 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: FATAL EXCEPTION: main
03-03 10:59:04.331 29213 29213 E AndroidRuntime: Process: cgeo.geocaching, PID: 29213
03-03 10:59:04.331 29213 29213 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.yahoo.mail.provider.AttachmentFileProvider from ProcessRecord{b3975da 29213:cgeo.geocaching/u0a333} (pid=29213, uid=10333) that is not exported from UID 10228
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2088)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2056)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2004)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6031)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7342)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2895)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2124)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1678)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1510)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1194)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at cgeo.geocaching.files.FileTypeDetector.getFileType(FileTypeDetector.java:35)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at cgeo.geocaching.files.GPXImporter.importGPX(GPXImporter.java:89)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at cgeo.geocaching.files.GPXImporter.importGPX(GPXImporter.java:161)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at cgeo.geocaching.CacheListActivity.lambda$importGpxAttachement$4(CacheListActivity.java:618)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at cgeo.geocaching.CacheListActivity.lambda$importGpxAttachement$4$CacheListActivity(Unknown Source:0)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at cgeo.geocaching.-$$Lambda$CacheListActivity$ZyzHICuUWbvLhVk59vIUWp4yB_U.call(Unknown Source:4)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at cgeo.geocaching.list.StoredList$UserInterface.lambda$promptForListSelection$0(StoredList.java:146)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at cgeo.geocaching.list.StoredList$UserInterface.lambda$promptForListSelection$0$StoredList$UserInterface(Unknown Source:0)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at cgeo.geocaching.list.-$$Lambda$StoredList$UserInterface$krzEx7wJJyD95_F-5VTcjndVJwk.onClick(Unknown Source:10)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1463)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:374)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1736)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4207)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.widget.AbsListView$7.run(AbsListView.java:6692)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:8551)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:8391)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:9059)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2546)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3427)
03-03 10:59:04.331 29213 29213 E AndroidRuntime: 
03-03 15:17:49.066 29928 29928 E AndroidRuntime: FATAL EXCEPTION: main
03-03 15:17:49.066 29928 29928 E AndroidRuntime: Process: cgeo.geocaching, PID: 29928
03-03 15:17:49.066 29928 29928 E AndroidRuntime: java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/all_downloads/4050 from pid=29928, uid=10333 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2088)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2056)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:188)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:151)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:705)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1694)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1510)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1194)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at cgeo.geocaching.files.FileTypeDetector.getFileType(FileTypeDetector.java:35)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at cgeo.geocaching.files.GPXImporter.importGPX(GPXImporter.java:89)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at cgeo.geocaching.files.GPXImporter.importGPX(GPXImporter.java:161)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at cgeo.geocaching.CacheListActivity.lambda$importGpxAttachement$4(CacheListActivity.java:618)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at cgeo.geocaching.CacheListActivity.lambda$importGpxAttachement$4$CacheListActivity(Unknown Source:0)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at cgeo.geocaching.-$$Lambda$CacheListActivity$ZyzHICuUWbvLhVk59vIUWp4yB_U.call(Unknown Source:4)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at cgeo.geocaching.list.StoredList$UserInterface.lambda$promptForListSelection$0(StoredList.java:146)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at cgeo.geocaching.list.StoredList$UserInterface.lambda$promptForListSelection$0$StoredList$UserInterface(Unknown Source:0)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at cgeo.geocaching.list.-$$Lambda$StoredList$UserInterface$krzEx7wJJyD95_F-5VTcjndVJwk.onClick(Unknown Source:10)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1463)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:374)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1736)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4207)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.widget.AbsListView$7.run(AbsListView.java:6692)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
03-03 15:17:49.066 29928 29928 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: FATAL EXCEPTION: main
03-03 15:17:58.906 17345 17345 E AndroidRuntime: Process: cgeo.geocaching, PID: 17345
03-03 15:17:58.906 17345 17345 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.yahoo.mail.provider.AttachmentFileProvider from ProcessRecord{557ab4b 17345:cgeo.geocaching/u0a333} (pid=17345, uid=10333) that is not exported from UID 10228
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2088)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2056)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2004)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.getContentProvider(IActivityManager.java:6031)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7342)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2895)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:2124)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1678)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1510)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1194)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at cgeo.geocaching.files.FileTypeDetector.getFileType(FileTypeDetector.java:35)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at cgeo.geocaching.files.GPXImporter.importGPX(GPXImporter.java:89)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at cgeo.geocaching.files.GPXImporter.importGPX(GPXImporter.java:161)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at cgeo.geocaching.CacheListActivity.lambda$importGpxAttachement$4(CacheListActivity.java:618)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at cgeo.geocaching.CacheListActivity.lambda$importGpxAttachement$4$CacheListActivity(Unknown Source:0)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at cgeo.geocaching.-$$Lambda$CacheListActivity$ZyzHICuUWbvLhVk59vIUWp4yB_U.call(Unknown Source:4)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at cgeo.geocaching.list.StoredList$UserInterface.lambda$promptForListSelection$0(StoredList.java:146)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at cgeo.geocaching.list.StoredList$UserInterface.lambda$promptForListSelection$0$StoredList$UserInterface(Unknown Source:0)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at cgeo.geocaching.list.-$$Lambda$StoredList$UserInterface$krzEx7wJJyD95_F-5VTcjndVJwk.onClick(Unknown Source:10)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1463)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.widget.AdapterView.performItemClick(AdapterView.java:374)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1736)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4207)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.widget.AbsListView.onTouchUp(AbsListView.java:6707)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:6453)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.widget.ListView.onTouchEvent(ListView.java:1721)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:14368)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3857)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:6365)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:770)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1952)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.app.Dialog.dispatchTouchEvent(Dialog.java:1156)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:728)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:14636)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6582)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6360)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5849)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5815)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5971)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5823)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6028)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5849)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5815)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5823)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9032)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8889)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8842)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9169)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.os.MessageQueue.next(MessageQueue.java:336)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:197)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:8551)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProviderImpl(ActivityManagerService.java:8391)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.getContentProvider(ActivityManagerService.java:9059)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2546)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3427)
03-03 15:17:58.906 17345 17345 E AndroidRuntime: 
```

```
--- System information ---
Device: SM-A705FN (a70qeea, samsung)
Android version: 10
Android build: QP1A.190711.020.A705FNXXU5CTK4
c:geo version: 2021.02.14
Google Play services: disabled - 21.02.14 (120400-352619232)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: own/found archived
Hide waypoints: visited
HW acceleration: disabled (manually changed)
System language: nl_NL / user-defined language: 
System date format: dd-MM-y
Debug mode active: yes
System internal c:geo dir: /data/user/0/cgeo.geocaching (63,9 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (63,9 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (63,9 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (151,2 MB) on system internal storage
Last backup: 16 feb. 20:28
GPX import path: /storage/emulated/0/cgeo/gpx
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/emulated/0/cgeo/gpx
Map render theme path: 
Live map mode: true
Global filter: display all caches
Sailfish OS detected: false
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Ingelogd) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins: contacts
BRouter connection available: false
--- End of system information ---
```

**Comment by eddiemuc** [comment]
Without having look into this deeper, I think the error message is pretty clear:
`java.lang.SecurityException: Permission Denial: reading com.android.providers.downloads.DownloadProvider uri content://downloads/all_downloads/4048 from pid=31663, uid=10333 requires android.permission.ACCESS_ALL_DOWNLOADS, or grantUriPermission()`

I would assume that both WhatsApp/email does not correctly assign read permission for c:geo on the Uri, and we do not ourself have ACCESS_ALL_DOWNLOADS permission.

**Comment by Lineflyer** [comment]
I have not heard of similar problems neither got more related problem reports. Closing. Assuming the bug was fixed at remote end.
