### ISSUE TITLE
AbstractLocusAppTest.testToLocusTypeCount fails

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#10191]
**Describe the bug:**
see
https://ci.cgeo.org/job/cgeo%20pull%20request/5123/testReport/cgeo.geocaching.apps/AbstractLocusAppTest/testToLocusTypeCount/

~~~
java.lang.AssertionError: expected:<22> but was:<23>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at cgeo.geocaching.apps.AbstractLocusAppTest.testToLocusTypeCount(AbstractLocusAppTest.java:22)
~~~

**Comment by moving-bits** [comment]
@bekuno 
Seems to be fixed meanwhile (don't have the PR number at hand, though) - can we close this issue?

**Comment by bekuno** [comment]
The issue was raised as we implemented the LC Connector with our extra LC type.
The number change for the test was fixed.

I have checked the Locus Api. The state is until now (version 0.9.35): "Lab cache, not published over API".
So for now no need to change our code.
