### ISSUE TITLE
App hanging on fresh start with SAF-related security exception

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#10211]
Just had something fancy in the emulator: I had a fresh install of c:geo, walked through the wizard, restored settings (without restarting c:geo), setting some new setting, and stumbled upon c:geo ignoring my changed setting.
So I force-closed c:geo and restarted it.

First restart ended after some minutes with an `OutOfMemoryError` while still only showing the splash screen:
```
2021-03-19 20:41:48.236 25274-25274/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 25274
    java.lang.OutOfMemoryError: OutOfMemoryError thrown while trying to throw OutOfMemoryError; no stack trace available
```

So I did a fresh restart of c:geo (from within the emulator), and kept an eye on LogCat in AS. It got readily filled with the following error:

```
2021-03-19 20:42:21.786 24232-24246/? E/DatabaseUtils: Writing exception to parcel
    java.lang.SecurityException: Permission Denial: reading com.android.externalstorage.ExternalStorageProvider uri content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps/children from pid=25444, uid=10160 requires that you obtain access using ACTION_OPEN_DOCUMENT or related APIs
        at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:729)
        at com.android.externalstorage.ExternalStorageProvider.enforceReadPermissionInner(ExternalStorageProvider.java:134)
        at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
2021-03-19 20:42:22.033 24232-24246/? E/DatabaseUtils: Writing exception to parcel
```
(actually hundreds of it)

I guess this at least explains the `OutOfMemoryError`, but may be related to errors like #10202, maybe others?

Anyway: Is this something we can catch and handle?

Extract from settings file:
```
<string name="pref_dataDir">/storage/emulated/0/Android/data/cgeo.geocaching/files</string>
<string name="renderthemefile"></string>
<string name="persistablefolder_basedir">DOCUMENT::content://com.android.externalstorage.documents/tree/primary%3Acgeo::</string>
<string name="persistablefolder_offlinemaps">DOCUMENT::content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::</string>
<string name="persistable_folder_broutertiles">DOCUMENT::content://com.android.externalstorage.documents/tree/primary%3AAndroid%2Fdata%2Fbtools.routingapp%2Ffiles%2Fbrouter%2Fsegments4::</string>
<string name="mapsource">cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleMapSource</string>
<boolean name="renderthemefolder_synctolocal" value="false" />
```

**Comment by eddiemuc** [comment]
@Lineflyer this might be serious, may I ask you to stop distribution of beta until this is resolved?

**Comment by eddiemuc** [comment]
The Security Exception is the one that is thrown if you try to access a valid Uri which exists in the file system but you have no permission to do so. Such situation may happen on settings restore situations if this is not handled carefully.

Unfortunately I do not handle SecurityException yet in ContentStorage (only IllegalArgumentException), will have to add that. But a local test with a no-longer-allowed Uri worked fine on my emulator nevertheless. Also, I have no idea why this Uri is queried in the context of a Binder object (can anyone explain to me what this is?) and why this seems to loop

@moving-bits
* can you reproduce the situation and make a trace dump while c:geo is "looping"? I need to know where c:geo stays in its code
* I assume the uri reported above was the valid offline map folder before but you changed it to some other folder? (this would explain why the Uri is so obvisouly a user-selected one but no longer valid

As a short-term measurement I could stop giving back folder access privileges to the system after deselecting it, but this would lead to c:geo accumulating folder permissions over time and might result in overflow on long term. Have to think/sleep about this.

**Comment by moving-bits** [comment]
@eddiemuc 

You mean something like this?

```
"main@12205" prio=5 tid=0x2 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	  at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
	  at android.content.ContentResolver.query(ContentResolver.java:944)
	  at android.content.ContentResolver.query(ContentResolver.java:880)
	  at android.content.ContentResolver.query(ContentResolver.java:836)
	  at cgeo.geocaching.storage.DocumentContentAccessor.queryDir(DocumentContentAccessor.java:358)
	  at cgeo.geocaching.storage.DocumentContentAccessor.findCreateSubdirectory(DocumentContentAccessor.java:328)
	  at cgeo.geocaching.storage.DocumentContentAccessor.getSubdirUri(DocumentContentAccessor.java:311)
	  at cgeo.geocaching.storage.DocumentContentAccessor.getFolderUri(DocumentContentAccessor.java:278)
	  at cgeo.geocaching.storage.DocumentContentAccessor.getUriForFolder(DocumentContentAccessor.java:229)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:282)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
```
(same three code lines repeating for hundreds of times)
```
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.getUriForFolder(ContentStorage.java:284)
	  at cgeo.geocaching.utils.LocalizationUtils.getMultiPurposeString(LocalizationUtils.java:71)
	  at cgeo.geocaching.storage.ContentStorage.reportProblem(ContentStorage.java:553)
	  at cgeo.geocaching.storage.ContentStorage.list(ContentStorage.java:219)
	  at cgeo.geocaching.storage.ContentStorage.list(ContentStorage.java:202)
	  at cgeo.geocaching.maps.mapsforge.v6.RenderThemeHelper.addAvailableThemes(RenderThemeHelper.java:406)
	  at cgeo.geocaching.maps.mapsforge.v6.RenderThemeHelper.recalculateAvailableThemes(RenderThemeHelper.java:383)
	  at cgeo.geocaching.maps.mapsforge.v6.RenderThemeHelper.<clinit>(RenderThemeHelper.java:101)
	  at cgeo.geocaching.maps.mapsforge.v6.RenderThemeHelper.resynchronizeOrDeleteMapThemeFolder(RenderThemeHelper.java:372)
	  at cgeo.geocaching.MainActivity.onCreate(MainActivity.java:338)
	  at android.app.Activity.performCreate(Activity.java:7802)
	  at android.app.Activity.performCreate(Activity.java:7791)
	  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
	  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
	  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
	  at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
	  at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	  at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
	  at android.os.Handler.dispatchMessage(Handler.java:107)
	  at android.os.Looper.loop(Looper.java:214)
	  at android.app.ActivityThread.main(ActivityThread.java:7356)
	  at java.lang.reflect.Method.invoke(Method.java:-1)
	  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by moving-bits** [comment]
During migration c:geo only asked me for BASE folder, and during restoring settings no additional question regarding folders came. I'll debug into the latter, as the "folder settings change - need to regrant access"-detection seems to fail here.

**Comment by moving-bits** [comment]
Ok, seems to be a bug introduced by myself with #10136: 

I'm checking restored settings against already existing SAF grants, but I do not check for restoring grants for folders not yet assigned (which is the typical situation for restore after a fresh install).

I'll create a PR for it.

**Comment by moving-bits** [comment]
PR #10213 is created for the underlying issue leading to this loop.

@eddiemuc 
Please check if you want to/can add some safeguard for the security exception.

**Comment by eddiemuc** [comment]
@moving-bits thanks for fixing the "surfacing" of this.

But this is clearly a bug of mine, such a loop should never be created. I will fix it.

**Comment by eddiemuc** [comment]
Oh and also thanka for providing the additional info which wich it is now easy to see the problem

**Comment by moving-bits** [comment]
> @moving-bits thanks for fixing the "surfacing" of this.
> 
> But this is clearly a bug of mine, such a loop should never be created. I will fix it.

Actually I had my share on it as well by missing the "unset folders" part...

And I learned something new along the way: How to create a trace from the middle of nowhere / without being able to set a breakpoint first...

BTW: This brings me to the question whether we will have to check for permissions to files as well? Currently I'm checking all `PersistableFolders` only, but what about grant to a single track file? (Do we have more than this?)

**Comment by eddiemuc** [comment]
PR #10214 is on its way. I would appreciate a review of someone since this deals with some things near the "heart" of SAF...

@moving-bits : yes in principle we would have to check the file permission as well on settings migration (we just have a single one :-))

While testing this I made a strange discovery:
* To simulate the error situation I set a user-defined folder "/cgeo/maps" for offline maps, then I copied the resulting setting string, then I changed the offline map folder to something else, then I passed the old Uri string into settings manually (so now settings point to a valid Uri for which c:geo has no longer access). Tested the PR in this setup
* Afterwards I set the base folder to "/cgeo" (was set to legacy before"
* I would have expected that now the "cgeo/maps" folder can be accessed too. But this was not the case
* This seems to be because SAF seems to validate each "root folder" separately and gives permission from there. And "/cgeo" is a different "root folder" than "/cgeo/maps"
* When I set maps folder to "set default", everything works (because c:geo-internall I use the Base "root folder" in this case). Only in the "change folder" dialog, c:geo thinkgs that "/cgeo/maps" and default folder "maps" under "/cgeo" are different (because it cannot access the former and thus the "marker file" check fails).

Yet again something where SAF behaves unexpected when compared to files

**Comment by Lineflyer** [comment]
Question: Shall we still stop the distribution of the beta version?

**Comment by eddiemuc** [comment]
I don't know how fine-grained you can steer this. It would be good if the fix comes into the beta rather quickly, and maybe we should at least not increase the distribution percentage until it is a few days in the wild. Does that sound reasonable?

**Comment by Lineflyer** [comment]
I will stop the distribution of the current beta. 
We can AFAIK anytime either continue or replace it. Hopefully Google Play is clever enough to prefer existing users of current beta after replacement and not randomly select other 50% for the update.

**Comment by Lineflyer** [comment]
Done:
![grafik](https://user-images.githubusercontent.com/949669/111866574-c20d6e00-896e-11eb-9845-947de8c93b8c.png)

**Comment by moving-bits** [comment]
> PR #10214 is on its way. I would appreciate a review of someone since this deals with some things near the "heart" of SAF...

From a first quick glance it LGTM, but I'll run a test against my "fresh install" scenario (without having included #10213).

> @moving-bits : yes in principle we would have to check the file permission as well on settings migration (we just have a single one :-))

Ok, I'll try to tackle this tonight, but that should not stop us from updating our beta after #10213 and #10214 have been merged.

**Comment by moving-bits** [comment]
Fixes for looping (#10214) and restoring unset folders (#10213) are merged to `release` and `master`. 
Thanks @eddiemuc for the fast reaction!

Theoretically we would be able to update our beta with this.
@Lineflyer What do you think?

**Comment by Lineflyer** [comment]
Sure, on my way.

**Comment by moving-bits** [comment]
Thanks! Then we can still make use of the weekend's higher usage of c:geo for more intense testing.
