### ISSUE TITLE
SAF folder cannot be accessed (IOException / NullPointerException)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10248]
On support mail a beta user informed us, that we sees an error toast, that /cgeo/maps cannot be accessed:

![Screenshot_2021-03-23-22-45-48-431_cgeo geocaching](https://user-images.githubusercontent.com/949669/112300685-6823e580-8c99-11eb-99ad-a5cbce2b83cb.jpg)

System information:
```
--- System information ---
c:geo version: 2021.03.22-RC

Device:
-------
- Device type: Redmi Note 9 Pro (joyeuse_eea, Redmi)
- Android version: 10
- Android build: QKQ1.191215.002 test-keys
- Sailfish OS detected: false
- Google Play services: enabled - 21.06.13 (120400-358943053)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Hide caches: archived
- Hide waypoints: -
- Set language: en
- System date format: M/d/yy
- Debug mode active: no
- Live map mode: true
- Global filter: display all caches
- Last backup: Oct 3, 2020, 12:43 AM
- Routing mode: Car
- Map: Google: Satellite
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleSatelliteSource
  - Atts: none
  - Theme:

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
- Geocaching.com date format: dd/MM/yyyy
- BRouter installed: false / connection available: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (68.2 GB free) v2 internal isDir(7 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (68.2 GB free) v2 external non-removable isDir(5 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (68.2 GB free) v2 external non-removable isDir(256 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (68.2 GB free) v2 internal isDir(0 entries)
- Public Folders: #9
- BASE: /cgeo (User-defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::], default: /storage/emulated/0/cgeo[FILE#0:p-file:///storage/emulated/0/cgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, Files:11, dirs:9, totalFileSize:126.5 MB, free space: 68.2 GB, files on device: 13511675)
- OFFLINE_MAPS: /cgeo/maps (User-defined)[/cgeo/maps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::], default: /cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps, Av:false, Files:0, dirs:0, totalFileSize:0 B, free space: -1 B, files on device: -1)
- OFFLINE_MAP_THEMES: /Download (User-defined)[/Download[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ADownload::], default: /cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ADownload/document/primary%3ADownload, Av:true, Files:30, dirs:0, totalFileSize:768.5 MB, free space: 68.2 GB, files on device: 13511675)
- LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, Files:10, dirs:0, totalFileSize:125.2 MB, free space: 68.2 GB, files on device: 13511675)
- GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, Files:0, dirs:0, totalFileSize:0 B, free space: 68.2 GB, files on device: 13511675)
- BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, Files:1, dirs:1, totalFileSize:1.3 MB, free space: 68.2 GB, files on device: 13511675)
- FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, Files:0, dirs:0, totalFileSize:0 B, free space: 68.2 GB, files on device: 13511675)
- SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos], default: (same)] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, Files:0, dirs:3, totalFileSize:0 B, free space: 68.2 GB, files on device: 13511675)
- TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest], default: (same)] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, Files:0, dirs:0, totalFileSize:0 B, free space: 68.2 GB, files on device: -1)
- Map render theme path:
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #3
- content://com.android.externalstorage.documents/tree/primary%3ADownload (Mar 22, 2:58 PM):RW
- content://com.android.externalstorage.documents/tree/primary%3Acgeo (Mar 22, 2:58 PM):RW
- content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps (Mar 22, 2:58 PM):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v94, Size:8.0 MB) on system internal storage
-Settings: v5, Count:133
--- End of system information ---
```

Log file (Relevant part):
```
03-23 22:46:21.167 24499 25110 W cgeo    : [AsyncTask #1] ContentStorage: Folder 'content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps)' could not be accessed
03-23 22:46:21.168 24499 25110 W cgeo    : [AsyncTask #1] Could not show toast 'Folder '/cgeo/maps (User-defined)' could not be accessed' to user: java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
03-23 22:46:21.171 24499 25110 W cgeo    : [AsyncTask #1] ContentStorage: Files in Folder 'content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps)' could not be listed
03-23 22:46:21.171 24499 25110 W cgeo    : java.io.IOException: Failed dir query for 'content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps' cols [document_id,_display_name,mime_type,last_modified,_size]
03-23 22:46:21.171 24499 25110 W cgeo    : 	at cgeo.geocaching.storage.DocumentContentAccessor.queryDir(DocumentContentAccessor.java:382)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at cgeo.geocaching.storage.DocumentContentAccessor.listInternal(DocumentContentAccessor.java:203)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at cgeo.geocaching.storage.DocumentContentAccessor.list(DocumentContentAccessor.java:185)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at cgeo.geocaching.storage.ContentStorage.list(ContentStorage.java:213)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at cgeo.geocaching.storage.ContentStorage.list(ContentStorage.java:203)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at cgeo.geocaching.storage.FolderUtils.treeWalk(FolderUtils.java:789)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at cgeo.geocaching.storage.FolderUtils.treeWalk(FolderUtils.java:785)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at cgeo.geocaching.storage.FolderUtils.getFolderInfo(FolderUtils.java:153)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at cgeo.geocaching.utils.SystemInformation.appendPublicFolders(SystemInformation.java:172)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at cgeo.geocaching.utils.SystemInformation.getSystemInformation(SystemInformation.java:120)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at cgeo.geocaching.AboutActivity$GatherSystemInformationTask.doInBackground(AboutActivity.java:342)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at cgeo.geocaching.AboutActivity$GatherSystemInformationTask.doInBackground(AboutActivity.java:316)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-23 22:46:21.171 24499 25110 W cgeo    : 	at java.lang.Thread.run(Thread.java:919)
03-23 22:46:21.171 24499 25110 W cgeo    : Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToNext()' on a null object reference
03-23 22:46:21.171 24499 25110 W cgeo    : 	at cgeo.geocaching.storage.DocumentContentAccessor.queryDir(DocumentContentAccessor.java:371)
03-23 22:46:21.171 24499 25110 W cgeo    : 	... 17 more
03-23 22:46:21.171 24499 25110 W cgeo    : [AsyncTask #1] Could not show toast 'Files in Folder '/cgeo/maps' could not be listed' to user: java.lang.RuntimeException: Can't toast on a thread that has not called Looper.prepare()
03-23 22:46:21.278 24499 24610 D OpenGLRenderer: endAllActiveAnimators on 0x713a66d600 (MenuPopupWindow$MenuDropDownListView) with handle 0x713a0f5b20
03-23 22:46:21.581 24499 25110 W BpBinder: Slow Binder: BpBinder transact took 359 ms, interface=android.content.IContentProvider, code=21 oneway=false
03-23 22:46:21.609 24499 24499 D ViewRootImpl: [TouchInput][ViewRootImpl] KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=363070915, downTime=363070915, deviceId=-1, source=0x101, displayId=-1 }
03-23 22:46:21.696 24499 24499 D ViewRootImpl: [TouchInput][ViewRootImpl] KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=363071005, downTime=363070915, deviceId=-1, source=0x101, displayId=-1 }
03-23 22:46:21.731 24499 24514 W System  : A resource failed to call close. 
03-23 22:46:21.732 24499 24514 I chatty  : uid=10257(cgeo.geocaching) FinalizerDaemon identical 4 lines
03-23 22:46:21.732 24499 24514 W System  : A resource failed to call close. 
03-23 22:46:21.745 24499 24499 D ForceDarkHelper: updateByCheckExcludeList: pkg: cgeo.geocaching activity: cgeo.geocaching.MainActivity@67e8e7d
03-23 22:46:23.955 24499 24610 D OpenGLRenderer: endAllActiveAnimators on 0x713a492400 (MenuPopupWindow$MenuDropDownListView) with handle 0x71abe036e0
03-23 22:46:34.756 24499 24579 I cgeo    : [RxCachedThreadScheduler-1] [LogCat]Issuing command: [logcat, -d, *:V, -f, /data/user/0/cgeo.geocaching/cache/cgeo_tempfile_1183711118194179075.tmp]
03-23 22:46:34.781 24499 24610 D OpenGLRenderer: endAllActiveAnimators on 0x71a7706500 (RippleDrawable) with handle 0x71ab20fec0
03-23 22:46:35.154 24499 24499 W cgeo    : [main] ContentStorage: Folder 'content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps)' could not be accessed
03-23 22:46:35.172 24499 24499 W cgeo    : [main] ContentStorage: Files in Folder 'content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps)' could not be listed
03-23 22:46:35.172 24499 24499 W cgeo    : java.io.IOException: Failed dir query for 'content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps' cols [document_id,_display_name,mime_type,last_modified,_size]
03-23 22:46:35.172 24499 24499 W cgeo    : 	at cgeo.geocaching.storage.DocumentContentAccessor.queryDir(DocumentContentAccessor.java:382)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at cgeo.geocaching.storage.DocumentContentAccessor.listInternal(DocumentContentAccessor.java:203)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at cgeo.geocaching.storage.DocumentContentAccessor.list(DocumentContentAccessor.java:185)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at cgeo.geocaching.storage.ContentStorage.list(ContentStorage.java:213)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at cgeo.geocaching.storage.ContentStorage.list(ContentStorage.java:203)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at cgeo.geocaching.storage.FolderUtils.treeWalk(FolderUtils.java:789)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at cgeo.geocaching.storage.FolderUtils.treeWalk(FolderUtils.java:785)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at cgeo.geocaching.storage.FolderUtils.getFolderInfo(FolderUtils.java:153)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at cgeo.geocaching.utils.SystemInformation.appendPublicFolders(SystemInformation.java:172)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at cgeo.geocaching.utils.SystemInformation.getSystemInformation(SystemInformation.java:120)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at cgeo.geocaching.utils.DebugUtils.shareLogfileAsEmail(DebugUtils.java:136)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at cgeo.geocaching.utils.DebugUtils.lambda$createLogcatHelper$6(DebugUtils.java:122)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at cgeo.geocaching.utils.-$$Lambda$DebugUtils$70tQoPSzV8SqzTPVUwruW9XuKL0.run(Unknown Source:8)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at android.os.Handler.handleCallback(Handler.java:883)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at android.os.Looper.loop(Looper.java:224)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:7562)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
03-23 22:46:35.172 24499 24499 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-23 22:46:35.172 24499 24499 W cgeo    : Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'boolean android.database.Cursor.moveToNext()' on a null object reference
03-23 22:46:35.172 24499 24499 W cgeo    : 	at cgeo.geocaching.storage.DocumentContentAccessor.queryDir(DocumentContentAccessor.java:371)
03-23 22:46:35.172 24499 24499 W cgeo    : 	... 20 more
03-23 22:46:35.267 24499 24499 I Timeline: Timeline: Activity_launch_request time:363084578
```

**Comment by eddiemuc** [comment]
I admit the handling of this NPE in code is not good, I will correct this.

However overall it looks as if the dir /cgeo/maps does not exist (any more), while the /cgeo dir does exist. Did the user (maybe accidentally) moved or deleted this directory in his device?

**Comment by Lineflyer** [comment]
Is this really correct...it looks doubled in its path:

From the stack trace:
```
'content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps)
```

**Comment by eddiemuc** [comment]
> Is this really correct...it looks doubled in its path:
> 
> From the stack trace:
> ```
> 'content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps)
> ```
> 

The ) at the very end is a bug in the log message, it is not really part of the Uri.

Wrt the rest: yes, this seems to be the way Google builds "document" Uris from "Tree" Uris
* The first part of the Uri (up to "/document/...") is a "Tree Uri" as returned by the action_open_document_tree intent. 
* Such an Uri  can not directly be used to access the folder, it must be converted into a "document Uri". This conversion seems to append the path a second time.
* If you access subfolders of the folder, the corresponding Document Uri will still start with the same "Tree Uri" (subfolder will not be attached), but the appended "document Uri" part will then also contain the subfolder.

**Comment by eddiemuc** [comment]
Additional to the above: note that the Uri semantics are specific to a Document Provider, and they are not documented (and can change from one day to the other). For example the Document Provider for "Download" folder has often different semantics (uses numeric ids in Uris). 

As an example to illustrate the above, here is a "typical" Uri for a log file in folder `/cgeo/logfiles`. This Uri was created from Tree Uri (as returned by a previous call to action_open_document_tree)  `/cgeo` (the Tree Uri is the uri where user granted access rights to; the document part of the Uri points to the real folder/file underneath that Tree Uri).

`content://com.android.externalstorage.documents/tree/primary%2Fcgeo/document/primary%3Acgeo%2Flogfiles%2Flogcat_2020-12-28_17-22-20-2.txt`

**Comment by eddiemuc** [comment]
PE #10250 will handle the NPE better in the logfile and enhance system information. But it will not make the /cgeo/maps folder magically accessible any more.

It might be that the user deleted or moved the `/cgeo/maps` folder, this would explain the system behaviour. But there might be something else as well: if you grant permission to a folder (say `/cgeo/maps`), then you delete this folder, then create a folder with same name at same place -> then the original granted permission, although it is for the same Uri, will NOT grant you access to the new folder any more. This is tricky to analyze of course, but in this case the user must try to re-select the folder (and thus re-grant permission to it)

**Comment by moving-bits** [comment]
A different way to "achieve" this might be the bug I had introduced regarding restoring settings (fixed with #10213): After a fresh install, users will get asked for a "base" folder grant. It they restore settings after that, and if that settings includes a "maps" folder path, that value got set without asking the user for a new grant. => bang!
(This is fixed with #10213 by additionally checking the settings to-be-restored for SAF folders yet being unset.)

**Comment by Lineflyer** [comment]
The user provided feedback, that he did not use offline maps and did not delete any folder.
Is there a possibility we assume cgeo/maps exists, while it doesn't?

**Comment by eddiemuc** [comment]
> The user provided feedback, that he did not use offline maps and did not delete any folder.
> Is there a possibility we assume cgeo/maps exists, while it doesn't?

Frankly, I have currently no idea how this could have happened. The User set the maps folder using SAF at some point (because this is the only way that this value could get a content-Uri as user-defined value), maybe only half-knowing what he is doing in the wizard. But that does not explain at all why the folder is not accessible any more (provided it is still there), because I can also see that he has the persisted permission for this folder in his sys info

**Comment by Lineflyer** [comment]
Its not accessible because it does not exist. That was confirmed by the user. He however stated, that he did not delete it but the error message came up out of the sudden and then he checked and could not find the folder.

But most likely he deleted it...or is there some point in our code where we might delete it.

Other question:
Why do we need SAF permission for the subfolders of /cgeo after all if the user already selected those as base.

**Comment by eddiemuc** [comment]
> But most likely he deleted it...or is there some point in our code where we might delete it.

Apart from the always lingering possibility of a bug, the only place where we really delete something is the "move" process. But also there we only delete the content of the folder to be moved, not the folder itself

**Comment by eddiemuc** [comment]
> Other question:
> Why do we need SAF permission for the subfolders of /cgeo after all if the user already selected /cgeo as base.

The short answer: we need to stop applying principles of the "file system world" to the "SAF world". It does not have these principles and works differently.

The long answer: SAF works like this:
* By issuing a "ACTION_OPEN_DOCUMENT_TREE" intent, we get back an Uri from the system where the user granted us read/write access to the folder and the subfolders represented by this Uri. This is called a "Tree Uri" by SAF.
* When we want to execute such access, we always have to do this through this Tree Uri. 
* When the user grants access this way to several "Tree Uris" then each of these "Tree Uris" has their own Permission entry.
* Now the important part: if the user grants access to two "Tree Uris" which are in a parent-child-relationship (e.g. one for "/cgeo" and one for "/cgeo/maps"), the SAF/Android system is not aware of this relationship! Means: it does not know and does not care that one is in the file system a parent of the other. More precise: SAF does not know the concept of a parent
* To stay in this example: assuming we have one grant for "/cgeo" and one for "/cgeo/maps" and we want to access a file "/cgeo/maps/berlin.map" -> then c:geo can decide whether to use the first grant (in which case it has to scan the Tree Uri starting from root /cgeo) or the second grant (in which case it has to scan the Tree Uri starting from root /cgeo/maps). But c:geo has no way (other than to use hacky heuristics on Uri patterns) of knowing that one folder is the parent from the other

This is what lead me to the concept of default folders, which on the technical level "executes" the above difference. Example Offline Maps folder:
* If a user chooses a separate folder for "offline maps", then a separate "grant" is created, and offline maps are accessed using this separate grant
* If a user chooses the "default folder", then NO separate grant is created (the one from "base" folder is used) and offline maps are accessed using the Base folder grant and searching in subfolder "maps" of this base folder
* Special case: if the user chooses "separate folder" for "offline maps", but then actively selects folder "maps" under Base folder (e.g. /cgeo/maps) then a separate grant is used for offline maps. Because c:geo cannot know that the user de facto selected a subfolder of base.

**Comment by eddiemuc** [comment]
is there anything left to do or can this be closed?

**Comment by Lineflyer** [comment]
Can be closed IMHO.
