### ISSUE TITLE
cgeo crashes when opening live map

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#10281]
cgeo keeps crashing when opening live map

(Individual route was set before upgrading to newest nightly) 

Stacktrace:
```
FATAL EXCEPTION: RxCachedThreadScheduler-1
Process: cgeo.geocaching, PID: 27833
io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.SecurityException: Binder invocation to an incorrect interface
	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:372)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:68)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:929)
Caused by: java.lang.SecurityException: Binder invocation to an incorrect interface
	at android.os.Parcel.createException(Parcel.java:2071)
	at android.os.Parcel.readException(Parcel.java:2039)
	at android.os.Parcel.readException(Parcel.java:1987)
	at cgeo.geocaching.brouter.IBRouterService$Stub$Proxy.getTrackFromParams(IBRouterService.java:157)
	at cgeo.geocaching.maps.routing.BRouterServiceConnection.getTrackFromParams(BRouterServiceConnection.java:46)
	at cgeo.geocaching.maps.routing.Routing.calculateRouting(Routing.java:213)
	at cgeo.geocaching.maps.routing.Routing.getTrackNoCaching(Routing.java:191)
	at cgeo.geocaching.models.Route.calculateNavigationRoute(Route.java:145)
	at cgeo.geocaching.models.IndividualRoute.toggleItemInternal(IndividualRoute.java:133)
	at cgeo.geocaching.models.IndividualRoute.loadRouteInternal(IndividualRoute.java:99)
	at cgeo.geocaching.models.IndividualRoute.lambda$_GNSf27WQYOP2dSZLbdIUw-Qclw(Unknown Source:0)
	at cgeo.geocaching.models.-$$Lambda$IndividualRoute$_GNSf27WQYOP2dSZLbdIUw-Qclw.run(Unknown Source:2)
	at cgeo.geocaching.utils.AndroidRxUtils.lambda$andThenOnUi$2(AndroidRxUtils.java:70)
	at cgeo.geocaching.utils.-$$Lambda$AndroidRxUtils$bqzWo9nlvU86BvboB-9jhDWp5vc.run(Unknown Source:4)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	... 6 more
```

**Comment by moving-bits** [comment]
Hm, this looks like the routing service. What settings do you have regarding the routing? Internal on/off? BRouter installed yes/no? Can you post your system info as well?

**Comment by fm-sys** [comment]
```
--- System information ---
c:geo version: 2021.03.28-NB-31d79d7

Device:
-------
- Device type: SNE-LX1 (SNE-LX1, HUAWEI)
- Android version: 10
- Android build: SNE-LX1 10.0.0.245(C432E10R1P1)
- Sailfish OS detected: false
- Google Play services: enabled - 21.09.15 (120408-361652764)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Hide caches: own/found archived
- Hide waypoints: original parking visited
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Debug mode active: no
- Live map mode: true
- Global filter: display all caches
- Last backup: 23. März, 09:01
- Routing mode: Fahrrad
 -Settings: v5, Count:170
- Map: Kombiniert (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMultiMapSource
  - Atts: <p><b>austria.map</b>:<br>mapsforge-map-writer-0.10.0</p><p><b>Deutschland.map</b>:<br>mapsforge-map-writer-0.10.0</p><p><b>hessen.map</b>:<br>Map data (c) OpenStreetMap contributors</p><p><b>sachsen.map</b>:<br>Map data (c) OpenStreetMap contributors</p><p><b>world.map</b>:<br>mapsforge-map-writer-dev-SNAPSHOT</p>
  - Theme: 

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Not logged in (Anmeldung…)
- Geocaching.com date format: dd.MM.yyyy
- Routing: external / connection available: true / BRouter installed: true
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (2,0 GB free) v2 internal isDir(6 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (2,0 GB free) v2 external non-removable isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (2,0 GB free) v2 external non-removable isDir(355 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (2,0 GB free) v2 internal isDir(0 entries)
- Public Folders: #11
  - BASE: /cgeo (Benutzerdefiniert)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:58, dirs:25, totalFileSize:2,9 GB, topLevel(7):[gpx/;field-notes/;logfiles/;backup/;GeocachePhotos/;maps/;routing/], free space: 2,0 GB, files on device: 12925952)
  - OFFLINE_MAPS: /cgeo/maps (Standard)[/cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps, Av:true, files:14, dirs:1, totalFileSize:2,8 GB, topLevel(8):[austria.map;_themes/;hessen.map;world.map;sachsen.map;Deutschland.map;hessen.map-cgeo.txt;sachsen.map-cgeo.txt], free space: 2,0 GB, files on device: 12925952)
  - OFFLINE_MAP_THEMES: /cgeo/maps/_themes (Standard)[/cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps%2F_themes, Av:true, files:7, dirs:0, totalFileSize:4,5 MB, topLevel(7):[paws_tourist.zip;paws_mix.zip;paws_4.zip;winter_paws_4.zip;paws_cyclist.zip;Elevate.zip;Elevate.zip-cgeo.txt], free space: 2,0 GB, files on device: 12925952)
  - LOGFILES: /cgeo/logfiles (Standard)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:8, dirs:0, totalFileSize:97,7 KB, topLevel(8):[log-properties.txt.useItCarefully;logcat_2020-08-31_15-52.txt;logcat_2020-11-30_16-51.txt;logcat_2020-12-07_09-32.txt;logcat_2020-12-07_09-33.txt;logcat_12-11-2020_07-46-14.txt;logcat_2020-12-11_07-52.txt;logcat_2020-12-23_13-40.txt], free space: 2,0 GB, files on device: 12925952)
  - GPX: /cgeo/gpx (Standard)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:10, dirs:0, totalFileSize:11,2 MB, topLevel(10):[Meli Tour.gpx;export_2020-12-23.gpx;route_2020-12-23_13-52-29.gpx;export_2020-12-23_2.gpx;export_2021-01-11.gpx;Geocaching Fahrradtour 20-02-2021.gpx;route-2021-02-20-19-17-37-2.gpx;meli_tour_peter.gpx;Radtour_mit_Peter_25-02-2021.gpx;2._Tour_mit_Peter.gpx], free space: 2,0 GB, files on device: 12925952)
  - BACKUP: /cgeo/backup (Standard)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:26, dirs:13, totalFileSize:105,0 MB, topLevel(first 10 of 13):[2021-02-14 21-40/;2021-02-19 10-59/;2021-03-23 09-01/;2021-02-06 10-05/;2021-01-16 18-06/;2021-01-19 18-39/;2021-01-05 12-50/;2021-02-07 21-31/;2021-01-05 17-14/;2020-10-21 14-24 (last without database patch)/], free space: 2,0 GB, files on device: 12925952)
  - FIELD_NOTES: /cgeo/field-notes (Standard)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, topLevel(0):[], free space: 2,0 GB, files on device: 12925952)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Standard)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:3, totalFileSize:0 B, topLevel(1):[M/], free space: 2,0 GB, files on device: 12925952)
  - ROUTING_BASE: /cgeo/routing (Standard)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:0, dirs:1, totalFileSize:0 B, topLevel(1):[segments4/], free space: 2,0 GB, files on device: 12925952)
  - ROUTING_TILES: /cgeo/routing/segments4 (Standard)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, topLevel(0):[], free space: 2,0 GB, files on device: 12925952)
  - TEST_FOLDER: [Veraltet]/data/user/0/cgeo.geocaching/files/unittest (Standard)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, topLevel(0):[], free space: 2,0 GB, files on device: -1)
- Map render theme path: 
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (25. März, 10:36):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v94, Size:8,4 MB) on system internal storage
--- End of system information ---
 
```

**Comment by moving-bits** [comment]
Hm, crashing here as well in the emulator, but with a different exception:

```
2021-03-28 10:52:07.276 31555-31555/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 31555
    java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.maps.google.v2.GoogleMapActivity}: java.lang.IllegalStateException: Already attached
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalStateException: Already attached
        at androidx.fragment.app.FragmentManagerImpl.attachController(FragmentManagerImpl.java:2563)
        at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:116)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:284)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
        at cgeo.geocaching.maps.google.v2.GoogleMapActivity.superOnCreate(GoogleMapActivity.java:134)
        at cgeo.geocaching.maps.AbstractMap.onCreate(AbstractMap.java:55)
        at cgeo.geocaching.maps.CGeoMap.onCreate(CGeoMap.java:536)
        at cgeo.geocaching.maps.google.v2.GoogleMapActivity.onCreate(GoogleMapActivity.java:67)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
[...]
```

This would more point into the direction of #10049 (changes to the map activities as first step of unifying styles and rework of themes). I'll debug into this.

**Comment by moving-bits** [comment]
Ok, got behind the first crash and reached the second. First crash comes from calling `onCreate()` twice, which seems to be introduced with #10251 - we need to check the add `super.onXXX()` calls whether they lead to such a situation, and if so, remove them + add lint suppressions. (But as you got past this error without crashing, maybe this is system-specific or only happens in the emulator?)

Now for the second crash (with the exception posted initially here)...

**Comment by MagpieFourtyTwo** [comment]
Same over here. Do you need additional debug data?
Otherwise I would revert to yesterday's nightly.

**Comment by moving-bits** [comment]
Thanks, I think a have a path to follow. Looks like I need to rename the new internal routing service to not clash between internal and external. I'll investigate further...

**Comment by fm-sys** [comment]
> But as you got past this error without crashing, maybe this is system-specific or only happens in the emulator?

I'm using the mapsforge offline map. The `super.onXXX()` is probably only happening at the Google map. When I switch to Google in the settings, the crash is indeed a different one:

```
FATAL EXCEPTION: main
Process: cgeo.geocaching, PID: 3454
java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.maps.google.v2.GoogleMapActivity}: java.lang.IllegalStateException: Already attached
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: java.lang.IllegalStateException: Already attached
	at androidx.fragment.app.FragmentManagerImpl.attachController(FragmentManagerImpl.java:2563)
	at androidx.fragment.app.FragmentController.attachHost(FragmentController.java:116)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:284)
	at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
	at cgeo.geocaching.maps.google.v2.GoogleMapActivity.superOnCreate(GoogleMapActivity.java:134)
	at cgeo.geocaching.maps.AbstractMap.onCreate(AbstractMap.java:55)
	at cgeo.geocaching.maps.CGeoMap.onCreate(CGeoMap.java:536)
	at cgeo.geocaching.maps.google.v2.GoogleMapActivity.onCreate(GoogleMapActivity.java:67)
	at android.app.Activity.performCreate(Activity.java:8086)
	at android.app.Activity.performCreate(Activity.java:8074)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
	... 11 more
```
