### ISSUE TITLE
c:geo "Forbidden" login at GCConnector

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#10339]
Currently the login does not work.
In such situation c:geo should catch the exception.

Currently:
~~~
2021-04-05 16:10:54.803 27947-28577/cgeo.geocaching W/cgeo: [network--5] parallelCombineActive: swallowing error from connector cgeo.geocaching.connector.gc.GCConnector@522ca7c
    java.lang.RuntimeException: java.io.IOException: request was not successful: Response{protocol=http/1.1, code=403, message=Forbidden, url=https://www.geocaching.com/account/oauth/token}
        at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
        at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
        at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3645)
        at cgeo.geocaching.connector.gc.GCWebAPI.searchMap(GCWebAPI.java:425)
        at cgeo.geocaching.connector.gc.GCMap.searchPlayMapByViewport(GCMap.java:133)
        at cgeo.geocaching.connector.gc.GCMap.searchByViewport(GCMap.java:105)
        at cgeo.geocaching.connector.gc.GCConnector.searchByViewport(GCConnector.java:268)
        at cgeo.geocaching.connector.ConnectorFactory.lambda$searchByViewport$0(ConnectorFactory.java:360)
        at cgeo.geocaching.connector.-$$Lambda$ConnectorFactory$-tY22muaGuR_0LpEE7Hz1E8smAs.apply(Unknown Source:4)
        at cgeo.geocaching.SearchResult.lambda$null$0(SearchResult.java:327)
        at cgeo.geocaching.-$$Lambda$SearchResult$e-ztiXGWtwcO9WMhd9XE-kd_qhc.call(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:47)
        at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5330)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.io.IOException: request was not successful: Response{protocol=http/1.1, code=403, message=Forbidden, url=https://www.geocaching.com/account/oauth/token}
        at cgeo.geocaching.network.Network.lambda$static$6(Network.java:621)
        at cgeo.geocaching.network.-$$Lambda$Network$HJwZsCLFMmiISrdxtajFdFJJscU.apply(Unknown Source:2)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:77)
        at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
        at cgeo.geocaching.utils.RxOkHttpUtils$1.onResponse(RxOkHttpUtils.java:48)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2021-04-05 16:11:00.621 27947-28448/cgeo.geocaching W/System: A resource failed to call response.body().close(). 
~~~

**Comment by Lineflyer** [comment]
> In such situation c:geo should catch the exception.

Let me add: ...and present a proper non-teccy error message to the user.
