### ISSUE TITLE
Exported position history is cut off

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10331]
From support mail for 2021.03.28-RC:

- I try to export my position history which is shown completely on the screen
- The first try only contains 120kB and not the full track
- The sedond try contains only 80kB of the track
- Both files end in the middle of a line, they seem cut off

---

Did not try to reproduce yet as I don't have a sufficient history on my device

Logs show countless entries like this (but might be unrelated?):
```
04-04 20:51:53.469 25814 25814 W cgeo    : java.lang.NullPointerException: Attempt to invoke virtual method 'float cgeo.geocaching.location.Geopoint.distanceTo(cgeo.geocaching.models.ICoordinates)' on a null object reference
04-04 20:51:53.469 25814 25814 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.getClosestDistanceInM(AbstractCachesOverlay.java:405)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.getClosestDistanceInM(CachesBundle.java:335)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.NewMap$UpdateLoc.repaintPositionOverlay(NewMap.java:1271)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.NewMap$UpdateLoc.updateGeoDir(NewMap.java:1234)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at cgeo.geocaching.sensors.GeoDirHandler.updateGeoDirData(GeoDirHandler.java:70)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at cgeo.geocaching.sensors.GeoDirHandler.lambda$start$0(GeoDirHandler.java:109)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at cgeo.geocaching.sensors.GeoDirHandler.lambda$start$0$GeoDirHandler(Unknown Source:0)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at cgeo.geocaching.sensors.-$$Lambda$GeoDirHandler$iBu37b5fsSLKy3w8O-YfiBttMp8.accept(Unknown Source:4)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.operators.flowable.AbstractBackpressureThrottlingSubscriber.drain(AbstractBackpressureThrottlingSubscriber.java:124)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onNext(FlowableOnBackpressureLatest.java:41)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:56)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at android.os.Handler.handleCallback(Handler.java:883)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at android.os.Looper.loop(Looper.java:237)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:8167)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
04-04 20:51:53.469 25814 25814 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
04-04 20:51:54.065 25814 25814 W cgeo    : [main] Failed to update location
04-04 20:51:54.065 25814 25814 W cgeo    : java.lang.NullPointerException: Attempt to invoke virtual method 'float cgeo.geocaching.location.Geopoint.distanceTo(cgeo.geocaching.models.ICoordinates)' on a null object reference
04-04 20:51:54.065 25814 25814 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.getClosestDistanceInM(AbstractCachesOverlay.java:405)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.getClosestDistanceInM(CachesBundle.java:335)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.NewMap$UpdateLoc.repaintPositionOverlay(NewMap.java:1271)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.NewMap$UpdateLoc.updateGeoDir(NewMap.java:1234)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at cgeo.geocaching.sensors.GeoDirHandler.updateGeoDirData(GeoDirHandler.java:70)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at cgeo.geocaching.sensors.GeoDirHandler.lambda$start$0(GeoDirHandler.java:109)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at cgeo.geocaching.sensors.GeoDirHandler.lambda$start$0$GeoDirHandler(Unknown Source:0)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at cgeo.geocaching.sensors.-$$Lambda$GeoDirHandler$iBu37b5fsSLKy3w8O-YfiBttMp8.accept(Unknown Source:4)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.operators.flowable.AbstractBackpressureThrottlingSubscriber.drain(AbstractBackpressureThrottlingSubscriber.java:124)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onNext(FlowableOnBackpressureLatest.java:41)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:56)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at android.os.Handler.handleCallback(Handler.java:883)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at android.os.Looper.loop(Looper.java:237)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:8167)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
04-04 20:51:54.065 25814 25814 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
04-04 20:51:54.573 25814 25814 W cgeo    : [main] Failed to update location
04-04 20:51:54.573 25814 25814 W cgeo    : java.lang.NullPointerException: Attempt to invoke virtual method 'float cgeo.geocaching.location.Geopoint.distanceTo(cgeo.geocaching.models.ICoordinates)' on a null object reference
04-04 20:51:54.573 25814 25814 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.getClosestDistanceInM(AbstractCachesOverlay.java:405)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.getClosestDistanceInM(CachesBundle.java:335)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.NewMap$UpdateLoc.repaintPositionOverlay(NewMap.java:1271)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.NewMap$UpdateLoc.updateGeoDir(NewMap.java:1234)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at cgeo.geocaching.sensors.GeoDirHandler.updateGeoDirData(GeoDirHandler.java:70)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at cgeo.geocaching.sensors.GeoDirHandler.lambda$start$0(GeoDirHandler.java:109)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at cgeo.geocaching.sensors.GeoDirHandler.lambda$start$0$GeoDirHandler(Unknown Source:0)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at cgeo.geocaching.sensors.-$$Lambda$GeoDirHandler$iBu37b5fsSLKy3w8O-YfiBttMp8.accept(Unknown Source:4)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.subscribers.LambdaSubscriber.onNext(LambdaSubscriber.java:65)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.operators.flowable.AbstractBackpressureThrottlingSubscriber.drain(AbstractBackpressureThrottlingSubscriber.java:124)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableOnBackpressureLatest$BackpressureLatestSubscriber.onNext(FlowableOnBackpressureLatest.java:41)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.operators.flowable.FlowableFromObservable$SubscriberObserver.onNext(FlowableFromObservable.java:56)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at io.reactivex.rxjava3.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:123)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at android.os.Handler.handleCallback(Handler.java:883)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at android.os.Looper.loop(Looper.java:237)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:8167)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
04-04 20:51:54.573 25814 25814 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by Lineflyer** [comment]
The user sent us example exports and indeed they are cut off, e.g. it ends with:
```
      <trkpt lat=3D"48.938447" lon=3D"9.0852556">
        <ele>268.96</ele>
        <time>2021-04-04T16:30:52Z</time>
      </trkpt>
      <trkpt la
```

**Comment by bekuno** [comment]
The NPE are duplicates to #10071 and #10307 User 1.

Very strange that the position history list should include values without position data.
Is the cutoff really with `<trkpt la`, not `<trkpt lat=`?

**Comment by Lineflyer** [comment]
Yes, its plainly cutoff in the middle. Other files are cut off at other random places, e.g.:
```
      <trkpt lat=3D"48.9387078" lon=3D"9.0854118">
        <ele>265.01</ele>
        <time>2021-04-04T16:31:13Z</time>
      </trkpt>
      <trkpt lat=3D"48.938792" lon=3D"9.0854887">
        <ele>266.44</ele>
        <time>2021-04-04T16:31
```

Seems more to be a file writing issue, than a data issue.

**Comment by Lineflyer** [comment]
I was meanwhile able to reproduce this issue.
I did nothing more than switching on the position history track and used c:geo on the weekend.
Today I exported the resulting track, the file is 123kB and looking into it, it is just cut off at the end. 
```
      <trkpt lat="51.4062216" lon="6.3335685">
        <ele>76.65</ele>
        <time>2021-04-10T14:26:33Z</ti
´´´

In two consecutive exports the file is totally identical (despite the creation date in its metadata and name part) and cut off at the same place.

@moving-bits 
Ideas? Can you reproduce it?

**Comment by moving-bits** [comment]
Hm, need to look into it more deeply:

Just did an export on current released version and got a 720kB file, non-truncated (history length is set to max. 5000 points for me). Then I imported the related database to the emulator and did the same export again, and the exported file got truncated app. 20kB too early. But no error messages in the log :-(

**Comment by moving-bits** [comment]
This is strange. I've added a couple of `try/catch` statements, and it always reported an `Stream closed` error. My first idea was whether the `BufferedWriter` somehow got closed before the underlying `OutputStream` had a chance to flush it's buffer, but that did not change anything.

In the end I've ended up unfolding the three output classes, and doing manual close handling instead of Java-internal automatic resource closing, and now it works in the emulator!

After some more testing it seems to boil down to either use automatic resource management or not:
```
BufferedWriter writer = null;
OutputStream os = null;
try {
    os = ContentStorage.get().openForWrite(uri);
    if (os == null) {
        return null;
    }
    try {
        writer = new BufferedWriter(new OutputStreamWriter(os, StandardCharsets.UTF_8));
        final XmlSerializer gpx = new KXmlSerializer();
        ...
    } catch (final IOException e) {
        // delete partial GPX file on error
        Log.e("IOException on trail export: " + e.getMessage());
        ContentStorage.get().delete(uri);
        return null;
    } finally {
        IOUtils.closeQuietly(writer);
        IOUtils.closeQuietly(os);
    }
} catch (final Exception e) {
    Log.e("Exception on trail export: " + e.getMessage());
}
```

instead of

```
BufferedWriter writer = null;
try (OutputStream os = ContentStorage.get().openForWrite(uri)) {
    if (os == null) {
        return null;
    }
    writer = new BufferedWriter(new OutputStreamWriter(os, StandardCharsets.UTF_8));
    final XmlSerializer gpx = new KXmlSerializer();
    ...
} catch (final IOException e) {
    // delete partial GPX file on error
    ContentStorage.get().delete(uri);
    return null;
} finally {
    IOUtils.closeQuietly(writer);
}
```

@eddiemuc 
Do you have any idea if this could be the actual cause, and whether this is SAF-related?

**Comment by eddiemuc** [comment]
No idea what happens here. But if it works with explicit resource closing I suggest leaving it like this

**Comment by moving-bits** [comment]
Ok, thanks for cross-checking. Will prepare a PR then.

**Comment by eddiemuc** [comment]
One idea I have now:
Maybe in code with auto-close, Java sometimes closes writer first (which internally closes also os), then auto-close tries to close is again which leads to the observed error.

But this is just a wild guess after looking on the code snippet. Maybe auto-close is not such a great feature after all...

**Comment by Lineflyer** [comment]
It seems not to happen with other files we write (e.g. exported caches as GPX or field notes). Maybe you could compare the code.

**Comment by moving-bits** [comment]
Checked a few other exports. Some do not write files to the local storage, for the others it's undecided: `IndividualRouteExport` and `FieldNotesExport` works the same way as the "fixed" `TrailHistoryExport` (manually closing file resources), whereas the `GpxExport` works the same way `TrailHistoryExport` did before (auto-closing). So coming from 2:2 it's now a 1:3. Strange...
But anyway, #10331 should not harm anything, so we can give it a try.
