### ISSUE TITLE
Crash after refreshing subset of a list of caches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10374]
## Bug description 

From support mail:
The user refreshes a filtered list of caches. If he tries to scroll through the list after refresh the app crashes

### Steps to reproduce the problem

- Open list of many caches (scrolling needed)
- Apply a filter (user filtered for last update > 7 days ago)
- Refresh selected
- After refresh has been completed, scroll down or up through the list

### Actual result after these steps 

In a high percentage of tries, c:geo crashes (return to main menu or dies completely)

### Expected result after these steps 

Normal list functionality

## c:geo version 

2021.04.11-RC

## Reproducible 

Not clearly, but happens in high percentage of tries for the user. 

## System information 

```
--- System information ---
c:geo version: 2021.04.11-RC

Device:
-------
- Device type: SM-A705FN (a70qeea, samsung)
- Android version: 10
- Android build: QP1A.190711.020.A705FNXXU5CUA7
- Sailfish OS detected: false
- Google Play services: disabled - 21.09.15 (120400-361652764)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: orientation

Program settings:
-------
- Hide caches: own/found archived
- Hide waypoints: original visited
- Set language: de_AT (system default)
- System date format: dd.MM.yy
- Debug mode active: no
- Live map mode: false
- Global filter: display all caches
- Last backup: 2. Apr., 18:50
- Routing mode: Gehen
- Map: Austria_200403 (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:0000-0000:OfflineMaps/Austria_200403.map
  - Atts: (C) 2007-2020 OpenMaps.eu
  - Theme: Elevate.xml

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
- Geocaching.com date format: dd.MM.yyyy
- BRouter installed: false / connection available: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (66,2 GB free) v2 internal isDir(11 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (66,2 GB free) v2 external non-removable isDir(5 entries)
- Geocache data: /storage/0000-0000/Android/data/cgeo.geocaching/files/GeocacheData (1,9 GB free) v2 external removable isDir(25658 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (66,2 GB free) v2 internal isDir(0 entries)
- Public Folders: #9
  - BASE: /cgeo (Benutzerdefiniert)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=15, dirs:>=6, totalFileSize:>=589,5 MB, topLevel(5):[backup/;gpx/;logfiles/;GeocachePhotos/;field-notes/], free space: 66,2 GB, files on device: 3645440)
  - OFFLINE_MAPS: SD-Karte/OfflineMaps (Benutzerdefiniert)[SD-Karte/OfflineMaps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineMaps::]] (Uri: content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineMaps/document/0000-0000%3AOfflineMaps, Av:true, files:14, dirs:0, totalFileSize:3,9 GB, topLevel(first 10 of 14):[montenegro.poi;slovenia.poi;slovenia_190228.map;austria.poi;austria_190401.map;czech_republic.map;germany.map;Austria_200403.map;slovakia.map;bosnia-herzegovina.poi], free space: 1,9 GB, files on device: 0)
  - OFFLINE_MAP_THEMES: SD-Karte/OfflineThemes (Benutzerdefiniert)[SD-Karte/OfflineThemes[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineThemes::]] (Uri: content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineThemes/document/0000-0000%3AOfflineThemes, Av:true, files:800, dirs:3, totalFileSize:4,0 MB, topLevel(first 10 of 11):[Elevate/;Elements.xml;Elevate.xml;read_me_elevate.txt;ele_res/;GC94CYH.gpx;ZZ1020_2.gpx;ZZ1020.gpx;GC3A51M.gpx;GC94CYH_2.gpx], free space: 1,9 GB, files on device: 0)
  - LOGFILES: /cgeo/logfiles (Standard)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:7, dirs:0, totalFileSize:3,3 MB, topLevel(7):[logcat-2021-04-01-18-10-55-2.txt;logcat-2021-04-05-07-23-29-2.txt;logcat-2021-04-11-21-33-19-2.txt;logcat-2021-04-06-22-11-22-2.txt;logcat-2021-04-11-21-29-08-2.txt;logcat-2021-04-01-20-45-54-2.txt;logcat-2021-04-08-21-45-01-2.txt], free space: 66,2 GB, files on device: 3645440)
  - GPX: SD-Karte/OfflineThemes (Benutzerdefiniert)[SD-Karte/OfflineThemes[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineThemes::]] (Uri: content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineThemes/document/0000-0000%3AOfflineThemes, Av:true, files:800, dirs:3, totalFileSize:4,0 MB, topLevel(first 10 of 11):[Elevate/;Elements.xml;Elevate.xml;read_me_elevate.txt;ele_res/;GC94CYH.gpx;ZZ1020_2.gpx;ZZ1020.gpx;GC3A51M.gpx;GC94CYH_2.gpx], free space: 1,9 GB, files on device: 0)
  - BACKUP: /cgeo/backup (Standard)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:2, dirs:1, totalFileSize:585,6 MB, topLevel(1):[2021-04-02 18-50/], free space: 66,2 GB, files on device: 3645440)
  - FIELD_NOTES: /cgeo/field-notes (Standard)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:215, dirs:0, totalFileSize:155,1 KB, topLevel(first 10 of 215):[20201021191549.txt;20201212171827.txt;20200625141328.txt;20200208184143.txt;20200731215004.txt;20200612230855.txt;20200111112119.txt;20210330181914.txt;20200507141420.txt;20201113100020.txt], free space: 66,2 GB, files on device: 3645440)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Standard)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, topLevel(0):[], free space: 66,2 GB, files on device: 3645440)
  - TEST_FOLDER: [Veraltet]/data/user/0/cgeo.geocaching/files/unittest (Standard)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, topLevel(0):[], free space: 66,2 GB, files on device: -1)
- Map render theme path: Elevate.xml
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #3
  - content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineThemes (31. März, 13:28):RW
  - content://com.android.externalstorage.documents/tree/0000-0000%3AOfflineMaps (31. März, 13:27):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (31. März, 13:27):RW
- Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (v94, Size:603,3 MB) on user storage
-Settings: v5, Count:160
--- End of system information ---
```

## Additional context 

Crash in log:
```
04-08 21:43:39.265 14924 14924 E AndroidRuntime: FATAL EXCEPTION: main
04-08 21:43:39.265 14924 14924 E AndroidRuntime: Process: cgeo.geocaching, PID: 14924
04-08 21:43:39.265 14924 14924 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=1887; index=1891
04-08 21:43:39.265 14924 14924 E AndroidRuntime: 	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:380)
04-08 21:43:39.265 14924 14924 E AndroidRuntime: 	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:393)
04-08 21:43:39.265 14924 14924 E AndroidRuntime: 	at org.mapsforge.map.layer.Layers.get(Layers.java:336)
04-08 21:43:39.265 14924 14924 E AndroidRuntime: 	at org.mapsforge.map.android.input.TouchGestureHandler.onSingleTapConfirmed(TouchGestureHandler.java:263)
04-08 21:43:39.265 14924 14924 E AndroidRuntime: 	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:345)
04-08 21:43:39.265 14924 14924 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-08 21:43:39.265 14924 14924 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
04-08 21:43:39.265 14924 14924 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
04-08 21:43:39.265 14924 14924 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-08 21:43:39.265 14924 14924 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
04-08 21:43:39.265 14924 14924 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: FATAL EXCEPTION: main
04-09 19:19:37.703 26805 26805 E AndroidRuntime: Process: cgeo.geocaching, PID: 26805
04-09 19:19:37.703 26805 26805 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getBottom()' on a null object reference
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.widget.ListView.fillDown(ListView.java:840)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.widget.ListView.fillGap(ListView.java:801)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:8315)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.widget.ListView.trackMotionScroll(ListView.java:2155)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:4945)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.widget.AbsListView.onTouchMove(AbsListView.java:6632)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:6448)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.widget.ListView.onTouchEvent(ListView.java:1721)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:14368)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3857)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:6365)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:770)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1952)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:4038)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:728)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:14636)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6582)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6360)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5849)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5815)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5971)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5823)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6028)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5849)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5815)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5823)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9032)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8889)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8842)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9169)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:183)
04-09 19:19:37.703 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9109)
04-09 19:19:37.704 26805 26805 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9196)
04-09 19:19:37.704 26805 26805 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
04-09 19:19:37.704 26805 26805 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
04-09 19:19:37.704 26805 26805 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:725)
04-09 19:19:37.704 26805 26805 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
04-09 19:19:37.704 26805 26805 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
04-09 19:19:37.704 26805 26805 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-09 19:19:37.704 26805 26805 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
04-09 19:19:37.704 26805 26805 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
04-09 19:19:37.704 26805 26805 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-09 19:19:37.704 26805 26805 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
04-09 19:19:37.704 26805 26805 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: FATAL EXCEPTION: main
04-09 19:26:25.459 30032 30032 E AndroidRuntime: Process: cgeo.geocaching, PID: 30032
04-09 19:26:25.459 30032 30032 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getTop()' on a null object reference
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.widget.ListView.fillUp(ListView.java:874)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.widget.ListView.fillGap(ListView.java:810)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.widget.AbsListView.trackMotionScroll(AbsListView.java:8315)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.widget.ListView.trackMotionScroll(ListView.java:2155)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.widget.AbsListView.scrollIfNeeded(AbsListView.java:4945)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.widget.AbsListView.onTouchMove(AbsListView.java:6632)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:6448)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.widget.ListView.onTouchEvent(ListView.java:1721)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:14368)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3857)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3535)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:6365)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3863)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:3551)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:770)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1952)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:4038)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:728)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:14636)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6582)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6360)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5849)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5815)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5971)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5823)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6028)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5849)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5815)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5823)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5796)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9032)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8889)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8842)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9169)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:194)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:183)
04-09 19:26:25.459 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:9109)
04-09 19:26:25.460 30032 30032 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:9196)
04-09 19:26:25.460 30032 30032 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
04-09 19:26:25.460 30032 30032 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
04-09 19:26:25.460 30032 30032 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:725)
04-09 19:26:25.460 30032 30032 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
04-09 19:26:25.460 30032 30032 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
04-09 19:26:25.460 30032 30032 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-09 19:26:25.460 30032 30032 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
04-09 19:26:25.460 30032 30032 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
04-09 19:26:25.460 30032 30032 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-09 19:26:25.460 30032 30032 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
04-09 19:26:25.460 30032 30032 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by eddiemuc** [comment]
Crash was created because after refresh the list was not valid any more (after fresh update, "last update > 7 days" is no longer true for the updated caches).
Fixed with PR #11396 by reloading/filtering list after refresh run
