### ISSUE TITLE
App not repsonsive / some maps not readable

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10418]
This is still under investigation on support mail.

A user reported, that using the offline map in 2021.04.15 is very slow / unresponsive for him.
Themes are not in use.

Looking at his log I do see this:
```
04-19 12:06:32.165 31269 31269 E cgeo    : [main] Problem opening map file 'content://com.android.externalstorage.documents/tree/0000-0000%3AKarten1/document/0000-0000%3AKarten1%2F._germany.map'
04-19 12:06:32.165 31269 31269 E cgeo    : org.mapsforge.map.reader.header.MapFileException: invalid magic byte: À€À€À€À€Mac OS X    
04-19 12:06:32.165 31269 31269 E cgeo    : 	at org.mapsforge.map.reader.MapFile.<init>(MapFile.java:293)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.createMapFile(MapsforgeMapProvider.java:334)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.readAttributionFromMapFileIfValid(MapsforgeMapProvider.java:304)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.getAttributionIfValidFor(MapsforgeMapProvider.java:286)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.isValidMapFile(MapsforgeMapProvider.java:272)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.lambda$updateOfflineMaps$1(MapsforgeMapProvider.java:358)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.-$$Lambda$MapsforgeMapProvider$dNvFadrqDeK3MNo397SkHkUf-nQ.call(Unknown Source:2)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.utils.CollectionStream.filter(CollectionStream.java:102)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.updateOfflineMaps(MapsforgeMapProvider.java:358)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.updateOfflineMaps(MapsforgeMapProvider.java:349)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.lambda$new$0(MapsforgeMapProvider.java:65)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.lambda$new$0$MapsforgeMapProvider(Unknown Source:0)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.-$$Lambda$MapsforgeMapProvider$nXBLTXaiBuevlXAmqjPIWvAbJY0.accept(Unknown Source:4)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.storage.PersistableFolder.notifyChanged(PersistableFolder.java:105)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.storage.PersistableFolder.setUserDefinedFolder(PersistableFolder.java:136)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.storage.ContentStorage.setUserDefinedFolder(ContentStorage.java:478)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.storage.ContentStorageActivityHelper.finalizePersistableFolderSelection(ContentStorageActivityHelper.java:391)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.storage.ContentStorageActivityHelper.continuePersistableFolderSelectionCopyMove(ContentStorageActivityHelper.java:376)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.storage.ContentStorageActivityHelper.lambda$continuePersistableFolderSelectionCheckFoldersAreEqual$6(ContentStorageActivityHelper.java:353)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.storage.ContentStorageActivityHelper.lambda$continuePersistableFolderSelectionCheckFoldersAreEqual$6$ContentStorageActivityHelper(Unknown Source:0)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at cgeo.geocaching.storage.-$$Lambda$ContentStorageActivityHelper$HybJDYdFrJ7iADLvGqtV5Ir_ckQ.onClick(Unknown Source:12)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:184)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at android.os.Looper.loop(Looper.java:214)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:7073)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
04-19 12:06:32.165 31269 31269 E cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)


04-19 12:05:54.406 31269 31269 E cgeo    : [main] Problem opening map file 'content://com.android.externalstorage.documents/tree/0000-0000%3AKarten/document/0000-0000%3AKarten%2Fgermanyoffline.map'
04-19 12:05:54.406 31269 31269 E cgeo    : org.mapsforge.map.reader.header.MapFileException: invalid file size: 2470729399
04-19 12:05:54.406 31269 31269 E cgeo    : 	at org.mapsforge.map.reader.MapFile.<init>(MapFile.java:293)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.createMapFile(MapsforgeMapProvider.java:334)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.readAttributionFromMapFileIfValid(MapsforgeMapProvider.java:304)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.getAttributionIfValidFor(MapsforgeMapProvider.java:286)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.isValidMapFile(MapsforgeMapProvider.java:272)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.lambda$updateOfflineMaps$1(MapsforgeMapProvider.java:358)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.-$$Lambda$MapsforgeMapProvider$dNvFadrqDeK3MNo397SkHkUf-nQ.call(Unknown Source:2)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.utils.CollectionStream.filter(CollectionStream.java:102)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.updateOfflineMaps(MapsforgeMapProvider.java:358)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.updateOfflineMaps(MapsforgeMapProvider.java:349)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.<init>(MapsforgeMapProvider.java:68)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.<init>(MapsforgeMapProvider.java:48)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$Holder.<clinit>(MapsforgeMapProvider.java:72)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$Holder.access$100(MapsforgeMapProvider.java:71)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.getInstance(MapsforgeMapProvider.java:76)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.MapProviderFactory.<clinit>(MapProviderFactory.java:41)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.maps.MapProviderFactory.getMapSources(MapProviderFactory.java:68)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.settings.SettingsActivity.initMapSourcePreference(SettingsActivity.java:174)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.settings.SettingsActivity.initPreferences(SettingsActivity.java:135)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at cgeo.geocaching.settings.SettingsActivity.onCreate(SettingsActivity.java:103)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at android.app.Activity.performCreate(Activity.java:7327)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at android.app.Activity.performCreate(Activity.java:7318)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3096)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3259)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at android.os.Looper.loop(Looper.java:214)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:7073)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
04-19 12:05:54.406 31269 31269 E cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

I will first of all ask the user to check whether the affected files are not corrupted and ask him to remove/replace them.

This issue is only a reminder to myself, except someone else has a clue regarding the listed exceptions.

**Comment by moving-bits** [comment]
Maybe that's some Mac OS thing adding some special characters to the file? (IIRC Mac OS stores some resource info as a separate file in file systems like FAT, but integrated in the file in their own file system. Maybe it got confused while writing to the Android partition, thinking it was a Mac OS file system?)

**Comment by Lineflyer** [comment]
User did never reply. Assuming the files were corrupt and fixed by my question to redownload them.
