### ISSUE TITLE
Position freezes on mapsforge map / NPE on mapsforge

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10490]
## Bug description 

Reported by a user, that says this is a new bug appearing since 2021.04.15 for him

### Steps to reproduce the problem

- Open map
- Walk around

### Actual result after these steps 

- After some time of map usage the position icon freezes and is no longer moving
- Restart only helps

### Expected result after these steps 

Normal operation

## c:geo version 

2021.04.25

## Reproducible 

Not clearly

## System information 

```
--- System information ---
c:geo version: 2021.04.25

Device:
-------
- Device type: SM-A520F (a5y17ltexx, samsung)
- Available processors: 8
- Android version: 8.0.0
- Android build: R16NW.A520FXXUGCTKA
- Sailfish OS detected: false
- Google Play services: enabled - 21.12.13 (040408-367530751)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Hide caches: -
- Hide waypoints: -
- Set language: fr_FR (system default)
- System date format: dd/MM/y
- Debug mode active: no
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Global filter: display all caches
- Last backup: never
- Routing mode: Walk
- Map: Lorraine (hors-ligne)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:82AD-1914:Cartes/lorraine.map
  - Atts: mapsforge-map-writer-0.6.0-rc3
  - Theme: none

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Connecté) / PREMIUM
- Geocaching.com date format: dd/MM/yyyy
- BRouter installed: false / connection available: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (12,1 GB free) v2 internal isDir(9 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (12,1 GB free) v2 external non-removable isDir(5 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (12,1 GB free) v2 external non-removable isDir(308 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (12,1 GB free) v2 internal isDir(0 entries)
- Public Folders: #9
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=3, dirs:>=5, totalFileSize:>=2,6 MB, free space: 12,1 GB, files on device: 783360)
  - OFFLINE_MAPS: Carte SD/Cartes (User-Defined)[Carte SD/Cartes[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/82AD-1914%3ACartes::]] (Uri: content://com.android.externalstorage.documents/tree/82AD-1914%3ACartes/document/82AD-1914%3ACartes, Av:true, files:6, dirs:1, totalFileSize:292,9 MB, free space: 25,2 GB, files on device: 0)
  - OFFLINE_MAP_THEMES: Carte SD/Cartes/_themes (Default)[Carte SD/Cartes/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/82AD-1914%3ACartes::/_themes]] (Uri: content://com.android.externalstorage.documents/tree/82AD-1914%3ACartes/document/82AD-1914%3ACartes%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 25,2 GB, files on device: 0)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:2, dirs:0, totalFileSize:56,4 KB, free space: 12,1 GB, files on device: 783360)
  - GPX: /cgeo/gpx (User-Defined)[/cgeo/gpx[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx/document/primary%3Acgeo%2Fgpx, Av:true, files:1, dirs:0, totalFileSize:2,6 MB, free space: 12,1 GB, files on device: 783360)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 12,1 GB, files on device: 783360)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 12,1 GB, files on device: 783360)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 12,1 GB, files on device: 783360)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 12,1 GB, files on device: -1)
- Map render theme path:
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #3
  - content://com.android.externalstorage.documents/tree/82AD-1914%3ACartes (31 mars à 08:10):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (31 mars à 08:10):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx (31 mars à 08:10):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v94, Size:13,6 MB) on system internal storage
-Settings: v5, Count:127
--- End of system information ---
```

## Additional context 

Logfile sent by the user with his problem report contains one crash, not sure if related. Rest is nothing abnormal:
```
--------- beginning of crash
04-25 16:24:05.171 30689  5540 E AndroidRuntime: FATAL EXCEPTION: LayerManager
04-25 16:24:05.171 30689  5540 E AndroidRuntime: Process: cgeo.geocaching, PID: 30689
04-25 16:24:05.171 30689  5540 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getHeight()' on a null object reference
04-25 16:24:05.171 30689  5540 E AndroidRuntime: 	at org.mapsforge.map.android.graphics.AndroidBitmap.getHeight(AndroidBitmap.java:109)
04-25 16:24:05.171 30689  5540 E AndroidRuntime: 	at cgeo.geocaching.maps.mapsforge.v6.layers.PositionLayer.draw(PositionLayer.java:81)
04-25 16:24:05.171 30689  5540 E AndroidRuntime: 	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
04-25 16:24:05.171 30689  5540 E AndroidRuntime: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
```

**Comment by Lineflyer** [comment]
No follow up by the user, no further reports. Closing.
