### ISSUE TITLE
No app to handle OPEN_DOCUMENT_TREE

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10506]
## Bug description 

c:geo keeps crashing on base folder selection as it cannot find an app to handle `OPEN_DOCUMENT_TREE`
Thus thus the user cannot migrate.

I asked the user to install a even newer version which includes the fix for #10413 with no success.

### Steps to reproduce the problem

- Start c:geo
- Select base folder dialog shown
- User selects "Continue"

### Actual result after these steps 

Crash

### Expected result after these steps 

Dir chooser should open

## c:geo version 

2021.04.25
2021.04.27-RC (inofficial RC)

## Reproducible 

Yes, for this user

## System information 

Seems to be a rather rare Android car radio, but user said, c:geo was working good on that.

![grafik](https://user-images.githubusercontent.com/949669/116603533-50d9b700-a92d-11eb-8d77-86d248dd4833.png)

```
--- System information ---
c:geo version: 2021.04.27-RC

Device:
-------
- Device type: 8227L (full_8227L, ffkj)
- Available processors: 4
- Android version: 9
- Android build: full_8227L_demo-userdebug 8.1.0 O11019 1550113051 test-keys
- Sailfish OS detected: false
- Google Play services: enabled - 21.12.13 (040304-367530751)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: no
- Rotation vector sensor: absent
- Orientation sensor: absent
- Magnetometer & Accelerometer sensor: absent
- Direction sensor used: magnetometer & accelerometer

Program settings:
-------
- Hide caches: -
- Hide waypoints: -
- Set language: nl_NL (system default)
- System date format: dd-MM-yy
- Debug mode active: yes
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Global filter: display all caches
- Last backup: never
- Routing mode: Walk
- Map: Google: Map
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleMapSource
  - Atts: none
  - Theme: none

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Ingelogd) / PREMIUM
- Geocaching.com date format: dd/MM/yy
- BRouter installed: false / connection available: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (19,4 GB free) v2 internal isDir(7 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (19,4 GB free) v2 external non-removable isDir(6 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (19,4 GB free) v2 external non-removable isDir(2 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (19,4 GB free) v2 internal isDir(0 entries)
- Public Folders: #9
  - BASE: [Legacy]/storage/emulated/0/cgeo (Default)[/storage/emulated/0/cgeo[FILE#0:p-file:///storage/emulated/0/cgeo::]] (Uri: file:///storage/emulated/0/cgeo, Av:true, files:>=9, dirs:>=7, totalFileSize:>=15,2 MB, free space: 19,4 GB, files on device: -1)
  - OFFLINE_MAPS: [Legacy]/storage/emulated/0/cgeo/maps (Default)[/storage/emulated/0/cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/maps]] (Uri: file:///storage/emulated/0/cgeo/maps, Av:true, files:0, dirs:1, totalFileSize:0 B, free space: 19,4 GB, files on device: -1)
  - OFFLINE_MAP_THEMES: [Legacy]/storage/emulated/0/cgeo/maps/_themes (Default)[/storage/emulated/0/cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-file:///storage/emulated/0/cgeo::/maps/_themes]] (Uri: file:///storage/emulated/0/cgeo/maps/_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 19,4 GB, files on device: -1)
  - LOGFILES: [Legacy]/storage/emulated/0/cgeo/logfiles (Default)[/storage/emulated/0/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/logfiles]] (Uri: file:///storage/emulated/0/cgeo/logfiles, Av:true, files:9, dirs:0, totalFileSize:15,2 MB, free space: 19,4 GB, files on device: -1)
  - GPX: [Legacy]/storage/emulated/0/cgeo/gpx (Default)[/storage/emulated/0/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/gpx]] (Uri: file:///storage/emulated/0/cgeo/gpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 19,4 GB, files on device: -1)
  - BACKUP: [Legacy]/storage/emulated/0/cgeo/backup (Default)[/storage/emulated/0/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/backup]] (Uri: file:///storage/emulated/0/cgeo/backup, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 19,4 GB, files on device: -1)
  - FIELD_NOTES: [Legacy]/storage/emulated/0/cgeo/field-notes (Default)[/storage/emulated/0/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/field-notes]] (Uri: file:///storage/emulated/0/cgeo/field-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 19,4 GB, files on device: -1)
  - SPOILER_IMAGES: [Legacy]/storage/emulated/0/cgeo/GeocachePhotos (Default)[/storage/emulated/0/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-file:///storage/emulated/0/cgeo::/GeocachePhotos]] (Uri: file:///storage/emulated/0/cgeo/GeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 19,4 GB, files on device: -1)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 19,4 GB, files on device: -1)
- Map render theme path:
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #0
- Database: /data/user/0/cgeo.geocaching/databases/data (v94, Size:184,0 KB) on system internal storage
-Settings: v5, Count:107
--- End of system information ---
```

## Additional context 

```
04-29 21:00:34.668  2010  2010 E AndroidRuntime: FATAL EXCEPTION: main
04-29 21:00:34.668  2010  2010 E AndroidRuntime: Process: cgeo.geocaching, PID: 2010
04-29 21:00:34.668  2010  2010 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 (has extras) }
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1937)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4571)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4529)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at cgeo.geocaching.storage.ContentStorageActivityHelper.selectFolderInternal(ContentStorageActivityHelper.java:328)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at cgeo.geocaching.storage.ContentStorageActivityHelper.migratePersistableFolder(ContentStorageActivityHelper.java:212)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at cgeo.geocaching.InstallWizardActivity.requestBasefolder(InstallWizardActivity.java:426)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at cgeo.geocaching.InstallWizardActivity.lambda$S12dzTv1tNyVh49CWAcHgRWECHs(Unknown Source:0)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at cgeo.geocaching.-$$Lambda$InstallWizardActivity$S12dzTv1tNyVh49CWAcHgRWECHs.run(Unknown Source:2)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at cgeo.geocaching.InstallWizardActivity.lambda$setNavigation$8(InstallWizardActivity.java:297)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at cgeo.geocaching.-$$Lambda$InstallWizardActivity$qKYa72uUggZbUw_6eh42zWfcXVo.onClick(Unknown Source:2)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at android.view.View.performClick(View.java:6300)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:24941)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6529)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
04-29 21:00:34.668  2010  2010 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
04-29 21:05:13.879  4151  4151 E AndroidRuntime: FATAL EXCEPTION: main
04-29 21:05:13.879  4151  4151 E AndroidRuntime: Process: cgeo.geocaching, PID: 4151
04-29 21:05:13.879  4151  4151 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.OPEN_DOCUMENT_TREE flg=0x43 (has extras) }
04-29 21:05:13.879  4151  4151 E AndroidRuntime: 	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1937)
04-29 21:05:13.879  4151  4151 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1616)
04-29 21:05:13.879  4151  4151 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4571)
04-29 21:05:13.879  4151  4151 E AndroidRuntime: 	at android.app.Activity.startActivityForResult(Activity.java:4529)
04-29 21:05:13.879  4151  4151 E AndroidRuntime: 	at cgeo.geocaching.storage.ContentStorageActivityHelper.selectFolderInternal(ContentStorageActivityHelper.java:328)
04-29 21:05:13.879  4151  4151 E AndroidRuntime: 	at cgeo.geocaching.storage.ContentStorageActivityHelper.lambda$selectPersistableFolder$0(ContentStorageActivityHelper.java:192)
04-29 21:05:13.879  4151  4151 E AndroidRuntime: 	at cgeo.geocaching.storage.ContentStorageActivityHelper.lambda$selectPersistableFolder$0$ContentStorageActivityHelper(Unknown Source:0)
04-29 21:05:13.879  4151  4151 E AndroidRuntime: 	at cgeo.geocaching.storage.-$$Lambda$ContentStorageActivityHelper$tu9zPTlHm0nj4aCEw7OuEgcNbKo.onClick(Unknown Source:4)
04-29 21:05:13.879  4151  4151 E AndroidRuntime: 	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:166)
04-29 21:05:13.879  4151  4151 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-29 21:05:13.879  4151  4151 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
04-29 21:05:13.879  4151  4151 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6529)
04-29 21:05:13.879  4151  4151 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-29 21:05:13.879  4151  4151 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
04-29 21:05:13.879  4151  4151 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
04-29 21:05:25.419  4619  4619 W ViewRootImpl[MainActivity]: Dropping event due to root view being removed: MotionEvent { action=ACTION_MOVE, actionButton=0, id[0]=0, x[0]=-83.094635, y[0]=408.07983, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=6, eventTime=452323, downTime=452250, deviceId=1, source=0x1002 }
```

**Comment by Lineflyer** [comment]
As the user says, that other apps are capable of showing such a selection dialog, maybe this (really old) mitigation I found on heise.de?!

https://www.heise.de/developer/artikel/Hilfe-mein-Storage-Access-Framework-Provider-spinnt-2487053.html

**Comment by eddiemuc** [comment]
The heißen article references problems with Android versions before SDK21 (Android 4.4). Starting with SDK21, open_document_tree should be supported by the system according to android spec. I currently don't know any way to install or replace this.

Can the user name another app where this is working and where this is really a SAF dialog? Can he maybe try the backup folder selection in Signal (one of the few places I know SAF is already used)?

**Comment by Lineflyer** [comment]
I asked the user for now if he disabled or removed any system app and whether any version upgrade is available for his device.

**Comment by Lineflyer** [comment]
Additionally:
According to what a Google search told me, it might even be, that this device "8227L" is normally kind of locked Android device with a limited scope which can be unlocked to sideload apps. This could explain, why it not fully implements Android specs.

**Comment by eddiemuc** [comment]
> Additionally:
> According to what a Google search told me, it might even be, that this device "8227L" is normally kind of locked Android device with a limited scope which can be unlocked to sideload apps. This could explain, why it not fully implements Android specs.

Indeed...

**Comment by eddiemuc** [comment]
@Lineflyer can you ask the user whether he is able to attach an image (selected from storage) to the offline log?
I am.asking this because this would use another SAF intent in the background (OPEN_DOCUMENT instead of OPEN_DOCUMENT_TREE) and it would be interesting to see whether this one works.

**Comment by Lineflyer** [comment]
I asked the user to check image attachment and report back.

Additionally the user already contacted the manufacturer and asked for an update. I provided the exception text and a lik to this issue to forward to their support.

**Comment by Lineflyer** [comment]
The user reports, that for attaching an image the app "ES File Explorer" opens.

**Comment by bekuno** [comment]
> The user reports, that for attaching an image the app "ES File Explorer" opens.

There are many apps with this name. Which one does he mean?

**Comment by marinus53** [comment]
> 
> 
> > The user reports, that for attaching an image the app "ES File Explorer" opens.
> 
> There are many apps with this name. Which one does he mean?

the one from droid tech lab

**Comment by Lineflyer** [comment]
Thanks @marinus53 

@eddiemuc @bekuno That was a feedback from the user reporting this :)

**Comment by bekuno** [comment]
The ES File Explorer has the repo at https://github.com/samir-shaikh28/es-files-explorer.

**Comment by eddiemuc** [comment]
I am really very sorry, but I think there s nothing we can do here. Even if we would implement our own die selection dialog or an intent catching OPEN_DOCUMENT_TREE, we cannot grant permission to c:geo to use the selected folder. This can only be done by the Android system - at least that's my understanding (and otherwise the whole idea of scoped storage would not work).

@marinus53 is it possible for you to somehow upgrade the system?
Otherwise you should be able to continue using c:geo (wizard will unfortunately open on each start which might be a bit unnerving), but public files like maps will no longer be accessible to you once we switch to Android 11

**Comment by eddiemuc** [comment]
@marinus53

Assuming you're a technically more advanced user, I feel you deserve some more details on what is actually happening here.

First of all, right now, if you click away the wizard, c:geo should work as before, reading files from /cgeo and maps/themes/... from the folders you last selected in the respective settings.

Once we switch cgeo to Android 11 (which we are forced to by Google in late summer/autumn this year), and assuming you can't find a way to use OPEN_DOCUMENT_TREE, then the following will happen:
* When cgeo starts it will try to access /cgeo folder and use it if this is successful. I assume however this will then fail
* Cgeo will then try to use the systems Document folder. This might or might not work. If it works, cgeo will use it and you should be fine
* If this fails too cgeo will use a folder in its internal storage space (where also the database etc lies). I don't know if you are able to access this in your setup?

The above is for the base folder. You might need to set individual paths for maps, themes, gpx etc to "default" (this works without intent), then cgeo will look for those in subfolders of the base folder.

@moving-bits for situations like this it might make sense to have a Setting to disable the wizard, otherwise it will continue to pop up on every startup for the user. What do you think?

**Comment by Lineflyer** [comment]
> @moving-bits for situations like this it might make sense to have a Setting to disable the wizard, otherwise it will continue to pop up on every startup for the user. What do you think?

It will hopefully be a very rare case. At the moment I have only one such case (this one) on support.
If you want such a function, please hide it deep down. Otherwise some users might "accidentally" use it and end up with a non working c:geo if we switch to Android 11.

**Comment by marinus53** [comment]
Goodevening Lars,

 

Thank you and the github group for the work so far.

 

I have send the problem tot he chinese suplier, and they will look at it.

Maybe new firmware or an other solution I hope.

 

To make a switch to bypass the configuration wizard should be the last solution, while I am the only one.

Keep it in mind and wait, I will be back when I have an answer from China.

 

Greetings from Greece

 

 

Van: Lars ***@***.***> 
Verzonden: maandag 3 mei 2021 12:12
Aan: cgeo/cgeo ***@***.***>
CC: marinus53 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [cgeo/cgeo] No app to handle OPEN_DOCUMENT_TREE (#10506)

 

@moving-bits <https://github.com/moving-bits>  for situations like this it might make sense to have a Setting to disable the wizard, otherwise it will continue to pop up on every startup for the user. What do you think?

It will hopefully be a very rare case. At the moment I have only one such case (this one) on support.
If you want such a function, please hide it deep down. Otherwise some users might "accidentally" use it and end up with a non working c:geo if we switch to Android 11.

**Comment by moving-bits** [comment]
> > @moving-bits for situations like this it might make sense to have a Setting to disable the wizard, otherwise it will continue to pop up on every startup for the user. What do you think?
> 
> It will hopefully be a very rare case. At the moment I have only one such case (this one) on support.
> If you want such a function, please hide it deep down. Otherwise some users might "accidentally" use it and end up with a non working c:geo if we switch to Android 11.

We could implement such a switch, if needed, but in consideration of the second comment I would propose to do it "under the hood", meaning without GUI. So in case of need, the use could add a special setting's variable (with the help of support), which, if set to true, would suppress calling the wizard on startup.

**Comment by eddiemuc** [comment]
Agreed.

Btw, by manually editing the settings (with help of support) the user is also already able to select file-based directories on his device as public folders. If a file-based folder can be found on the device still accessible to c:geo with SAF enforced, it can be set this way.

**Comment by moving-bits** [comment]
So we don't need an extra switch for this edge case at all? Even better :-)

**Comment by eddiemuc** [comment]
> So we don't need an extra switch for this edge case at all? Even better :-)

Not sure. IIRC the wizard checks whether a stored uri is a "legacy" uri (means: a file Uri or a file path) and pops up if it is. So even when the user directly enters a file Uri/path in settings the wizard might pop up.

**Comment by Lineflyer** [comment]
@marinus53 
Any feedback from the chinese vendor?
We had no other such problems reported, so it seems a single case (or a somehow broken Android device).

Thus I would like to close without changes/workarounds anyway, but maybe you got a solution from the vendor, which we could document here.

**Comment by Lineflyer** [comment]
Closing due to lack of response and no plans/possibility for us to fix (as its simply a short coming of the device manufacturer.
