### ISSUE TITLE
cgeo.geocaching.downloader.DownloaderTest.testBRouterTiles failing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10553]
org.junit.ComparisonFailure: expected:<112[0]> but was:<112[1]>
at java.lang.reflect.Constructor.newInstance0(Native Method)
at cgeo.geocaching.downloader.DownloaderTest.testBRouterTiles(DownloaderTest.java:153)
at java.lang.reflect.Method.invoke(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at androidx.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:73)
at junit.framework.TestResult.run(TestResult.java:118)
at androidx.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:51)
at junit.framework.TestCase.run(TestCase.java:124)
at androidx.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:62)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at androidx.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:97)
at androidx.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:65)
at androidx.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:115)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)

**Comment by fm-sys** [comment]
AFAIK these routing tiles are 2x2 Latitudes/longitude (except these areas which only contain water) so the count should indeed not change. So it seems like this is not a false positive, but another element was recognized as routing tile (but I might be wrong)

**Comment by eddiemuc** [comment]
Looking at the url http://brouter.de/brouter/segments4/, I count 1121 files looking like routing tiles from me (all from entry E0_N10.rd5 at the top to W95_S5.rd5  at the bottom and NOT counting storageconfig.txt, 0_timestamps_are_map_snapshot_time_in_CET_timezone and the directory diff)

I guess a new routing tile really has appeared

**Comment by fm-sys** [comment]
Yes, you are right. Sorry for the confusion...

**Comment by moving-bits** [comment]
> The test checks the number of available brouter tiles on a specific Url and expects it to be 1120. But there are in fact 1121 brouter tiles on the page right now.
> 
> @moving-bits does it make sense to check tile count against a hard-coded number?

Yes and no. Yes, because I want a safeguard to detect any relevant website changes that would make the downloader fail. But no - probably don't need to check the exact number, but a small range.

Seems that there is one new entry here...
