### ISSUE TITLE
Log with picture has posting error / CalledFromWrongThread Exception

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#10831]
## Bug description 

Just reported by a nightly user, not sure if also `release` is affected

### Steps to reproduce the problem

- Compose a log for a gc.com cache
- Attach new picture (no scling)
- Send log

### Actual result after these steps 

- "Error sending log" message is shown after picture upload is finished, the log is however posted online including the picture

### Expected result after these steps 

- No error message if upload is successful

## c:geo version 

2021.03.06-NB  (not sure if `release` is also affected).

## Reproducible 

I was able to reproduce it by posting a log + picture as "Note" to one of my owned caches

## Additional context 

Website change?

**Comment by fm-sys** [comment]
Yes, noticed that while writing a log yesterday as well. Had thought that it was a one-time problem but apparently not... So yes, I can verify the issue. 

Should IMHO be included into the next bugfix release.

**Comment by Lineflyer** [comment]
@fm-sys  Can you look into this problem?

I will wait with bigfix release.

**Comment by fm-sys** [comment]
Unfortunately I will have no time this weekend (where I live, Thursday and Friday is already free this week.)

So you will probably need to wait at least until Monday. Or someone else can look into it.

For sure we also could do two small releases...

**Comment by Lineflyer** [comment]
Finding so far from my side:
Tested on a Google Pixel 3a (Android 12/S preview) with current release and nightly the problem is not reproducible.

WIth current nightly it is however reproducible on my Samsung S20 (Android 11) and show the following in logcat:
```
2021-06-03 20:52:34.004 18072-29050/? E/cgeo: [AsyncTask #66] LogCacheActivity.Poster.doInBackgroundInternal
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:10695)
        at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:2166)
        at android.view.View.requestLayout(View.java:27055)
        at android.view.View.requestLayout(View.java:27055)
        at android.view.View.requestLayout(View.java:27055)
        at android.view.View.requestLayout(View.java:27055)
        at android.view.View.requestLayout(View.java:27055)
        at android.view.View.requestLayout(View.java:27055)
        at android.widget.ScrollView.requestLayout(ScrollView.java:2594)
        at android.view.View.requestLayout(View.java:27055)
        at android.view.View.requestLayout(View.java:27055)
        at android.view.View.requestLayout(View.java:27055)
        at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:380)
        at android.view.View.requestLayout(View.java:27055)
        at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4586)
        at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.triggerUpdateProcessor(RecyclerView.java:5747)
        at androidx.recyclerview.widget.RecyclerView$RecyclerViewDataObserver.onItemRangeRemoved(RecyclerView.java:5730)
        at androidx.recyclerview.widget.RecyclerView$AdapterDataObservable.notifyItemRangeRemoved(RecyclerView.java:12694)
        at androidx.recyclerview.widget.RecyclerView$Adapter.notifyItemRangeRemoved(RecyclerView.java:7755)
        at cgeo.geocaching.ui.recyclerview.ManagedListAdapter.setItems(ManagedListAdapter.java:196)
        at cgeo.geocaching.ui.recyclerview.ManagedListAdapter.clearList(ManagedListAdapter.java:188)
        at cgeo.geocaching.ui.ImageListFragment.clearImages(ImageListFragment.java:122)
        at cgeo.geocaching.log.LogCacheActivity$Poster.doInBackgroundInternal(LogCacheActivity.java:785)
        at cgeo.geocaching.log.LogCacheActivity$Poster.doInBackgroundInternal(LogCacheActivity.java:706)
        at cgeo.geocaching.utils.AbstractAsyncTaskWithProgress.doInBackground(AbstractAsyncTaskWithProgress.java:134)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
```

**Comment by eddiemuc** [comment]
Thanks for the log, error is clear to me now.

To solve this:
In `LogCacheActivity.java:785`, the call to imagefragmentlist.clearList must be removed and executed after the asyncthread has finished in the GUI thread

I recently corrected a problem with asynchronity in ManagedLiatAdapter, this most likely introduced the problem above.

I can currently not really plan my programming time, if this is really urgent then maybe someone else can fix this? Otherwise I will try to squeeze it in somewhere today or at weekend.

**Comment by Lineflyer** [comment]
Can you tell if this problem is on master only?
I guess so, but had no time to test yet.

**Comment by eddiemuc** [comment]
> Can you tell if this problem is on master only?
> I guess so, but had no time to test yet.

Yes, this is on master only

**Comment by eddiemuc** [comment]
PR #10842 created
