### ISSUE TITLE
Crash when clicking on cache in live map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11185]
Beta user reported that sometimes (not reproducible) the app crashes when he clicks on a cache on live map to open its popup.
Started with beta update.

Log shows:
```
07-11 11:30:43.032 20961 20961 E AndroidRuntime: FATAL EXCEPTION: main
07-11 11:30:43.032 20961 20961 E AndroidRuntime: Process: cgeo.geocaching, PID: 20961
07-11 11:30:43.032 20961 20961 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=506; index=506
07-11 11:30:43.032 20961 20961 E AndroidRuntime: 	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:380)
07-11 11:30:43.032 20961 20961 E AndroidRuntime: 	at java.util.concurrent.CopyOnWriteArrayList.get(CopyOnWriteArrayList.java:393)
07-11 11:30:43.032 20961 20961 E AndroidRuntime: 	at org.mapsforge.map.layer.Layers.get(Layers.java:336)
07-11 11:30:43.032 20961 20961 E AndroidRuntime: 	at org.mapsforge.map.android.input.TouchGestureHandler.onSingleTapConfirmed(TouchGestureHandler.java:263)
07-11 11:30:43.032 20961 20961 E AndroidRuntime: 	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:345)
07-11 11:30:43.032 20961 20961 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-11 11:30:43.032 20961 20961 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
07-11 11:30:43.032 20961 20961 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
07-11 11:30:43.032 20961 20961 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-11 11:30:43.032 20961 20961 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
07-11 11:30:43.032 20961 20961 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

Sys info:
```
## System information

c:geo version: 2021.07.10-RC

Device:
-------
- Device type: SM-G960F (starltexx, samsung)
- Available processors: 8
- Android version: 10
- Android build: QP1A.190711.020.G960FXXUFFUE1
- Screen resolution: 1440x2768px (360x668dp)
- Sailfish OS detected: false
- Google Play services: enabled - 21.21.16 (120408-378233385)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Hide caches: own/ foundarchived
- Hide waypoints: -
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Debug mode active: no
- Live map mode: true
- OSM multi-threading: true / threads: 4
- Global filter: display all caches
- Last backup: 26. Apr. 2020, 11:18
- Routing mode: Walk
- Settings: v5, Count:171
- Map: Kombiniert (Offline)
- Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMultiMapSource
- Atts: alps.map: / Map data (c) OpenStreetMap contributors / / austria.map: / Map data (c) OpenStreetMap contributors / / baden-wuerttemberg.map: / Map data (c) OpenStreetMap contributors / / bayern.map: / Map data (c) OpenStreetMap contributors / / hessen.map: / Map data (c) OpenStreetMap contributors / / rheinland-pfalz.map: / Map data (c) OpenStreetMap contributors
- Theme: none

Services:
-------
- Geocaching sites enabled:
geocaching.com: Logged in (Anmeldung OK) / PREMIUM
extremcaching.com: Logged in (Anmeldung OK)
Geocaching.com Adventure Lab
opencaching.de: Logged in (Anmeldung OK)
- Geocaching.com date format: dd/MM/yyyy
- Routing: external / BRouter installed: true
- Installed c:geo plugins: contacts

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (1,7 GB free) v2 internal isDir(6 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (1,7 GB free) v2 external non-removable isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (1,7 GB free) v2 external non-removable isDir(2434 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (1,7 GB free) v2 internal isDir(0 entries)
- Public Folders: #11
- BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=11, dirs:>=9, totalFileSize:>=14,4 MB, free space: 1,7 GB, files on device: 1740800)
- OFFLINE_MAPS: /Locus/maps (User-Defined)[/Locus/maps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ALocus%2Fmaps::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ALocus%2Fmaps/document/primary%3ALocus%2Fmaps, Av:true, files:12, dirs:1, totalFileSize:3,2 GB, free space: 1,7 GB, files on device: 1740800)
- OFFLINE_MAP_THEMES: /Locus/maps/_themes (Default)[/Locus/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3ALocus%2Fmaps::/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ALocus%2Fmaps/document/primary%3ALocus%2Fmaps%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,7 GB, files on device: 1740800)
- LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:2, dirs:0, totalFileSize:974,3 KB, free space: 1,7 GB, files on device: 1740800)
- GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:47, dirs:0, totalFileSize:23,2 MB, free space: 1,7 GB, files on device: 1740800)
- BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:2, dirs:1, totalFileSize:13,4 MB, free space: 1,7 GB, files on device: 1740800)
- FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,7 GB, files on device: 1740800)
- SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,7 GB, files on device: 1740800)
- ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81,2 KB, free space: 1,7 GB, files on device: 1740800)
- ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,7 GB, files on device: 1740800)
- TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,7 GB, files on device: -1)
- Map render theme path:
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #2
- content://com.android.externalstorage.documents/tree/primary%3ALocus%2Fmaps (21. März, 10:41):RW
- content://com.android.externalstorage.documents/tree/primary%3Acgeo (21. März, 10:40):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v95, Size:89,7 MB) on system internal storage

--- End of system information ---

```

**Comment by moving-bits** [comment]
Won't fix. Old map implementations are deprecated as of release 2025.07.17 and superseded by UnifiedMap.
