### ISSUE TITLE
NPE in testOpenAndroMapsThemes 

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#11417]
### Describe your problem!

seen on CI:
~~~
**> Task :main:connectedBasicDebugAndroidTest
Starting 593 tests on android-28(AVD) - 11

cgeo.geocaching.downloader.DownloaderTest > testOpenAndroMapsThemes[android-28(AVD) - 11] [31mFAILED [0m
	java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
	at java.util.regex.Matcher.reset(Matcher.java:256)

> Task :main:connectedBasicDebugAndroidTest FAILED**
~~~

### How to reproduce?

see https://ci.cgeo.org/job/cgeo%20pull%20request/6657/console

### Reproducible

Yes

### c:geo Version

developer build

**Comment by moving-bits** [comment]
The error info gets truncated to 
``` 
cgeo.geocaching.downloader.DownloaderTest > testOpenAndroMapsThemes[android-28(AVD) - 11] [31mFAILED [0m
	java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
	at java.util.regex.Matcher.reset(Matcher.java:256)

> Task :main:connectedBasicDebugAndroidTest FAILED
```

Any chance to get the full error message (with details for calling lines etc.)?

**Comment by bekuno** [comment]
The problem lies in `DownloaderTest.getList`.
~~~
        final String page = Network.getResponseData(Network.getRequest(url));
        downloader.analyzePage(Uri.parse(url), list, page);
~~~
Here the `page` can be `null`.

In the only method (outside test) where `analyzePage` is called - `cgeo.geocaching.downloader.DownloadSelectorActivity`
it is wrapped in 
~~~
            try {
                downloader.analyzePage(uri, list, page);
                ...
            } catch (final Exception e) {
~~~

In `analyzePage` we typically call 
~~~
        final MatcherWrapper matchMap = new MatcherWrapper(PATTERN_TILE, page);
~~~
with a `@NonNull` declaration
~~~
    public MatcherWrapper(@NonNull final Pattern pattern, @NonNull final String input) {
~~~

 I well create a PR.
