### ISSUE TITLE
Crash when switching to another app while using coordinate calculator

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11412]
### Describe your problem!

The app is crashing when I switch to another app (e.g. to copy a formula) while I am on the coordinate calculator.

---

Not reproducible for me.

### How to reproduce?

- Edit waypoint
- Select coordinate calculator
- Fill some fields
- Switch to another app
- Switch back to c:geo

### Actual result after these steps?

Crash

### Expected result after these steps?

Normal operation

### Reproducible

Unclear

### c:geo Version

2021.07.30-RC

### Additional Information

Stacktrace of the user shows two things. Not sure which is related but probably both need to be solved (or are already solved based on the related issues?):

```
08-03 16:44:32.074 13920 13920 E AndroidRuntime: org.apache.commons.lang3.SerializationException: java.io.NotSerializableException: cgeo.geocaching.calculator.ButtonData
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:140)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:154)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at cgeo.geocaching.ui.dialog.CoordinatesCalculateDialog.onSaveInstanceState(CoordinatesCalculateDialog.java:529)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performSaveInstanceState(Fragment.java:3151)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.saveBasicState(FragmentStateManager.java:683)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.saveState(FragmentStateManager.java:649)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at androidx.fragment.app.FragmentStore.saveActiveFragments(FragmentStore.java:177)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.saveAllState(FragmentManager.java:2655)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.saveAllState(FragmentController.java:152)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity$1.saveState(FragmentActivity.java:133)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at androidx.savedstate.SavedStateRegistry.performSave(SavedStateRegistry.java:227)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at androidx.savedstate.SavedStateRegistryController.performSave(SavedStateRegistryController.java:74)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at androidx.activity.ComponentActivity.onSaveInstanceState(ComponentActivity.java:314)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at cgeo.geocaching.EditWaypointActivity.onSaveInstanceState(EditWaypointActivity.java:485)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at cgeo.geocaching.EditWaypointActivity_.onSaveInstanceState(EditWaypointActivity_.java:117)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at android.app.Activity.performSaveInstanceState(Activity.java:2043)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1485)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at android.app.ActivityThread.callActivityOnSaveInstanceState(ActivityThread.java:5304)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:4630)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:4594)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:4669)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:41)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: Caused by: java.io.NotSerializableException: cgeo.geocaching.calculator.ButtonData
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1240)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at java.util.ArrayList.writeObject(ArrayList.java:762)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at java.io.ObjectStreamClass.invokeWriteObject(ObjectStreamClass.java:1036)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1552)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1604)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1565)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1488)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1234)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:354)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:138)
08-03 16:44:32.074 13920 13920 E AndroidRuntime: 	... 30 more
```

```
08-03 16:44:35.549 27778 27778 E AndroidRuntime: FATAL EXCEPTION: main
08-03 16:44:35.549 27778 27778 E AndroidRuntime: Process: cgeo.geocaching, PID: 27778
08-03 16:44:35.549 27778 27778 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.CacheDetailActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator: could not find Fragment constructor
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator: could not find Fragment constructor
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:297)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at cgeo.geocaching.activity.AbstractActivity.onCreate(AbstractActivity.java:129)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at cgeo.geocaching.activity.AbstractActionBarActivity.onCreate(AbstractActionBarActivity.java:22)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at cgeo.geocaching.activity.TabbedViewPagerActivity.onCreate(TabbedViewPagerActivity.java:256)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity.onCreate(CacheDetailActivity.java:238)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7824)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7813)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	... 11 more
08-03 16:44:35.549 27778 27778 E AndroidRuntime: Caused by: java.lang.NoSuchMethodException: cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator.<init> []
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at java.lang.Class.getConstructor0(Class.java:2332)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at java.lang.Class.getConstructor(Class.java:1728)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
08-03 16:44:35.549 27778 27778 E AndroidRuntime: 	... 28 more
```

**Comment by eddiemuc** [comment]
I am pretty sure the first exception iis with PR https://github.com/cgeo/cgeo/pull/11381 and the second one with PR https://github.com/cgeo/cgeo/pull/11385

**Comment by Lineflyer** [comment]
Lets then assume this is fixed already. Will ask the user to report back for next nightly.
