### ISSUE TITLE
Crashes when handling with lists

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11919]
Short note from field.
Keep having lots of crashes while crawling lists and viewing caches.

2021.10.16-NB

```
10-16 12:07:58.742 29285 29285 E AndroidRuntime: FATAL EXCEPTION: main
10-16 12:07:58.742 29285 29285 E AndroidRuntime: Process: cgeo.geocaching, PID: 29285
10-16 12:07:58.742 29285 29285 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.CacheDetailActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean cgeo.geocaching.VariablesViewPageFragment$VariablesListAdapter.hasUnsavedChanges()' on a null object reference
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3623)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8107)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean cgeo.geocaching.VariablesViewPageFragment$VariablesListAdapter.hasUnsavedChanges()' on a null object reference
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at cgeo.geocaching.VariablesViewPageFragment.checkUnsavedChanges(VariablesViewPageFragment.java:441)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at cgeo.geocaching.VariablesViewPageFragment.setContent(VariablesViewPageFragment.java:425)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at cgeo.geocaching.activity.TabbedViewPagerFragment.notifyDataSetChanged(TabbedViewPagerFragment.java:61)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at cgeo.geocaching.activity.TabbedViewPagerActivity.setOrderedPages(TabbedViewPagerActivity.java:110)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at cgeo.geocaching.activity.TabbedViewPagerActivity.createViewPager(TabbedViewPagerActivity.java:49)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity.onCreate(CacheDetailActivity.java:333)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7957)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7946)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3598)
10-16 12:07:58.742 29285 29285 E AndroidRuntime: 	... 11 more
10-16 23:59:14.804 30973 30973 E AndroidRuntime: FATAL EXCEPTION: main
10-16 23:59:14.804 30973 30973 E AndroidRuntime: Process: cgeo.geocaching, PID: 30973
10-16 23:59:14.804 30973 30973 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.CacheDetailActivity}: java.lang.NullPointerException: Attempt to read from field 'cgeo.geocaching.models.CacheVariables cgeo.geocaching.VariablesViewPageFragment$VariablesListAdapter.variables' on a null object reference
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3623)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3775)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5763)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:5671)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2261)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8107)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'cgeo.geocaching.models.CacheVariables cgeo.geocaching.VariablesViewPageFragment$VariablesListAdapter.variables' on a null object reference
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at cgeo.geocaching.VariablesViewPageFragment$VariablesListAdapter.access$500(VariablesViewPageFragment.java:117)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at cgeo.geocaching.VariablesViewPageFragment.checkUnsavedChanges(VariablesViewPageFragment.java:418)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at cgeo.geocaching.VariablesViewPageFragment.setContent(VariablesViewPageFragment.java:402)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at cgeo.geocaching.activity.TabbedViewPagerFragment.notifyDataSetChanged(TabbedViewPagerFragment.java:61)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at cgeo.geocaching.activity.TabbedViewPagerActivity.setOrderedPages(TabbedViewPagerActivity.java:110)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at cgeo.geocaching.activity.TabbedViewPagerActivity.createViewPager(TabbedViewPagerActivity.java:49)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity.onCreate(CacheDetailActivity.java:334)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7957)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7946)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3598)
10-16 23:59:14.804 30973 30973 E AndroidRuntime: 	... 13 more
```

**Comment by eddiemuc** [comment]
Will be fixed with PR #11918
