### ISSUE TITLE
Crash when trying to edit custom waypoints

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#11981]
### Describe your problem!

From support mail:
User creates a custom waypoint for a cache and also inserts a description/note to it. If he later wants to edit/modify the waypoint c:geo shows the edit view but then returns to main screen.

### How to reproduce?

I cannot reproduce, user describes:
- Open a stored cache
- Create a custom waypoint, enter coords and some text for description/user note
- Save it
- Some time later open the cache again and edit the previously created waypoint

### Actual result after these steps?

User describes:
The virtual keyboard opens but I cannot enter text, after some seconds the edit windows closes again

### Expected result after these steps?

Normal editing

### Reproducible

Unclear

### c:geo Version

2021.10.08

### System information

```text
## System information

c:geo version: 2021.10.08

Device:
-------
- Device type: WAS-LX1A (WAS-LX1A, HUAWEI)
- Available processors: 8
- Android version: 8.0.0
- Android build: WAS-LX1A 8.0.0.394(C432)
- Screen resolution: 1080x1794px (360x574dp)
- Pixel density: 3.0
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 21.39.16 (040408-402663742)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: orientation

Program settings:
-------
- Settings: v8, Count:149
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Time zone: GMT+02:00
- Debug mode active: no
- Last backup: never
- Routing mode: Off
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Google: Karte
- Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleMapSource
- Atts: none
- Theme: none

Filters:
-------
- Hide waypoints: visited
- LIVE: Status:5 Elemente,Cache-Typ:9 Elemente ([:inconclusive=false:advanced=true]AND(status:owned_no:found_no:solved_mystery_yes:exclude_disabled:exclude_archived;type:VIRTUAL:ADVLAB:TRADITIONAL:LETTERBOX:MULTI:EVENT:MYSTERY:WEBCAM:WHERIGO))
- OFFLINE: Cache-Typ:5 Elemente ([:inconclusive=false:advanced=true]AND(difficulty_terrain:d=-:d=-:t=-:t=-;type:ADVLAB:TRADITIONAL:MULTI:EVENT:MYSTERY))

Services:
-------
- Geocaching sites enabled:
geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com Adventure Lab
- Geocaching.com date format: dd.MM.yyyy
- Routing: external / BRouter installed: false
- Installed c:geo plugins: contacts

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (432,3 MB free) v2 internal isDir(8 entries)
- Legacy User storage c:geo dir: /storage/3632-3733/cgeo (25,5 GB free) v2 external removable isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (412,3 MB free) v2 external non-removable isDir(6559 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (432,3 MB free) v2 internal isDir(0 entries)
- Public Folders: #11
- BASE: SD-Karte/cgeo (User-Defined)[SD-Karte/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo/document/3632-3733%3Acgeo, Av:true, files:>=1, dirs:>=7, totalFileSize:>=72,3 KB, free space: 25,5 GB, files on device: 0)
- OFFLINE_MAPS: SD-Karte/offlinekarten (User-Defined)[SD-Karte/offlinekarten[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/3632-3733%3Aofflinekarten::]] (Uri: content://com.android.externalstorage.documents/tree/3632-3733%3Aofflinekarten/document/3632-3733%3Aofflinekarten, Av:true, files:0, dirs:1, totalFileSize:0 B, free space: 25,5 GB, files on device: 0)
- OFFLINE_MAP_THEMES: SD-Karte (User-Defined)[SD-Karte[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/3632-3733%3A::]] (Uri: content://com.android.externalstorage.documents/tree/3632-3733%3A/document/3632-3733%3A, Av:true, files:>=5, dirs:>=120, totalFileSize:>=2,2 GB, free space: 25,5 GB, files on device: 0)
- LOGFILES: SD-Karte/cgeo/logfiles (Default)[SD-Karte/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo/document/3632-3733%3Acgeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:72,3 KB, free space: 25,5 GB, files on device: 0)
- GPX: SD-Karte/cgeo/gpx (Default)[SD-Karte/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo/document/3632-3733%3Acgeo%2Fgpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 25,5 GB, files on device: 0)
- BACKUP: SD-Karte/cgeo/backup (Default)[SD-Karte/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo/document/3632-3733%3Acgeo%2Fbackup, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 25,5 GB, files on device: 0)
- FIELD_NOTES: SD-Karte/cgeo/field-notes (Default)[SD-Karte/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo/document/3632-3733%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 25,5 GB, files on device: 0)
- SPOILER_IMAGES: SD-Karte/cgeo/GeocachePhotos (Default)[SD-Karte/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo/document/3632-3733%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 25,5 GB, files on device: 0)
- ROUTING_BASE: SD-Karte/cgeo/routing (Default)[SD-Karte/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo/document/3632-3733%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81,2 KB, free space: 25,5 GB, files on device: 0)
- ROUTING_TILES: SD-Karte/cgeo/routing/segments4 (Default)[SD-Karte/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo/document/3632-3733%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 25,5 GB, files on device: 0)
- TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 432,3 MB, files on device: -1)
- Map render theme path:
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #3
- content://com.android.externalstorage.documents/tree/3632-3733%3A (17. Apr., 10:37):RW
- content://com.android.externalstorage.documents/tree/3632-3733%3Aofflinekarten (17. Apr., 10:36):RW
- content://com.android.externalstorage.documents/tree/3632-3733%3Acgeo (17. Apr., 10:36):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v97, Size:175,1 MB) on system internal storage

--- End of system information ---
```

### Additional Information

Support ticket #181960

Found this (many times in the log):
```
10-22 12:42:49.626 32018 32018 E AndroidRuntime: FATAL EXCEPTION: main
10-22 12:42:49.626 32018 32018 E AndroidRuntime: Process: cgeo.geocaching, PID: 32018
10-22 12:42:49.626 32018 32018 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getBoundsOnScreen(android.graphics.Rect)' on a null object reference
10-22 12:42:49.626 32018 32018 E AndroidRuntime: 	at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:484)
10-22 12:42:49.626 32018 32018 E AndroidRuntime: 	at android.app.assist.AssistStructure.<init>(AssistStructure.java:1908)
10-22 12:42:49.626 32018 32018 E AndroidRuntime: 	at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3580)
10-22 12:42:49.626 32018 32018 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2238)
10-22 12:42:49.626 32018 32018 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
10-22 12:42:49.626 32018 32018 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
10-22 12:42:49.626 32018 32018 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7529)
10-22 12:42:49.626 32018 32018 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-22 12:42:49.626 32018 32018 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
10-22 12:42:49.626 32018 32018 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

**Comment by Lineflyer** [comment]
Seems to be fixed, see #12556
