### ISSUE TITLE
NPE on mapsforge map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12031]
### Describe your problem!

From support mail:
I have had a problem for some time that when I use the app for a long time and have to switch on an off it, it wont let me open the cache pages anymore.
For example now that we have Adventure labs I have to switch between those apps so that I don't miss anything.

The problem occures so that I try to select a cache from Live map and it only zoomes in. No matter how detailed the zoom level is, the cache cannot be opened.
The problem resets when I close the app and open again.

I think I've had this problem for some time already but lately the time frame has decreased making it more annoying since now I cannot go for a cache search without one.

### How to reproduce?

Unclear, but the user contacted us again with a debug log saved after the problem occured.
I found this NPE in there, maybe its related/causing it?

```
10-28 14:45:54.433 22316 22316 E AndroidRuntime: FATAL EXCEPTION: main
10-28 14:45:54.433 22316 22316 E AndroidRuntime: Process: cgeo.geocaching, PID: 22316
10-28 14:45:54.433 22316 22316 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.getVisibleCacheGeocodes()' on a null object reference
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at cgeo.geocaching.maps.mapsforge.v6.NewMap.onPrepareOptionsMenu(NewMap.java:379)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at android.app.Activity.onPreparePanel(Activity.java:4103)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:485)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:470)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:3111)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1934)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2188)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:268)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:722)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7582)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-28 14:45:54.433 22316 22316 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

### Reproducible

Unclear

### c:geo Version

2021.10.08

### System information

```text
## System information

c:geo version: 2021.10.08

Device:
-------
- Device type: motorola one zoom (parker_reteu, motorola)
- Available processors: 8
- Android version: 10
- Android build: QPHS30.29-Q3-28-13-10-10
- Screen resolution: 1080x2156px (485x966dp)
- Pixel density: 2.2250001
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 21.39.16 (120400-402663742)
- HW acceleration: enabled (default state)

Sensor and location:
-------
- Low power mode: active
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: absent
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v8, Count:184
- Set language: en_FI (system default)
- System date format: dd/MM/y
- Time zone: GMT+03:00
- Debug mode active: yes
- Last backup: 27 May 2020, 19.26
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Google: Map
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleMapSource
  - Atts: none
  - Theme: peruskartta.zip:Peruskartta.xml

Filters:
-------
- Hide waypoints: -
- LIVE: None ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status))
- OFFLINE: None ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status))

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   Geocaching.com Adventure Lab
- Geocaching.com date format: d.M.yyyy
- Routing: external / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (39,7 GB free) v2 internal isDir(6 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (39,7 GB free) v2 external non-removable isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (39,7 GB free) v2 external non-removable isDir(1196 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (39,7 GB free) v2 internal isDir(0 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=93, dirs:>=8, totalFileSize:>=33,1 MB, free space: 39,7 GB, files on device: 13511675)
  - OFFLINE_MAPS: /cgeo/maps (User-Defined)[/cgeo/maps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps, Av:true, files:4, dirs:2, totalFileSize:4,2 GB, free space: 39,7 GB, files on device: 13511675)
  - OFFLINE_MAP_THEMES: /cgeo/maps/theme (User-Defined)[/cgeo/maps/theme[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps%2Ftheme::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps%2Ftheme/document/primary%3Acgeo%2Fmaps%2Ftheme, Av:true, files:2, dirs:0, totalFileSize:419,5 KB, free space: 39,7 GB, files on device: 13511675)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:2, dirs:0, totalFileSize:52,0 KB, free space: 39,7 GB, files on device: 13511675)
  - GPX: /cgeo/gpx (User-Defined)[/cgeo/gpx[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx/document/primary%3Acgeo%2Fgpx, Av:true, files:2, dirs:0, totalFileSize:880,6 KB, free space: 39,7 GB, files on device: 13511675)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:2, dirs:1, totalFileSize:32,1 MB, free space: 39,7 GB, files on device: 13511675)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:87, dirs:0, totalFileSize:70,7 KB, free space: 39,7 GB, files on device: 13511675)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 39,7 GB, files on device: 13511675)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81,2 KB, free space: 39,7 GB, files on device: 13511675)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 39,7 GB, files on device: 13511675)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 39,7 GB, files on device: -1)
- Map render theme path: peruskartta.zip:Peruskartta.xml
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #4
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (18 Apr, 23.27):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx (18 Apr, 23.27):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps (19 Apr, 18.32):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps%2Ftheme (19 Apr, 18.59):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v97, Size:43,8 MB) on system internal storage

--- End of system information ---
```

### Additional Information

Support ticket #139717

**Comment by eddiemuc** [comment]
Not completely trivial. "caches" is null in onPrepareOptions, although it should have been initialized in onStart. Needs some deeper look into lifecycle

**Comment by eddiemuc** [comment]
Seems that invalidateOptionsMenu is called asynchronous sometimes. This might interfere with lifecycle.

IMHO, oPrepareOptions must be able to handle it if caches is null. But I am not sure whether this might have any unwanted side effects. Is there anyone who has worked in this area recently?

**Comment by moving-bits** [comment]
Won't fix. Old map implementations are deprecated as of release 2025.07.17 and superseded by UnifiedMap.
