### ISSUE TITLE
Mapsforge crash in emulator

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12060]
### Describe your problem!

Running master in emulator it crashs when displaying any Mapsforge map. I went back two weeks in time (in the branch) and the same is happening there.

```
2021-11-06 19:36:49.053 8569-8590/cgeo.geocaching D/LeakCanary: Setting up flushing for Thread[Studio:view.ins [layoutinspector.view.inspection primary],10,main]
2021-11-06 19:36:49.053 8569-8590/cgeo.geocaching D/LeakCanary: Setting up flushing for Thread[PixelCopyHelper,7,main]
2021-11-06 19:36:52.091 8569-8569/cgeo.geocaching I/ToolbarWidgetWrapper: Progress display unsupported
2021-11-06 19:36:52.305 8569-8569/cgeo.geocaching I/AndroidUtil: TILECACHE INMEMORY SIZE: 121
2021-11-06 19:36:52.308 8569-8569/cgeo.geocaching I/AndroidUtil: TILECACHE FILE SIZE: 2000
2021-11-06 19:36:53.109 8569-8569/cgeo.geocaching D/LeakCanary: Watching instance of androidx.fragment.app.FragmentManagerViewModel (androidx.fragment.app.FragmentManagerViewModel received ViewModel#onCleared() callback) with key 6def1ea5-3bb0-470a-9a41-8bce6ee726db
2021-11-06 19:36:53.109 8569-8569/cgeo.geocaching D/LeakCanary: Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key f75b8415-0347-4efc-a0ad-1224f15765a9
2021-11-06 19:36:53.110 8569-8569/cgeo.geocaching D/LeakCanary: Watching instance of androidx.lifecycle.ReportFragment (androidx.lifecycle.ReportFragment received Fragment#onDestroy() callback) with key b5ebbad3-a21a-4109-9b77-73bbee6ca873
2021-11-06 19:36:53.110 8569-8569/cgeo.geocaching D/LeakCanary: Watching instance of cgeo.geocaching.MainActivity (cgeo.geocaching.MainActivity received Activity#onDestroy() callback) with key 43e9b8dc-bbbf-4888-9b6b-e4500566c6f4
2021-11-06 19:36:53.114 8569-8569/cgeo.geocaching D/LeakCanary: Watching instance of android.widget.RelativeLayout (cgeo.geocaching.StatusFragment received Fragment#onDestroyView() callback (references to its views should be cleared to prevent leaks)) with key dba1ef47-3af9-4735-8180-837891032e58
2021-11-06 19:36:53.115 8569-8569/cgeo.geocaching D/LeakCanary: Watching instance of androidx.loader.app.LoaderManagerImpl$LoaderViewModel (androidx.loader.app.LoaderManagerImpl$LoaderViewModel received ViewModel#onCleared() callback) with key 92fa62e9-e9e9-4edd-b9ba-b0755f9be4d9
2021-11-06 19:36:53.115 8569-8569/cgeo.geocaching D/LeakCanary: Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key 6f17428e-d7ba-47cb-ace9-3ff88b37e623
2021-11-06 19:36:53.115 8569-8569/cgeo.geocaching D/LeakCanary: Watching instance of cgeo.geocaching.StatusFragment (cgeo.geocaching.StatusFragment received Fragment#onDestroy() callback) with key 62c9e6af-1dc1-4383-9e16-75b3b8b410c2
2021-11-06 19:36:53.342 8569-8710/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: TileDownloadThread
    Process: cgeo.geocaching, PID: 8569
    java.lang.IllegalStateException: Cannot access request header fields after connection is set
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getRequestProperties(HttpURLConnectionImpl.java:236)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getRequestProperties(DelegatingHttpsURLConnection.java:183)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getRequestProperties(HttpsURLConnectionImpl.java:30)
        at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.getRequestProperties(TrackedHttpURLConnection.java:230)
        at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.trackPreConnect(TrackedHttpURLConnection.java:63)
        at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.getInputStream(TrackedHttpURLConnection.java:372)
        at com.android.tools.profiler.support.network.httpurl.HttpsURLConnection$.getInputStream(HttpsURLConnection$.java:261)
        at org.mapsforge.map.layer.download.TileDownloader.getInputStream(TileDownloader.java:37)
        at org.mapsforge.map.layer.download.TileDownloader.downloadImage(TileDownloader.java:71)
        at org.mapsforge.map.layer.download.TileDownloadThread.downloadTile(TileDownloadThread.java:81)
        at org.mapsforge.map.layer.download.TileDownloadThread.doWork(TileDownloadThread.java:60)
        at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
2021-11-06 19:36:53.342 8569-8710/cgeo.geocaching W/cgeo: [TileDownloadThread] UncaughtException
    java.lang.IllegalStateException: Cannot access request header fields after connection is set
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getRequestProperties(HttpURLConnectionImpl.java:236)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getRequestProperties(DelegatingHttpsURLConnection.java:183)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getRequestProperties(HttpsURLConnectionImpl.java:30)
        at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.getRequestProperties(TrackedHttpURLConnection.java:230)
        at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.trackPreConnect(TrackedHttpURLConnection.java:63)
        at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.getInputStream(TrackedHttpURLConnection.java:372)
        at com.android.tools.profiler.support.network.httpurl.HttpsURLConnection$.getInputStream(HttpsURLConnection$.java:261)
        at org.mapsforge.map.layer.download.TileDownloader.getInputStream(TileDownloader.java:37)
        at org.mapsforge.map.layer.download.TileDownloader.downloadImage(TileDownloader.java:71)
        at org.mapsforge.map.layer.download.TileDownloadThread.downloadTile(TileDownloadThread.java:81)
        at org.mapsforge.map.layer.download.TileDownloadThread.doWork(TileDownloadThread.java:60)
        at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
2021-11-06 19:36:53.353 8569-8708/cgeo.geocaching W/cgeo: [TileDownloadThread] UncaughtException
    java.lang.IllegalStateException: Cannot access request header fields after connection is set
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getRequestProperties(HttpURLConnectionImpl.java:236)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getRequestProperties(DelegatingHttpsURLConnection.java:183)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getRequestProperties(HttpsURLConnectionImpl.java:30)
        at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.getRequestProperties(TrackedHttpURLConnection.java:230)
        at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.trackPreConnect(TrackedHttpURLConnection.java:63)
        at com.android.tools.profiler.support.network.httpurl.TrackedHttpURLConnection.getInputStream(TrackedHttpURLConnection.java:372)
        at com.android.tools.profiler.support.network.httpurl.HttpsURLConnection$.getInputStream(HttpsURLConnection$.java:261)
        at org.mapsforge.map.layer.download.TileDownloader.getInputStream(TileDownloader.java:37)
        at org.mapsforge.map.layer.download.TileDownloader.downloadImage(TileDownloader.java:71)
        at org.mapsforge.map.layer.download.TileDownloadThread.downloadTile(TileDownloadThread.java:81)
        at org.mapsforge.map.layer.download.TileDownloadThread.doWork(TileDownloadThread.java:60)
        at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
2021-11-06 19:36:53.353 8569-8708/cgeo.geocaching I/Process: Sending signal. PID: 8569 SIG: 9
```

### How to reproduce?

Pixel 4 API 30 Play Store image as basis

### Reproducible

Yes

### c:geo Version

2021.11.05-NB

**Comment by ztNFny** [comment]
haven't seen this in a while
