### ISSUE TITLE
Refactor settings: crash when opening map preference screen

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12114]
One of the issues discovered in the WIP PR #11298, happened on an Android 10 emulator:

c:geo crashes when opening the map preferences
 ```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 25841
    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.Set
        at android.app.SharedPreferencesImpl.getStringSet(SharedPreferencesImpl.java:298)
        at androidx.preference.Preference.getPersistedStringSet(Preference.java:1739)
        at androidx.preference.MultiSelectListPreference.onSetInitialValue(MultiSelectListPreference.java:205)
        at androidx.preference.Preference.onSetInitialValue(Preference.java:1614)
        at androidx.preference.Preference.dispatchSetInitialValue(Preference.java:1587)
        at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1311)
        at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1326)
        at androidx.preference.PreferenceGroup.addPreference(PreferenceGroup.java:249)
        at androidx.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:170)
        at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:345)
        at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:346)
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157)
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109)
        at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
        at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:377)
        at cgeo.geocaching.settings.fragments.PreferenceMapFragment.onCreatePreferences(PreferenceMapFragment.java:24)
        at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by fm-sys** [comment]
looks similar to #12120

**Comment by moving-bits** [comment]
Cannot reproduce anymore - seems to be fixed meanwhile, so let's close here.

**Comment by fm-sys** [comment]
It **_is_** still happening, still the same stack trace as posted above...

**Comment by moving-bits** [comment]
Ok, then please add some info on how to reproduce it, because simply going to settings => map does not lead to a crash.

**Comment by fm-sys** [comment]
To be honest, I'm already actively searching for the cause but cannot find it. The only thing which I know is, that it finally leads to a crash...

When looking at the exception, it's actually pretty clear: `ClassCastException: Integer cannot be cast to Set`

This happens when the wrong datatype is stored inside the shared preferences. But I haven't found the problematic setting yet.

I would like to do a settings backup and share it, but the "start backup" setting is currently still disabled as well... :-/

**Comment by fm-sys** [comment]
[cgeo-settings.zip](https://github.com/cgeo/cgeo/files/7652696/cgeo-settings.zip)

These are the cgeo settings which are active on the affected device...

**Comment by moving-bits** [comment]
I compared the file you provided with settings of a current dev build, but was not able to find a setting having a different type :-(

Have you tried "implanting" a cgeo-settings.xml from an older backup into the build you are currently using? Does that work?

**Comment by fm-sys** [comment]
> Have you tried "implanting" a cgeo-settings.xml from an older backup into the build you are currently using? Does that work?

Unfortunately, all backups have the same problem. BTW, also my regular device using the nightly builds is affected :-/

Next thing I will try is disabling all map settings and enable them one-by-one again...

Out of interest: Can you reproduce the crash if you import the provided settings into your dev machine?

**Comment by moving-bits** [comment]
> Out of interest: Can you reproduce the crash if you import the provided settings into your dev machine?

Have just tried it:
- uploaded your cgeo-settings.xml to my most recent backup folder (after having deleted the existing settings file first)
- started a "restore" in c:geo (needed to regrant access to "/cgeo/maps" folder along the way)
- entered settings => map => no crash
- closed c:geo using task manager and restarted it
- entered settings => map => still no crash

So cannot reproduce it over here.

**Comment by Lineflyer** [comment]
Have the same problem on my tablet after upgrading to nightly 2021.12.04-NB.
Trying to enter the map settings the app crashes. Did not yet check the logs though.

Anything I can help with?

**Comment by Lineflyer** [comment]
Log from  my tablet:

```
2021-12-05 12:39:45.822 18583-18583/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 18583
    java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.Set
        at android.app.SharedPreferencesImpl.getStringSet(SharedPreferencesImpl.java:298)
        at androidx.preference.Preference.getPersistedStringSet(Preference.java:1739)
        at androidx.preference.MultiSelectListPreference.onSetInitialValue(MultiSelectListPreference.java:205)
        at androidx.preference.Preference.onSetInitialValue(Preference.java:1614)
        at androidx.preference.Preference.dispatchSetInitialValue(Preference.java:1587)
        at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1311)
        at androidx.preference.Preference.onAttachedToHierarchy(Preference.java:1326)
        at androidx.preference.PreferenceGroup.addPreference(PreferenceGroup.java:249)
        at androidx.preference.PreferenceGroup.addItemFromInflater(PreferenceGroup.java:170)
        at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:345)
        at androidx.preference.PreferenceInflater.rInflate(PreferenceInflater.java:346)
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:157)
        at androidx.preference.PreferenceInflater.inflate(PreferenceInflater.java:109)
        at androidx.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:216)
        at androidx.preference.PreferenceFragmentCompat.setPreferencesFromResource(PreferenceFragmentCompat.java:377)
        at cgeo.geocaching.settings.fragments.PreferenceMapFragment.onCreatePreferences(PreferenceMapFragment.java:32)
        at androidx.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:160)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:8107)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

**Comment by moving-bits** [comment]
@Lineflyer @fm-sys 
`MultiSelectPreference` was a temporary assignment by @SchoolGuy for our `ColorpickerPreference` - gone since I fixed and reenabled that preferences yesterday.

So question is: Does the error still occur with today's nightly? (would that be '2021.12.05-NB`?)

**Comment by fm-sys** [comment]
Indeed, I was still using the yesterday's development state. From my side, the issue is gone...

**Comment by Lineflyer** [comment]
Same here, just updated to 2021.12.05 and working now.

**Comment by moving-bits** [comment]
Good to hear, thanks for cross-checking!
