### ISSUE TITLE
Crash when long tapping coordinate of cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12211]
### Describe your problem!

Nightly crashes when long tapping on the coordinate field in cache details.

### How to reproduce?

- Open cache
- Long tap coords

### Actual result after these steps?

c:geo crashes

### Expected result after these steps?

Normal operation

### Reproducible

Yes

### c:geo Version

2021.12.01-6697118 developer build

### System information

```text
Emulator API30
```

### Additional Information

```
2021-12-01 20:22:49.308 6345-6345/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 6345
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.widget.TextView.getText()' on a null object reference
        at cgeo.geocaching.CacheDetailActivity$10.prepareClipboardActionMode(CacheDetailActivity.java:2303)
        at cgeo.geocaching.CacheDetailActivity$10.onCreateActionMode(CacheDetailActivity.java:2348)
        at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onCreateActionMode(AppCompatDelegateImpl.java:2692)
        at androidx.appcompat.app.WindowDecorActionBar$ActionModeImpl.dispatchOnCreate(WindowDecorActionBar.java:1060)
        at androidx.appcompat.app.WindowDecorActionBar.startActionMode(WindowDecorActionBar.java:528)
        at androidx.appcompat.app.AppCompatDelegateImpl.startSupportActionMode(AppCompatDelegateImpl.java:1204)
        at androidx.appcompat.app.AppCompatActivity.startSupportActionMode(AppCompatActivity.java:362)
        at cgeo.geocaching.CacheDetailActivity.lambda$addContextMenu$11$CacheDetailActivity(CacheDetailActivity.java:2292)
        at cgeo.geocaching.-$$Lambda$CacheDetailActivity$obhFglOeQgNDqx6HC2rztHcejnA.onLongClick(Unknown Source:4)
        at android.view.View.performLongClickInternal(View.java:7528)
        at android.view.View.performLongClick(View.java:7486)
        at android.widget.TextView.performLongClick(TextView.java:12391)
        at android.view.View.performLongClick(View.java:7504)
        at android.view.View$CheckForLongPress.run(View.java:28263)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-12-01 20:22:49.308 6345-6345/cgeo.geocaching W/cgeo: [main] UncaughtException
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.CharSequence android.widget.TextView.getText()' on a null object reference
        at cgeo.geocaching.CacheDetailActivity$10.prepareClipboardActionMode(CacheDetailActivity.java:2303)
        at cgeo.geocaching.CacheDetailActivity$10.onCreateActionMode(CacheDetailActivity.java:2348)
        at androidx.appcompat.app.AppCompatDelegateImpl$ActionModeCallbackWrapperV9.onCreateActionMode(AppCompatDelegateImpl.java:2692)
        at androidx.appcompat.app.WindowDecorActionBar$ActionModeImpl.dispatchOnCreate(WindowDecorActionBar.java:1060)
        at androidx.appcompat.app.WindowDecorActionBar.startActionMode(WindowDecorActionBar.java:528)
        at androidx.appcompat.app.AppCompatDelegateImpl.startSupportActionMode(AppCompatDelegateImpl.java:1204)
        at androidx.appcompat.app.AppCompatActivity.startSupportActionMode(AppCompatActivity.java:362)
        at cgeo.geocaching.CacheDetailActivity.lambda$addContextMenu$11$CacheDetailActivity(CacheDetailActivity.java:2292)
        at cgeo.geocaching.-$$Lambda$CacheDetailActivity$obhFglOeQgNDqx6HC2rztHcejnA.onLongClick(Unknown Source:4)
        at android.view.View.performLongClickInternal(View.java:7528)
        at android.view.View.performLongClick(View.java:7486)
        at android.widget.TextView.performLongClick(TextView.java:12391)
        at android.view.View.performLongClick(View.java:7504)
        at android.view.View$CheckForLongPress.run(View.java:28263)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by Lineflyer** [comment]
Long tap also crashes several other places on the cache details tab.

**Comment by moving-bits** [comment]
Most likely related to / similar cause as #12205, #12208 should provide a quick fix (at least for crash on tapping geocode it worked for me), but I will try to dive a bit deeper into it.

**Comment by moving-bits** [comment]
Extended #12208 to also fix this error
