### ISSUE TITLE
c:geo crashes on resume in CacheDetailActivity

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#12242]
### Describe your problem!

c:geo crashes when CacheDetailActivity is resumed after low-memory situation.

### How to reproduce?

1. Open cache details
2. Put c:geo into background
3. Do something that uses lots of memory and causes the CacheDetailActivity to be suspended
4. Switch back to c:geo

### Actual result after these steps?

c:geo crashes with

```
12-04 19:13:52.760  8835  8835 W cgeo    : [main] UncaughtException
12-04 19:13:52.760  8835  8835 W cgeo    : java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.CacheDetailActivity}: java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to android.widget.ScrollView$SavedState
12-04 19:13:52.760  8835  8835 W cgeo    : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:102)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at android.os.Looper.loop(Looper.java:154)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:6186)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
12-04 19:13:52.760  8835  8835 W cgeo    : Caused by: java.lang.ClassCastException: android.view.AbsSavedState$1 cannot be cast to android.widget.ScrollView$SavedState
12-04 19:13:52.760  8835  8835 W cgeo    : 	at android.widget.ScrollView.onRestoreInstanceState(ScrollView.java:1832)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at android.view.View.dispatchRestoreInstanceState(View.java:15755)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:3231)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at android.view.View.restoreHierarchyState(View.java:15733)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:639)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at androidx.fragment.app.Fragment.restoreViewState(Fragment.java:3010)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:3001)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:580)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:285)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at cgeo.geocaching.activity.AbstractActivity.onStart(AbstractActivity.java:305)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1249)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at android.app.Activity.performStart(Activity.java:6701)
12-04 19:13:52.760  8835  8835 W cgeo    : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2647)
```

### Expected result after these steps?

No crash.

### Reproducible

Yes

### c:geo Version

2021.12.04-NB-3b6e977

**Comment by SammysHP** [comment]
I'd like to push this issue. What I've found so far: This happens when there are multiple elements with the same ID over all pages in a viewpager. The implementation that restores the activity from a bundle tries to instantiate each view with the first matching ID found in the bundle. But if it is from a different page it will fail with the exception in the stacktrace.

**Comment by eddiemuc** [comment]
I noticed same behaviour while implementing calculated coordinates. I have an idea how to approach this, will take a look at it.

**Comment by fm-sys** [comment]
Just a side note: This can easily be reproduced by modifying the background limit in the system developer options... 

![Screenshot_20211211_142712_com android settings_copy_270x585](https://user-images.githubusercontent.com/64581222/145678464-7e4bd01e-857b-4124-b978-1c4db820ff19.jpg)

**Comment by eddiemuc** [comment]
PR #12297 should fix this.

(But I haven't side-checked with @fm-sys 's comment)

**Comment by eddiemuc** [comment]
I targeted release because problem is already present there

**Comment by eddiemuc** [comment]
...and PR# 12298 will do same thing for bottom navigation (targeted to master since bottom navigation is not yet on release)
