### ISSUE TITLE
Webhooks not working to tigger PR and/or commit builds

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12285]
Yesterday evening I noticed (at first on the WhereYouGo jobs, see https://github.com/cgeo/WhereYouGo/issues/314 ) that no build is triggered when pushes are made or PRs are opened. Later that evening it also stopped working for the cgeo repository.

After revisiting the job configuration on CI and the existing webhooks I have two assumptions:
- There is and was no webhook for PR builds defined in the cgeo repository. I wonder how it worked before (is it maybe proxied via one of the other hooks defined there (e.g. zenhub. io or notify.travis-ci.org) ?
- Apart from that the common fail of deliveries from both repositories looks more like a problem with internet communication on the CI. See also this warning on the commit job for cgeo: 
![grafik](https://user-images.githubusercontent.com/949669/145412114-d0bfae9d-2bad-4184-85cb-f260741b09a3.png)
On the other hand the Github side shows recent delivers with response code 200:
![grafik](https://user-images.githubusercontent.com/949669/145412299-f49da932-7134-44a6-b63c-6011c42c023c.png)

So I am really lost what happend here, stopped my trials to bring it alive and left all jobs and webhooks in initial state.
@mucek4 @kumy  Any help is appreciated.

**Comment by Lineflyer** [comment]
I get no other clue than some problem on CI causing this (e.g. some background process not working properly).
@mucek4 will reboot CI tomorrow.

**Comment by Lineflyer** [comment]
Now I finally found some clue in the Jenkins system log:

```
Unable to connect using credentials: SIGN_PASS
java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/user
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
	at org.kohsuke.github.Requester.parse(Requester.java:615)
Caused: java.io.IOException: Server returned HTTP response code: 401 for URL: https://api.github.com/user
	at java.base/jdk.internal.reflect.GeneratedConstructorAccessor7317.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
	at org.kohsuke.github.Requester.parse(Requester.java:625)
Caused: org.kohsuke.github.HttpException: Server returned HTTP response code: 401, message: 'Unauthorized' for URL: https://api.github.com/user
	at org.kohsuke.github.Requester.parse(Requester.java:646)
	at org.kohsuke.github.Requester.parse(Requester.java:607)
	at org.kohsuke.github.Requester._to(Requester.java:285)
Caused: org.kohsuke.github.HttpException: {"message":"Bad credentials","documentation_url":"https://docs.github.com/rest"}
	at org.kohsuke.github.Requester.handleApiError(Requester.java:703)
	at org.kohsuke.github.Requester._to(Requester.java:306)
	at org.kohsuke.github.Requester.to(Requester.java:247)
	at org.kohsuke.github.GitHub.getMyself(GitHub.java:384)
	at org.kohsuke.github.GitHub.<init>(GitHub.java:158)
	at org.kohsuke.github.GitHubBuilder.build(GitHubBuilder.java:207)
	at org.jenkinsci.plugins.ghprb.GhprbGitHubAuth.buildConnection(GhprbGitHubAuth.java:210)
	at org.jenkinsci.plugins.ghprb.GhprbGitHubAuth.getConnection(GhprbGitHubAuth.java:219)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.getGitHub(GhprbTrigger.java:513)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.initGhRepository(GhprbRepository.java:88)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.check(GhprbRepository.java:133)
	at org.jenkinsci.plugins.ghprb.GhprbTrigger.run(GhprbTrigger.java:371)
	at hudson.triggers.Trigger.checkTriggers(Trigger.java:278)
	at hudson.triggers.Trigger$Cron.doRun(Trigger.java:226)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:58)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

Seems to be again some authorization problem.

**Comment by Lineflyer** [comment]
Reopening:
PR builds seem to run smooth, but commit build fail as also the shared secret seemingly got lost or unsynced between Jenkins and Github.
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 400 Signature was expected, but not provided</title>
</head>
<body><h2>HTTP ERROR 400</h2>
<p>Problem accessing /github-webhook/. Reason:
<pre>    Signature was expected, but not provided</pre></p><hr><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.4.z-SNAPSHOT</a><hr/>

</body>
</html>
```

Will look into this tomorrow and setup new secrets.

**Comment by Lineflyer** [comment]
Functional again for building PRs.
Remaining issue: Token permissions need change to also react on PR comments like "retest..."

**Comment by Lineflyer** [comment]
Long story short: Now everything is working.

That is, what I assume happend (not sure though):
The Git PR/commit poll mechanisms on CI have been set to automatically manage their needed webhooks by using the access token of cgeo-ci-bot. That auto setup worked when setting up the jobs and CI was fine from then on.

Due to the change on Github in November (mandatory authorization) I had to create a new token as it needed new permissions and I wasn't in posession of the existing token. That all went fine, but I forgot to authorizes access to write hooks.
As the existing hooks were still working, this did not show up as a problem immediately.

Now Github recently changed that webhooks need to use a (previously optional) shared secret but seemingly our existing webhooks didn't have those so Jenkins started renewal but failed due to missing permission of the access token.

After providing an access token with appropriate permissions the automatic hook creation by Jenkins worked by the created hooks did not work for fetching changes to PRs / sync PRs. Therefore everything worked despite things like "retest this please", etc.

Finally I disabled all the auto-hook management and created everything manually.
I tested for cgeo and WhereYouGo:
- New PR build
- PR rebuilding
- Commit building (after push)

I took some notes and will try to write down the working mechanism into our Wiki (in case something like that happens again). I find this relatively confusing as three different credentials/secrets are involved....but at least I learned something ;)

**Comment by Lineflyer** [comment]
Wiki documentation has been amended with a section "Configuration" describing the credentials needed and steps to configure on Jenkins:
https://github.com/cgeo/cgeo/wiki/Continuous-Integration
