### ISSUE TITLE
crash exporting waypoints that use global variables to Personal note 

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12341]
1. add some global vars
2. add waypoint with formula that uses those
3. "add/update waypoints" to export them to PCN

Using a build that should match 21-12-17-NB, based on https://github.com/cgeo/cgeo/commit/ecf6204b15d7ac2e2e0e0bdd0c6156dc339b6989

```
12-17 20:06:07.759  7462  7462 E cgeo    : [main] Unable to read calculator state information
12-17 20:06:07.759  7462  7462 E cgeo    : org.json.JSONException: Value PLAIN of type java.lang.String cannot be converted to JSONObject
12-17 20:06:07.759  7462  7462 E cgeo    :      at org.json.JSON.typeMismatch(JSON.java:112)
12-17 20:06:07.759  7462  7462 E cgeo    :      at org.json.JSONObject.<init>(JSONObject.java:169)
12-17 20:06:07.759  7462  7462 E cgeo    :      at org.json.JSONObject.<init>(JSONObject.java:182)
12-17 20:06:07.759  7462  7462 E cgeo    :      at cgeo.geocaching.models.CalcState.fromJSON(CalcState.java:92)
12-17 20:06:07.759  7462  7462 E cgeo    :      at cgeo.geocaching.models.WaypointParser.getParseableFormula(WaypointParser.java:436)
12-17 20:06:07.759  7462  7462 E cgeo    :      at cgeo.geocaching.models.WaypointParser.getParseableText(WaypointParser.java:405)
12-17 20:06:07.759  7462  7462 E cgeo    :      at cgeo.geocaching.models.WaypointParser.getParseableTextWithRestrictedUserNote(WaypointParser.java:377)
12-17 20:06:07.759  7462  7462 E cgeo    :      at cgeo.geocaching.models.WaypointParser.getParseableText(WaypointParser.java:356)
12-17 20:06:07.759  7462  7462 E cgeo    :      at cgeo.geocaching.models.WaypointParser.putParseableWaypointsInText(WaypointParser.java:340)
12-17 20:06:07.759  7462  7462 E cgeo    :      at cgeo.geocaching.CacheDetailActivity.storeWaypointsInPersonalNote(CacheDetailActivity.java:2728)
12-17 20:06:07.759  7462  7462 E cgeo    :      at cgeo.geocaching.CacheDetailActivity$DescriptionViewCreator.lambda$setContent$2(CacheDetailActivity.java:1695)
12-17 20:06:07.759  7462  7462 E cgeo    :      at cgeo.geocaching.CacheDetailActivity$DescriptionViewCreator.lambda$setContent$2$CacheDetailActivity$DescriptionViewCreator(Unknown Source:0)
12-17 20:06:07.759  7462  7462 E cgeo    :      at cgeo.geocaching.-$$Lambda$CacheDetailActivity$DescriptionViewCreator$aSRicv83d6S1MZ9PYk_iU7c_A8g.onClick(Unknown Source:4)
12-17 20:06:07.759  7462  7462 E cgeo    :      at android.view.View.performClick(View.java:7520)
12-17 20:06:07.759  7462  7462 E cgeo    :      at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
12-17 20:06:07.759  7462  7462 E cgeo    :      at android.view.View.performClickInternal(View.java:7489)
12-17 20:06:07.759  7462  7462 E cgeo    :      at android.view.View.access$3600(View.java:826)
12-17 20:06:07.759  7462  7462 E cgeo    :      at android.view.View$PerformClick.run(View.java:28555)
12-17 20:06:07.759  7462  7462 E cgeo    :      at android.os.Handler.handleCallback(Handler.java:938)
12-17 20:06:07.759  7462  7462 E cgeo    :      at android.os.Handler.dispatchMessage(Handler.java:99)
12-17 20:06:07.759  7462  7462 E cgeo    :      at android.os.Looper.loop(Looper.java:233)
12-17 20:06:07.759  7462  7462 E cgeo    :      at android.app.ActivityThread.main(ActivityThread.java:8010)
12-17 20:06:07.759  7462  7462 E cgeo    :      at java.lang.reflect.Method.invoke(Native Method)
12-17 20:06:07.759  7462  7462 E cgeo    :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
12-17 20:06:07.759  7462  7462 E cgeo    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
12-17 20:06:07.760  7462  7462 D AndroidRuntime: Shutting down VM
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge: Crash unexpectedly: java.lang.NullPointerException: Attempt to read from field 'cgeo.geocaching.settings.Settings$CoordInputFormatEnum cgeo.geocaching.models.CalcState.format' on a null object reference
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at cgeo.geocaching.models.WaypointParser.getParseableFormulaString(WaypointParser.java:452)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at cgeo.geocaching.models.WaypointParser.getParseableFormula(WaypointParser.java:438)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at cgeo.geocaching.models.WaypointParser.getParseableText(WaypointParser.java:405)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at cgeo.geocaching.models.WaypointParser.getParseableTextWithRestrictedUserNote(WaypointParser.java:377)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at cgeo.geocaching.models.WaypointParser.getParseableText(WaypointParser.java:356)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at cgeo.geocaching.models.WaypointParser.putParseableWaypointsInText(WaypointParser.java:340)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at cgeo.geocaching.CacheDetailActivity.storeWaypointsInPersonalNote(CacheDetailActivity.java:2728)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at cgeo.geocaching.CacheDetailActivity$DescriptionViewCreator.lambda$setContent$2(CacheDetailActivity.java:1695)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at cgeo.geocaching.CacheDetailActivity$DescriptionViewCreator.lambda$setContent$2$CacheDetailActivity$DescriptionViewCreator(Unknown Source:0)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at cgeo.geocaching.-$$Lambda$CacheDetailActivity$DescriptionViewCreator$aSRicv83d6S1MZ9PYk_iU7c_A8g.onClick(Unknown Source:4)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at android.view.View.performClick(View.java:7520)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at android.view.View.performClickInternal(View.java:7489)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at android.view.View.access$3600(View.java:826)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at android.view.View$PerformClick.run(View.java:28555)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at android.os.Handler.handleCallback(Handler.java:938)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at android.os.Looper.loop(Looper.java:233)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at android.app.ActivityThread.main(ActivityThread.java:8010)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at java.lang.reflect.Method.invoke(Native Method)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
12-17 20:06:07.760  7462  7462 I LSPosed-Bridge:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
12-17 20:06:07.760  7462  7462 E AndroidRuntime: FATAL EXCEPTION: main
12-17 20:06:07.760  7462  7462 E AndroidRuntime: Process: cgeo.geocaching, PID: 7462
12-17 20:06:07.760  7462  7462 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'cgeo.geocaching.settings.Settings$CoordInputFormatEnum cgeo.geocaching.models.CalcState.format' on a null object reference
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at cgeo.geocaching.models.WaypointParser.getParseableFormulaString(WaypointParser.java:452)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at cgeo.geocaching.models.WaypointParser.getParseableFormula(WaypointParser.java:438)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at cgeo.geocaching.models.WaypointParser.getParseableText(WaypointParser.java:405)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at cgeo.geocaching.models.WaypointParser.getParseableTextWithRestrictedUserNote(WaypointParser.java:377)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at cgeo.geocaching.models.WaypointParser.getParseableText(WaypointParser.java:356)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at cgeo.geocaching.models.WaypointParser.putParseableWaypointsInText(WaypointParser.java:340)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at cgeo.geocaching.CacheDetailActivity.storeWaypointsInPersonalNote(CacheDetailActivity.java:2728)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at cgeo.geocaching.CacheDetailActivity$DescriptionViewCreator.lambda$setContent$2(CacheDetailActivity.java:1695)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at cgeo.geocaching.CacheDetailActivity$DescriptionViewCreator.lambda$setContent$2$CacheDetailActivity$DescriptionViewCreator(Unknown Source:0)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at cgeo.geocaching.-$$Lambda$CacheDetailActivity$DescriptionViewCreator$aSRicv83d6S1MZ9PYk_iU7c_A8g.onClick(Unknown Source:4)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at android.view.View.performClick(View.java:7520)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7489)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at android.view.View.access$3600(View.java:826)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:28555)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:233)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8010)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
12-17 20:06:07.760  7462  7462 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
12-17 20:06:07.760  7462  7462 W cgeo    : [main] UncaughtException
12-17 20:06:07.760  7462  7462 W cgeo    : java.lang.NullPointerException: Attempt to read from field 'cgeo.geocaching.settings.Settings$CoordInputFormatEnum cgeo.geocaching.models.CalcState.format' on a null object reference
12-17 20:06:07.760  7462  7462 W cgeo    :      at cgeo.geocaching.models.WaypointParser.getParseableFormulaString(WaypointParser.java:452)
12-17 20:06:07.760  7462  7462 W cgeo    :      at cgeo.geocaching.models.WaypointParser.getParseableFormula(WaypointParser.java:438)
12-17 20:06:07.760  7462  7462 W cgeo    :      at cgeo.geocaching.models.WaypointParser.getParseableText(WaypointParser.java:405)
12-17 20:06:07.760  7462  7462 W cgeo    :      at cgeo.geocaching.models.WaypointParser.getParseableTextWithRestrictedUserNote(WaypointParser.java:377)
12-17 20:06:07.760  7462  7462 W cgeo    :      at cgeo.geocaching.models.WaypointParser.getParseableText(WaypointParser.java:356)
12-17 20:06:07.760  7462  7462 W cgeo    :      at cgeo.geocaching.models.WaypointParser.putParseableWaypointsInText(WaypointParser.java:340)
12-17 20:06:07.760  7462  7462 W cgeo    :      at cgeo.geocaching.CacheDetailActivity.storeWaypointsInPersonalNote(CacheDetailActivity.java:2728)
12-17 20:06:07.760  7462  7462 W cgeo    :      at cgeo.geocaching.CacheDetailActivity$DescriptionViewCreator.lambda$setContent$2(CacheDetailActivity.java:1695)
12-17 20:06:07.760  7462  7462 W cgeo    :      at cgeo.geocaching.CacheDetailActivity$DescriptionViewCreator.lambda$setContent$2$CacheDetailActivity$DescriptionViewCreator(Unknown Source:0)
12-17 20:06:07.760  7462  7462 W cgeo    :      at cgeo.geocaching.-$$Lambda$CacheDetailActivity$DescriptionViewCreator$aSRicv83d6S1MZ9PYk_iU7c_A8g.onClick(Unknown Source:4)
12-17 20:06:07.760  7462  7462 W cgeo    :      at android.view.View.performClick(View.java:7520)
12-17 20:06:07.760  7462  7462 W cgeo    :      at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
12-17 20:06:07.760  7462  7462 W cgeo    :      at android.view.View.performClickInternal(View.java:7489)
12-17 20:06:07.760  7462  7462 W cgeo    :      at android.view.View.access$3600(View.java:826)
12-17 20:06:07.760  7462  7462 W cgeo    :      at android.view.View$PerformClick.run(View.java:28555)
12-17 20:06:07.760  7462  7462 W cgeo    :      at android.os.Handler.handleCallback(Handler.java:938)
12-17 20:06:07.760  7462  7462 W cgeo    :      at android.os.Handler.dispatchMessage(Handler.java:99)
12-17 20:06:07.760  7462  7462 W cgeo    :      at android.os.Looper.loop(Looper.java:233)
12-17 20:06:07.760  7462  7462 W cgeo    :      at android.app.ActivityThread.main(ActivityThread.java:8010)
12-17 20:06:07.760  7462  7462 W cgeo    :      at java.lang.reflect.Method.invoke(Native Method)
12-17 20:06:07.760  7462  7462 W cgeo    :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
12-17 20:06:07.760  7462  7462 W cgeo    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
12-17 20:06:07.763  1806  7241 W ActivityTaskManager:   Force finishing activity cgeo.geocaching/.CacheDetailActivity

```

**Comment by eddiemuc** [comment]
Should be fixed by PR #12342
