### ISSUE TITLE
Crashes when using map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12371]
Lately the nightlies got unstable for me.
Cannot reproduce it but its in some scenario like:
- Have a list of stored caches (several types incl. labs)
- Map the list
- Maybe also enable live and disable again
- Look at some cache/wp popups and/or open details and return to map

After some iterations the app crashes and I am back on the dashboard.

Could it be related to the changed activity stack?

Running: 2021.12.20-NB

Logfile:

```
12-20 22:29:17.659 17954 22248 W cgeo    : [RxComputationThreadPool-1] UncaughtException
12-20 22:29:17.659 17954 22248 W cgeo    : java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.widget.TextView.getResources()' on a null object reference
12-20 22:29:17.659 17954 22248 W cgeo    : 	at cgeo.geocaching.network.SmileyImage.scaleImage(SmileyImage.java:29)
12-20 22:29:17.659 17954 22248 W cgeo    : 	at cgeo.geocaching.network.HtmlImage$1.loadFromDisk(HtmlImage.java:251)
12-20 22:29:17.659 17954 22248 W cgeo    : 	at cgeo.geocaching.network.HtmlImage$1.lambda$downloadAndSave$2(HtmlImage.java:274)
12-20 22:29:17.659 17954 22248 W cgeo    : 	at cgeo.geocaching.network.HtmlImage$1.lambda$downloadAndSave$2$HtmlImage$1(Unknown Source:0)
12-20 22:29:17.659 17954 22248 W cgeo    : 	at cgeo.geocaching.network.-$$Lambda$HtmlImage$1$hSTXcuM97z_Rw6Px8qKtpFuI59A.run(Unknown Source:4)
12-20 22:29:17.659 17954 22248 W cgeo    : 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
12-20 22:29:17.659 17954 22248 W cgeo    : 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
12-20 22:29:17.659 17954 22248 W cgeo    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-20 22:29:17.659 17954 22248 W cgeo    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
12-20 22:29:17.659 17954 22248 W cgeo    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-20 22:29:17.659 17954 22248 W cgeo    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-20 22:29:17.659 17954 22248 W cgeo    : 	at java.lang.Thread.run(Thread.java:923)
12-20 22:29:17.659 17954 22248 E AndroidRuntime: FATAL EXCEPTION: RxComputationThreadPool-1
12-20 22:29:17.659 17954 22248 E AndroidRuntime: Process: cgeo.geocaching, PID: 17954
12-20 22:29:17.659 17954 22248 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.widget.TextView.getResources()' on a null object reference
12-20 22:29:17.659 17954 22248 E AndroidRuntime: 	at cgeo.geocaching.network.SmileyImage.scaleImage(SmileyImage.java:29)
12-20 22:29:17.659 17954 22248 E AndroidRuntime: 	at cgeo.geocaching.network.HtmlImage$1.loadFromDisk(HtmlImage.java:251)
12-20 22:29:17.659 17954 22248 E AndroidRuntime: 	at cgeo.geocaching.network.HtmlImage$1.lambda$downloadAndSave$2(HtmlImage.java:274)
12-20 22:29:17.659 17954 22248 E AndroidRuntime: 	at cgeo.geocaching.network.HtmlImage$1.lambda$downloadAndSave$2$HtmlImage$1(Unknown Source:0)
12-20 22:29:17.659 17954 22248 E AndroidRuntime: 	at cgeo.geocaching.network.-$$Lambda$HtmlImage$1$hSTXcuM97z_Rw6Px8qKtpFuI59A.run(Unknown Source:4)
12-20 22:29:17.659 17954 22248 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
12-20 22:29:17.659 17954 22248 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
12-20 22:29:17.659 17954 22248 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-20 22:29:17.659 17954 22248 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
12-20 22:29:17.659 17954 22248 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-20 22:29:17.659 17954 22248 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-20 22:29:17.659 17954 22248 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by Lineflyer** [comment]
I am not using the combined mode, so your issue could be just another one.

If you manage to crash it again, pleae use Settings - System - Generate logfile and attach it either here or send to support@cgeo.org refering to this issue.

And also provide your systeminformation. You can find it in About cgeo - System tab.

**Comment by Lineflyer** [comment]
@eosti 
Thanks for sending the infos and sorry for the delay.
I opened a dedicated issue for that: https://github.com/cgeo/cgeo/issues/12430

**Comment by moving-bits** [comment]
Won't fix. Old map implementations are deprecated as of release 2025.07.17 and superseded by UnifiedMap.
