### ISSUE TITLE
Variable tab - NPE after selecting patterns from scan listing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12406]
### Describe your problem!

I managed to make the app crash when trying out the "Scan listing" functions on the variable tab.
No idea if what I did makes sense but at least it should not crash.

### How to reproduce?

- Open GC8P68F
- Go to variable tab
- Use "Scan Listing"
- It will find 4 patterns
- Select the first two patterns: `(3574-Y)` and `(3742-X)`
- Click OK

### Actual result after these steps?

Crash:

```
2021-12-25 19:28:52.213 7953-7953/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 7953
    java.lang.NullPointerException: rhs == null
        at java.lang.String.compareTo(Native Method)
        at cgeo.geocaching.utils.formulas.VariableList.getSortedPos(VariableList.java:92)
        at cgeo.geocaching.ui.VariableListView$VariablesListAdapter.addVariable(VariableListView.java:341)
        at cgeo.geocaching.VariablesViewPageFragment.lambda$scanCache$11(VariablesViewPageFragment.java:150)
        at cgeo.geocaching.VariablesViewPageFragment.lambda$scanCache$11$VariablesViewPageFragment(Unknown Source:0)
        at cgeo.geocaching.-$$Lambda$VariablesViewPageFragment$a2wnPBo8xDgpakmCyin8g32CaKM.accept(Unknown Source:4)
        at cgeo.geocaching.ui.dialog.SimpleDialog.lambda$selectMultiple$7(SimpleDialog.java:402)
        at cgeo.geocaching.ui.dialog.-$$Lambda$SimpleDialog$rvc72q66gbEcPx-_99eo1KIzVUc.onClick(Unknown Source:4)
        at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

### Expected result after these steps?

No crash

### Reproducible

Yes

### c:geo Version

2021.12.25-NB

### System information

```text
Samsung S20, Android 11
```

**Comment by eddiemuc** [comment]
Clear bug on my side, will fix
