### ISSUE TITLE
Crash when trying to change waypoint name

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12556]
### Describe your problem!

A user has the reproducable problem, that c:geo crashes when trying to change the name of a "Go to" target. Not sure if changing a waypoint name in a "normal cache" has the same problem.

In a first try I was unable to reproduce it, maybe some other precondition or depending on Android version.

### How to reproduce?

- User creates new ZZ0 waypoint by triggering c:geo from the ALC app
- User long taps on that waypoint in ZZ0 and selects "Edit"
- Waypoint edit dialog is shown and users taps on the waypoint name field

See also video from user:

https://user-images.githubusercontent.com/949669/149926381-a3e1a38a-15c8-4f84-b583-672644c1392d.mp4

### Actual result after these steps?

- Crash

```
01-18 11:42:13.202 30862 30862 E AndroidRuntime: FATAL EXCEPTION: main
01-18 11:42:13.202 30862 30862 E AndroidRuntime: Process: cgeo.geocaching, PID: 30862
01-18 11:42:13.202 30862 30862 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.getBoundsOnScreen(android.graphics.Rect)' on a null object reference
01-18 11:42:13.202 30862 30862 E AndroidRuntime: 	at android.app.assist.AssistStructure$WindowNode.<init>(AssistStructure.java:484)
01-18 11:42:13.202 30862 30862 E AndroidRuntime: 	at android.app.assist.AssistStructure.<init>(AssistStructure.java:1908)
01-18 11:42:13.202 30862 30862 E AndroidRuntime: 	at android.app.ActivityThread.handleRequestAssistContextExtras(ActivityThread.java:3580)
01-18 11:42:13.202 30862 30862 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2238)
01-18 11:42:13.202 30862 30862 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:108)
01-18 11:42:13.202 30862 30862 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:166)
01-18 11:42:13.202 30862 30862 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7529)
01-18 11:42:13.202 30862 30862 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-18 11:42:13.202 30862 30862 E AndroidRuntime: 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
01-18 11:42:13.202 30862 30862 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
```

### Expected result after these steps?

Normal operation, no crash

### Reproducible

Unclear

### c:geo Version

2021.12.24

### System information

```text
## System information

c:geo version: 2021.12.24

Device:
-------
- Device type: WAS-LX1A (WAS-LX1A, HUAWEI)
- Available processors: 8
- Android version: 8.0.0
- Android build: WAS-LX1A 8.0.0.394(C432)
- Screen resolution: 1080x1794px (360x574dp)
- Pixel density: 3.4499998
- System font scale: 1.15 / used scale: 1.15
- Sailfish OS detected: false
- Google Play services: disabled - 21.48.15 (040408-414534850)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v8, Count:138
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Time zone: GMT+01:00
- Debug mode active: yes
- Last backup: never
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Kombiniert (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMultiMapSource
  - Atts: CzechRepublic_openmaps_eu_europe.map: / (C) 2007-2018 OpenMaps.eu /  / Freizeitkarte_DEU+OST.map: / (c) Map: FZK project (free for private use); Map data: OpenStreetMap contributors; Contour data: U.S. Geological Survey and J. de Ferranti /  / germany.map: / mapsforge-map-writer-master-SNAPSHOT /  / poland.map: / mapsforge-map-writer-master-SNAPSHOT
  - Theme: none

Filters:
-------
- Hide waypoints: original
- LIVE: Cache-Typ:11 Elemente,Status:4 Elemente ([:inconclusive=false:advanced=false]AND(type:MULTI:EVENT:WEBCAM:EARTH:TRADITIONAL:USER_DEFINED:WHERIGO:VIRTUAL:CITO:LETTERBOX:MYSTERY;difficulty_terrain:d=-:d=-:t=-:t=-;status:owned_no:found_no:exclude_disabled:exclude_archived))
- OFFLINE: Keine ([:inconclusive=false:advanced=false])

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   Geocaching.com Adventure Lab
- Geocaching.com date format: dd/MMM/yyyy
- Routing: external / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (7,2 GB free) v3 internal isDir(10 entries)
- Legacy User storage c:geo dir: /storage/3639-3533/cgeo (15,3 GB free) v3 external removable isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (7,1 GB free) v3 external non-removable isDir(177 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (7,2 GB free) v3 internal isDir(0 entries)
- Public Folders: #11
  - BASE: SD-Karte/cgeo (User-Defined)[SD-Karte/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo/document/3639-3533%3Acgeo, Av:true, files:>=2, dirs:>=10, totalFileSize:>=22,3 KB, free space: 15,3 GB, files on device: 0)
  - OFFLINE_MAPS: SD-Karte/Maps (User-Defined)[SD-Karte/Maps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/3639-3533%3AMaps::]] (Uri: content://com.android.externalstorage.documents/tree/3639-3533%3AMaps/document/3639-3533%3AMaps, Av:true, files:4, dirs:1, totalFileSize:3,6 GB, free space: 15,3 GB, files on device: 0)
  - OFFLINE_MAP_THEMES: SD-Karte/Maps/_themes (Default)[SD-Karte/Maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/3639-3533%3AMaps::/_themes]] (Uri: content://com.android.externalstorage.documents/tree/3639-3533%3AMaps/document/3639-3533%3AMaps%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 15,3 GB, files on device: 0)
  - LOGFILES: SD-Karte/cgeo/logfiles (Default)[SD-Karte/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo/document/3639-3533%3Acgeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:21,7 KB, free space: 15,3 GB, files on device: 0)
  - GPX: SD-Karte/cgeo/gpx (Default)[SD-Karte/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo/document/3639-3533%3Acgeo%2Fgpx, Av:true, files:1, dirs:0, totalFileSize:606 B, free space: 15,3 GB, files on device: 0)
  - BACKUP: SD-Karte/cgeo/backup (Default)[SD-Karte/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo/document/3639-3533%3Acgeo%2Fbackup, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 15,3 GB, files on device: 0)
  - FIELD_NOTES: SD-Karte/cgeo/field-notes (Default)[SD-Karte/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo/document/3639-3533%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 15,3 GB, files on device: 0)
  - SPOILER_IMAGES: SD-Karte/cgeo/GeocachePhotos (Default)[SD-Karte/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo/document/3639-3533%3Acgeo%2FGeocachePhotos, Av:true, files:>=0, dirs:>=7, totalFileSize:>=0 B, free space: 15,3 GB, files on device: 0)
  - ROUTING_BASE: SD-Karte/cgeo/routing (Default)[SD-Karte/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo/document/3639-3533%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81,2 KB, free space: 15,3 GB, files on device: 0)
  - ROUTING_TILES: SD-Karte/cgeo/routing/segments4 (Default)[SD-Karte/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo/document/3639-3533%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 15,3 GB, files on device: 0)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 7,2 GB, files on device: -1)
- Map render theme path:
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #2
  - content://com.android.externalstorage.documents/tree/3639-3533%3AMaps (17. Apr. 2021, 09:44):RW
  - content://com.android.externalstorage.documents/tree/3639-3533%3Acgeo (17. Apr. 2021, 09:43):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v98, Size:17,2 MB) on system internal storage

--- End of system information ---
```

### Additional Information

Support ticket 401802

**Comment by Lineflyer** [comment]
@cgeo/team 
Can someone take a look on this issue (the NPE involved might be easy to fix?!)?

**Comment by ztNFny** [comment]
This is missing a reproducable scenario. In the video the waypoint is named "undefined", it seems to be broken already when the video starts. Question is how it came to this.

**Comment by eddiemuc** [comment]
I found this: https://stackoverflow.com/questions/51351208/crash-happening-only-in-android-8

**Comment by eddiemuc** [comment]
If the error described in above link is the problem, then PR #12666 will fix it

**Comment by Lineflyer** [comment]
> This is missing a reproducable scenario. In the video the waypoint is named "undefined", it seems to be broken already when the video starts. Question is how it came to this.

The undefined name is probably unrelated.
As mentioned in the post below it happens to the user for all waypoints/in all caches.

**Comment by eddiemuc** [comment]
I will merge PR #12666 in the hope that it fixes the problem. This hope is solely backed by the information in the SO linked above. But I can't be sure because I am unable to reproduce the problem in the first place.... Anyway the PR shouldn't hurt either.

**Comment by eddiemuc** [comment]
This issue was autoclosed incorrectly since my PR is only based on a guess, I couldn't reproduce (I should probably not use the term "trying to fix #xyz" :-))

I will reopen. Should be closed when code change is in beta and fix (hopefully) confirmed by user.

**Comment by moving-bits** [comment]
Duplicate of #11981?

**Comment by Lineflyer** [comment]
No negative feedback from user, lets regard this as fixed then.
