### ISSUE TITLE
Failure in LogTemplateProviderTest.testNoNumberIncrement

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#12937]
```
java.lang.NumberFormatException: For input string: ""
	at java.lang.Integer.parseInt(Integer.java:627)
	at java.lang.Integer.parseInt(Integer.java:650)
	at cgeo.geocaching.log.LogTemplateProviderTest.testNoNumberIncrement(LogTemplateProviderTest.java:72)
```

Both withIncrement and withoutIncrement are ""

#10107 addressed a similar issue. I cleared all offline logs but it's still failing

**Comment by fm-sys** [comment]
The template `[ONLINENUM]` will return "" for GC45GGA, if there is no GC user successfully logged in... (or the user has 0 finds?)

https://github.com/cgeo/cgeo/blob/446483ae2b9239f1f21f86f23806a77cc50a08ea/tests/src-android/cgeo/geocaching/log/LogTemplateProviderTest.java#L65-L75

**Comment by nmrsmn** [comment]
> The template `[ONLINENUM]` will return "" for GC45GGA, if there is no GC user successfully logged in... (or the user has 0 finds?)

Is there a way to fake or even mock the login proces? If so, we can alter the test to use fake user and set its caches found to whatever number and then the test won't fail anymore (unless the code is broken offcourse)
