### ISSUE TITLE
NullPointerException on reselecting offline map source 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#12963]
### Describe your problem!

```
--------- beginning of crash
05-04 15:41:29.980 13666 13792 E AndroidRuntime: FATAL EXCEPTION: LayerManager
05-04 15:41:29.980 13666 13792 E AndroidRuntime: Process: cgeo.geocaching, PID: 13666
05-04 15:41:29.980 13666 13792 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
05-04 15:41:29.980 13666 13792 E AndroidRuntime: 	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
05-04 15:41:29.980 13666 13792 E AndroidRuntime: 	at android.graphics.Canvas.drawBitmap(Canvas.java:1336)
05-04 15:41:29.980 13666 13792 E AndroidRuntime: 	at org.mapsforge.map.android.graphics.AndroidCanvas.drawBitmap(AndroidCanvas.java:119)
05-04 15:41:29.980 13666 13792 E AndroidRuntime: 	at org.mapsforge.map.layer.TileLayer.draw(TileLayer.java:114)
05-04 15:41:29.980 13666 13792 E AndroidRuntime: 	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
05-04 15:41:29.980 13666 13792 E AndroidRuntime: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
05-04 15:41:30.037 13666 13666 W cgeo    : [main] UncaughtException
05-04 15:41:30.037 13666 13666 W cgeo    : java.util.ConcurrentModificationException
05-04 15:41:30.037 13666 13666 W cgeo    : 	at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:411)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at java.util.LinkedHashMap$ValueIterator.next(LinkedHashMap.java:426)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at org.mapsforge.map.layer.cache.InMemoryTileCache.purge(InMemoryTileCache.java:82)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at org.mapsforge.map.layer.cache.TwoLevelTileCache.purge(TwoLevelTileCache.java:80)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.RenderThemeHelper.reapplyMapTheme(RenderThemeHelper.java:186)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.NewMap.switchTileLayer(NewMap.java:709)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.NewMap.changeMapSource(NewMap.java:641)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.NewMap.onOptionsItemSelected(NewMap.java:502)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at android.app.Activity.onMenuItemSelected(Activity.java:3356)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:352)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at androidx.appcompat.app.AppCompatDelegateImpl.onMenuItemSelected(AppCompatDelegateImpl.java:1179)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:91)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at android.widget.AdapterView.performItemClick(AdapterView.java:313)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at android.widget.AbsListView.performItemClick(AbsListView.java:1201)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3195)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at android.widget.AbsListView.onTouchUp(AbsListView.java:4152)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at android.widget.HwAbsListView.onTouchUp(HwAbsListView.java:514)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:3896)
05-04 15:41:30.037 13666 13666 W cgeo    : 	at 
```

### How to reproduce?

c:geo crashes when reselecting the current map provider. Only happens if an offline map is currently used. 

### Reproducible

Yes

### c:geo Version

2022.03.10

**Comment by moving-bits** [comment]
> c:geo crashes when reselecting the current map provider. Only happens if an offline map is currently used.

Do you have some additional info to your c:geo environment?

Cannot reproduce the described behavior, with neither 2022.03.10 nor with current RC.
(Tried with a couple of OAM and Mapsforge offline maps, with both default theme and Elevate theme.)

**Comment by fm-sys** [comment]
To be honest, I can not reproduce the bug myself. It happend on the device of a fellow cacher and was permanently reproducible.

The device was running Android 7, he had downloaded a normal mapsforge offline map without additional theme.

 Complete log file: [logcat-2022-05-04-15-42-13-2.txt](https://github.com/cgeo/cgeo/files/8627180/logcat-2022-05-04-15-42-13-2.txt)

**Comment by eddiemuc** [comment]
In its core this seems to be a concurrency issue within mapsforge (probably we did not follow fully the guidelines of mapsforge, but who can tell?). It happens when tile cache is purged after a call to (re)set the theme (note: we also set a theme when no downloaded theme is available -> then we apply the mapsforge default theme).

This is really hard to analyze unfortunately.

We could wrap the "purge" call resulting in the exception in a try/catch-block and ignore the exception. Don't know about side effects though. What do you think?

**Comment by eddiemuc** [comment]
Another idea: since the problem seems to appear only when selection same map source again, we could add code not to do anything if user selects same map source again.

But my feeling would be that this is  not the root of the problem.
