### ISSUE TITLE
TransationTooLarge Exception when trying to open caches from map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12990]
### Describe your problem!

A single user reported the problem of frequent (but not strictly reproducible) crashes when using the map.

Things checked already:
- Deleted and deactivated Positions history (see #9188)
- Checked different map types and happens on all of them

Here is a video (Note: The video shows some broken position history, but as stated above we already tried removing it afterwards but it did not fix the problem):
https://www.dropbox.com/s/sxn6q6dmnxjd8nz/2022-05-09%2011.42.50-1.mp4

Any ideas how to debug?

### How to reproduce?

The problem usually appears when subsequently clicking on caches, open the popup and then after clicking "More details".

### Actual result after these steps?

Crash

```
05-09 19:40:12.867 31459 31459 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 622968)
05-09 19:40:12.868 31459 31459 W ActivityStopInfo: Bundle stats:
05-09 19:40:12.871 31459 31459 W ActivityStopInfo:   route [size=621920]
05-09 19:40:12.871 31459 31459 W ActivityStopInfo: PersistableBundle stats:
05-09 19:40:12.871 31459 31459 W ActivityStopInfo:   [null]
05-09 19:40:12.872 31459 31459 D AndroidRuntime: Shutting down VM
05-09 19:40:12.872 31459 31459 E AndroidRuntime: FATAL EXCEPTION: main
05-09 19:40:12.872 31459 31459 E AndroidRuntime: Process: cgeo.geocaching, PID: 31459
05-09 19:40:12.872 31459 31459 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 622968 bytes
05-09 19:40:12.872 31459 31459 E AndroidRuntime:     at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
05-09 19:40:12.872 31459 31459 E AndroidRuntime:     at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
05-09 19:40:12.872 31459 31459 E AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:938)
05-09 19:40:12.872 31459 31459 E AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
05-09 19:40:12.872 31459 31459 E AndroidRuntime:     at android.os.Looper.loopOnce(Looper.java:226)
05-09 19:40:12.872 31459 31459 E AndroidRuntime:     at android.os.Looper.loop(Looper.java:313)
05-09 19:40:12.872 31459 31459 E AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:8663)
05-09 19:40:12.872 31459 31459 E AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
05-09 19:40:12.872 31459 31459 E AndroidRuntime:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
05-09 19:40:12.872 31459 31459 E AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
05-09 19:40:12.872 31459 31459 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 622968 bytes
05-09 19:40:12.872 31459 31459 E AndroidRuntime:     at android.os.BinderProxy.transactNative(Native Method)
05-09 19:40:12.872 31459 31459 E AndroidRuntime:     at android.os.BinderProxy.transact(BinderProxy.java:635)
05-09 19:40:12.872 31459 31459 E AndroidRuntime:     at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1358)
05-09 19:40:12.872 31459 31459 E AndroidRuntime:     at android.app.ActivityClient.activityStopped(ActivityClient.java:83)
05-09 19:40:12.872 31459 31459 E AndroidRuntime:     ... 9 more
05-09 19:40:12.872 31459 31459 W cgeo    : [main] UncaughtException
05-09 19:40:12.872 31459 31459 W cgeo    : java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 622968 bytes
05-09 19:40:12.872 31459 31459 W cgeo    :     at android.app.ActivityClient.activityStopped(ActivityClient.java:86)
05-09 19:40:12.872 31459 31459 W cgeo    :     at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
05-09 19:40:12.872 31459 31459 W cgeo    :     at android.os.Handler.handleCallback(Handler.java:938)
05-09 19:40:12.872 31459 31459 W cgeo    :     at android.os.Handler.dispatchMessage(Handler.java:99)
05-09 19:40:12.872 31459 31459 W cgeo    :     at android.os.Looper.loopOnce(Looper.java:226)
05-09 19:40:12.872 31459 31459 W cgeo    :     at android.os.Looper.loop(Looper.java:313)
05-09 19:40:12.872 31459 31459 W cgeo    :     at android.app.ActivityThread.main(ActivityThread.java:8663)
05-09 19:40:12.872 31459 31459 W cgeo    :     at java.lang.reflect.Method.invoke(Native Method)
05-09 19:40:12.872 31459 31459 W cgeo    :     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
05-09 19:40:12.872 31459 31459 W cgeo    :     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
05-09 19:40:12.872 31459 31459 W cgeo    : Caused by: android.os.TransactionTooLargeException: data parcel size 622968 bytes
05-09 19:40:12.872 31459 31459 W cgeo    :     at android.os.BinderProxy.transactNative(Native Method)
05-09 19:40:12.872 31459 31459 W cgeo    :     at android.os.BinderProxy.transact(BinderProxy.java:635)
05-09 19:40:12.872 31459 31459 W cgeo    :     at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1358)
05-09 19:40:12.872 31459 31459 W cgeo    :     at android.app.ActivityClient.activityStopped(ActivityClient.java:83)
05-09 19:40:12.872 31459 31459 W cgeo    :     ... 9 more
05-09 19:40:12.883 31459 31459 I Process : Sending signal. PID: 31459 SIG: 9
05-09 19:40:13.142  2154  2154 E cgeo.geocachin: Not starting debugger since process cannot load the jdwp agent.
05-09 19:40:13.145  2154  2154 E USNET   : USNET: appName: cgeo.geocaching
05-09 19:40:13.145  2154  2154 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
```

### Expected result after these steps?

No crash

### Reproducible

Unclear

### c:geo Version

2022.03.10

### System information

```text
## System information

c:geo version: 2022.03.10

Device: - Device type: SM-G975F (beyond2lteeea, samsung)
- Available processors: 8
- Android version: 12
- Android build: SP1A.210812.016.G975FXXUEHVC6
- Screen resolution: 1080x2047px (411x779dp)
- Pixel density: 3.4125
- System font scale: 1.3 / used scale: 1.3
- Sailfish OS detected: false
- Google Play services: enabled - 22.12.15 (190400-439420056)

Sensor and location: - Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings: - Settings: v9, Count:200
- Set language: de_AT (system default)
- System date format: dd.MM.yy
- Time zone: GMT+02:00
- Debug mode active: no
- Last backup: 12. Feb., 19:28
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: true / threads: 4
- Map: Austria (Offline)
- Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:primary:Locus/mapsVector/Austria.map
- Atts: Map data (c) OpenStreetMap contributors
- Theme: Elevate.zip:Elements.xml

Filters: - Hide waypoints: -
- LIVE: Status:Gefunden=Nein,Eigener=Nein ([:inconclusive=false:advanced=true]AND(favorites:-:-:percentage=false;type;difficulty_terrain:d=-:d=-:t=-:t=-;status:owned_no:found_no))
- OFFLINE: Keine ([:inconclusive=false:advanced=true]AND(status;type;difficulty_terrain:d=-:d=-:t=-:t=-))

Stored Filters (#0):

Services: - Geocaching sites enabled:
geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com Adventure Lab
- Geocaching.com date format: yyyy-MM-dd
- Routing: internal / BRouter installed: true
- Installed c:geo plugins: contacts

Permissions & paths: - Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (277,2 GB free) v3 internal isDir(7 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (277,2 GB free) v3 internal isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (277,2 GB free) v3 external non-removable isDir(204 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (277,2 GB free) v3 internal isDir(9 entries)
- Public Folders: #11
- BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=20, dirs:>=9, totalFileSize:>=13,8 MB, free space: 277,2 GB, files on device: 15351808)
- OFFLINE_MAPS: /Locus/mapsVector (User-Defined)[/Locus/mapsVector[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector/document/primary%3ALocus%2FmapsVector, Av:true, files:55, dirs:1, totalFileSize:13,3 GB, free space: 277,2 GB, files on device: 15351808)
- OFFLINE_MAP_THEMES: /Locus/mapsVector/_themes (Default)[/Locus/mapsVector/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector::/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector/document/primary%3ALocus%2FmapsVector%2F_themes, Av:true, files:8, dirs:0, totalFileSize:1,5 MB, free space: 277,2 GB, files on device: 15351808)
- LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:6, dirs:0, totalFileSize:13,7 MB, free space: 277,2 GB, files on device: 15351808)
- GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 277,2 GB, files on device: 15351808)
- BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:5, dirs:2, totalFileSize:293,8 MB, free space: 277,2 GB, files on device: 15351808)
- FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:13, dirs:0, totalFileSize:105,5 KB, free space: 277,2 GB, files on device: 15351808)
- SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 277,2 GB, files on device: 15351808)
- ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:11, dirs:1, totalFileSize:516,8 MB, free space: 277,2 GB, files on device: 15351808)
- ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:4, dirs:0, totalFileSize:516,7 MB, free space: 277,2 GB, files on device: 15351808)
- TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 277,2 GB, files on device: -1)
- Map render theme path: Elevate.zip:Elements.xml
- PersistedDocumentUris: #1
- UNUSED_TRACK: null
- Persisted Uri Permissions: #2
- content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector (20. Jän., 21:27):RW
- content://com.android.externalstorage.documents/tree/primary%3Acgeo (17. Jän., 20:34):RW
- Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (v98, Size:149,2 MB) on user storage

--- End of system information ---
```

### Additional Information

Support ticket #379658

**Comment by Lineflyer** [comment]
It turned out the user has many stored adventure labs from lab2gpx. As soon as he removes those from the stored caches, the problem is gone.

If I interpret the exception correctly, its about the amount of data stored when saving the state of an activity....maybe due to the amount of caches stored?!
Anyway do we need to store the caches shown/filtered anyway, respectively couldn't we catch this problem and rather drop the saving than crashing the app?`

Does anyone have insights on this (also looking the the linked issues above @moving-bits @eddiemuc )?

I failed to reproduce this...but maybe its depending on the memory of the device or similar.

**Comment by gcey** [comment]
This a big problem for me and removing the caches imported from lab2gpx is just a workaround.
Does anyone know, how to correct this TransactionTooLarge problem?
Many thanks in advance!

**Comment by moving-bits** [comment]
Interesting background article regarding the `TransactionTooLargeException`, including a possible approach for resolving it:
https://medium.com/livefront/transactiontoolargeexception-and-a-bridge-to-safety-part-1-c3736644e26

**Comment by gcey** [comment]
> Interesting background article regarding the `TransactionTooLargeException`, including a possible approach for resolving it: https://medium.com/livefront/transactiontoolargeexception-and-a-bridge-to-safety-part-1-c3736644e26

This is very interesting and I think, it should be considered to change c:geo accordingly.
It seems that c:geo quite often fails to save its state: 
When c:geo is switched between foreground and background it often forgets its state (e.g. map position, ...).

**Comment by moving-bits** [comment]
We had a change regarding individual routes meanwhile (since quite some time, actually), which no longer get stored in-memory on pausing a map.

@gcey 
Does this error still happen for you, or can we close here?

**Comment by moving-bits** [comment]
Additional question, if it still happens: Which of the following map types are affected?
- "old" Google Maps
- "old" Mapsforge (OSM)
- new UnifiedMap Google Maps
- new UnifiedMap VTM (OSM)

**Comment by gcey** [comment]
I think, the error does not happen any more.

**Comment by moving-bits** [comment]
ok, thanks for the feedback. Then let's close here. Feel free to reopen with new info if it comes up again.
