### ISSUE TITLE
Waypoint of lab caches either not shown on OSM map or crash

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#12999]
### Describe your problem!

A user reported, that when he has lab caches or user defined caches with self created waypoints he very often has the problem, that 
1. not all of these waypoints are shown on the live map / list map
2. sometimes the map spontanously even crashes

The problem is only existing on OSM, Google is OK (see video).

### How to reproduce?

The user recorded a video:
https://www.youtube.com/watch?v=TspLZdv6yS8

and provided the used caches GPX:
[export.zip](https://github.com/cgeo/cgeo/files/8664441/export.zip)

### Actual result after these steps?

This is what I found in the logfile:
```
-------- beginning of crash
05-10 02:12:23.648  4183  4183 E AndroidRuntime: FATAL EXCEPTION: main
05-10 02:12:23.648  4183  4183 E AndroidRuntime: Process: cgeo.geocaching, PID: 4183
05-10 02:12:23.648  4183  4183 E AndroidRuntime: java.lang.IllegalStateException: layer is not assigned
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at org.mapsforge.map.layer.Layer.unassign(Layer.java:181)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at org.mapsforge.map.layer.Layers.remove(Layers.java:424)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at org.mapsforge.map.layer.Layers.remove(Layers.java:410)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.removeItems(AbstractCachesOverlay.java:358)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.invalidateAll(AbstractCachesOverlay.java:109)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.invalidateAll(CachesBundle.java:264)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at cgeo.geocaching.maps.mapsforge.v6.NewMap.checkCompactIconMode(NewMap.java:1693)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at cgeo.geocaching.maps.mapsforge.v6.NewMap.onChange(NewMap.java:1704)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at org.mapsforge.map.model.common.Observable.notifyObservers(Observable.java:46)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at org.mapsforge.map.model.MapViewPosition.setScaleFactor(MapViewPosition.java:423)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at org.mapsforge.map.model.MapViewPosition.setZoomLevelInternal(MapViewPosition.java:563)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at org.mapsforge.map.model.MapViewPosition.moveCenterAndZoom(MapViewPosition.java:330)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at org.mapsforge.map.model.MapViewPosition.moveCenter(MapViewPosition.java:294)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at org.mapsforge.map.android.input.TouchGestureHandler.onScroll(TouchGestureHandler.java:262)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.GestureDetector.onTouchEvent(GestureDetector.java:686)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at org.mapsforge.map.android.view.MapView.onTouchEvent(MapView.java:451)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at cgeo.geocaching.maps.mapsforge.v6.MfMapView.onTouchEvent(MfMapView.java:140)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:13464)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3107)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2763)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3113)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2777)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3113)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2777)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3113)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2777)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3113)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2777)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3113)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2777)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3113)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2777)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3113)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2777)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3113)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2777)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3113)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2777)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:466)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1851)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:4060)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:424)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:13728)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5664)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5458)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4957)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5010)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4976)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5116)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4984)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5173)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4957)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5010)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4976)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4984)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4957)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7764)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7733)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7684)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7903)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:188)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:178)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7850)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7927)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:791)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:719)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7399)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
05-10 02:12:23.648  4183  4183 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: FATAL EXCEPTION: main
05-10 10:30:58.429 26176 26176 E AndroidRuntime: Process: cgeo.geocaching, PID: 26176
05-10 10:30:58.429 26176 26176 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.EditWaypointActivity_}: java.lang.NullPointerException: Attempt to invoke virtual method 'cgeo.geocaching.enumerations.CacheType cgeo.geocaching.models.Geocache.getType()' on a null object reference
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3302)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3441)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7399)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'cgeo.geocaching.enumerations.CacheType cgeo.geocaching.models.Geocache.getType()' on a null object reference
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at cgeo.geocaching.EditWaypointActivity.getDefaultWaypointTypePosition(EditWaypointActivity.java:351)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at cgeo.geocaching.EditWaypointActivity.initializeWaypointTypeSelector(EditWaypointActivity.java:335)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at cgeo.geocaching.EditWaypointActivity.onCreate(EditWaypointActivity.java:235)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at cgeo.geocaching.EditWaypointActivity_.onCreate(EditWaypointActivity_.java:40)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7869)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7858)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3277)
05-10 10:30:58.429 26176 26176 E AndroidRuntime: 	... 11 more
05-10 10:31:22.954 27573 27573 E AndroidRuntime: FATAL EXCEPTION: main
05-10 10:31:22.954 27573 27573 E AndroidRuntime: Process: cgeo.geocaching, PID: 27573
05-10 10:31:22.954 27573 27573 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.EditWaypointActivity_}: java.lang.NullPointerException: Attempt to invoke virtual method 'cgeo.geocaching.enumerations.CacheType cgeo.geocaching.models.Geocache.getType()' on a null object reference
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3302)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3441)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2045)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7399)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:502)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'cgeo.geocaching.enumerations.CacheType cgeo.geocaching.models.Geocache.getType()' on a null object reference
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at cgeo.geocaching.EditWaypointActivity.getDefaultWaypointTypePosition(EditWaypointActivity.java:351)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at cgeo.geocaching.EditWaypointActivity.initializeWaypointTypeSelector(EditWaypointActivity.java:335)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at cgeo.geocaching.EditWaypointActivity.onCreate(EditWaypointActivity.java:235)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at cgeo.geocaching.EditWaypointActivity_.onCreate(EditWaypointActivity_.java:40)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7869)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7858)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3277)
05-10 10:31:22.954 27573 27573 E AndroidRuntime: 	... 11 more
```

### Expected result after these steps?

All waypoints shown, no crashes

### Reproducible

Yes

### c:geo Version

2022.03.10

### System information

```text
Ticket is older (older version) but still happens on 2022.03.10:

## System information

c:geo version: 2021.11.21

Device:
- Device type: Armor 8 Pro (Armor_8_Pro_8GB_EEA, Ulefone)
- Available processors: 8
- Android version: 11
- Android build: X70HEWS88C7.GQU.Ulefone_EEA.HB.FHJ.AZVF.20210611.V3.01
- Screen resolution: 720x1412px (360x704dp)
- Pixel density: 2.0
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 21.45.16 (150406-414021728)

Sensor and location:
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
- Settings: v8, Count:194
- Set language: de_AT (system default)
- System date format: dd.MM.yy
- Time zone: GMT+01:00
- Debug mode active: no
- Last backup: 25. Okt., 23:19
- Routing mode: Car
- Live map mode: true
- OSM multi-threading: true / threads: 4
- Map: Google: Karte
- Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleMapSource
- Atts: none
- Theme: Elevate.zip:Elements.xml

Filters:
- Hide waypoints: original visited
- LIVE: Cache-Typ:Adv Lab,Status:Gefunden=Nein ([:inconclusive=false:advanced=false]AND(type:ADVLAB;difficulty_terrain:d=-:d=-:t=-:t=-;status:found_no))
- OFFLINE: Cache-Typ:Adv Lab ([:inconclusive=false:advanced=false]AND(type:ADVLAB;difficulty_terrain:d=-:d=-:t=-:t=-;status))

Services:
- Geocaching sites enabled:
geocaching.com: Logged in (Anmeldung OK) / PREMIUM
Geocaching.com Adventure Lab
- Geocaching.com date format: yyyy-MM-dd
- Routing: internal / BRouter installed: false
- Installed c:geo plugins: none

Permissions & paths:
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (74,8 GB free) v2 internal isDir(6 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (74,8 GB free) v2 internal isDir(6 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (74,8 GB free) v2 external non-removable isDir(85 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (74,8 GB free) v2 internal isDir(3 entries)
- Public Folders: #11
- BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=13, dirs:>=11, totalFileSize:>=15,1 MB, free space: 74,8 GB, files on device: 7356416)
- OFFLINE_MAPS: /cgeo/maps (User-Defined)[/cgeo/maps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps, Av:true, files:4, dirs:1, totalFileSize:1,8 GB, free space: 74,8 GB, files on device: 7356416)
- OFFLINE_MAP_THEMES: /cgeo/gpx (User-Defined)[/cgeo/gpx[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx/document/primary%3Acgeo%2Fgpx, Av:true, files:2, dirs:0, totalFileSize:468,1 KB, free space: 74,8 GB, files on device: 7356416)
- LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:3,8 KB, free space: 74,8 GB, files on device: 7356416)
- GPX: /cgeo/gpx (User-Defined)[/cgeo/gpx[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx/document/primary%3Acgeo%2Fgpx, Av:true, files:2, dirs:0, totalFileSize:468,1 KB, free space: 74,8 GB, files on device: 7356416)
- BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:6, dirs:3, totalFileSize:15,0 MB, free space: 74,8 GB, files on device: 7356416)
- FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 74,8 GB, files on device: 7356416)
- SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 74,8 GB, files on device: 7356416)
- ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:10, dirs:1, totalFileSize:240,7 MB, free space: 74,8 GB, files on device: 7356416)
- ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:3, dirs:0, totalFileSize:240,6 MB, free space: 74,8 GB, files on device: 7356416)
- TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 74,8 GB, files on device: -1)
- Map render theme path: Elevate.zip:Elements.xml
- PersistedDocumentUris: #1
- TRACK: null
- Persisted Uri Permissions: #3
- content://com.android.externalstorage.documents/tree/primary%3Acgeo (23. Okt., 17:00):RW
- content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fgpx (23. Okt., 17:02):RW
- content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps (23. Okt., 17:02):RW
- Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (v98, Size:8,2 MB) on user storage

--- End of system information ---
```

### Additional Information

Support ticket #746335

**Comment by alan666notb** [comment]
Isn't this the same issue I reported in #12848 ?
I think there's a fix in the latest beta, but I haven't had a change to fully test it yet.

**Comment by Lineflyer** [comment]
Maybe the crash is unrelated to the waypoint vanishing problem...so the crash seems already solved at least.

**Comment by bekuno** [comment]
Point 1 sounds like #10652.

**Comment by Lineflyer** [comment]
> Point 1 sounds like #10652.

I dont think so, did you watch the video?

**Comment by bekuno** [comment]
>> Point 1 sounds like #10652.
> 
> I dont think so, did you watch the video?

Now I watched the video.
It is a different problem.

**Comment by Herr-Ma** [comment]
Have the same Problem with a fresh installed cgeo:

Waypoints from Labcaches will only shown on google maps. After switching to any osm map (online and offline) the waypoints are hidden. Switching back to google maps, all waypoints are shown again.

**Comment by moving-bits** [comment]
Does it still happen for _newly created_ waypoints?

We had some issues in the past with waypoints not getting assigned a specific internal field (not visible on the UI, but used by OSM maps to distinguish between different waypoints) - this should be solved meanwhile.

**Comment by moving-bits** [comment]
The yet missing "waypoints of labs not shown on OSM" part should probably be fixed with #14255 as well

**Comment by Lineflyer** [comment]
I will ask the user via Support ticket #746335 whether this problem is still existing with recent versions.

**Comment by moving-bits** [comment]
No feedback from the related user, so let's close here for now
