### ISSUE TITLE
NPE from Google Pre-Launch Report

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13011]
### Describe your problem!

After publishing 2022.05.13-RC the GooglePlayConsole reported a crash from the built-in app-crawling tests:

```
FATAL EXCEPTION: Thread-3
Process: cgeo.geocaching, PID: 18916
java.lang.NullPointerException: Attempt to read from field 'cgeo.geocaching.location.Geopoint cgeo.geocaching.location.Viewport.bottomLeft' on a null object reference
	at cgeo.geocaching.maps.CGeoMap.onOptionsItemSelected(CGeoMap.java:852)
	at cgeo.geocaching.maps.google.v2.GoogleMapActivity.onOptionsItemSelected(GoogleMapActivity.java:120)
	at android.app.Activity.onMenuItemSelected(Activity.java:3595)
	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:352)
	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:264)
	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:109)
	at androidx.appcompat.app.AppCompatDelegateImpl.onMenuItemSelected(AppCompatDelegateImpl.java:1179)
	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:834)
	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1333)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3310)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at androidx.test.espresso.base.Interrogator.loopAndInterrogate(Interrogator.java:10)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:7)
	at androidx.test.espresso.base.UiControllerImpl.loopUntil(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.injectMotionEvent(UiControllerImpl.java:5)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:6)
	at androidx.test.espresso.action.MotionEvents.sendUp(MotionEvents.java:1)
	at androidx.test.espresso.action.Tap.sendSingleTap(Tap.java:5)
	at androidx.test.espresso.action.Tap.-$$Nest$smsendSingleTap(Unknown Source:0)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:2)
	at androidx.test.espresso.ViewInteraction.doPerform(ViewInteraction.java:21)
	at androidx.test.espresso.ViewInteraction.-$$Nest$mdoPerform(Unknown Source:0)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:5)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:1)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6846)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:883)
```

### How to reproduce?

https://user-images.githubusercontent.com/949669/168400300-16c44f45-304d-44f8-85ef-5705d9d1f728.mp4

### Reproducible

Unclear

### c:geo Version

2022.05.13-RC

### System information

```text
Modellname
AQUOS sense2 SH-01L
Hersteller
DOCOMO
Android-Version
Android 9 (SDK 28)
Gebietsschema
it_CH
Bildschirmgröße
1080 x 2160
Bildschirmdichte (dpi)
480
RAM (Gesamtspeicherplatz)
3.072 MB
OpenGL ES-Version
3.2
ABI
ABI_ARM64_V8
CPU
Qualcomm SDM450
```

### Additional Information

https://play.google.com/console/developers/7945466068179931672/app/4975240647192321833/pre-launch-report/details?tab=stability&artifactId=4859682404250270256

**Comment by moving-bits** [comment]
Won't fix. Old map implementations are deprecated as of release 2025.07.17 and superseded by UnifiedMap.
