### ISSUE TITLE
Google Maps stopped working 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13205]
### Describe your problem!

With todays nightly 2022.06.26-NB Google Maps is no longer working for me.
Reproducible on real device as well as emulator (API 30) with current `master`.

### How to reproduce?

- Open map
- Set map type to Google street or satellite maps

### Actual result after these steps?

```
2022-06-26 18:25:28.584 25131-25131/cgeo.geocaching W/cgeo: [main] UncaughtException {OOMDumpingUncaughtExceptionHandler.lambda$installUncaughtExceptionHandler$0:26/-$$Lambda$OOMDumpingUncaughtExceptionHandler$h5ON7aCd5MQnyQ5bQnIb7zK8lvY.uncaughtException:2/ThreadGroup.uncaughtException:1073/ThreadGroup.uncaughtException:1068/Thread.dispatchUncaughtException:2203}
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.maps.google.v2.GoogleMapActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'android.content.Context cgeo.geocaching.maps.interfaces.MapViewImpl.getContext()' on a null object reference
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3365)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'android.content.Context cgeo.geocaching.maps.interfaces.MapViewImpl.getContext()' on a null object reference
        at cgeo.geocaching.maps.CGeoMap.<init>(CGeoMap.java:422)
        at cgeo.geocaching.maps.google.v2.GoogleMapActivity.<init>(GoogleMapActivity.java:57)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
```

### Expected result after these steps?

Normal operation

### Reproducible

Yes

### c:geo Version

2022.06.26-NB

### Additional Information

Support tickets eg: 685110

**Comment by moving-bits** [comment]
Probably fixed with #13218

**Comment by Lineflyer** [comment]
Its working again with todays nightly. 
@moving-bits Do you consider it suitably fixed so we can close or was it just a "quick hack" or some follow-up needed?

**Comment by moving-bits** [comment]
The fix itself is ok for this issue here, and the merge would have closed this issue, if I hadn't listed the wrong issue in the commit message... 

Whether the observer change introduced with #13184 still works, should be checker by @NotWoods, though, - I'll leave a comment for him in my PR.
