### ISSUE TITLE
No gc.com caches returned for searches

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13200]
### Describe your problem!

Using todays nightly (2022.06.26-NB) I have the problem, that searches do not return any caches from GC but only from OC.de (have both connectors active and logged in).

Live map is showing caches normally.

### How to reproduce?

Use search - Search for a location/coordinate or user

### Actual result after these steps?

No GC caches in result list

### Expected result after these steps?

GC caches in result list

### Reproducible

Yes

### c:geo Version

2022.06.26-NB

### Additional Information

```
2022-06-26 13:43:25.910 25117-25207/? W/cgeo: [network--9] parallelCombineActive: swallowing error from connector cgeo.geocaching.connector.gc.GCConnector@720fcae1 {SearchResult.lambda$parallelCombineActive$7:376/-$$Lambda$SearchResult$bkP3obAy-CSIm80iNz3q2k1Trgg.call:4/MaybeFromCallable.subscribeActual:47/Maybe.subscribe:5375/MaybeSubscribeOn$SubscribeTask.run:54/ScheduledDirectTask.call:38/ScheduledDirectTask.call:25/FutureTask.run:266}
    java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
        at cgeo.geocaching.connector.gc.GCWebAPI.searchCaches(GCWebAPI.java:928)
        at cgeo.geocaching.connector.gc.GCMap.searchByFilter(GCMap.java:108)
        at cgeo.geocaching.connector.gc.GCMap.searchByFilter(GCMap.java:85)
        at cgeo.geocaching.connector.gc.GCConnector.searchByFilter(GCConnector.java:317)
        at cgeo.geocaching.loaders.LiveFilterGeocacheListLoader.lambda$runSearch$0(LiveFilterGeocacheListLoader.java:28)
        at cgeo.geocaching.loaders.-$$Lambda$LiveFilterGeocacheListLoader$W2lFBaD1HdSJ-lD6tHP9rAcTc94.apply(Unknown Source:4)
        at cgeo.geocaching.SearchResult.lambda$parallelCombineActive$7(SearchResult.java:374)
        at cgeo.geocaching.-$$Lambda$SearchResult$bkP3obAy-CSIm80iNz3q2k1Trgg.call(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:47)
        at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5375)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

**Comment by moving-bits** [comment]
We had #13187 yesterday with changes in that area - maybe related to those?

I can't reproduce currently with current master. What type of search are you using? Do you have any filters applied?

**Comment by Lineflyer** [comment]
I tested again and deactivated all connectors except gc.com.

- Search for "Wuppertal"
- Result shows "No caches"
- No filter involved

Same for coordinate based search, keyword search, owner search. Only search by finder is working (but I guess this is using another method).

**Comment by moving-bits** [comment]
Strange. I had tried both address search ("Colorgne" in my case) and a coordinate search, and both returned results. I'm logged in with my regular geocaching account and have both GC and AL connectors enabled, none else.

**Comment by moving-bits** [comment]
Now it starts getting interesting: Did an address search for "Wuppertal" and have activated oc.de conector in the meantime: Now I'll get AL and oc.de caches only, but still no error message in LogCat.

**Comment by Lineflyer** [comment]
I had my IDE updated from `master`  some days ago. It worked on the emulator.
Now I just pulled again from `master` and I do see the same problem now in my emulator:

![image](https://user-images.githubusercontent.com/949669/175814165-e6e16124-2b02-4cca-8ff3-b47b5c0c9de7.png)


Only ALC returned on my emulator API 30, premium user, GC and ALC active

**Comment by moving-bits** [comment]
Ok, did a quick cross-test: When checking out e55274f75bf2a527559fafaf86b9083a8813312b (last commit before the changes of #13187), a search for "Wuppertal" still delivers caches from gc.com, so the culprit seems to be somewhere in that PR.

**Comment by moving-bits** [comment]
Have a fix for it, PR will follow
