### ISSUE TITLE
Problem opening map file 'content://com.android.externalstorage.documents/tree/...california.map'

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13265]
### Describe your problem!

While testing the current Mapsforge code, I stumbled across some errors.It looks like a download error, possible by a broken connection to the server.

~~~
022-07-24 11:45:34.676 9255-9255/cgeo.geocaching I/AndroidUtil: TILECACHE INMEMORY SIZE: 100
2022-07-24 11:45:34.677 9255-9255/cgeo.geocaching I/AndroidUtil: TILECACHE FILE SIZE: 2000
2022-07-24 11:45:34.733 9255-9255/cgeo.geocaching E/cgeo: [main] Problem opening map file 'content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Fmaps%2Fcalifornia.map'
    org.mapsforge.map.reader.header.MapFileException: reading magic byte has failed
        at org.mapsforge.map.reader.MapFile.<init>(MapFile.java:293)
        at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.createMapFile(MapsforgeMapProvider.java:345)
        at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider.access$300(MapsforgeMapProvider.java:49)
        at cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource.createTileLayer(MapsforgeMapProvider.java:150)
        at cgeo.geocaching.maps.mapsforge.v6.NewMap.switchTileLayer(NewMap.java:645)
        at cgeo.geocaching.maps.mapsforge.v6.NewMap.initializeLayers(NewMap.java:747)
        at cgeo.geocaching.maps.mapsforge.v6.NewMap.onStart(NewMap.java:742)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
        at android.app.Activity.performStart(Activity.java:8024)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3475)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
~~~

The system downloader shows "File not found error while receiving file".
Maybe we can catch this error?

### How to reproduce?

Unclear.
A second download later on was ok.

### Actual result after these steps?

The map name was shown in the list of (offline) maps.
After switching to it no map was shown.
Later on this entry was not more visible.

### Expected result after these steps?

The error should be catched and an info (toast?) should be shown.

### Reproducible

Unclear

### c:geo Version

PR #13264 at commit 44346a3d

### System information

```text
Virtual device API 30
```

**Comment by fm-sys** [comment]
The error is not directly related to the downloader but clames that a file inside the `/maps/` directory (California.map in this case) could not be validated as correct map file.

I've seen such errors in previous versions of mapsforge as well, while working in the emulator.

**Comment by Lineflyer** [comment]
Anything to be done for this issue? 
It looks like just the map file is not valid (corrupt, incomplete) and therefore the exception is thrown.

@bekuno Feel free to reopen.

**Comment by bekuno** [comment]
> Anything to be done for this issue?
> It looks like just the map file is not valid (corrupt, incomplete) and therefore the exception is thrown.

This is also my guess.
We should catch such problem and inform the user, imho. Maybe also delete the file after asking the user.
