### ISSUE TITLE
Map not recongized

### ISSUE THREAD

**Issue by pingurus** [cgeo/cgeo#13342]
### Describe your problem!

I downloaded the Germany (OAM) map via the integrated downloader, however the file is not picked up by c:geo. A subsequent download of Austria (OAM) was successful.

Not sure if it is related, but c:geo regularly crashes when trying to open the settings.

### How to reproduce?

1. Download with c:geo downloader
2. Map is not recognized by c:geo
3. Download another map to compare
4. See that *.map-cgeo.txt is missing for the first map
5. fake that file for the first map with adjusted contents
6. Map is still not recognized by c:geo

### Actual result after these steps?

first downloaded map is not recognized 

### Expected result after these steps?

The *cgeo_map.txt file should not be missing in the first place, but after supplying it, c:geo should recognize the map.

Maybe c:geo should even recognize the map without the *cgeo_map.txt file

### Reproducible

Unclear

### c:geo Version

2022.07.31

### System information

```text
## System information

c:geo version: 2022.07.31

Device:
-------
- Device type: SM-A520F (lineage_a5y17lte, samsung)
- Available processors: 8
- Android version: 11
- Android build: lineage_a5y17lte-userdebug 11 RQ3A.211001.001 eng.root.20220615.001155 dev-keys
- Screen resolution: 1080x1920px (360x616dp)
- Pixel density: 3.0
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 0.2.24.214816

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:149
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Time zone: GMT+02:00
- Debug mode active: no
- Last backup: never
- Routing mode: Bike
- Live map mode: false
- OSM multi-threading: false / threads: 1
- Map: Austria (OAM) (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:primary:cgeo/maps/Austria (OAM).map
  - Atts: Maps: (c)Christian Kernbeis & Michael Bechtold , Themes: (c)Tobias Kuehn, www.openandromaps.org 2012-2022
  - Theme: Elevate.zip:Elements.xml

Filters:
-------
- Hide waypoints: -
- LIVE: Schwierigkeit / Gelände:*-4.0 / *-*,Cache-Typ:8 Elemente ([:inconclusive=false:advanced=true]AND(difficulty_terrain:d=-:d=4.0:t=-:t=-;type:EARTH:ADVLAB:VIRTUAL:USER_DEFINED:TRADITIONAL:WEBCAM:LETTERBOX:WHERIGO))
- OFFLINE: Keine ([:inconclusive=false:advanced=false])

Stored Filters (#0):

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
- Geocaching.com date format: dd.MM.yyyy
- Last successful login on geocaching.com: 2022-08-17 08-16
- Routing: external / BRouter installed: true
- Installed c:geo plugins: contacts

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (1,1 GB free) v3 internal isDir(9 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (1,1 GB free) v3 external non-removable isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (1,1 GB free) v3 external non-removable isDir(23 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (1,1 GB free) v3 internal isDir(3 entries)
- Public Folders: #11
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=10, dirs:>=9, totalFileSize:>=5,1 GB, free space: 1,1 GB, files on device: 1558560)
  - OFFLINE_MAPS: /cgeo/maps (Default)[/cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps, Av:true, files:6, dirs:1, totalFileSize:5,0 GB, free space: 1,1 GB, files on device: 1558560)
  - OFFLINE_MAP_THEMES: /cgeo/maps/_themes (Default)[/cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps%2F_themes, Av:true, files:2, dirs:0, totalFileSize:509,0 KB, free space: 1,1 GB, files on device: 1558560)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,1 GB, files on device: 1558560)
  - GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:4, dirs:0, totalFileSize:1,4 MB, free space: 1,1 GB, files on device: 1558560)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:>=8, dirs:>=5, totalFileSize:>=1,8 MB, free space: 1,1 GB, files on device: 1558560)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,1 GB, files on device: 1558560)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,1 GB, files on device: 1558560)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81,2 KB, free space: 1,1 GB, files on device: 1558560)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,1 GB, files on device: 1558560)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,1 GB, files on device: -1)
- Map render theme path: Elevate.zip:Elements.xml
- PersistedDocumentUris: #1
- UNUSED_TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (19. Juni 2021, 07:46):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v98, Size:440,0 KB) on system internal storage

--- End of system information ---
```

### Additional Information

--------- beginning of crash
08-17 07:39:18.155 14221 14251 E AndroidRuntime: FATAL EXCEPTION: IntentService[ReceiveDownloadService]
08-17 07:39:18.155 14221 14251 E AndroidRuntime: Process: cgeo.geocaching, PID: 14221
08-17 07:39:18.155 14221 14251 E AndroidRuntime: android.database.sqlite.SQLiteFullException: database or disk is full (code 13 SQLITE_FULL)
08-17 07:39:18.155 14221 14251 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:182)
08-17 07:39:18.155 14221 14251 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
08-17 07:39:18.155 14221 14251 E AndroidRuntime: 	at android.content.ContentProviderProxy.delete(ContentProviderNative.java:624)
08-17 07:39:18.155 14221 14251 E AndroidRuntime: 	at android.content.ContentResolver.delete(ContentResolver.java:2289)
08-17 07:39:18.155 14221 14251 E AndroidRuntime: 	at android.content.ContentResolver.delete(ContentResolver.java:2255)
08-17 07:39:18.155 14221 14251 E AndroidRuntime: 	at cgeo.geocaching.downloader.ReceiveDownloadService.copyInternal(ReceiveDownloadService.java:236)
08-17 07:39:18.155 14221 14251 E AndroidRuntime: 	at cgeo.geocaching.downloader.ReceiveDownloadService.handleMapFile(ReceiveDownloadService.java:162)
08-17 07:39:18.155 14221 14251 E AndroidRuntime: 	at cgeo.geocaching.downloader.ReceiveDownloadService.onHandleIntent(ReceiveDownloadService.java:101)
08-17 07:39:18.155 14221 14251 E AndroidRuntime: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:77)
08-17 07:39:18.155 14221 14251 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-17 07:39:18.155 14221 14251 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
08-17 07:39:18.155 14221 14251 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by pingurus** [comment]
Re-downloading fixed the issue. I guess one possible solution would be to alert the user that the download failed, which didn't happen in my case.

**Comment by moving-bits** [comment]
There have been a couple of improvements in this area since back then:
- partial downloads get cleared (files removed) if they cannot be resumed
- old map files with numbering get cleared on copying the new map file

Regarding the "c:geo should recognize the map without the *cgeo_map.txt file": This should already be the case, as not everybody is using the integrated downloader. I guess there has been some access rights problem (Android is somewhat unstable and inconsistent in this area). This can be resolved in most cases by regranting c:geo access to the configured map folder.

Thus let's close here for now. Feel free to reopen here or open a new issue, if further problems arise.
