### ISSUE TITLE
Allow resume of broken downloads

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13415]
### Tell us your idea!

On support mail 2-3 users informed us, that they have the feeling, that the background download of caches often fails to complete, e.g. like this:
![grafik](https://user-images.githubusercontent.com/949669/190089825-d72c3be9-10b1-4f19-a326-6d65e7f30b2a.png)

In the logs I could see, connection problems to geocaching.com which makes it look like its not a c:geo issue:
```
08-29 12:29:39.993 27741 29430 W cgeo    : [OkHttp] Failure (36 ms) GET https://www.geocaching.com/seek/cache_details.aspx?decrypt=y&wp=GC8ANVD&log=y&numlogs=0 (java.net.ConnectException: Failed to connect to www.geocaching.com/63.251.163.200:443)
08-29 12:29:39.996 27741 29302 E cgeo    : [refresh--3] Exception in GCLogin.getRequestLogged
08-29 12:29:39.996 27741 29302 E cgeo    : java.lang.RuntimeException: java.net.ConnectException: Failed to connect to www.geocaching.com/63.251.163.200:443
08-29 12:29:39.996 27741 29302 E cgeo    : 	at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3645)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at cgeo.geocaching.connector.gc.GCLogin.getRequestLogged(GCLogin.java:542)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at cgeo.geocaching.connector.gc.GCParser.requestHtmlPage(GCParser.java:1362)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at cgeo.geocaching.connector.gc.GCConnector.searchByGeocode(GCConnector.java:253)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at cgeo.geocaching.models.Geocache.searchByGeocode(Geocache.java:2066)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at cgeo.geocaching.models.Geocache.storeCache(Geocache.java:1966)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at cgeo.geocaching.service.CacheDownloaderService.handleDownload(CacheDownloaderService.java:215)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at cgeo.geocaching.service.CacheDownloaderService.lambda$onHandleIntent$2(CacheDownloaderService.java:177)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at cgeo.geocaching.service.CacheDownloaderService.lambda$onHandleIntent$2$CacheDownloaderService(Unknown Source:0)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at cgeo.geocaching.service.-$$Lambda$CacheDownloaderService$r6J1-U8ToSaXmq0u6A5N-_0MBdk.subscribe(Unknown Source:4)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at io.reactivex.rxjava3.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:41)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at io.reactivex.rxjava3.core.Observable.subscribe(Observable.java:13173)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
08-29 12:29:39.996 27741 29302 E cgeo    : 	at java.lang.Thread.run(Thread.java:1012)
```

### What solution would you suggest?

1. As the user claims he often refreshes his dedicated cache list and never had any trouble in older versions (w/o background download) but now most of the time experiences such problem, we should investigate if it can still be our issue
2. It would be good to have a user option to resume the download (only loading the not yet downloaded caches) from the notification

### Is there an alternative?

At this moment the user can only restart the whole action (meaning download all caches again), which generated unnecessary traffic and potentially leads to the same interruption after some time.

### Additional Information

Support ticket 947386

**Comment by fm-sys** [comment]
I guess the failure is caused by wifi / mobile network being unavailable. However, we should handle this in a more appropriate way... E.g. wait until network becomes available and restart automatically.

A resume possibility however sounds good as well.

**Comment by Lineflyer** [comment]
Could this notification directly offer two options "Dismiss" and "Resume"?

**Comment by fm-sys** [comment]
> Could this notification directly offer two options "Dismiss" and "Resume"?

Wouldn't "dismiss" be effectively the same than swiping away the notification?

**Comment by moving-bits** [comment]
Related to / possible duplicate of #13408

**Comment by moving-bits** [comment]
I've added "cache" to the issue title to distinguish it from downloads using the built-in downloader (eg: maps, routing data), which do have a resume functionality meanwhile. Downloading caches in background is handled differently.

**Comment by moving-bits** [comment]
See also #15378 (closing that one as duplicate)
