### ISSUE TITLE
testBRouterTiles fails

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13485]
### Describe your problem!

New error on CI.
Details from
https://ci.cgeo.org/job/cgeo-CI_PR-build/2973/testReport/cgeo.geocaching.downloader/DownloaderTest/testBRouterTiles/ :

<b>Regression</b>

cgeo.geocaching.downloader.DownloaderTest.testBRouterTiles (from cgeo.geocaching.CgeoApplicationTest) 

<b>Stacktrace</b>

java.lang.AssertionError:
Expecting:
<1132>
to be between:
[1115, 1130]
at cgeo.geocaching.downloader.DownloaderTest.testBRouterTiles(DownloaderTest.java:158)
at java.lang.reflect.Method.invoke(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)

### How to reproduce?

run the cgeo.geocaching.CgeoApplicationTest

### Reproducible

Yes

### c:geo Version

CI  Build #2973

**Comment by bekuno** [comment]
Now the elements count of https://brouter.de/brouter/segments4/ is really 1132.
