### ISSUE TITLE
cgeo test errors "Unparseable date"

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13568]
### Describe your problem!

This errors are long known to me. (I think I got the errors already on the first test yers ago)
I supposed that this is only for me for a language library problem. And we got no such error on CI or from the field.
I got this error on different VM as long as on ma physical dev device (Android 7)
But now as we do not reset the language anymore this should deeper analyzed.
We tals already in the last (?) dev meeting about, and @fm-sys did some tests.

The errors are in the classTrackablesTest in the methods:
`testParseTrackableWithDiscoveredDate` and `testParseTrackableWithRetrievedDate` .
They fail with error
`E cgeo    : java.text.ParseException: Unparseable date: "09/16/2018"`
`E cgeo    : java.text.ParseException: Unparseable date: "10/18/2008"`

The full stack traces:
```
--------- beginning of main
10-29 10:31:22.596 10146  8242  8275 I TestRunner: started: testParseTrackableWithDiscoveredDate(cgeo.geocaching.connector.gc.TrackablesTest)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : [Instr: androidx.test.runner.AndroidJUnitRunner] GCParser.parseTrackable: Failed to parse log
10-29 10:31:22.605 10146  8242  8275 E cgeo    : java.text.ParseException: Unparseable date: "09/16/2018"
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at java.text.DateFormat.parse(DateFormat.java:362)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at cgeo.geocaching.connector.gc.GCLogin.parseGcCustomDate(GCLogin.java:408)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at cgeo.geocaching.connector.gc.GCLogin.parseGcCustomDate(GCLogin.java:412)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at cgeo.geocaching.connector.gc.GCParser.parseTrackable(GCParser.java:1540)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at cgeo.geocaching.connector.gc.TrackablesTest.parseTrackable(TrackablesTest.java:91)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at cgeo.geocaching.connector.gc.TrackablesTest.testParseTrackableWithDiscoveredDate(TrackablesTest.java:72)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at junit.framework.TestCase.runBare(TestCase.java:134)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at junit.framework.TestResult$1.protect(TestResult.java:115)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at androidx.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:73)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at junit.framework.TestResult.run(TestResult.java:118)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at androidx.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:51)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at junit.framework.TestCase.run(TestCase.java:124)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at androidx.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:62)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at junit.framework.TestSuite.run(TestSuite.java:238)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at androidx.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:97)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at androidx.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:65)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at androidx.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:115)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at org.junit.runners.Suite.runChild(Suite.java:128)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at org.junit.runners.Suite.runChild(Suite.java:27)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
10-29 10:31:22.605 10146  8242  8275 E cgeo    : 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
10-29 10:31:22.632 10146  8242  8275 I cgeo.geocachin: Explicit concurrent copying GC freed 1729(229KB) AllocSpace objects, 27(2632KB) LOS objects, 49% free, 5404KB/10MB, paused 278us total 10.798ms
10-29 10:31:22.641 10146  8242  8275 I cgeo.geocachin: Explicit concurrent copying GC freed 91(50KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5385KB/10MB, paused 268us total 8.633ms
10-29 10:31:22.641 10146  8242  8275 E TestRunner: failed: testParseTrackableWithDiscoveredDate(cgeo.geocaching.connector.gc.TrackablesTest)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: ----- begin exception -----
10-29 10:31:22.641 10146  8242  8275 E TestRunner: java.lang.AssertionError: 
10-29 10:31:22.641 10146  8242  8275 E TestRunner: Expecting actual not to be null
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at cgeo.geocaching.connector.gc.TrackablesTest.testParseTrackableWithDiscoveredDate(TrackablesTest.java:74)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at junit.framework.TestCase.runBare(TestCase.java:134)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at junit.framework.TestResult$1.protect(TestResult.java:115)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at androidx.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:73)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at junit.framework.TestResult.run(TestResult.java:118)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at androidx.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:51)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at junit.framework.TestCase.run(TestCase.java:124)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at androidx.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:62)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at junit.framework.TestSuite.run(TestSuite.java:238)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at androidx.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:97)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at androidx.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:65)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at androidx.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:115)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:128)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:27)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
10-29 10:31:22.641 10146  8242  8275 E TestRunner: ----- end exception -----
10-29 10:31:22.643 10146  8242  8275 I TestRunner: finished: testParseTrackableWithDiscoveredDate(cgeo.geocaching.connector.gc.TrackablesTest)

java.lang.AssertionError: 
Expecting actual not to be null
	at cgeo.geocaching.connector.gc.TrackablesTest.testParseTrackableWithDiscoveredDate(TrackablesTest.java:74)
	at java.lang.reflect.Method.invoke(Native Method)
	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)
```
```
--------- beginning of main
10-29 10:31:22.659 10146  8242  8275 E cgeo    : [Instr: androidx.test.runner.AndroidJUnitRunner] GCParser.parseTrackable: Failed to parse log
10-29 10:31:22.659 10146  8242  8275 E cgeo    : java.text.ParseException: Unparseable date: "10/18/2008"
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at java.text.DateFormat.parse(DateFormat.java:362)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at cgeo.geocaching.connector.gc.GCLogin.parseGcCustomDate(GCLogin.java:408)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at cgeo.geocaching.connector.gc.GCLogin.parseGcCustomDate(GCLogin.java:412)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at cgeo.geocaching.connector.gc.GCParser.parseTrackable(GCParser.java:1540)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at cgeo.geocaching.connector.gc.TrackablesTest.parseTrackable(TrackablesTest.java:91)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at cgeo.geocaching.connector.gc.TrackablesTest.testParseTrackableWithRetrievedDate(TrackablesTest.java:64)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at junit.framework.TestCase.runBare(TestCase.java:134)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at junit.framework.TestResult$1.protect(TestResult.java:115)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at androidx.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:73)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at junit.framework.TestResult.run(TestResult.java:118)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at androidx.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:51)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at junit.framework.TestCase.run(TestCase.java:124)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at androidx.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:62)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at junit.framework.TestSuite.run(TestSuite.java:238)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at androidx.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:97)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at androidx.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:65)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at androidx.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:115)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at org.junit.runners.Suite.runChild(Suite.java:128)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at org.junit.runners.Suite.runChild(Suite.java:27)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
10-29 10:31:22.659 10146  8242  8275 E cgeo    : 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
10-29 10:31:22.683 10146  8242  8275 I cgeo.geocachin: Explicit concurrent copying GC freed 2408(297KB) AllocSpace objects, 27(2584KB) LOS objects, 49% free, 5394KB/10MB, paused 266us total 10.631ms
10-29 10:31:22.694 10146  8242  8275 I cgeo.geocachin: Explicit concurrent copying GC freed 87(34KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 5391KB/10MB, paused 257us total 10.814ms
10-29 10:31:22.694 10146  8242  8275 E TestRunner: failed: testParseTrackableWithRetrievedDate(cgeo.geocaching.connector.gc.TrackablesTest)
10-29 10:31:22.694 10146  8242  8275 E TestRunner: ----- begin exception -----
10-29 10:31:22.695 10146  8242  8275 E TestRunner: java.lang.AssertionError: 
10-29 10:31:22.695 10146  8242  8275 E TestRunner: Expecting actual not to be null
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at cgeo.geocaching.connector.gc.TrackablesTest.testParseTrackableWithRetrievedDate(TrackablesTest.java:66)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at junit.framework.TestCase.runBare(TestCase.java:134)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at junit.framework.TestResult$1.protect(TestResult.java:115)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at androidx.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:73)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at junit.framework.TestResult.run(TestResult.java:118)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at androidx.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:51)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at junit.framework.TestCase.run(TestCase.java:124)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at androidx.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:62)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at junit.framework.TestSuite.runTest(TestSuite.java:243)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at junit.framework.TestSuite.run(TestSuite.java:238)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at androidx.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:97)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at androidx.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:65)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at androidx.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:115)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:128)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at org.junit.runners.Suite.runChild(Suite.java:27)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:444)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
10-29 10:31:22.695 10146  8242  8275 E TestRunner: ----- end exception -----
10-29 10:31:22.695 10146  8242  8275 I TestRunner: finished: testParseTrackableWithRetrievedDate(cgeo.geocaching.connector.gc.TrackablesTest)

java.lang.AssertionError: 
Expecting actual not to be null
	at cgeo.geocaching.connector.gc.TrackablesTest.testParseTrackableWithRetrievedDate(TrackablesTest.java:66)
	at java.lang.reflect.Method.invoke(Native Method)
	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)
```

### How to reproduce?

* Open AS
* run "All tests" on a VM (with initialized c:geo)

### Actual result after these steps?

Test results success 594/596

### Expected result after these steps?

Test results without error => 596/596

### Reproducible

Yes

### c:geo Version

dev build from current master

### System information

```text
## System information

c:geo version: 2022.10.29-ecea470 developer build

Device:
-------
- Device type: Android SDK built for x86 (sdk_gphone_x86, google)
- Available processors: 4
- Android version: 10
- Android build: sdk_gphone_x86-userdebug 10 QSR1.210802.001 7603624 dev-keys
- Screen resolution: 1080x2208px (392x778dp)
- Pixel density: 2.75
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 20.24.14 (040700-319035315)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:28
- Set language: en_US (system default)
- System date format: M/d/yy
- Time zone: GMT
- Debug mode active: no
- Last backup: never
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Google: Map
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleMapSource
  - Atts: none
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: None ([:inconclusive=false:advanced=false])
- OFFLINE: None ([:inconclusive=false:advanced=false])

Stored Filters (#0):

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   Geocaching.com Adventure Lab
- Geocaching.com date format: dd.MM.yy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: Failed to log in to geocaching.com due to captcha required (2022-10-29 10-30)
- Last successful login on geocaching.com: 2022-10-29 10-54
- Routing: internal / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (5.5 GB free) v3 internal isDir(7 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (5.5 GB free) v3 internal isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (5.5 GB free) v3 external non-removable isDir(2 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (5.5 GB free) v3 internal isDir(0 entries)
- Public Folders: #12
  - BASE: SDCARD/cgeo (User-Defined)[SDCARD/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo/document/1CED-290D%3Acgeo, Av:true, files:>=0, dirs:>=9, totalFileSize:>=0 B, free space: 509.8 MB, files on device: 0)
  - OFFLINE_MAPS: SDCARD/cgeo/maps (Default)[SDCARD/cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo/document/1CED-290D%3Acgeo%2Fmaps, Av:true, files:0, dirs:2, totalFileSize:0 B, free space: 509.8 MB, files on device: 0)
  - OFFLINE_MAP_THEMES: SDCARD/cgeo/maps/_themes (Default)[SDCARD/cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo/document/1CED-290D%3Acgeo%2Fmaps%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 509.8 MB, files on device: 0)
  - OFFLINE_MAP_SHADING: SDCARD/cgeo/maps/_hgt (Default)[SDCARD/cgeo/maps/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo::/maps/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo/document/1CED-290D%3Acgeo%2Fmaps%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 509.8 MB, files on device: 0)
  - LOGFILES: SDCARD/cgeo/logfiles (Default)[SDCARD/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo/document/1CED-290D%3Acgeo%2Flogfiles, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 509.8 MB, files on device: 0)
  - GPX: SDCARD/cgeo/gpx (Default)[SDCARD/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo/document/1CED-290D%3Acgeo%2Fgpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 509.8 MB, files on device: 0)
  - BACKUP: SDCARD/cgeo/backup (Default)[SDCARD/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo/document/1CED-290D%3Acgeo%2Fbackup, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 509.8 MB, files on device: 0)
  - FIELD_NOTES: SDCARD/cgeo/field-notes (Default)[SDCARD/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo/document/1CED-290D%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 509.8 MB, files on device: 0)
  - SPOILER_IMAGES: SDCARD/cgeo/GeocachePhotos (Default)[SDCARD/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo/document/1CED-290D%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 509.8 MB, files on device: 0)
  - ROUTING_BASE: SDCARD/cgeo/routing (Default)[SDCARD/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo/document/1CED-290D%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81.7 KB, free space: 509.8 MB, files on device: 0)
  - ROUTING_TILES: SDCARD/cgeo/routing/segments4 (Default)[SDCARD/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo/document/1CED-290D%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 509.8 MB, files on device: 0)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:>=5, dirs:>=29, totalFileSize:>=0 B, free space: 5.5 GB, files on device: -1)
- Map render theme path: 
- PersistedDocumentUris: #1
- UNUSED_TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/1CED-290D%3Acgeo (Oct 29, 10:29 AM):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v99, Size:740.0 KB) on system internal storage

--- End of system information ---
```

**Comment by bekuno** [comment]
maybe related to #13552

**Comment by bekuno** [comment]
Fixed in the meantime.
