### ISSUE TITLE
Search by address not working on Non-Google devices

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13677]
### Describe your problem!

A user with Lineage OS reported, that starting with 2022.11.13 he can no longer use the search by address.
I can reproduce the problem by running an emulator without Google services.

### How to reproduce?

- Go to search menu
- Enter a city name
- Select "Search Address"

### Actual result after these steps?

Toast "c:geo was unable to map this address to an existing location"

Log cat:
```
2022-11-16 19:34:55.656  2340-2340  Toolb...pper cgeo.geocaching  I  Progress display unsupported
2022-11-16 19:34:55.684  2340-2340  cgeo         cgeo.geocaching  D  [main] HTTP-GET: https://open.mapquestapi.com/geocoding/v1/address?location=Berlin&maxResults=20&thumbMaps=false&key=Fmjtd%7Cluurn1u2n9%2Cbs%3Do5-9wynua {Network.request:345/Network.requestJSON:508/MapQuestGeocoder.get:52/MapQuestGeocoder.getFromLocationName:38/AddressListActivity.lookupAddressInBackground:48/AddressListActivity.onCreate:43/Activity.performCreate:7994/Activity.performCreate:7978}
2022-11-16 19:34:55.688  2340-2703  cgeo         cgeo.geocaching  D  [OkHttp] GET https://open.mapquestapi.com/geocoding/v1/address?location=Berlin&maxResults=20&thumbMaps=false&key=Fmjtd%7Cluurn1u2n9%2Cbs%3Do5-9wynua {Network$LoggingInterceptor.intercept:386/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:374/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641}
2022-11-16 19:34:56.021  2340-2424  okhtt...ient cgeo.geocaching  W  A connection to https://open.mapquestapi.com/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
2022-11-16 19:34:56.121  2340-2703  cgeo         cgeo.geocaching  D  [OkHttp] 403 [Forbidden] (433 ms) GET https://open.mapquestapi.com/geocoding/v1/address?location=Berlin&maxResults=20&thumbMaps=false&key=Fmjtd%7Cluurn1u2n9%2Cbs%3Do5-9wynua (http/1.1) {Network$LoggingInterceptor.intercept:396/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:374/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641}
2022-11-16 19:34:56.658  2340-2340  LeakCanary   cgeo.geocaching  D  Watching instance of androidx.fragment.app.FragmentManagerViewModel (androidx.fragment.app.FragmentManagerViewModel received ViewModel#onCleared() callback) with key 42a52d33-73ec-4c22-9649-f38818cf1524
2022-11-16 19:34:56.658  2340-2340  LeakCanary   cgeo.geocaching  D  Watching instance of androidx.lifecycle.SavedStateHandlesVM (androidx.lifecycle.SavedStateHandlesVM received ViewModel#onCleared() callback) with key e551c683-9208-45b5-8ff1-05c2d5bdd93b
2022-11-16 19:34:56.658  2340-2340  LeakCanary   cgeo.geocaching  D  Watching instance of leakcanary.internal.ViewModelClearedWatcher (leakcanary.internal.ViewModelClearedWatcher received ViewModel#onCleared() callback) with key a9e21948-bb94-4575-9998-e6c1978d8680
2022-11-16 19:34:56.658  2340-2340  LeakCanary   cgeo.geocaching  D  Watching instance of androidx.lifecycle.ReportFragment (androidx.lifecycle.ReportFragment received Fragment#onDestroy() callback) with key e4b1e638-b531-49e9-9a54-f09850447869
2022-11-16 19:34:56.658  2340-2340  LeakCanary   cgeo.geocaching  D  Watching instance of cgeo.geocaching.address.AddressListActivity (cgeo.geocaching.address.AddressListActivity received Activity#onDestroy() callback) with key 9dd91a76-5676-42f2-933c-9724448fd7d7
2022-11-16 19:34:56.662  2340-2340  Windo...ager cgeo.geocaching  E  android.view.WindowLeaked: Activity cgeo.geocaching.address.AddressListActivity has leaked window DecorView@14572ab[Searching for places] that was originally added here
                                                                     	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:733)
                                                                     	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:717)
                                                                     	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:399)
                                                                     	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:109)
                                                                     	at android.app.Dialog.show(Dialog.java:340)
                                                                     	at android.app.ProgressDialog.show(ProgressDialog.java:190)
                                                                     	at android.app.ProgressDialog.show(ProgressDialog.java:147)
                                                                     	at cgeo.geocaching.address.AddressListActivity.onCreate(AddressListActivity.java:41)
                                                                     	at android.app.Activity.performCreate(Activity.java:7994)
                                                                     	at android.app.Activity.performCreate(Activity.java:7978)
                                                                     	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
                                                                     	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
                                                                     	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
                                                                     	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                     	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                     	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                     	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
                                                                     	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                     	at android.os.Looper.loop(Looper.java:223)
                                                                     	at android.app.ActivityThread.main(ActivityThread.java:7656)
                                                                     	at java.lang.reflect.Method.invoke(Native Method)
                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2022-11-16 19:35:01.672  2340-2364  cgeo....chin cgeo.geocaching  I  Explicit concurrent copying GC freed 46798(2534KB) AllocSpace objects, 1(20KB) LOS objects, 49% free, 8943KB/17MB, paused 19us total 12.817ms
```

### Expected result after these steps?

Result shown

### Reproducible

Yes

### c:geo Version

2022.11.13

### System information

```text
Device without Google services
```

**Comment by Lineflyer** [comment]
The main reason seems to be the 403 returned by mapquestapi.com (which we only use on devices without Google services).
Does anyone know, whether the service is still provided?

Still also wondering about the exception...or is that only because of the 403 error?

**Comment by Lineflyer** [comment]
An request returns: ```The AppKey submitted with this request is invalid.```

Did we change anything?

**Comment by Lineflyer** [comment]
@samueltardieu 
If my commit browsing is correct, you added the key for the mapquest geocoder back in 2014 with this commit:
https://github.com/cgeo/cgeo/commit/f1787fec5d99a97e212e12b0aa34732f7b69cf13

Do you remember the account associated to this key?
Maybe its your account and you recently disabled it?

**Comment by samueltardieu** [comment]
I haven't changed anything for years, and indeed my key was used for cgeo. Let me see if I can regenerate another. Right now their site displays "Unable to fetch information for your plan" but lists many authorizations associated with this unknown plan.

I'll send new key information via email.

**Comment by samueltardieu** [comment]
Just for fun, here is the screen I get:

![image](https://user-images.githubusercontent.com/44656/202269232-6752eded-2a5a-41c0-ba65-0f9914c0b327.png)

**Comment by Lineflyer** [comment]
Interesting enough the key you just provided via mail is identical to the one we use in our code.
Not sure whether we use the secret anywhere?

**Comment by Lineflyer** [comment]
I created an account and created an own key. 
Using that own key shows the same problem.

**Comment by Lineflyer** [comment]
It looks like the problem is not the key (so the error is misleading) but the URL we use:

Not working: ```https://open.mapquestapi.com/geocoding/v1/address...```
Working: ```http://www.mapquestapi.com/geocoding/v1/address...```

Does someone know, whether the difference in subdomain is intentional or did their endpoint change recently?
