### ISSUE TITLE
Scoped storage problem for a certain user

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13706]
### Describe your problem!

A user installed c:geo on his new device (Samsung A52, Android 12).
After installation we tried to restore a database but kept having crashes while trying.

Further investigation showed, that he is able to define his base folder without a problem, c:geo however fails to access files within this base folder.

We already tried 
- New installation
- Change of base folder (several locations tested in internal and SD-card)
- check on any antivirus or other tools
- Check, that the "normal" file manager is used to approve access (looks exactly like on my device)
- All permissions for c:geo granted
- No encryption of file boxing like "Samsung Knox" active

Any clues or debugging ideas?

Please also note, that within the system information below there is one irregularity for the base folders:
It reports ```totalFileSize:0 B, free space: -1 B, files on device: -1``` while on my device it shows the actual numbers

### How to reproduce?

Happens if the users triggers backup or restore, tries to export GPX, tries to export field notes.

### Actual result after these steps?

Example of GPX export try:
```
11-19 16:37:31.657 22370 22370 E AndroidRuntime: FATAL EXCEPTION: main
11-19 16:37:31.657 22370 22370 E AndroidRuntime: Process: cgeo.geocaching, PID: 22370
11-19 16:37:31.657 22370 22370 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=59374, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/CA6C-17E6:cgeo/gpx/export-2022-11-19-16-36-42-2 test.gpx flg=0x43 }} to activity {cgeo.geocaching/cgeo.geocaching.CacheListActivity}: java.lang.SecurityException: com.android.externalstorage has no access to content://media/ca6c-17e6/file/1000010370
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5864)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5903)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8669)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: Caused by: java.lang.SecurityException: com.android.externalstorage has no access to content://media/ca6c-17e6/file/1000010370
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2438)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2422)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2405)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at cgeo.geocaching.files.FileTypeDetector.getFileType(FileTypeDetector.java:35)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at cgeo.geocaching.files.GPXImporter.importGPX(GPXImporter.java:88)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at cgeo.geocaching.CacheListActivity.importGpx(CacheListActivity.java:1304)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at cgeo.geocaching.CacheListActivity.lambda$cyjsceS3x9s28NY3cCDSTuRGQNk(Unknown Source:0)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at cgeo.geocaching.-$$Lambda$CacheListActivity$cyjsceS3x9s28NY3cCDSTuRGQNk.accept(Unknown Source:4)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at cgeo.geocaching.storage.ContentStorageActivityHelper.callCallback(ContentStorageActivityHelper.java:518)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at cgeo.geocaching.storage.ContentStorageActivityHelper.handleResultSelectFiles(ContentStorageActivityHelper.java:378)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at cgeo.geocaching.storage.ContentStorageActivityHelper.onActivityResult(ContentStorageActivityHelper.java:289)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at cgeo.geocaching.CacheListActivity.onActivityResult(CacheListActivity.java:1312)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:8659)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5857)
11-19 16:37:31.657 22370 22370 E AndroidRuntime: 	... 13 more
11-19 16:37:31.657 22370 22370 W cgeo    : [main] UncaughtException
11-19 16:37:31.657 22370 22370 W cgeo    : java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=59374, result=-1, data=Intent { dat=content://com.android.externalstorage.documents/document/CA6C-17E6:cgeo/gpx/export-2022-11-19-16-36-42-2 test.gpx flg=0x43 }} to activity {cgeo.geocaching/cgeo.geocaching.CacheListActivity}: java.lang.SecurityException: com.android.externalstorage has no access to content://media/ca6c-17e6/file/1000010370
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5864)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:5903)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:54)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2438)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:106)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.os.Looper.loopOnce(Looper.java:226)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.os.Looper.loop(Looper.java:313)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:8669)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
11-19 16:37:31.657 22370 22370 W cgeo    : Caused by: java.lang.SecurityException: com.android.externalstorage has no access to content://media/ca6c-17e6/file/1000010370
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2438)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.os.Parcel.createException(Parcel.java:2422)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.os.Parcel.readException(Parcel.java:2405)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:153)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:780)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:2034)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1849)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.content.ContentResolver.openInputStream(ContentResolver.java:1525)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at cgeo.geocaching.files.FileTypeDetector.getFileType(FileTypeDetector.java:35)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at cgeo.geocaching.files.GPXImporter.importGPX(GPXImporter.java:88)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at cgeo.geocaching.CacheListActivity.importGpx(CacheListActivity.java:1304)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at cgeo.geocaching.CacheListActivity.lambda$cyjsceS3x9s28NY3cCDSTuRGQNk(Unknown Source:0)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at cgeo.geocaching.-$$Lambda$CacheListActivity$cyjsceS3x9s28NY3cCDSTuRGQNk.accept(Unknown Source:4)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at cgeo.geocaching.storage.ContentStorageActivityHelper.callCallback(ContentStorageActivityHelper.java:518)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at cgeo.geocaching.storage.ContentStorageActivityHelper.handleResultSelectFiles(ContentStorageActivityHelper.java:378)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at cgeo.geocaching.storage.ContentStorageActivityHelper.onActivityResult(ContentStorageActivityHelper.java:289)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at cgeo.geocaching.CacheListActivity.onActivityResult(CacheListActivity.java:1312)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.app.Activity.dispatchActivityResult(Activity.java:8659)
11-19 16:37:31.657 22370 22370 W cgeo    : 	at android.app.ActivityThread.deliverResults(ActivityThread.java:5857)
11-19 16:37:31.657 22370 22370 W cgeo    : 	... 13 more
```

### Expected result after these steps?

Normal operation, no crash

### Reproducible

Unclear

### c:geo Version

2022.11.13

### System information

```text
## System information

c:geo version: 2022.11.13

Device:
-------
- Device type: SM-A528B (a52sxqeea, samsung)
- Available processors: 8
- Android version: 12
- Android build: SP1A.210812.016.A528BXXS1CVI6
- Screen resolution: 1080x2177px (384x774dp)
- Pixel density: 3.09375
- System font scale: 1.1 / used scale: 1.1
- Sailfish OS detected: false
- Google Play services: enabled - 22.43.12 (190400-483592595)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:81
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Time zone: GMT+01:00
- Debug mode active: no
- Last backup: 15. Nov., 11:20
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Google: Karte
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleMapSource
  - Atts: none
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: Keine ([:inconclusive=false:advanced=false])
- OFFLINE: Keine ([:inconclusive=false:advanced=false])

Stored Filters (#0):

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   Geocaching.com Adventure Lab
- Geocaching.com date format: dd/MMM/yyyy
- Geocaching.com website language: en-US
- Last successful login on geocaching.com: 2022-11-17 21-12
- Routing: internal / BRouter installed: false
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (82,1 GB free) v3 internal isDir(6 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (82,1 GB free) v3 internal isDir(6 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (82,1 GB free) v3 external non-removable isDir(3 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (82,1 GB free) v3 internal isDir(0 entries)
- Public Folders: #12
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=0, dirs:>=9, totalFileSize:>=0 B, free space: -1 B, files on device: -1)
  - OFFLINE_MAPS: /cgeo/maps (Default)[/cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps, Av:true, files:0, dirs:2, totalFileSize:0 B, free space: -1 B, files on device: -1)
  - OFFLINE_MAP_THEMES: /cgeo/maps/_themes (Default)[/cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: -1 B, files on device: -1)
  - OFFLINE_MAP_SHADING: /cgeo/maps/_hgt (Default)[/cgeo/maps/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: -1 B, files on device: -1)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: -1 B, files on device: -1)
  - GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: -1 B, files on device: -1)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:2, dirs:1, totalFileSize:252,2 KB, free space: -1 B, files on device: -1)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: -1 B, files on device: -1)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: -1 B, files on device: -1)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81,7 KB, free space: -1 B, files on device: -1)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: -1 B, files on device: -1)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 82,1 GB, files on device: -1)
- Map render theme path: 
- PersistedDocumentUris: #1
- UNUSED_TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (15. Nov., 11:17):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v99, Size:272,0 KB) on system internal storage

--- End of system information ---
```

### Additional Information

Support ticket 443530

**Comment by Lineflyer** [comment]
Revisiting all the details I exchanged with the user I stumbled upon this screenshot.
It looks like the user disabled the file access for some system apps (see here e.g. "Externer Speicher" and "com.android.sharedstorage"). 
Once I try this on my device I at least see the same `-1B` sizes in system information.
So it pretty much looks like a "user fault", though I did not know that its so easy to break scoped storage.

![grafik](https://user-images.githubusercontent.com/949669/203060691-f22cc419-ce20-499d-908a-4d473d04df94.png)

**Comment by eddiemuc** [comment]
Your feedback sounds like a possible vause of the experienced behaviour. I am clueless otherwise...

PS: the reported `-1`/`0` numbers reported for file sizues/count is a sign that also the functions retrieving this info were denied access permission.
