### ISSUE TITLE
Crash when trying to open filter menu while distance filter active

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13715]
### Describe your problem!

A user on support mail applied a distance filter on his stored caches and he can`t remove it.
As soon as he tries, the app crashes.

### How to reproduce?

According to user:
- Setup distance filter for stored caches
Chosen setting according to user: "I think I set the lower range to be equal to the max range because I was trying to filter on the caches I have that are more than 500 miles away."
- Tap on "filter" to remove it

### Actual result after these steps?

Crash

```
11-22 10:31:50.885 21511 21511 E AndroidRuntime: java.lang.IllegalStateException: Slider value(311.30698) must be greater or equal to valueFrom(-0.2), and lower or equal to valueTo(311.2)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at com.google.android.material.slider.BaseSlider.validateValues(BaseSlider.java:558)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at com.google.android.material.slider.BaseSlider.validateConfigurationIfDirty(BaseSlider.java:611)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at com.google.android.material.slider.BaseSlider.onDraw(BaseSlider.java:1662)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:23187)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22062)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:22917)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22048)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:22917)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22048)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:22917)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22048)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:22917)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22048)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:22917)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22048)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:22917)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5204)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:23190)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4603)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22062)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:22917)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22048)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:22917)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22048)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:22917)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:23190)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.widget.ScrollView.draw(ScrollView.java:2880)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22062)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:22917)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22048)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:22917)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22048)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:22917)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22048)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:22917)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22048)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:22917)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5230)
11-22 10:31:50.885 21511 21511 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4987)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.view.View.draw(View.java:23190)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at com.android.internal.policy.DecorView.draw(DecorView.java:1154)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.view.View.updateDisplayListIfDirty(View.java:22062)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:588)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:594)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:667)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:4293)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4077)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3345)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2222)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9123)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:999)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:797)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:732)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:984)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8167)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
11-22 10:31:50.886 21511 21511 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
```

### Expected result after these steps?

Filter menu opened to remove filter

### Reproducible

Unclear

### c:geo Version

2022.11.13

### System information

```text
## System information

c:geo version: 2022.11.13

Device:
-------
- Device type: SM-G965U (star2qltesq, samsung)
- Available processors: 8
- Android version: 10
- Android build: QP1A.190711.020.G965USQU9FVB2
- Screen resolution: 1080x2094px (411x773dp)
- Pixel density: 3.9375
- System font scale: 1.5 / used scale: 1.5
- Sailfish OS detected: false
- Google Play services: enabled - 22.44.17 (100400-488410709)

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:181
- Set language: en_US (system default)
- System date format: M/d/yy
- Time zone: MST
- Debug mode active: no
- Last backup: never
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Utah (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:1617-1206:myMaps/utah.map
  - Atts: Map data (c) OpenStreetMap contributors
  - Theme: none

Filters:
-------
- Hide waypoints: visited
- LIVE: Status: 4 items ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status:owned_no:found_no:exclude_disabled:exclude_archived))
- OFFLINE: Distance: N40 31.964 W111 51.252(>501.0), Status: 3 items ([:inconclusive=false:advanced=true]AND(distance:501.0:-:coord=-:use_current_pos=true;status:owned_no:found_no:has_offline_found_log_no))

Stored Filters (#0):

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
   Geocaching.com Adventure Lab
- Geocaching.com date format: MM/dd/yyyy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: communication error (2022-10-30 09-11)
- Last successful login on geocaching.com: 2022-11-22 10-47
- Routing: external / BRouter installed: true
- Installed c:geo plugins:  none

Permissions & paths:
-------
- Fine location permission: granted
- Write external storage permission: granted
- System internal c:geo dir: /data/user/0/cgeo.geocaching (15.9 GB free) v3 internal isDir(10 entries)
- Legacy User storage c:geo dir: /storage/emulated/0/cgeo (15.9 GB free) v3 external non-removable isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (15.9 GB free) v3 external non-removable isDir(2025 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (15.9 GB free) v3 internal isDir(0 entries)
- Public Folders: #12
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=4, dirs:>=13, totalFileSize:>=32.0 MB, free space: 15.9 GB, files on device: 1732608)
  - OFFLINE_MAPS: SD card/myMaps (User-Defined)[SD card/myMaps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/1617-1206%3AmyMaps::]] (Uri: content://com.android.externalstorage.documents/tree/1617-1206%3AmyMaps/document/1617-1206%3AmyMaps, Av:true, files:22, dirs:2, totalFileSize:2.0 GB, free space: 15.3 GB, files on device: 0)
  - OFFLINE_MAP_THEMES: Downloads:/downloads (User-Defined)[Downloads:/downloads[DOCUMENT#0:p-content://com.android.providers.downloads.documents/tree/downloads::]] (Uri: content://com.android.providers.downloads.documents/tree/downloads/document/downloads, Av:true, files:26, dirs:1, totalFileSize:24.6 MB, free space: -1 B, files on device: -1)
  - OFFLINE_MAP_SHADING: SD card/myMaps/_hgt (Default)[SD card/myMaps/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/1617-1206%3AmyMaps::/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/1617-1206%3AmyMaps/document/1617-1206%3AmyMaps%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 15.3 GB, files on device: 0)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:353.6 KB, free space: 15.9 GB, files on device: 1732608)
  - GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:1, dirs:0, totalFileSize:1.0 MB, free space: 15.9 GB, files on device: 1732608)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:>=8, dirs:>=6, totalFileSize:>=124.4 MB, free space: 15.9 GB, files on device: 1732608)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 15.9 GB, files on device: 1732608)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:>=0, dirs:>=7, totalFileSize:>=0 B, free space: 15.9 GB, files on device: 1732608)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81.2 KB, free space: 15.9 GB, files on device: 1732608)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 15.9 GB, files on device: 1732608)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 15.9 GB, files on device: -1)
- Map render theme path:
- PersistedDocumentUris: #1
- UNUSED_TRACK: null
- Persisted Uri Permissions: #3
  - content://com.android.providers.downloads.documents/tree/downloads (Apr 19, 2021, 5:34 PM):RW
  - content://com.android.externalstorage.documents/tree/1617-1206%3AmyMaps (Oct 1, 2021, 4:25 PM):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (Apr 19, 2021, 5:34 PM):RW
- Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (v99, Size:38.4 MB) on user storage

--- End of system information ---
```

### Additional Information

Support ticket 793882

**Comment by eddiemuc** [comment]
Please ask the user to navigate to his settings and send us the value of `cache_filter_config.OFFLINE`.

As a quick fix for him, he can then **delete** this setting. This will reset the offline filter, he should then be able to set it again.

**Comment by Lineflyer** [comment]
Done, waiting for feedback.
Looking at his system information, it should be:
```Distance: N40 31.964 W111 51.252(>501.0), Status: 3 items ([:inconclusive=false:advanced=true]AND(distance:501.0:-:coord=-:use_current_pos=true;status:owned_no:found_no:has_offline_found_log_no))```

**Comment by eddiemuc** [comment]
Fixed with #13716
