### ISSUE TITLE
Online map tiles from mapy.cz not loading

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#13742]
### Describe your problem!

Reported by a user and reproducible for me.
Did not yet have a look into the log to check map server responses

### How to reproduce?

- Use online map source mapy.cz
- Start map

### Actual result after these steps?

No map tiles shown (empty) but caches shown

### Expected result after these steps?

Map tiles and caches shown

### Reproducible

Yes

### c:geo Version

2022.11.25

**Comment by Lineflyer** [comment]
Looks like a certificate problem:
```
11-29 15:56:53.145 15123 15803 E TileDownloadThread: Hostname m3.mapserver.mapy.cz not verified:
11-29 15:56:53.145 15123 15803 E TileDownloadThread:     certificate: sha1/H/Hw6AK57hkTkMdB7M+f7V/4WxI=
11-29 15:56:53.145 15123 15803 E TileDownloadThread:     DN: CN=*.mapy.cz
11-29 15:56:53.145 15123 15803 E TileDownloadThread:     subjectAltNames: [*.mapy.cz, mapy.cz]
11-29 15:56:53.145 15123 15803 E TileDownloadThread: javax.net.ssl.SSLPeerUnverifiedException: Hostname m3.mapserver.mapy.cz not verified:
11-29 15:56:53.145 15123 15803 E TileDownloadThread:     certificate: sha1/H/Hw6AK57hkTkMdB7M+f7V/4WxI=
11-29 15:56:53.145 15123 15803 E TileDownloadThread:     DN: CN=*.mapy.cz
11-29 15:56:53.145 15123 15803 E TileDownloadThread:     subjectAltNames: [*.mapy.cz, mapy.cz]
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:205)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:167)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:211)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at java.net.URLConnection.getContentEncoding(URLConnection.java:529)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getContentEncoding(DelegatingHttpsURLConnection.java:143)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:30)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloader.getInputStream(TileDownloader.java:34)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloader.downloadImage(TileDownloader.java:71)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloadThread.downloadTile(TileDownloadThread.java:81)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloadThread.doWork(TileDownloadThread.java:60)
11-29 15:56:53.145 15123 15803 E TileDownloadThread: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: Hostname m2.mapserver.mapy.cz not verified:
11-29 15:56:53.146 15123 15801 E TileDownloadThread:     certificate: sha1/H/Hw6AK57hkTkMdB7M+f7V/4WxI=
11-29 15:56:53.146 15123 15801 E TileDownloadThread:     DN: CN=*.mapy.cz
11-29 15:56:53.146 15123 15801 E TileDownloadThread:     subjectAltNames: [*.mapy.cz, mapy.cz]
11-29 15:56:53.146 15123 15801 E TileDownloadThread: javax.net.ssl.SSLPeerUnverifiedException: Hostname m2.mapserver.mapy.cz not verified:
11-29 15:56:53.146 15123 15801 E TileDownloadThread:     certificate: sha1/H/Hw6AK57hkTkMdB7M+f7V/4WxI=
11-29 15:56:53.146 15123 15801 E TileDownloadThread:     DN: CN=*.mapy.cz
11-29 15:56:53.146 15123 15801 E TileDownloadThread:     subjectAltNames: [*.mapy.cz, mapy.cz]
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:205)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:167)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:211)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at java.net.URLConnection.getContentEncoding(URLConnection.java:529)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getContentEncoding(DelegatingHttpsURLConnection.java:143)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:30)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloader.getInputStream(TileDownloader.java:34)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloader.downloadImage(TileDownloader.java:71)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloadThread.downloadTile(TileDownloadThread.java:81)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloadThread.doWork(TileDownloadThread.java:60)
11-29 15:56:53.146 15123 15801 E TileDownloadThread: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: Hostname m1.mapserver.mapy.cz not verified:
11-29 15:56:53.146 15123 15799 E TileDownloadThread:     certificate: sha1/H/Hw6AK57hkTkMdB7M+f7V/4WxI=
11-29 15:56:53.146 15123 15799 E TileDownloadThread:     DN: CN=*.mapy.cz
11-29 15:56:53.146 15123 15799 E TileDownloadThread:     subjectAltNames: [*.mapy.cz, mapy.cz]
11-29 15:56:53.146 15123 15799 E TileDownloadThread: javax.net.ssl.SSLPeerUnverifiedException: Hostname m1.mapserver.mapy.cz not verified:
11-29 15:56:53.146 15123 15799 E TileDownloadThread:     certificate: sha1/H/Hw6AK57hkTkMdB7M+f7V/4WxI=
11-29 15:56:53.146 15123 15799 E TileDownloadThread:     DN: CN=*.mapy.cz
11-29 15:56:53.146 15123 15799 E TileDownloadThread:     subjectAltNames: [*.mapy.cz, mapy.cz]
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:205)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:167)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:211)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at java.net.URLConnection.getContentEncoding(URLConnection.java:529)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getContentEncoding(DelegatingHttpsURLConnection.java:143)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:30)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloader.getInputStream(TileDownloader.java:34)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloader.downloadImage(TileDownloader.java:71)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloadThread.downloadTile(TileDownloadThread.java:81)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloadThread.doWork(TileDownloadThread.java:60)
11-29 15:56:53.146 15123 15799 E TileDownloadThread: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: Hostname m2.mapserver.mapy.cz not verified:
11-29 15:56:53.179 15123 15806 E TileDownloadThread:     certificate: sha1/H/Hw6AK57hkTkMdB7M+f7V/4WxI=
11-29 15:56:53.179 15123 15806 E TileDownloadThread:     DN: CN=*.mapy.cz
11-29 15:56:53.179 15123 15806 E TileDownloadThread:     subjectAltNames: [*.mapy.cz, mapy.cz]
11-29 15:56:53.179 15123 15806 E TileDownloadThread: javax.net.ssl.SSLPeerUnverifiedException: Hostname m2.mapserver.mapy.cz not verified:
11-29 15:56:53.179 15123 15806 E TileDownloadThread:     certificate: sha1/H/Hw6AK57hkTkMdB7M+f7V/4WxI=
11-29 15:56:53.179 15123 15806 E TileDownloadThread:     DN: CN=*.mapy.cz
11-29 15:56:53.179 15123 15806 E TileDownloadThread:     subjectAltNames: [*.mapy.cz, mapy.cz]
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:205)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:167)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:211)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at java.net.URLConnection.getContentEncoding(URLConnection.java:529)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getContentEncoding(DelegatingHttpsURLConnection.java:143)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:30)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloader.getInputStream(TileDownloader.java:34)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloader.downloadImage(TileDownloader.java:71)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloadThread.downloadTile(TileDownloadThread.java:81)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloadThread.doWork(TileDownloadThread.java:60)
11-29 15:56:53.179 15123 15806 E TileDownloadThread: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: Hostname m1.mapserver.mapy.cz not verified:
11-29 15:56:53.184 15123 15805 E TileDownloadThread:     certificate: sha1/H/Hw6AK57hkTkMdB7M+f7V/4WxI=
11-29 15:56:53.184 15123 15805 E TileDownloadThread:     DN: CN=*.mapy.cz
11-29 15:56:53.184 15123 15805 E TileDownloadThread:     subjectAltNames: [*.mapy.cz, mapy.cz]
11-29 15:56:53.184 15123 15805 E TileDownloadThread: javax.net.ssl.SSLPeerUnverifiedException: Hostname m1.mapserver.mapy.cz not verified:
11-29 15:56:53.184 15123 15805 E TileDownloadThread:     certificate: sha1/H/Hw6AK57hkTkMdB7M+f7V/4WxI=
11-29 15:56:53.184 15123 15805 E TileDownloadThread:     DN: CN=*.mapy.cz
11-29 15:56:53.184 15123 15805 E TileDownloadThread:     subjectAltNames: [*.mapy.cz, mapy.cz]
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:205)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaders(HttpURLConnectionImpl.java:167)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:211)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at java.net.URLConnection.getContentEncoding(URLConnection.java:529)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getContentEncoding(DelegatingHttpsURLConnection.java:143)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:30)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloader.getInputStream(TileDownloader.java:34)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloader.downloadImage(TileDownloader.java:71)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloadThread.downloadTile(TileDownloadThread.java:81)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at org.mapsforge.map.layer.download.TileDownloadThread.doWork(TileDownloadThread.java:60)
11-29 15:56:53.184 15123 15805 E TileDownloadThread: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
```

**Comment by Lineflyer** [comment]
@jirkavrba Any idea or contact person to involve on their side? I get the same certificate error when trying to reach *.mapserver.mapy.cz via website. My browser tells "BAD_CERT_DOMAIN" where however the certificate seems valid for "*.mapy.cz". 

Could it be a usage restriction on their side?

Did anyone ever check up with them, whether we are allowed to use it? In https://github.com/cgeo/cgeo/pull/11419 this point was still open but still merged.

**Comment by jirkavrba** [comment]
Also I can confirm, that the Mapy.cz map source stopped working for me

**Comment by Lineflyer** [comment]
@jirkavrba Can you post the URL of the usage condition, with this section about "requiring attribution"? Then I will contact them and simply ask, whether we are allowed to use it in our context, based on that section in their usage conditions and why it does not work.

**Comment by jirkavrba** [comment]
Sorry, I fear that there is no possibility to use the maps overlay directly. The attribution section only covers the official JavaScript SDK which I missed.

🥲

**Comment by moving-bits** [comment]
Shall we remove mapy.cz map type then?

**Comment by moving-bits** [comment]
For reference: We'd contacted mapy.cz a while ago and asked them for a way to re-integrate mapy.cz into c:geo, but have not received any response from them yet.
