### ISSUE TITLE
LOGIN_CAPTCHA_ERROR - GC login not possible

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#13747]
When I was out today c:geo would get "Login failed" for GC. Performing the GC login via a webbrowser would show me the Google Captcha, but even after logging in multiple times (each with captcha) via browser didn't make it work in c:geo.
![image](https://user-images.githubusercontent.com/1258173/205496345-24e3357d-3ed1-4ef8-acc7-f8c843ac9706.png)

Only when I returned home and connected to Wifi login worked again. But disconnecting from wifi it's again not working.

We should try to find a way to make it work with captcha.

**Comment by SammysHP** [comment]
IIRC we removed a captcha proxy implementation some years ago because it was too difficult to maintain.

This is mostly a problem with the ISP that got blocked by the CDN due to too much spam / too many requests. Sometimes whole IP ranges get blocked, sometimes only a single IP, but especially with mobile networks IPs are shared between multiple users and they can rotate quite often.

**Comment by ztNFny** [comment]
> especially with mobile networks IPs are shared between multiple users and they can rotate quite often.

mobile networks is where c:geo is used though. And this is my countries biggest mobile network provider. Not sure whether it's just a specific region right now, but a 1,5h drives distance didn't get me far enough to get a "good" IP

**Comment by Lineflyer** [comment]
Are you using any VPN services on your device, or anonymizer like TOR-network?

**Comment by ztNFny** [comment]
> Are you using any VPN services on your device, or anonymizer like TOR-network?

No

**Comment by fm-sys** [comment]
HANDS UP: This topic seems to become more and more urgent. (CI build is failing for all current PRs, e.g. #13757, #13758)

```
13:27:23  cgeo.geocaching.connector.gc.GCLoginTest > testLanguageSwitch[android-30(AVD) - 11] [31mFAILED [0m
13:27:23  	org.junit.ComparisonFailure: expected:<[NO]_ERROR> but was:<[LOGIN_CAPTCHA]_ERROR>
13:27:23  	at java.lang.reflect.Constructor.newInstance0(Native Method)
13:27:24  
13:27:24  cgeo.geocaching.connector.gc.GCLoginTest > testNoHtmlInHomeLocation[android-30(AVD) - 11] [31mFAILED [0m
13:27:24  	org.junit.ComparisonFailure: expected:<[NO]_ERROR> but was:<[LOGIN_CAPTCHA]_ERROR>
13:27:24  	at java.lang.reflect.Constructor.newInstance0(Native Method)
13:27:25  
13:27:25  cgeo.geocaching.connector.gc.GCLoginTest > testRetrieveHomeLocation[android-30(AVD) - 11] [31mFAILED [0m
13:27:25  	org.junit.ComparisonFailure: expected:<[NO]_ERROR> but was:<[LOGIN_CAPTCHA]_ERROR>
13:27:25  	at java.lang.reflect.Constructor.newInstance0(Native Method)
13:27:25  
13:27:25  cgeo.geocaching.connector.gc.GCLoginTest > testValidHomeLocation[android-30(AVD) - 11] [31mFAILED [0m
13:27:25  	org.junit.ComparisonFailure: expected:<[NO]_ERROR> but was:<[LOGIN_CAPTCHA]_ERROR>
13:27:25  	at java.lang.reflect.Constructor.newInstance0(Native Method)
13:27:26  
13:27:26  cgeo.geocaching.connector.gc.GCLoginTest > testAvatar[android-30(AVD) - 11] [31mFAILED [0m
13:27:26  	org.junit.ComparisonFailure: expected:<[NO]_ERROR> but was:<[LOGIN_CAPTCHA]_ERROR>
13:27:26  	at java.lang.reflect.Constructor.newInstance0(Native Method)
13:27:28

**Comment by fm-sys** [comment]
Any idea how we could handle this? Especially for our CI this seems like an impossible task, but even forwarding captchas to the end user inside c:geo seems like a too heavy task to be worth it. Maybe just claim GC in their forums and hope they make their captchas less prominent again?

**Comment by fm-sys** [comment]
Interesting, today the build is fine again. Is our CI connected via a dynamic IP?

**Comment by mucek4** [comment]
> Interesting, today the build is fine again. Is our CI connected via a dynamic IP?

No. CI is on static IP address. And geocaching too returns only 1 IP for v4 and no for v6.

**Comment by moving-bits** [comment]
After having the new box for "manual login from within c:geo when occurring a captcha" - can we close here?
