### ISSUE TITLE
c:geo crashing on multiple dots in formulas

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13763]
User reports this on support: (ticket #793938):

Hier zuerst die kurze Version, wie ich einen Absturz von c:geo provozieren kann:

Wegpunktformel:
N 48° 21.1A E 009° 40.456

Variable:
A="."

Die Nordkoordinate bzw. den zweiten Punkt kann c:geo nicht mehr richtig interpretieren und stürzt reproduzierbar ab.

Die modifizierte Formeln "N 48° 21.1A2" und "N 48° 21.A" führen jeweils zu keinem Absturz.

---

Der Vollständigkeit halber hier auch noch die lange Version am Beispiel eines konkreten Multi-Caches.

In Vorbereitung einer Tour habe ich beim Multi GC22QAT u.a. ein paar Variablen und die Finalformal eingetragen.

Das sieht dann in der persönlichen Notiz wie folgt aus:

{c:geo-start}
@Finale (F) {CC|N 48° 21.EGC|E 009° 40.C(I+B)H}
$A=sub($ABCB;0;1) | $B=sub($ABCB;1;1) | $C=sub($ABCB;2;1) | 
$D=sub($ADEF;1;1) | $E=sub($ADEF;2;1) | $F=sub($ADEF;3;1) | $G=2 | $H= | 
$I= | $ADEF=1790 #? | $ABCB=1...
{c:geo-end}

Diese Daten führen reproduzierbar zu einem Absturz von c:geo.

Durch Tests habe ich herausgefunden, dass der Inhalt der Variablen C und G entscheidend sind.

Details dazu:

Es sind zwei Jahreszahlen gesucht. Dafür lege ich zwei Variablen an (mit unvollständigen Daten):

ABCB=1...
ADEF=1790 #?

Die Werte der Einzelvariablen A-F hole ich mit der Funktion sub() aus diesen Variablen:

A=sub($ABCB;0;1)
B=sub($ABCB;1;1)
C=sub($ABCB;2;1)
D=sub($ADEF;1;1)
usw.

Außerdem habe ich Vorabwissen und setze G=2.

Dadurch, dass ich die Jahreszahl $ABCB noch nicht kenne und als Platzhalter den nicht-numerischen Wert "1..." eingetragen habe, ist nun C="." gesetzt. Dies führt in Kombination mit dem (beliebigen) Wert von G dazu, dass c:geo mit der Formel der Nordkoordinaten Probleme hat. Die Ostkoordinate spielt keine Rolle, obwohl hier C auch vorkommt.

N 48° 21.EGC

führt zu:

N 48° 21.92.

Mit zweiten Punkt kann c:geo wohl nicht umgehen.

**Comment by eddiemuc** [comment]
Confirmed bug + fixed with #13765

Thanks to the user for a **very** detailled analysis, made it very easy to find and fix the bug.

**Comment by eddiemuc** [comment]
For reference: causing exception:

```
FATAL EXCEPTION: main
                                                                   Process: cgeo.geocaching, PID: 30853
                                                                   java.lang.NumberFormatException: multiple points
                                                                   	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1914)
                                                                   	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
                                                                   	at java.lang.Double.parseDouble(Double.java:538)
                                                                   	at cgeo.geocaching.utils.formulas.DegreeFormula.evaluateNumber(DegreeFormula.java:349)
                                                                   	at cgeo.geocaching.utils.formulas.DegreeFormula.lambda$createDegreePartNode$8$DegreeFormula(DegreeFormula.java:205)
                                                                   	at cgeo.geocaching.utils.formulas.-$$Lambda$DegreeFormula$PR8_6yb9nq4ovP5fJ9jSBcRRGT8.apply(Unknown Source:12)
                                                                   	at cgeo.geocaching.utils.formulas.DegreeFormula.evaluate(DegreeFormula.java:308)
                                                                   	at cgeo.geocaching.models.CalculatedCoordinate.calculateLatitudeData(CalculatedCoordinate.java:153)
                                                                   	at cgeo.geocaching.ui.dialog.CoordinatesCalculateGlobalDialog.updateView(CoordinatesCalculateGlobalDialog.java:335)
                                                                   	at cgeo.geocaching.ui.dialog.CoordinatesCalculateGlobalDialog.lambda$onCreateView$6$CoordinatesCalculateGlobalDialog(CoordinatesCalculateGlobalDialog.java:215)
                                                                   	at cgeo.geocaching.ui.dialog.-$$Lambda$CoordinatesCalculateGlobalDialog$avtqmZXwAsGWwSy1OG8StFh6Lsk.call(Unknown Source:6)
                                                                   	at cgeo.geocaching.ui.VariableListView$VariablesListAdapter.lambda$onCreateViewHolder$6$VariableListView$VariablesListAdapter(VariableListView.java:304)

```
