### ISSUE TITLE
Test error on testParseCacheFromTextWithMockedData 

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#13900]
### Describe your problem!

Seen on CI PR test:
~~~
cgeo.geocaching.connector.gc.GCParserTest.testParseCacheFromTextWithMockedData (from cgeo.geocaching.CgeoApplicationTest) 

Stacktrace

java.lang.AssertionError:
Expecting actual not to be null
at cgeo.test.Compare.assertCompareCaches(Compare.java:34)
at cgeo.geocaching.connector.gc.GCParserTest.testParseCacheFromTextWithMockedData(GCParserTest.java:123)
at java.lang.reflect.Method.invoke(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)
~~~

### How to reproduce?

see e.g. https://ci.cgeo.org/job/cgeo-CI_PR-build/3983/testReport/cgeo.geocaching.connector.gc/GCParserTest/testParseCacheFromTextWithMockedData/

### Reproducible

Yes

### c:geo Version

CI PR-build 3983

**Comment by bekuno** [comment]
Not permanent.
The error was gone on the next PR build.

**Comment by bekuno** [comment]
Only a single error.
Lets close.
