### ISSUE TITLE
Crash in GeoJSonUtils on opening the map

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13979]
User on support reports the map is always crashing for her. Error log points to GeoJsonUtils, see below:

```
io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.OutOfMemoryError: Failed to allocate a 268959752 byte allocation with 16777216 free bytes and 228MB until OOM
at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:372)
at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:68)
at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:760)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 268959752 byte allocation with 16777216 free bytes and 228MB until OOM
at java.util.Arrays.copyOf(Arrays.java:3352)
at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:550)
at java.lang.StringBuilder.append(StringBuilder.java:205)
at com.cocoahero.android.geojson.util.StreamUtils.toString(StreamUtils.java:38)
at com.cocoahero.android.geojson.util.StreamUtils.toString(StreamUtils.java:18)
at com.cocoahero.android.geojson.GeoJSON.parse(GeoJSON.java:135)
at cgeo.geocaching.utils.GeoJsonUtils.parseGeoJson(GeoJsonUtils.java:57)
at cgeo.geocaching.files.GPXTrackOrRouteImporter.parseAsGeoJson(GPXTrackOrRouteImporter.java:120)
at cgeo.geocaching.files.GPXTrackOrRouteImporter.doInBackground(GPXTrackOrRouteImporter.java:89)
at cgeo.geocaching.files.GPXTrackOrRouteImporter.lambda$doImport$1(GPXTrackOrRouteImporter.java:39)
at cgeo.geocaching.files.GPXTrackOrRouteImporter.$r8$lambda$g0pSx27yHp6Zq7CsAgfCAE4gnXU(GPXTrackOrRouteImporter.java)
at cgeo.geocaching.files.GPXTrackOrRouteImporter$$ExternalSyntheticLambda0.run(R8$$SyntheticClass)
at cgeo.geocaching.utils.AndroidRxUtils.lambda$andThenOnUi$2(AndroidRxUtils.java:91)
at cgeo.geocaching.utils.AndroidRxUtils.$r8$lambda$bqzWo9nlvU86BvboB-9jhDWp5vc(AndroidRxUtils.java)
at cgeo.geocaching.utils.AndroidRxUtils$$ExternalSyntheticLambda0.run(R8$$SyntheticClass)
at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
... 6 more
```
Release 2023.02.12
ticket 724300

Edit: I asked the user whether she has some tracks activated on map and whether she can send us the files so that we can debug into it.

**Comment by eddiemuc** [comment]
OutOfMemoryError and staktrace suggests that user opens a very very large json file as a route/track file - so large that parsing it into memory leads to the OOME.

If this is the case, then a quick solution for the user would be to move the file in question on her local storage to another place (then c:geo won't find it on opening the map).

In general I don't know exactly how to deal with this. Should we set an upper-bound on route/track files which the user is allowed to open?
Does anyone know how much memory c:geo gets granted by Android and how/if we can influence this?

**Comment by eddiemuc** [comment]
Quickfix in PR #13981 catches OOME and continues as if file couldn't be read

**Comment by moving-bits** [comment]
Update: 

User reported back "what is a track", so she probably does not have loaded a track file yet.
I asked her whether she has some JSON file in the GPX folder, let's see what comes back.

No problems like this reported from other users yet, so probably a single case. User runs her system on Android 7.1 with relatively low memory, which does not explain why this code path gets triggered, but could explain the crash itself when that code path is triggered.

**Comment by Lineflyer** [comment]
We have another case of this now on support:

User reports, that since upgrade to the new version it crashes each time he wants to open the map.
Pretty sure he did not use any Geojson yet.


```
02-16 23:28:08.184 13862 14316 E AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-4
02-16 23:28:08.184 13862 14316 E AndroidRuntime: Process: cgeo.geocaching, PID: 13862
02-16 23:28:08.184 13862 14316 E AndroidRuntime: io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.OutOfMemoryError: Failed to allocate a 349693734 byte allocation with 16777216 free bytes and 172MB until OOM
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:372)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:68)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: Caused by: java.lang.OutOfMemoryError: Failed to allocate a 349693734 byte allocation with 16777216 free bytes and 172MB until OOM
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.enlargeBuffer(AbstractStringBuilder.java:95)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at java.lang.AbstractStringBuilder.append0(AbstractStringBuilder.java:125)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at java.lang.StringBuilder.append(StringBuilder.java:271)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at com.cocoahero.android.geojson.util.StreamUtils.toString(StreamUtils.java:38)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at com.cocoahero.android.geojson.util.StreamUtils.toString(StreamUtils.java:18)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at com.cocoahero.android.geojson.GeoJSON.parse(GeoJSON.java:135)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at cgeo.geocaching.utils.GeoJsonUtils.parseGeoJson(GeoJsonUtils.java:57)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at cgeo.geocaching.files.GPXTrackOrRouteImporter.parseAsGeoJson(GPXTrackOrRouteImporter.java:120)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at cgeo.geocaching.files.GPXTrackOrRouteImporter.doInBackground(GPXTrackOrRouteImporter.java:89)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at cgeo.geocaching.files.GPXTrackOrRouteImporter.lambda$doImport$1(GPXTrackOrRouteImporter.java:39)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at cgeo.geocaching.files.GPXTrackOrRouteImporter.$r8$lambda$g0pSx27yHp6Zq7CsAgfCAE4gnXU(GPXTrackOrRouteImporter.java)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at cgeo.geocaching.files.GPXTrackOrRouteImporter$$ExternalSyntheticLambda0.run(R8$$SyntheticClass)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at cgeo.geocaching.utils.AndroidRxUtils.lambda$andThenOnUi$2(AndroidRxUtils.java:91)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at cgeo.geocaching.utils.AndroidRxUtils.$r8$lambda$bqzWo9nlvU86BvboB-9jhDWp5vc(AndroidRxUtils.java)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at cgeo.geocaching.utils.AndroidRxUtils$$ExternalSyntheticLambda0.run(R8$$SyntheticClass)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
02-16 23:28:08.184 13862 14316 E AndroidRuntime: 	... 7 more
```

**Comment by moving-bits** [comment]
User of ticket 838250 has provided us with track files he's using, 30 of them. Not sure yet, whether he has loaded all of them, but selected some of them to be hidden, or if he has loaded just a couple of them.

But either way I have not yet been able to reproduce the problem, even with reducing allowed memory to the minimum required to be able start c:geo at all. This was on my default dev emulator, though, running Android 13. Will create an Android 6 environment next.

**Comment by eddiemuc** [comment]
Should be fixed with referenced PR

**Comment by moving-bits** [comment]
For the second user it may simply have been a map file stored in gpx folder. He claims that after deleting this file he's back in the game. (Not sure yet whether he has actually selected a map file as track, or if he only has stored this file in the folder. Question pending.)
