### ISSUE TITLE
Permission WRITE_EXTERNAL_STORAGE missing

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#13988]
### Describe your problem!

Trying to reproduce some other bug on my physical testing device, c:geo asked me whether to update my routing data. On selecting to update it, c:geo crashed. Logcat (see below) showed a missing WRITE_EXTERNAL_STORAGE permission.

### How to reproduce?

For me:
- uninstalled existing release 2023.02.13
- installed dev build from current state of `release`
- followed wizard, granting location permission, selecting base folder, and then restoring backup
- tapped on home screen notification whether to update downloaded routing data

### Actual result after these steps?

crash

Logcat shows this:
```
FATAL EXCEPTION: network--4
Process: cgeo.geocaching, PID: 12409
io.reactivex.rxjava3.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/E5_N50.rd5: Neither user 10285 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
	at io.reactivex.rxjava3.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:372)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:45)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/E5_N50.rd5: Neither user 10285 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
	at android.content.ContentResolver.insert(ContentResolver.java:1284)
	at android.app.DownloadManager.enqueue(DownloadManager.java:1336)
	at cgeo.geocaching.downloader.DownloaderUtils.lambda$triggerDownloads$3(DownloaderUtils.java:202)
	at cgeo.geocaching.downloader.DownloaderUtils$$ExternalSyntheticLambda4.run(D8$$SyntheticClass)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
```

received a similar error on next restart, when I tried to update map data

### Expected result after these steps?

check existing routing data and display update dialog

### Reproducible

Yes

### c:geo Version

release as of 2023-02-17

### System information

```text
## System information

c:geo version: 2023.02.17-06ae7c6 developer build

Device:- Device type: SM-G903F (s5neoltexx, samsung)
- Available processors: 8
- Android version: 6.0.1
- Android build: MMB29K.G903FXXU2BRH2
- Screen resolution: 1080x1920px (360x616dp)
- Pixel density: 3.0
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 22.50.14 (040308-499278674)

Sensor and location:- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:- Settings: v9, Count:80
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Time zone: GMT+01:00
- Debug mode active: no
- Last backup: 12. Feb., 22:44
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Google: Karte
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleMapSource
  - Atts: none
  - Theme: none

Filters:- Hide waypoints: -
- LIVE: Keine ([:advanced=false:inconclusive=false])
- OFFLINE: Keine ([:advanced=false:inconclusive=false])

Stored Filters (#0):

Services:- Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / BASIC
- Geocaching.com date format: M/d/yyyy
- Geocaching.com website language: en-US
- Last successful login on geocaching.com: 2023-02-17 20-32
- Routing: internal / BRouter installed: false
- Installed c:geo plugins: contacts

Permissions-android.permission.ACCESS_COARSE_LOCATION:: granted
-android.permission.ACCESS_FINE_LOCATION:: granted
-android.permission.READ_CONTACTS:: DENIED
-android.permission.READ_EXTERNAL_STORAGE:: DENIED

Paths- System internal c:geo dir: /data/user/0/cgeo.geocaching (1,6 GB free) v3 internal isDir(9 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (1,6 GB free) v3 internal isDir(9 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (1,5 GB free) v3 external non-removable isDir(2 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (1,6 GB free) v3 internal isDir(0 entries)
- Public Folders: #12
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=49, dirs:>=10, totalFileSize:>=671,7 MB, free space: 1,5 GB, files on device: 369824)
  - OFFLINE_MAPS: /cgeo/maps (Default)[/cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps, Av:true, files:7, dirs:2, totalFileSize:667,4 MB, free space: 1,5 GB, files on device: 369824)
  - OFFLINE_MAP_THEMES: /cgeo/maps/_themes (Default)[/cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps%2F_themes, Av:true, files:2, dirs:0, totalFileSize:518,8 KB, free space: 1,5 GB, files on device: 369824)
  - OFFLINE_MAP_SHADING: /cgeo/maps/_hgt (Default)[/cgeo/maps/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,5 GB, files on device: 369824)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:8, dirs:0, totalFileSize:658,8 KB, free space: 1,5 GB, files on device: 369824)
  - GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:34, dirs:0, totalFileSize:3,7 MB, free space: 1,5 GB, files on device: 369824)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:>=8, dirs:>=11, totalFileSize:>=6,6 MB, free space: 1,5 GB, files on device: 369824)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,5 GB, files on device: 369824)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,5 GB, files on device: 369824)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:9, dirs:1, totalFileSize:229,1 MB, free space: 1,5 GB, files on device: 369824)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:2, dirs:0, totalFileSize:229,0 MB, free space: 1,5 GB, files on device: 369824)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 1,5 GB, files on device: -1)
- Map render theme path:
- PersistedDocumentUris: #1
- UNUSED_TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (17. Feb., 20:22):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v99, Size:236,0 KB) on system internal storage

--- End of system information ---
```

**Comment by eddiemuc** [comment]
Phew, so Google is lying about this permission no longer relevant for Android 11+?
Should it be re-added into installation wizard?

**Comment by bekuno** [comment]
> Phew, so Google is lying about this permission no longer relevant for Android 11+? Should it be re-added into installation wizard?

The device info says `- Android version: 6.0.1`

**Comment by fm-sys** [comment]
AFAIK we still need to request this permission for API < 29

**Comment by eddiemuc** [comment]
> AFAIK we still need to request this permission for API < 29

Something like this?

```
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" android:maxSdkVersion="28" tools:ignore="ScopedStorage" />
```

Plus an extra install wizard screen to show for affected SDks only?

**Comment by moving-bits** [comment]
Looks good, thanks for diving into it. Though I'm not sure about required SDK version. I guess if it would really be API 29 we would have quite a few reports on support. So it might be an Android 6 thing or even vendor-/device-specific.

**Comment by eddiemuc** [comment]
I googled this but couldn't find anything matching our case. It looks also to me like a (vendor-/device-specific) bug. Because my understanding of Google documentation is that the permission is no longer needed as long as our target SDK is 30+ (independent of the SDK used on the device running c:geo)

However, question is how to handle this. Request the permission from all c:geo users , although the vast majority won't need it?

@moving-bits do you have the problem on the affected device just in conjunction with download manager or also in other storage situations (e.g. writing/accessing gpx or maps or log files)?

**Comment by fm-sys** [comment]
> Because my understanding of Google documentation is that the permission is no longer needed as long as our target SDK is 30+ (independent of the SDK used on the device running c:geo)

This is true for Android 10 and above, but how can prior android versions know that the permission won't be necessary anymore in the future?

> Though I'm not sure about required SDK version. I guess if it would really be API 29 we would have quite a few reports on support.  

OTOH cgeo probably isn't installed anymore that often on older devices. 

Has anyone done some tests in the emulator yet? Maybe this issue is easily reproducible and device independent...

**Comment by eddiemuc** [comment]
> This is true for Android 10 and above, but how can prior android versions know that the permission won't be necessary anymore in the future?

I don't know much about how Android achieves downward compatibility for older versions with new features. In the current case they could for example emulate that all apps always have the permission in question while doing the real checks within the "downward compatibility wrapper" (which I assume is part of the APK in these cases). Anyway, that's speculation only.

**Comment by moving-bits** [comment]
Started testing with emulators:

API 23 (Android 6)
- open map
- select "check for missing routing data" => some missing entries listed
- select "ok" => crash

`Caused by: java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/E5_N45.rd5: Neither user 10061 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.`

So it looks rather version-specific than vendor- or device-specific.

Interestingly the system is blocking writing to the `Download` folder, so not SAF-specific c:geo folder access.

Will continue by creating emulators for newer Android versions.

**Comment by eddiemuc** [comment]
PR #13997 re-enables write-external-storage permission for SDK <= 29 and includes asking for this permission into the installation wizard
