### ISSUE TITLE
Crash when opening caches from map

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#14109]
### Describe your problem!

Since some days the nightlys are quite unstable.
If I open caches from the map view after the second or third when I click on "Mehr Details" c:geo chrashes and jumps back to the main page

### How to reproduce?

Go to map view
Shift to area with no stored caches
xxx
Click on cache symbol
Click on more details
Use back button to go back to map
Goto xxx

### Actual result after these steps?

c:geo crashes and restarts at main page

### Expected result after these steps?

No crash, but show details of cache

### Reproducible

Yes

### c:geo Version

2023.03.17-NB-f73cf2a

### System information

```text
## System information

c:geo version: 2023.03.17-NB-f73cf2a

Device:
-------
- Device type: MI 8 (dipper, Xiaomi)
- Available processors: 8
- Android version: 10
- Android build: QKQ1.190828.002 test-keys
- Screen resolution: 1080x2029px (392x737dp)
- Pixel density: 2.75
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: disabled - 23.08.55 (100400-514581917)
- Memory:  Available:1,1 GB, Total:5,5 GB, Threshold: 216,0 MB, low:false

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:224
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Time zone: GMT+01:00
- Debug mode active: no
- Last backup: 12. März, 08:34
- Routing mode: Bike
- Live map mode: true
- OSM multi-threading: true / threads: 4
- Map: Google: Satellit
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleSatelliteSource
  - Atts: none
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: Status: Eigener=Nein ([:inconclusive=false:advanced=true]AND(status:owned_no;size;difficulty_terrain:d=-:d=-:t=-:t=-;type))
- OFFLINE: Keine ([:inconclusive=false:advanced=true])

Stored Filters (#3):
- gefunden: [gefunden:inconclusive=false:advanced=false]AND(status))
- T5: [T5:inconclusive=false:advanced=false]AND(terrain:5.0:5.0))
- T5t: [T5t:inconclusive=false:advanced=false]AND(owner:*t*:contains;terrain:5.0:5.0))

Services:
-------
- Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
- Geocaching.com date format: dd.MM.yy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: communication error (2023-03-05 13-32)
- Last successful login on geocaching.com: 2023-03-17 23-04
- Routing: external / BRouter installed: true
- Installed c:geo plugins:  none

Permissions
-------
-android.permission.ACCESS_COARSE_LOCATION:: granted
-android.permission.ACCESS_FINE_LOCATION:: granted
-android.permission.READ_CONTACTS:: DENIED
-android.permission.READ_EXTERNAL_STORAGE:: DENIED
-android.permission.WRITE_EXTERNAL_STORAGE:: DENIED

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (75,7 GB free) v3 internal isDir(16 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (75,7 GB free) v3 internal isDir(16 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (75,7 GB free) v3 external non-removable isDir(1681 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (75,7 GB free) v3 internal isDir(0 entries)
- Public Folders: #12
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=9, dirs:>=11, totalFileSize:>=230,5 KB, free space: 75,7 GB, files on device: 7413760)
  - OFFLINE_MAPS: /Locus/mapsVector (User-Defined)[/Locus/mapsVector[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector/document/primary%3ALocus%2FmapsVector, Av:true, files:16, dirs:2, totalFileSize:7,1 GB, free space: 75,7 GB, files on device: 7413760)
  - OFFLINE_MAP_THEMES: /Locus/mapsVector/_themes (Default)[/Locus/mapsVector/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector::/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector/document/primary%3ALocus%2FmapsVector%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 75,7 GB, files on device: 7413760)
  - OFFLINE_MAP_SHADING: /Locus/mapsVector/_hgt (Default)[/Locus/mapsVector/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector::/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector/document/primary%3ALocus%2FmapsVector%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 75,7 GB, files on device: 7413760)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:6, dirs:0, totalFileSize:922,4 KB, free space: 75,7 GB, files on device: 7413760)
  - GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:61, dirs:0, totalFileSize:20,9 MB, free space: 75,7 GB, files on device: 7413760)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:>=8, dirs:>=12, totalFileSize:>=218,7 MB, free space: 75,7 GB, files on device: 7413760)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 75,7 GB, files on device: 7413760)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:2, dirs:3, totalFileSize:149,3 KB, free space: 75,7 GB, files on device: 7413760)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:7, dirs:1, totalFileSize:81,2 KB, free space: 75,7 GB, files on device: 7413760)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 75,7 GB, files on device: 7413760)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 75,7 GB, files on device: -1)
- Map render theme path: 
- PersistedDocumentUris: #1
- UNUSED_TRACK: null
- Persisted Uri Permissions: #2
  - content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector (20. Feb., 22:40):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (30. Jan. 2021, 13:54):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v99, Size:55,9 MB) on system internal storage

--- End of system information ---
```

**Comment by eddiemuc** [comment]
Can you provide a log file please?

**Comment by geocachermgo** [comment]
Send directly to eddiemuc via e-mail

**Comment by eddiemuc** [comment]
Looking into the log, the crash is caused by a TransactionTooLargeException while a message handler (probably main loop) tries to handle a message.

Unfortunately the stack trace gives no hint about the c:geo Codepart causing this (no c:geo class included). But since the error seems to happen after several "cache openings", I assume that some data collection piles up with every such opening, and the whole thing is sent to cache details activity on tapping "more details". Once it becomes too large, the exception is fired and c:geo crashes.

Haven't had the chance to look into code or AS yet

**Comment by eddiemuc** [comment]
Log contains the following exception over and over again:

```
--------- beginning of crash
03-10 00:43:47.578 16754 16754 E AndroidRuntime: FATAL EXCEPTION: main
03-10 00:43:47.578 16754 16754 E AndroidRuntime: Process: cgeo.geocaching, PID: 16754
03-10 00:43:47.578 16754 16754 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1146852 bytes
03-10 00:43:47.578 16754 16754 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
03-10 00:43:47.578 16754 16754 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
03-10 00:43:47.578 16754 16754 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-10 00:43:47.578 16754 16754 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
03-10 00:43:47.578 16754 16754 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7562)
03-10 00:43:47.578 16754 16754 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-10 00:43:47.578 16754 16754 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
03-10 00:43:47.578 16754 16754 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-10 00:43:47.578 16754 16754 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 1146852 bytes
03-10 00:43:47.578 16754 16754 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
03-10 00:43:47.578 16754 16754 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:511)
03-10 00:43:47.578 16754 16754 E AndroidRuntime: 	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4646)
03-10 00:43:47.578 16754 16754 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
03-10 00:43:47.578 16754 16754 E AndroidRuntime: 	... 7 more
03-10 07:01:30.580 26911 26911 E AndroidRuntime: FATAL EXCEPTION: main
03-10 07:01:30.580 26911 26911 E AndroidRuntime: Process: cgeo.geocaching, PID: 26911
03-10 07:01:30.580 26911 26911 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2285892 bytes
03-10 07:01:30.580 26911 26911 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
03-10 07:01:30.580 26911 26911 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
03-10 07:01:30.580 26911 26911 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-10 07:01:30.580 26911 26911 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
03-10 07:01:30.580 26911 26911 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7562)
03-10 07:01:30.580 26911 26911 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-10 07:01:30.580 26911 26911 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
03-10 07:01:30.580 26911 26911 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-10 07:01:30.580 26911 26911 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 2285892 bytes
03-10 07:01:30.580 26911 26911 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
03-10 07:01:30.580 26911 26911 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:511)
03-10 07:01:30.580 26911 26911 E AndroidRuntime: 	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4646)
03-10 07:01:30.580 26911 26911 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
03-10 07:01:30.580 26911 26911 E AndroidRuntime: 	... 7 more
```

**Comment by geocachermgo** [comment]
Restarted cgeo (closed via Menue,(shows running apps) swipe left)  and could open 50 caches from the map without crash.
Seems the 'pile up' extended over a londer period.
Will the closing as descibed clear such internal stacks?

**Comment by eddiemuc** [comment]
I have currently no idea what piles up unfortunately... The error message in the log is really not giving any hints.

I am currently thinking about extending our c:geo logger so it may help analyze what piles up here. As time permits...

**Comment by eddiemuc** [comment]
@geocachermgo last night's nightly contains some new code which aims to log where big transactions are created. 

It would be great if you can install this nightly, then turn on c:Geo's debug mode. When you now reproduce the problem and get a log, it should contain lines with the tag `[TransactionSize]`

I would be interested in such a log for analyzing if your time permits this. Thanks a lot.

**Comment by geocachermgo** [comment]
I send a report, with debug option active

**Comment by geocachermgo** [comment]
Again, after update to current nightly

**Comment by geocachermgo** [comment]
Yes, with the mentioned ticket number

**Comment by moving-bits** [comment]
have forwarded the logfile to @eddiemuc

**Comment by eddiemuc** [comment]
Got the log and analyzed it. It doesn't seem to be a too-larger save state causing this exception.

Using ChatGPT (I am still stunned what it can do....) I found out that the exception is probably caused by the `onStop `event of an activity (reason for this guess: exception contains `android.app.servertransaction.PendingTransactionActions$StopInfo.run`). But I was not able to identify whats the problem here

**Comment by eddiemuc** [comment]
Here's something interesting:

```
3-29 07:33:15.238 11648 11648 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 2336732)
03-29 07:33:15.238 11648 11648 W ActivityStopInfo: Bundle stats:
03-29 07:33:15.239 11648 11648 W ActivityStopInfo:   android:viewHierarchyState [size=4812]
03-29 07:33:15.239 11648 11648 W ActivityStopInfo:     android:views [size=4764]
03-29 07:33:15.260 11648 11648 W ActivityStopInfo:   route [size=2329180]
03-29 07:33:15.260 11648 11648 W ActivityStopInfo:   androidx.lifecycle.BundlableSavedStateRegistry.key [size=1212]
03-29 07:33:15.260 11648 11648 W ActivityStopInfo: PersistableBundle stats:
03-29 07:33:15.260 11648 11648 W ActivityStopInfo:   [null]
03-29 07:33:15.260 11648 11648 D AndroidRuntime: Shutting down VM
03-29 07:33:15.261 11648 11648 E AndroidRuntime: FATAL EXCEPTION: main
03-29 07:33:15.261 11648 11648 E AndroidRuntime: Process: cgeo.geocaching, PID: 11648
03-29 07:33:15.261 11648 11648 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 2336732 bytes
03-29 07:33:15.261 11648 11648 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:161)
03-29 07:33:15.261 11648 11648 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
03-29 07:33:15.261 11648 11648 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-29 07:33:15.261 11648 11648 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:224)
03-29 07:33:15.261 11648 11648 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7562)
03-29 07:33:15.261 11648 11648 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-29 07:33:15.261 11648 11648 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
03-29 07:33:15.261 11648 11648 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-29 07:33:15.261 11648 11648 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 2336732 bytes
03-29 07:33:15.261 11648 11648 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
03-29 07:33:15.261 11648 11648 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:511)
03-29 07:33:15.261 11648 11648 E AndroidRuntime: 	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4646)
03-29 07:33:15.261 11648 11648 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
03-29 07:33:15.261 11648 11648 E AndroidRuntime: 	... 7 more

```

**Comment by eddiemuc** [comment]
It seems that on stop of map activity a parcelable of the current `InvididualRoute` is stored in the save state of the activity. This parcelable gets far too large (in the example of the last comment 2329180 bytes, roughly 2MB; max. allowed size is 1MB)

@moving-bits is there a way to ensure that a parcelled individual route is not larger than e.g. 500KB? Or is there a way such that the individual route doesn't need to be stored in the activity's save state?

**Comment by geocachermgo** [comment]
My individual route has only 14 point

**Comment by eddiemuc** [comment]
@geocachermgo is your individual "complex"? Means: 
* are the geocaches far apart?
* What kind of route type are you using? (straight-line,  by foot, by bicycle, by car)
* Which map are you using? Google, OSM or Offline?

Because the route between two caches is stored as a list of geopoint on every turn of the street etc, and the size of the route object increases with this.

**Comment by geocachermgo** [comment]
I stored route gpx: it has 0.99k
I stored the track: it has 648kB
Shall I send the file to support?
It a round trip, the farest point is San Marino, but is not routed completely.
![IMG_20230401_194416](https://user-images.githubusercontent.com/43813636/229306411-2e584837-7d14-4d36-9777-746eb41037b1.jpg)

**Comment by geocachermgo** [comment]
I switch map and routing quite often. Mostly bicyle and walk. At the moment it's "walk". I have installed brouter.

**Comment by eddiemuc** [comment]
@geocachermgo would be great to have the file. Doesn't matter whether it's route gpx or track

**Comment by eddiemuc** [comment]
BTW: a route by foot/bicycle on such a big distance (>600km * 2) could well result in a very large point-line.

@moving-bits I still don't understand why we need to store these route details on activity state anyway.

**Comment by geocachermgo** [comment]
> @geocachermgo would be great to have the file. Doesn't matter whether it's route gpx or track

Send (to support).
Or shall I send it directly to you?

**Comment by eddiemuc** [comment]
I have massive problems getting routing calculation to work on my emulator with longer distances. Even a route by foot/bicycle between e.g. frankfurt and hamburg fails to calculate. Let alone the distances in @geocachermgo s route.

It doesn't matter though. Even when I calculate very short routes (e.g. within munich) I already get easily up to 4000-500 points. Storing one point (Geopoint) takes 8 bytes of space, and in a transaction a total of 1MB is the upper limit. So we would hit this at about 131000 points. It is easy to imagine that this limit is hit in @geocachermgo s example.

--> So it boils down to that we can't store routes in activity save bundles. @moving-bits : can you take over from here on?

**Comment by moving-bits** [comment]
Sorry @eddiemuc for not coming back to this earlier. Not much time lately, so I had my c:geo activity focused on support.

> @moving-bits I still don't understand why we need to store these route details on activity state anyway.

Recalculating a route, especially a long distance-one, is very costly, so I tried to avoid it by caching calculation results, both within a route and preserving it over destroyal of activity.

If I'm reading activity lifecycle correctly, this will happen only when destroying an activity, not when pausing it, so we could remove it from `onSaveInstanceState` and trigger a recalculation later on (maybe directly in `onRestoreInstanceState`).

Still I do not see why the track provided already hits the limit - it contains some 13,000 points, which would lead to a bit more than 100k - still far to go to the 1MB limit.

**Comment by moving-bits** [comment]
> I have massive problems getting routing calculation to work on my emulator with longer distances. 

There are two limits involved, which may hit in the emulator, especially for long distances:
- c:geo has a distance limit (can be raised in settings => offline navigation)
- brouter (as well as the internal engine) has a limit of 60s (IIRC)

**Comment by moving-bits** [comment]
@geocachermgo 
Has the original problem (crash on opening a cache from map view) been resolved for you with the recent nightlies? We have applied a change to the map about three weeks ago, which would prevent trying to store the calculated path of an individual route when leaving the map view.

**Comment by geocachermgo** [comment]
I deleted the long route and had crashes anyway shortly after that. In the last weeks there were no crashes.

**Comment by moving-bits** [comment]
That's good news, thanks for the info. So let's close here, and open a separate issue (or reopen here) if something similar arises.
