### ISSUE TITLE
Crash when trying to open cache details

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14217]
### Describe your problem!

A user claims, that c:geo keeps crashing when he tries to open any cache.

Any idea how to debug other than resetting the app?

### How to reproduce?

Open cache details

### Actual result after these steps?

Users log is full of crashes like this:
```
04-20 21:28:58.657  9674  9674 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 539064 bytes
04-20 21:28:58.657  9674  9674 E AndroidRuntime: 	at android.app.ActivityClient.activityStopped(ActivityClient.java:88)
04-20 21:28:58.657  9674  9674 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:143)
04-20 21:28:58.657  9674  9674 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
04-20 21:28:58.657  9674  9674 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-20 21:28:58.657  9674  9674 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
04-20 21:28:58.657  9674  9674 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
04-20 21:28:58.657  9674  9674 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8757)
04-20 21:28:58.657  9674  9674 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-20 21:28:58.657  9674  9674 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
04-20 21:28:58.657  9674  9674 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
04-20 21:28:58.657  9674  9674 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 539064 bytes
04-20 21:28:58.657  9674  9674 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
04-20 21:28:58.657  9674  9674 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:662)
04-20 21:28:58.657  9674  9674 E AndroidRuntime: 	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1309)
04-20 21:28:58.657  9674  9674 E AndroidRuntime: 	at android.app.ActivityClient.activityStopped(ActivityClient.java:85)
04-20 21:28:58.657  9674  9674 E AndroidRuntime: 	... 9 more
```

### Expected result after these steps?

Normal operation

### Reproducible

Unclear

### c:geo Version

2023.04.11

### System information

```text
## System information

c:geo version: 2023.04.11

Device:
-------
- Device type: SM-G781B (r8qxeea, samsung)
- Available processors: 8
- Android version: 13
- Android build: TP1A.220624.014.G781BXXS4HWC2
- Screen resolution: 1080x2186px (411x832dp)
- Pixel density: 2.625
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 23.13.12 (190408-519946965)
- Memory:  Available:2,0 GB, Total:5,5 GB, Threshold: 303,0 MB, low:false

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: orientation

Program settings:
-------
- Settings: v9, Count:224
- Set language: fr
- System date format: dd/MM/y
- Time zone: GMT+02:00
- Debug mode active: no
- Last backup: 22 avr., 09:42
- Routing mode: Car
- Live map mode: true
- OSM multi-threading: true / threads: 4
- Map: France (hors-ligne)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:primary:cgeo/maps/france.map
  - Atts: mapsforge-map-writer-master-SNAPSHOT
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: Aucun ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status))
- OFFLINE: Aucun ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status))

Stored Filters (#0):

Services:
-------
- Geocaching sites enabled:
   - geocaching.com: Logged in (Connecté) / PREMIUM
   - Geocaching.com Adventure Lab
- Geocaching.com date format: dd/MM/yyyy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: communication error (2023-04-19 19-43)
- Last successful login on geocaching.com: 2023-04-22 09-47
- Routing: internal / BRouter installed: true
- Installed c:geo plugins:  none

Permissions
-------
- android.permission.ACCESS_COARSE_LOCATION:: granted
- android.permission.ACCESS_FINE_LOCATION:: granted
- android.permission.READ_CONTACTS:: DENIED
- android.permission.READ_EXTERNAL_STORAGE:: DENIED
- android.permission.WRITE_EXTERNAL_STORAGE:: DENIED

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (26,8 GB free) v3 internal isDir(7 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (26,8 GB free) v3 internal isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (26,8 GB free) v3 external non-removable isDir(2561 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (26,8 GB free) v3 internal isDir(0 entries)
- Map render theme path: 
- Public Folders: #12
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=6, dirs:>=10, totalFileSize:>=313,9 MB, free space: 26,8 GB, files on device: 13511677)
  - OFFLINE_MAPS: /cgeo/maps (User-Defined)[/cgeo/maps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps, Av:true, files:3, dirs:2, totalFileSize:3,3 GB, free space: 26,8 GB, files on device: 13511677)
  - OFFLINE_MAP_THEMES: /cgeo/maps (User-Defined)[/cgeo/maps[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps, Av:true, files:3, dirs:2, totalFileSize:3,3 GB, free space: 26,8 GB, files on device: 13511677)
  - OFFLINE_MAP_SHADING: /cgeo/maps/_hgt (Default)[/cgeo/maps/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps::/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps/document/primary%3Acgeo%2Fmaps%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 26,8 GB, files on device: 13511677)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:2, dirs:0, totalFileSize:3,4 MB, free space: 26,8 GB, files on device: 13511677)
  - GPX: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=6, dirs:>=10, totalFileSize:>=313,9 MB, free space: 26,8 GB, files on device: 13511677)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:4, dirs:3, totalFileSize:310,5 MB, free space: 26,8 GB, files on device: 13511677)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 26,8 GB, files on device: 13511677)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 26,8 GB, files on device: 13511677)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:12, dirs:1, totalFileSize:549,4 MB, free space: 26,8 GB, files on device: 13511677)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:5, dirs:0, totalFileSize:549,3 MB, free space: 26,8 GB, files on device: 13511677)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 26,8 GB, files on device: -1)
- PersistedDocumentUris: #1
- UNUSED_TRACK: null
- Persisted Uri Permissions: #2
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (23 mai 2022, 21:10):RW
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo%2Fmaps (7 août 2022, 21:30):RW
- Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (v99, Size:155,2 MB) on user storage

--- End of system information ---
```

### Additional Information

Support ticket 656520

**Comment by moving-bits** [comment]
Does this happen when coming from a map? Then it might be that the user has created an individual route which results in a huge number of calculated points. See discussion in #14109 which we have a proposed fix for in the nightlies with #14165.
