### ISSUE TITLE
User unable to create backups

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14218]
### Describe your problem!

A user reports, that we cannot create backups any longer.
Files are there but with 0 byte filesize.

### How to reproduce?

Perform a manual backup

### Actual result after these steps?

Logfile shows this:
```
4-13 17:44:52.981 25050 25050 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at cgeo.geocaching.utils.SettingsUtils.getType(SettingsUtils.java:87)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at cgeo.geocaching.utils.BackupUtils.createSettingsBackupInternal(BackupUtils.java:582)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at cgeo.geocaching.utils.BackupUtils.backupInternal(BackupUtils.java:541)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at cgeo.geocaching.utils.BackupUtils.backup(BackupUtils.java:369)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at cgeo.geocaching.settings.fragments.PreferenceBackupFragment.lambda$onCreatePreferences$0(PreferenceBackupFragment.java:23)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at cgeo.geocaching.settings.fragments.PreferenceBackupFragment.$r8$lambda$LYlQUpmmMlAgENsHhuocmhJYpoo(Unknown Source:0)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at cgeo.geocaching.settings.fragments.PreferenceBackupFragment$$ExternalSyntheticLambda2.onPreferenceClick(Unknown Source:4)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at androidx.preference.Preference.performClick(Preference.java:1200)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at androidx.preference.Preference.performClick(Preference.java:1182)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at androidx.preference.Preference$1.onClick(Preference.java:182)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at android.view.View.performClick(View.java:7558)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at android.view.View.performClickInternal(View.java:7534)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:29661)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:240)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:351)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8364)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
04-13 17:44:52.981 25050 25050 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

### Expected result after these steps?

backup is created

### Reproducible

Unclear

### c:geo Version

2023.04.13-NB-f30a5ba

### System information

```text
## System information

c:geo version: 2023.04.13-NB-f30a5ba

Device:
- Device type: LE2123 (OnePlus9Pro_EEA, OnePlus)
- Available processors: 8
- Android version: 13
- Android build: LE2123_11_F.75
- Screen resolution: 1080x2200px (411x838dp)
- Pixel density: 2.625
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 23.13.12 (190408-519946965)
- Memory:  Available:3,9 GB, Total:11,0 GB, Threshold: 648,0 MB, low:false

Sensor and location:
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: orientation

Program settings:
- Settings: v9, Count:277
- Set language: de_DE (system default)
- System date format: dd.MM.yy
- Time zone: GMT+02:00
- Debug mode active: no
- Log Settings: debug=false, minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=8, throwOnError=false, transactionSizes=false
- Last backup: 13. Apr., 17:45
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: true / threads: 4
- Map: Germany (OAM) (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:primary:Locus/mapsVector/Germany (OAM).map
  - Atts: Maps: (c)Christian Kernbeis & Michael Bechtold , Themes: (c)Tobias Kuehn, http://www.openandromaps.org 2012-2022
  - Theme: Elevate.zip:Elements.xml

Filters:
- Hide waypoints: original
- LIVE: Keine ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status))
- OFFLINE: Keine ([:inconclusive=false:advanced=false]AND(type;difficulty_terrain:d=-:d=-:t=-:t=-;status))

Stored Filters (#1):
- Offline-Log: [Offline-Log:inconclusive=false:advanced=false]AND(offlinelog::is_present;type;difficulty:-:-;terrain:-:-))

Services:
- Geocaching sites enabled:
   - geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   - extremcaching.com: Logged in (Anmeldung OK)
   - Geocaching.com Adventure Lab
   - opencaching.de: Logged in (Anmeldung OK)
- Geocaching.com date format: yyyy-MM-dd
- Geocaching.com website language: en-US
- Last login error on geocaching.com: communication error (2023-02-26 15-41)
- Last successful login on geocaching.com: 2023-04-13 17-45
- Routing: internal / BRouter installed: true
- Installed c:geo plugins: contacts

Permissions
- android.permission.ACCESS_COARSE_LOCATION:: granted
- android.permission.ACCESS_FINE_LOCATION:: granted
- android.permission.READ_CONTACTS:: DENIED
- android.permission.READ_EXTERNAL_STORAGE:: granted
- android.permission.WRITE_EXTERNAL_STORAGE:: DENIED

Paths
- System internal c:geo dir: /data/user/0/cgeo.geocaching (50,1 GB free) v3 internal isDir(8 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (50,1 GB free) v3 internal isDir(8 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (50,1 GB free) v3 external non-removable isDir(2269 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (50,1 GB free) v3 internal isDir(0 entries)
- Map render theme path: Elevate.zip:Elements.xml
- Public Folders: #12
  - BASE: /c.geo (User-Defined)[/c.geo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Ac.geo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Ac.geo/document/primary%3Ac.geo, Av:true, files:>=4, dirs:>=14, totalFileSize:>=636,6 MB, free space: 50,1 GB, files on device: 12812797)
  - OFFLINE_MAPS: /Locus/mapsVector (User-Defined)[/Locus/mapsVector[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector/document/primary%3ALocus%2FmapsVector, Av:true, files:10, dirs:3, totalFileSize:7,5 GB, free space: 50,1 GB, files on device: 12812797)
  - OFFLINE_MAP_THEMES: /Locus/mapsVector/_themes (User-Defined)[/Locus/mapsVector/_themes[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector%2F_themes::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector%2F_themes/document/primary%3ALocus%2FmapsVector%2F_themes, Av:true, files:3, dirs:0, totalFileSize:558,2 KB, free space: 50,1 GB, files on device: 12812797)
  - OFFLINE_MAP_SHADING: /Locus/mapsVector/_hgt (Default)[/Locus/mapsVector/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector::/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector/document/primary%3ALocus%2FmapsVector%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 50,1 GB, files on device: 12812797)
  - LOGFILES: /c.geo/logfiles (Default)[/c.geo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Ac.geo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Ac.geo/document/primary%3Ac.geo%2Flogfiles, Av:true, files:3, dirs:0, totalFileSize:100,3 KB, free space: 50,1 GB, files on device: 12812797)
  - GPX: /c.geo/gpx (User-Defined)[/c.geo/gpx[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Ac.geo%2Fgpx::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Ac.geo%2Fgpx/document/primary%3Ac.geo%2Fgpx, Av:true, files:17, dirs:0, totalFileSize:86,8 MB, free space: 50,1 GB, files on device: 12812797)
  - BACKUP: /c.geo/backup (Default)[/c.geo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Ac.geo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Ac.geo/document/primary%3Ac.geo%2Fbackup, Av:true, files:>=4, dirs:>=14, totalFileSize:>=0 B, free space: 50,1 GB, files on device: 12812797)
  - FIELD_NOTES: /c.geo/field-notes (Default)[/c.geo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Ac.geo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Ac.geo/document/primary%3Ac.geo%2Ffield-notes, Av:true, files:2, dirs:0, totalFileSize:6,6 MB, free space: 50,1 GB, files on device: 12812797)
  - SPOILER_IMAGES: /c.geo/GeocachePhotos (Default)[/c.geo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Ac.geo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Ac.geo/document/primary%3Ac.geo%2FGeocachePhotos, Av:true, files:>=2, dirs:>=6, totalFileSize:>=730,0 KB, free space: 50,1 GB, files on device: 12812797)
  - ROUTING_BASE: /c.geo/routing (Default)[/c.geo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Ac.geo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Ac.geo/document/primary%3Ac.geo%2Frouting, Av:true, files:15, dirs:1, totalFileSize:820,0 MB, free space: 50,1 GB, files on device: 12812797)
  - ROUTING_TILES: /c.geo/routing/segments4 (Default)[/c.geo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Ac.geo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Ac.geo/document/primary%3Ac.geo%2Frouting%2Fsegments4, Av:true, files:8, dirs:0, totalFileSize:820,0 MB, free space: 50,1 GB, files on device: 12812797)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 50,1 GB, files on device: -1)
- PersistedDocumentUris: #1
- UNUSED_TRACK: content://com.android.externalstorage.documents/document/primary%3ADownload%2FWWT_Drei-Waelder-Weg.gpx
- Persisted Uri Permissions: #4
  - content://com.android.externalstorage.documents/tree/primary%3Ac.geo%2Fgpx (3. Apr., 00:23):RW
  - content://com.android.externalstorage.documents/tree/primary%3Ac.geo (3. Apr., 00:18):RW
  - content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector (24. Juli 2022, 19:21):RW
  - content://com.android.externalstorage.documents/tree/primary%3ALocus%2FmapsVector%2F_themes (22. Aug. 2022, 20:04):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v99, Size:686,5 MB) on system internal storage

--- End of system information ---
```

### Additional Information

Support ticket 246488

**Comment by Lineflyer** [comment]
Addition:
If the user tries to create a backup a new folder with correct date/time is created.
It contains a o byte cgeosettings.xml and no database backup file.

**Comment by moving-bits** [comment]
The offending code line tries to document unknown data types in settings. I'm not sure why it gets called with a `null` object (but only when performing a manual backup!), but I'll create a PR to catch this anyway.

**Comment by moving-bits** [comment]
fix confirmed by user as working
