### ISSUE TITLE
Mapsforge map: NPE in IndividualRoutePointLayer.onLongPress

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14212]
### Describe your problem!

Lately I experience crashes while browsing on my offline map.
This mostly happens on a cache map or list map when trying to long tap to create a new cache/waypoint.

### How to reproduce?

Not really reproducible but can be provoked within some minutes of working with the map

### Actual result after these steps?

```
04-22 11:57:12.420 21113 21113 E AndroidRuntime: FATAL EXCEPTION: main
04-22 11:57:12.420 21113 21113 E AndroidRuntime: Process: cgeo.geocaching, PID: 21113
04-22 11:57:12.420 21113 21113 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
04-22 11:57:12.420 21113 21113 E AndroidRuntime: 	at org.mapsforge.map.android.graphics.AndroidBitmap.getWidth(AndroidBitmap.java:114)
04-22 11:57:12.420 21113 21113 E AndroidRuntime: 	at cgeo.geocaching.maps.mapsforge.v6.layers.IndividualRoutePointLayer.onLongPress(IndividualRoutePointLayer.java:28)
04-22 11:57:12.420 21113 21113 E AndroidRuntime: 	at org.mapsforge.map.android.input.TouchGestureHandler.onLongPress(TouchGestureHandler.java:161)
04-22 11:57:12.420 21113 21113 E AndroidRuntime: 	at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:993)
04-22 11:57:12.420 21113 21113 E AndroidRuntime: 	at android.view.GestureDetector.-$$Nest$mdispatchLongPress(Unknown Source:0)
04-22 11:57:12.420 21113 21113 E AndroidRuntime: 	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:357)
04-22 11:57:12.420 21113 21113 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-22 11:57:12.420 21113 21113 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:226)
04-22 11:57:12.420 21113 21113 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:313)
04-22 11:57:12.420 21113 21113 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8757)
04-22 11:57:12.420 21113 21113 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-22 11:57:12.420 21113 21113 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
04-22 11:57:12.420 21113 21113 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
04-22 11:57:12.420 21113 21113 W cgeo    : [main] UncaughtException
04-22 11:57:12.420 21113 21113 W cgeo    : java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
04-22 11:57:12.420 21113 21113 W cgeo    : 	at org.mapsforge.map.android.graphics.AndroidBitmap.getWidth(AndroidBitmap.java:114)
04-22 11:57:12.420 21113 21113 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.layers.IndividualRoutePointLayer.onLongPress(IndividualRoutePointLayer.java:28)
04-22 11:57:12.420 21113 21113 W cgeo    : 	at org.mapsforge.map.android.input.TouchGestureHandler.onLongPress(TouchGestureHandler.java:161)
04-22 11:57:12.420 21113 21113 W cgeo    : 	at android.view.GestureDetector.dispatchLongPress(GestureDetector.java:993)
04-22 11:57:12.420 21113 21113 W cgeo    : 	at android.view.GestureDetector.-$$Nest$mdispatchLongPress(Unknown Source:0)
04-22 11:57:12.420 21113 21113 W cgeo    : 	at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:357)
04-22 11:57:12.420 21113 21113 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-22 11:57:12.420 21113 21113 W cgeo    : 	at android.os.Looper.loopOnce(Looper.java:226)
04-22 11:57:12.420 21113 21113 W cgeo    : 	at android.os.Looper.loop(Looper.java:313)
04-22 11:57:12.420 21113 21113 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:8757)
04-22 11:57:12.420 21113 21113 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
04-22 11:57:12.420 21113 21113 W cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
04-22 11:57:12.420 21113 21113 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

### Expected result after these steps?

No crash

### Reproducible

Unclear

### c:geo Version

2022.04.21-NB

**Comment by moving-bits** [comment]
_Copied from https://github.com/cgeo/cgeo/issues/14243#issue-1691219063:_

Not many errors reported in Play Store yet for current beta 2023.04.30, but this one is so far the most frequent one:

`java.lang.NullPointerException` in `cgeo.geocaching.maps.mapsforge.v6.layers.IndividualRoutePointLayer.onLongPress`

```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
  at org.mapsforge.map.android.graphics.AndroidBitmap.getWidth (AndroidBitmap.java:114)
  at cgeo.geocaching.maps.mapsforge.v6.layers.IndividualRoutePointLayer.onLongPress (IndividualRoutePointLayer.java:28)
  at org.mapsforge.map.android.input.TouchGestureHandler.onLongPress (TouchGestureHandler.java:161)
  at android.view.GestureDetector.dispatchLongPress (GestureDetector.java:890)
  at android.view.GestureDetector.-$$Nest$mdispatchLongPress
  at android.view.GestureDetector$GestureHandler.handleMessage (GestureDetector.java:324)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:211)
  at android.os.Looper.loop (Looper.java:300)
  at android.app.ActivityThread.main (ActivityThread.java:8152)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:580)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1028)
```

no pattern in Android versions or vendors

A slight variation of the error log is like this:

```
Exception java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
  at org.mapsforge.map.android.graphics.AndroidBitmap.getWidth (AndroidBitmap.java:114)
  at cgeo.geocaching.maps.mapsforge.v6.layers.IndividualRoutePointLayer.onLongPress (IndividualRoutePointLayer.java:28)
  at org.mapsforge.map.android.input.TouchGestureHandler.onLongPress (TouchGestureHandler.java:161)
  at android.view.GestureDetector.dispatchLongPress (GestureDetector.java:986)
  at android.view.GestureDetector.access$400 (GestureDetector.java:69)
  at android.view.GestureDetector$GestureHandler.handleMessage (GestureDetector.java:350)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:226)
  at android.os.Looper.loop (Looper.java:313)
  at android.app.ActivityThread.main (ActivityThread.java:8751)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:571)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1135)
```

**Comment by eddiemuc** [comment]
The cgeo class in question `IndividualRoutePointLayer` creates a static `AndroidBitmap` instane called `marker`. This marker class is apparently destroyed at the time the `onLongPress` method is called. This in turn leads to NPE (when calling getWidth, the AndroidBitmap finds its internal bitmap instance to be null)

Question is why the marker was destroyed, and whether it is even legal according to mapsforge framework to store such static references to `AndroidBitmap`. @fm-sys since this is your code, could you take a look into this?

**Comment by fm-sys** [comment]
Does this crash still happen? A fix is out meanwhile, please reopen if it should not be solved yet...
