### ISSUE TITLE
[Nightly] Crash on creating filter with "letzte Detailaktualisierung"

### ISSUE THREAD

**Issue by murggel** [cgeo/cgeo#14395]
### Describe your problem!

c:geo crashes when I create a filter with the criteria "letzte Detailaktualisierung".

### How to reproduce?

1. Open advanced filter dialog from map or search activity.
2. Add criteria "letzte Detailaktualisierung"

### Actual result after these steps?

The app crashes.

### Expected result after these steps?

The app does not crash.

### Reproducible

Yes

### c:geo Version

2023.07.06-NB-3ca512a

### System information

```text
## System information

c:geo version: 2023.07.06-NB-3ca512a

Device:
-------
- Device type: SM-G980F (x1sxx, samsung)
- Available processors: 8
- Android version: 11
- Android build: RP1A.200720.012.G980FXXSCDUK1
- Screen resolution: 1080x2178px (360x726dp)
- Pixel density: 3.3000002
- System font scale: 1.1 / used scale: 1.1
- Sailfish OS detected: false
- Google Play services: enabled - 23.24.14 (150400-544099984)
- Memory:  Available:2,3 GB, Total:7,3 GB, Threshold: 216,0 MB, low:false

Sensor and location:
-------
- Low power mode: active
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:200
- Set language: de
- System date format: dd.MM.yy
- Time zone: GMT+02:00
- Debug mode active: no
- Log Settings: debug=false, minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=8, throwOnError=false, transactionSizes=false
- Last manual backup: 28. Dez. 2022, 00:43
- Last auto backup: 25. Juni, 22:04
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Kombiniert (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMultiMapSource
  - Atts: austria.map: / Map data (c) OpenStreetMap contributors /  / Germany (OAM).map: / VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2022 /  / Germany.map: / Map data (c) OpenStreetMap contributors /  / Switzerland.map: / Map data (c) OpenStreetMap contributors
  - Theme: Elevate.zip:Elements.xml

Filters:
-------
- Hide waypoints: original visited
- LIVE: Keine ([:inconclusive=false:advanced=false])
- OFFLINE: Status: Gelöster Mystery=Nein, NICHT[Komplex] ([:inconclusive=false:advanced=true]AND(status:solved_mystery_no;NOT(AND(stored_list:103:96))))

Stored Filters (#19):
...


Services:
-------
- Geocaching sites enabled:
   - geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   - Geocaching.com Adventure Lab
   - opencaching.de: Logged in (Anmeldung OK)
- Geocaching.com date format: dd MMM yy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: communication error (2023-06-30 09-35)
- Last successful login on geocaching.com: 2023-07-07 00-23
- Routing: internal / BRouter installed: false
- Installed c:geo plugins:  none

Permissions
-------
- android.permission.ACCESS_COARSE_LOCATION:: granted
- android.permission.ACCESS_FINE_LOCATION:: granted
- android.permission.READ_CONTACTS:: DENIED
- android.permission.READ_EXTERNAL_STORAGE:: DENIED
- android.permission.WRITE_EXTERNAL_STORAGE:: DENIED

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (59,8 GB free) v3 internal isDir(8 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (59,8 GB free) v3 internal isDir(8 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (59,8 GB free) v3 external non-removable isDir(3379 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (59,8 GB free) v3 internal isDir(0 entries)
- Map render theme path: Elevate.zip:Elements.xml
- Public Folders: #12
  - BASE: SD-Karte/CGeo (User-Defined)[SD-Karte/CGeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo, Av:true, files:>=21, dirs:>=9, totalFileSize:>=7,1 GB, free space: 104,2 GB, files on device: 0)
  - OFFLINE_MAPS: SD-Karte/CGeo/maps (Default)[SD-Karte/CGeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Fmaps, Av:true, files:10, dirs:2, totalFileSize:7,1 GB, free space: 104,2 GB, files on device: 0)
  - OFFLINE_MAP_THEMES: SD-Karte/CGeo/maps/_themes (Default)[SD-Karte/CGeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Fmaps%2F_themes, Av:true, files:2, dirs:0, totalFileSize:518,8 KB, free space: 104,2 GB, files on device: 0)
  - OFFLINE_MAP_SHADING: SD-Karte/CGeo/maps/_hgt (Default)[SD-Karte/CGeo/maps/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/maps/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Fmaps%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 104,2 GB, files on device: 0)
  - LOGFILES: SD-Karte/CGeo/logfiles (Default)[SD-Karte/CGeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Flogfiles, Av:true, files:1, dirs:0, totalFileSize:72,7 KB, free space: 104,2 GB, files on device: 0)
  - GPX: SD-Karte/CGeo/gpx (Default)[SD-Karte/CGeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Fgpx, Av:true, files:10, dirs:0, totalFileSize:257,9 KB, free space: 104,2 GB, files on device: 0)
  - BACKUP: SD-Karte/CGeo/backup (Default)[SD-Karte/CGeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Fbackup, Av:true, files:>=8, dirs:>=10, totalFileSize:>=451,9 MB, free space: 104,2 GB, files on device: 0)
  - FIELD_NOTES: SD-Karte/CGeo/field-notes (Default)[SD-Karte/CGeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Ffield-notes, Av:true, files:21, dirs:0, totalFileSize:59,8 KB, free space: 104,2 GB, files on device: 0)
  - SPOILER_IMAGES: SD-Karte/CGeo/GeocachePhotos (Default)[SD-Karte/CGeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2FGeocachePhotos, Av:true, files:>=4, dirs:>=44, totalFileSize:>=6,8 MB, free space: 104,2 GB, files on device: 0)
  - ROUTING_BASE: SD-Karte/CGeo/routing (Default)[SD-Karte/CGeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Frouting, Av:true, files:10, dirs:1, totalFileSize:484,3 MB, free space: 104,2 GB, files on device: 0)
  - ROUTING_TILES: SD-Karte/CGeo/routing/segments4 (Default)[SD-Karte/CGeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo/document/3438-3261%3ACGeo%2Frouting%2Fsegments4, Av:true, files:3, dirs:0, totalFileSize:484,2 MB, free space: 104,2 GB, files on device: 0)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 59,8 GB, files on device: -1)
- PersistedDocumentUris: #1
  - UNUSED_TRACK: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/3438-3261%3ACGeo (1. Apr. 2022, 19:00):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v99, Size:131,0 MB) on system internal storage

--- End of system information ---
```

### Additional Information

[logcat-2023-07-07-00-23-34-2.txt](https://github.com/cgeo/cgeo/files/11972953/logcat-2023-07-07-00-23-34-2.txt)

**Comment by ztNFny** [comment]
It seems you have a filter stored with "-10" as value and initializing the filter with that causes the crash.

```
java.text.ParseException: Unparseable date: "-10"
 	at java.text.DateFormat.parse(DateFormat.java:362)
 	at cgeo.geocaching.filters.core.DateFilter.parseDate(DateFilter.java:150)
 	at cgeo.geocaching.filters.core.DateFilter.setConfig(DateFilter.java:127)
 	at cgeo.geocaching.filters.core.DateRangeGeocacheFilter.setConfig(DateRangeGeocacheFilter.java:51)
```

Should be caused by https://github.com/cgeo/cgeo/commit/ac437971ccb9b219317648098385183dfd69fcad which changed the filter type. Didn't think about stored filters then ☹️
Not sure what's the best way to proceed here... Rename the filter from STORED_SINCE to make it a "new" filter?

**Comment by murggel** [comment]
Indeed I have a filter for unsaved caches...
UnsavedCaches: [_unsaved:inconclusive=false:advanced=false]AND(status:found_no:exclude_archived;stored_since:-:-:false:-1:-1))

**Comment by ztNFny** [comment]
I'm unable to reproduce this issue. Went back to before the change was merged, created a filter, reapplied the change. Then tried it with your filter expression, in no case do I get a crash.

**Comment by murggel** [comment]
Hm, then I don't have any filter with date -10.

I tried to delete all filters, c:geo still crashes.
So probably a dedicated cache is the reason? 
I will try to debug with my database...

**Comment by ztNFny** [comment]
> Hm, then I don't have any filter with date -10.
> 
> I tried to delete all filters, c:geo still crashes. So probably a dedicated cache is the reason? I will try to debug with my database...

Can you please test if this fixes the issue? GeocacheFilterType.java, line 36, change "stored_since" to "somethingnew"

**Comment by murggel** [comment]
Weired - I just tried to debug - no crash -> updated to current nightly on my device - no crash. But I don't see any possible closed PRs to explain that behaviour-change

**Comment by murggel** [comment]
So I will close that issue and observe it...
