### ISSUE TITLE
Crash in landscape

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14465]
With Saturdays master (https://github.com/cgeo/cgeo/commit/4e4a22db776afaf370d6cec6abf1c64641ddb4dd) i get crashes whenever cgeo is started in landscape or when rotating the device and doing any UI interaction.
Screen size in landscape is 1706x1080 - might be relevant as i can't reproduce on another device.
In portrait everything is fine.

FATAL EXCEPTION: main
Process: cgeo.geocaching, PID: 17939
java.lang.RuntimeException: Unable to resume activity {cgeo.geocaching/cgeo.geocaching.MainActivity}: java.lang.ClassCastException: com.google.android.material.navigationrail.NavigationRailView cannot be cast to com.google.android.material.bottomnavigation.BottomNavigationView
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4935)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4974)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:60)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:344)
	at android.app.ActivityThread.main(ActivityThread.java:8212)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
Caused by: java.lang.ClassCastException: com.google.android.material.navigationrail.NavigationRailView cannot be cast to com.google.android.material.bottomnavigation.BottomNavigationView
	at cgeo.geocaching.activity.AbstractBottomNavigationActivity.setCustomBNitem(AbstractBottomNavigationActivity.java:252)
	at cgeo.geocaching.activity.AbstractBottomNavigationActivity.onResume(AbstractBottomNavigationActivity.java:206)
	at cgeo.geocaching.MainActivity.onResume(MainActivity.java:443)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1491)
	at android.app.Activity.performResume(Activity.java:8280)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4925)
	... 13 more

**Comment by ztNFny** [comment]
@moving-bits i think this is caused by https://github.com/cgeo/cgeo/commit/486c7329343ea3691131a6a53159a29d3a6816e0#diff-f8cfdefa212cf26fb6e86686aaf06a83c664eaf3c42be4cc9e81d5b6dcef6fddR254

Not sure though why i see it only in landscape.

**Comment by ztNFny** [comment]
Btw, i find the label "custom menu entry" quite bad. I wouldn't have known what it does had i not seen the commits.

How about "last bottom navigation item"? (Bottom is required as else it'll be confused with map routing kimd of navigation)

**Comment by moving-bits** [comment]
It does appear in landscape only, as we use a `NavigationRailView` in landscape mode, whereas we use a `BottomNavigationView` in portrait mode. I'll prepare a fix.
