### ISSUE TITLE
TB logging not possible for non-migrated user

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#14681]
### Describe your problem!

Using nightly 2023.10.03-NB2 (with new log API) I cannot grab a trackable.

### How to reproduce?

- Search for a trackable using its secret code
- The trackable page is shown (in my case another user has this TB in his inventory)
- Open TB log page, select "Woanders mitgenommen"
- Write log text
- Send the log

### Actual result after these steps?

c:geo claims it could not upload a log picture (although there is no log picture in this scenario)
![image](https://github.com/cgeo/cgeo/assets/949669/bf95643e-d7ad-4106-8abd-c4edec5c6773)

### Expected result after these steps?

TB grabbing should work normal

### Reproducible

Yes

### c:geo Version

2023.10.03-NB2-9acf5e6

**Comment by eddiemuc** [comment]
I checked in code.
* The strange error message is a harmless bug, I issued the wrong one (will provide a PR to fix)
* The underlying problem is that c:geo couldn't get a CRSF Token. @Lineflyer can you redo the action in debug mode and send me the logfile?

**Comment by Lineflyer** [comment]
@eddiemuc Log sent to your personal gmx.net

**Comment by Lineflyer** [comment]
@eddiemuc Feel free to play with this trackable if its helpful. The tracking code is in the log.

**Comment by eddiemuc** [comment]
In the log I can see that c:geo gets a HTTP500 when trying to GET the following page:

`https://www.geocaching.com/live/trackable/TBxyz/log`

(Replace `TBxyz` with real TB code)

That's the URL for the new log page. We need to fetch it for the card token. 

@Lineflyer can you try to open this URL in your browser, being logged in with the same GC user? It works for my (non migrated) normal GC user.

**Comment by Lineflyer** [comment]
@eddiemuc 
I tested it as requested.
For my not-migrated user my browser also returns a 500 for that page. Same for all TBxxx codes I tried.
For a migrated user the page works.

It seems not all new API pages are available for non-migrated users :(
What now?

**Comment by eddiemuc** [comment]
> @eddiemuc 
> I tested it as requested.
> For my not-migrated user my browser also returns a 500 for that page. Same for all TBxxx codes I tried.
> For a migrated user the page works.
> 
> It seems not all new API pages are available for non-migrated users :(
> What now?
> 

That's a bummer. But also strange because the page works for my non-migrated user.

I guess we have to build in a fork so the old way is used when the new one doesn't work.

**Comment by eddiemuc** [comment]
@Lineflyer another question: does the normal cache logging work for your non-migrated user? Including images, fav-point-adding and trackable/inventory-status?

**Comment by Lineflyer** [comment]
Just tested it:
Logged a cache inlcuding one TB visiting, one GK visiting, attaching a photo and providing a favorite point. 
It shows the "red note" on te logging screen and al was submitted/logged as expected.

So it looks fine for cache-logging for non-migrated users, the only problems seems to be the TB logging.

**Comment by Lineflyer** [comment]
Changed the issue title to reflect the remaining/real issue.

**Comment by Lineflyer** [comment]
Tried to log a TB as non-migrated PM user today and it fails to send the log.

Undortunately I am out of home, no log right now.

The common error message toast is shown about cgeo being unable to send the log.

Used 2023.10.16-NB....up to date

**Comment by Lineflyer** [comment]
Addition: Seems discovering works but taking out of cache doesn't....or its bound to some other speciality of that TB.

**Comment by eddiemuc** [comment]
- is the normal error message shown (not the one about an image)?
- does the same happen on the website (like before)?
- can you send a log file?

**Comment by Lineflyer** [comment]
This is a raw log from the emulator for that described problem.
Its a 403 error when trying to post the log....happens for log type "Retrieved". Discovering the very same trackable is working.

```
2023-10-18 21:26:15.295 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=6080.97ms min=11.06ms max=72067.45ms count=12
2023-10-18 21:26:15.346 20676-20676 Toolb...pper cgeo.geocaching  I  Progress display unsupported
2023-10-18 21:26:15.418 20676-20676 TextI...yout cgeo.geocaching  I  EditText added is not a TextInputEditText. Please switch to using that class instead.
2023-10-18 21:26:15.436 20676-20676 TextI...yout cgeo.geocaching  I  EditText added is not a TextInputEditText. Please switch to using that class instead.
2023-10-18 21:26:15.448 20676-20676 TextI...yout cgeo.geocaching  I  EditText added is not a TextInputEditText. Please switch to using that class instead.
2023-10-18 21:26:15.468 20676-20813 cgeo         cgeo.geocaching  D  [network--10] HTTP-GET: https://www.geocaching.com/track/details.aspx?tracker=TB3ZJRY {Network.request:363/Network.getRequest:506/GCLogin.getRequestLogged:546/GCParser.searchTrackable:1080/TravelBugConnector.searchTrackable:83/ConnectorFactory.lambda$loadTrackable$4:476/ConnectorFactory$$ExternalSyntheticLambda0.call:8/MaybeFromCallable.subscribeActual:47}
2023-10-18 21:26:15.470 20676-21397 cgeo         cgeo.geocaching  D  [OkHttp] HTTP-REQ:GET https://www.geocaching.com/track/details.aspx?tracker=TB3ZJRY, headers=[Accept-Charset:utf-8,iso-8859-1;q=0.8,utf-16;q=0.8,*;q=0.7;Accept-Language:en-US,*;q=0.9;User-Agent:Mozilla/5.0 (X11; Linux x86_64; rv:9.0.1) Gecko/20100101 Firefox/9.0.1 cgeo/2023.10.18-83bba6b developer build;X-Requested-With:XMLHttpRequest] {Network$LoggingInterceptor.intercept:404/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:392/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641}
2023-10-18 21:26:15.471 20676-21397 cgeo         cgeo.geocaching  D  [OkHttp] HTTP-COOKIES: SEND for https://www.geocaching.com/track/details.aspx?tracker=TB3ZJRY: ;gspkauth=_1tHGL-jbs#172#Cs1;jwt=eyJhbGciOi#931#0TM;Culture=de-DE;LogPageOptOut=true;__RequestVerificationToken=0HRUy496YT#92#Os1 {Cookies$InMemoryCookieJar.loadForRequest:77/BridgeInterceptor.intercept:74/RealInterceptorChain.proceed:109/RetryAndFollowUpInterceptor.intercept:76/RealInterceptorChain.proceed:109/Network$LoggingInterceptor.intercept:408/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:392}
2023-10-18 21:26:15.993 20676-20749 OpenG...erer cgeo.geocaching  D  endAllActiveAnimators on 0x7ac221ec7d30 (RippleDrawable) with handle 0x7ac131e019c0
2023-10-18 21:26:16.095 20676-21397 cgeo         cgeo.geocaching  D  [OkHttp] HTTP-COOKIES: SAVE for https://www.geocaching.com/track/details.aspx?tracker=TB3ZJRY: ;gspkauth=tGrD6zeYpt#172#s81;Culture=de-DE {Cookies$InMemoryCookieJar.saveFromResponse:38/HttpHeaders.receiveHeaders:207/BridgeInterceptor.intercept:85/RealInterceptorChain.proceed:109/RetryAndFollowUpInterceptor.intercept:76/RealInterceptorChain.proceed:109/Network$LoggingInterceptor.intercept:408/RealInterceptorChain.proceed:109}
2023-10-18 21:26:16.097 20676-21397 cgeo         cgeo.geocaching  D  [OkHttp] HTTP-RESP:200 (625 ms) GET https://www.geocaching.com/track/details.aspx?tracker=TB3ZJRY (http/1.1), headers=[Cache-Control:private;Content-Length:49268;Content-Type:text/html; charset=utf-8;Date:Wed, 18 Oct 2023 19:26:19 GMT;Request-Context:appId=cid-v1:019d82c2-5dd7-44cb-aa94-01e052f0d40c;Set-Cookie:Culture=de-DE; path=/; secure; HttpOnly;Strict-Transport-Security:max-age=31536000; includeSubDomains;X-Content-Type-Options:nosniff;X-Frame-Options:SAMEORIGIN;X-XSS-Protection:1] {Network$LoggingInterceptor.intercept:412/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:392/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641}
2023-10-18 21:26:16.304 20676-21405 cgeo         cgeo.geocaching  D  [ModernAsyncTask #1] HTTP-GET: https://www.geocaching.com/track/log.aspx?wid=44f546fd-ecf0-4aec-b738-52c419d6b815 {Network.request:363/Network.getRequest:506/TravelBugConnector.getTravelbugViewstates:67/TravelBugLoggingManager.loadInBackground:50/TravelBugLoggingManager.loadInBackground:29/AsyncTaskLoader.onLoadInBackground:307/AsyncTaskLoader$LoadTask.doInBackground:60/AsyncTaskLoader$LoadTask.doInBackground:48}
2023-10-18 21:26:16.306 20676-21397 cgeo         cgeo.geocaching  D  [OkHttp] HTTP-REQ:GET https://www.geocaching.com/track/log.aspx?wid=44f546fd-ecf0-4aec-b738-52c419d6b815, headers=[Accept-Charset:utf-8,iso-8859-1;q=0.8,utf-16;q=0.8,*;q=0.7;Accept-Language:en-US,*;q=0.9;User-Agent:Mozilla/5.0 (X11; Linux x86_64; rv:9.0.1) Gecko/20100101 Firefox/9.0.1 cgeo/2023.10.18-83bba6b developer build;X-Requested-With:XMLHttpRequest] {Network$LoggingInterceptor.intercept:404/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:392/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641}
2023-10-18 21:26:16.307 20676-21397 cgeo         cgeo.geocaching  D  [OkHttp] HTTP-COOKIES: SEND for https://www.geocaching.com/track/log.aspx?wid=44f546fd-ecf0-4aec-b738-52c419d6b815: ;gspkauth=tGrD6zeYpt#172#s81;jwt=eyJhbGciOi#931#0TM;Culture=de-DE;LogPageOptOut=true;__RequestVerificationToken=0HRUy496YT#92#Os1 {Cookies$InMemoryCookieJar.loadForRequest:77/BridgeInterceptor.intercept:74/RealInterceptorChain.proceed:109/RetryAndFollowUpInterceptor.intercept:76/RealInterceptorChain.proceed:109/Network$LoggingInterceptor.intercept:408/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:392}
2023-10-18 21:26:16.348 20676-20676 Assis...ture cgeo.geocaching  I  Flattened final assist data: 3008 bytes, containing 1 windows, 21 views
2023-10-18 21:26:16.367 20676-20676 Input...ager cgeo.geocaching  D  showSoftInput() view=androidx.appcompat.widget.AppCompatEditText{6e2aac9 VFED..CL. .F...... 0,0-1024,393 #7f090298 app:id/log aid=1073741825} flags=0 reason=SHOW_SOFT_INPUT
2023-10-18 21:26:16.449 20676-20676 Inset...ller cgeo.geocaching  D  show(ime(), fromIme=true)
2023-10-18 21:26:16.552 20676-21397 cgeo         cgeo.geocaching  D  [OkHttp] HTTP-COOKIES: SAVE for https://www.geocaching.com/track/log.aspx?wid=44f546fd-ecf0-4aec-b738-52c419d6b815: ;gspkauth=3SHslq5P-y#172#5E1;Culture=de-DE {Cookies$InMemoryCookieJar.saveFromResponse:38/HttpHeaders.receiveHeaders:207/BridgeInterceptor.intercept:85/RealInterceptorChain.proceed:109/RetryAndFollowUpInterceptor.intercept:76/RealInterceptorChain.proceed:109/Network$LoggingInterceptor.intercept:408/RealInterceptorChain.proceed:109}
2023-10-18 21:26:16.555 20676-21397 cgeo         cgeo.geocaching  D  [OkHttp] HTTP-RESP:200 (248 ms) GET https://www.geocaching.com/track/log.aspx?wid=44f546fd-ecf0-4aec-b738-52c419d6b815 (http/1.1), headers=[Cache-Control:no-cache;Content-Length:32037;Content-Type:text/html; charset=utf-8;Date:Wed, 18 Oct 2023 19:26:19 GMT;Expires:-1;Pragma:no-cache;Request-Context:appId=cid-v1:019d82c2-5dd7-44cb-aa94-01e052f0d40c;Set-Cookie:Culture=de-DE; path=/; secure; HttpOnly;Strict-Transport-Security:max-age=31536000; includeSubDomains;X-Content-Type-Options:nosniff;X-Frame-Options:SAMEORIGIN;X-XSS-Protection:1] {Network$LoggingInterceptor.intercept:412/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:392/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641}
2023-10-18 21:26:16.755 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=23.60ms min=3.24ms max=237.59ms count=51
2023-10-18 21:26:17.815 20676-20747 cgeo         cgeo.geocaching  D  [looper callbacks] LocationProvider: stopping location requests {GoogleLocationProvider.updateRequest:66/GoogleLocationProvider.lambda$get$0:101/GoogleLocationProvider$$ExternalSyntheticLambda1.run:4/HandlerScheduler$ScheduledRunnable.run:123/Handler.handleCallback:938/Handler.dispatchMessage:99/Looper.loopOnce:201/Looper.loop:288}
2023-10-18 21:26:17.827 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=59.49ms min=14.30ms max=460.40ms count=18
2023-10-18 21:26:18.828 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=499.99ms min=497.87ms max=502.11ms count=2
2023-10-18 21:26:19.847 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=509.53ms min=501.52ms max=517.54ms count=2
2023-10-18 21:26:21.346 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=499.47ms min=499.03ms max=500.33ms count=3
2023-10-18 21:26:22.849 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=500.60ms min=497.08ms max=504.25ms count=3
2023-10-18 21:26:23.861 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=84.27ms min=22.34ms max=151.34ms count=12
2023-10-18 21:26:24.897 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=86.25ms min=16.87ms max=197.05ms count=12
2023-10-18 21:26:26.298 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=107.68ms min=10.70ms max=503.38ms count=13
2023-10-18 21:26:27.207 20676-20676 cgeo         cgeo.geocaching  D  [main] LooperLogger: total:#2000/11847ms/avg 5ms {LooperLogger.process:78/LooperLogger.$r8$lambda$IQJlhstRB0ylWGjFWsOcbpEUIlc:0/LooperLogger$$ExternalSyntheticLambda0.println:2/Looper.loopOnce:236/Looper.loop:288/ActivityThread.main:7839/Method.invoke:-2/RuntimeInit$MethodAndArgsCaller.run:548}
2023-10-18 21:26:30.701 20676-20676 Inset...ller cgeo.geocaching  D  show(ime(), fromIme=true)
2023-10-18 21:26:31.663 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=125.09ms min=4.45ms max=499.60ms count=8
2023-10-18 21:26:32.666 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=55.50ms min=8.99ms max=496.43ms count=18
2023-10-18 21:26:33.679 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=506.38ms min=502.63ms max=510.12ms count=2
2023-10-18 21:26:34.680 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=499.95ms min=499.12ms max=500.79ms count=2
2023-10-18 21:26:35.651 20676-20803 cgeo         cgeo.geocaching  D  [AsyncTask #1] add tb: key=(1)HH9CYY, action=RETRIEVED_IT {LastTrackableAction.setAction:50/LastTrackableAction.setAction:54/TravelBugLoggingManager.postLog:72/LogTrackableTask.doInBackgroundInternal:33/LogTrackableTask.doInBackgroundInternal:14/AsyncTaskWithProgress.doInBackground:95/AsyncTask$3.call:394/FutureTask.run:266}
2023-10-18 21:26:35.656 20676-21397 cgeo         cgeo.geocaching  D  [OkHttp] HTTP-REQ:GET https://www.geocaching.com/live/trackable/TB3ZJRY/log, headers=[Accept-Charset:utf-8,iso-8859-1;q=0.8,utf-16;q=0.8,*;q=0.7;Accept-Language:en-US,*;q=0.9;Authorization:bearer eyJ#938#7cE;User-Agent:Mozilla/5.0 (X11; Linux x86_64; rv:9.0.1) Gecko/20100101 Firefox/9.0.1 cgeo/2023.10.18-83bba6b developer build;X-Requested-With:XMLHttpRequest] {Network$LoggingInterceptor.intercept:404/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:392/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641}
2023-10-18 21:26:35.658 20676-21397 cgeo         cgeo.geocaching  D  [OkHttp] HTTP-COOKIES: SEND for https://www.geocaching.com/live/trackable/TB3ZJRY/log: ;gspkauth=3SHslq5P-y#172#5E1;jwt=eyJhbGciOi#931#0TM;Culture=de-DE;LogPageOptOut=true;__RequestVerificationToken=0HRUy496YT#92#Os1 {Cookies$InMemoryCookieJar.loadForRequest:77/BridgeInterceptor.intercept:74/RealInterceptorChain.proceed:109/RetryAndFollowUpInterceptor.intercept:76/RealInterceptorChain.proceed:109/Network$LoggingInterceptor.intercept:408/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:392}
2023-10-18 21:26:35.693 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=168.83ms min=15.42ms max=499.51ms count=6
2023-10-18 21:26:36.407 20676-21397 cgeo         cgeo.geocaching  D  [OkHttp] HTTP-COOKIES: SAVE for https://www.geocaching.com/live/trackable/TB3ZJRY/log: ;_csrf=iyHFLlVfxbh7PV7hw8gcVngL {Cookies$InMemoryCookieJar.saveFromResponse:38/HttpHeaders.receiveHeaders:207/BridgeInterceptor.intercept:85/RealInterceptorChain.proceed:109/RetryAndFollowUpInterceptor.intercept:76/RealInterceptorChain.proceed:109/Network$LoggingInterceptor.intercept:408/RealInterceptorChain.proceed:109}
2023-10-18 21:26:36.409 20676-21397 cgeo         cgeo.geocaching  D  [OkHttp] HTTP-RESP:200 (753 ms) GET https://www.geocaching.com/live/trackable/TB3ZJRY/log (http/1.1), headers=[cache-control:private, no-cache, no-store, max-age=0, must-revalidate;Connection:keep-alive;Content-Length:177646;Content-Type:text/html; charset=utf-8;Date:Wed, 18 Oct 2023 19:26:40 GMT;etag:"139oktm3xuh3sqq";set-cookie:_csrf=iyHFLlVfxbh7PV7hw8gcVngL; Path=/;Vary:Accept-Encoding;x-powered-by:Next.js] {Network$LoggingInterceptor.intercept:412/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:392/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641}
2023-10-18 21:26:36.735 20676-20749 EGL_e...tion cgeo.geocaching  D  app_time_stats: avg=12.66ms min=7.02ms max=32.11ms count=62
2023-10-18 21:26:37.114 20676-20803 cgeo         cgeo.geocaching  D  [AsyncTask #1] HTTP-JSON: attempt to send: {"images":[],"logDate":"2023-10-18T19:26:15","logText":"Weiter gehts nach NRW.","trackingCode":"HH9CYY","logType":13} {HttpRequest.bodyJson:246/GCWebAPI.postLogTrackableNew:1531/TravelBugLoggingManager.postLog:75/LogTrackableTask.doInBackgroundInternal:33/LogTrackableTask.doInBackgroundInternal:14/AsyncTaskWithProgress.doInBackground:95/AsyncTask$3.call:394/FutureTask.run:266}
2023-10-18 21:26:37.116 20676-21397 cgeo         cgeo.geocaching  D  [OkHttp] HTTP-REQ:POST https://www.geocaching.com/api/live/v1/logs/TB3ZJRY/trackableLog, headers=[Accept:application/json, text/javascript, */*; q=0.01;Accept-Charset:utf-8,iso-8859-1;q=0.8,utf-16;q=0.8,*;q=0.7;Accept-Language:en-US,*;q=0.9;Authorization:bearer eyJ#938#7cE;CSRF-Token:NE2wj7SE-Yy0MRjCv31RHUBKVM3qLlKcxGbI;User-Agent:Mozilla/5.0 (X11; Linux x86_64; rv:9.0.1) Gecko/20100101 Firefox/9.0.1 cgeo/2023.10.18-83bba6b developer build;X-Requested-With:XMLHttpRequest] {Network$LoggingInterceptor.intercept:404/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:392/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641}
2023-10-18 21:26:37.117 20676-21397 cgeo         cgeo.geocaching  D  [OkHttp] HTTP-COOKIES: SEND for https://www.geocaching.com/api/live/v1/logs/TB3ZJRY/trackableLog: ;gspkauth=3SHslq5P-y#172#5E1;jwt=eyJhbGciOi#931#0TM;Culture=de-DE;LogPageOptOut=true;__RequestVerificationToken=0HRUy496YT#92#Os1;_csrf=iyHFLlVfxbh7PV7hw8gcVngL {Cookies$InMemoryCookieJar.loadForRequest:77/BridgeInterceptor.intercept:74/RealInterceptorChain.proceed:109/RetryAndFollowUpInterceptor.intercept:76/RealInterceptorChain.proceed:109/Network$LoggingInterceptor.intercept:408/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:392}
2023-10-18 21:26:37.463 20676-21397 cgeo         cgeo.geocaching  D  [OkHttp] HTTP-RESP:403 [Forbidden] (346 ms) POST https://www.geocaching.com/api/live/v1/logs/TB3ZJRY/trackableLog (http/1.1), headers=[Connection:keep-alive;Content-Length:196;Content-Type:application/json; charset=utf-8;Date:Wed, 18 Oct 2023 19:26:41 GMT;etag:"cfndzk9erw5g";Vary:Accept-Encoding] {Network$LoggingInterceptor.intercept:414/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:392/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641}
2023-10-18 21:26:37.478 20676-20803 cgeo         cgeo.geocaching  W  [AsyncTask #1] LOG ERROR:Problem pasting trackable log, response is: cgeo.geocaching.connector.gc.GCWebAPI$GCWebTrackableLogResponse, status=403, isSuccessful=false, response = Response{protocol=http/1.1, code=403, message=Forbidden, url=https://www.geocaching.com/api/live/v1/logs/TB3ZJRY/trackableLog}, body = {"message":"{\"statusCode\":403,\"statusMessage\":\"Forbidden\",\"errorMessage\":\"{\\\"Message\\\":\\\"Forbidden\\\"}\",\"uri\":\"https://web.groundspeak.biz/web/v1/logs/TB3ZJRY/trackableLog\"}"} {GCWebAPI.generateLogError:1543/GCWebAPI.postLogTrackableNew:1535/TravelBugLoggingManager.postLog:75/LogTrackableTask.doInBackgroundInternal:33/LogTrackableTask.doInBackgroundInternal:14/AsyncTaskWithProgress.doInBackground:95/AsyncTask$3.call:394/FutureTask.run:266}
2023-10-18 21:26:37.481 20676-20676 cgeo         cgeo.geocaching  D  [main] [cgeo.geocaching.log.LogTrackableActivity].showToast(It seems that your log was not posted. Please check it on the cache originating website.){1} {ActivityMixin.showCgeoToast:87/ActivityMixin.lambda$postShowToast$0:102/ActivityMixin$$ExternalSyntheticLambda0.run:6/Activity.runOnUiThread:7133/ActivityMixin.postShowToast:102/ActivityMixin.showToast:121/AbstractActivity.showToast:88/LogTrackableActivity.onPostExecuteInternal:458}
2023-10-18 21:26:37.482 20676-20676 Compa...rter cgeo.geocaching  D  Compat change id reported: 147798919; UID 10146; state: ENABLED
2023-10-18 21:26:37.516   783-783   ndroi...temu com....systemui  E  Failed to open APK '/data/app/~~2rBtURT-5HSmCK2DVv67xA==/cgeo.geocaching-8DO7GuEZcDBUtRVYobG0lA==/base.apk': I/O error
2023-10-18 21:26:37.534   783-783   ndroi...temu com....systemui  E  Failed to open APK '/data/app/~~2rBtURT-5HSmCK2DVv67xA==/cgeo.geocaching-8DO7GuEZcDBUtRVYobG0lA==/base.apk': I/O error
2023-10-18 21:26:37.534   783-783   Resou...ager com....systemui  E  failed to add asset path '/data/app/~~2rBtURT-5HSmCK2DVv67xA==/cgeo.geocaching-8DO7GuEZcDBUtRVYobG0lA==/base.apk'
                                                                     java.io.IOException: Failed to load asset path /data/app/~~2rBtURT-5HSmCK2DVv67xA==/cgeo.geocaching-8DO7GuEZcDBUtRVYobG0lA==/base.apk
                                                                     	at android.content.res.ApkAssets.nativeLoad(Native Method)
                                                                     	at android.content.res.ApkAssets.<init>(ApkAssets.java:295)
                                                                     	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:144)
                                                                     	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:454)
                                                                     	at android.app.ResourcesManager.access$000(ResourcesManager.java:72)
                                                                     	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:168)
                                                                     	at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:530)
                                                                     	at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:612)
                                                                     	at android.app.ResourcesManager.findOrCreateResourcesImplForKeyLocked(ResourcesManager.java:664)
                                                                     	at android.app.ResourcesManager.createResources(ResourcesManager.java:1011)
                                                                     	at android.app.ResourcesManager.getResources(ResourcesManager.java:1114)
                                                                     	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:2372)
                                                                     	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1751)
                                                                     	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1737)
                                                                     	at android.app.ApplicationPackageManager.getDrawable(ApplicationPackageManager.java:1506)
                                                                     	at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:3029)
                                                                     	at android.content.pm.PackageItemInfo.loadUnbadgedIcon(PackageItemInfo.java:290)
                                                                     	at com.android.systemui.toast.SystemUIToast.getBadgedIcon(SystemUIToast.java:284)
                                                                     	at com.android.systemui.toast.SystemUIToast.inflateToastView(SystemUIToast.java:198)
                                                                     	at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:90)
                                                                     	at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:77)
                                                                     	at com.android.systemui.toast.ToastFactory.createToast(ToastFactory.java:78)
                                                                     	at com.android.systemui.toast.ToastUI.lambda$showToast$0(ToastUI.java:113)
                                                                     	at com.android.systemui.toast.ToastUI.$r8$lambda$w_gPCh3F8Xxn1jN4lkQZoUci71c(Unknown Source:0)
                                                                     	at com.android.systemui.toast.ToastUI$$ExternalSyntheticLambda0.run(Unknown Source:16)
                                                                     	at com.android.systemui.toast.ToastUI.showToast(ToastUI.java:140)
                                                                     	at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:1431)
                                                                     	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                     	at android.os.Looper.loopOnce(Looper.java:201)
                                                                     	at android.os.Looper.loop(Looper.java:288)
                                                                     	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                     	at java.lang.reflect.Method.invoke(Native Method)
                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by Lineflyer** [comment]
On the website https://www.geocaching.com/live/trackable/TB3ZJRY/log I could successfully log a "Retrieved".

**Comment by eddiemuc** [comment]
I am currently on a trip w/o access to my computer. Will look at it on weekend. 

As far as we know, the http 403 might just happen for non-migrated users for the new log page under whatever circumstances w/o much we can do. However I don't currently understand why the fallback to "old" way doesn't seem to work in this case.

**Comment by Lineflyer** [comment]
> As far as we know, the http 403 might just happen for non-migrated users for the new log page under whatever circumstances

But it seems somehow related to what we do in c:geo as it worked with the new log page on the website itself.

**Comment by eddiemuc** [comment]
> > As far as we know, the http 403 might just happen for non-migrated users for the new log page under whatever circumstances
> 
> But it seems somehow related to what we do in c:geo as it worked with the new log page on the website itself.

Good point. Maybe I use the wrong log type code...

@Lineflyer can I do test logs on the mentioned trackable?

**Comment by Lineflyer** [comment]
@eddiemuc 
Its not mine, so better not.

I prepared a TB for you and placed it in a cache. Try to retrieve it:
TB-Code: TB54VJJ
Secret Code: NC52XJ (will remove it here shortly)

**Comment by eddiemuc** [comment]
@Lineflyer : I retrieved and dropped the TB, thanks for preparation. 

Case seems to be clear. Apparently for "Retrieve", gc.com requires us to send an additional field "geocacheReferenceCode". Here is the complete example json:

```
{
  "geocacheReferenceCode": "GC352Y3",
  "images": [],
  "logDate": "2023-10-19T21:11:26.639Z",
  "logText": "Test entry, will be deleted again",
  "logType": 13,
  "trackingCode": "xxx",
  "usedFavoritePoint": false
}
```

Can't tell for sure of course, but this is most likely the source of the problem here

**Comment by eddiemuc** [comment]
Hm it seems this is new and there was no need to provide a geocache code for a "retrieve" in the old API. This probably means we have to parse it from the log page. Found following entry in it's source code: 

`currentGeocache":{"id":2511222,"referenceCode":"GC352Y3","name":"Die alte Schule"}`

Hope I can provide a fix on the weekend

**Comment by eddiemuc** [comment]
@Lineflyer can I use the test trackable you provided for some more tests? (retrieving it, then dropping it again into the cache)

**Comment by Lineflyer** [comment]
Feel free to do whatever you want with it :) No need to delete logs afterwards.

**Comment by moving-bits** [comment]
> Secret Code: removed (will remove it here shortly)

@Lineflyer
Editing an entry will still have the old version in the history. Not sure it that's visible to all users, but I've deleted the old version anyway.

**Comment by eddiemuc** [comment]
> > Secret Code: removed (will remove it here shortly)
> 
> @Lineflyer Editing an entry will still have the old version in the history. Not sure it that's visible to all users, but I've deleted the old version anyway.

Did the same with the log file snippet pasted a few comments above. The log contained a trackable code, I replaced it with xxx and also deleted old history entry

**Comment by eddiemuc** [comment]
PR #14749 should fix the problem of logging trackable retrievals. 

@Lineflyer I created quite some test logs on both your cache and trackable when moving the tb forth and back. Please give me a hint if you want me to delete those

**Comment by Lineflyer** [comment]
@eddiemuc  
Just leave the logs as is. I might clean up later.

@moving-bits 
How shall we proceed. I suggest merging this fix to `release`, merge `release` back to `master`. Test it one day in nightly and then push a beta update. There are some beta users out there, which are also stuck with TB logging.

**Comment by moving-bits** [comment]
yes, let's test it in the nightly, then create a beta update tomorrow evening, if everything runs smooth
