### ISSUE TITLE
Crash when using "Set map language" on unified map

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#14802]
Crash when using "Set map language" on unified map while `combined` map is selected:

```
09:55:15.551  E  FATAL EXCEPTION: main
                 Process: cgeo.geocaching, PID: 6767
                 java.lang.NullPointerException: Attempt to invoke virtual method 'void org.oscim.tiling.source.mapfile.MapFileTileSource.setPreferredLanguage(java.lang.String)' on a null object reference
                 	at cgeo.geocaching.unifiedmap.tileproviders.AbstractMapsforgeOfflineTileProvider.setPreferredLanguage(AbstractMapsforgeOfflineTileProvider.java:55)
                 	at cgeo.geocaching.unifiedmap.mapsforgevtm.MapsforgeVtmFragment.setPreferredLanguage(MapsforgeVtmFragment.java:313)
                 	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.onOptionsItemSelected(UnifiedMapActivity.java:747)
                 	at android.app.Activity.onMenuItemSelected(Activity.java:4525)
                 	at androidx.activity.ComponentActivity.onMenuItemSelected(ComponentActivity.java:529)
                 	at androidx.fragment.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:352)
                 	at androidx.appcompat.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:269)
                 	at androidx.appcompat.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:110)
                 	at androidx.appcompat.app.AppCompatDelegateImpl.onMenuItemSelected(AppCompatDelegateImpl.java:1259)
                 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
                 	at androidx.appcompat.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:91)
                 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
                 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
                 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
                 	at android.widget.AdapterView.performItemClick(AdapterView.java:330)
                 	at android.widget.AbsListView.performItemClick(AbsListView.java:1265)
                 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3278)
                 	at android.widget.AbsListView$3.run(AbsListView.java:4244)
                 	at android.os.Handler.handleCallback(Handler.java:958)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:205)
                 	at android.os.Looper.loop(Looper.java:294)
                 	at android.app.ActivityThread.main(ActivityThread.java:8177)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by moving-bits** [comment]
Which maps are you using?
(Have not been able yet to reproduce. I'm using two installed offline maps, Berlin & Cap Verde, both directly from Mapsforge.)

**Comment by fm-sys** [comment]
I think I used New York OAM + some small African country for testing. But I can also reproduce with world base map + OAM.

[world.zip](https://github.com/cgeo/cgeo/files/13259423/world.zip)
