### ISSUE TITLE
[unified map] crash drawing a route with only 1 item

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14811]
### Describe your problem!

Drawing a route with only 1 item on unified map crashs reproducably.

To reproduce: Without an individual route add the first cache to route by long-clicking it or remove the second-last cache from an existing route.
Workaround: Add at least 2 caches on old map.

Logcat:

java.lang.IllegalArgumentException: Illegal item: GROUP[[POLYLINE!:1 pts [(N 52° 09.146' · E 005° 17.592',N 52° 09.146' · E 005° 17.592')],zLevel:12]]
	at cgeo.geocaching.unifiedmap.geoitemlayer.GeoItemLayer.put(GeoItemLayer.java:256)
	at cgeo.geocaching.unifiedmap.geoitemlayer.GeoItemLayer.put(GeoItemLayer.java:246)
	at cgeo.geocaching.unifiedmap.layers.IndividualRouteLayer.lambda$new$1(IndividualRouteLayer.java:49)
	at cgeo.geocaching.unifiedmap.layers.IndividualRouteLayer.$r8$lambda$sh4y-w3gx_JAdV5Iu7e1EeOHoT0(IndividualRouteLayer.java:0)
	at cgeo.geocaching.unifiedmap.layers.IndividualRouteLayer$$ExternalSyntheticLambda0.onChanged(R8$$SyntheticClass:0)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at cgeo.geocaching.utils.livedata.ConstantLiveData.notifyDataChanged(ConstantLiveData.java:21)
	at cgeo.geocaching.unifiedmap.UnifiedMapViewModel.lambda$toggleRouteItem$2(UnifiedMapViewModel.java:99)
	at cgeo.geocaching.unifiedmap.UnifiedMapViewModel.$r8$lambda$pHFTfmtU7c7otbaWKV0YmuOoE1M(UnifiedMapViewModel.java:0)
	at cgeo.geocaching.unifiedmap.UnifiedMapViewModel$$ExternalSyntheticLambda3.updateIndividualRoute(R8$$SyntheticClass:0)
	at cgeo.geocaching.models.IndividualRoute.updateRoute(IndividualRoute.java:94)
	at cgeo.geocaching.models.IndividualRoute.addOrToggleItem(IndividualRoute.java:73)
	at cgeo.geocaching.models.IndividualRoute.toggleItem(IndividualRoute.java:50)
	at cgeo.geocaching.models.IndividualRoute.toggleItem(IndividualRoute.java:46)
	at cgeo.geocaching.unifiedmap.UnifiedMapViewModel.toggleRouteItem(UnifiedMapViewModel.java:99)
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.handleTap(UnifiedMapActivity.java:934)
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.lambda$onTap$14(UnifiedMapActivity.java:911)
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.$r8$lambda$74E-ANBwNL5OjcDITid-NpIYe-4(UnifiedMapActivity.java:0)
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity$$ExternalSyntheticLambda5.onClick(R8$$SyntheticClass:0)
	at androidx.appcompat.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1068)

### How to reproduce?

long-click cache

### Reproducible

Yes

### c:geo Version

https://github.com/cgeo/cgeo/commit/5deb9c4abd219c6449d42c426381d5120f29a432

**Comment by eddiemuc** [comment]
That exception is thrown when one tries to add an invalid GeoItem to a GeoItemLayer. In this case, one tries to add a polyline with just one point.

Should the GeoItemLayer handle such cases differently? E.g. stay silent and simply don't draw anything?

Here is an overview on what is considered to be a valid GeoPrimitive:

![image](https://github.com/cgeo/cgeo/assets/6909759/57a2f70f-a9cb-43e1-90f4-f29e641b3513)

**Comment by ztNFny** [comment]
Imho no polyline should be returned from Individual route if there's only 1 item, that'd be the "proper" way to fix this.

But also crashing when an invalid item is added seems kinda bad, this should be logged as error and the illegal item not drawn, but crashing is kinda bad (though it probably helps a lot in development as otherwise it's hard to notice something went wrong - maybe show a Toast instead of throwing?)

**Comment by ztNFny** [comment]
I replaced the throw with a simple return, but that results in a broken polyline:
![image](https://github.com/cgeo/cgeo/assets/1258173/710bec17-ad2b-4950-9b71-6a39ba5e5dd2)

**Comment by eddiemuc** [comment]
PR #14812 will fix the problem by ignoring invalid GeoPrimitives in drawing (they won't be passed to the drawing map provider). That way if a GeoGroup is passed to the GeoItemLayer and this group contains both valid and invalid elements, the valid ones will still be drawn.
