### ISSUE TITLE
ANR parsing long note

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#14902]
### Describe your problem!

Opening a specific cache in CacheDetailsActivity c:geo runs into a ANR.

11-26 18:52:09.049  1647 18685 E ActivityManager: ANR in cgeo.geocaching (cgeo.geocaching/.CacheDetailActivity)
11-26 18:52:09.049  1647 18685 E ActivityManager: PID: 18168
11-26 18:52:09.049  1647 18685 E ActivityManager: Reason: Input dispatching timed out (e435d3d GCA65M3 (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=true))
11-26 18:52:09.049  1647 18685 E ActivityManager: Parent: cgeo.geocaching/.CacheDetailActivity
11-26 18:52:09.049  1647 18685 E ActivityManager: Frozen: false
11-26 18:52:09.049  1647 18685 E ActivityManager: Load: 0.0 / 0.0 / 0.0

A little further up in logcat I found references to  cgeo.geocaching.CacheDetailActivity.adjustPersonalNoteVarsOutOfSyncButton(CacheDetailActivity.java:2991), so my guess is this is caused by a very long personal note (see below for full excerpt from logcat)

I'm unable to reproduce this on a second device - but that device doesn't have the same note. By scrolling down very quickly I can see that the personal note stored in c:geo is not the latest available online but contains some additional older texts. Unfortunately I'm unable to copy that text before c:geo crashs.

**Any advice on how to extract the note text? I'm unable to debug this device as it's using official keys and is not rooted.**

### How to reproduce?

-

### Reproducible

Yes

### c:geo Version

2023.10.26

### System information

```text
11-26 18:52:03.931  1647  5502 I FocusResolver: updateFocusedWindow, be6e000 cgeo.geocaching/cgeo.geocaching.CacheDetailActivity on display 0, reason: setFocusedWindow, result:   FocusedWindows:
11-26 18:52:03.931  1647  5502 I FocusResolver:     displayId=0, name='be6e000 cgeo.geocaching/cgeo.geocaching.CacheDetailActivity'
11-26 18:52:03.932  1208  1208 D OplusMovieIdle: updateLayerStacks,mOmiSupport is not supoort
11-26 18:52:03.933  1647  5458 D TheiaManager: stackTrace found in args
11-26 18:52:03.933  1647  5458 D TheiaManager: KEY:logTypeVALUE:UITimeout
11-26 18:52:03.933  1647  5458 D TheiaManager: KEY:deadMomentVALUE:1701021123912
11-26 18:52:03.933  1647  5458 D TheiaManager: KEY:appNameVALUE:c:geo
11-26 18:52:03.934  1647  5458 D TheiaManager: KEY:packageVersionVALUE:2023.11.25-null-3fc3275
11-26 18:52:03.934  1647  5458 D TheiaManager: KEY:packageNameVALUE:cgeo.geocaching
11-26 18:52:03.934  1647 11259 D TheiaSocketClient: TheiaSend receive content : 4298113029:UITimeout:1701021123933
11-26 18:52:03.934  1647  5458 D TheiaManager: KEY:stackTraceVALUE:[UITimeout MainThread Info]
11-26 18:52:03.934  1647  5458 D TheiaManager: Message:{ when=-7s966ms what=0 target=cgeo.geocaching.CacheDetailActivity$LoadCacheHandler } 
11-26 18:52:03.934  1647  5458 D TheiaManager: Message start time:2023-11-26 18:51:56.081
11-26 18:52:03.934  1647  5458 D TheiaManager: Message end time:2023-11-26 18:52:03.910
11-26 18:52:03.934  1647  5458 D TheiaManager: Message cost time:7828 ms
11-26 18:52:03.934  1647  5458 D TheiaManager: 
11-26 18:52:03.934  1647  5458 D TheiaManager: Cpu cost time:6140 ms(between first got stack to message end)
11-26 18:52:03.934  1647  5458 D TheiaManager: Stack 1:
11-26 18:52:03.934  1647  5458 D TheiaManager: ----- pid 18168 at 2023-11-26 18:51:57.582 -----
11-26 18:52:03.934  1647  5458 D TheiaManager: Cmd line: cgeo.geocaching
11-26 18:52:03.934  1647  5458 D TheiaManager: "main" prio=5 tid=2 RUNNABLE sysTid=18168
11-26 18:52:03.934  1647  5458 D TheiaManager:   at java.lang.String.fastSubstring(Native Method)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at java.lang.String.substring(String.java:2439)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.utils.TextUtils.getTextAfterIndexUntil(TextUtils.java:361)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.utils.TextUtils.getTextAfterIndexUntil(TextUtils.java:319)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.models.CacheArtefactParser.parseSingleWaypoint(CacheArtefactParser.java:199)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.models.CacheArtefactParser.parseWaypointsWithSpecificCoords(CacheArtefactParser.java:159)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.models.CacheArtefactParser.parseWaypointsFromString(CacheArtefactParser.java:129)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.models.CacheArtefactParser.parse(CacheArtefactParser.java:105)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.models.Geocache.getVariableDifferencesFromUserNotes(Geocache.java:1850)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.CacheDetailActivity.adjustPersonalNoteVarsOutOfSyncButton(CacheDetailActivity.java:2991)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.CacheDetailActivity.access$3300(CacheDetailActivity.java:196)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.CacheDetailActivity$DescriptionViewCreator.setContent(CacheDetailActivity.java:1740)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.activity.TabbedViewPagerFragment.notifyDataSetChanged(TabbedViewPagerFragment.java:63)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.activity.TabbedViewPagerActivity.setOrderedPages(TabbedViewPagerActivity.java:125)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.CacheDetailActivity.notifyDataSetChanged(CacheDetailActivity.java:908)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.CacheDetailActivity$LoadCacheHandler.handleRegularMessage(CacheDetailActivity.java:860)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.utils.DisposableHandler.handleMessage(DisposableHandler.java:61)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at android.os.Handler.dispatchMessage(Handler.java:106)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at android.os.Looper.loopOnce(Looper.java:233)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at android.os.Looper.loop(Looper.java:344)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at android.app.ActivityThread.main(ActivityThread.java:8212)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at java.lang.reflect.Method.invoke(Native Method)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
11-26 18:52:03.934  1647  5458 D TheiaManager: 
11-26 18:52:03.934  1647  5458 D TheiaManager: Stack 2:
11-26 18:52:03.934  1647  5458 D TheiaManager: ----- pid 18168 at 2023-11-26 18:51:59.087 -----
11-26 18:52:03.934  1647  5458 D TheiaManager: Cmd line: cgeo.geocaching
11-26 18:52:03.934  1647  5458 D TheiaManager: "main" prio=5 tid=2 RUNNABLE sysTid=18168
11-26 18:52:03.934  1647  5458 D TheiaManager:   at com.android.icu.util.regex.MatcherNative.findNextImpl(Native Method)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at com.android.icu.util.regex.MatcherNative.findNext(MatcherNative.java:99)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at java.util.regex.Matcher.find(Matcher.java:549)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.utils.MatcherWrapper.find(MatcherWrapper.java:26)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.location.GeopointParser$UTMParser.parse(GeopointParser.java:447)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.location.GeopointParser.parseAll(GeopointParser.java:604)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.models.CacheArtefactParser.parseWaypointsWithCoords(CacheArtefactParser.java:141)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.models.CacheArtefactParser.parseWaypointsFromString(CacheArtefactParser.java:126)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.models.CacheArtefactParser.parse(CacheArtefactParser.java:105)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.models.Geocache.getVariableDifferencesFromUserNotes(Geocache.java:1850)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.CacheDetailActivity.adjustPersonalNoteVarsOutOfSyncButton(CacheDetailActivity.java:2991)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.CacheDetailActivity.access$3300(CacheDetailActivity.java:196)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.CacheDetailActivity$DescriptionViewCreator.setContent(CacheDetailActivity.java:1740)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.activity.TabbedViewPagerFragment.notifyDataSetChanged(TabbedViewPagerFragment.java:63)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.activity.TabbedViewPagerActivity.reinitializeViewPager(TabbedViewPagerActivity.java:241)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.CacheDetailActivity.notifyDataSetChanged(CacheDetailActivity.java:909)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.CacheDetailActivity$LoadCacheHandler.handleRegularMessage(CacheDetailActivity.java:860)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at cgeo.geocaching.utils.DisposableHandler.handleMessage(DisposableHandler.java:61)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at android.os.Handler.dispatchMessage(Handler.java:106)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at android.os.Looper.loopOnce(Looper.java:233)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at android.os.Looper.loop(Looper.java:344)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at android.app.ActivityThread.main(ActivityThread.java:8212)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at java.lang.reflect.Method.invoke(Native Method)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
11-26 18:52:03.934  1647  5458 D TheiaManager:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
11-26 18:52:03.934  1647  5458 D TheiaManager: 
11-26 18:52:03.934  1647  5458 D TheiaManager: KEY:fileIdVALUE:42206b9bb760e605cc84b012e62d411e
```

**Comment by eddiemuc** [comment]
You could make a backup of the database, then opening it with a sqlite-browser and extract the text from the cg_cache table.

The underlying root cause seems to be that the sync does happen on the main thread. In was not aware that it could take that long.

**Comment by moving-bits** [comment]
May be related to #15687.

@ztNFny 
With #15744 provided as quickfix for #15687, does the issue you described in the opening item still happen?

**Comment by ztNFny** [comment]
Unfortunately I don't have the long note causing this in the db anymore, so am unable to reproduce, this closing.
