### ISSUE TITLE
UnifiedMap: Crash when tapping on GeoJSON object

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#14944]
- open UnifiedMap
- load GeoJSON object
- tap on such an object on the map

=> crash

(happens for both Google Maps / OSM variants, and for both short- and long-tap)

**Comment by moving-bits** [comment]
The cause will very likely be the changes I'd done for long-tap menus for routes/tracks, I'll need to look into that.

Stack trace is:
```
java.lang.ClassCastException: cgeo.geocaching.location.GeoItemHolder cannot be cast to cgeo.geocaching.models.Route
at cgeo.geocaching.unifiedmap.UnifiedMapActivity.onTap(UnifiedMapActivity.java:911)
at cgeo.geocaching.unifiedmap.AbstractMapFragment.onTapCallback(AbstractMapFragment.java:173)
at cgeo.geocaching.unifiedmap.googlemaps.GoogleMapsFragment.access$100(GoogleMapsFragment.java:41)
at cgeo.geocaching.unifiedmap.googlemaps.GoogleMapsFragment$1.onSingleTapUp(GoogleMapsFragment.java:61)
at android.view.GestureDetector.onTouchEvent(GestureDetector.java:752)
at cgeo.geocaching.unifiedmap.googlemaps.GoogleMapsFragment$$ExternalSyntheticLambda1.call(Unknown Source:4)
at cgeo.geocaching.ui.TouchableWrapper.dispatchTouchEvent(TouchableWrapper.java:34)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3121)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2802)
[...]
```

**Comment by eddiemuc** [comment]
@moving-bits ok. Give me a ping when I should look into it

**Comment by moving-bits** [comment]
Thanks, but cause was indeed the conversion to a `Route` object, which is required for both elevation chart and context menu currently. (Although context menu could also be used for non-Route-based tracks, but that's a different issue.)
