### ISSUE TITLE
Crash on map source change

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#15023]
### Describe your problem!

While playing with unified map I experienced a crash after consecutive change of map source between offline and online maps.

### How to reproduce?

Not sure

### Actual result after these steps?

Crash

```
2023-12-15 00:22:31.115   549-549   Andro...time cgeo.geocaching  E  FATAL EXCEPTION: main
                                                                     Process: cgeo.geocaching, PID: 549
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'org.oscim.core.BoundingBox org.oscim.map.Map.getBoundingBox(int)' on a null object reference
                                                                     	at cgeo.geocaching.unifiedmap.mapsforgevtm.MapsforgeVtmFragment.getBoundingBox(MapsforgeVtmFragment.java:268)
                                                                     	at cgeo.geocaching.unifiedmap.AbstractMapFragment.getViewport(AbstractMapFragment.java:93)
                                                                     	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.updateCacheCountSubtitle(UnifiedMapActivity.java:411)
                                                                     	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.lambda$onCreate$4(UnifiedMapActivity.java:226)
                                                                     	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.$r8$lambda$ULMnr--LtXl8U8k9slg4fxPP5Fw(UnifiedMapActivity.java:0)
                                                                     	at cgeo.geocaching.unifiedmap.UnifiedMapActivity$$ExternalSyntheticLambda18.onChanged(R8$$SyntheticClass:0)
                                                                     	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
                                                                     	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
                                                                     	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
                                                                     	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
                                                                     	at android.os.Handler.handleCallback(Handler.java:942)
                                                                     	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                     	at android.os.Looper.loopOnce(Looper.java:226)
                                                                     	at android.os.Looper.loop(Looper.java:313)
                                                                     	at android.app.ActivityThread.main(ActivityThread.java:8762)
                                                                     	at java.lang.reflect.Method.invoke(Native Method)
                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
2023-12-15 00:22:31.115   549-549   cgeo         cgeo.geocaching  W  [main] UncaughtException
                                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'org.oscim.core.BoundingBox org.oscim.map.Map.getBoundingBox(int)' on a null object reference
                                                                     	at cgeo.geocaching.unifiedmap.mapsforgevtm.MapsforgeVtmFragment.getBoundingBox(MapsforgeVtmFragment.java:268)
                                                                     	at cgeo.geocaching.unifiedmap.AbstractMapFragment.getViewport(AbstractMapFragment.java:93)
                                                                     	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.updateCacheCountSubtitle(UnifiedMapActivity.java:411)
                                                                     	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.lambda$onCreate$4(UnifiedMapActivity.java:226)
                                                                     	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.$r8$lambda$ULMnr--LtXl8U8k9slg4fxPP5Fw(UnifiedMapActivity.java:0)
                                                                     	at cgeo.geocaching.unifiedmap.UnifiedMapActivity$$ExternalSyntheticLambda18.onChanged(R8$$SyntheticClass:0)
                                                                     	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
                                                                     	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
                                                                     	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
                                                                     	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
                                                                     	at android.os.Handler.handleCallback(Handler.java:942)
                                                                     	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                     	at android.os.Looper.loopOnce(Looper.java:226)
                                                                     	at android.os.Looper.loop(Looper.java:313)
                                                                     	at android.app.ActivityThread.main(ActivityThread.java:8762)
                                                                     	at java.lang.reflect.Method.invoke(Native Method)
                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

```

### Expected result after these steps?

normal operation

### Reproducible

No

### c:geo Version

2023.12.14-NB

**Comment by moving-bits** [comment]
Have not been able to reproduce yet, but from the error location and message it looks like `mMap` is not yet defined, so `getViewport()` gets called before `onViewCreated()` has been called. Maybe we need some `isMapRead()` flag and postpone calculating the subtitle until this flag is set?

**Comment by Lineflyer** [comment]
It could indeed be kind of a race condition as I changed map source multiple times before it appeared.

**Comment by moving-bits** [comment]
Much has changed meanwhile in UnifiedMap - does this error still happen or can we close this issue?

**Comment by Lineflyer** [comment]
Lets close and create a new one if needed. Not appeared yet since using unified map.
