### ISSUE TITLE
Map downloader crashes if companion file cannot be read

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15130]
While checking some things for #15129 I noticed that opening the map downloader makes c:geo crash, if a companion file in the map folder can be seen, but cannot be read. An error toast is shown, then c:geo gets terminated.

```
12-31 00:17:24.833 32084 32084 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.Reader.read(char[])' on a null object reference
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at java.util.Properties$LineReader.readLine(Properties.java:434)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at java.util.Properties.load0(Properties.java:349)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at java.util.Properties.load(Properties.java:337)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at cgeo.geocaching.downloader.CompanionFileUtils.availableOfflineMaps(CompanionFileUtils.java:104)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at cgeo.geocaching.downloader.CompanionFileUtils.availableOfflineMapRelatedFiles(CompanionFileUtils.java:77)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at cgeo.geocaching.downloader.DownloadSelectorActivity.changeSource(DownloadSelectorActivity.java:254)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at cgeo.geocaching.downloader.DownloadSelectorActivity.access$700(DownloadSelectorActivity.java:40)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at cgeo.geocaching.downloader.DownloadSelectorActivity$1.onItemSelected(DownloadSelectorActivity.java:211)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at android.widget.AdapterView.fireOnSelected(AdapterView.java:1398)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:1387)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at android.widget.AdapterView.-$$Nest$mdispatchOnItemSelected(Unknown Source:0)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:1345)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:958)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:230)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at android.os.Looper.loop(Looper.java:319)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8893)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
12-31 00:17:24.833 32084 32084 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
12-31 00:17:24.833 32084 32084 W cgeo : [main] UncaughtException
12-31 00:17:24.833 32084 32084 W cgeo : java.lang.NullPointerException: Attempt to invoke virtual method 'int java.io.Reader.read(char[])' on a null object reference
12-31 00:17:24.833 32084 32084 W cgeo : at java.util.Properties$LineReader.readLine(Properties.java:434)
12-31 00:17:24.833 32084 32084 W cgeo : at java.util.Properties.load0(Properties.java:349)
12-31 00:17:24.833 32084 32084 W cgeo : at java.util.Properties.load(Properties.java:337)
12-31 00:17:24.833 32084 32084 W cgeo : at cgeo.geocaching.downloader.CompanionFileUtils.availableOfflineMaps(CompanionFileUtils.java:104)
12-31 00:17:24.833 32084 32084 W cgeo : at cgeo.geocaching.downloader.CompanionFileUtils.availableOfflineMapRelatedFiles(CompanionFileUtils.java:77)
12-31 00:17:24.833 32084 32084 W cgeo : at cgeo.geocaching.downloader.DownloadSelectorActivity.changeSource(DownloadSelectorActivity.java:254)
12-31 00:17:24.833 32084 32084 W cgeo : at cgeo.geocaching.downloader.DownloadSelectorActivity.access$700(DownloadSelectorActivity.java:40)
12-31 00:17:24.833 32084 32084 W cgeo : at cgeo.geocaching.downloader.DownloadSelectorActivity$1.onItemSelected(DownloadSelectorActivity.java:211)
12-31 00:17:24.833 32084 32084 W cgeo : at android.widget.AdapterView.fireOnSelected(AdapterView.java:1398)
12-31 00:17:24.833 32084 32084 W cgeo : at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:1387)
12-31 00:17:24.833 32084 32084 W cgeo : at android.widget.AdapterView.-$$Nest$mdispatchOnItemSelected(Unknown Source:0)
12-31 00:17:24.833 32084 32084 W cgeo : at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:1345)
12-31 00:17:24.833 32084 32084 W cgeo : at android.os.Handler.handleCallback(Handler.java:958)
12-31 00:17:24.833 32084 32084 W cgeo : at android.os.Handler.dispatchMessage(Handler.java:99)
12-31 00:17:24.833 32084 32084 W cgeo : at android.os.Looper.loopOnce(Looper.java:230)
12-31 00:17:24.833 32084 32084 W cgeo : at android.os.Looper.loop(Looper.java:319)
12-31 00:17:24.833 32084 32084 W cgeo : at android.app.ActivityThread.main(ActivityThread.java:8893)
12-31 00:17:24.833 32084 32084 W cgeo : at java.lang.reflect.Method.invoke(Native Method)
12-31 00:17:24.833 32084 32084 W cgeo : at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
12-31 00:17:24.833 32084 32084 W cgeo : at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by moving-bits** [comment]
Fixed with #15132
