### ISSUE TITLE
NewMap constantly crashing since a couple of days

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15158]
User report on support: NewMap is constantly crashing since a couple of days, has been working before.

Logfile reports a repeated error like this:
```
01-02 16:03:58.381  3856  5018 E AndroidRuntime: FATAL EXCEPTION: LayerManager
01-02 16:03:58.381  3856  5018 E AndroidRuntime: Process: cgeo.geocaching, PID: 3856
01-02 16:03:58.381  3856  5018 E AndroidRuntime: java.lang.IllegalArgumentException: width and height must be > 0
01-02 16:03:58.381  3856  5018 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:1095)
01-02 16:03:58.381  3856  5018 E AndroidRuntime: 	at android.graphics.Bitmap.createBitmap(Bitmap.java:934)
01-02 16:03:58.381  3856  5018 E AndroidRuntime: 	at cgeo.geocaching.maps.mapsforge.v6.layers.PositionLayer.rotateArrow(PositionLayer.java:135)
01-02 16:03:58.381  3856  5018 E AndroidRuntime: 	at cgeo.geocaching.maps.mapsforge.v6.layers.PositionLayer.draw(PositionLayer.java:79)
01-02 16:03:58.381  3856  5018 E AndroidRuntime: 	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
01-02 16:03:58.381  3856  5018 E AndroidRuntime: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
```

(Due to this the user switched to Google Maps for now, but would prefer to be able to use offline maps.)

Ticket 698843

## System information

c:geo version: 2023.12.21

Device:
-------
- Device type: S96GT (ZN129T_EEA, DOOGEE)
- Available processors: 8
- Android version: 12
- Android build: S9TV68B7.DGE.DOOGEE_EEA.HB.FHD.AZY8AEPTYDVFY5VKPUCSZ.20230223.V3.03
- Screen resolution: 720x1370px (360x684dp)
- Pixel density: 2.0
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 23.48.16 (190400-590025996)
- Memory:  Available:3.5 GB, Total:7.5 GB, Threshold: 216.0 MB, low:false

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:101
- Set language: en_GB (system default)
- System date format: dd/MM/y
- Time zone: GMT
- Debug mode active: no
- Log Settings: debug=false, minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=8, throwOnError=false, transactionSizes=false
- Last manual backup: never
- Last auto backup: 31 Dec 2023, 10:54
- Routing mode: Walk
- Live map mode: true
- OSM multi-threading: false / threads: 1
- Map: Google: Map
  - Id: cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleMapSource
  - Atts: none
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: Status: Found=No, Owned=No ({"advanced":false,"inconclusive":false,"tree":{"type":"status","config":{"values":["owned_no","found_no"]}}})
- OFFLINE: None ({"advanced":false,"inconclusive":false})

Stored Filters (#0):

Services:
-------
- Geocaching sites enabled:
   - geocaching.com: Logged in (Login OK) / PREMIUM
   - Geocaching.com Adventure Lab
- Geocaching.com date format: dd/MM/yyyy
- Geocaching.com website language: en-US
- Last login error on geocaching.com: communication error (2024-01-03 12-54)
- Last successful login on geocaching.com: 2024-01-04 11-39
- Routing: external / BRouter installed: true
- Installed c:geo plugins:  none

Permissions
-------
- ACCESS_COARSE_LOCATION: granted
- ACCESS_FINE_LOCATION: granted
- READ_CONTACTS: DENIED
- READ_EXTERNAL_STORAGE: DENIED
- WRITE_EXTERNAL_STORAGE: DENIED
- POST_NOTIFICATIONS: granted

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (151.5 GB free) v3 internal isDir(8 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (151.5 GB free) v3 internal isDir(8 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (151.5 GB free) v3 external non-removable isDir(450 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (151.5 GB free) v3 internal isDir(0 entries)
- Map render theme path:
- Public Folders: #12
  - BASE: /Cgeo (User-Defined)[/Cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo, Av:true, files:>=10, dirs:>=9, totalFileSize:>=1.0 MB, free space: 151.5 GB, files on device: 15155200)
  - OFFLINE_MAPS: /Cgeo/maps (Default)[/Cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Fmaps, Av:true, files:2, dirs:2, totalFileSize:1.2 GB, free space: 151.5 GB, files on device: 15155200)
  - OFFLINE_MAP_THEMES: /Cgeo/maps/_themes (Default)[/Cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Fmaps%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 151.5 GB, files on device: 15155200)
  - OFFLINE_MAP_SHADING: /Cgeo/maps/_hgt (Default)[/Cgeo/maps/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/maps/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Fmaps%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 151.5 GB, files on device: 15155200)
  - LOGFILES: /Cgeo/logfiles (Default)[/Cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Flogfiles, Av:true, files:2, dirs:0, totalFileSize:946.3 KB, free space: 151.5 GB, files on device: 15155200)
  - GPX: /Cgeo/gpx (Default)[/Cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Fgpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 151.5 GB, files on device: 15155200)
  - BACKUP: /Cgeo/backup (Default)[/Cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Fbackup, Av:true, files:>=8, dirs:>=6, totalFileSize:>=43.8 MB, free space: 151.5 GB, files on device: 15155200)
  - FIELD_NOTES: /Cgeo/field-notes (Default)[/Cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 151.5 GB, files on device: 15155200)
  - SPOILER_IMAGES: /Cgeo/GeocachePhotos (Default)[/Cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 151.5 GB, files on device: 15155200)
  - ROUTING_BASE: /Cgeo/routing (Default)[/Cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Frouting, Av:true, files:8, dirs:1, totalFileSize:87.8 KB, free space: 151.5 GB, files on device: 15155200)
  - ROUTING_TILES: /Cgeo/routing/segments4 (Default)[/Cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3ACgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3ACgeo/document/primary%3ACgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 151.5 GB, files on device: 15155200)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 151.5 GB, files on device: -1)
- PersistedDocumentUris: #2
  - PROXIMITY_NOTIFICATION_FAR: null
  - PROXIMITY_NOTIFICATION_CLOSE: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary%3ACgeo (18 Oct 2023, 20:39):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v100, Size:15.6 MB) on system internal storage

--- End of system information ---

**Comment by moving-bits** [comment]
I've created a mitigation that checks for the rotation arrow's dimensions, to let the user continue using the map.

But that's just a mitigation, not a fix for the underlying issue.

This issue might be related to #14295.

**Comment by moving-bits** [comment]
Won't fix. Old map implementations are deprecated as of release 2025.07.17 and superseded by UnifiedMap.
