### ISSUE TITLE
Crash during log creation on  2024.01.05-NB-602a5e1

### ISSUE THREAD

**Issue by Lomanic** [cgeo/cgeo#15167]
### Describe your problem!

c:geo crashes when opening the log composition interface for a GC.com geocache, while loading remote data. That's a regression between   2024.01.04-NB-* and  2024.01.05-NB-602a5e1 (#15144,  #15156?)

### How to reproduce?

Create a log on a GC.com geocache

### Actual result after these steps?

c:geo crashes
```
type: crash
osVersion: google/redfin/redfin:14/UP1A.231105.001/2023123100:user/release-keys
package: cgeo.geocaching:30240105
process: cgeo.geocaching
processUptime: 6664 + 1273 ms
installer: com.looker.droidify

java.lang.NullPointerException: Attempt to read from field 'boolean cgeo.geocaching.log.LogTypeTrackable.allowedForInventory' on a null object reference in method 'cgeo.geocaching.log.LogTypeTrackable cgeo.geocaching.log.LogCacheActivity$InventoryLogAdapter.checkAndGetAction(java.lang.String, cgeo.geocaching.log.LogTypeTrackable)'
	at cgeo.geocaching.log.LogCacheActivity$InventoryLogAdapter.checkAndGetAction(LogCacheActivity.java:747)
	at cgeo.geocaching.log.LogCacheActivity$InventoryLogAdapter.fillViewHolder(LogCacheActivity.java:809)
	at cgeo.geocaching.log.LogCacheActivity$InventoryLogAdapter.getView(LogCacheActivity.java:800)
	at cgeo.geocaching.ui.ViewUtils.setListViewHeightBasedOnItems(ViewUtils.java:346)
	at cgeo.geocaching.log.LogCacheActivity$InventoryLogAdapter.handleChangedData(LogCacheActivity.java:777)
	at cgeo.geocaching.log.LogCacheActivity$InventoryLogAdapter.resortTrackables(LogCacheActivity.java:726)
	at cgeo.geocaching.log.LogCacheActivity$InventoryLogAdapter.setTrackables(LogCacheActivity.java:717)
	at cgeo.geocaching.log.LogCacheActivity.onLoadFinished(LogCacheActivity.java:607)
	at cgeo.geocaching.log.LogCacheActivity.onLoadFinished(LogCacheActivity.java:75)
	at androidx.loader.app.LoaderManagerImpl$LoaderObserver.onChanged(LoaderManagerImpl.java:250)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.setValue(LoaderManagerImpl.java:189)
	at androidx.loader.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManagerImpl.java:174)
	at androidx.loader.content.Loader.deliverResult(Loader.java:132)
	at androidx.loader.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:258)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:83)
	at androidx.loader.content.ModernAsyncTask.finish(ModernAsyncTask.java:490)
	at androidx.loader.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:507)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8225)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)

```

### Expected result after these steps?

c:geo does not crash

### Reproducible

Yes

### c:geo Version

2024.01.05-NB-602a5e1

### System information

```text
## System information

c:geo version: 2024.01.05-NB-602a5e1

Device:
-------
- Device type: Pixel 5 (redfin, google)
- Available processors: 8
- Android version: 14
- Android build: UP1A.231105.001.2023123100
- Screen resolution: 1080x2072px (393x753dp)
- Pixel density: 2.75
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: unavailable
- Memory:  Available:714.1 MB, Total:7.3 GB, Threshold: 216.0 MB, low:false

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:168
- Set language: en_CA (system default)
- System date format: y-MM-dd
- Time zone: GMT+01:00
- Debug mode active: no
- Log Settings: debug=false, minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=8, throwOnError=false, transactionSizes=false
- Last manual backup: Jul 6, 2023, 12:00
- Last auto backup: Jan 4, 00:54
- Routing mode: Walk
- Live map mode: true
- Use unified map: true
- OSM multi-threading: false / threads: 1
- Map: OpenStreetMap.org
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OsmMapSource
  - Atts: © OpenStreetMap DE, map data OpenStreetMap contributors
  - Theme: none

Filters:
-------
- Hide waypoints: -
- LIVE: None ({"advanced":false,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"type","config":{}},{"type":"difficulty_terrain","config":{"d":{},"t":{}}},{"type":"status","config":{}}]}})
- OFFLINE: None ({"advanced":false,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"type","config":{}},{"type":"difficulty_terrain","config":{"d":{},"t":{}}},{"type":"status","config":{}}]}})

Stored Filters (#0):

Services:
-------
- Geocaching sites enabled:
   - geocaching.com: Logged in (Login OK) / PREMIUM
   - Geocaching.com Adventure Lab
- Geocaching.com date format: yyyy-MM-dd
- Geocaching.com website language: en-US
- Last login error on geocaching.com: communication error (2023-12-18 22-54)
- Last successful login on geocaching.com: 2024-01-05 11-41
- Routing: external / BRouter installed: false
- Installed c:geo plugins:  none

Permissions
-------
- ACCESS_COARSE_LOCATION: granted
- ACCESS_FINE_LOCATION: granted
- READ_CONTACTS: DENIED
- WRITE_EXTERNAL_STORAGE: DENIED
- POST_NOTIFICATIONS: granted

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (80.9 GB free) v3 internal isDir(7 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (80.9 GB free) v3 internal isDir(7 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (80.9 GB free) v3 external non-removable isDir(766 entries)
- Internal theme sync (is turned off): /data/user/0/cgeo.geocaching/MapThemeData (80.9 GB free) v3 internal isDir(0 entries)
- Map render theme path: 
- Public Folders: #12
  - BASE: /cgeo (User-Defined)[/cgeo[DOCUMENT#0:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo, Av:true, files:>=0, dirs:>=9, totalFileSize:>=0 B, free space: 80.9 GB, files on device: 13511677)
  - OFFLINE_MAPS: /cgeo/maps (Default)[/cgeo/maps[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps, Av:true, files:0, dirs:2, totalFileSize:0 B, free space: 80.9 GB, files on device: 13511677)
  - OFFLINE_MAP_THEMES: /cgeo/maps/_themes (Default)[/cgeo/maps/_themes[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps/_themes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps%2F_themes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 80.9 GB, files on device: 13511677)
  - OFFLINE_MAP_SHADING: /cgeo/maps/_hgt (Default)[/cgeo/maps/_hgt[PERSISTABLE_FOLDER(OFFLINE_MAPS)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/maps/_hgt]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fmaps%2F_hgt, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 80.9 GB, files on device: 13511677)
  - LOGFILES: /cgeo/logfiles (Default)[/cgeo/logfiles[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/logfiles]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Flogfiles, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 80.9 GB, files on device: 13511677)
  - GPX: /cgeo/gpx (Default)[/cgeo/gpx[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/gpx]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fgpx, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 80.9 GB, files on device: 13511677)
  - BACKUP: /cgeo/backup (Default)[/cgeo/backup[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/backup]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Fbackup, Av:true, files:>=8, dirs:>=8, totalFileSize:>=76.1 MB, free space: 80.9 GB, files on device: 13511677)
  - FIELD_NOTES: /cgeo/field-notes (Default)[/cgeo/field-notes[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/field-notes]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Ffield-notes, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 80.9 GB, files on device: 13511677)
  - SPOILER_IMAGES: /cgeo/GeocachePhotos (Default)[/cgeo/GeocachePhotos[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/GeocachePhotos]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2FGeocachePhotos, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 80.9 GB, files on device: 13511677)
  - ROUTING_BASE: /cgeo/routing (Default)[/cgeo/routing[PERSISTABLE_FOLDER(BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting, Av:true, files:8, dirs:1, totalFileSize:82.1 KB, free space: 80.9 GB, files on device: 13511677)
  - ROUTING_TILES: /cgeo/routing/segments4 (Default)[/cgeo/routing/segments4[PERSISTABLE_FOLDER(ROUTING_BASE)#1:p-content://com.android.externalstorage.documents/tree/primary%3Acgeo::/routing/segments4]] (Uri: content://com.android.externalstorage.documents/tree/primary%3Acgeo/document/primary%3Acgeo%2Frouting%2Fsegments4, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 80.9 GB, files on device: 13511677)
  - TEST_FOLDER: [Legacy]/data/user/0/cgeo.geocaching/files/unittest (Default)[/data/user/0/cgeo.geocaching/files/unittest[FILE#1:p-file:///data/user/0/cgeo.geocaching/files::/unittest]] (Uri: file:///data/user/0/cgeo.geocaching/files/unittest, Av:true, files:0, dirs:0, totalFileSize:0 B, free space: 80.9 GB, files on device: -1)
- PersistedDocumentUris: #2
  - PROXIMITY_NOTIFICATION_FAR: null
  - PROXIMITY_NOTIFICATION_CLOSE: null
- Persisted Uri Permissions: #1
  - content://com.android.externalstorage.documents/tree/primary%3Acgeo (Nov 5, 2022, 20:04):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v103, Size:22.2 MB) on system internal storage

--- End of system information ---
```

### Additional Information

Possibly fixed by #15164 but it's light on details.

**Comment by eddiemuc** [comment]
Fixed with PR #15166
