### ISSUE TITLE
[Development] Toast icons not working / exceptions in log

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15180]
During development when using local builds in emulator, Toasts appear with an Android icon instead of the c:geo-icon:

![image](https://github.com/cgeo/cgeo/assets/6909759/1f24343e-4b8c-44f0-8194-d9d46a7afd3a)

Also I get the following related exceptions in the log:

```
2024-01-07 11:53:18.510 28293-28293 cgeo       cge...developer  I  [main] [cgeo.geocaching.log.LogCacheActivity].showToast(c:geo successfully saved the log.){1} {ActivityMixin.showCgeoToast:89/ActivityMixin.lambda$postShowToast$0:106/ActivityMixin$$ExternalSyntheticLambda0.run:6/Handler.handleCallback:938/Handler.dispatchMessage:99/Looper.loopOnce:201/Looper.loop:288/ActivityThread.main:7839}
2024-01-07 11:53:18.568   765-765   ziparchive com....systemui  W  Unable to open '/data/app/~~GOYP8Vo-DDi1T5UpDjt6hg==/cgeo.geocaching.developer-neTgXVRB1YoxFsWmq6KxBg==/base.apk': No such file or directory
2024-01-07 11:53:18.568   765-765   ndro...emu com....systemui  E  Failed to open APK '/data/app/~~GOYP8Vo-DDi1T5UpDjt6hg==/cgeo.geocaching.developer-neTgXVRB1YoxFsWmq6KxBg==/base.apk': I/O error
2024-01-07 11:53:18.569   765-765   Reso...ger com....systemui  W  failed to preload asset path '/data/app/~~GOYP8Vo-DDi1T5UpDjt6hg==/cgeo.geocaching.developer-neTgXVRB1YoxFsWmq6KxBg==/base.apk'
                                                                   java.io.IOException: Failed to load asset path /data/app/~~GOYP8Vo-DDi1T5UpDjt6hg==/cgeo.geocaching.developer-neTgXVRB1YoxFsWmq6KxBg==/base.apk
                                                                   	at android.content.res.ApkAssets.nativeLoad(Native Method)
                                                                   	at android.content.res.ApkAssets.<init>(ApkAssets.java:295)
                                                                   	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:144)
                                                                   	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:454)
                                                                   	at android.app.ResourcesManager.access$000(ResourcesManager.java:72)
                                                                   	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:168)
                                                                   	at android.app.ResourcesManager.createApkAssetsSupplierNotLocked(ResourcesManager.java:980)
                                                                   	at android.app.ResourcesManager.getResources(ResourcesManager.java:1101)
                                                                   	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:2372)
                                                                   	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1751)
                                                                   	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1737)
                                                                   	at android.app.ApplicationPackageManager.getDrawable(ApplicationPackageManager.java:1506)
                                                                   	at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:3029)
                                                                   	at android.content.pm.PackageItemInfo.loadUnbadgedIcon(PackageItemInfo.java:290)
                                                                   	at com.android.systemui.toast.SystemUIToast.getBadgedIcon(SystemUIToast.java:284)
                                                                   	at com.android.systemui.toast.SystemUIToast.inflateToastView(SystemUIToast.java:198)
                                                                   	at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:90)
                                                                   	at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:77)
                                                                   	at com.android.systemui.toast.ToastFactory.createToast(ToastFactory.java:78)
                                                                   	at com.android.systemui.toast.ToastUI.lambda$showToast$0(ToastUI.java:113)
                                                                   	at com.android.systemui.toast.ToastUI.$r8$lambda$w_gPCh3F8Xxn1jN4lkQZoUci71c(Unknown Source:0)
                                                                   	at com.android.systemui.toast.ToastUI$$ExternalSyntheticLambda0.run(Unknown Source:16)
                                                                   	at com.android.systemui.toast.ToastUI.showToast(ToastUI.java:140)
                                                                   	at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:1431)
                                                                   	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                   	at android.os.Looper.loopOnce(Looper.java:201)
                                                                   	at android.os.Looper.loop(Looper.java:288)
                                                                   	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                   	at java.lang.reflect.Method.invoke(Native Method)
                                                                   	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                   	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
2024-01-07 11:53:18.574   765-765   ziparchive com....systemui  W  Unable to open '/data/app/~~GOYP8Vo-DDi1T5UpDjt6hg==/cgeo.geocaching.developer-neTgXVRB1YoxFsWmq6KxBg==/base.apk': No such file or directory
2024-01-07 11:53:18.575   765-765   ndro...emu com....systemui  E  Failed to open APK '/data/app/~~GOYP8Vo-DDi1T5UpDjt6hg==/cgeo.geocaching.developer-neTgXVRB1YoxFsWmq6KxBg==/base.apk': I/O error
2024-01-07 11:53:18.575   765-765   Reso...ger com....systemui  E  failed to add asset path '/data/app/~~GOYP8Vo-DDi1T5UpDjt6hg==/cgeo.geocaching.developer-neTgXVRB1YoxFsWmq6KxBg==/base.apk'
                                                                   java.io.IOException: Failed to load asset path /data/app/~~GOYP8Vo-DDi1T5UpDjt6hg==/cgeo.geocaching.developer-neTgXVRB1YoxFsWmq6KxBg==/base.apk
                                                                   	at android.content.res.ApkAssets.nativeLoad(Native Method)
                                                                   	at android.content.res.ApkAssets.<init>(ApkAssets.java:295)
                                                                   	at android.content.res.ApkAssets.loadFromPath(ApkAssets.java:144)
                                                                   	at android.app.ResourcesManager.loadApkAssets(ResourcesManager.java:454)
                                                                   	at android.app.ResourcesManager.access$000(ResourcesManager.java:72)
                                                                   	at android.app.ResourcesManager$ApkAssetsSupplier.load(ResourcesManager.java:168)
                                                                   	at android.app.ResourcesManager.createAssetManager(ResourcesManager.java:530)
                                                                   	at android.app.ResourcesManager.createResourcesImpl(ResourcesManager.java:612)
                                                                   	at android.app.ResourcesManager.findOrCreateResourcesImplForKeyLocked(ResourcesManager.java:664)
                                                                   	at android.app.ResourcesManager.createResources(ResourcesManager.java:1011)
                                                                   	at android.app.ResourcesManager.getResources(ResourcesManager.java:1114)
                                                                   	at android.app.ActivityThread.getTopLevelResources(ActivityThread.java:2372)
                                                                   	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1751)
                                                                   	at android.app.ApplicationPackageManager.getResourcesForApplication(ApplicationPackageManager.java:1737)
                                                                   	at android.app.ApplicationPackageManager.getDrawable(ApplicationPackageManager.java:1506)
                                                                   	at android.app.ApplicationPackageManager.loadUnbadgedItemIcon(ApplicationPackageManager.java:3029)
                                                                   	at android.content.pm.PackageItemInfo.loadUnbadgedIcon(PackageItemInfo.java:290)
                                                                   	at com.android.systemui.toast.SystemUIToast.getBadgedIcon(SystemUIToast.java:284)
                                                                   	at com.android.systemui.toast.SystemUIToast.inflateToastView(SystemUIToast.java:198)
                                                                   	at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:90)
                                                                   	at com.android.systemui.toast.SystemUIToast.<init>(SystemUIToast.java:77)
                                                                   	at com.android.systemui.toast.ToastFactory.createToast(ToastFactory.java:78)
                                                                   	at com.android.systemui.toast.ToastUI.lambda$showToast$0(ToastUI.java:113)
                                                                   	at com.android.systemui.toast.ToastUI.$r8$lambda$w_gPCh3F8Xxn1jN4lkQZoUci71c(Unknown Source:0)
                                                                   	at com.android.systemui.toast.ToastUI$$ExternalSyntheticLambda0.run(Unknown Source:16)
                                                                   	at com.android.systemui.toast.ToastUI.showToast(ToastUI.java:140)
                                                                   	at com.android.systemui.statusbar.CommandQueue$H.handleMessage(CommandQueue.java:1431)
                                                                   	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                   	at android.os.Looper.loopOnce(Looper.java:201)
                                                                   	at android.os.Looper.loop(Looper.java:288)
                                                                   	at android.app.ActivityThread.main(ActivityThread.java:7839)
                                                                   	at java.lang.reflect.Method.invoke(Native Method)
                                                                   	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                                                                   	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Is anyone else experiencing this problem? Is this maybe a problem in my local dev setup?

Update: using emulated Pixel XL with API 31

**Comment by moving-bits** [comment]
Haven't had this yet. Starting with target API 31 it should show the app icon (see [Android docs](https://developer.android.com/guide/topics/ui/notifiers/toasts)), but there seem to be some quirks (see [SO article](https://stackoverflow.com/questions/69630124/how-to-configure-toast-icon-in-android-12)).

**Comment by eddiemuc** [comment]
Hm so it's probably a local sev environment quirk. Thanks for the feedback, I will close here
