### ISSUE TITLE
different app id - follow up errors

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#15302]
### Describe your problem!

I saw two follow up problems after using the special appID for debug builds.

First - the build task `copyDefaultPreferencesToAndroid` fails.
~~~
> Task :main:copyDefaultPreferencesToAndroid
cgeo.geocaching_preferences.xml: 1 file pushed, 0 skipped.
run-as:
 unknown package: cgeo.geocaching
~~~

Second - the test `cgeo.geocaching.ExampleInstrumentationTest.useAppContext()` fails
~~~
org.junit.ComparisonFailure: expected:<cgeo.geocaching[]> but was:<cgeo.geocaching[.developer]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at cgeo.geocaching.ExampleInstrumentationTest.useAppContext(ExampleInstrumentationTest.java:16)
~~~

### How to reproduce?

In AS run "All tests".

### Reproducible

Yes

### c:geo Version

2024.02.04 developer from master

**Comment by bekuno** [comment]
To easier fix the first error, the PR #15304 should be merges first.

**Comment by moving-bits** [comment]
> To easier fix the first error, the PR #15304 should be merges first.

FYI: That one's merged meanwhile.

**Comment by bekuno** [comment]
closing as fixed
