### ISSUE TITLE
Invalid drawable added to LayerDrawable! Drawable already belongs to another owner but does not expose a constant state.

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15359]
Found several times in a logfile on support:

```
02-19 19:59:04.599 25927 25927 W LayerDrawable: Invalid drawable added to LayerDrawable! Drawable already belongs to another owner but does not expose a constant state.
02-19 19:59:04.599 25927 25927 W LayerDrawable: java.lang.RuntimeException
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:1857)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1977)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable.createConstantState(LayerDrawable.java:174)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.graphics.drawable.LayerDrawable.mutate(LayerDrawable.java:1782)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.ImageView.applyImageTint(ImageView.java:739)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.ImageView.setImageTintList(ImageView.java:661)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.core.widget.ImageViewCompat$Api21Impl.setImageTintList(ImageViewCompat.java:125)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.core.widget.ImageViewCompat.setImageTintList(ImageViewCompat.java:53)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at cgeo.geocaching.ui.GeoItemSelectorUtils.setViewValues(GeoItemSelectorUtils.java:167)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at cgeo.geocaching.ui.GeoItemSelectorUtils.createGeocacheItemView(GeoItemSelectorUtils.java:57)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at cgeo.geocaching.ui.GeoItemSelectorUtils.createRouteItemView(GeoItemSelectorUtils.java:133)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at cgeo.geocaching.ui.GeoItemSelectorUtils.createRouteOrRouteItemView(GeoItemSelectorUtils.java:125)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.lambda$onTap$20(UnifiedMapActivity.java:998)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.$r8$lambda$cuxoGsOS33fkjXDMtNKCfFSr6Cw(UnifiedMapActivity.java:0)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at cgeo.geocaching.unifiedmap.UnifiedMapActivity$$ExternalSyntheticLambda11.call(R8$$SyntheticClass:0)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at cgeo.geocaching.ui.SimpleItemListView$ItemListViewHolder.applyItemView(SimpleItemListView.java:160)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at cgeo.geocaching.ui.SimpleItemListView$ItemListViewHolder.fillData(SimpleItemListView.java:129)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at cgeo.geocaching.ui.SimpleItemListView$ItemListAdapter.onBindViewHolder(SimpleItemListView.java:258)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at cgeo.geocaching.ui.SimpleItemListView$ItemListAdapter.onBindViewHolder(SimpleItemListView.java:170)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7747)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7847)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6646)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6917)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:4022)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.View.measure(View.java:27129)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.View.measure(View.java:27129)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.View.measure(View.java:27129)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.View.measure(View.java:27129)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.View.measure(View.java:27129)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.appcompat.widget.AlertDialogLayout.tryOnMeasure(AlertDialogLayout.java:134)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.appcompat.widget.AlertDialogLayout.onMeasure(AlertDialogLayout.java:64)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.View.measure(View.java:27129)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.View.measure(View.java:27129)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.View.measure(View.java:27129)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.View.measure(View.java:27129)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.View.measure(View.java:27129)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7980)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:197)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1278)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.View.measure(View.java:27129)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4528)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3193)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3525)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2911)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10458)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.Choreographer.doFrame(Choreographer.java:797)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.os.Handler.handleCallback(Handler.java:938)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.os.Handler.dispatchMessage(Handler.java:99)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.os.Looper.loopOnce(Looper.java:226)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.os.Looper.loop(Looper.java:313)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at android.app.ActivityThread.main(ActivityThread.java:8669)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at java.lang.reflect.Method.invoke(Native Method)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
02-19 19:59:04.599 25927 25927 W LayerDrawable: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

**Comment by eddiemuc** [comment]
Fixed with PR #15380

**Comment by bekuno** [comment]
Reopen because of https://github.com/cgeo/cgeo/pull/15380#issuecomment-1965129704

**Comment by eddiemuc** [comment]
> Reopen because of https://github.com/cgeo/cgeo/pull/15380#issuecomment-1965129704

The PR was fine. I assume there was a bug when merging release back to master

**Comment by moving-bits** [comment]
As written in the PR comment: I've fixed this on `master` meanwhile, `release` compiled fine for me - probably some merging artifact.

**Comment by bekuno** [comment]
You PR was parallel to my check of the Watchdog error.
The Watchdog is also green now after a manual rebuild.
