### ISSUE TITLE
Crash when mapping history Geocaches

### ISSUE THREAD

**Issue by rouroni1** [cgeo/cgeo#15389]
### Describe your problem!

When I try to map the list of geocaches in the history, c:geo hangs and crashes to history list.

### How to reproduce?

1. Click on history
2. Click map ícon on the top bar

The issue is with unified map active. If unified map os disabled, it works.

### Actual result after these steps?

Hangs and shows the options to wait ir end, and goes to home screen of c:geo

https://github.com/cgeo/cgeo/assets/27059385/499e85d8-c1d9-42d8-9028-0b1cb405309d

### Expected result after these steps?

The app don't Crash and map the geocaches

### Reproducible

Yes

### c:geo Version

2024.02.26 RC

### System information

```text
## System information

c:geo version: 2024.02.26-RC

Device:
-------
- Device type: 21121210G (ingres_eea, POCO)
- Available processors: 8
- Android version: 13
- Android build: TKQ1.220807.001 test-keys
- Screen resolution: 1080x2186px (392x794dp)
- Pixel density: 2.75
- System font scale: 1.0 / used scale: 1.0
- Sailfish OS detected: false
- Google Play services: enabled - 24.06.15 (190400-607434073)
- Memory:  Available:3,8 GB, Total:10,9 GB, Threshold: 216,0 MB, low:false

Sensor and location:
-------
- Low power mode: inactive
- Compass capabilities: yes
- Rotation vector sensor: present
- Orientation sensor: present
- Magnetometer & Accelerometer sensor: present
- Direction sensor used: rotation vector

Program settings:
-------
- Settings: v9, Count:183
- Set language: pt_PT (system default)
- System date format: dd/MM/yy
- Time zone: GMT+00:00
- Debug mode active: no
- Log Settings: debug=false, minLevel=WARN, minAddCallerInfo=NONE, addCallerInfoMaxDepth=8, throwOnError=false, transactionSizes=false
- Last manual backup: never
- Last auto backup: 23/02, 20:54
- Routing mode: Walk
- Live map mode: true
- Use unified map: true
- OSM multi-threading: false / threads: 1
- Map: Spain-Portugal (OAM) (Offline)
  - Id: cgeo.geocaching.maps.mapsforge.MapsforgeMapProvider$OfflineMapSource:primary:CGEO/maps/Spain-Portugal (OAM).map
  - Atts: VectorMaps:(c)Christian Kernbeis, GeneralMaps:(c)Michael Bechtold, Themes:(c)Tobias Kuehn, www.openandromaps.org 2012-2023
  - Theme: Elevate.zip:Elevate.xml

Filters:
-------
- Hide waypoints: original 
- LIVE: Estado: 3 itens ({"advanced":false,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"type","config":{}},{"type":"difficulty_terrain","config":{"d":{},"t":{}}},{"type":"status","config":{"values":["owned_no","found_no","has_offline_found_log_no"]}}]}})
- OFFLINE: Estado: 4 itens ({"advanced":true,"inconclusive":false,"tree":{"type":"AND","children":[{"type":"type","config":{}},{"type":"status","config":{"values":["owned_no","found_no","has_offline_log_no","has_offline_found_log_no"]}}]}})

Services:
-------
- Geocaching sites enabled:
   - geocaching.com: Logged in (Sessão iniciada) / PREMIUM
   - Geocaching.com Adventure Lab
- Geocaching.com date format: yyyy-MM-dd
- Geocaching.com website language: pt-PT
- Last login error on geocaching.com: communication error (2024-01-27 18-17)
- Last successful login on geocaching.com: 2024-02-27 21-17
- Routing: internal / BRouter installed: false

Permissions
-------
- ACCESS_COARSE_LOCATION: granted
- ACCESS_FINE_LOCATION: granted
- READ_CONTACTS: granted
- WRITE_EXTERNAL_STORAGE: DENIED
- POST_NOTIFICATIONS: granted

Paths
-------
- System internal c:geo dir: /data/user/0/cgeo.geocaching (159,0 GB free) v3 internal isDir(10 entries)
- Legacy User storage c:geo dir: /data/user/0/cgeo.geocaching (159,0 GB free) v3 internal isDir(10 entries)
- Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (159,0 GB free) v3 external non-removable isDir(6697 entries)
- Internal theme sync (is turned ON): /data/user/0/cgeo.geocaching/MapThemeData (159,0 GB free) v3 internal isDir(9 entries)
- Map render theme path: Elevate.zip:Elevate.xml
- Public Folders: #12
  - BASE: content://com.android.externalstorage.documents/tree/primary:CGEO/document/primary:CGEO (av:true, files:>=24, size:>=1,9 GB, free:>=159,0 GB)
  - OFFLINE_MAPS: content://com.android.externalstorage.documents/tree/primary:CGEO/maps/document/primary:CGEO/maps (av:true, files:>=10, size:>=1,8 GB, free:>=159,0 GB)
  - OFFLINE_MAP_THEMES: content://com.android.externalstorage.documents/tree/primary:CGEO/maps/_themes/document/primary:CGEO/maps/_themes (av:true, files:>=8, size:>=1,9 MB, free:>=159,0 GB)
  - OFFLINE_MAP_SHADING: content://com.android.externalstorage.documents/tree/primary:CGEO/maps/_hgt/document/primary:CGEO/maps/_hgt (av:true, files:>=0, size:>=0 B, free:>=159,0 GB)
  - LOGFILES: content://com.android.externalstorage.documents/tree/primary:CGEO/document/primary:CGEO/logfiles (av:true, files:>=2, size:>=119,4 KB, free:>=159,0 GB)
  - GPX: content://com.android.externalstorage.documents/tree/primary:CGEO/document/primary:CGEO/gpx (av:true, files:>=12, size:>=24,1 MB, free:>=159,0 GB)
  - BACKUP: content://com.android.externalstorage.documents/tree/primary:CGEO/document/primary:CGEO/backup (av:true, files:>=10, size:>=847,9 MB, free:>=159,0 GB)
  - FIELD_NOTES: content://com.android.externalstorage.documents/tree/primary:CGEO/document/primary:CGEO/field-notes (av:true, files:>=0, size:>=0 B, free:>=159,0 GB)
  - SPOILER_IMAGES: content://com.android.externalstorage.documents/tree/primary:CGEO/document/primary:CGEO/GeocachePhotos (av:true, files:>=0, size:>=0 B, free:>=159,0 GB)
  - ROUTING_BASE: content://com.android.externalstorage.documents/tree/primary:CGEO/document/primary:CGEO/routing (av:true, files:>=11, size:>=180,0 MB, free:>=159,0 GB)
  - ROUTING_TILES: content://com.android.externalstorage.documents/tree/primary:CGEO/document/primary:CGEO/routing/segments4 (av:true, files:>=3, size:>=179,9 MB, free:>=159,0 GB)
  - TEST_FOLDER: file:///data/user/0/cgeo.geocaching/files/unittest (av:true, files:>=0, size:>=0 B, free:>=159,0 GB)
- PersistedDocumentUris: #2
  - PROXIMITY_NOTIFICATION_FAR: null
  - PROXIMITY_NOTIFICATION_CLOSE: null
- Persisted Uri Permissions: #4
  - content://com.android.externalstorage.documents/tree/primary:CGEO/maps/_hgt (30/01/2023, 21:22):RW
  - content://com.android.externalstorage.documents/tree/primary:CGEO/maps (30/01/2023, 21:22):RW
  - content://com.android.externalstorage.documents/tree/primary:CGEO/maps/_themes (30/01/2023, 21:22):RW
  - content://com.android.externalstorage.documents/tree/primary:CGEO (12/01/2023, 21:47):RW
- Database: /data/user/0/cgeo.geocaching/databases/data (v103, Size:269,8 MB) on system internal storage

--- End of system information ---
```

**Comment by rouroni1** [comment]
A more complete video of the issue

https://github.com/cgeo/cgeo/assets/27059385/499e85d8-c1d9-42d8-9028-0b1cb405309d

**Comment by moving-bits** [comment]
@rouroni1:

Can you add a logfile after such a crash, please (or send it to our support address, if you prefer)?

Go to "about c:geo" => swipe to "system" and use the "create logfile" button at the bottom.

Thanks.

**Comment by moving-bits** [comment]
Thanks for providing the logs. It seems to boil down to `onResume` taking too long due to having to reload a large amount of caches. This should be put into the background.

```
03-01 12:52:17.815 11072 11072 W Activity: PerfMonitor: Slow Operation: Activity cgeo.geocaching/.unifiedmap.UnifiedMapActivity onStart took 2358ms
03-01 12:52:18.157 11072 11427 W MIUIScout App: Enter APP_SCOUT_WARNING State
03-01 12:52:18.158 11072 11427 W MIUIScout App:  (Current message: duration=2743ms seq=19862 late=2ms h=android.app.ActivityThread$H w=159)
03-01 12:52:18.159 11072 11777 W MIUIScout App: Event:APP_SCOUT_WARNING Thread:main backtrace:
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1068)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:673)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:590)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:62)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.database.sqlite.SQLiteQuery.<init>(SQLiteQuery.java:37)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:46)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1712)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.database.sqlite.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1651)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at cgeo.geocaching.storage.DataStore.loadCachesFromGeocodes(DataStore.java:3070)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at cgeo.geocaching.storage.DataStore.lambda$loadCaches$28(DataStore.java:2991)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at cgeo.geocaching.storage.DataStore.$r8$lambda$fP3XOtezZgFoBAu9KXvQ1xszkYY(DataStore.java:0)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at cgeo.geocaching.storage.DataStore$$ExternalSyntheticLambda61.get(R8$$SyntheticClass:0)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at cgeo.geocaching.storage.DataStore.withAccessLock(DataStore.java:958)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at cgeo.geocaching.storage.DataStore.loadCaches(DataStore.java:2967)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at cgeo.geocaching.storage.DataStore.loadCache(DataStore.java:2952)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at cgeo.geocaching.unifiedmap.UnifiedMapActivity.addSearchResultByGeocaches(UnifiedMapActivity.java:521)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at cgeo.geocaching.unifiedmap.UnifiedMapActivity.reloadCachesAndWaypoints(UnifiedMapActivity.java:423)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at cgeo.geocaching.unifiedmap.UnifiedMapActivity.onResume(UnifiedMapActivity.java:1178)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1532)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.app.Activity.performResume(Activity.java:8610)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4908)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4951)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2363)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.os.Handler.dispatchMessage(Handler.java:106)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.os.Looper.loopOnce(Looper.java:210)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.os.Looper.loop(Looper.java:299)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at android.app.ActivityThread.main(ActivityThread.java:8123)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at java.lang.reflect.Method.invoke(Native Method)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
03-01 12:52:18.159 11072 11777 W MIUIScout App:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
03-01 12:52:18.169 11072 11081 I cgeo.geocaching: Thread[6,tid=11081,WaitingInMainSignalCatcherLoop,Thread*=0xb400007bde248000,peer=0x12c03c20,"Signal Catcher"]: reacting to signal 3
03-01 12:52:18.169 11072 11081 I cgeo.geocaching: 
03-01 12:52:18.203 11072 11081 I cgeo.geocaching: Wrote stack traces to tombstoned
03-01 12:52:19.868 11072 11072 W Activity: PerfMonitor: Slow Operation: Activity cgeo.geocaching/.unifiedmap.UnifiedMapActivity onResume took 2053ms
```
