### ISSUE TITLE
crash applying a filter to a stored list on map

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#15440]
1. Open a list
2. Map the list
3. Apply a filter 

FATAL EXCEPTION: main
Process: cgeo.geocaching, PID: 7785
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:760)
	at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:782)
	at cgeo.geocaching.filters.core.GeocacheFilter.filterList(GeocacheFilter.java:182)
	at cgeo.geocaching.maps.MapUtils.filter(MapUtils.java:105)
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.refreshMapData(UnifiedMapActivity.java:921)
	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.refreshWithFilter(UnifiedMapActivity.java:913)
	at cgeo.geocaching.utils.FilterUtils$$ExternalSyntheticLambda3.accept(Unknown Source:4)
	at cgeo.geocaching.ui.dialog.SimpleDialog.lambda$selectSingle$4(SimpleDialog.java:472)
	at cgeo.geocaching.ui.dialog.SimpleDialog$$ExternalSyntheticLambda4.accept(Unknown Source:4)
	at cgeo.geocaching.ui.dialog.SimpleDialog.lambda$selectItems$7$cgeo-geocaching-ui-dialog-SimpleDialog(SimpleDialog.java:573)
	at cgeo.geocaching.ui.dialog.SimpleDialog$$ExternalSyntheticLambda8.call(Unknown Source:13)
	at cgeo.geocaching.ui.SimpleItemListModel.triggerChange(SimpleItemListModel.java:408)
	at cgeo.geocaching.ui.SimpleItemListModel.setSelectedItems(SimpleItemListModel.java:380)
	at cgeo.geocaching.ui.SimpleItemListView$ItemListAdapter.handleClick(SimpleItemListView.java:257)
	at cgeo.geocaching.ui.SimpleItemListView$ItemListAdapter.lambda$onBindViewHolder$2$cgeo-geocaching-ui-SimpleItemListView$ItemListAdapter(SimpleItemListView.java:268)
	at cgeo.geocaching.ui.SimpleItemListView$ItemListAdapter$$ExternalSyntheticLambda5.onClick(Unknown Source:4)

caused by the combination of #15432 and https://github.com/cgeo/cgeo/pull/15395

Build: master 2024-03-09

**Comment by ztNFny** [comment]
@eddiemuc @moving-bits I tried to find an easy fix for this but am giving up for today. Do you have the chance to take a look? I guess the "apply filter" would have to be async as well.

Otherwise I suggest rolling back https://github.com/cgeo/cgeo/pull/15432 (and thus reopening https://github.com/cgeo/cgeo/issues/15399) as a crash in master is worse than a broken feature.

**Comment by eddiemuc** [comment]
We could try to sync over cache list while filtering. Don't know what this would mean performance-wise, also there might be others modifying the cache list meanwhile

**Comment by eddiemuc** [comment]
PR #15443 rolls back #15432. There is most liekly no easy fix to this concurrent modification exception problem. Maybe a common background thread needs to be established for all cache list updates.

**Comment by ztNFny** [comment]
Using the filter dialog works because that calls UnifiedMapActivity:onResume() - maybe using the filter menu should just do the same?

**Comment by ztNFny** [comment]
https://github.com/cgeo/cgeo/pull/15444 just calls onResume() - and this seems to fix all issues. Maybe not the most elegant solution but it's exactly what using the filter dialog does, so it can't be bad.
