### ISSUE TITLE
NPE on opening map while sorting track names

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15567]
Reported by user on support:

Map crashes immediately on opening since update to release 2024.04.05

Logfile has the following error multiple times:
```
04-06 22:23:12.957  3753  3932 E AndroidRuntime: java.lang.NullPointerException
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at java.text.RuleBasedCollator.compare(RuleBasedCollator.java:365)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils.lambda$sortListLocaleAware$1(TextUtils.java:74)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils.$r8$lambda$j6mHIsc-4Pt3x2MIjzi6b8Or4Gk(TextUtils.java:0)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils$$ExternalSyntheticLambda5.compare(R8$$SyntheticClass:0)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at java.util.TimSort.sort(TimSort.java:220)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at java.util.Arrays.sort(Arrays.java:1498)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at java.util.ArrayList.sort(ArrayList.java:1470)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at java.util.Collections.sort(Collections.java:201)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils.sortListLocaleAware(TextUtils.java:74)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at cgeo.geocaching.storage.extension.Trackfiles.getTrackfiles(Trackfiles.java:113)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at cgeo.geocaching.maps.Tracks.lambda$getListOfTrackfilesInBackground$1(Tracks.java:61)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at cgeo.geocaching.maps.Tracks.$r8$lambda$azHt6QFMsKe3nK1gEHxvtvu8c6M(Tracks.java:0)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at cgeo.geocaching.maps.Tracks$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-06 22:23:12.957  3753  3932 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

@eddiemuc 
Probably related to #15513. Anything the user can do to mitigate that situation?

**Comment by eddiemuc** [comment]
Fixed with #15568 (handles null-entries in location aware sorts)

@moving-bits root cause is a track with a null displayname. I don't know how this can happen and thus not how the user might mitigate

**Comment by eddiemuc** [comment]
One idea: maybe it helps when the user (temporarily) moves his track files to another folder. Then c:geo won't find them and thus also not include the faulty one (with null display name) into the list to sort

**Comment by moving-bits** [comment]
Thanks for the quick fix. WRT to track display name being `null`: I thought about editing the display name and leaving it empty, but this won't be stored. No idea where `null` is coming from (except from some error).

**Comment by moving-bits** [comment]
> One idea: maybe it helps when the user (temporarily) moves his track files to another folder. Then c:geo won't find them and thus also not include the faulty one (with null display name) into the list to sort

Track files are copied to app-internal folder to be able to read them using file operations instead of SAF, therefore I fear they are not accessible for the user. Links to those files (as well as their display names) are stored in the database - can be edited, but that's only for the brave :-)

**Comment by moving-bits** [comment]
FYI: Fixed for the user by uninstalling and reinstalling c:geo (which removes the temporary copies)

**Comment by Lineflyer** [comment]
We have a seemingly similar report with 2024.04.18 (although the fix should be included there, shouldn't it?):

Support ticket 550373

```
04-20 11:49:53.220 12619 12643 E AndroidRuntime: java.lang.NullPointerException
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at java.text.RuleBasedCollator.compare(RuleBasedCollator.java:365)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils.lambda$sortListLocaleAware$1(TextUtils.java:74)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils.$r8$lambda$j6mHIsc-4Pt3x2MIjzi6b8Or4Gk(TextUtils.java:0)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils$$ExternalSyntheticLambda5.compare(R8$$SyntheticClass:0)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at cgeo.geocaching.utils.CommonUtils.lambda$getNullHandlingComparator$0(CommonUtils.java:113)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at cgeo.geocaching.utils.CommonUtils.$r8$lambda$VLTbOqYeHEAb3Ja6pv2ZEjHrqdU(CommonUtils.java:0)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at cgeo.geocaching.utils.CommonUtils$$ExternalSyntheticLambda0.compare(R8$$SyntheticClass:0)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at java.util.TimSort.sort(TimSort.java:220)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at java.util.Arrays.sort(Arrays.java:1498)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at java.util.ArrayList.sort(ArrayList.java:1470)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at java.util.Collections.sort(Collections.java:201)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils.sortListLocaleAware(TextUtils.java:74)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at cgeo.geocaching.storage.extension.Trackfiles.getTrackfiles(Trackfiles.java:113)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at cgeo.geocaching.maps.Tracks.lambda$getListOfTrackfilesInBackground$1(Tracks.java:61)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at cgeo.geocaching.maps.Tracks.$r8$lambda$azHt6QFMsKe3nK1gEHxvtvu8c6M(Tracks.java:0)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at cgeo.geocaching.maps.Tracks$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-20 11:49:53.220 12619 12643 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: FATAL EXCEPTION: RxComputationThreadPool-4
04-20 11:50:03.361 12708 12797 E AndroidRuntime: Process: cgeo.geocaching, PID: 12708
04-20 11:50:03.361 12708 12797 E AndroidRuntime: java.lang.NullPointerException
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at java.text.RuleBasedCollator.compare(RuleBasedCollator.java:365)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils.lambda$sortListLocaleAware$1(TextUtils.java:74)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils.$r8$lambda$j6mHIsc-4Pt3x2MIjzi6b8Or4Gk(TextUtils.java:0)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils$$ExternalSyntheticLambda5.compare(R8$$SyntheticClass:0)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at cgeo.geocaching.utils.CommonUtils.lambda$getNullHandlingComparator$0(CommonUtils.java:113)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at cgeo.geocaching.utils.CommonUtils.$r8$lambda$VLTbOqYeHEAb3Ja6pv2ZEjHrqdU(CommonUtils.java:0)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at cgeo.geocaching.utils.CommonUtils$$ExternalSyntheticLambda0.compare(R8$$SyntheticClass:0)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at java.util.TimSort.sort(TimSort.java:220)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at java.util.Arrays.sort(Arrays.java:1498)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at java.util.ArrayList.sort(ArrayList.java:1470)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at java.util.Collections.sort(Collections.java:201)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils.sortListLocaleAware(TextUtils.java:74)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at cgeo.geocaching.storage.extension.Trackfiles.getTrackfiles(Trackfiles.java:113)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at cgeo.geocaching.maps.Tracks.lambda$getListOfTrackfilesInBackground$1(Tracks.java:61)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at cgeo.geocaching.maps.Tracks.$r8$lambda$azHt6QFMsKe3nK1gEHxvtvu8c6M(Tracks.java:0)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at cgeo.geocaching.maps.Tracks$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-20 11:50:03.361 12708 12797 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: FATAL EXCEPTION: RxComputationThreadPool-7
04-20 11:50:31.076 12911 12955 E AndroidRuntime: Process: cgeo.geocaching, PID: 12911
04-20 11:50:31.076 12911 12955 E AndroidRuntime: java.lang.NullPointerException
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at java.text.RuleBasedCollator.compare(RuleBasedCollator.java:365)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils.lambda$sortListLocaleAware$1(TextUtils.java:74)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils.$r8$lambda$j6mHIsc-4Pt3x2MIjzi6b8Or4Gk(TextUtils.java:0)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils$$ExternalSyntheticLambda5.compare(R8$$SyntheticClass:0)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at cgeo.geocaching.utils.CommonUtils.lambda$getNullHandlingComparator$0(CommonUtils.java:113)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at cgeo.geocaching.utils.CommonUtils.$r8$lambda$VLTbOqYeHEAb3Ja6pv2ZEjHrqdU(CommonUtils.java:0)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at cgeo.geocaching.utils.CommonUtils$$ExternalSyntheticLambda0.compare(R8$$SyntheticClass:0)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at java.util.TimSort.sort(TimSort.java:220)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at java.util.Arrays.sort(Arrays.java:1498)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at java.util.ArrayList.sort(ArrayList.java:1470)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at java.util.Collections.sort(Collections.java:201)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils.sortListLocaleAware(TextUtils.java:74)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at cgeo.geocaching.storage.extension.Trackfiles.getTrackfiles(Trackfiles.java:113)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at cgeo.geocaching.maps.Tracks.lambda$getListOfTrackfilesInBackground$1(Tracks.java:61)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at cgeo.geocaching.maps.Tracks.$r8$lambda$azHt6QFMsKe3nK1gEHxvtvu8c6M(Tracks.java:0)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at cgeo.geocaching.maps.Tracks$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
04-20 11:50:31.076 12911 12955 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
```

**Comment by moving-bits** [comment]
This is issue #15609, reported with ticket 817077. Closing that one in favor of this here.

**Comment by moving-bits** [comment]
Got another report for this, ticket 766235, for release 2024.04.25

**Comment by bekuno** [comment]
Are tracks prepared in a similar way to maps? There is issue #15613 with 0 byte map files. Perhaps the problematic track files are also empty?

**Comment by fm-sys** [comment]
Should hopefully be fixed with 2024.06.02. Let's monitor our crash statistics...

**Comment by fm-sys** [comment]
@moving-bits could you check the crash statistics whether this issue can be closed?

**Comment by moving-bits** [comment]
seems to have been fixed, so let's close here
