### ISSUE TITLE
NPE on opening map

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#15609]
Ticket on support (817077): user is unable to open any map.

Logfiles shows the following error repeatedly:
```
04-15 07:03:29.540 26362 27612 E AndroidRuntime: java.lang.NullPointerException
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at java.text.RuleBasedCollator.compare(RuleBasedCollator.java:395)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils.lambda$sortListLocaleAware$1(TextUtils.java:74)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils.$r8$lambda$j6mHIsc-4Pt3x2MIjzi6b8Or4Gk(TextUtils.java:0)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils$$ExternalSyntheticLambda5.compare(R8$$SyntheticClass:0)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at cgeo.geocaching.utils.CommonUtils.lambda$getNullHandlingComparator$0(CommonUtils.java:113)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at cgeo.geocaching.utils.CommonUtils.$r8$lambda$VLTbOqYeHEAb3Ja6pv2ZEjHrqdU(CommonUtils.java:0)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at cgeo.geocaching.utils.CommonUtils$$ExternalSyntheticLambda0.compare(R8$$SyntheticClass:0)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at java.util.TimSort.sort(TimSort.java:220)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at java.util.Arrays.sort(Arrays.java:1344)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at java.util.ArrayList.sort(ArrayList.java:1738)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at java.util.Collections.sort(Collections.java:210)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at cgeo.geocaching.utils.TextUtils.sortListLocaleAware(TextUtils.java:74)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at cgeo.geocaching.storage.extension.Trackfiles.getTrackfiles(Trackfiles.java:113)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at cgeo.geocaching.maps.Tracks.lambda$getListOfTrackfilesInBackground$1(Tracks.java:61)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at cgeo.geocaching.maps.Tracks.$r8$lambda$azHt6QFMsKe3nK1gEHxvtvu8c6M(Tracks.java:0)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at cgeo.geocaching.maps.Tracks$$ExternalSyntheticLambda1.run(R8$$SyntheticClass:0)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
04-15 07:03:29.540 26362 27612 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
```

This is reported for 2024.04.13, a version which already includes the trackables display name fix (PR #15568).

**Comment by moving-bits** [comment]
Closing here in favor of https://github.com/cgeo/cgeo/issues/15567#issuecomment-2080034714
