### ISSUE TITLE
[Nightly] c:geo crashes on trying to refresh caches in the foreground (suspect missing permission for SDK 24) 

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#15834]
c:geo version: 2024.07.01-NB-0068930, Android version: 14
Support Tickets: #[524984](https://cgeosupport.droescher.eu/scp/tickets.php?id=8148), #328347

Taken from user on support: "I have a saved list, the select 3 dots, top right, manages caches, refresh all and system closes and caches are not refreshed. Like system craches. Normally cgeo starts and update of all caches in the list.. hope this helps"

from logfile I suspect we have to declare permission FOREGROUND_SERVICE_DATA_SYNC in manifest with SDK 34, see eg https://developer.android.com/about/versions/14/changes/fgs-types-required#data-sync

Exception from logfile:
```
07-01 21:39:56.968 27926 27926 E AndroidRuntime: FATAL EXCEPTION: main
07-01 21:39:56.968 27926 27926 E AndroidRuntime: Process: cgeo.geocaching, PID: 27926
07-01 21:39:56.968 27926 27926 E AndroidRuntime: java.lang.RuntimeException: Unable to create service cgeo.geocaching.service.CacheDownloaderService: java.lang.SecurityException: Starting FGS with type dataSync callerApp=ProcessRecord{ea1b3ea 27926:cgeo.geocaching/u0a463} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_DATA_SYNC] 
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5111)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:230)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:319)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8918)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: Caused by: java.lang.SecurityException: Starting FGS with type dataSync callerApp=ProcessRecord{ea1b3ea 27926:cgeo.geocaching/u0a463} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_DATA_SYNC] 
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3053)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:3036)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2978)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7220)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at android.app.Service.startForeground(Service.java:775)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at cgeo.geocaching.service.AbstractForegroundIntentService.onCreate(AbstractForegroundIntentService.java:45)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5098)
07-01 21:39:56.968 27926 27926 E AndroidRuntime: 	... 9 more
07-01 21:39:56.968 27926 27926 W cgeo    : [main] UncaughtException
07-01 21:39:56.968 27926 27926 W cgeo    : java.lang.RuntimeException: Unable to create service cgeo.geocaching.service.CacheDownloaderService: java.lang.SecurityException: Starting FGS with type dataSync callerApp=ProcessRecord{ea1b3ea 27926:cgeo.geocaching/u0a463} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_DATA_SYNC] 
07-01 21:39:56.968 27926 27926 W cgeo    : 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5111)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2506)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:106)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at android.os.Looper.loopOnce(Looper.java:230)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at android.os.Looper.loop(Looper.java:319)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:8918)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
07-01 21:39:56.968 27926 27926 W cgeo    : Caused by: java.lang.SecurityException: Starting FGS with type dataSync callerApp=ProcessRecord{ea1b3ea 27926:cgeo.geocaching/u0a463} targetSDK=34 requires permissions: all of the permissions allOf=true [android.permission.FOREGROUND_SERVICE_DATA_SYNC] 
07-01 21:39:56.968 27926 27926 W cgeo    : 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at android.os.Parcel.createException(Parcel.java:3053)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at android.os.Parcel.readException(Parcel.java:3036)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at android.os.Parcel.readException(Parcel.java:2978)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7220)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at android.app.Service.startForeground(Service.java:775)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at cgeo.geocaching.service.AbstractForegroundIntentService.onCreate(AbstractForegroundIntentService.java:45)
07-01 21:39:56.968 27926 27926 W cgeo    : 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5098)
07-01 21:39:56.968 27926 27926 W cgeo    : 	... 9 more
```

**Comment by eddiemuc** [comment]
Second support ticket reported same problem

**Comment by moving-bits** [comment]
We have declared those foreground service types in `AndroidManifest.xml` with #15174, but maybe that's been in the wrong place or incomplete? Or do we request permissions from users for it?

**Comment by eddiemuc** [comment]
> We have declared those foreground service types in `AndroidManifest.xml` with #15174, but maybe that's been in the wrong place or incomplete? Or do we request permissions from users for it?

I believe we have to request permission https://developer.android.com/reference/android/Manifest.permission#FOREGROUND_SERVICE_DATA_SYNC in addition.

**Comment by ztNFny** [comment]
I have the same issue now as well, it's a regression from last week.
Reproducable from:
- Cache Popup
- List -> Manage Caches
Not reproducable from
- Cache Details

**Comment by ztNFny** [comment]
PR #15836 fixes both crashs for me, validated on my A14 phone

**Comment by moving-bits** [comment]
Thanks @ztNFny for fixing this issue
