### ISSUE TITLE
geokrety related test errors

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#15965]
### Describe your problem!

On local tests I got now 3 GK releted errors.
Don't know, if these are only test problems or functional errors.

1) `GeokretyConnectorTest.testCanHandleTrackable`:
~~~
org.junit.ComparisonFailure: expected:<[fals]e> but was:<[tru]e>
at java.lang.reflect.Constructor.newInstance0(Native Method)
at cgeo.geocaching.connector.trackable.GeokretyConnectorTest.testCanHandleTrackable(GeokretyConnectorTest.java:34)
~~~

2) `TrackableTest.testTrackableUrl`:
~~~
org.junit.ComparisonFailure: expected:<"https://[www.geocaching.com//track/details.aspx?tracker=TB1234]"> but was:<"https://[geokrety.org/konkret.php?id=4660]">
at java.lang.reflect.Constructor.newInstance0(Native Method)
at cgeo.geocaching.models.TrackableTest.testTrackableUrl(TrackableTest.java:41)
~~~

3) ``WatchdogTest.testTrackableWebsites`:
~~~
java.lang.AssertionError: Failed to get response from trackable website geokrety.org proxy https://api.geokrety.org
at cgeo.watchdog.WatchdogTest.checkWebsite(WatchdogTest.java:105)
at cgeo.watchdog.WatchdogTest.testTrackableWebsites(WatchdogTest.java:115)
~~~

### How to reproduce?

Use AS 2024.1.1.1.
Select virtual device API34.
Run "All tests".

### Reproducible

Yes

### c:geo Version

current master

**Comment by moving-bits** [comment]
#15966 fixes the first two issues

**Comment by bekuno** [comment]
geokrety.org is up.

All issues are fixed, let's close.
