### ISSUE TITLE
Remove GcVote

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16024]
From a user on support:
Ticket #812495, c:geo problem report (2024.08.09-RC)

In settings I can pick GCVOTE to use. It has been "GCVote is currently broken and may never be fixed. Sorry."  for _at least_ the last 2 years. Maybe time to remove as an option? 

I put this up for discussion.

**Comment by SammysHP** [comment]
Duplicate of #7169, #11487, #12840, #13599.

**Comment by eddiemuc** [comment]
> Duplicate of #7169, #11487, #12840, #13599.

Those are all closed

**Comment by SammysHP** [comment]
Indeed, that's why I kept this one open.

**Comment by ztNFny** [comment]
but for those still logged in it continues working?

**Comment by moving-bits** [comment]
from today's dev meeting:
As the service seems to be no longer supported, but just "running 'as is'", we should think about removing it from c:geo completely.

@Lineflyer 
Can you do a survey on FB to check users' opinions about this?

**Comment by Lineflyer** [comment]
What answer options should such survey have?
Yes/No for removal only or also asking whether any successor (if available) is interesting for users (e.g. CacheVote)?

**Comment by ztNFny** [comment]
There is no working successor afaik - cachevote is dead. Gcvote continues to work for those registered though, so it'd be a loss for those currently using it. Maybe just hide the option for new installs?

**Comment by SammysHP** [comment]
> Maybe just hide the option for new installs?

People might reinstall c:geo. Just disable it by default (isn't that already done?).

**Comment by Lineflyer** [comment]
Update:
Since some month I keep having problems to send votes to GCVote as existing user.
Today I found time to check the logs....I guess something is broken now since  a longer time and not being repaired/maintained.

So, finally sadly time to remove it.

Sending votes:
```
2025-09-14 22:50:54.518 29214-757   cgeo         cgeo.geocaching  I  [OkHttp] HTTP-RESP: 403 [Forbidden] (93 ms) GET https://ssl.webpack.de/gcvote.com/setVote.php?userName=Lineflyer&password=***&cacheId=c526789e-38b2-436c-ac55-79b4bdc70164&waypoint=GC5KZ5C&voteUser=4.0&version=cgeo (http/1.1), headers=[Connection:keep-alive;Content-Type:text/html;Date:Sun, 14 Sep 2025 20:50:54 GMT;ETag:W/"6391baca-b33";Server:nginx;Transfer-Encoding:chunked] {Network$LoggingInterceptor.intercept:430/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:401/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1156/ThreadPoolExecutor$Worker.run:651}
2025-09-14 22:50:54.520 29214-29724 cgeo         cgeo.geocaching  E  [network--9] GCVote.setRating: could not post rating, answer was null {GCVote.setRating:182/GCConnector.postVote:149/LogUtils.postCacheRating:198/LogUtils.createLogTaskLogic:163/LogActivityHelper.$r8$lambda$-rzs7JfF91UQaoBwdkIR7yopGuA:51/LogActivityHelper$$ExternalSyntheticLambda2.call:0/WorkerTask.$r8$lambda$tLW4RUNBOpoY0-S5pep-d3hN5zg:228/WorkerTask$$ExternalSyntheticLambda9.subscribe:0}
```

Check registration / load votes:
```
2025-09-14 22:53:35.810 29214-4840  cgeo         cgeo.geocaching  I  [OkHttp] HTTP-RESP: 403 [Forbidden] (3141 ms) GET http://gcvote.com/getVotes.php?version=cgeo&userName=Lineflyer&password=*** (http/1.1), headers=[Connection:keep-alive;Content-Length:2867;Content-Type:text/html;Date:Sun, 14 Sep 2025 20:53:35 GMT;ETag:"6391baca-b33";Server:nginx] {Network$LoggingInterceptor.intercept:430/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:401/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1156/ThreadPoolExecutor$Worker.run:651}
2025-09-14 22:53:35.811 29214-29719 cgeo         cgeo.geocaching  W  [network--7] Cannot parse GCVote result {GCVoteLogin.login:76/AbstractLogin.login:98/GCVoteAuthorizationActivity.checkCredentials:27/AbstractCredentialsAuthorizationActivity.$r8$lambda$PGgy1PdwcjwVWlnU2D1Oz0GiH-Q:103/AbstractCredentialsAuthorizationActivity$$ExternalSyntheticLambda0.get:0/ObservableDefer.subscribeActual:33/Observable.subscribe:13263/ObservableObserveOn.subscribeActual:46}
                                                                     java.lang.IllegalArgumentException: is == null
                                                                     	at com.android.org.kxml2.io.KXmlParser.setInput(KXmlParser.java:1636)
                                                                     	at cgeo.geocaching.gcvote.GCVoteLogin.login(SourceFile:59)
                                                                     	at cgeo.geocaching.connector.AbstractLogin.login(SourceFile:98)
                                                                     	at cgeo.geocaching.settings.GCVoteAuthorizationActivity.checkCredentials(SourceFile:27)
                                                                     	at cgeo.geocaching.settings.AbstractCredentialsAuthorizationActivity.$r8$lambda$PGgy1PdwcjwVWlnU2D1Oz0GiH-Q(SourceFile:103)
                                                                     	at cgeo.geocaching.settings.AbstractCredentialsAuthorizationActivity$$ExternalSyntheticLambda0.get(SourceFile:0)
                                                                     	at io.reactivex.rxjava3.internal.operators.observable.ObservableDefer.subscribeActual(SourceFile:33)
                                                                     	at io.reactivex.rxjava3.core.Observable.subscribe(SourceFile:13263)
                                                                     	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn.subscribeActual(SourceFile:46)
                                                                     	at io.reactivex.rxjava3.core.Observable.subscribe(SourceFile:13263)
                                                                     	at io.reactivex.rxjava3.internal.operators.observable.ObservableTakeWhile.subscribeActual(SourceFile:32)
                                                                     	at io.reactivex.rxjava3.core.Observable.subscribe(SourceFile:13263)
                                                                     	at io.reactivex.rxjava3.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(SourceFile:96)
                                                                     	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(SourceFile:38)
                                                                     	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(SourceFile:25)
                                                                     	at java.util.concurrent.FutureTask.run(FutureTask.java:317)
                                                                     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1156)
                                                                     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:651)
                                                                     	at java.lang.Thread.run(Thread.java:1119)
```

**Comment by bekuno** [comment]
The gcvote.com start site is visible blank, the content behind has parking information.

So yes, time to remove.
