### ISSUE TITLE
NPE when trying to open navigation menu

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16048]
On support, we have a ticket from a user claiming that c:geo crashes when trying to open navigation.
[Ticket #878538](https://cgeosupport.droescher.eu/scp/tickets.php?id=8537)
c:geo version 2024.09.01

In the log file I found following exception which assumingly is the cause of that crash:

```
09-07 19:16:36.196  8588  8588 E MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setEnabled(boolean)' on a null object reference
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at cgeo.geocaching.CachePopupFragment.showNavigationMenu(CachePopupFragment.java:353)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at cgeo.geocaching.CacheMenuHandler.onMenuItemSelected(CacheMenuHandler.java:71)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at cgeo.geocaching.AbstractDialogFragment.onPopupOptionsItemSelected(AbstractDialogFragment.java:194)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at cgeo.geocaching.CachePopupFragment.onPopupOptionsItemSelected(CachePopupFragment.java:201)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at cgeo.geocaching.CachePopupFragment$$ExternalSyntheticLambda4.onMenuItemClick(R8$$SyntheticClass:0)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:225)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:836)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:159)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:987)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at android.widget.AdapterView.performItemClick(AdapterView.java:376)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at android.widget.AbsListView.performItemClick(AbsListView.java:1287)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3563)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at android.widget.AbsListView.onTouchUp(AbsListView.java:4733)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at android.widget.AbsListView.onTouchEvent(AbsListView.java:4448)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at android.widget.ListView.onTouchEvent(ListView.java:1709)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at androidx.appcompat.widget.DropDownListView.onTouchEvent(DropDownListView.java:236)
09-07 19:16:36.204  8588  8588 E MessageQueue-JNI: 	at androidx.appcompat.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:140)

```

**Comment by eddiemuc** [comment]
NPE-line was added only recently with 93fc62f1cfff26b88c67e6ccedea1386c53635c0

**Comment by eddiemuc** [comment]
@moving-bits could you take a look at this. I don't understand how the commit was supposed to work

**Comment by moving-bits** [comment]
Scenario is reproducible for me when navigation icon (the "square with the arrow in it") is visible in overflow menu only. See #16049 for a fix.
