### ISSUE TITLE
Wherigo: NPE in cartridge

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16164]
For the sake of testing I tried a different cartridge in the emulator: GC3XXBF ("Die Hard im Ruhrpott"). 

I started it, then moved current location a few hundred meters away from "the bomb", got the message "too far", moved back a bit, and then c:geo displayed "you have hit a bug", but seemingly continued to work. Actually it had lost its inventory, though (which makes continuing this specific cartridge impossible).

Here's the logcat:
```
10-05 00:03:02.663 10957 10957 I cgeo    : [main] WORKERTASK{wherigo-download}:post FINISHED{wherigo-download}
10-05 00:03:35.847 10957 10957 W cgeo    : [main] WHERIGOGAME: Creating engine...
10-05 00:03:35.860 10957 11831 W cgeo    : [Thread-25] WHERIGOGAME: Creating state...
10-05 00:03:35.865 10957 11831 W cgeo    : [Thread-25] WHERIGOGAME: Building javafunc map...
10-05 00:03:35.865 10957 11831 W cgeo    : [Thread-25] WHERIGOGAME: Loading stdlib...
10-05 00:03:35.874 10957 11831 W cgeo    : [Thread-25] WHERIGOGAME: calling...
10-05 00:03:35.874 10957 11831 W cgeo    : [Thread-25] WHERIGOGAME: Registering WIG libs...
10-05 00:03:35.876 10957 11831 W cgeo    : [Thread-25] WHERIGOGAME: Building event queue...
10-05 00:03:35.876 10957 11831 W cgeo    : [Thread-25] WHERIGOGAME: Loading gwc...
10-05 00:03:35.876 10957 11831 W cgeo    : [Thread-25] WHERIGOGAME: pre-setting properties...
10-05 00:03:35.876 10957 11831 W cgeo    : [Thread-25] WHERIGOGAME: loading code...
10-05 00:03:35.877 10957 11831 W cgeo    : [Thread-25] WHERIGOGAME: parsing...
10-05 00:03:35.890 10957 11831 W cgeo    : [Thread-25] WHERIGOGAME: calling...
10-05 00:03:35.998 10957 11831 W cgeo    : [Thread-25] WHERIGOGAME: Starting game...
10-05 00:03:35.998 10957 11831 I cgeo    : [Thread-25] WHERIGOGAME: pos: null
10-05 00:03:35.999 10957 11831 W cgeo    : [Thread-25] STOPPED: geoData:null, dir:0.0, fixedLocation: null
10-05 00:03:36.001 10957 11831 W cgeo    : [Thread-25] STARTED: geoData:Location[fused 51.481843,7.216235 hAcc=5.0 et=+59m40s880ms alt=0.0 vAcc=0.5 vel=0.0 sAcc=0.5], dir:-0.016694268, fixedLocation: null
10-05 00:03:36.025 10957 11831 I cgeo    : [Thread-25] WHERIGOGAME: pushInput:translate / Uebersetzen / traduire
10-05 00:03:36.091 10957 10957 I cgeo    : [main] WherigoGameService STARTED
10-05 00:03:36.095 10957 10957 I cgeo    : [main] WherigoGameService STARTCOMMAND
10-05 00:03:42.505 10957 11833 I cgeo    : [Thread-26] WHERIGOGAME: pushDialog:[Hallo movingbits McClane, Ich hasse Dich weil du meinen lieben Bruder ermordet hast und ich hoffe Du wirst jetzt sterben. AHAHAH!!! :p]
10-05 00:03:54.397 10957 11833 I cgeo    : [Thread-26] WHERIGOGAME: pushDialog:[Du wirst eine Zone sehen mit zwei Kanistern und einer Bombe. Du kannst die Bombe entschaerfen, wenn du exakt 4 Liter Wasser in den Tank fuellst. Du bekommst einen Fuenf-Liter-Kanister und einen Drei-Liter-Kanister. Du findest in einiger Entfernung eine Quelle. Ich hoffe Du bist umweltbewusst.... AHAHAH na, spreche ich in Raetseln! :p]
10-05 00:04:33.158 10957 10957 E cgeo    : [main] Launching UnifiedMap in viewport mode, viewport=Viewport[N 51° 28.911' · E 007° 12.966',N 51° 28.921' · E 007° 12.982'])
10-05 00:04:33.261 10957 11865 W cgeo    : [RxCachedThreadScheduler-7] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching.developer/trackfiles/track-2024-10-04-23-53-48-2.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.1: could not parse XML
10-05 00:04:33.262 10957 11865 W cgeo    : [RxCachedThreadScheduler-7] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching.developer/trackfiles/track-2024-10-04-23-53-48-2.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.0: could not parse XML
10-05 00:04:33.263 10957 11865 W cgeo    : [RxCachedThreadScheduler-7] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching.developer/trackfiles/track-2024-10-04-23-53-48-2.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.1: could not parse XML (At line 1, column 0: not well-formed (invalid token))
10-05 00:04:33.264 10957 11865 W cgeo    : [RxCachedThreadScheduler-7] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching.developer/trackfiles/track-2024-10-04-23-53-48-2.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.0: could not parse XML (At line 1, column 0: not well-formed (invalid token))
10-05 00:04:33.264 10957 11865 W cgeo    : [RxCachedThreadScheduler-7] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching.developer/trackfiles/track-2024-10-04-23-53-48-2.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.0: could not parse XML
10-05 00:04:33.549 10957 10957 I cgeo    : [main] AsyncMapWrapper: Init Layer
10-05 00:04:33.549 10957 10957 I cgeo    : [main] AsyncMapWrapper: Init Layer
10-05 00:04:33.583 10957 10957 I cgeo    : [main] GeoItemLayer:clickableItems(MapsforgeV6GeoItemLayer):BATCH-END - ADDS:402(402), REMOVES:0(0), REPLACES:0(0)
10-05 00:04:33.748 10957 10957 I cgeo    : [main] GeoItemLayer:nonClickableItems(MapsforgeV6GeoItemLayer):BATCH-END - ADDS:2(2), REMOVES:0(0), REPLACES:0(0)
10-05 00:04:40.072 10957 10957 I cgeo    : [main] GeoItemLayer:clickableItems(MapsforgeV6GeoItemLayer):BATCH-END - ADDS:0(402), REMOVES:401(401), REPLACES:0(0)
10-05 00:05:08.631 10957 10957 I cgeo    : [main] Destroy Layer
10-05 00:05:08.632 10957 10957 I cgeo    : [main] Destroy Layer
10-05 00:05:28.250 10957 11833 I cgeo    : [Thread-26] WHERIGOGAME: pushDialog:[there are 0 liters inside your can.
10-05 00:05:28.250 10957 11833 I cgeo    : Es sind 0 Liter in dem Kanister
10-05 00:05:28.250 10957 11833 I cgeo    : Il y a 0 Litres dans ce bidon.]
10-05 00:06:39.542 10957 10957 E cgeo    : [main] Launching UnifiedMap in viewport mode, viewport=Viewport[N 51° 28.911' · E 007° 12.966',N 51° 28.921' · E 007° 12.982'])
10-05 00:06:39.680 10957 11949 W cgeo    : [RxCachedThreadScheduler-10] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching.developer/trackfiles/track-2024-10-04-23-53-48-2.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.1: could not parse XML
10-05 00:06:39.681 10957 11949 W cgeo    : [RxCachedThreadScheduler-10] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching.developer/trackfiles/track-2024-10-04-23-53-48-2.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.0: could not parse XML
10-05 00:06:39.682 10957 11949 W cgeo    : [RxCachedThreadScheduler-10] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching.developer/trackfiles/track-2024-10-04-23-53-48-2.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.1: could not parse XML (At line 1, column 0: not well-formed (invalid token))
10-05 00:06:39.682 10957 11949 W cgeo    : [RxCachedThreadScheduler-10] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching.developer/trackfiles/track-2024-10-04-23-53-48-2.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.0: could not parse XML (At line 1, column 0: not well-formed (invalid token))
10-05 00:06:39.683 10957 11949 W cgeo    : [RxCachedThreadScheduler-10] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching.developer/trackfiles/track-2024-10-04-23-53-48-2.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.0: could not parse XML
10-05 00:06:39.865 10957 10957 I cgeo    : [main] AsyncMapWrapper: Init Layer
10-05 00:06:39.866 10957 10957 I cgeo    : [main] AsyncMapWrapper: Init Layer
10-05 00:06:39.963 10957 10957 I cgeo    : [main] GeoItemLayer:clickableItems(MapsforgeV6GeoItemLayer):BATCH-END - ADDS:1(1), REMOVES:0(0), REPLACES:0(0)
10-05 00:06:40.096 10957 10957 I cgeo    : [main] GeoItemLayer:nonClickableItems(MapsforgeV6GeoItemLayer):BATCH-END - ADDS:2(2), REMOVES:0(0), REPLACES:0(0)
10-05 00:08:43.865 10957 10957 I cgeo    : [main] GeoItemLayer:nonClickableItems(MapsforgeV6GeoItemLayer):BATCH-END - ADDS:0(2), REMOVES:0(0), REPLACES:2(2)
10-05 00:08:44.137 10957 11833 I cgeo    : [Thread-26] WHERIGOGAME: pushDialog:[Uhhh Mc Clane - du siehst nicht wo die Quelle ist? Wie schade - suche sie in etwa 90m Entfernung - aber beeile Dich..hahahaah!]
10-05 00:09:03.964 10957 10957 I cgeo    : [main] GeoItemLayer:nonClickableItems(MapsforgeV6GeoItemLayer):BATCH-END - ADDS:0(2), REMOVES:0(0), REPLACES:2(4)
10-05 00:09:14.545 10957 11833 W cgeo    : [Thread-26] WHERIGOGAME: ERRORyou hit a bug! please report at openwig.googlecode.com and i'll fix it for you!
10-05 00:09:14.545 10957 11833 W cgeo    : java.lang.NullPointerException: Attempt to get length of null array
10-05 00:09:14.545 10957 11833 W cgeo    : 
10-05 00:09:14.545 10957 11833 W cgeo    : stack trace: at PlayAudioat @E:/webtempfiles/b50a2d43-b5cf-4951-8bdc-cc4a0e11a4f4/_cartridge-new.enc:1342
10-05 00:09:14.545 10957 10957 I cgeo    : [main] [APP].showToast(WHERIGO:ERROR:you hit a bug! please report at openwig.googlecode.com and i'll fix it for you!
10-05 00:09:14.545 10957 10957 I cgeo    : java.lang.NullPointerException: Attempt to get length of null array
10-05 00:09:14.545 10957 10957 I cgeo    : 
10-05 00:09:14.545 10957 10957 I cgeo    : stack trace: at PlayAudioat @E:/webtempfiles/b50a2d43-b5cf-4951-8bdc-cc4a0e11a4f4/_cartridge-new.enc:1342
10-05 00:09:14.545 10957 10957 I cgeo    : ){LONG}
10-05 00:09:26.453 10957 11833 I cgeo    : [Thread-26] WHERIGOGAME: pushDialog:[Oh - da ist ja die Quelle - jetzt beeil dich aber]
10-05 00:09:26.475 10957 10957 I cgeo    : [main] GeoItemLayer:clickableItems(MapsforgeV6GeoItemLayer):BATCH-END - ADDS:1(2), REMOVES:0(0), REPLACES:0(0)
10-05 00:09:31.642 10957 11833 I cgeo    : [Thread-26] WHERIGOGAME: showScreen:1:Die Quelle
10-05 00:09:37.568 10957 10957 E cgeo    : [main] Launching UnifiedMap in viewport mode, viewport=Viewport[N 51° 28.914' · E 007° 13.044',N 51° 28.924' · E 007° 13.060'])
10-05 00:09:37.725 10957 11974 W cgeo    : [RxCachedThreadScheduler-12] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching.developer/trackfiles/track-2024-10-04-23-53-48-2.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.1: could not parse XML
10-05 00:09:37.726 10957 11974 W cgeo    : [RxCachedThreadScheduler-12] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching.developer/trackfiles/track-2024-10-04-23-53-48-2.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.0: could not parse XML
10-05 00:09:37.726 10957 11974 W cgeo    : [RxCachedThreadScheduler-12] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching.developer/trackfiles/track-2024-10-04-23-53-48-2.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.1: could not parse XML (At line 1, column 0: not well-formed (invalid token))
10-05 00:09:37.729 10957 11974 W cgeo    : [RxCachedThreadScheduler-12] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching.developer/trackfiles/track-2024-10-04-23-53-48-2.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.0: could not parse XML (At line 1, column 0: not well-formed (invalid token))
10-05 00:09:37.730 10957 11974 W cgeo    : [RxCachedThreadScheduler-12] Problem parsing GPX Track file 'file:///data/user/0/cgeo.geocaching.developer/trackfiles/track-2024-10-04-23-53-48-2.gpx': cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.0: could not parse XML
10-05 00:09:37.889 10957 10957 I cgeo    : [main] AsyncMapWrapper: Init Layer
10-05 00:09:37.889 10957 10957 I cgeo    : [main] AsyncMapWrapper: Init Layer
10-05 00:09:37.898 10957 10957 I cgeo    : [main] Destroy Layer
10-05 00:09:37.899 10957 10957 I cgeo    : [main] Destroy Layer
10-05 00:09:37.977 10957 10957 I cgeo    : [main] GeoItemLayer:clickableItems(MapsforgeV6GeoItemLayer):BATCH-END - ADDS:2(2), REMOVES:0(0), REPLACES:0(0)
10-05 00:09:38.030 10957 10957 I cgeo    : [main] GeoItemLayer:nonClickableItems(MapsforgeV6GeoItemLayer):BATCH-END - ADDS:2(2), REMOVES:0(0), REPLACES:0(0)
10-05 00:09:44.356 10957 10957 I cgeo    : [main] Destroy Layer
10-05 00:09:44.360 10957 10957 I cgeo    : [main] Destroy Layer
10-05 00:09:54.358 10957 11833 I cgeo    : [Thread-26] WHERIGOGAME: pushDialog:[Water is flowing slowly! Es fliesst etwas Wasser! L'eau coule doucement!]
10-05 00:10:10.780 10957 11833 I cgeo    : [Thread-26] WHERIGOGAME: pushDialog:[The tap is closed / Der Wasserhahn ist zu/ Le robinet est ferme.]
10-05 00:11:11.451 10957 10957 I cgeo    : [main] AsyncMapWrapper: Init Layer
10-05 00:11:11.452 10957 10957 I cgeo    : [main] AsyncMapWrapper: Init Layer
10-05 00:11:11.594 10957 10957 I cgeo    : [main] GeoItemLayer:clickableItems(MapsforgeV6GeoItemLayer):BATCH-END - ADDS:2(2), REMOVES:0(0), REPLACES:0(0)
10-05 00:11:11.594 10957 10957 I cgeo    : [main] GeoItemLayer:nonClickableItems(MapsforgeV6GeoItemLayer):BATCH-END - ADDS:2(2), REMOVES:0(0), REPLACES:0(0)
10-05 00:13:40.384 10957 10957 W cgeo    : [main] LooperLogger: long process time for >>>>> Dispatching to Handler (android.view.ViewRootImpl$ViewRootHandler) {11b00b0} androidx.appcompat.app.AppCompatDelegateImpl$2@27128cc: 0 (534ms, total:#163268/156733ms/avg 0ms), 0traces:
10-05 00:13:40.501 10957 10957 I cgeo    : [main] Destroy Layer
10-05 00:13:40.501 10957 10957 I cgeo    : [main] Destroy Layer
10-05 00:13:41.257 10957 12116 W cgeo    : [RxCachedThreadScheduler-14] External public cgeo directory '/storage/emulated/0/cgeo' not available
10-05 00:13:50.421 10957 12116 I cgeo    : [RxCachedThreadScheduler-14] [LogCat]Issuing command: [logcat, -d, AndroidRuntime:E, cgeo:D, cgeo.geocachin:I, *:S, -f, /data/user/0/cgeo.geocaching.developer/cache/cgeo_tempfile_4010769870723488465.tmp]
```

_Originally posted by @moving-bits in https://github.com/cgeo/cgeo/issues/10087#issuecomment-2394739711_

**Comment by eddiemuc** [comment]
@moving-bits do you know if this cartridge works in WhereYouGo or any other OpenWIG-based player?

**Comment by moving-bits** [comment]
Yes, I have played this cartridge a long time ago with WhereYouGo

**Comment by eddiemuc** [comment]
Reproduced it. Annoyingly OpenWIG "logs" to System.err / System.out, so this is not easy to catch. But here we go:

```
2024-10-05 13:55:47.382  4736-5280  Traf...ats cge...developer  D  tagSocket(116) with statsTag=0xffffffff, statsUid=-1
2024-10-05 13:55:55.267  4736-4973  System.err cge...developer  W  java.lang.NullPointerException: Attempt to get length of null array
2024-10-05 13:55:55.267  4736-4973  System.err cge...developer  W  	at cgeo.geocaching.wherigo.WherigoGame.playSound(WherigoGame.java:336)
2024-10-05 13:55:55.267  4736-4973  System.err cge...developer  W  	at cz.matejcik.openwig.Media.play(Media.java:58)
2024-10-05 13:55:55.267  4736-4973  System.err cge...developer  W  	at cz.matejcik.openwig.WherigoLib.playAudio(WherigoLib.java:373)
2024-10-05 13:55:55.267  4736-4973  System.err cge...developer  W  	at cz.matejcik.openwig.WherigoLib.call(WherigoLib.java:222)
2024-10-05 13:55:55.267  4736-4973  System.err cge...developer  W  	at se.krka.kahlua.vm.LuaState.callJava(LuaState.java:233)
2024-10-05 13:55:55.267  4736-4973  System.err cge...developer  W  	at se.krka.kahlua.vm.LuaState.luaMainloop(LuaState.java:693)
2024-10-05 13:55:55.267  4736-4973  System.err cge...developer  W  	at se.krka.kahlua.vm.LuaState.call(LuaState.java:217)
2024-10-05 13:55:55.267  4736-4973  System.err cge...developer  W  	at se.krka.kahlua.vm.LuaState.call(LuaState.java:1136)
2024-10-05 13:55:55.267  4736-4973  System.err cge...developer  W  	at cz.matejcik.openwig.EventTable.callEvent(EventTable.java:112)
2024-10-05 13:55:55.267  4736-4973  System.err cge...developer  W  	at cz.matejcik.openwig.Engine$2.run(Engine.java:288)
2024-10-05 13:55:55.267  4736-4973  System.err cge...developer  W  	at util.BackgroundRunner.run(BackgroundRunner.java:56)
2024-10-05 13:55:55.267  4736-4973  System.out cge...developer  I  at PlayAudioat @E:/webtempfiles/3e0d81c3-52f8-4757-84d9-3dfc151a5954/_cartridge-new.enc:1342
2024-10-05 13:55:55.268  4736-4973  cgeo       cge...developer  W  [Thread-3] WHERIGOGAME: ERROR: you hit a bug! please report at openwig.googlecode.com and i'll fix it for you!
                                                                   java.lang.NullPointerException: Attempt to get length of null array
                                                                   
                                                                   stack trace: at PlayAudioat @E:/webtempfiles/3e0d81c3-52f8-4757-84d9-3dfc151a5954/_cartridge-new.enc:1342
2024-10-05 13:55:55.268  4736-4736  cgeo       cge...developer  I  [main] [APP].showToast(WHERIGO: ERROR: you hit a bug! please report at openwig.googlecode.com and i'll fix it for you!
                                                                   java.lang.NullPointerException: Attempt to get length of null array
                                                                   
                                                                   stack trace: at PlayAudioat @E:/webtempfiles/3e0d81c3-52f8-4757-84d9-3dfc151a5954/_cartridge-new.enc:1342
                                                                   ){LONG}

```

Fix is on its way
