### ISSUE TITLE
Crash on resuming new mapsforge

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#16177]
### Describe your problem!

Resuming new mapsforge map from bundle causes a crash.

### How to reproduce?

Open map, switch to other activity and wait until c:geo is stopped, resume c:geo.

### Reproducible

Yes

### c:geo Version

2024.10.06-NB-fff53c4

### Additional Information

```
---------------- CGeoApplication: startup -------------
10-06 10:51:22.689  4032  4032 E cgeo    : [main] c:geo version 2024.10.06-NB-fff53c4
10-06 10:51:22.689  4032  4032 I cgeo    : [main] [CtxLog]CGeoApplication.onCreate:START
10-06 10:51:22.695  4032  4032 I cgeo    : [main] [CtxLog]DataStore.init:START
10-06 10:51:22.698  4032  4032 I cgeo    : [main] [DB] Current Database Version: 103
10-06 10:51:22.700  4032  4032 I cgeo    : [main] [CtxLog]DataStore.init:END (5ms)
10-06 10:51:22.703  4032  4032 I cgeo    : [main] LooperLogger: started for Thread: main
10-06 10:51:22.703  4032  4032 W System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
10-06 10:51:22.703  4032  4032 W System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
10-06 10:51:22.703  4032  4032 W System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
10-06 10:51:22.704  4032  4032 I cgeo    : [main] [CtxLog]CGeoApplication.onCreate:END (15ms)
10-06 10:51:22.833  4032  4094 I cgeo    : [network--1] GCLogin: get login Page
10-06 10:51:22.959  4032  4032 E AndroidRuntime: FATAL EXCEPTION: main
10-06 10:51:22.959  4032  4032 E AndroidRuntime: Process: cgeo.geocaching, PID: 4032
10-06 10:51:22.959  4032  4032 E AndroidRuntime: java.lang.IllegalArgumentException: zoomLevel must not be negative: -1
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at org.mapsforge.map.model.MapViewPosition.setZoomLevel(MapViewPosition.java:579)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at org.mapsforge.map.model.MapViewPosition.setZoomLevel(MapViewPosition.java:566)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at org.mapsforge.map.android.view.MapView.setZoomLevel(MapView.java:568)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at cgeo.geocaching.unifiedmap.mapsforge.MapsforgeFragment.setZoom(MapsforgeFragment.java:377)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at cgeo.geocaching.unifiedmap.mapsforge.MapsforgeFragment.onViewCreated(MapsforgeFragment.java:89)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at cgeo.geocaching.activity.AbstractActivity.onStart(AbstractActivity.java:313)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at cgeo.geocaching.activity.AbstractNavigationBarActivity.onStart(AbstractNavigationBarActivity.java:211)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.onStart(UnifiedMapActivity.java:1237)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1597)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8931)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4016)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:224)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:318)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8755)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
10-06 10:51:22.959  4032  4032 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
10-06 10:51:22.960  4032  4032 W cgeo    : [main] UncaughtException
10-06 10:51:22.960  4032  4032 W cgeo    : java.lang.IllegalArgumentException: zoomLevel must not be negative: -1
10-06 10:51:22.960  4032  4032 W cgeo    : 	at org.mapsforge.map.model.MapViewPosition.setZoomLevel(MapViewPosition.java:579)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at org.mapsforge.map.model.MapViewPosition.setZoomLevel(MapViewPosition.java:566)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at org.mapsforge.map.android.view.MapView.setZoomLevel(MapView.java:568)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at cgeo.geocaching.unifiedmap.mapsforge.MapsforgeFragment.setZoom(MapsforgeFragment.java:377)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at cgeo.geocaching.unifiedmap.mapsforge.MapsforgeFragment.onViewCreated(MapsforgeFragment.java:89)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at cgeo.geocaching.activity.AbstractActivity.onStart(AbstractActivity.java:313)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at cgeo.geocaching.activity.AbstractNavigationBarActivity.onStart(AbstractNavigationBarActivity.java:211)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.onStart(UnifiedMapActivity.java:1237)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1597)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at android.app.Activity.performStart(Activity.java:8931)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4016)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at android.os.Looper.loopOnce(Looper.java:224)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at android.os.Looper.loop(Looper.java:318)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:8755)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
10-06 10:51:22.960  4032  4032 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by moving-bits** [comment]
PR #16179 fixes this
