### ISSUE TITLE
Crash on screen rotation in unified map

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#16190]
### Describe your problem!

Changing the screen orientation in unified map causes a crash.

### How to reproduce?

Open unified map and rotate device.

### Reproducible

Yes

### c:geo Version

2024.10.07-NB-b8e33cf

### Additional Information

```
10-07 20:18:09.205 26050 26050 E AndroidRuntime: FATAL EXCEPTION: main
10-07 20:18:09.205 26050 26050 E AndroidRuntime: Process: cgeo.geocaching, PID: 26050
10-07 20:18:09.205 26050 26050 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setRotation(float)' on a null object reference
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.repaintRotationIndicator(UnifiedMapActivity.java:919)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at cgeo.geocaching.unifiedmap.AbstractMapFragment.setMapRotation(AbstractMapFragment.java:164)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at cgeo.geocaching.unifiedmap.mapsforge.MapsforgeFragment.setMapRotation(MapsforgeFragment.java:391)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at cgeo.geocaching.unifiedmap.mapsforge.MapsforgeFragment.onViewCreated(MapsforgeFragment.java:76)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at cgeo.geocaching.activity.AbstractActivity.onStart(AbstractActivity.java:313)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at cgeo.geocaching.activity.AbstractNavigationBarActivity.onStart(AbstractNavigationBarActivity.java:211)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.onStart(UnifiedMapActivity.java:1237)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1597)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:8931)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4016)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:224)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:318)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8755)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
10-07 20:18:09.205 26050 26050 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
10-07 20:18:09.206 26050 26050 W cgeo    : [main] UncaughtException
10-07 20:18:09.206 26050 26050 W cgeo    : java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setRotation(float)' on a null object reference
10-07 20:18:09.206 26050 26050 W cgeo    : 	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.repaintRotationIndicator(UnifiedMapActivity.java:919)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at cgeo.geocaching.unifiedmap.AbstractMapFragment.setMapRotation(AbstractMapFragment.java:164)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at cgeo.geocaching.unifiedmap.mapsforge.MapsforgeFragment.setMapRotation(MapsforgeFragment.java:391)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at cgeo.geocaching.unifiedmap.mapsforge.MapsforgeFragment.onViewCreated(MapsforgeFragment.java:76)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at cgeo.geocaching.activity.AbstractActivity.onStart(AbstractActivity.java:313)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at cgeo.geocaching.activity.AbstractNavigationBarActivity.onStart(AbstractNavigationBarActivity.java:211)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at cgeo.geocaching.unifiedmap.UnifiedMapActivity.onStart(UnifiedMapActivity.java:1237)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1597)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at android.app.Activity.performStart(Activity.java:8931)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4016)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:235)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:215)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:187)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:106)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at android.os.Looper.loopOnce(Looper.java:224)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at android.os.Looper.loop(Looper.java:318)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:8755)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
10-07 20:18:09.206 26050 26050 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by moving-bits** [comment]
Fixed with #16201
