### ISSUE TITLE
NPE in GCParser

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#16265]
[Ticket #145739](https://cgeosupport.droescher.eu/scp/tickets.php?id=8715)
c:geo problem report (2024.10.24-NB-f52fb17)

User reports an error when trying to upload drafts to gc.com Logfile reveals a repeating NPE:

```
10-19 18:38:12.393  5490  7100 E AndroidRuntime: FATAL EXCEPTION: network--10
10-19 18:38:12.393  5490  7100 E AndroidRuntime: Process: cgeo.geocaching, PID: 5490
10-19 18:38:12.393  5490  7100 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
10-19 18:38:12.393  5490  7100 E AndroidRuntime: 	at cgeo.geocaching.connector.gc.GCParser.parseCacheFromText(GCParser.java:388)
10-19 18:38:12.393  5490  7100 E AndroidRuntime: 	at cgeo.geocaching.connector.gc.GCParser.parseCache(GCParser.java:148)
10-19 18:38:12.393  5490  7100 E AndroidRuntime: 	at cgeo.geocaching.connector.gc.GCConnector.searchByGeocode(GCConnector.java:286)
10-19 18:38:12.393  5490  7100 E AndroidRuntime: 	at cgeo.geocaching.models.Geocache.searchByGeocode(Geocache.java:2193)
10-19 18:38:12.393  5490  7100 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity.lambda$onCreate$3(CacheDetailActivity.java:379)
10-19 18:38:12.393  5490  7100 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity.$r8$lambda$ejXkgPcN7t0Lh2OXPDz7K4B8weE(CacheDetailActivity.java:0)
10-19 18:38:12.393  5490  7100 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity$$ExternalSyntheticLambda2.run(R8$$SyntheticClass:0)
10-19 18:38:12.393  5490  7100 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
10-19 18:38:12.393  5490  7100 E AndroidRuntime: 	at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:25)
10-19 18:38:12.393  5490  7100 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
10-19 18:38:12.393  5490  7100 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
10-19 18:38:12.393  5490  7100 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
10-19 18:38:12.393  5490  7100 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
10-19 18:38:19.773  7563  7614 E AndroidRuntime: FATAL EXCEPTION: network--1
```

**Comment by bekuno** [comment]
Maybe network-related. We have problem descriptions with uploading FN on FB.

**Comment by cylorak** [comment]
Hi 👋 I've been investigating this one and would like to take it on — could a maintainer please assign it to me?

While reproducing the reported crash I found that the original `String.equals()` -on-null NPE in GCParser.parseCacheFromText is already resolved, but a crash of the same class still exists on partial/truncated pages (which matches the "network-related" hint in the report): 
when a cache page is cut off mid-waypoint-section (e.g. an interrupted download), the parser does an unchecked 
`substring(0, indexOf("</table>"))`. 
The closing tag is missing, `indexOf `returns -1, and `substring(0, -1)` throws `StringIndexOutOfBoundsException`, crashing cache load.

**Comment by moving-bits** [comment]
Thanks, @cylorak, for looking into this, very appreciated. I've assigned this issue to you.
