### ISSUE TITLE
NPE on importing a GPX file

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#16314]
similar to #16310, but different symptoms:

Ticket 343578

c:geo fails to import a GPX file. Log reveals the following error:

```
11-02 18:09:32.818 10355 10922 E cgeo    : [Thread-6] Importing caches failed - unknown error: 
11-02 18:09:32.818 10355 10922 E cgeo    : java.lang.NullPointerException: Attempt to invoke virtual method 'boolean cgeo.geocaching.models.Geocache.recalculateWaypoints(cgeo.geocaching.models.CacheVariableList)' on a null object reference
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.models.CacheVariableList.recalculateWaypoints(CacheVariableList.java:106)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.models.CacheVariableList.saveState(CacheVariableList.java:73)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.models.Geocache.changeVariables(Geocache.java:1884)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.models.Geocache.addCacheArtefactsFromText(Geocache.java:1859)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.models.Geocache.addCacheArtefactsFromNotes(Geocache.java:1817)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.models.Geocache.addCacheArtefactsFromNotes(Geocache.java:1809)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.storage.DataStore.lambda$saveCaches$20(DataStore.java:2403)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.storage.DataStore.$r8$lambda$x6se3Wos1Bdhqcul_16qtR7gcQw(DataStore.java:0)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.storage.DataStore$$ExternalSyntheticLambda26.run(R8$$SyntheticClass:0)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.storage.DataStore.withAccessLock(DataStore.java:1023)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.storage.DataStore.saveCaches(DataStore.java:2361)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.storage.DataStore.saveCache(DataStore.java:2348)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.files.GPXParser$1.end(GPXParser.java:277)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at android.sax.RootElement$Handler.endElement(RootElement.java:188)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:160)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:501)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:488)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at android.util.Xml.parse(Xml.java:71)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.files.GPXParser.parse(GPXParser.java:434)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.files.GPX10Parser.parse(GPX10Parser.java:7)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.files.ImportGpxAttachmentThread.doImport(ImportGpxAttachmentThread.java:47)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.files.AbstractImportGpxThread.doImport(AbstractImportGpxThread.java:21)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.files.AbstractImportThread.run(AbstractImportThread.java:30)
11-02 18:09:32.818 10355 10922 E cgeo    : 	at cgeo.geocaching.files.ImportGpxAttachmentThread.run(ImportGpxAttachmentThread.java:24)
```

A quick fix is to add a null check in `CacheListVariable.recalculateWaypoints()`, but the underlying issue is that c:geo tries to store data for a cache (in this case: gathered from cache notes) while the cache does not yet exist in the database.

Setting Prio to "high", as this bug effectively blocks importing cache data as soon as the cache note contains some data which require to store cache data (eg: variables or waypoints).

Relevant place is the call to `cache.addCacheArtefactsFromNotes()` in `DataStore.saveCaches()` (around line 2346 as of current `master`).

**Comment by eddiemuc** [comment]
Regardless of the deeper meaning behind why GPX import uses methods meant for existing caches only, it is mandatory that all code is stable to foreseeable problems like this (every NPE is a bug. Always!). So PR #16317 fixes the actual NPE. I put it on release since this might also affect productive versions of c:geo

**Comment by moving-bits** [comment]
From further tests on both `release` and `master` branches: Fixing the crash seems to be sufficient, no further handling required.

(On importing the GPX provided by the user, analyzing the cache notes + creating the variables from it is done again further down the pipeline, so it does not hurt if the first analysis cannot store the gathered data due to cache not yet being stored.)

Thus closing this issue.
