### ISSUE TITLE
Unified Mapsforge: no max zoom limit -> crash

### ISSUE THREAD

**Issue by ztNFny** [cgeo/cgeo#16468]
UnifiedMaps Mapsforge doesn't limit the maximum zoom level, allowing you to zoom in further and further - until it crashs. (The level before it crashs the size of map elements is doubled, indicating that already there the maximum possible is reached)

Max zoom should probably be limited to 20, at least that's what it seems to be for VTM. There's really no point in zooming in further.

FATAL EXCEPTION: LayerManager
Process: cgeo.geocaching, PID: 32394
java.lang.IllegalArgumentException: top: 2.147483647E9, bottom: -2.147483544E9
	at org.mapsforge.core.model.Rectangle.check(Rectangle.java:265)
	at org.mapsforge.core.model.Rectangle.<init>(Rectangle.java:32)
	at org.mapsforge.map.layer.overlay.Marker.draw(Marker.java:83)
	at cgeo.geocaching.unifiedmap.geoitemlayer.MapsforgeV6GeoItemLayer.draw(MapsforgeV6GeoItemLayer.java:241)
	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:108)
	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)

**Comment by moving-bits** [comment]
I've debugged a bit into it and opened a [discussion on Mapsforge](https://github.com/mapsforge/mapsforge/discussions/1607)

**Comment by moving-bits** [comment]
See PR #16470
