### ISSUE TITLE
Network operation on UI thread

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#1705]
A network request may be done from the UI thread when creating a `cgeovisit` (now renamed into `VisitCacheActivity`) if the template contains `[NUMBER]`:

``` 
 at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
  at cgeo.geocaching.cgBase.doRequest(cgBase.java:2908)
  at cgeo.geocaching.cgBase.request(cgBase.java:2889)
  at cgeo.geocaching.cgBase.request(cgBase.java:2880)
  at cgeo.geocaching.cgBase.request(cgBase.java:2801)
  at cgeo.geocaching.LogTemplateProvider$5.getValue(LogTemplateProvider.java:88)
  at cgeo.geocaching.LogTemplateProvider$LogTemplate.apply(LogTemplateProvider.java:40)
  at cgeo.geocaching.LogTemplateProvider.applyTemplates(LogTemplateProvider.java:117)
  at cgeo.geocaching.cgeovisit.init(cgeovisit.java:462)
  at cgeo.geocaching.cgeovisit.onCreate(cgeovisit.java:244)
```

This may lead to *Application Not Responding* errors.

**Edit 2014-08-12:** this also leads to crashes with recent Android versions which do not allow this kind of operation to happen on the UI thread, see later comment.

**Comment by Lineflyer** [comment]
@samueltardieu I do no longer see the exception when starting a logging and using `[NUMBER]` in the log template.  Still open?

**Comment by samueltardieu** [comment]
As fas as I know, yes. On which Android version do you test?

**Comment by Lineflyer** [comment]
Better late then never: I used Android 4.3. Also now on Android 5 I can not reproduce.

**Comment by samueltardieu** [comment]
Can no longer happen with OkHttp.
