### ISSUE TITLE
Do not build complete responses in memory

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#1806]
Many crashes are linked to `OutOfMemoryError` on low-end devices due to the fact that we systematically store responses in strings, whereas we could process them as a stream. This is due to our all-regex approach, which could be replaced in many cases by a sax-like parser such as the one from tagsoup. That would not require storing whole web pages in memory.

``` text
java.lang.OutOfMemoryError: (Heap Size=11719KB, Allocated=6276KB, Bitmap Size=7969KB)
at ch.boye.httpclientandroidlib.util.CharArrayBuffer.expand(CharArrayBuffer.java:63)
at ch.boye.httpclientandroidlib.util.CharArrayBuffer.append(CharArrayBuffer.java:93)
at android.support.v4.app.ActivityCompatHoneycomb.toString(RequiredFields.java:225)
at cgeo.geocaching.network.Network.getResponseDataNoError(Network.java:371)
at cgeo.geocaching.network.Network.getResponseData(Network.java:387)
at cgeo.geocaching.network.Network.getResponseData(Network.java:380)
at cgeo.geocaching.connector.gc.Login.switchToEnglish(Login.java:221)
at cgeo.geocaching.connector.gc.Login.login(Login.java:87)
at cgeo.geocaching.cgeo$firstLogin.run(cgeo.java:825)
```

**Comment by Lineflyer** [comment]
@samueltardieu This issue is rather old. Is it still relevant? As far as I understand we meanwhile started using things like JSoup and other methods, and perhaps this issue is much to generic to ever be solved?!

**Comment by samueltardieu** [comment]
We use JSoup in some places, but not everywhere, far from it. The issue is still relevant.

**Comment by kumy** [comment]
Jsoup is only used in some (small) parts, and there are still many regex used :(. we should keep the issue and probably rename it to "Use a dom parser instead of Regex"
