### ISSUE TITLE
Application crash when rotating the phone while posting log

### ISSUE THREAD

**Issue by YraFyra** [cgeo/cgeo#3198]
I got the following stacktrace today when I posted a log for a cache. I probably rotated the phone right after I pressed 'post'.

```
E WindowManager: Activity cgeo.geocaching.LogCacheActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{42784ec8 V.E..... R.....I. 0,0-565,347} that was originally added here
E WindowManager: android.view.WindowLeaked: Activity cgeo.geocaching.LogCacheActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{42784ec8 V.E..... R.....I. 0,0-565,347} that was originally added here
E WindowManager: 	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:355)
E WindowManager: 	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:216)
E WindowManager: 	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
E WindowManager: 	at android.app.Dialog.show(Dialog.java:289)
E WindowManager: 	at cgeo.geocaching.activity.Progress.show(Progress.java:40)
E WindowManager: 	at cgeo.geocaching.utils.AsyncTaskWithProgress.onPreExecute(AsyncTaskWithProgress.java:77)
E WindowManager: 	at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:586)
E WindowManager: 	at android.os.AsyncTask.execute(AsyncTask.java:534)
E WindowManager: 	at cgeo.geocaching.LogCacheActivity$PostListener.onClick(LogCacheActivity.java:524)
E WindowManager: 	at android.view.View.performClick(View.java:4278)
E WindowManager: 	at android.view.View$PerformClick.run(View.java:17430)
E WindowManager: 	at android.os.Handler.handleCallback(Handler.java:725)
E WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:92)
E WindowManager: 	at android.os.Looper.loop(Looper.java:217)
E WindowManager: 	at android.app.ActivityThread.main(ActivityThread.java:5092)
E WindowManager: 	at java.lang.reflect.Method.invokeNative(Native Method)
E WindowManager: 	at java.lang.reflect.Method.invoke(Method.java:511)
E WindowManager: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
E WindowManager: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
E WindowManager: 	at dalvik.system.NativeStart.main(Native Method)
D AndroidRuntime: Shutting down VM
W dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4162eae0)
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: java.lang.IllegalArgumentException: View not attached to window manager
E AndroidRuntime: 	at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:383)
E AndroidRuntime: 	at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:285)
E AndroidRuntime: 	at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:79)
E AndroidRuntime: 	at android.app.Dialog.dismissDialog(Dialog.java:331)
E AndroidRuntime: 	at android.app.Dialog.dismiss(Dialog.java:314)
E AndroidRuntime: 	at cgeo.geocaching.activity.Progress.dismiss(Progress.java:31)
E AndroidRuntime: 	at cgeo.geocaching.utils.AsyncTaskWithProgress.onPostExecute(AsyncTaskWithProgress.java:97)
E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:631)
E AndroidRuntime: 	at android.os.AsyncTask.access$600(AsyncTask.java:177)
E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:217)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5092)
E AndroidRuntime: 	at java.lang.reflect.Method.invokeNative(Native Method)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:511)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:564)
E AndroidRuntime: 	at dalvik.system.NativeStart.main(Native Method)
W ActivityManager:   Force finishing activity cgeo.geocaching/.CacheDetailActivity
```

**Comment by Lineflyer** [comment]
This is no longer happening with 2015.01.05-RC (and most likely also since some versions before).
