### ISSUE TITLE
Attempt to draw recycled bitmap

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#3528]
Message from user: "Zoom in, zoom out, over".

I have already seen such reports with the previous release.

```
java.lang.NullPointerException
   at android.graphics.Canvas.throwIfRecycled(Canvas.java:1025)
   at android.graphics.Canvas.drawBitmap(Canvas.java:1065)
   at org.mapsforge.android.maps.FrameBuffer.drawBitmap(FrameBuffer.java:101)
   at org.mapsforge.android.maps.MapView.redrawTiles(MapView.java:402)
   at org.mapsforge.android.maps.inputhandling.MultiTouchHandler.onActionMove(MultiTouchHandler.java:91)
   at org.mapsforge.android.maps.inputhandling.MultiTouchHandler.handleMotionEvent(MultiTouchHandler.java:186)
   at org.mapsforge.android.maps.inputhandling.TouchEventHandler.handleTouchEvent(TouchEventHandler.java:149)
   at org.mapsforge.android.maps.MapView.onTouchEvent(MapView.java:349)
   at cgeo.geocaching.maps.mapsforge.MapsforgeMapView.onTouchEvent(MapsforgeMapView.java:274)
   at android.view.View.dispatchTouchEvent(View.java:7337)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2410)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2145)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2416)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2159)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2416)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2159)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2416)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2159)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2416)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2159)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2416)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2159)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2416)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2159)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2416)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2159)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2416)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2159)
   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2115)
   at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1468)
   at android.app.Activity.dispatchTouchEvent(Activity.java:2487)
   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2063)
   at android.view.View.dispatchPointerEvent(View.java:7520)
   at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3376)
   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3308)
   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4402)
   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4380)
   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4484)
   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:171)
   at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
   at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:163)
   at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:4452)
   at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:4503)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:725)
   at android.view.Choreographer.doCallbacks(Choreographer.java:555)
   at android.view.Choreographer.doFrame(Choreographer.java:523)
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:711)
   at android.os.Handler.handleCallback(Handler.java:615)
   at android.os.Handler.dispatchMessage(Handler.java:92)
   at android.os.Looper.loop(Looper.java:137)
   at android.app.ActivityThread.main(ActivityThread.java:4898)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1006)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:773)
   at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Lineflyer** [comment]
From Google Play with version 2015.07.08, this seems to be similar/the same (?):

```
java.lang.NullPointerException
   at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1094)
   at android.graphics.Canvas.drawBitmap(Canvas.java:1150)
   at org.mapsforge.android.maps.FrameBuffer.drawBitmap(FrameBuffer.java:101)
   at org.mapsforge.android.maps.MapView.redrawTiles(MapView.java:402)
   at org.mapsforge.android.maps.inputhandling.MultiTouchHandler.onActionMove(MultiTouchHandler.java:91)
   at org.mapsforge.android.maps.inputhandling.MultiTouchHandler.handleMotionEvent(MultiTouchHandler.java:186)
   at org.mapsforge.android.maps.inputhandling.TouchEventHandler.handleTouchEvent(TouchEventHandler.java:149)
   at org.mapsforge.android.maps.MapView.onTouchEvent(MapView.java:349)
   at cgeo.geocaching.maps.mapsforge.MapsforgeMapView.onTouchEvent(MapsforgeMapView.java:277)
   at android.view.View.dispatchTouchEvent(View.java:7767)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2224)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2230)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1973)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2230)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1973)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2230)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1973)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2230)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1973)
   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2230)
   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1973)
   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2072)
   at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1518)
   at android.app.Activity.dispatchTouchEvent(Activity.java:2531)
   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2020)
   at android.view.View.dispatchPointerEvent(View.java:8004)
   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4136)
   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3990)
   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3548)
   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3598)
   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3567)
   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3674)
   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3575)
   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3731)
   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3548)
   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3598)
   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3567)
   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3575)
   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3548)
   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5817)
   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5797)
   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5768)
   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5897)
   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
   at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
   at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
   at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5870)
   at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5916)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
   at android.view.Choreographer.doCallbacks(Choreographer.java:574)
   at android.view.Choreographer.doFrame(Choreographer.java:542)
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:757)
   at android.os.Handler.handleCallback(Handler.java:733)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:149)
   at android.app.ActivityThread.main(ActivityThread.java:5257)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
   at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Lineflyer** [comment]
With 2016.08.21 we already have 13 reports this week:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1269)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1325)
	at org.mapsforge.v3.android.maps.FrameBuffer.drawBitmap(FrameBuffer.java:101)
	at org.mapsforge.v3.android.maps.MapView.redrawTiles(MapView.java:402)
	at org.mapsforge.v3.android.maps.inputhandling.MultiTouchHandler.onActionMove(MultiTouchHandler.java:91)
	at org.mapsforge.v3.android.maps.inputhandling.MultiTouchHandler.handleMotionEvent(MultiTouchHandler.java:186)
	at org.mapsforge.v3.android.maps.inputhandling.TouchEventHandler.handleTouchEvent(TouchEventHandler.java:149)
	at org.mapsforge.v3.android.maps.MapView.onTouchEvent(MapView.java:349)
	at cgeo.geocaching.maps.mapsforge.MapsforgeMapView.onTouchEvent(MapsforgeMapView.java:277)
	at android.view.View.dispatchTouchEvent(View.java:9300)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
	at android.view.View.dispatchPointerEvent(View.java:9520)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5996)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6048)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:600)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by Lineflyer** [comment]
Still happening with recent versions on Google Play:

In this case User message was: Moving around map of stored caches

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1269)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1325)
	at org.mapsforge.v3.android.maps.FrameBuffer.drawBitmap(FrameBuffer.java:101)
	at org.mapsforge.v3.android.maps.MapView.redrawTiles(MapView.java:402)
	at org.mapsforge.v3.android.maps.inputhandling.MultiTouchHandler.onActionMove(MultiTouchHandler.java:91)
	at org.mapsforge.v3.android.maps.inputhandling.MultiTouchHandler.handleMotionEvent(MultiTouchHandler.java:186)
	at org.mapsforge.v3.android.maps.inputhandling.TouchEventHandler.handleTouchEvent(TouchEventHandler.java:149)
	at org.mapsforge.v3.android.maps.MapView.onTouchEvent(MapView.java:349)
	at cgeo.geocaching.maps.mapsforge.MapsforgeMapView.onTouchEvent(MapsforgeMapView.java:277)
	at android.view.View.dispatchTouchEvent(View.java:9301)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2547)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2240)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2254)
	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2659)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1787)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2771)
	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2620)
	at android.view.View.dispatchPointerEvent(View.java:9521)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4238)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4104)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3795)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3852)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3703)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3669)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3677)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3650)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5932)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5906)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5867)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6035)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6006)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6058)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:600)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by Lineflyer** [comment]
Closing as wont fix, as we are about to phase out the mapsforge v0.3 anyway.
