### ISSUE TITLE
Comparison method violates its general contract

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#3532]
Comment from user: system crash, use filter, or read cache details.

```
java.lang.IllegalArgumentException: Comparison method violates its general contract!
   at java.util.TimSort.mergeHi(TimSort.java:864)
   at java.util.TimSort.mergeAt(TimSort.java:481)
   at java.util.TimSort.mergeCollapse(TimSort.java:404)
   at java.util.TimSort.sort(TimSort.java:210)
   at java.util.TimSort.sort(TimSort.java:169)
   at java.util.Arrays.sort(Arrays.java:2038)
   at java.util.Collections.sort(Collections.java:1891)
   at cgeo.geocaching.ui.CacheListAdapter.forceSort(CacheListAdapter.java:276)
   at cgeo.geocaching.ui.CacheListAdapter.setComparator(CacheListAdapter.java:161)
   at cgeo.geocaching.CacheListActivity.setComparator(CacheListActivity.java:755)
   at cgeo.geocaching.CacheListActivity.access$2700(CacheListActivity.java:91)
   at cgeo.geocaching.CacheListActivity$11.run(CacheListActivity.java:689)
   at cgeo.geocaching.CacheListActivity$11.run(CacheListActivity.java:678)
   at cgeo.geocaching.sorting.ComparatorUserInterface$2.onClick(ComparatorUserInterface.java:92)
   at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:941)
   at android.widget.AdapterView.performItemClick(AdapterView.java:298)
   at android.widget.AbsListView.performItemClick(AbsListView.java:1100)
   at android.widget.AbsListView$PerformClick.run(AbsListView.java:2749)
   at android.widget.AbsListView$1.run(AbsListView.java:3423)
   at android.os.Handler.handleCallback(Handler.java:725)
   at android.os.Handler.dispatchMessage(Handler.java:92)
   at android.os.Looper.loop(Looper.java:137)
   at android.app.ActivityThread.main(ActivityThread.java:5041)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
   at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Lineflyer** [comment]
This error can no longer be seen on Google Play now for a long time. Additionally there was a change done by @samueltardieu with respect to the problem.
Feel free to reopen if you disagree or it appears again.
