### ISSUE TITLE
NPE in settings

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#3710]
In 2014.03.31.

```
rx.exceptions.OnErrorNotImplementedException
   at rx.Observable$25.onError(Observable.java:6805)
   at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:124)
   at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:93)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:108)
   at rx.operators.OperatorWeakBinding$WeakSubscriber.onNext(OperatorWeakBinding.java:75)
   at rx.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:147)
   at rx.operators.OperatorObserveOn$ObserveOnSubscriber.access$400(OperatorObserveOn.java:74)
   at rx.operators.OperatorObserveOn$ObserveOnSubscriber$1.call(OperatorObserveOn.java:116)
   at rx.operators.OperatorObserveOn$ObserveOnSubscriber$1.call(OperatorObserveOn.java:111)
   at rx.android.schedulers.HandlerThreadScheduler$InnerHandlerThreadScheduler$2.run(HandlerThreadScheduler.java:117)
   at android.os.Handler.handleCallback(Handler.java:615)
   at android.os.Handler.dispatchMessage(Handler.java:92)
   at android.os.Looper.loop(Looper.java:153)
   at android.app.ActivityThread.main(ActivityThread.java:5042)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
   at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
   at cgeo.geocaching.settings.SettingsActivity.initBasicMemberPreferences(SettingsActivity.java:373)
   at cgeo.geocaching.settings.AbstractCheckCredentialsPreference$LoginCheckClickListener$1.call(AbstractCheckCredentialsPreference.java:86)
   at cgeo.geocaching.settings.AbstractCheckCredentialsPreference$LoginCheckClickListener$1.call(AbstractCheckCredentialsPreference.java:73)
   at rx.Observable$25.onNext(Observable.java:6810)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:101)
   ... 15 more
```

**Comment by Lineflyer** [comment]
I can not see this specific problem on GooglePlay anymore.
 @samueltardieu @Bananeweizen OK with closing it or is there still a task to do?

**Comment by samueltardieu** [comment]
Let's close it.
