### ISSUE TITLE
Could not allocate CursorWindow crash

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3727]
I have seen similar reports on GooglePlay console and can also kind of reproduce this with 2014.04.03-NB:
- Open live map, google sat
- Start scrolling into one direction really fast 
- Keep on scrolling until crash

For me it takes real effort scrolling on the map until this happens. Therefore assigning as 'Low' by now.

```
21:00:06.246 Error CursorWindow 18601  Could not allocate CursorWindow '/data/data/cgeo.geocaching/databases/data' of size 2097152 due to error -24.
21:00:06.366 Error cgeo 18601  DataStore.loadInViewport
21:00:06.366 Error cgeo 18601  android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed.
21:00:06.366 Error cgeo 18601  	at android.database.CursorWindow.<init>(CursorWindow.java:104)
21:00:06.366 Error cgeo 18601  	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
21:00:06.366 Error cgeo 18601  	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
21:00:06.366 Error cgeo 18601  	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
21:00:06.366 Error cgeo 18601  	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
21:00:06.366 Error cgeo 18601  	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
21:00:06.366 Error cgeo 18601  	at cgeo.geocaching.DataStore.cursorToColl(DataStore.java:2143)
21:00:06.366 Error cgeo 18601  	at cgeo.geocaching.DataStore.queryToColl(DataStore.java:2138)
21:00:06.366 Error cgeo 18601  	at cgeo.geocaching.DataStore.loadInViewport(DataStore.java:2283)
21:00:06.366 Error cgeo 18601  	at cgeo.geocaching.DataStore.loadCachedInViewport(DataStore.java:2239)
21:00:06.366 Error cgeo 18601  	at cgeo.geocaching.maps.CGeoMap$LoadRunnable.run(CGeoMap.java:1069)
21:00:06.366 Error cgeo 18601  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
21:00:06.366 Error cgeo 18601  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
21:00:06.366 Error cgeo 18601  	at java.lang.Thread.run(Thread.java:856)
```

**Comment by Lineflyer** [comment]
Closing as suggested.

**Comment by Lineflyer** [comment]
Reopening as we still have occurences with the new release.

2015.03.31, 23 reports up to now.

User message seem all to relate to map activities like zooming or panning around the live map.

```
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed.
at android.database.CursorWindow.<init>(CursorWindow.java:104)
at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
at cgeo.geocaching.DataStore.cursorToColl(DataStore.java:2150)
at cgeo.geocaching.DataStore.loadWaypoints(DataStore.java:2913)
at cgeo.geocaching.maps.CGeoMap.doLoadRun(CGeoMap.java:1274)
at cgeo.geocaching.maps.CGeoMap.access$2600(CGeoMap.java:103)
at cgeo.geocaching.maps.CGeoMap$LoadRunnable.runWithMap(CGeoMap.java:1228)
at cgeo.geocaching.maps.CGeoMap$DoRunnable.run(CGeoMap.java:1443)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
```

**Comment by samueltardieu** [comment]
This is a symptom of a memory full error, which happens right there but could happen at any other place. We should (once again) implement Google Maps API v2 and a newer Mapsforge.
