### ISSUE TITLE
Crash when trying to log OC-cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#3962]
2014.06.06-NB:

- Open OC-cache: http://www.opencaching.de/OC10CB8
- Cache was already stored and has the status found (if this makes a difference)
- Select "Log Visit"

Crash:
```
21:40:29.107 Error cgeo 18239  UncaughtException
21:40:29.107 Error cgeo 18239  java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.LogCacheActivity}: android.os.NetworkOnMainThreadException
21:40:29.107 Error cgeo 18239  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2295)
21:40:29.107 Error cgeo 18239  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2349)
21:40:29.107 Error cgeo 18239  	at android.app.ActivityThread.access$700(ActivityThread.java:159)
21:40:29.107 Error cgeo 18239  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
21:40:29.107 Error cgeo 18239  	at android.os.Handler.dispatchMessage(Handler.java:99)
21:40:29.107 Error cgeo 18239  	at android.os.Looper.loop(Looper.java:137)
21:40:29.107 Error cgeo 18239  	at android.app.ActivityThread.main(ActivityThread.java:5419)
21:40:29.107 Error cgeo 18239  	at java.lang.reflect.Method.invokeNative(Native Method)
21:40:29.107 Error cgeo 18239  	at java.lang.reflect.Method.invoke(Method.java:525)
21:40:29.107 Error cgeo 18239  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
21:40:29.107 Error cgeo 18239  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
21:40:29.107 Error cgeo 18239  	at dalvik.system.NativeStart.main(Native Method)
21:40:29.107 Error cgeo 18239  Caused by: android.os.NetworkOnMainThreadException
21:40:29.107 Error cgeo 18239  	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1144)
21:40:29.107 Error cgeo 18239  	at java.net.InetAddress.lookupHostByName(InetAddress.java:385)
21:40:29.107 Error cgeo 18239  	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
21:40:29.107 Error cgeo 18239  	at java.net.InetAddress.getAllByName(InetAddress.java:214)
21:40:29.107 Error cgeo 18239  	at ch.boye.httpclientandroidlib.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
21:40:29.107 Error cgeo 18239  	at ch.boye.httpclientandroidlib.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:278)
21:40:29.107 Error cgeo 18239  	at ch.boye.httpclientandroidlib.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:162)
21:40:29.107 Error cgeo 18239  	at ch.boye.httpclientandroidlib.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:294)
21:40:29.107 Error cgeo 18239  	at ch.boye.httpclientandroidlib.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:645)
21:40:29.107 Error cgeo 18239  	at ch.boye.httpclientandroidlib.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:480)
21:40:29.107 Error cgeo 18239  	at ch.boye.httpclientandroidlib.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:902)
21:40:29.107 Error cgeo 18239  	at ch.boye.httpclientandroidlib.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:137)
21:40:29.107 Error cgeo 18239  	at ch.boye.httpclientandroidlib.impl.client.DecompressingHttpClient.execute(DecompressingHttpClient.java:108)
21:40:29.107 Error cgeo 18239  	at cgeo.geocaching.network.Network.doLogRequest(Network.java:230)
21:40:29.107 Error cgeo 18239  	at cgeo.geocaching.network.Network.request(Network.java:191)
21:40:29.107 Error cgeo 18239  	at cgeo.geocaching.network.Network.getRequest(Network.java:295)
21:40:29.107 Error cgeo 18239  	at cgeo.geocaching.connector.oc.OkapiClient.request(OkapiClient.java:715)
21:40:29.107 Error cgeo 18239  	at cgeo.geocaching.connector.oc.OkapiClient.getUserInfo(OkapiClient.java:790)
21:40:29.107 Error cgeo 18239  	at cgeo.geocaching.connector.oc.OCApiLiveConnector.login(OCApiLiveConnector.java:145)
21:40:29.107 Error cgeo 18239  	at cgeo.geocaching.utils.LogTemplateProvider$5.getValue(LogTemplateProvider.java:169)
21:40:29.107 Error cgeo 18239  	at cgeo.geocaching.utils.LogTemplateProvider$LogTemplate.apply(LogTemplateProvider.java:101)
21:40:29.107 Error cgeo 18239  	at cgeo.geocaching.utils.LogTemplateProvider.applyTemplates(LogTemplateProvider.java:270)
21:40:29.107 Error cgeo 18239  	at cgeo.geocaching.LogCacheActivity.onCreate(LogCacheActivity.java:255)
21:40:29.107 Error cgeo 18239  	at android.app.Activity.performCreate(Activity.java:5372)
21:40:29.107 Error cgeo 18239  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1104)
21:40:29.107 Error cgeo 18239  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2257)
21:40:29.107 Error cgeo 18239  	... 11 more
```

Seems to work OK if I open the cache from within c:geo instead of clicking the link from my mail client

**Comment by rsudev** [comment]
Today I cross-checked this issue and it seems to be gone. @Lineflyer: Can you confirm?

**Comment by Lineflyer** [comment]
I can also no longer reproduce it, but was there something changed regarding network on main thread?

**Comment by rsudev** [comment]
As this is quite old and there were several changes in the area of login and network access, I assume it was fixed/prevented implicitly and just wanted an independent confirmation.
So I guess we can close this.

**Comment by Bananeweizen** [comment]
@rsudev If you feel like that, just close issues. Don't wait for confirmation. Since everything can be re-opened there is no real problem if something is closed "to early". And you are doing us all a favor with closing an issue. :)
