### ISSUE TITLE
NPE in initBasicMemberPreferences

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4473]
From Google Play store, many versions concerned, including 2014.11.04. Few but regular occurrences. Users write that this happens when they try to log in.

```
rx.exceptions.OnErrorNotImplementedException
   at rx.Observable$26.onError(Observable.java:6678)
   at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:135)
   at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:103)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:118)
   at rx.operators.OperatorConditionalBinding$1.onNext(OperatorConditionalBinding.java:77)
   at rx.internal.operators.NotificationLite.accept(NotificationLite.java:147)
   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:141)
   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:61)
   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$1.call(OperatorObserveOn.java:123)
   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:43)
   at android.os.Handler.handleCallback(Handler.java:615)
   at android.os.Handler.dispatchMessage(Handler.java:92)
   at android.os.Looper.loop(Looper.java:137)
   at android.app.ActivityThread.main(ActivityThread.java:4963)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
   at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
   at cgeo.geocaching.settings.SettingsActivity.initBasicMemberPreferences(SettingsActivity.java:417)
   at cgeo.geocaching.settings.AbstractCheckCredentialsPreference$LoginCheckClickListener$1.call(AbstractCheckCredentialsPreference.java:96)
   at cgeo.geocaching.settings.AbstractCheckCredentialsPreference$LoginCheckClickListener$1.call(AbstractCheckCredentialsPreference.java:82)
   at rx.Observable$26.onNext(Observable.java:6683)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:111)
   ... 15 more
```

**Comment by Lineflyer** [comment]
Still happning in 2015.06.19.

**Comment by Lineflyer** [comment]
```
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
  at android.os.Handler.handleCallback(Handler.java:739)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:145)
  at android.app.ActivityThread.main(ActivityThread.java:5944)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
Caused by: rx.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'void android.preference.Preference.setEnabled(boolean)' on a null object reference
  at rx.Observable$30.onError(Observable.java:7358)
  at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
  at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
  at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:137)
  at rx.internal.operators.OperatorSubscribeOn$1$1$1.onNext(OperatorSubscribeOn.java:76)
  at rx.android.app.OperatorConditionalBinding$1.onNext(OperatorConditionalBinding.java:79)
  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:208)
  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
  ... 8 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.setEnabled(boolean)' on a null object reference
  at cgeo.geocaching.settings.SettingsActivity.initBasicMemberPreferences(SettingsActivity.java:472)
  at cgeo.geocaching.settings.AbstractCheckCredentialsPreference$LoginCheckClickListener$1.call(AbstractCheckCredentialsPreference.java:95)
  at cgeo.geocaching.settings.AbstractCheckCredentialsPreference$LoginCheckClickListener$1.call(AbstractCheckCredentialsPreference.java:81)
  at rx.Observable$30.onNext(Observable.java:7363)
  at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
  ... 13 more
```

**Comment by Lineflyer** [comment]
Not happening recently.
