### ISSUE TITLE
Bad window token in RecaptchaHandler

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4474]
cgeo 2011.11.04

User says that it happened when starting the live map. Others when refreshing a cache.

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@40513d80 is not valid; is your activity running?
   at android.view.ViewRoot.setView(ViewRoot.java:532)
   at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:200)
   at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:114)
   at android.view.Window$LocalWindowManager.addView(Window.java:424)
   at android.app.Dialog.show(Dialog.java:241)
   at cgeo.geocaching.connector.gc.RecaptchaHandler.handleMessage(RecaptchaHandler.java:113)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loop(Looper.java:130)
   at android.app.ActivityThread.main(ActivityThread.java:3687)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:507)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
   at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Lineflyer** [comment]
Opened a new issue for this one for a newer Google Play report, therefore closing this issue.
#5053
