### ISSUE TITLE
NPE: Unable to start activity 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4520]
I am not sure, whether this NPE reported on GooglePlay with version 2014.11.04 has been listed here already.
However it is the most occuring issue on Google Play right now.

Here is one sample stack trace:
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.CacheListActivity}: java.lang.NullPointerException
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2787)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2803)
at android.app.ActivityThread.access$2300(ActivityThread.java:135)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2136)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:144)
at android.app.ActivityThread.main(ActivityThread.java:4937)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at cgeo.geocaching.DataStore$PreparedStatements.getStatement(DataStore.java:2982)
at cgeo.geocaching.DataStore$PreparedStatements.getCountCachesOnStandardList(DataStore.java:2997)
at cgeo.geocaching.DataStore$PreparedStatements.access$1400(DataStore.java:2934)
at cgeo.geocaching.DataStore.getList(DataStore.java:2620)
at cgeo.geocaching.CacheListActivity.onCreateLoader(CacheListActivity.java:1611)
at android.support.v4.app.LoaderManagerImpl.createLoader(LoaderManager.java:490)
at android.support.v4.app.LoaderManagerImpl.createAndInstallLoader(LoaderManager.java:499)
at android.support.v4.app.LoaderManagerImpl.initLoader(LoaderManager.java:553)
at cgeo.geocaching.CacheListActivity.onCreate(CacheListActivity.java:425)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1069)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2751)
... 11 more
```

and another one:
```
ava.lang.RuntimeException: Unable to create application cgeo.geocaching.CgeoApplication: java.lang.NullPointerException
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3286)
at android.app.ActivityThread.access$2200(ActivityThread.java:117)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:980)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3733)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:931)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at cgeo.geocaching.DataStore$PreparedStatements.getStatement(DataStore.java:2968)
at cgeo.geocaching.DataStore$PreparedStatements.getCountCachesOnStandardList(DataStore.java:2983)
at cgeo.geocaching.DataStore$PreparedStatements.access$1700(DataStore.java:2920)
at cgeo.geocaching.DataStore.getLists(DataStore.java:2587)
at cgeo.geocaching.CgeoApplication.onCreate(CgeoApplication.java:75)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3283)
... 10 more
```

Comments vary a bit but often "Crashes on start".

**Comment by Lineflyer** [comment]
This report is outdated and possibly superseeded by #5054
