### ISSUE TITLE
NPE when performing backup

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4557]
From GooglePlay with 2014.12.22:
Device: AlcatelOneTouch 603
Android 4.1

User message: Attempting backup

Stacktrace:
```
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:52)
   at android.os.Handler.handleCallback(Handler.java:615)
   at android.os.Handler.dispatchMessage(Handler.java:92)
   at android.os.Looper.loop(Looper.java:153)
   at android.app.ActivityThread.main(ActivityThread.java:5037)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:821)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
   at dalvik.system.NativeStart.main(Native Method)
Caused by: rx.exceptions.OnErrorNotImplementedException
   at rx.Observable$31.onError(Observable.java:7134)
   at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
   at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
   at rx.internal.operators.NotificationLite.accept(NotificationLite.java:147)
   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:177)
   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:65)
   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:153)
   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
   ... 9 more
Caused by: java.lang.NullPointerException
   at cgeo.geocaching.DataStore$PreparedStatement.clearPreparedStatements(DataStore.java:2954)
   at cgeo.geocaching.DataStore$PreparedStatement.access$000(DataStore.java:2907)
   at cgeo.geocaching.DataStore.closeDb(DataStore.java:371)
   at cgeo.geocaching.DataStore.backupDatabaseInternal(DataStore.java:387)
   at cgeo.geocaching.utils.DatabaseBackupUtils$3.call(DatabaseBackupUtils.java:71)
   at cgeo.geocaching.utils.DatabaseBackupUtils$3.call(DatabaseBackupUtils.java:68)
   at rx.util.async.operators.OperatorFromFunctionals$InvokeAsync.call(OperatorFromFunctionals.java:73)
   at rx.util.async.operators.OperatorFromFunctionals$InvokeAsync.call(OperatorFromFunctionals.java:62)
   at rx.Observable.unsafeSubscribe(Observable.java:7304)
   at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
   at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
   at java.util.concurrent.FutureTask.run(FutureTask.java:137)
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:150)
   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:264)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
   at java.lang.Thread.run(Thread.java:856)
```

**Comment by samueltardieu** [comment]
Another explanation would be if `getStatement()` is called concurrently and, because of the race condition with the nullness test, the same statement is inserted twice into the list. In this case, the first `null` assignment in the loop would have nulled the `statement` field.

Given the concurrent nature of our operations when we load cache information, I think this explanation is at least as likely as the duplicate `clearPreparedStatements()` call. I would rather protect `getStatement` with a lock on the `statements` object if we need to initialize it (so that no two insertions happen at the same time, which might be another problem).
