### ISSUE TITLE
Crash while refreshing list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4569]
This happened sometimes but not reproducibly while testing #4563.
It always happend at or near the end of the refreshing progress:
```
23:37:03.264 Error cgeo 11214  UncaughtException
23:37:03.264 Error cgeo 11214  java.lang.IllegalStateException: The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(16908298, class android.widget.ListView) with Adapter(class android.widget.HeaderViewListAdapter)]
23:37:03.264 Error cgeo 11214  	at android.widget.ListView.layoutChildren(ListView.java:1566)
23:37:03.264 Error cgeo 11214  	at android.widget.AbsListView.onLayout(AbsListView.java:2578)
23:37:03.264 Error cgeo 11214  	at android.view.View.layout(View.java:15745)
23:37:03.264 Error cgeo 11214  	at android.view.ViewGroup.layout(ViewGroup.java:4868)
23:37:03.264 Error cgeo 11214  	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
23:37:03.264 Error cgeo 11214  	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
23:37:03.264 Error cgeo 11214  	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
23:37:03.264 Error cgeo 11214  	at android.view.View.layout(View.java:15745)
23:37:03.264 Error cgeo 11214  	at android.view.ViewGroup.layout(ViewGroup.java:4868)
23:37:03.264 Error cgeo 11214  	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
23:37:03.264 Error cgeo 11214  	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
23:37:03.264 Error cgeo 11214  	at android.view.View.layout(View.java:15745)
23:37:03.264 Error cgeo 11214  	at android.view.ViewGroup.layout(ViewGroup.java:4868)
23:37:03.264 Error cgeo 11214  	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:459)
23:37:03.264 Error cgeo 11214  	at android.view.View.layout(View.java:15745)
23:37:03.264 Error cgeo 11214  	at android.view.ViewGroup.layout(ViewGroup.java:4868)
23:37:03.264 Error cgeo 11214  	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
23:37:03.264 Error cgeo 11214  	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
23:37:03.264 Error cgeo 11214  	at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
23:37:03.264 Error cgeo 11214  	at android.view.View.layout(View.java:15745)
23:37:03.264 Error cgeo 11214  	at android.view.ViewGroup.layout(ViewGroup.java:4868)
23:37:03.264 Error cgeo 11214  	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
23:37:03.264 Error cgeo 11214  	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
23:37:03.264 Error cgeo 11214  	at android.view.View.layout(View.java:15745)
23:37:03.264 Error cgeo 11214  	at android.view.ViewGroup.layout(ViewGroup.java:4868)
23:37:03.264 Error cgeo 11214  	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2338)
23:37:03.264 Error cgeo 11214  	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2051)
23:37:03.264 Error cgeo 11214  	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
23:37:03.264 Error cgeo 11214  	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6602)
23:37:03.264 Error cgeo 11214  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:805)
23:37:03.264 Error cgeo 11214  	at android.view.Choreographer.doCallbacks(Choreographer.java:605)
23:37:03.264 Error cgeo 11214  	at android.view.Choreographer.doFrame(Choreographer.java:575)
23:37:03.264 Error cgeo 11214  	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:791)
23:37:03.264 Error cgeo 11214  	at android.os.Handler.handleCallback(Handler.java:733)
23:37:03.264 Error cgeo 11214  	at android.os.Handler.dispatchMessage(Handler.java:95)
23:37:03.264 Error cgeo 11214  	at android.os.Looper.loop(Looper.java:136)
23:37:03.264 Error cgeo 11214  	at android.app.ActivityThread.main(ActivityThread.java:5476)
23:37:03.264 Error cgeo 11214  	at java.lang.reflect.Method.invokeNative(Native Method)
23:37:03.264 Error cgeo 11214  	at java.lang.reflect.Method.invoke(Method.java:515)
23:37:03.264 Error cgeo 11214  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
23:37:03.264 Error cgeo 11214  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
23:37:03.264 Error cgeo 11214  	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by samueltardieu** [comment]
You can test the fix in 2015.01.02-NB1.
