### ISSUE TITLE
NPE accessing prepared statement

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#4626]
Play report from yesterdays release (2015.01.20):
```
java.lang.RuntimeException: Unable to create application cgeo.geocaching.CgeoApplication: java.lang.NullPointerException
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3414)
at android.app.ActivityThread.access$2200(ActivityThread.java:124)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:985)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:3822)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at cgeo.geocaching.DataStore$PreparedStatement.getStatement(DataStore.java:2994)
at cgeo.geocaching.DataStore$PreparedStatement.simpleQueryForLong(DataStore.java:2986)
at cgeo.geocaching.DataStore.getLists(DataStore.java:2609)
at cgeo.geocaching.CgeoApplication.onCreate(CgeoApplication.java:67)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3411)
... 10 more
```

**Comment by rsudev** [comment]
Will take a look later today.

**Comment by Lineflyer** [comment]
Looking at the PlayConsole I can see, that this also happend in older releases.
Shall we postpone staged release or continue and fix it for the next release?

**Comment by samueltardieu** [comment]
This is a long-running bug probably occurring when the database is corrupted and cannot be opened. This should not affect the release process.

**Comment by Lineflyer** [comment]
This report is outdated and possibly superseeded by #5054
