### ISSUE TITLE
Android geocoder test is not robust

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4627]
From @rsudev:

> First it failed, because the emulator was set to Netherlands(Belgium) and 'Parijs' is not really equal 'Paris' :)
> When I switched to English(US) the streat name didn't fit and when switching to French he suddenly saw the location on 46 rue barrault instead '42'...
> So somewhat unreliable it seems, but the City-level was ok...

**Comment by samueltardieu** [comment]
Don't hesitate to test this with your settings @rsudev.

**Comment by rsudev** [comment]
Today I ran the tests when checking #4637 and still get (english settings):
```
java.lang.AssertionError: [street address for Android .geocoder]
Expecting:
<"46 barrault st">
to contain:
<"rue barrault">
at cgeo.geocaching.location.GeocoderTest.testGeocoder(GeocoderTest.java:64)
at cgeo.geocaching.location.GeocoderTest.testAndroidGeocoder(GeocoderTest.java:34)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at com.google.android.apps.common.testing.testrunner.GoogleInstrumentationTestRunner.onStart(GoogleInstrumentationTestRunner.java:167)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```
Not sure if there is a way around that, as those names generally depend on the device locale, I assume...
