### ISSUE TITLE
NPE on nearby search

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4720]
2015.03.02-NB-b6ed572

- Set global filter to "Event cache"
- Search for Adress "Prag"
- On the result page click on "Load more caches"

Result:
```
15:15:41.056 Error cgeo 26418  [main] UncaughtException
15:15:41.056 Error cgeo 26418  java.lang.NullPointerException
15:15:41.056 Error cgeo 26418  	at cgeo.geocaching.CacheListActivity.onCreateLoader(CacheListActivity.java:1620)
15:15:41.056 Error cgeo 26418  	at android.support.v4.app.LoaderManagerImpl.createLoader(LoaderManager.java:490)
15:15:41.056 Error cgeo 26418  	at android.support.v4.app.LoaderManagerImpl.createAndInstallLoader(LoaderManager.java:499)
15:15:41.056 Error cgeo 26418  	at android.support.v4.app.LoaderManagerImpl.restartLoader(LoaderManager.java:646)
15:15:41.056 Error cgeo 26418  	at cgeo.geocaching.CacheListActivity$MoreCachesListener.onClick(CacheListActivity.java:1295)
15:15:41.056 Error cgeo 26418  	at android.view.View.performClick(View.java:4633)
15:15:41.056 Error cgeo 26418  	at android.view.View$PerformClick.run(View.java:19330)
15:15:41.056 Error cgeo 26418  	at android.os.Handler.handleCallback(Handler.java:733)
15:15:41.056 Error cgeo 26418  	at android.os.Handler.dispatchMessage(Handler.java:95)
15:15:41.056 Error cgeo 26418  	at android.os.Looper.loop(Looper.java:157)
15:15:41.056 Error cgeo 26418  	at android.app.ActivityThread.main(ActivityThread.java:5356)
15:15:41.056 Error cgeo 26418  	at java.lang.reflect.Method.invokeNative(Native Method)
15:15:41.056 Error cgeo 26418  	at java.lang.reflect.Method.invoke(Method.java:515)
15:15:41.056 Error cgeo 26418  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
15:15:41.056 Error cgeo 26418  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
15:15:41.056 Error cgeo 26418  	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Bananeweizen** [comment]
happens only on current master
