### ISSUE TITLE
Picture fails to download due to illegal character

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4743]
2015.03.16-NB1:

- Open GC45ZGY
- In the description a QR code image is missing

Log shows:
```
11:36:11.915 Error cgeo 29287  [network-2] HtmlImage.downloadOrRefreshCopy
11:36:11.915 Error cgeo 29287  java.lang.IllegalArgumentException: Illegal character in query at index 105: http://chart.apis.google.com/chart?cht=qr&chs=200x200&chl=http%3A//ruhrsteig.ohrenbaer.bplaced.net&chld=H|0
11:36:11.915 Error cgeo 29287  	at java.net.URI.create(URI.java:727)
11:36:11.915 Error cgeo 29287  	at ch.boye.httpclientandroidlib.client.methods.HttpGet.<init>(HttpGet.java:69)
11:36:11.915 Error cgeo 29287  	at cgeo.geocaching.network.Network.request(Network.java:180)
11:36:11.915 Error cgeo 29287  	at cgeo.geocaching.network.Network.getRequest(Network.java:288)
11:36:11.915 Error cgeo 29287  	at cgeo.geocaching.network.HtmlImage.downloadOrRefreshCopy(HtmlImage.java:312)
11:36:11.915 Error cgeo 29287  	at cgeo.geocaching.network.HtmlImage.access$700(HtmlImage.java:54)
11:36:11.915 Error cgeo 29287  	at cgeo.geocaching.network.HtmlImage$4.downloadAndSave(HtmlImage.java:258)
11:36:11.915 Error cgeo 29287  	at cgeo.geocaching.network.HtmlImage$4.access$500(HtmlImage.java:217)
11:36:11.915 Error cgeo 29287  	at cgeo.geocaching.network.HtmlImage$4$1$1.call(HtmlImage.java:236)
11:36:11.915 Error cgeo 29287  	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
11:36:11.915 Error cgeo 29287  	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
11:36:11.915 Error cgeo 29287  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11:36:11.915 Error cgeo 29287  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11:36:11.915 Error cgeo 29287  	at java.lang.Thread.run(Thread.java:841)
```

**Comment by samueltardieu** [comment]
The error is in the cache description web page. The URL shown as

    http://chart.apis.google.com/chart?cht=qr&chs=200x200&chl=http%3A//ruhrsteig.ohrenbaer.bplaced.net&chld=H|0

should be shown as

    http://chart.apis.google.com/chart?cht=qr&chs=200x200&chl=http%3A//ruhrsteig.ohrenbaer.bplaced.net&chld=H%7C0

(`%7C` should be used instead of `|` in the URI component)

Ideally, that should be fixed at the cache owner level.

**Comment by Lineflyer** [comment]
@samueltardieu So, No Fix or work around?

**Comment by samueltardieu** [comment]
Well, a fix would need quite a lot of testing as we would take the risk of transforming valid URLs into non-equivalent ones. Better would be to ask the cache owner to fix the link.

**Comment by Lineflyer** [comment]
Yes, closing.
