### ISSUE TITLE
getUrl cannot be called on unknown trackables

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#4746]
From Google Play with 2015.03.12 and earlier 2015 versions.
```
java.lang.IllegalStateException: getUrl cannot be called on unknown trackables
   at cgeo.geocaching.connector.trackable.UnknownTrackableConnector.getUrl(UnknownTrackableConnector.java:17)
   at cgeo.geocaching.Trackable.getUrl(Trackable.java:47)
   at cgeo.geocaching.TrackableActivity.onPrepareOptionsMenu(TrackableActivity.java:232)
   at android.app.Activity.onPreparePanel(Activity.java:2596)
   at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:491)
   at android.support.v7.app.ActionBarActivity.superOnPrepareOptionsPanel(ActionBarActivity.java:240)
   at android.support.v7.app.ActionBarActivityDelegate.onPrepareOptionsPanel(ActionBarActivityDelegate.java:157)
   at android.support.v7.app.ActionBarActivity.onPrepareOptionsPanel(ActionBarActivity.java:212)
   at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:480)
   at android.support.v7.app.ActionBarActivity.superOnPreparePanel(ActionBarActivity.java:236)
   at android.support.v7.app.ActionBarActivityDelegateICS.onPreparePanel(ActionBarActivityDelegateICS.java:154)
   at android.support.v7.app.ActionBarActivity.onPreparePanel(ActionBarActivity.java:204)
   at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.onPreparePanel(ActionBarActivityDelegateICS.java:298)
   at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:535)
   at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:934)
   at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:292)
   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:791)
   at android.view.Choreographer.doCallbacks(Choreographer.java:591)
   at android.view.Choreographer.doFrame(Choreographer.java:560)
   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:777)
   at android.os.Handler.handleCallback(Handler.java:730)
   at android.os.Handler.dispatchMessage(Handler.java:92)
   at android.os.Looper.loop(Looper.java:176)
   at android.app.ActivityThread.main(ActivityThread.java:5419)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:525)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
   at dalvik.system.NativeStart.main(Native Method)
```

**Comment by samueltardieu** [comment]
@Lineflyer We could merge this into `release` if no ill effect is seen on `master`. Given that we will have a testing period on `release`, you might want to merge this even sooner.

**Comment by samueltardieu** [comment]
Merging into release for RC testing.
