### ISSUE TITLE
Find count for gc.com not working

### ISSUE THREAD

**Issue by Bugsy1905** [cgeo/cgeo#4761]
Just noticed that when logging in the total caches found shows 0 - not what you have achieved.
Not sure if Geocaching.com have updated something and causing an error on the app.

**Comment by Lineflyer** [comment]
This is most probably due to the recent website change.
I can confirm with current NB and current RC.

**Comment by rsudev** [comment]
Geocaching.com has changed and we are already working on that. Thanks for the report.

**Comment by Lineflyer** [comment]
This CI-failure seems to have the same reason:
```
08:30:16       [exec] Error in testCacheCountOnline:
08:30:16       [exec] java.lang.AssertionError: 
08:30:16       [exec] Expecting:
08:30:16       [exec]  <false>
08:30:16       [exec] to be equal to:
08:30:16       [exec]  <true>
08:30:16       [exec] but was not.
08:30:16       [exec] 	at cgeo.geocaching.connector.gc.GCConstantsTest.testCacheCountOnline(GCConstantsTest.java:53)
08:30:16       [exec] 	at java.lang.reflect.Method.invokeNative(Native Method)
08:30:16       [exec] 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
08:30:16       [exec] 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
08:30:16       [exec] 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
08:30:16       [exec] 	at com.google.android.apps.common.testing.testrunner.GoogleInstrumentationTestRunner.onStart(GoogleInstrumentationTestRunner.java:167)
08:30:16       [exec] 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
08:30:16       [exec] ...
```

**Comment by rsudev** [comment]
This is relatively easy to fix, a small pattern change and it should work again.

**Comment by basti2k** [comment]
Unfortunately, again broken. Geocaching has again changed something on the side.
