### ISSUE TITLE
Membership detection not working

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4763]
Reason ist most probably recent changes on the website
```
08:28:24       [exec] cgeo.geocaching.SettingsTest:.
08:28:24       [exec] Error in testSettings:
08:28:24       [exec] java.lang.AssertionError: 
08:28:24       [exec] Expecting:
08:28:24       [exec]  <false>
08:28:24       [exec] to be equal to:
08:28:24       [exec]  <true>
08:28:24       [exec] but was not.
08:28:24       [exec] 	at cgeo.geocaching.SettingsTest.testSettings(SettingsTest.java:29)
08:28:24       [exec] 	at java.lang.reflect.Method.invokeNative(Native Method)
08:28:24       [exec] 	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
08:28:24       [exec] 	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
08:28:24       [exec] 	at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
08:28:24       [exec] 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
08:28:24       [exec] 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
08:28:24       [exec] 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
08:28:24       [exec] 	at com.google.android.apps.common.testing.testrunner.GoogleInstrumentationTestRunner.onStart(GoogleInstrumentationTestRunner.java:167)
08:28:24       [exec] 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
08:28:24       [exec] .
```

**Comment by Lineflyer** [comment]
In fact it seems #4762 can be caused by this as we seem to fail detecting premium membership here:
```
 assertThat(Settings.isGCPremiumMember()).isTrue();
```
This means we possibly don't request a loc.file as we identify the user as basic member.
We may need to confirm this by logging the activities.

**Comment by Lineflyer** [comment]
Confirmed in debug log:
- Login is working in general
- Switch to english is working
- Homezone and date detection seems ok

but membership status is empty:
```
14:09:13.788 Debug cgeo 18593  [network-2] GET https://www.geocaching.com/login/default.aspx
14:09:14.893 Debug cgeo 18593  [network-2] 200 (1162 ms) GET https://www.geocaching.com/login/default.aspx
14:09:14.893 Info cgeo 18593  [network-2] Already logged in Geocaching.com as Lineflyer ()
```

**Comment by rsudev** [comment]
This is a little more complex, it seems. AFAICS does the page normally no longer state your 'status', but mostly (not on the map) show an 'Upgrade' button for BM.

**Comment by Lineflyer** [comment]
We could also request https://www.geocaching.com/account/settings/membership.

**Comment by rsudev** [comment]
Currently we try to get the finds and membership status from all pages 'in passing by' AFAIK. This is an area where I have little experience, so some more research is necessary.
