### ISSUE TITLE
Showcase in compass is missing the circle

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4772]
2015.03.27-RC1

![](http://imgur.com/lrwlmjy.png)

**Comment by Lineflyer** [comment]
I am quite sure it worked on the first try.
Afterwards I reset c:geo to defaults (delete all app data) and tried again. Other showcases are OK, but the compass showcase looks like posted above.

**Comment by Lineflyer** [comment]
Reboot solved the problem for me. Strange.
So nevermind to release without analyzing this.

**Comment by Lineflyer** [comment]
Addition:
It seems to happen if I did not access any settings before starting the compass.
(So I am able to reproduce that the problem shows up when I don't store any login information and continue to the compass directly after starting a fresh installation).

Here is the debug log:
```
10:46:16.210 Error cgeo 17091  Couldn't create showcase view
10:46:16.210 Error cgeo 17091  java.lang.NullPointerException
10:46:16.210 Error cgeo 17091  	at com.github.amlcurran.showcaseview.targets.ActionBarViewWrapper.getActionItem(ActionBarViewWrapper.java:129)
10:46:16.210 Error cgeo 17091  	at com.github.amlcurran.showcaseview.targets.ActionItemTarget.getPoint(ActionItemTarget.java:44)
10:46:16.210 Error cgeo 17091  	at com.github.amlcurran.showcaseview.ShowcaseView$1.run(ShowcaseView.java:166)
10:46:16.210 Error cgeo 17091  	at android.os.Handler.handleCallback(Handler.java:733)
10:46:16.210 Error cgeo 17091  	at android.os.Handler.dispatchMessage(Handler.java:95)
10:46:16.210 Error cgeo 17091  	at android.os.Looper.loop(Looper.java:157)
10:46:16.210 Error cgeo 17091  	at android.app.ActivityThread.main(ActivityThread.java:5356)
10:46:16.210 Error cgeo 17091  	at java.lang.reflect.Method.invokeNative(Native Method)
10:46:16.210 Error cgeo 17091  	at java.lang.reflect.Method.invoke(Method.java:515)
10:46:16.210 Error cgeo 17091  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
10:46:16.210 Error cgeo 17091  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
10:46:16.210 Error cgeo 17091  	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Lineflyer** [comment]
Showcase has been removed
