### ISSUE TITLE
Geokrety image loading failed

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4777]
2015.03.28-NB1:

- Open GKA301
- Image is not shown

Log:
```
00:07:35.644 Debug cgeo 17545  [network-10] GeokretyConnector.searchTrackable: gkid=41729
00:07:35.644 Debug cgeo 17545  [network-10] GET http://geokretymap.org/export-details.php?gkid=41729
00:07:36.764 Debug cgeo 17545  [network-10] 200 (1027 ms) GET http://geokretymap.org/export-details.php?gkid=41729
00:07:36.894 Error cgeo 17545  [network-6] HtmlImage.downloadOrRefreshCopy
00:07:36.894 Error cgeo 17545  java.lang.IllegalArgumentException: Illegal character in path at index 28: http://geokrety.org/obrazki/
00:07:36.894 Error cgeo 17545  	at java.net.URI.create(URI.java:727)
00:07:36.894 Error cgeo 17545  	at ch.boye.httpclientandroidlib.client.methods.HttpGet.<init>(HttpGet.java:69)
00:07:36.894 Error cgeo 17545  	at cgeo.geocaching.network.Network.request(Network.java:180)
00:07:36.894 Error cgeo 17545  	at cgeo.geocaching.network.Network.getRequest(Network.java:288)
00:07:36.894 Error cgeo 17545  	at cgeo.geocaching.network.HtmlImage.downloadOrRefreshCopy(HtmlImage.java:312)
00:07:36.894 Error cgeo 17545  	at cgeo.geocaching.network.HtmlImage.access$700(HtmlImage.java:54)
00:07:36.894 Error cgeo 17545  	at cgeo.geocaching.network.HtmlImage$4.downloadAndSave(HtmlImage.java:258)
00:07:36.894 Error cgeo 17545  	at cgeo.geocaching.network.HtmlImage$4.access$500(HtmlImage.java:217)
00:07:36.894 Error cgeo 17545  	at cgeo.geocaching.network.HtmlImage$4$1$1.call(HtmlImage.java:236)
00:07:36.894 Error cgeo 17545  	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
00:07:36.894 Error cgeo 17545  	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
00:07:36.894 Error cgeo 17545  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
00:07:36.894 Error cgeo 17545  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
00:07:36.894 Error cgeo 17545  	at java.lang.Thread.run(Thread.java:841)
00:07:37.914 Debug cgeo 17545  [looper callbacks] LocationProvider: stopping location requests
```

**Comment by kumy** [comment]
PR #4799
