### ISSUE TITLE
NPE when trying to open OC cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4798]
2015.03.29-NB2:

- Enter OC10E19 in the search bar
- c:geo returns that the cache can not be found (but it exists)

Log:
```
22:18:48.011 Debug cgeo 31489  [network-8] Saving OC10E19 GK Hotel "Zum Froschkonzert" (0) to DB
22:18:48.011 Error cgeo 31489  [network-8] SaveCache
22:18:48.011 Error cgeo 31489  java.lang.NullPointerException
22:18:48.011 Error cgeo 31489  	at cgeo.geocaching.Trackable.getReleased(Trackable.java:145)
22:18:48.011 Error cgeo 31489  	at cgeo.geocaching.DataStore.saveInventoryWithoutTransaction(DataStore.java:1516)
22:18:48.011 Error cgeo 31489  	at cgeo.geocaching.DataStore.storeIntoDatabase(DataStore.java:1194)
22:18:48.011 Error cgeo 31489  	at cgeo.geocaching.DataStore.saveCaches(DataStore.java:1124)
22:18:48.011 Error cgeo 31489  	at cgeo.geocaching.DataStore.saveCache(DataStore.java:1066)
22:18:48.011 Error cgeo 31489  	at cgeo.geocaching.connector.oc.OkapiClient.parseCache(OkapiClient.java:415)
22:18:48.011 Error cgeo 31489  	at cgeo.geocaching.connector.oc.OkapiClient.getCache(OkapiClient.java:165)
22:18:48.011 Error cgeo 31489  	at cgeo.geocaching.connector.oc.OCApiConnector.searchByGeocode(OCApiConnector.java:59)
22:18:48.011 Error cgeo 31489  	at cgeo.geocaching.Geocache.searchByGeocode(Geocache.java:1624)
22:18:48.011 Error cgeo 31489  	at cgeo.geocaching.CacheDetailActivity$2.call(CacheDetailActivity.java:334)
22:18:48.011 Error cgeo 31489  	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
22:18:48.011 Error cgeo 31489  	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
22:18:48.011 Error cgeo 31489  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
22:18:48.011 Error cgeo 31489  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
22:18:48.011 Error cgeo 31489  	at java.lang.Thread.run(Thread.java:841)
22:18:48.011 Debug cgeo 31489  [ModernAsyncTask #5] 200 (423 ms) GET http://geokrety.org/export2.php?wpt=OC10E19
22:18:48.121 Debug cgeo 31489  [main] DataStore.loadCaches([OC10E19]) returned no results
```

**Comment by kumy** [comment]
Ha... Seen that too when tried to reproduce #4781.

**Comment by Bananeweizen** [comment]
my fault, from the bugfix cleanups. didn't handle null.
