### ISSUE TITLE
NumberFormatException on loading GK

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4805]
2015.03.30-NB1:

- Open GKC241
- Gk is shown but log contains a NumberFormatException

```
22:23:20.651 Debug cgeo 28799  [network-6] GeokretyConnector.searchTrackable: gkid=49729
22:23:20.651 Debug cgeo 28799  [network-6] GET http://geokretymap.org/export-details.php?gkid=49729
22:23:22.851 Debug cgeo 28799  [network-6] 200 (2196 ms) GET http://geokretymap.org/export-details.php?gkid=49729
22:23:22.851 Debug cgeo 28799  [looper callbacks] LocationProvider: stopping location requests
22:23:22.851 Error cgeo 28799  [network-6] Parsing geokret
22:23:22.851 Error cgeo 28799  java.lang.NumberFormatException: Invalid int: ""
22:23:22.851 Error cgeo 28799  	at java.lang.Integer.invalidInt(Integer.java:137)
22:23:22.851 Error cgeo 28799  	at java.lang.Integer.parseInt(Integer.java:358)
22:23:22.851 Error cgeo 28799  	at java.lang.Integer.parseInt(Integer.java:331)
22:23:22.851 Error cgeo 28799  	at cgeo.geocaching.connector.trackable.GeokretyParser$GeokretyHandler.endElement(GeokretyParser.java:139)
22:23:22.852 Error cgeo 28799  	at org.apache.harmony.xml.ExpatParser.endElement(ExpatParser.java:156)
22:23:22.852 Error cgeo 28799  	at org.apache.harmony.xml.ExpatParser.appendBytes(Native Method)
22:23:22.852 Error cgeo 28799  	at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:513)
22:23:22.852 Error cgeo 28799  	at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:474)
22:23:22.852 Error cgeo 28799  	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:316)
22:23:22.852 Error cgeo 28799  	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:279)
22:23:22.852 Error cgeo 28799  	at cgeo.geocaching.connector.trackable.GeokretyParser.parse(GeokretyParser.java:172)
22:23:22.852 Error cgeo 28799  	at cgeo.geocaching.connector.trackable.GeokretyConnector.searchTrackable(GeokretyConnector.java:77)
22:23:22.852 Error cgeo 28799  	at cgeo.geocaching.connector.trackable.GeokretyConnector.searchTrackable(GeokretyConnector.java:58)
22:23:22.852 Error cgeo 28799  	at cgeo.geocaching.TrackableActivity$3.call(TrackableActivity.java:234)
22:23:22.852 Error cgeo 28799  	at cgeo.geocaching.TrackableActivity$3.call(TrackableActivity.java:227)
22:23:22.852 Error cgeo 28799  	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:44)
22:23:22.852 Error cgeo 28799  	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:33)
22:23:22.853 Error cgeo 28799  	at rx.Observable.unsafeSubscribe(Observable.java:7495)
22:23:22.853 Error cgeo 28799  	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
22:23:22.853 Error cgeo 28799  	at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
22:23:22.853 Error cgeo 28799  	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
22:23:22.853 Error cgeo 28799  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
22:23:22.853 Error cgeo 28799  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
22:23:22.853 Error cgeo 28799  	at java.lang.Thread.run(Thread.java:841)
```

**Comment by kumy** [comment]
This Kret has never traveled.
It hasn't any location...

Have to check if empty/null "spotted type" has an impact...

http://geokrety.org/konkret.php?id=49729

**Comment by kumy** [comment]
PR #4808

**Comment by Lineflyer** [comment]
Tested and working now with 2015.03.31-NB2
