### ISSUE TITLE
NPE on compass

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4820]
From Google Play with version 2015.03.28 (not sure if maybe 6165ec4f26ba5860c5e3da2913bf6accc49d199e fixed that already)

User comment:
the new hint feature shuts down the app before I can go from the compass the the map

Stack trace:
```
java.lang.NullPointerException
   at cgeo.geocaching.CompassActivity.onOptionsItemSelected(CompassActivity.java:217)
   at android.app.Activity.onMenuItemSelected(Activity.java:2250)
   at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:372)
   at android.support.v7.app.ActionBarActivity.superOnMenuItemSelected(ActionBarActivity.java:244)
   at android.support.v7.app.ActionBarActivityDelegateBase.onMenuItemSelected(ActionBarActivityDelegateBase.java:352)
   at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:130)
   at android.support.v7.app.ActionBarActivityDelegateBase.onMenuItemSelected(ActionBarActivityDelegateBase.java:357)
   at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:777)
   at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
   at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:922)
   at android.support.v7.internal.view.menu.ActionMenuView.invokeItem(ActionMenuView.java:544)
   at android.support.v7.internal.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:105)
   at android.view.View.performClick(View.java:2532)
   at android.view.View$PerformClick.run(View.java:9277)
   at android.os.Handler.handleCallback(Handler.java:587)
   at android.os.Handler.dispatchMessage(Handler.java:92)
   at android.os.Looper.loop(Looper.java:143)
   at android.app.ActivityThread.main(ActivityThread.java:4196)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:507)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
   at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Lineflyer** [comment]
A slightly different report (looks a bit like there is a NPE when trying to set the compass target):

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.CompassActivity}: java.lang.NullPointerException
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2305)
   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2363)
   at android.app.ActivityThread.access$900(ActivityThread.java:161)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1265)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:157)
   at android.app.ActivityThread.main(ActivityThread.java:5356)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:515)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
   at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
   at cgeo.geocaching.CompassActivity.setTarget(CompassActivity.java:255)
   at cgeo.geocaching.CompassActivity.onCreate(CompassActivity.java:96)
   at android.app.Activity.performCreate(Activity.java:5426)
   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2269)
... 11 more
```

**Comment by Bananeweizen** [comment]
The first one is fixed with the commit you mentioned.

**Comment by Lineflyer** [comment]
No longer appearing in the Google Play reports of newer release.
