### ISSUE TITLE
crash on navigate to android wear

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#4829]
A user on geoclub.de highlighted an issue, were he got a crash when navigating with Wear under Android 5.0.
Report from March, 31st, 23:14.
Here is the stacktrace:
```
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=cgeo.geocaching.wear.NAVIGATE_TO (has extras) }
at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1786)
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1815)
at android.app.ContextImpl.startService(ContextImpl.java:1799)
at android.content.ContextWrapper.startService(ContextWrapper.java:515)
at cgeo.geocaching.apps.cache.navi.AndroidWearApp.navigate(AndroidWearApp.java:50)
at cgeo.geocaching.apps.cache.navi.AndroidWearApp.navigate(AndroidWearApp.java:35)
at cgeo.geocaching.apps.cache.navi.NavigationSelectionActionProvider$1.onMenuItemClick(NavigationSelectionActionProvider.java:49)
at android.support.v7.internal.view.menu.MenuItemWrapperICS$OnMenuItemClickListenerWrapper.onMenuItemClick(MenuItemWrapperICS.java:370)
at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:147)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:897)
at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:887)
at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:179)
at android.widget.AdapterView.performItemClick(AdapterView.java:300)
at android.widget.AbsListView.performItemClick(AbsListView.java:1247)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3215)
at android.widget.AbsListView$3.run(AbsListView.java:4009)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:155)
at android.app.ActivityThread.main(ActivityThread.java:5696)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
```

**Comment by rsudev** [comment]
Does anybody have a Lollipop device to test this? I am not sure if you need a wear device in order to see the crash.

**Comment by Lineflyer** [comment]
I have Android wear but no Lollipop yet.

**Comment by rsudev** [comment]
Fix based on release, merged for test first to master. Re-opening for test.

**Comment by tomw2005** [comment]
This issues still exists on Nexus 5 & LG G Watch R with Lollipop. What help can I provide for testing?

**Comment by SammysHP** [comment]
Which version? Latest nightly?

**Comment by tomw2005** [comment]
I'm not currently testing the nightly. I noticed the issue on the latest version from the Google Play store. When I saw this I figured I'd offer to test as I'm interested in the feature.

**Comment by SammysHP** [comment]
Well, it is not yet fixed in the release (there was no release after this fix).

**Comment by tomw2005** [comment]
What do I need to do to help test the nightly? I am very keen to see this functionality working on my watch.

**Comment by SammysHP** [comment]
Simply install the nightly build: http://www.cgeo.org/c-geo-nightly.apk

**Comment by tomw2005** [comment]
Ok. Initial test (sat down at desk) It works on the watch without crashing. All buttons in the Wear app work fine without crashing. The directions however do not appear to be accurate (pointing East instead of North) that being said I am currently inside and will have to try a full test later (there's a cache near home I know well).

I did calibrate my compass on the watch earlier but not sure if that can be overwritten by different watch faces.

**Comment by SammysHP** [comment]
We're not developer of the Wear app, we only hand the data over the it.

**Comment by tomw2005** [comment]
Well in that case the nightly works with a Nexus 5 running Lollipop (5.1.0) and an LG G Watch R running Lollipop (5.0.2) :)

**Comment by Lineflyer** [comment]
@tomw2005 Please have a look here for current issues with respect to the LG G Watch R internal compass:https://github.com/culmor30/cgeo-wear/issues/13

But your comment above shows that the crash (which is the issue here) has been solved. so @sudev could merge it to release.

**Comment by rsudev** [comment]
merged into release, closing.
