### ISSUE TITLE
NPE when starting map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4848]
With 2015.04.06-NB I have the following problem (only on my tablet device, smartphone OK):
Whereever I start a map activity I get a NPE.

The following is an example of Cache Details -> Navigate -> Map

Log:
```
22:25:22.156 Error cgeo 489  [main] UncaughtException
22:25:22.156 Error cgeo 489  java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.maps.google.v1.GoogleMapActivity}: java.lang.NullPointerException
22:25:22.156 Error cgeo 489  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2328)
22:25:22.156 Error cgeo 489  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2386)
22:25:22.156 Error cgeo 489  	at android.app.ActivityThread.access$900(ActivityThread.java:169)
22:25:22.156 Error cgeo 489  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1277)
22:25:22.156 Error cgeo 489  	at android.os.Handler.dispatchMessage(Handler.java:102)
22:25:22.156 Error cgeo 489  	at android.os.Looper.loop(Looper.java:136)
22:25:22.156 Error cgeo 489  	at android.app.ActivityThread.main(ActivityThread.java:5476)
22:25:22.156 Error cgeo 489  	at java.lang.reflect.Method.invokeNative(Native Method)
22:25:22.156 Error cgeo 489  	at java.lang.reflect.Method.invoke(Method.java:515)
22:25:22.156 Error cgeo 489  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
22:25:22.156 Error cgeo 489  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
22:25:22.156 Error cgeo 489  	at dalvik.system.NativeStart.main(Native Method)
22:25:22.156 Error cgeo 489  Caused by: java.lang.NullPointerException
22:25:22.156 Error cgeo 489  	at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.size(GoogleCacheOverlay.java:48)
22:25:22.156 Error cgeo 489  	at com.google.android.maps.ItemizedOverlay.populate(ItemizedOverlay.java:298)
22:25:22.156 Error cgeo 489  	at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.superPopulate(GoogleCacheOverlay.java:68)
22:25:22.156 Error cgeo 489  	at cgeo.geocaching.maps.AbstractItemizedOverlay.populate(AbstractItemizedOverlay.java:27)
22:25:22.156 Error cgeo 489  	at cgeo.geocaching.maps.CachesOverlay.<init>(CachesOverlay.java:55)
22:25:22.156 Error cgeo 489  	at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.<init>(GoogleCacheOverlay.java:33)
22:25:22.156 Error cgeo 489  	at cgeo.geocaching.maps.google.v1.GoogleMapView.createAddMapOverlay(GoogleMapView.java:124)
22:25:22.156 Error cgeo 489  	at cgeo.geocaching.maps.CGeoMap.onCreate(CGeoMap.java:509)
22:25:22.156 Error cgeo 489  	at cgeo.geocaching.maps.google.v1.GoogleMapActivity.onCreate(GoogleMapActivity.java:37)
22:25:22.156 Error cgeo 489  	at android.app.Activity.performCreate(Activity.java:5473)
22:25:22.156 Error cgeo 489  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
22:25:22.156 Error cgeo 489  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2292)
22:25:22.156 Error cgeo 489  	... 11 more
```

**Comment by Lineflyer** [comment]
Ok.
2015.04.05-NB is working, but 2015.04.06-NB is not on this device:
```
--- System information ---
Device: SM-P600 (lt03wifixx, samsung)
Android version: 4.4.2
Android build: KOT49H.P600XXUCNH3
Cgeo version: 2015.04.06-NB-d0198c7
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: absent
Orientation sensor: present
Hide own/found: true
Map strategy: auto
HW-acceleration: enabled (default state)
Geocaching sites enabled:
- geocaching.com: logged in (Login OK) / Premium
- opencaching.de: logged in (Login OK)
System language: de_DE
Installed cgeo plugins: calendar contacts
--- End of system information ---
```

**Comment by Lineflyer** [comment]
Also reports from FB.
It is obviously not connected to the device but only appears if google maps are used. My smartphone uses OSM and was therefore not affected.

**Comment by Bananeweizen** [comment]
My fault, I trusted the static code analysis about a member never being null. But this member is already accessed while the constructor is not yet finished.
