### ISSUE TITLE
rx.exceptions.OnErrorNotImplementedException

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4866]
From Google Play reports with 2015.03.31:

User message: crashes when trying to refresh geocaches. android 4.2.2

13 occurences

Is this really a disk full problem, because I am wondering why RX is having this issue?

```
rx.exceptions.OnErrorNotImplementedException: database or disk is full (code 13)
at rx.Observable$32.onError(Observable.java:7322)
at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:137)
at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:224)
at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
at rx.subjects.ReplaySubject$UnboundedReplayState.accept(ReplaySubject.java:466)
at rx.subjects.ReplaySubject$UnboundedReplayState.replayObserverFromIndex(ReplaySubject.java:515)
at rx.subjects.ReplaySubject$UnboundedReplayState.replayObserver(ReplaySubject.java:503)
at rx.subjects.ReplaySubject.caughtUp(ReplaySubject.java:423)
at rx.subjects.ReplaySubject.onNext(ReplaySubject.java:369)
at rx.Observable$35.onNext(Observable.java:7468)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
at rx.internal.operators.OperatorZip$Zip.tick(OperatorZip.java:263)
at rx.internal.operators.OperatorZip$Zip$InnerSubscriber.onNext(OperatorZip.java:334)
at rx.internal.operators.OperatorToObservableList$1.onCompleted(OperatorToObservableList.java:84)
at rx.internal.operators.OperatorSubscribeOn$1$1$1.onCompleted(OperatorSubscribeOn.java:66)
at cgeo.geocaching.connector.gc.GCParser$4.call(GCParser.java:1767)
at cgeo.geocaching.connector.gc.GCParser$4.call(GCParser.java:1715)
at rx.Observable.unsafeSubscribe(Observable.java:7495)
at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:49)
at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:33)
at rx.Observable.unsafeSubscribe(Observable.java:7495)
at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: android.database.sqlite.SQLiteFullException: database or disk is full (code 13)
at android.database.sqlite.SQLiteConnection.nativeExecute(Native Method)
at android.database.sqlite.SQLiteConnection.execute(SQLiteConnection.java:559)
at android.database.sqlite.SQLiteSession.endTransactionUnchecked(SQLiteSession.java:437)
at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:401)
at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:537)
at cgeo.geocaching.DataStore.saveLogs(DataStore.java:1430)
at cgeo.geocaching.connector.gc.GCParser$6.call(GCParser.java:1886)
at cgeo.geocaching.connector.gc.GCParser$6.call(GCParser.java:1883)
at rx.Observable$32.onNext(Observable.java:7327)
at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
... 25 more
Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: [Ljava.lang.Object;.class
at rx.internal.operators.OperatorZip$Zip.tick(OperatorZip.java:268)
... 15 more
```

**Comment by samueltardieu** [comment]
RxJava shows up only because the operation was done in the background in an observable, but the exception is really a disk full error. I think we can close this one, there is nothing we can do about it.

**Comment by Lineflyer** [comment]
Ah OK.
Closing.

**Comment by mucek4** [comment]
13 occurences? Are they from same user? If it says same version and device it could be it. Maybe we could check that and report to user somehow?
