### ISSUE TITLE
OOM crash on Android 5.0+ only

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4868]
Looking at the PlayStore this error seems to be limited to Android 5.0+ and not related to the known mapsforge OOM issue.

2015.03.31 and 2015.03.28.

User messages:
stopped when I tried to store
app always crashing, not sure what's going on usually very reliable.
Bei der kartenansicht stürzt die App laufend ab.

```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:145)
   at android.app.ActivityThread.main(ActivityThread.java:5832)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 4665612 byte allocation with 1016073 free bytes and 992KB until OOM
   at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
   at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
   at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:767)
   at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:743)
   at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:477)
   at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:515)
   at cgeo.geocaching.StaticMapsProvider.decodeFile(StaticMapsProvider.java:330)
   at cgeo.geocaching.StaticMapsProvider.getPreviewMap(StaticMapsProvider.java:314)
   at cgeo.geocaching.CacheDetailActivity$8.call(CacheDetailActivity.java:1283)
   at cgeo.geocaching.CacheDetailActivity$8.call(CacheDetailActivity.java:1273)
   at rx.Observable$1.call(Observable.java:144)
   at rx.Observable$1.call(Observable.java:136) 
   at rx.Observable$1.call(Observable.java:144)
   at rx.Observable$1.call(Observable.java:136)
   at rx.Observable.unsafeSubscribe(Observable.java:7495)
   at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
   at rx.schedulers.ExecutorScheduler$ExecutorAction.run(ExecutorScheduler.java:173)
   at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:99)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
   at java.lang.Thread.run(Thread.java:818)
```

**Comment by SammysHP** [comment]
```
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 4665612 byte allocation with 1016073 free bytes and 992KB until OOM
   at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
   at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
```

OOM while decoding static map image. Mapsforge already uses much memory, the additional memory for static map processing is too much.

We should use the latest Mapsforge version, I think it will use less memory.

**Comment by Lineflyer** [comment]
> OOM while decoding static map image. Mapsforge already uses much memory, the additional memory for static map processing is too much.

Do you think it could be so easy?
I do not realize any procedure of how to laod statismaps while mapsforge is running...or am I wrong.
I am just wondering that this occurence seems limited to 5.0+ up to now.

**Comment by SammysHP** [comment]
Live Map → popup → store cache → OOM.

**Comment by Lineflyer** [comment]
Continued in #4922.
