### ISSUE TITLE
ConcurrentModificationException on map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4869]
2015.03.31 from GooglePlay.

```
java.util.ConcurrentModificationException
   at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:350)
   at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:370)
   at java.util.AbstractCollection.toArray(AbstractCollection.java:343)
   at java.util.ArrayList.<init>(ArrayList.java:93)
   at cgeo.geocaching.maps.CGeoMap.getSingleModeCache(CGeoMap.java:269)
   at cgeo.geocaching.maps.CGeoMap.calculateTitle(CGeoMap.java:258)
   at cgeo.geocaching.maps.CGeoMap.setTitle(CGeoMap.java:241)
   at cgeo.geocaching.maps.CGeoMap.access$000(CGeoMap.java:103)
   at cgeo.geocaching.maps.CGeoMap$DisplayHandler.handleMessage(CGeoMap.java:223)
   at android.os.Handler.dispatchMessage(Handler.java:99)
   at android.os.Looper.loop(Looper.java:137)
   at android.app.ActivityThread.main(ActivityThread.java:4921)
   at java.lang.reflect.Method.invokeNative(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:511)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
   at dalvik.system.NativeStart.main(Native Method)
```

Link to #3569?

**Comment by Lineflyer** [comment]
No longer appearing since some months in the Google Play reports.
Possibily implicitly fixed with the fix for #3569.
