### ISSUE TITLE
Error in testSearchTrackables

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4871]
This looks like a "real" failure on CI:
```
12:53:00       [exec] Error in testSearchTrackables:
12:53:00       [exec] java.lang.AssertionError: 
12:53:00       [exec] Expected size:<2> but was:<0> in:
12:53:00       [exec] <[]>
12:53:00       [exec] 	at cgeo.geocaching.connector.trackable.GeokretyConnectorTest.testSearchTrackables(GeokretyConnectorTest.java:63)
12:53:00       [exec] 	at java.lang.reflect.Method.invokeNative(Native Method)
12:53:00       [exec] 	at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
12:53:00       [exec] 	at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
12:53:00       [exec] 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
12:53:00       [exec] 	at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
12:53:00       [exec] 	at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
12:53:00       [exec] 	at com.google.android.apps.common.testing.testrunner.GoogleInstrumentationTestRunner.onStart(GoogleInstrumentationTestRunner.java:167)
12:53:00       [exec] 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
12:53:00       [exec] 
```

**Comment by kumy** [comment]
Not a problem with c:geo code.

Problem was on GKM side.
GKM, would need some unit test on his own.
We'll do later with the new server...
