### ISSUE TITLE
GeokretyConnector acts on unknown caches

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#4929]
The GeokretyConnector should not act on caches from the unknown connector. This happens when importing lab caches.

```
05-10 11:59:53.145: W/cgeo(1807): [ModernAsyncTask #2] GeokretyConnector.searchTrackables
05-10 11:59:53.145: W/cgeo(1807): java.lang.IllegalArgumentException: Illegal character in query at index 46: http://api.geokretymap.org/export2.php?wpt=DAS ROEMISCHE STADTTOR-ROEMISCHES MAINZ - THE ROMAN MAINZ
05-10 11:59:53.145: W/cgeo(1807): 	at java.net.URI.create(URI.java:733)
05-10 11:59:53.145: W/cgeo(1807): 	at ch.boye.httpclientandroidlib.client.methods.HttpGet.<init>(HttpGet.java:69)
05-10 11:59:53.145: W/cgeo(1807): 	at cgeo.geocaching.network.Network.request(Network.java:184)
05-10 11:59:53.145: W/cgeo(1807): 	at cgeo.geocaching.network.Network.getRequest(Network.java:335)
05-10 11:59:53.145: W/cgeo(1807): 	at cgeo.geocaching.connector.trackable.GeokretyConnector.searchTrackables(GeokretyConnector.java:107)
05-10 11:59:53.145: W/cgeo(1807): 	at cgeo.geocaching.loaders.GeokretyCacheInventoryLoader.loadInBackground(GeokretyCacheInventoryLoader.java:26)
05-10 11:59:53.145: W/cgeo(1807): 	at cgeo.geocaching.loaders.GeokretyCacheInventoryLoader.loadInBackground(GeokretyCacheInventoryLoader.java:1)
05-10 11:59:53.145: W/cgeo(1807): 	at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:242)
05-10 11:59:53.145: W/cgeo(1807): 	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:51)
05-10 11:59:53.145: W/cgeo(1807): 	at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:40)
05-10 11:59:53.145: W/cgeo(1807): 	at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:123)
05-10 11:59:53.145: W/cgeo(1807): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-10 11:59:53.145: W/cgeo(1807): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
05-10 11:59:53.145: W/cgeo(1807): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
05-10 11:59:53.145: W/cgeo(1807): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by kumy** [comment]
First step would be to correctly urlencode parameters, then decide how/when Trackables connectors should be called depending on cache connectors.

**Comment by Lineflyer** [comment]
Taken from #5017 

2015.06.03-RC1:

I had several GPX imports on my device for lab caches and custom made caches (not refering to a known geocode).
I would not expect, that these caches are checked towards GK or GKM for inventory as these geocodes are not supported for carrying GKs.

```
15:51:39.327 Debug cgeo 11463  [ModernAsyncTask #5] GeokretyConnector.searchTrackables: wpt=LABYRINTH-FESTUM
15:51:39.327 Debug cgeo 11463  [ModernAsyncTask #5] GET http://api.geokretymap.org/export2.php?wpt=LABYRINTH-FESTUM
15:51:39.437 Debug cgeo 11463  [main] Loading LABYRINTH-FESTUM Labyrinth-Festum (41) from DB
15:51:39.657 Debug cgeo 11463  [ModernAsyncTask #5] 200 (352 ms) GET http://api.geokretymap.org/export2.php?wpt=LABYRINTH-FESTUM
15:51:39.767 Debug cgeo 11463  [main] Loading LABYRINTH-FESTUM Labyrinth-Festum (41) from DB
```

**Comment by Lineflyer** [comment]
@kumy Any idea whether this is still open?

**Comment by kumy** [comment]
The current implementation still do the "unexpected" lookup as you described in your logs just before.
I'm removed my assignee as I don't plan to work on it anytime soon, sorry :(
