### ISSUE TITLE
Crash of c:geo when invoking wear navigation

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#4949]
--- System information ---
Device: HTC One M9 (himauhl_vodafone_uk, htc)
Android version: 5.0.2
Android build: LRX22G release-keys
Cgeo version: 2015.03.31
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: present
Orientation sensor: present
Hide own/found: false
Map strategy: auto
HW-acceleration: enabled (default state)
geocaching.com: not logged in ()
System language: nl_NL
Installed cgeo plugins: none
--- End of system information ---

Remark:
User is not logged in, could that be the reason (e.g. coords missing?)

Log:
```
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=cgeo.geocaching.wear.NAVIGATE_TO (has extras) }
  at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1812)
  at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1841)
  at android.app.ContextImpl.startService(ContextImpl.java:1825)
  at android.content.ContextWrapper.startService(ContextWrapper.java:515)
  at cgeo.geocaching.apps.cache.navi.AndroidWearApp.navigate(AndroidWearApp.java:50)
  at cgeo.geocaching.apps.cache.navi.AndroidWearApp.navigate(AndroidWearApp.java:35)
  at cgeo.geocaching.apps.cache.navi.NavigationSelectionActionProvider$1.onMenuItemClick(NavigationSelectionActionProvider.java:49)
  at android.support.v7.internal.view.menu.MenuItemWrapperICS$OnMenuItemClickListenerWrapper.onMenuItemClick(MenuItemWrapperICS.java:370)
  at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:147)
  at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:897)
  at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:887)
  at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:179)
  at android.widget.AdapterView.performItemClick(AdapterView.java:300)
  at android.widget.AbsListView.performItemClick(AbsListView.java:1247)
  at android.widget.AbsListView$PerformClick.run(AbsListView.java:3215)
  at android.widget.AbsListView.onTouchUp(AbsListView.java:4021)
  at android.widget.AbsListView.onTouchEvent(AbsListView.java:3793)
  at android.view.View.dispatchTouchEvent(View.java:8444)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2430)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2158)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2436)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2178)
  at android.widget.PopupWindow$PopupViewContainer.dispatchTouchEvent(PopupWindow.java:1682)
  at android.view.View.dispatchPointerEvent(View.java:8655)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4261)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4117)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3658)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3717)
  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3683)
  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3796)
  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3691)
  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3853)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3663)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3717)
  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3683)
  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3691)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3663)
  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5963)
  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5931)
  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5895)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6053)
  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:211)
  at android.os.MessageQueue.nativePollOnce(Native Method)
  at android.os.MessageQueue.next(MessageQueue.java:153)
  at android.os.Looper.loop(Looper.java:131)
  at android.app.ActivityThread.main(ActivityThread.java:5721)
  at java.lang.reflect.Method.invoke(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1029)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)
```

@JavaDog

**Comment by rsudev** [comment]
I am pretty sure this is a duplicate and already fixed on master, but cannot find it right now.

**Comment by rsudev** [comment]
Found it: #4829

**Comment by rsudev** [comment]
Closed as duplicate
