### ISSUE TITLE
NoClassDefFoundError 'Move to different list' cache from list from long press action

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#4967]
From master 1b4ff80d0c

* open a saved list
* long press on a cache
* select 'Move to different list'
* select or create a new list

```
java.lang.NoClassDefFoundError: cgeo.geocaching.command.AbstractCommand$ActionAsyncTask
            at cgeo.geocaching.command.AbstractCommand.execute(AbstractCommand.java:96)
            at cgeo.geocaching.command.MoveToListCommand.access$101(MoveToListCommand.java:17)
            at cgeo.geocaching.command.MoveToListCommand$1.call(MoveToListCommand.java:36)
            at cgeo.geocaching.command.MoveToListCommand$1.call(MoveToListCommand.java:30)
            at cgeo.geocaching.list.StoredList$UserInterface$1.onClick(StoredList.java:98)
            at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1082)
            at android.widget.AdapterView.performItemClick(AdapterView.java:305)
            at android.widget.AbsListView.performItemClick(AbsListView.java:1148)
            at android.widget.AbsListView$PerformClick.run(AbsListView.java:3059)
            at android.widget.AbsListView.onTouchUp(AbsListView.java:3878)
            at android.widget.AbsListView.onTouchEvent(AbsListView.java:3643)
            at android.view.View.dispatchTouchEvent(View.java:8472)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2400)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2093)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
            at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2406)
            at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2107)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2625)
            at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1770)
            at android.app.Dialog.dispatchTouchEvent(Dialog.java:765)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2586)
            at android.view.View.dispatchPointerEvent(View.java:8667)
            at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4129)
            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3995)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3686)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3743)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3603)
            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3569)
            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3577)
            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3550)
            at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5813)
            at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5787)
            at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5758)
            at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5903)
            at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
            at android.os.MessageQueue.nativePollOnce(Native Method)
            at android.os.MessageQueue.next(MessageQueue.java:143)
            at android.os.Looper.loop(Looper.java:122)
            at android.app.ActivityThread.main(ActivityThread.java:5293)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372
```

```
java.lang.NoClassDefFoundError: cgeo.geocaching.command.AbstractCommand$ActionAsyncTask
            at cgeo.geocaching.command.AbstractCommand.execute(AbstractCommand.java:96)
            at cgeo.geocaching.command.MoveToListCommand.access$101(MoveToListCommand.java:17)
            at cgeo.geocaching.command.MoveToListCommand$1.call(MoveToListCommand.java:36)
            at cgeo.geocaching.command.MoveToListCommand$1.call(MoveToListCommand.java:30)
            at cgeo.geocaching.list.StoredList$UserInterface$3.call(StoredList.java:164)
            at cgeo.geocaching.list.StoredList$UserInterface$3.call(StoredList.java:150)
            at cgeo.geocaching.list.StoredList$UserInterface$4.call(StoredList.java:184)
            at cgeo.geocaching.list.StoredList$UserInterface$4.call(StoredList.java:177)
            at cgeo.geocaching.ui.dialog.Dialogs$2.onClick(Dialogs.java:372)
            at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:162)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5293)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by Bananeweizen** [comment]
Works fine for me using Eclipse build or the Ant release build. That's why I guess you used the gradle build? If so, then the gradle build is probably not using the existing proguard configuration files. Be aware they are not called proguard.pro, as I've seen in other gradle configs.

**Comment by kumy** [comment]
Worlks fine on NB. Should be related to build from Idea.

**Comment by Lineflyer** [comment]
@kumy Is this build related (and can thus be closed as an application bug) or something else?

**Comment by kumy** [comment]
@Lineflyer yes it's build related
