### ISSUE TITLE
Description page in detail activity is created more than once

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#4978]
Open a cache, go to the description page. For demonstration immediately decrypt the hint. One or two seconds later the detail page is recreated and the hint is encrypted again (and the long description is hidden).

Maybe `setDataSetChanged()` is called a few seconds after the first creation of the page.

**Comment by Lineflyer** [comment]
I can not reproduce this.
Can you @SammysHP with the current master?

**Comment by Lineflyer** [comment]
But I seem to have something similar in the logbook view.
While reading logs it sometimes happens, that it jumps back to the top (maybe while/after loading smiley images?).

**Comment by SammysHP** [comment]
I reproduced it with yesterday's nightly, but cannot reproduce it today with the same version :/ (even tried it with GPRS only and un-cached caches)

**Comment by Lineflyer** [comment]
Oh yes...slow network could be causing it. While it was happening last time I was almost without network. 
So it seems something is still loaded and after it finishes the view is recreated.

**Comment by kumy** [comment]
https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/CacheDetailActivity.java#L215
Could be the cause, but I can t remember when this code was merged... Was it before May 26?

**Comment by kumy** [comment]
Merge was done on Mar 28 https://github.com/cgeo/cgeo/commit/187f4c41303b1f9c45d2d67b51b79a14870e82dc
So date don't match.

**Comment by Lineflyer** [comment]
The date the issue was reported does not need to be the date it was introduced..it could still be the cause.

**Comment by kumy** [comment]
Issue has been opened before the new code. But I agree it could be also(?) a cause.

**Comment by Lineflyer** [comment]
@Kumy: Isn't it the other way around? Code was merged March 28th, Issue opened May 26th.

As fasr as I understand a `notifyDataSetChanged();` is issued here after async loading of trackable information has completed.
This is for sure new at this place as with only GC-TB they have been loaded with the listing but never in background. Question is (which I can not answer) whether this change notification is needed at this point. 
If it is the cause of the problem, I wonder why it applies also if the tab is not in view.

**Comment by kumy** [comment]
My apologies, I was confused by the month (thought they were the same :D).

**Comment by kumy** [comment]
@Lineflyer assigning for testing

**Comment by kumy** [comment]
PR #4908 updated too

**Comment by Lineflyer** [comment]
That will be hard to test. I will keep this open and try to see if this happens again next weeks.

**Comment by rsudev** [comment]
@kumy I had to revert you implementation as it caused #5074
Unfortunately I didn't have the time to dig deeper here...

**Comment by kumy** [comment]
@rsudev ho sorry! Thanks for taking time to revert.
I'll not have time to look soon. I'll be at http://coord.info/GC5DMA1 ;)
Can someone catch a stack trace?

**Comment by kumy** [comment]
"Same here. It only happens, when I try to open a cache, that isn't saved offline."
Hum, never check that :( All my tests were on saved caches.

**Comment by kumy** [comment]
```
E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 3537
    java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
            at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
     Caused by: rx.exceptions.OnErrorNotImplementedException: Attempt to invoke virtual method 'java.util.List cgeo.geocaching.Geocache.getLogs()' on a null object reference
            at rx.Observable$29.onError(Observable.java:7316)
            at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
            at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
            at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:67)
            at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:48)
            at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
            at rx.android.app.OperatorConditionalBinding$1.onCompleted(OperatorConditionalBinding.java:59)
            at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:201)
            at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
            at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List cgeo.geocaching.Geocache.getLogs()' on a null object reference
            at cgeo.geocaching.CacheDetailActivity.getOrderedPages(CacheDetailActivity.java:2116)
            at cgeo.geocaching.activity.AbstractViewPagerActivity.insertPage(AbstractViewPagerActivity.java:313)
            at cgeo.geocaching.CacheDetailActivity.access$400(CacheDetailActivity.java:152)
            at cgeo.geocaching.CacheDetailActivity$3.call(CacheDetailActivity.java:346)
            at rx.Observable$11.onError(Observable.java:4314)
            at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:65)
            at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:48)
            at rx.internal.operators.OperatorDoOnEach$1.onCompleted(OperatorDoOnEach.java:53)
            at rx.android.app.OperatorConditionalBinding$1.onCompleted(OperatorConditionalBinding.java:59)
            at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:201)
            at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
            at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5289)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

**Comment by kumy** [comment]
GKM response arrives before cache has been loaded, and try to add the inventory page. Error is coming while trying to find page order.

**Comment by kumy** [comment]
Ra-Assign to me, but if someone would like to look, feel free to do.

**Comment by rsudev** [comment]
The issue is, that ```CacheDetailsActivity.getOrderPages()``` can only be called, after the cache is loaded. Currently I have no clear idea how to achieve that...

**Comment by Lineflyer** [comment]
Some time ago I opened another issue that loading GKs is not fitting into our current strateg anyway. We load them on every opening of the cache details...This fact implies the problem described here. Maybe we should fit the Gk loading into the strategy that for an offline saved cache no online access should be necessary....so load Gk inventory while saving it but not updating it on the fly.

**Comment by kumy** [comment]
@Lineflyer  I agree, and the issue you mentioned is #4779.

**Comment by samueltardieu** [comment]
Can someone please have a look at 456abe438117dffebd46b0bce2d850b2b0be8038? It replaces the use of the loader by the use of an observable. If it appears that the result sometimes comes too soon, we can cache it very easily and have it handled only later (by virtually zipping it with a signal saying "UI is ready").

**Comment by Lineflyer** [comment]
@kumy @samueltardieu  
Was something merged here in the meantime?
Reading the comments of 456abe4 I thought it would, but can't find anything related in the commits.

**Comment by Lineflyer** [comment]
OK, found that PR #4908 is merged. 
Can we consider this issue fixed then?

Should this be merged to release as well or do you consider the change to be too dangerous for a bugfix release?

**Comment by kumy** [comment]
@Lineflyer I'm not sure this has been fixed with PR #4908

**Comment by kumy** [comment]
@SammysHP do you still encounter this issue?

**Comment by SammysHP** [comment]
I cannot reproduce it at the moment. Will re-open if it happens again.
