### ISSUE TITLE
opencaching.com will be shut down

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#5015]
Garmin announced (not available online yet?) that they will shut down their geocaching platform opencaching**.com** in the near future. We should prepare to remove opencaching**.com** from our list of available services.

**Comment by SammysHP** [comment]
https://www.facebook.com/GarminD

**Comment by Lineflyer** [comment]
I don't see an info about shutdown on this FB page.

**Comment by SammysHP** [comment]
The info is not released yet online, but this post:

> Danke für 15 Jahre Geocaching!
Grüße an unsere Freunde von Groundspeak.

**Comment by Lineflyer** [comment]
Here is an article about that on GoCacher (but without link to source):
http://www.gocacher.de/aus-fuer-garmins-opencaching-com/#more-7787

Shall we remove it already now for the upcoming release or wait until it is shut down?

**Comment by Bananeweizen** [comment]
I suggest to wait until shutdown. Especially as _everything_ related to opencaching.com has been so slow, that it might take another year. :)

**Comment by rsudev** [comment]
Looks like now they pulled the plug....
opencaching.com redirects to http://www.garmin.com/en-US/geocaching, where they suggest downloading caches from geocaching.com.

**Comment by Opencachingna** [comment]
Yup, Apparently it happened on Friday, August 14th, and Garmin tweeted about it on August 12th. Get that thing out of my c:geo :-)

**Comment by Lineflyer** [comment]
@Bananeweizen  I see, that you assigned for that.

While using c:geo today I have seen that the shutdown might affect the performance of the live map...at least I had problems and the connector was active. Can you base the removal of it on `release` branch to get it out more quick?

Looking at the log I can see:
```
22:29:18.817 Error cgeo 15089  [network-3] Error importing from OpenCaching.com
22:29:18.817 Error cgeo 15089  cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.0: could not parse XML
22:29:18.817 Error cgeo 15089  	at cgeo.geocaching.files.GPXParser.parse(GPXParser.java:867)
22:29:18.817 Error cgeo 15089  	at cgeo.geocaching.connector.ox.OpenCachingApi.importCachesFromResponse(OpenCachingApi.java:59)
22:29:18.817 Error cgeo 15089  	at cgeo.geocaching.connector.ox.OpenCachingApi.searchByBoundingBox(OpenCachingApi.java:128)
22:29:18.817 Error cgeo 15089  	at cgeo.geocaching.connector.ox.OXConnector.searchByViewport(OXConnector.java:94)
22:29:18.817 Error cgeo 15089  	at cgeo.geocaching.connector.ConnectorFactory$1.call(ConnectorFactory.java:253)
22:29:18.817 Error cgeo 15089  	at cgeo.geocaching.connector.ConnectorFactory$1.call(ConnectorFactory.java:250)
22:29:18.817 Error cgeo 15089  	at cgeo.geocaching.SearchResult$3$1.call(SearchResult.java:327)
22:29:18.817 Error cgeo 15089  	at cgeo.geocaching.SearchResult$3$1.call(SearchResult.java:324)
22:29:18.817 Error cgeo 15089  	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:45)
22:29:18.817 Error cgeo 15089  	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:34)
22:29:18.817 Error cgeo 15089  	at rx.Observable.unsafeSubscribe(Observable.java:7713)
22:29:18.817 Error cgeo 15089  	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
22:29:18.817 Error cgeo 15089  	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
22:29:18.817 Error cgeo 15089  	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:98)
22:29:18.817 Error cgeo 15089  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
22:29:18.817 Error cgeo 15089  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
22:29:18.817 Error cgeo 15089  	at java.lang.Thread.run(Thread.java:818)
22:29:18.817 Error cgeo 15089  Caused by: android.sax.BadXmlException: Line 3: Root element name does not match. Expected: 'http://www.topografix.com/GPX/1/0:gpx', Got: 'html'
22:29:18.817 Error cgeo 15089  	at android.sax.RootElement$Handler.startRoot(RootElement.java:145)
22:29:18.817 Error cgeo 15089  	at android.sax.RootElement$Handler.startElement(RootElement.java:116)
22:29:18.817 Error cgeo 15089  	at org.apache.harmony.xml.ExpatParser.startElement(ExpatParser.java:143)
22:29:18.817 Error cgeo 15089  	at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
22:29:18.817 Error cgeo 15089  	at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
22:29:18.817 Error cgeo 15089  	at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
22:29:18.817 Error cgeo 15089  	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
22:29:18.817 Error cgeo 15089  	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
22:29:18.817 Error cgeo 15089  	at android.util.Xml.parse(Xml.java:71)
22:29:18.817 Error cgeo 15089  	at cgeo.geocaching.files.GPXParser.parse(GPXParser.java:864)
22:29:18.817 Error cgeo 15089  	... 16 more
22:29:19.147 Warning cgeo 15089  [network-1] 204 [No Content] (480 ms) GET http://tiles.geocaching.com/map.info?x=34050&y=21837&z=16&ep=1&app=cgeo&k=NH2M&st=bLUNXMtXJh8NaZ43qJixQZOZxmpj9zJlHy0LyMkYG3JdbPnjnVDmLVHSGiDwa6ayzo5rf7qAJgYwcx6HKfMgZ2PoHTem3Bq3t-1WhAcGk3Wr9Td0U5g73iXhhvV5Lo5-0&hf=1&hh=1&_=1439929762260
22:29:19.147 Warning cgeo 15089  [RxComputationThreadPool-2] GCMap.searchByViewport: No data from server for tile (34050/21837)
22:29:22.757 Error cgeo 15089  [network-2] Error importing from OpenCaching.com
22:29:22.757 Error cgeo 15089  cgeo.geocaching.files.ParserException: Cannot parse .gpx file as GPX 1.0: could not parse XML
22:29:22.757 Error cgeo 15089  	at cgeo.geocaching.files.GPXParser.parse(GPXParser.java:867)
22:29:22.757 Error cgeo 15089  	at cgeo.geocaching.connector.ox.OpenCachingApi.importCachesFromResponse(OpenCachingApi.java:59)
22:29:22.757 Error cgeo 15089  	at cgeo.geocaching.connector.ox.OpenCachingApi.searchByBoundingBox(OpenCachingApi.java:128)
22:29:22.757 Error cgeo 15089  	at cgeo.geocaching.connector.ox.OXConnector.searchByViewport(OXConnector.java:94)
22:29:22.757 Error cgeo 15089  	at cgeo.geocaching.connector.ConnectorFactory$1.call(ConnectorFactory.java:253)
22:29:22.757 Error cgeo 15089  	at cgeo.geocaching.connector.ConnectorFactory$1.call(ConnectorFactory.java:250)
22:29:22.757 Error cgeo 15089  	at cgeo.geocaching.SearchResult$3$1.call(SearchResult.java:327)
22:29:22.757 Error cgeo 15089  	at cgeo.geocaching.SearchResult$3$1.call(SearchResult.java:324)
22:29:22.757 Error cgeo 15089  	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:45)
22:29:22.757 Error cgeo 15089  	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:34)
22:29:22.757 Error cgeo 15089  	at rx.Observable.unsafeSubscribe(Observable.java:7713)
22:29:22.757 Error cgeo 15089  	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
22:29:22.757 Error cgeo 15089  	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
22:29:22.757 Error cgeo 15089  	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:98)
22:29:22.757 Error cgeo 15089  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
22:29:22.757 Error cgeo 15089  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
22:29:22.757 Error cgeo 15089  	at java.lang.Thread.run(Thread.java:818)
22:29:22.757 Error cgeo 15089  Caused by: android.sax.BadXmlException: Line 3: Root element name does not match. Expected: 'http://www.topografix.com/GPX/1/0:gpx', Got: 'html'
22:29:22.757 Error cgeo 15089  	at android.sax.RootElement$Handler.startRoot(RootElement.java:145)
22:29:22.757 Error cgeo 15089  	at android.sax.RootElement$Handler.startElement(RootElement.java:116)
22:29:22.757 Error cgeo 15089  	at org.apache.harmony.xml.ExpatParser.startElement(ExpatParser.java:143)
22:29:22.757 Error cgeo 15089  	at org.apache.harmony.xml.ExpatParser.appendChars(Native Method)
22:29:22.757 Error cgeo 15089  	at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:497)
22:29:22.757 Error cgeo 15089  	at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
22:29:22.757 Error cgeo 15089  	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
22:29:22.757 Error cgeo 15089  	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
22:29:22.757 Error cgeo 15089  	at android.util.Xml.parse(Xml.java:71)
22:29:22.757 Error cgeo 15089  	at cgeo.geocaching.files.GPXParser.parse(GPXParser.java:864)
22:29:22.757 Error cgeo 15089  	... 16 more
```

**Comment by SammysHP** [comment]
@Lineflyer Do you think it makes sense to post a notification that geocaching.com was shut down and that users should disable it?

**Comment by kumy** [comment]
@SammysHP you mean "opencaching.com" not "geocaching.com" ;)

**Comment by SammysHP** [comment]
@kumy Hehe, my edit was a second faster than your post. ;)

**Comment by Lineflyer** [comment]
I don't think it would be wise. Those followers mixing it up with geocaching.com would be the clear majority to those really using opencaching.com. ....
