### ISSUE TITLE
Missing backpressure exception

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5052]
From GooglePlay:

No regression as it also appeared with older versions.
Now reported for 2015.06.19.

User messages are like:
- Crashed on import of GPX
- Crashed on downloading caches

Several devices and spread over Android 2.x, 4.x

```
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60) 
  at android.os.Handler.handleCallback(Handler.java:733)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5333)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
  at dalvik.system.NativeStart.main(Native Method)
Caused by: rx.exceptions.OnErrorNotImplementedException
  at rx.Observable$30.onError(Observable.java:7358)
  at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
  at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:197)
  at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
  at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
  ... 9 more
Caused by: rx.exceptions.MissingBackpressureException
  at  rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.onNext(OperatorObserveOn.java:138)
  at rx.internal.operators.OnSubscribeRefCount$2.onNext(OnSubscribeRefCount.java:124)
  at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:224)
  at rx.subjects.ReplaySubject.onNext(ReplaySubject.java:370)
  at rx.internal.operators.OperatorMulticast$2.onNext(OperatorMulticast.java:106)
  at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
  at rx.observers.Subscribers$1.onNext(Subscribers.java:66)
  at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
  at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:224)
  at rx.subjects.PublishSubject.onNext(PublishSubject.java:114)
  at cgeo.geocaching.sensors.GpsStatusProvider$GpsStatusListener.onGpsStatusChanged(GpsStatusProvider.java:95)
  at android.location.LocationManager$GpsStatusListenerTransport$1.handleMessage(LocationManager.java:1552)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:136)
  at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by Lineflyer** [comment]
Duplicate of #5402 and solved meanwhile.
