### ISSUE TITLE
BadTokenException

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5053]
From Google Play:

No regression as also appearing with older versions but now on 2015.06.19.

Several devices Android 4.x and 5.x (no 2.x).

User messages:
- Stops on loading caches
- Stops on search
- Stops after importing .loc

```
android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@42970688 is not valid; is your activity running?
  at android.view.ViewRootImpl.setView(ViewRootImpl.java:536)
  at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:259)
  at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
  at android.app.Dialog.show(Dialog.java:294)
  at cgeo.geocaching.connector.gc.RecaptchaHandler.handleMessage(RecaptchaHandler.java:113)
  at android.os.Handler.dispatchMessage(Handler.java:106)
  at android.os.Looper.loop(Looper.java:136)
  at android.app.ActivityThread.main(ActivityThread.java:5196)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
  at dalvik.system.NativeStart.main(Native Method)
```

**Comment by rsudev** [comment]
Looks like related to the Captcha - I haven't had a look at this for quite some time...

**Comment by Lineflyer** [comment]
If you find no solution for this a possible solution would be to remove this option completely.
As written in another issue the Captcha is almost unreadable in our implementation.

**Comment by Lineflyer** [comment]
Captcha has been removed meanwhile.
