### ISSUE TITLE
NPE on startup

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5054]
From GooglePlay:

No regression as also appearing on older version, but now on 2015.06.19

Several devices over several Android versions.

User messages:
- Stops on startup
- Won't start

```
java.lang.RuntimeException: Unable to create application cgeo.geocaching.CgeoApplication: java.lang.NullPointerException
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3279)
  at android.app.ActivityThread.access$2200(ActivityThread.java:117)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:973)
  at android.os.Handler.dispatchMessage(Handler.java:99)
  at android.os.Looper.loop(Looper.java:130)
  at android.app.ActivityThread.main(ActivityThread.java:3689)
  at java.lang.reflect.Method.invokeNative(Native Method)
  at java.lang.reflect.Method.invoke(Method.java:507)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:842)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
  at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
  at cgeo.geocaching.DataStore$PreparedStatement.getStatement(DataStore.java:2934)
  at cgeo.geocaching.DataStore$PreparedStatement.simpleQueryForLong(DataStore.java:2926)
  at cgeo.geocaching.DataStore.getLists(DataStore.java:2555)
  at cgeo.geocaching.CgeoApplication.onCreate(CgeoApplication.java:76)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3276)
  ... 10 more
```

**Comment by Lineflyer** [comment]
No more reports like this.
