### ISSUE TITLE
NPE in ViewTarget

### ISSUE THREAD

**Issue by bafa1012** [cgeo/cgeo#5073]
Happened with Android 4.2.2, 4.3 and 4.4.2 on following devices:
- Samsung GTN7100
- Samsung G350L
- Positivo Mini

java.lang.NullPointerException
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.github.amlcurran.showcaseview.targets.ViewTarget.getPoint(ViewTarget.java:41)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.github.amlcurran.showcaseview.ShowcaseView$1.run(ShowcaseView.java:166)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at android.os.Handler.handleCallback(Handler.java:725)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at android.os.Handler.dispatchMessage(Handler.java:92)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at android.os.Looper.loop(Looper.java:137)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at android.app.ActivityThread.main(ActivityThread.java:5041)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.reflect.Method.invokeNative(Method.java)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at java.lang.reflect.Method.invoke(Method.java:511)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by bafa1012** [comment]
Nevermind, wrong project
