### ISSUE TITLE
NPE in speech service

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5096]
From Google Play console for cgeo 2015.07.08:

```
java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:145)
   at android.app.ActivityThread.main(ActivityThread.java:5942)
   at java.lang.reflect.Method.invoke(Native Method)
   at java.lang.reflect.Method.invoke(Method.java:372)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
Caused by: rx.exceptions.OnErrorNotImplementedException: Attempt to invoke interface method 'cgeo.geocaching.location.Geopoint cgeo.geocaching.ICoordinates.getCoords()' on a null object reference
   at rx.Observable$30.onError(Observable.java:7358)
   at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
   at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:137)
   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:208)
   at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:170)
   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
   ... 8 more
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'cgeo.geocaching.location.Geopoint cgeo.geocaching.ICoordinates.getCoords()' on a null object reference
   at cgeo.geocaching.location.Geopoint.distanceTo(Geopoint.java:196)
   at cgeo.geocaching.speech.SpeechService$1.updateGeoDir(SpeechService.java:58)
   at cgeo.geocaching.sensors.GeoDirHandler$3.call(GeoDirHandler.java:116)
   at cgeo.geocaching.sensors.GeoDirHandler$3.call(GeoDirHandler.java:113)
   at rx.Observable$30.onNext(Observable.java:7363)
   at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:130)
   ... 11 more
```

**Comment by samueltardieu** [comment]
Reopening for field testing and inclusion in `release`.

**Comment by Lineflyer** [comment]
Can you give a test case for that or is it device depending? 
Speech compass was working normal for me in the recent past.

**Comment by samueltardieu** [comment]
There exists a race condition (exhibited in the stack trace) where the service was started before the target is set. I can't reproduce it either, but from the code the race condition exists.

**Comment by Lineflyer** [comment]
Are there maybe points in the app where a navigation can be started on a cache which has no coords?

**Comment by samueltardieu** [comment]
Maybe.

**Comment by Lineflyer** [comment]
Voice compass is working normal for me in 2015.07.19-NB. I will probably not able to enforce the mentioned race condition, however OK for merging to release.
