### ISSUE TITLE
Refreshing of caches stored on list failed

### ISSUE THREAD

**Issue by LeXeRLV** [cgeo/cgeo#5115]
Today after installing latest Nightly build found error, when trying to refresh all stored caches on selected list. c:geo stopped working. 
Today after installing latest Nightly build found error, when trying to refresh all stored caches on selected list. c:geo stopped working. 
My device info from app:
https://www.dropbox.com/s/1vnmr7wok5y8vts/2015-07-24%2013.13.21.png?dl=0
https://www.dropbox.com/s/pd2uyw03dqpqnjr/2015-07-24%2013.13.38.png?dl=0
My device info from app:
--- System information ---
Device: HTC One X (htc_europe, htc)
Android version: 4.2.2
Android build: JDQ39
Cgeo version: 2015.07.24-NB-d4367c5
Google Play services: disabled
Low power mode: active
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: absent
Orientation sensor: present
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (manually changed)
System language: en_US
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / Basic
Installed cgeo plugins:  none
--- End of system information ---

**Comment by Hauwertlhaufn** [comment]
Same here. Also described it on the irc today.

--- System information ---
Device: Nexus 5 (hammerhead, google)
Android version: 5.1.1
Android build: LMY48B
Cgeo version: 2015.07.24-NB-d4367c5
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation sensor: present
Geomagnetic rotation sensor: present
Orientation sensor: present
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / Premium
Installed cgeo plugins: calendar
--- End of system information ---

**Comment by Lineflyer** [comment]
- Refresh list of 15 stored caches

2015.07.21-NB = OK
2015.07.24-NB = Partly NOK

List with 15 caches was OK, list with 18 caches failed:

```
14:29:36.526 Error cgeo 24572  [RxCachedThreadScheduler-3] UncaughtException
14:29:36.526 Error cgeo 24572  java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
14:29:36.526 Error cgeo 24572  	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
14:29:36.526 Error cgeo 24572  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
14:29:36.526 Error cgeo 24572  	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
14:29:36.526 Error cgeo 24572  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
14:29:36.526 Error cgeo 24572  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
14:29:36.526 Error cgeo 24572  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
14:29:36.526 Error cgeo 24572  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
14:29:36.526 Error cgeo 24572  	at java.lang.Thread.run(Thread.java:818)
14:29:36.526 Error cgeo 24572  Caused by: rx.exceptions.OnErrorNotImplementedException: more items arrived than were requested
14:29:36.526 Error cgeo 24572  	at rx.Observable$29.onError(Observable.java:7498)
14:29:36.526 Error cgeo 24572  	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:154)
14:29:36.526 Error cgeo 24572  	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:111)
14:29:36.526 Error cgeo 24572  	at rx.internal.operators.OperatorDoOnEach$1.onError(OperatorDoOnEach.java:70)
14:29:36.526 Error cgeo 24572  	at rx.internal.operators.OperatorMerge$MergeSubscriber.reportError(OperatorMerge.java:239)
14:29:36.526 Error cgeo 24572  	at rx.internal.operators.OperatorMerge$MergeSubscriber.checkTerminate(OperatorMerge.java:772)
14:29:36.526 Error cgeo 24572  	at rx.internal.operators.OperatorMerge$MergeSubscriber.emitLoop(OperatorMerge.java:530)
14:29:36.526 Error cgeo 24572  	at rx.internal.operators.OperatorMerge$MergeSubscriber.emit(OperatorMerge.java:519)
14:29:36.526 Error cgeo 24572  	at rx.internal.operators.OperatorMerge$MergeSubscriber.onError(OperatorMerge.java:249)
14:29:36.526 Error cgeo 24572  	at rx.internal.operators.OperatorMap$1.onError(OperatorMap.java:49)
14:29:36.526 Error cgeo 24572  	at rx.observers.SerializedObserver.onError(SerializedObserver.java:122)
14:29:36.526 Error cgeo 24572  	at rx.observers.SerializedSubscriber.onError(SerializedSubscriber.java:79)
14:29:36.526 Error cgeo 24572  	at rx.internal.operators.OperatorConcat$ConcatSubscriber.onError(OperatorConcat.java:146)
14:29:36.526 Error cgeo 24572  	at rx.internal.operators.OperatorConcat$ConcatInnerSubscriber.onError(OperatorConcat.java:215)
14:29:36.526 Error cgeo 24572  	at rx.Observable.unsafeSubscribe(Observable.java:7720)
14:29:36.526 Error cgeo 24572  	at rx.internal.operators.OperatorConcat$ConcatSubscriber.subscribeNext(OperatorConcat.java:176)
14:29:36.526 Error cgeo 24572  	at rx.internal.operators.OperatorConcat$ConcatSubscriber.completeInner(OperatorConcat.java:162)
14:29:36.526 Error cgeo 24572  	at rx.internal.operators.OperatorConcat$ConcatInnerSubscriber.onCompleted(OperatorConcat.java:223)
14:29:36.526 Error cgeo 24572  	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onCompleted(SubjectSubscriptionManager.java:232)
14:29:36.526 Error cgeo 24572  	at rx.subjects.ReplaySubject.onCompleted(ReplaySubject.java:404)
14:29:36.526 Error cgeo 24572  	at cgeo.geocaching.CacheListActivity$17.call(CacheListActivity.java:1243)
14:29:36.526 Error cgeo 24572  	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
14:29:36.526 Error cgeo 24572  	... 7 more
14:29:36.526 Error cgeo 24572  Caused by: java.lang.IllegalStateException: more items arrived than were requested
14:29:36.526 Error cgeo 24572  	at rx.internal.producers.ProducerArbiter.produced(ProducerArbiter.java:98)
14:29:36.526 Error cgeo 24572  	at rx.internal.operators.OperatorConcat$ConcatInnerSubscriber.onNext(OperatorConcat.java:208)
14:29:36.526 Error cgeo 24572  	at rx.subjects.SubjectSubscriptionManager$SubjectObserver.onNext(SubjectSubscriptionManager.java:224)
14:29:36.526 Error cgeo 24572  	at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
14:29:36.526 Error cgeo 24572  	at rx.subjects.ReplaySubject$UnboundedReplayState.accept(ReplaySubject.java:466)
14:29:36.526 Error cgeo 24572  	at rx.subjects.ReplaySubject$UnboundedReplayState.replayObserverFromIndex(ReplaySubject.java:515)
14:29:36.526 Error cgeo 24572  	at rx.subjects.ReplaySubject$1.call(ReplaySubject.java:98)
14:29:36.526 Error cgeo 24572  	at rx.subjects.ReplaySubject$1.call(ReplaySubject.java:94)
14:29:36.526 Error cgeo 24572  	at rx.subjects.SubjectSubscriptionManager.call(SubjectSubscriptionManager.java:59)
14:29:36.526 Error cgeo 24572  	at rx.subjects.SubjectSubscriptionManager.call(SubjectSubscriptionManager.java:35)
14:29:36.526 Error cgeo 24572  	at rx.Observable.unsafeSubscribe(Observable.java:7713)
14:29:36.526 Error cgeo 24572  	... 14 more
```

**Comment by Lineflyer** [comment]
Release version 2015.07.08 is OK, so the problem is most probably on master only.

**Comment by rsudev** [comment]
RxJava has been updated yesterday, so this is likely a side effect.

**Comment by LeXeRLV** [comment]
What does it mean, if issue now closed? Will it be ok with next nihgtly build?

**Comment by samueltardieu** [comment]
It should. The next one has already been prepared, you can update right away (by either visiting http://status.cgeo.org/ and selecting the APK or by forcibly killing cgeo and restarting it, it should propose an update).
