### ISSUE TITLE
Hang when launching LiveMapActivity + back multiple times

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5155]
I can get c:geo hang when selecting LiveMapActivty, then press immediately back, repeat (fast).

Are you able to reproduce?

```
08-27 20:16:17.599    3392-3392/cgeo.geocaching W/ResourcesManager﹕ Asset path '/system/framework/com.google.android.maps.jar' does not exist or contains no resources.
08-27 20:16:17.719    3392-3392/cgeo.geocaching W/ResourcesManager﹕ Asset path '/system/framework/com.google.android.maps.jar' does not exist or contains no resources.
08-27 20:16:17.852    3392-3435/cgeo.geocaching D/OpenGLRenderer﹕ Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-27 20:16:17.862    3392-3392/cgeo.geocaching D/Atlas﹕ Validating map...
08-27 20:16:17.907    3392-3435/cgeo.geocaching I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1_RB1.04.04.02.002.022_msm8974_LA.BF.1.1_RB1__release_AU ()
    OpenGL ES Shader Compiler Version: E031.25.01.03
    Build Date: 10/30/14 Thu
    Local Branch: mybranch5388235
    Remote Branch: quic/LA.BF.1.1_rb1.8
    Local Patches: NONE
    Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1_RB1.04.04.02.002.022 +  NOTHING
08-27 20:16:17.909    3392-3435/cgeo.geocaching I/OpenGLRenderer﹕ Initialized EGL, version 1.4
08-27 20:16:17.926    3392-3435/cgeo.geocaching D/OpenGLRenderer﹕ Enabling debug mode 0
08-27 20:16:18.058    3392-3392/cgeo.geocaching D/ShowcaseView﹕ Recalculated
08-27 20:16:18.107    3392-3392/cgeo.geocaching I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@1f87483a time:277569053
08-27 20:16:21.689    3392-3392/cgeo.geocaching W/cgeo﹕ [main] No Google API key available.
08-27 20:16:21.693    3392-3392/cgeo.geocaching I/Timeline﹕ Timeline: Activity_launch_request id:cgeo.geocaching time:277572639
08-27 20:16:21.960    3392-3392/cgeo.geocaching I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@a3bfab1 time:277572906
08-27 20:16:22.637    3392-3392/cgeo.geocaching I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@1f87483a time:277573584
08-27 20:16:23.870    3392-3392/cgeo.geocaching I/Timeline﹕ Timeline: Activity_launch_request id:cgeo.geocaching time:277574816
08-27 20:16:24.058    3392-3407/cgeo.geocaching I/art﹕ Background partial concurrent mark sweep GC freed 2229(166KB) AllocSpace objects, 29(19MB) LOS objects, 16% free, 80MB/96MB, paused 5.843ms total 50.057ms
08-27 20:16:24.134    3392-3392/cgeo.geocaching I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@419a33a time:277575081
08-27 20:16:24.923    3392-3392/cgeo.geocaching I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@1f87483a time:277575869
08-27 20:16:24.958    3392-3557/cgeo.geocaching W/System.err﹕ java.io.InterruptedIOException
08-27 20:16:24.958    3392-3557/cgeo.geocaching W/System.err﹕ at com.android.okio.Deadline.throwIfReached(Deadline.java:56)
08-27 20:16:24.958    3392-3557/cgeo.geocaching W/System.err﹕ at com.android.okio.Okio$2.read(Okio.java:110)
08-27 20:16:24.959    3392-3557/cgeo.geocaching W/System.err﹕ at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
08-27 20:16:24.959    3392-3557/cgeo.geocaching W/System.err﹕ at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
08-27 20:16:24.959    3392-3557/cgeo.geocaching W/System.err﹕ at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
08-27 20:16:24.959    3392-3557/cgeo.geocaching W/System.err﹕ at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
08-27 20:16:24.959    3392-3557/cgeo.geocaching W/System.err﹕ at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
08-27 20:16:24.959    3392-3557/cgeo.geocaching W/System.err﹕ at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
08-27 20:16:24.959    3392-3557/cgeo.geocaching W/System.err﹕ at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:649)
08-27 20:16:24.959    3392-3557/cgeo.geocaching W/System.err﹕ at org.mapsforge.android.maps.mapgenerator.tiledownloader.TileDownloader.executeJob(TileDownloader.java:60)
08-27 20:16:24.959    3392-3557/cgeo.geocaching W/System.err﹕ at org.mapsforge.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:73)
08-27 20:16:24.959    3392-3557/cgeo.geocaching W/System.err﹕ at org.mapsforge.android.maps.PausableThread.run(PausableThread.java:94)
08-27 20:16:24.959    3392-3557/cgeo.geocaching D/skia﹕ ---- read threw an exception
08-27 20:16:24.960    3392-3557/cgeo.geocaching D/skia﹕ --- SkImageDecoder::Factory returned null
08-27 20:16:28.196    3392-3424/cgeo.geocaching E/cgeo﹕ [RxComputationThreadPool-1] GCMap.searchByViewport: No cache parsed for viewport (N 43° xx.xxx · E 006° xx.xxx,N 43° xx.xxx · E 006° xx.xxx)
08-27 20:16:32.567    3392-3401/cgeo.geocaching I/art﹕ Thread[5,tid=3401,WaitingInMainSignalCatcherLoop,Thread*=0xb4a37800,peer=0x12c000a0,"Signal Catcher"]: reacting to signal 3
08-27 20:16:32.567    3392-3401/cgeo.geocaching I/art﹕ [ 08-27 20:16:32.767   791:  836 I/Process  ]
    Sending signal. PID: 791 SIG: 3
```

```
08-27 20:20:27.718    3882-3882/cgeo.geocaching W/ResourcesManager﹕ Asset path '/system/framework/com.google.android.maps.jar' does not exist or contains no resources.
08-27 20:20:27.837    3882-3882/cgeo.geocaching W/ResourcesManager﹕ Asset path '/system/framework/com.google.android.maps.jar' does not exist or contains no resources.
08-27 20:20:27.958    3882-3922/cgeo.geocaching D/OpenGLRenderer﹕ Use EGL_SWAP_BEHAVIOR_PRESERVED: true
08-27 20:20:27.963    3882-3882/cgeo.geocaching D/Atlas﹕ Validating map...
08-27 20:20:28.019    3882-3922/cgeo.geocaching I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build: AU_LINUX_ANDROID_LA.BF.1.1_RB1.04.04.02.002.022_msm8974_LA.BF.1.1_RB1__release_AU ()
    OpenGL ES Shader Compiler Version: E031.25.01.03
    Build Date: 10/30/14 Thu
    Local Branch: mybranch5388235
    Remote Branch: quic/LA.BF.1.1_rb1.8
    Local Patches: NONE
    Reconstruct Branch: AU_LINUX_ANDROID_LA.BF.1.1_RB1.04.04.02.002.022 +  NOTHING
08-27 20:20:28.020    3882-3922/cgeo.geocaching I/OpenGLRenderer﹕ Initialized EGL, version 1.4
08-27 20:20:28.036    3882-3922/cgeo.geocaching D/OpenGLRenderer﹕ Enabling debug mode 0
08-27 20:20:28.158    3882-3882/cgeo.geocaching D/ShowcaseView﹕ Recalculated
08-27 20:20:28.234    3882-3882/cgeo.geocaching I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@1f87483a time:277819180
08-27 20:20:31.828    3882-3882/cgeo.geocaching W/cgeo﹕ [main] No Google API key available.
08-27 20:20:31.832    3882-3882/cgeo.geocaching I/Timeline﹕ Timeline: Activity_launch_request id:cgeo.geocaching time:277822779
08-27 20:20:32.078    3882-3882/cgeo.geocaching I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@24e51cd4 time:277823024
08-27 20:20:34.872    3882-3882/cgeo.geocaching I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@1f87483a time:277825818
08-27 20:20:35.764    3882-3882/cgeo.geocaching I/Timeline﹕ Timeline: Activity_launch_request id:cgeo.geocaching time:277826710
08-27 20:20:36.030    3882-3882/cgeo.geocaching I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@167f3266 time:277826976
08-27 20:20:37.060    3882-3882/cgeo.geocaching I/Timeline﹕ Timeline: Activity_idle id: android.os.BinderProxy@1f87483a time:277828006
08-27 20:20:37.381    3882-3999/cgeo.geocaching W/System.err﹕ java.io.InterruptedIOException
08-27 20:20:37.381    3882-3999/cgeo.geocaching W/System.err﹕ at com.android.okio.Deadline.throwIfReached(Deadline.java:56)
08-27 20:20:37.381    3882-3999/cgeo.geocaching W/System.err﹕ at com.android.okio.Okio$2.read(Okio.java:110)
08-27 20:20:37.381    3882-3999/cgeo.geocaching W/System.err﹕ at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
08-27 20:20:37.381    3882-3999/cgeo.geocaching W/System.err﹕ at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:446)
08-27 20:20:37.387    3882-3999/cgeo.geocaching W/System.err﹕ at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
08-27 20:20:37.387    3882-3999/cgeo.geocaching W/System.err﹕ at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
08-27 20:20:37.387    3882-3999/cgeo.geocaching W/System.err﹕ at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
08-27 20:20:37.387    3882-3999/cgeo.geocaching W/System.err﹕ at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
08-27 20:20:37.387    3882-3999/cgeo.geocaching W/System.err﹕ at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:649)
08-27 20:20:37.387    3882-3999/cgeo.geocaching W/System.err﹕ at org.mapsforge.android.maps.mapgenerator.tiledownloader.TileDownloader.executeJob(TileDownloader.java:60)
08-27 20:20:37.387    3882-3999/cgeo.geocaching W/System.err﹕ at org.mapsforge.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:73)
08-27 20:20:37.388    3882-3999/cgeo.geocaching W/System.err﹕ at org.mapsforge.android.maps.PausableThread.run(PausableThread.java:94)
08-27 20:20:37.388    3882-3999/cgeo.geocaching D/skia﹕ ---- read threw an exception
08-27 20:20:37.388    3882-3999/cgeo.geocaching D/skia﹕ --- decoder->decode returned false
08-27 20:20:38.617    3882-3923/cgeo.geocaching E/cgeo﹕ [network-3] GCMap.searchByViewport: No cache parsed for viewport (N 43° xx.xxx · E 006° xx.xxx,N 43° xx.xxx · E 006° xx.xxx)
```

**Comment by kumy** [comment]
```
08-27 20:41:16.930    7426-7797/cgeo.geocaching E/TileDownloader﹕ null
    java.io.InterruptedIOException
            at com.android.okio.Deadline.throwIfReached(Deadline.java:56)
            at com.android.okio.Okio$1.write(Okio.java:67)
            at com.android.okio.RealBufferedSink.flush(RealBufferedSink.java:154)
            at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:130)
            at com.android.okhttp.internal.http.HttpTransport.flushRequest(HttpTransport.java:73)
            at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:626)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:199)
            at java.net.URL.openStream(URL.java:470)
            at org.mapsforge.android.maps.mapgenerator.tiledownloader.TileDownloader.executeJob(TileDownloader.java:59)
            at org.mapsforge.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:73)
            at org.mapsforge.android.maps.PausableThread.run(PausableThread.java:94)
```

**Comment by samueltardieu** [comment]
Using OSM, I could lock up the application doing what you described.

**Comment by SammysHP** [comment]
Can't find the issue, but I reported that some months ago (or was it only on IRC?).

**Comment by samueltardieu** [comment]
Still reproducible with the current master.

**Comment by Lineflyer** [comment]
Assigning me for field test.

**Comment by Lineflyer** [comment]
Behaviour still reproducible with 2018.03.16-NB
Did not look at the debug log, but assume it is the same.

**Comment by fm-sys** [comment]
Still reproducible. Anyway, opening and directly leaving the Livemap multiple times quickly isn't really something which can happen by mistake.

Should we close this as "won't fix" as there are many other issues which are way more important. What do you think?

**Comment by moving-bits** [comment]
(I had tried this yesterday as well. Reproducible with current release, but nothing specific in the logcat.)

I agree with @fm-sys

**Comment by Lineflyer** [comment]
fine for me.
