### ISSUE TITLE
Crash when trying to navigate with MapsWithMe and waypoints without coordinates

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5204]
(Error scenario deduced from the following playstore crash report)
```
java.lang.NullPointerException: Attempt to invoke virtual method 'double cgeo.geocaching.location.Geopoint.getLatitude()' on a null object reference
	at cgeo.geocaching.apps.navi.MapsMeApp.navigateWithWaypoints(MapsMeApp.java:43)
	at cgeo.geocaching.apps.navi.MapsMeApp.navigate(MapsMeApp.java:35)
	at cgeo.geocaching.apps.navi.NavigationAppFactory.navigateCache(NavigationAppFactory.java:250)
	at cgeo.geocaching.apps.navi.NavigationAppFactory.startDefaultNavigationApplication(NavigationAppFactory.java:290)
	at cgeo.geocaching.CacheDetailActivity.startDefaultNavigation(CacheDetailActivity.java:774)
	at cgeo.geocaching.ui.NavigationActionProvider$1.onClick(NavigationActionProvider.java:47)
	at android.view.View.performClick(View.java:5184)
	at android.view.View$PerformClick.run(View.java:20893)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5938)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```
(Report from 2015/09/24, 13:01)

**Comment by Bananeweizen** [comment]
Your thoughts are completely valid. This probably only happens since I made MapsMe use the waypoints in addition to the final coordinate. Unfortunately we had the same issue like 2 years ago with Locus and repeating such a bug should not happen. :(
