### ISSUE TITLE
cannot open cache details - galaxy SII

### ISSUE THREAD

**Issue by francois-dorval** [cgeo/cgeo#5420]
Hello, 
on my cyanogenmod  (12.1-2015116) galaxy s2, android 5.1.1, I cannot open a cache detail from the map : I get 
"C geo n'a pas pu télécharger les détails de la cache. Erreur inconnue"

Version : 2016.01.19

Here's the logcat ouptut :

```
I/ActivityManager( 2215): Displayed cgeo.geocaching/.CachePopup: +351ms
I/Timeline( 8167): Timeline: Activity_idle id: android.os.BinderProxy@2333f3d9 time:6711291
(...)
V/WindowManager( 2215): addAppToken: AppWindowToken{ec49c29 token=Token{303e5b0 ActivityRecord{1d09d4f3 u0 cgeo.geocaching/.CacheDetailActivity t1118}}} to stack=1 task=1118 at 3
V/WindowManager( 2215): Adding window Window{c62cd4f u0 GC2FVYN} at 12 of 16 (after Window{5c8950a u0 cgeo.geocaching/cgeo.geocaching.CachePopup})
V/WindowManager( 2215): Adding window Window{21e1d1e5 u0 cgeo.geocaching/cgeo.geocaching.CacheDetailActivity} at 12 of 17 (before Window{c62cd4f u0 GC2FVYN})
W/SupportMenuInflater( 8167): Cannot instantiate class: android.support.v7.widget.ShareActionProvider
W/SupportMenuInflater( 8167): java.lang.NoSuchMethodException: <init> [class android.content.Context]
W/SupportMenuInflater( 8167): 	at java.lang.Class.getConstructor(Class.java:531)
W/SupportMenuInflater( 8167): 	at java.lang.Class.getConstructor(Class.java:495)
W/SupportMenuInflater( 8167): 	at android.support.v7.internal.view.SupportMenuInflater$MenuState.newInstance(SupportMenuInflater.java:481)
W/SupportMenuInflater( 8167): 	at android.support.v7.internal.view.SupportMenuInflater$MenuState.readItem(SupportMenuInflater.java:383)
W/SupportMenuInflater( 8167): 	at android.support.v7.internal.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:168)
W/SupportMenuInflater( 8167): 	at android.support.v7.internal.view.SupportMenuInflater.inflate(SupportMenuInflater.java:118)
W/SupportMenuInflater( 8167): 	at cgeo.geocaching.CacheMenuHandler.addMenuItems(CacheMenuHandler.java:111)
W/SupportMenuInflater( 8167): 	at cgeo.geocaching.CacheMenuHandler.addMenuItems(CacheMenuHandler.java:116)
W/SupportMenuInflater( 8167): 	at cgeo.geocaching.CacheDetailActivity.onCreateOptionsMenu(CacheDetailActivity.java:562)
W/SupportMenuInflater( 8167): 	at android.app.Activity.onCreatePanelMenu(Activity.java:2823)
W/SupportMenuInflater( 8167): 	at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:262)
W/SupportMenuInflater( 8167): 	at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ActionBarActivity.java:233)
W/SupportMenuInflater( 8167): 	at android.support.v7.app.ActionBarActivityDelegateICS.onCreatePanelMenu(ActionBarActivityDelegateICS.java:146)
W/SupportMenuInflater( 8167): 	at android.support.v7.app.ActionBarActivity.onCreatePanelMenu(ActionBarActivity.java:200)
W/SupportMenuInflater( 8167): 	at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.onCreatePanelMenu(ActionBarActivityDelegateICS.java:293)
W/SupportMenuInflater( 8167): 	at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:600)
W/SupportMenuInflater( 8167): 	at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:972)
W/SupportMenuInflater( 8167): 	at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:309)
W/SupportMenuInflater( 8167): 	at android.os.Handler.handleCallback(Handler.java:739)
W/SupportMenuInflater( 8167): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/SupportMenuInflater( 8167): 	at android.os.Looper.loop(Looper.java:135)
W/SupportMenuInflater( 8167): 	at android.app.ActivityThread.main(ActivityThread.java:5294)
W/SupportMenuInflater( 8167): 	at java.lang.reflect.Method.invoke(Native Method)
W/SupportMenuInflater( 8167): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/SupportMenuInflater( 8167): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
W/SupportMenuInflater( 8167): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
I/ActivityManager( 2215): Displayed cgeo.geocaching/.CacheDetailActivity: +372ms
I/Timeline( 8167): Timeline: Activity_idle id: android.os.BinderProxy@644df2f time:6714058
I/Timeline( 2215): Timeline: Activity_windows_visible id: ActivityRecord{1d09d4f3 u0 cgeo.geocaching/.CacheDetailActivity t1118} time:6714358
I/art     ( 8167): Background sticky concurrent mark sweep GC freed 29539(1488KB) AllocSpace objects, 13(849KB) LOS objects, 11% free, 15MB/17MB, paused 7.089ms total 111.336ms
D/Yamaha-MC1N2-Audio( 1863): yamaha_mc1n2_audio_output_stop()
D/Yamaha-MC1N2-Audio( 1863): yamaha_mc1n2_audio_route_start()
I/dex2oat (13682): dex2oat took 24.458s (threads: 2) arena alloc=1215KB java alloc=10MB native alloc=18MB free=1586KB
I/ActivityManager( 2215): Force stopping com.google.android.gm appid=10055 user=-1: update pkg
W/PackageManager( 2215): Code path for pkg : com.google.android.gm changing from /data/app/com.google.android.gm-2 to /data/app/com.google.android.gm-1
W/PackageManager( 2215): Resource path for pkg : com.google.android.gm changing from /data/app/com.google.android.gm-2 to /data/app/com.google.android.gm-1
W/PackageManager( 2215): Unknown permission com.google.android.calendar.permission.READ_OOBE in package com.google.android.gm
W/PackageManager( 2215): Unknown permission com.google.android.voicesearch.AUDIO_FILE_ACCESS in package com.google.android.gm
W/PackageManager( 2215): Unknown permission com.google.android.email.permission.READ_ATTACHMENT in package com.google.android.gm
W/PackageManager( 2215): Unknown permission com.google.android.email.permission.ACCESS_PROVIDER in package com.google.android.gm
I/ActivityManager( 2215): Killing 13366:com.android.keychain/1000 (adj 15): empty #17
D/WifiService( 2215): acquireWifiLockLocked: WifiLock{NlpWifiLock type=2 binder=android.os.BinderProxy@38ec83ce}
I/ActivityManager( 2215): Force stopping com.google.android.gm appid=10055 user=0: pkg removed
I/InputReader( 2215): Reconfiguring input devices.  changes=0x00000020
D
```

**Comment by samueltardieu** [comment]
> ` W/cgeo ( 8167): [pool-6-thread-1] Working as guest.`

It looks like you are not logged in. Can you please send here the information from "À propos de cgeo" / "Système" ?

**Comment by francois-dorval** [comment]
--- System information ---
Device: GT-I9100 (GT-I9100, Samsung)
Android version: 5.1.1
Android build: cm_i9100-userdebug 5.1.1 LMY48Y 94e1372c6d test-keys
Cgeo version: 2016.01.19
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: fr_FR
Geocaching sites enabled:
- geocaching.com: not logged in (Erreur de connexion)
Installed cgeo plugins:  none
--- End of system information ---

**Comment by samueltardieu** [comment]
Don't hesitate to check your credentials by using "Vérifier les identifiants" just below the password field for geocaching.com.

**Comment by samueltardieu** [comment]
(btw, you might want to delete the log from your first post, it contains your Trello identifier, two Twitter identifiers and two gmail addresses)

**Comment by francois-dorval** [comment]
It is definitely a connection problem...
I re-installed the app, then rebooted... when I try to connect from the settings/services/geocaching.com
it fails.
vérifier les identifiants -> "erreur de connexion : erreur inconnue"...
but I can browse the internet...
I'll try debugging from the source.

Also I'll remove my log, thank you :-)

**Comment by francois-dorval** [comment]
Ok, I get it, I changed my nickname a few days ago...  That's why it wouldn't reconnect.

It can still qualify as a bug because instead of "connection error" I had "unknown error", even when I checked my account from the preferences window...

But feel free to close the bug if you want to. Thank you!
