### ISSUE TITLE
Locus export limit?

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5451]
Can someone with more insight on this feature help to get an answer on this support mail:

Hallo,
I have small problem if I want to show or export them into Locus (Menu / Show on map / Locus or Menu / Show on map / Export to Locus).
If I use it for ie 10 caches all is OK.
If I use it for ie 200 caches, I haven't tab Listing in Locus.

---

I guess there is some limitation in the amount of data we can hand over?!

**Comment by pstorch** [comment]
This is the Exception I get, when trying to export a 1000 Cachelist to Locus:

`02-16 22:02:49.383 835-2738/system_process E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!
02-16 22:02:49.383 835-2738/system_process W/ActivityManager: Exception in new application when starting activity menion.android.locus.pro/com.asamm.locus.basic.MainActivityBasic
                                                              android.os.TransactionTooLargeException
                                                                  at android.os.BinderProxy.transactNative(Native Method)
                                                                  at android.os.BinderProxy.transact(Binder.java:496)
                                                                  at android.app.ApplicationThreadProxy.scheduleLaunchActivity(ApplicationThreadNative.java:797)
                                                                  at com.android.server.am.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1206)
                                                                  at com.android.server.am.ActivityStackSupervisor.attachApplicationLocked(ActivityStackSupervisor.java:561)
                                                                  at com.android.server.am.ActivityManagerService.attachApplicationLocked(ActivityManagerService.java:6182)
                                                                  at com.android.server.am.ActivityManagerService.attachApplication(ActivityManagerService.java:6244)
                                                                  at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:482)
                                                                  at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2305)
                                                                  at android.os.Binder.execTransact(Binder.java:446)
`

So I guess there is a size Limit.

**Comment by pstorch** [comment]
From the Android [API:](https://developer.android.com/reference/android/os/TransactionTooLargeException.html)

> The Binder transaction buffer has a limited fixed size, currently 1Mb, which is shared by all transactions in progress for the process. Consequently this exception can be thrown when there are many transactions in progress even when most of the individual transactions are of moderate size.

**Comment by SammysHP** [comment]
Do we use the latest API?

**Comment by pstorch** [comment]
There is no version number for the Locus API. On the developer page it tells to clone the source directly from Bitbucket. 
The Locus API 4.0 jar in c:geo is from 2011, is that right? The last commit in Locus repo is from February 2016.

**Comment by pstorch** [comment]
I just made another Test. On my device with a test list, the limit is at around 800 Caches.

**Comment by SammysHP** [comment]
AFAIR Menion mentioned some time ago that there are issues with c:geo because it uses an old version of the API and he has to add support for such old stuff. Maybe we should update the API and see if it solves this issue.

**Comment by pstorch** [comment]
I can have a look and update the Locus API in cgeo
