### ISSUE TITLE
Error reading pocket query list

### ISSUE THREAD

**Issue by notspecified** [cgeo/cgeo#5472]
Since this evening i get an error when I try to retrieve a pocket query. Im on 2016.02.23-NB. Am I the only one? Is it gc related, or has it something to do with cgeo?

**Comment by Lineflyer** [comment]
Might be related to either major changes in this NB.
What kind of error do you get and what android device and android version are you using (Can you post your system information here please)?

**Comment by notspecified** [comment]
--- System information ---
Device: C5503 (C5503, Sony)
Android version: 4.4.4
Android build: 10.5.1.A.0.292
Cgeo version: 2016.02.23-NB-891182e
Google Play services: disabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: detailed
HW acceleration: enabled (default state)
System language: de_AT
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins:  none
--- End of system information ---


I just get a toast Msg with the content from the subject, and im redirected to the homescreen!

**Comment by Lineflyer** [comment]
Working for me with  2016.02.23-NB-891182e on Android 4.4.4

@notspecified Can you provide a log (via adb logcat)?

**Comment by notspecified** [comment]
I stripped down the log to entries which contain the keyword "geo", I hope the important line is still in there:

Log-Bericht
02-24 08:35:07.129 I/ActivityManager(861): Timeline: Activity_windows_visible id: ActivityRecord{42e849a8 u0 cgeo.geocaching/.MainActivity t241} time:43169189
02-24 08:35:09.201 I/ActivityManager(10298): Timeline: Activity_launch_request id:cgeo.geocaching time:43171253
02-24 08:35:09.201 I/ActivityManager(861): START u0 {cmp=cgeo.geocaching/.connector.gc.PocketQueryListActivity} from pid 10298
02-24 08:35:09.491 I/ActivityManager(861): Displayed cgeo.geocaching/.connector.gc.PocketQueryListActivity: +260ms
02-24 08:35:09.751 I/ActivityManager(861): Timeline: Activity_windows_visible id: ActivityRecord{4366da00 u0 cgeo.geocaching/.connector.gc.PocketQueryListActivity t241} time:43171803
02-24 08:35:11.363 E/cgeo    (10298): [network-5] GCParser.searchPocketQueryList: error parsing parsing html page
02-24 08:35:11.363 E/cgeo    (10298): java.lang.IndexOutOfBoundsException: Invalid index 2, size is 1
02-24 08:35:11.363 E/cgeo    (10298): 	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
02-24 08:35:11.363 E/cgeo    (10298): 	at java.util.ArrayList.get(ArrayList.java:308)
02-24 08:35:11.363 E/cgeo    (10298): 	at cgeo.geocaching.connector.gc.GCParser.getDownloadablePocketQueries(GCParser.java:1079)
02-24 08:35:11.363 E/cgeo    (10298): 	at cgeo.geocaching.connector.gc.GCParser.access$000(GCParser.java:82)
02-24 08:35:11.363 E/cgeo    (10298): 	at cgeo.geocaching.connector.gc.GCParser$1.call(GCParser.java:1024)
02-24 08:35:11.363 E/cgeo    (10298): 	at cgeo.geocaching.connector.gc.GCParser$1.call(GCParser.java:1010)
02-24 08:35:11.363 E/cgeo    (10298): 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
02-24 08:35:11.363 E/cgeo    (10298): 	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
02-24 08:35:11.363 E/cgeo    (10298): 	at rx.Observable.unsafeSubscribe(Observable.java:8314)
02-24 08:35:11.363 E/cgeo    (10298): 	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
02-24 08:35:11.363 E/cgeo    (10298): 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
02-24 08:35:11.363 E/cgeo    (10298): 	at rx.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:98)
02-24 08:35:11.363 E/cgeo    (10298): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
02-24 08:35:11.363 E/cgeo    (10298): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
02-24 08:35:11.363 E/cgeo    (10298): 	at java.lang.Thread.run(Thread.java:841)
02-24 08:35:11.693 I/ActivityManager(861): Timeline: Activity_windows_visible id: ActivityRecord{42e849a8 u0 cgeo.geocaching/.MainActivity t241} time:43173755
02-24 08:35:11.723 E/WindowManager(10298): android.view.WindowLeaked: Activity cgeo.geocaching.connector.gc.PocketQueryListActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{42e7f128 V.E..... R.....ID 0,0-684,324} that was originally added here
02-24 08:35:11.723 E/WindowManager(10298): 	at cgeo.geocaching.connector.gc.PocketQueryListActivity.onCreate(PocketQueryListActivity.java:27)

**Comment by pstorch** [comment]
Do you have PQs ready for download?
If possible can you send a Screenshot of the Download Tab of the Pocketquery Page?

**Comment by notspecified** [comment]
What do you mean with ready for download? 
I click on the Pq button in the cgeo menu then the ring turns and the Msg says Pq list is loaded, but instead of showing the available PQ it sends me back to the cgeo homescreen, and shows the error Msg.

From which step do you want the screenshot?

**Comment by pstorch** [comment]
Sorry, I meant from the geocaching.com Website.
This Link:
https://www.geocaching.com/pocket/default.aspx#DownloadablePQs

**Comment by notspecified** [comment]
Oh! I think I dont need to send a screenshot... I have no Pq ready for download!
But I have 9 active PQ on the other tab.

The strange thing is that I'm able to download these 9 on my tablet! Here I get no error.
And 5 days ago it even worked on my smartphone...

**Comment by pstorch** [comment]
There were some code changes reading the downloadable PQ from the website.
I think this doesn't handle an empty table correctly. I'm interessted in how the empty table looks like. To handle this case correctly.
As a workaround in the meantime you can execute one of your PQs, so that one is downloadable.

**Comment by notspecified** [comment]
Looool weird stuff! I made one PQ as download available and tried to get it with cgeo: not only this one is displayed but also the other 8 :-D

**Comment by pstorch** [comment]
But only one of them should have the "save" icon.

**Comment by notspecified** [comment]
Exactly!
Now everything is fine again for me, but some lines in the code have to be optimised that this doesn't happen again when no downloadable Pq is available.

**Comment by pstorch** [comment]
Of course, this will be fixed. I think I can do it this evening.

**Comment by samueltardieu** [comment]
@pstorch If the `release` branch is affected (it contains the latest code before switching to OkHttp), don't hesitate to fix it there so that we get a chance to fix it before the release.

**Comment by kumy** [comment]
Automatically closed while merging release into master.

**Comment by kumy** [comment]
@Lineflyer assigned for testing

**Comment by Lineflyer** [comment]
Well testing this is not so easy.
I deactivated my schedules and also manually tried to delete the existing downloadble PQs....they stay available however. Seems I have to be patient until they get deleted automatically.

**Comment by SammysHP** [comment]
I tested it with 2016.02.05 and 2016.02.26, works in both versions with an empty PQ download list.

**Comment by rsudev** [comment]
I cross-checked also with latest master - works

**Comment by Lineflyer** [comment]
Tested and working
