### ISSUE TITLE
Nightly build 2016.02.29 not starting

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5493]
###### Detailed steps causing the problem:
Users reported on support and FB report that the NB is installable but crashed immediately after starting.
Could be related to #5489 

###### Version of c:geo used:
2016.02.29-NB

###### Is the problem reproducible for you:
To be checked

###### Attach system information if available (see c:geo menu -> About c:geo -> System):
Will attach log this evening (or someone can help out please)

**Comment by mucek4** [comment]
CI is updated and not sure if it poses a problem.

**Comment by kumy** [comment]
Confirmed. Will try to test today

**Comment by kumy** [comment]
This is what I get.
```
02-29 14:28:25.033  28740-28740/cgeo.geocaching E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 28740
    Theme: themes:{}
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.SearchView.setSearchableInfo(android.app.SearchableInfo)' on a null object reference
            at cgeo.geocaching.MainActivity.onCreateOptionsMenu(MainActivity.java:302)
            at android.app.Activity.onCreatePanelMenu(Activity.java:2852)
            at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:262)
            at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ActionBarActivity.java:233)
            at android.support.v7.app.ActionBarActivityDelegateICS.onCreatePanelMenu(ActionBarActivityDelegateICS.java:146)
            at android.support.v7.app.ActionBarActivity.onCreatePanelMenu(ActionBarActivity.java:200)
            at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.onCreatePanelMenu(ActionBarActivityDelegateICS.java:293)
            at com.android.internal.policy.PhoneWindow.preparePanel(PhoneWindow.java:617)
            at com.android.internal.policy.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:989)
            at com.android.internal.policy.PhoneWindow$1.run(PhoneWindow.java:320)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5466)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by kumy** [comment]
Bisecting leads to this bad commit 47aaab1c5910abf721175a8644edfc9f48f185db

**Comment by kumy** [comment]
@Bananeweizen I've reverted your commit sorry.

**Comment by kumy** [comment]
Forced build a new NB. Tested ok for me.

**Comment by Lineflyer** [comment]
Assigning @Bananeweizen for review of the above mentioned revert.

**Comment by Lineflyer** [comment]
As this is now two weeks old and no further action has be done, I consider we can close this.
@Bananeweizen Feel free to reopen or whatever necessary as reaction on the mentioned revert.
