### ISSUE TITLE
NoSuchMethodException when opening Cache Details

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#5496]
Since some time I recognize an Exception in the Logs when opening the Cache Details.

###### Detailed steps causing the problem:
- Search a Cache
- Open Cache Details

###### Actual behaviour after performing these steps:
```
cgeo.geocaching W/SupportMenuInflater: Cannot instantiate class: android.support.v7.widget.ShareActionProvider
                                                                    java.lang.NoSuchMethodException: <init> [class android.content.Context]
                                                                        at java.lang.Class.getConstructor(Class.java:531)
                                                                        at java.lang.Class.getConstructor(Class.java:495)
                                                                        at android.support.v7.internal.view.SupportMenuInflater$MenuState.newInstance(SupportMenuInflater.java:481)
                                                                        at android.support.v7.internal.view.SupportMenuInflater$MenuState.readItem(SupportMenuInflater.java:383)
                                                                        at android.support.v7.internal.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:168)
                                                                        at android.support.v7.internal.view.SupportMenuInflater.inflate(SupportMenuInflater.java:118)
                                                                        at cgeo.geocaching.CacheMenuHandler.addMenuItems(CacheMenuHandler.java:111)
                                                                        at cgeo.geocaching.CacheMenuHandler.addMenuItems(CacheMenuHandler.java:116)
                                                                        at cgeo.geocaching.CacheDetailActivity.onCreateOptionsMenu(CacheDetailActivity.java:559)
                                                                        at android.app.Activity.onCreatePanelMenu(Activity.java:2823)
                                                                        at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:262)
                                                                        at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ActionBarActivity.java:233)
                                                                        at android.support.v7.app.ActionBarActivityDelegateICS.onCreatePanelMenu(ActionBarActivityDelegateICS.java:146)
                                                                        at android.support.v7.app.ActionBarActivity.onCreatePanelMenu(ActionBarActivity.java:200)
                                                                        at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.onCreatePanelMenu(ActionBarActivityDelegateICS.java:293)
                                                                        at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:600)
                                                                        at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:972)
                                                                        at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:309)
                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```

###### Version of c:geo used:
2016.03.02-fa68502 developer build

###### Is the problem reproducible for you:
Yes

###### Attach system information if available (see c:geo menu -> About c:geo -> System):
```
--- System information ---
Device: A0001 (bacon, oneplus)
Android version: 5.1.1
Android build: bacon-userdebug 5.1.1 LMY48W e111449243 test-keys
Cgeo version: 2016.03.02-fa68502 developer build
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
Geocaching sites enabled:
 - geocaching.com: logged in (Login OK) / PREMIUM
Installed cgeo plugins: calendar, contacts
--- End of system information ---
```

###### Other comments and remarks:
It doesn't seam to have any impact on the c:geo functionality. The Menu is created. It's just the Stacktrace in the Logs.

**Comment by Bananeweizen** [comment]
If you say "since some time" then I'd assume since the last update of the Google support repository dependency in the gradle script, since this is probably a bug in the support library.

**Comment by rsudev** [comment]
I think I have seen this even longer, just on the flyby, so to speak. I thought this is an 'optional' item, which only works on some versions of Android, therefore I did not dig deeper.

**Comment by pstorch** [comment]
Because the menu still works, this might be no problem.
