### ISSUE TITLE
Crashes when opening cache description with image from dropbox

### ISSUE THREAD

**Issue by MrYaz** [cgeo/cgeo#5505]
###### Detailed steps causing the problem:
- Search for and open GC5XBKZ, GC5NVYK or GC68R58 and many more with the partial name Bild af Piteå.

###### Actual behaviour after performing these steps:
- After a second the app crashes and sends you back to the start page.
- It just happens with some caches, not all.
- One common thing with the ones that causes the crash seems to be that they all have linked images from dropbox in the description using the short url format `https://db.tt/U7YqJqwN`.Don't know if it is a coincident or not.

###### Version of c:geo used:
2016.03.05 NB
The bug has been present in the NB:s for maybe a week by now.

###### Is the problem reproducible for you:
Yes

**Comment by kumy** [comment]
```
03-05 17:17:36.005  26593-26628/cgeo.geocaching W/cgeo﹕ [OkHttp] Failure (825 ms) GET https://dl.dropboxusercontent.com/u/36514766/Bild%20af%20Pite%C3%A5%2032a.jpg (java.lang.IllegalArgumentException: Unexpected char 0xe5 at 30 in content-disposition value: inline; filename="Bild af Piteå 32a.jpg"; filename*=UTF-8''Bild%20af%20Pite%C3%A5%2032a.jpg)
    --------- beginning of crash
03-05 17:17:36.022  26593-26628/cgeo.geocaching E/AndroidRuntime﹕ FATAL EXCEPTION: OkHttp Dispatcher
    Process: cgeo.geocaching, PID: 26593
    Theme: themes:{}
    java.lang.IllegalArgumentException: Unexpected char 0xe5 at 30 in content-disposition value: inline; filename="Bild af Piteå 32a.jpg"; filename*=UTF-8''Bild%20af%20Pite%C3%A5%2032a.jpg
            at okhttp3.Headers$Builder.checkNameAndValue(Headers.java:283)
            at okhttp3.Headers$Builder.add(Headers.java:233)
            at okhttp3.internal.http.Http2xStream.readSpdy3HeadersList(Http2xStream.java:236)
            at okhttp3.internal.http.Http2xStream.readResponseHeaders(Http2xStream.java:150)
            at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:723)
            at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:81)
            at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
            at cgeo.geocaching.network.Network$LoggingInterceptor.intercept(Network.java:220)
            at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:681)
            at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
            at okhttp3.RealCall.getResponse(RealCall.java:241)
            at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
            at cgeo.geocaching.network.Network$HeadersInterceptor.intercept(Network.java:205)
            at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
            at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
            at okhttp3.RealCall.access$100(RealCall.java:30)
            at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
            at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by kumy** [comment]
@samueltardieu would you look?

**Comment by samueltardieu** [comment]
Bug submitted to Dropbox, they violate RFC 2231. In the meantime, the best we can do is detect that and skip the image instead of crashing.
