### ISSUE TITLE
Migrate to Android Fragments?

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5606]
Do we already discuss about such migration?

Isn't it the normal evolution of Android applications?

Benefits could be a better tablet integration, and a starting path to a new design, no?

This should work with older android versions thanks to the App Compat libraries.

`Settings` activity should also migrate to `v7 Preference Support Library`.

**Comment by Bananeweizen** [comment]
I'm in favour of it. However, if you start working on that you might need to reserve some additional hours for teaching me afterwards, so I can still follow. :)

**Comment by kumy** [comment]
Adding `compile 'com.android.support:preference-v7:23.2.1'` lead to NPE on `Livemap`

```
04-02 01:00:54.397 27546-27546/cgeo.geocaching E/cgeo: [main] UncaughtException
                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.maps.mapsforge.MapsforgeMapActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
                                                           at android.app.ActivityThread.access$900(ActivityThread.java:154)
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                           at android.os.Looper.loop(Looper.java:135)
                                                           at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
                                                        Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
                                                           at cgeo.geocaching.maps.CGeoMap.onCreate(CGeoMap.java:498)
                                                           at cgeo.geocaching.maps.mapsforge.MapsforgeMapActivity.onCreate(MapsforgeMapActivity.java:32)
                                                           at android.app.Activity.performCreate(Activity.java:5990)
                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
                                                           at android.app.ActivityThread.access$900(ActivityThread.java:154) 
                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                           at android.os.Looper.loop(Looper.java:135) 
                                                           at android.app.ActivityThread.main(ActivityThread.java:5294) 
                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                           at java.lang.reflect.Method.invoke(Method.java:372) 
                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 

```
Linking to #4903

**Comment by Lineflyer** [comment]
@cgeo/team 
Can this be closed as its too generic and we already started working in that direction?

**Comment by fm-sys** [comment]
> @cgeo/team Can this be closed as its too generic and we already started working in that direction?

I would say so. Such "refactor everything" issues probably bring no real benefit...
