### ISSUE TITLE
ANR/Crash on live map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5690]
##### Detailed steps causing the problem:
- Search for location
- Map search result (using Google Sat view in my case)
- Enable live
- Scroll around some minutes to trigger repeated cache loading
##### Actual behavior after performing these steps:

At some point of time c:geo freezes and runs into ANR 
##### Expected behavior after performing these steps:

Normal operation
##### Version of c:geo used:

2016.04.16-NB
##### Is the problem reproducible for you?

Yes
##### Other comments and remarks:

Log:

```
12:09:40.732 Error cgeo 11252  [main] GoogleMapView.draw
12:09:40.732 Error cgeo 11252  java.lang.ArrayIndexOutOfBoundsException: length=428; index=428
12:09:40.732 Error cgeo 11252   at com.google.android.maps.ItemizedOverlay.getIndexToDraw(ItemizedOverlay.java:211)
12:09:40.732 Error cgeo 11252   at com.google.android.maps.ItemizedOverlay.draw(ItemizedOverlay.java:240)
12:09:40.732 Error cgeo 11252   at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.superDraw(GoogleCacheOverlay.java:101)
12:09:40.732 Error cgeo 11252   at cgeo.geocaching.maps.AbstractItemizedOverlay.draw(AbstractItemizedOverlay.java:44)
12:09:40.732 Error cgeo 11252   at cgeo.geocaching.maps.CachesOverlay.draw(CachesOverlay.java:106)
12:09:40.732 Error cgeo 11252   at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.draw(GoogleCacheOverlay.java:70)
12:09:40.732 Error cgeo 11252   at com.google.android.maps.Overlay.draw(Overlay.java:179)
12:09:40.732 Error cgeo 11252   at com.google.android.maps.OverlayBundle.draw(OverlayBundle.java:42)
12:09:40.732 Error cgeo 11252   at com.google.android.maps.MapView.onDraw(MapView.java:532)
12:09:40.732 Error cgeo 11252   at android.view.View.draw(View.java:15242)
12:09:40.732 Error cgeo 11252   at cgeo.geocaching.maps.google.v1.GoogleMapView.draw(GoogleMapView.java:69)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14136)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14178)
12:09:40.732 Error cgeo 11252   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3284)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14073)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14178)
12:09:40.732 Error cgeo 11252   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3284)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14073)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14178)
12:09:40.732 Error cgeo 11252   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3284)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14073)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14178)
12:09:40.732 Error cgeo 11252   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3284)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14073)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14178)
12:09:40.732 Error cgeo 11252   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3284)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14073)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14178)
12:09:40.732 Error cgeo 11252   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3284)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14073)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14178)
12:09:40.732 Error cgeo 11252   at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
12:09:40.732 Error cgeo 11252   at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
12:09:40.732 Error cgeo 11252   at android.view.ViewRootImpl.draw(ViewRootImpl.java:2748)
12:09:40.732 Error cgeo 11252   at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2614)
12:09:40.732 Error cgeo 11252   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2185)
12:09:40.732 Error cgeo 11252   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
12:09:40.732 Error cgeo 11252   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6496)
12:09:40.732 Error cgeo 11252   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:805)
12:09:40.732 Error cgeo 11252   at android.view.Choreographer.doCallbacks(Choreographer.java:605)
12:09:40.732 Error cgeo 11252   at android.view.Choreographer.doFrame(Choreographer.java:575)
12:09:40.732 Error cgeo 11252   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:791)
12:09:40.732 Error cgeo 11252   at android.os.Handler.handleCallback(Handler.java:733)
12:09:40.732 Error cgeo 11252   at android.os.Handler.dispatchMessage(Handler.java:95)
12:09:40.732 Error cgeo 11252   at android.os.Looper.loop(Looper.java:136)
12:09:40.732 Error cgeo 11252   at android.app.ActivityThread.main(ActivityThread.java:5476)
12:09:40.732 Error cgeo 11252   at java.lang.reflect.Method.invokeNative(Native Method)
12:09:40.732 Error cgeo 11252   at java.lang.reflect.Method.invoke(Method.java:515)
12:09:40.732 Error cgeo 11252   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
12:09:40.732 Error cgeo 11252   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
12:09:40.732 Error cgeo 11252   at dalvik.system.NativeStart.main(Native Method)
12:09:40.732 Error cgeo 11252  [main] UncaughtException
12:09:40.732 Error cgeo 11252  java.lang.ArrayIndexOutOfBoundsException: length=428; index=428
12:09:40.732 Error cgeo 11252   at com.google.android.maps.ItemizedOverlay.getIndexToDraw(ItemizedOverlay.java:211)
12:09:40.732 Error cgeo 11252   at com.google.android.maps.ItemizedOverlay.draw(ItemizedOverlay.java:240)
12:09:40.732 Error cgeo 11252   at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.superDraw(GoogleCacheOverlay.java:101)
12:09:40.732 Error cgeo 11252   at cgeo.geocaching.maps.AbstractItemizedOverlay.draw(AbstractItemizedOverlay.java:44)
12:09:40.732 Error cgeo 11252   at cgeo.geocaching.maps.CachesOverlay.draw(CachesOverlay.java:106)
12:09:40.732 Error cgeo 11252   at cgeo.geocaching.maps.google.v1.GoogleCacheOverlay.draw(GoogleCacheOverlay.java:70)
12:09:40.732 Error cgeo 11252   at com.google.android.maps.Overlay.draw(Overlay.java:179)
12:09:40.732 Error cgeo 11252   at com.google.android.maps.OverlayBundle.draw(OverlayBundle.java:42)
12:09:40.732 Error cgeo 11252   at com.google.android.maps.MapView.onDraw(MapView.java:532)
12:09:40.732 Error cgeo 11252   at android.view.View.draw(View.java:15242)
12:09:40.732 Error cgeo 11252   at cgeo.geocaching.maps.google.v1.GoogleMapView.draw(GoogleMapView.java:69)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14136)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14178)
12:09:40.732 Error cgeo 11252   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3284)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14073)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14178)
12:09:40.732 Error cgeo 11252   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3284)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14073)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14178)
12:09:40.732 Error cgeo 11252   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3284)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14073)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14178)
12:09:40.732 Error cgeo 11252   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3284)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14073)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14178)
12:09:40.732 Error cgeo 11252   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3284)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14073)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14178)
12:09:40.732 Error cgeo 11252   at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3284)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14073)
12:09:40.732 Error cgeo 11252   at android.view.View.getDisplayList(View.java:14178)
12:09:40.732 Error cgeo 11252   at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
12:09:40.732 Error cgeo 11252   at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
12:09:40.732 Error cgeo 11252   at android.view.ViewRootImpl.draw(ViewRootImpl.java:2748)
12:09:40.732 Error cgeo 11252   at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2614)
12:09:40.732 Error cgeo 11252   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2185)
12:09:40.732 Error cgeo 11252   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1249)
12:09:40.732 Error cgeo 11252   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6496)
12:09:40.732 Error cgeo 11252   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:805)
12:09:40.732 Error cgeo 11252   at android.view.Choreographer.doCallbacks(Choreographer.java:605)
12:09:40.732 Error cgeo 11252   at android.view.Choreographer.doFrame(Choreographer.java:575)
12:09:40.732 Error cgeo 11252   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:791)
12:09:40.732 Error cgeo 11252   at android.os.Handler.handleCallback(Handler.java:733)
12:09:40.732 Error cgeo 11252   at android.os.Handler.dispatchMessage(Handler.java:95)
12:09:40.732 Error cgeo 11252   at android.os.Looper.loop(Looper.java:136)
12:09:40.732 Error cgeo 11252   at android.app.ActivityThread.main(ActivityThread.java:5476)
12:09:40.732 Error cgeo 11252   at java.lang.reflect.Meth
12:09:40.857 Error cgeo 11252   at java.lang.reflect.Method.invoke(Method.java:515)
12:09:40.857 Error cgeo 11252   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
12:09:40.857 Error cgeo 11252   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
12:09:40.857 Error cgeo 11252   at dalvik.system.NativeStart.main(Native Method)
```

I remember having seen this kind of exception before but it did not influence the app function. We might even already have this issue somewhere (but I could not find it). New is, that c:geo freezes. Is this related to the recently introduced "Abort on log.e"?

**Comment by SammysHP** [comment]
Does it freeze also with debug disabled? Duplicate of #3507 and #4611. Related: #209, #3209

**Comment by Lineflyer** [comment]
Need to check that. In case it doesn't it seems a duplicate of #4611

**Comment by Lineflyer** [comment]
Having debug disabled the exception is still thrown but c:geo does not freeze/stop.
@samueltardieu How to handle that? The occurence is so frequent, that I would need to disable debug to have c:geo useful for me....that's not so nice for testing purposes.

**Comment by samueltardieu** [comment]
Well, that's unfortunate, but that's the sign of a real bug there. We can downgrade the error into a warning, but it won't make it disappear. Does it also happen with other maps or the new map?

**Comment by Lineflyer** [comment]
@samueltardieu Only on Google maps until now.

**Comment by rsudev** [comment]
This can also appear on the new map, but for a different reason.

**Comment by Lineflyer** [comment]
Following up in new issue

**Comment by pstorch** [comment]
The `Log.e()` for this is here: https://github.com/cgeo/cgeo/blob/891775d79c820488226731d709ba643039210418/main/src/cgeo/geocaching/maps/google/v1/GoogleMapView.java#L71
