### ISSUE TITLE
TitlePageIndicator Crash in CacheDetails and About 

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#5749]
##### Detailed steps causing the problem:
- Open CacheDetails or About

##### Actual behavior after performing these steps:
- c:geo crashes

##### Expected behavior after performing these steps:
- Show CacheDetails or About

##### Version of c:geo used:
Developer build `1f6c4cf`

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
```
About crashing.

##### Other comments and remarks:

```
05-22 22:21:40.427 16800-16800/cgeo.geocaching E/AndroidRuntime: 

FATAL EXCEPTION: main
 Process: cgeo.geocaching, PID: 16801
 java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.CacheDetailActivity}: android.view.InflateException: Binary XML file line #17: Error inflating class com.viewpagerindicator.TitlePageIndicator
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
     at android.app.ActivityThread.access$900(ActivityThread.java:154)
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
     at android.os.Handler.dispatchMessage(Handler.java:102)
     at android.os.Looper.loop(Looper.java:135)
     at android.app.ActivityThread.main(ActivityThread.java:5294)
     at java.lang.reflect.Method.invoke(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:372)
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
  Caused by: android.view.InflateException: Binary XML file line #17: Error inflating class com.viewpagerindicator.TitlePageIndicator
     at android.view.LayoutInflater.createView(LayoutInflater.java:633)
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
     at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:429)
     at android.app.Activity.setContentView(Activity.java:2145)
     at android.support.v7.app.ActionBarActivity.superSetContentView(ActionBarActivity.java:217)
     at android.support.v7.app.ActionBarActivityDelegateICS.setContentView(ActionBarActivityDelegateICS.java:110)
     at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:77)
     at cgeo.geocaching.activity.AbstractActivity.setContentView(AbstractActivity.java:159)
     at cgeo.geocaching.activity.AbstractActivity.onCreate(AbstractActivity.java:131)
     at cgeo.geocaching.activity.AbstractActionBarActivity.onCreate(AbstractActionBarActivity.java:21)
     at cgeo.geocaching.CacheDetailActivity.onCreate(CacheDetailActivity.java:216)
     at android.app.Activity.performCreate(Activity.java:5990)
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311)
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
     at android.app.ActivityThread.access$900(ActivityThread.java:154) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:135) 
     at android.app.ActivityThread.main(ActivityThread.java:5294) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:372) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
  Caused by: java.lang.reflect.InvocationTargetException
     at java.lang.reflect.Constructor.newInstance(Native Method)
     at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
     at android.view.LayoutInflater.createView(LayoutInflater.java:607)
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:429) 
     at android.app.Activity.setContentView(Activity.java:2145) 
     at android.support.v7.app.ActionBarActivity.superSetContentView(ActionBarActivity.java:217) 
     at android.support.v7.app.ActionBarActivityDelegateICS.setContentView(ActionBarActivityDelegateICS.java:110) 
     at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:77) 
     at cgeo.geocaching.activity.AbstractActivity.setContentView(AbstractActivity.java:159) 
     at cgeo.geocaching.activity.AbstractActivity.onCreate(AbstractActivity.java:131) 
     at cgeo.geocaching.activity.AbstractActionBarActivity.onCreate(AbstractActionBarActivity.java:21) 
     at cgeo.geocaching.CacheDetailActivity.onCreate(CacheDetailActivity.java:216) 
     at android.app.Activity.performCreate(Activity.java:5990) 
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311) 
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
     at android.app.ActivityThread.access$900(ActivityThread.java:154) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:135) 
     at android.app.ActivityThread.main(ActivityThread.java:5294) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:372) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
  Caused by: java.lang.UnsupportedOperationException: Can't convert to dimension: type=0x3
     at android.content.res.TypedArray.getDimension(TypedArray.java:495)
     at com.viewpagerindicator.TitlePageIndicator.<init>(TitlePageIndicator.java:147)
     at com.viewpagerindicator.TitlePageIndicator.<init>(TitlePageIndicator.java:0)
     at java.lang.reflect.Constructor.newInstance(Native Method) 
     at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
     at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743) 
     at android.view.LayoutInflater.rInflate(LayoutInflater.java:806) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:504) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:414) 
     at android.view.LayoutInflater.inflate(LayoutInflater.java:365) 
     at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:429) 
     at android.app.Activity.setContentView(Activity.java:2145) 
     at android.support.v7.app.ActionBarActivity.superSetContentView(ActionBarActivity.java:217) 
     at android.support.v7.app.ActionBarActivityDelegateICS.setContentView(ActionBarActivityDelegateICS.java:110) 
     at android.support.v7.app.ActionBarActivity.setContentView(ActionBarActivity.java:77) 
     at cgeo.geocaching.activity.AbstractActivity.setContentView(AbstractActivity.java:159) 
     at cgeo.geocaching.activity.AbstractActivity.onCreate(AbstractActivity.java:131) 
     at cgeo.geocaching.activity.AbstractActionBarActivity.onCreate(AbstractActionBarActivity.java:21) 
     at cgeo.geocaching.CacheDetailActivity.onCreate(CacheDetailActivity.java:216) 
     at android.app.Activity.performCreate(Activity.java:5990) 
     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106) 
     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2311) 
     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
     at android.app.ActivityThread.access$900(ActivityThread.java:154) 
     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
     at android.os.Handler.dispatchMessage(Handler.java:102) 
     at android.os.Looper.loop(Looper.java:135) 
     at android.app.ActivityThread.main(ActivityThread.java:5294) 
     at java.lang.reflect.Method.invoke(Native Method) 
     at java.lang.reflect.Method.invoke(Method.java:372) 
     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 

```

**Comment by Bananeweizen** [comment]
Is this self compiled? If so, please run clean in between. What target level does your emulator/phone have?

I've been using the basic debug build all the time yesterday afternoon after the refactoring of the viewpagerindicator and did not see any issue.

**Comment by pstorch** [comment]
After several cleans/rebuilds I got it working again -> closed
