### ISSUE TITLE
update to mapsforge 0.6.1

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#5787]
I just updated my local branch to mapsforge 0.6.1. However, I see "empty" parts in the map when scrolling around and matching exceptions in the log. This is on an emulator, so I'm not sure if the problem is local only, or if this indicates a bug in the new mapsforge version.

```
06-14 12:28:26.172 1853-2030/cgeo.geocaching E/FileSystemTileCache: external storage appears full
                                                                    java.io.FileNotFoundException: /storage/emulated/0/Android/data/org.mapsforge.android.maps/cache/1/25.tile: open failed: ENOENT (No such file or directory)
                                                                        at libcore.io.IoBridge.open(IoBridge.java:452)
                                                                        at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
                                                                        at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
                                                                        at org.mapsforge.v3.android.maps.mapgenerator.FileSystemTileCache.put(FileSystemTileCache.java:342)
                                                                        at org.mapsforge.v3.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:80)
                                                                        at org.mapsforge.v3.android.maps.PausableThread.run(PausableThread.java:94)
                                                                     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                        at libcore.io.Posix.open(Native Method)
                                                                        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
                                                                        at libcore.io.IoBridge.open(IoBridge.java:438)
                                                                        at java.io.FileOutputStream.<init>(FileOutputStream.java:87) 
                                                                        at java.io.FileOutputStream.<init>(FileOutputStream.java:72) 
                                                                        at org.mapsforge.v3.android.maps.mapgenerator.FileSystemTileCache.put(FileSystemTileCache.java:342) 
                                                                        at org.mapsforge.v3.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:80) 
                                                                        at org.mapsforge.v3.android.maps.PausableThread.run(PausableThread.java:94) 
```

The emulator settings indicate there is sufficient free space. Can someone reproduce this behaviour?

**Comment by rsudev** [comment]
I will give it a check

**Comment by rsudev** [comment]
For me no issues come up (on a real device), so I'll commit the upgrade.
