### ISSUE TITLE
Crash while opening certain cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5810]
##### Detailed steps causing the problem:
From Facebook:
- Open GC6661W

##### Actual behavior after performing these steps:
c:geo crashes reproducibly 

##### Expected behavior after performing these steps:
Cache details should be opened

##### Version of c:geo used:
2016.06.09 (and current master)

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
```
23:20:10.071 Debug cgeo 18728  [network-8] GeokretyConnector.searchTrackables: wpt=GC6661W
23:20:10.072 Debug cgeo 18728  [OkHttp] GET https://www.geocaching.com/seek/cache_details.aspx?decrypt=y&wp=GC6661W&log=y&numlogs=0
23:20:10.072 Debug cgeo 18728  [main] LocationProvider: requesting most precise locations
23:20:10.291 Debug cgeo 18728  [OkHttp] GET https://api.geokretymap.org/export2.php?wpt=GC6661W
23:20:10.403 Debug cgeo 18728  [OkHttp] 301 [Moved Permanently] (281 ms) GET https://www.geocaching.com/seek/cache_details.aspx?decrypt=y&wp=GC6661W&log=y&numlogs=0 (http/1.1)
23:20:10.403 Debug cgeo 18728  [OkHttp] GET https://www.geocaching.com/geocache/GC6661W_kohikohi-paru?decrypt=y&log=y&numlogs=0
23:20:10.404 Debug cgeo 18728  [OkHttp] 302 [Moved Temporarily] (141 ms) GET https://api.geokretymap.org/export2.php?wpt=GC6661W (http/1.1)
23:20:10.509 Debug cgeo 18728  [OkHttp] GET http://api.gkm.kumy.org/export2.php?wpt=GC6661W
23:20:10.617 Debug cgeo 18728  [OkHttp] 200 (40 ms) GET http://api.gkm.kumy.org/export2.php?wpt=GC6661W (http/1.1)
23:20:10.838 Debug cgeo 18728  [OkHttp] 200 (465 ms) GET https://www.geocaching.com/geocache/GC6661W_kohikohi-paru?decrypt=y&log=y&numlogs=0 (http/1.1)
23:20:12.255 Error cgeo 18728  [network-7] UncaughtException
23:20:12.255 Error cgeo 18728  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
23:20:12.255 Error cgeo 18728  	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
23:20:12.255 Error cgeo 18728  	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:108)
23:20:12.255 Error cgeo 18728  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
23:20:12.255 Error cgeo 18728  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
23:20:12.255 Error cgeo 18728  	at java.lang.Thread.run(Thread.java:818)
23:20:12.255 Error cgeo 18728  Caused by: java.lang.IllegalArgumentException: Invalid % sequence at 1: z%u00e4nkisches+Bergvolk&amp;sortdir=desc&amp;sort=placed
23:20:12.256 Error cgeo 18728  	at libcore.net.UriCodec.decode(UriCodec.java:169)
23:20:12.256 Error cgeo 18728  	at java.net.URLDecoder.decode(URLDecoder.java:60)
23:20:12.256 Error cgeo 18728  	at cgeo.geocaching.network.Network.decode(Network.java:479)
23:20:12.256 Error cgeo 18728  	at cgeo.geocaching.connector.gc.GCParser.parseCacheFromText(GCParser.java:479)
23:20:12.256 Error cgeo 18728  	at cgeo.geocaching.connector.gc.GCParser.parseCache(GCParser.java:372)
23:20:12.256 Error cgeo 18728  	at cgeo.geocaching.connector.gc.GCConnector.searchByGeocode(GCConnector.java:187)
23:20:12.256 Error cgeo 18728  	at cgeo.geocaching.models.Geocache.searchByGeocode(Geocache.java:1739)
23:20:12.256 Error cgeo 18728  	at cgeo.geocaching.CacheDetailActivity$2.call(CacheDetailActivity.java:331)
23:20:12.256 Error cgeo 18728  	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
23:20:12.256 Error cgeo 18728  	... 4 more
23:20:12.256 Error cgeo 18728  [network-7] UncaughtException
23:20:12.256 Error cgeo 18728  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
23:20:12.256 Error cgeo 18728  	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:62)
23:20:12.257 Error cgeo 18728  	at rx.internal.schedulers.ExecutorScheduler$ExecutorSchedulerWorker.run(ExecutorScheduler.java:108)
23:20:12.257 Error cgeo 18728  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
23:20:12.257 Error cgeo 18728  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
23:20:12.257 Error cgeo 18728  	at java.lang.Thread.run(Thread.java:818)
23:20:12.257 Error cgeo 18728  Caused by: java.lang.IllegalArgumentException: Invalid % sequence at 1: z%u00e4nkisches+Bergvolk&amp;sortdir=desc&amp;sort=placed
23:20:12.257 Error cgeo 18728  	at libcore.net.UriCodec.decode(UriCodec.java:169)
23:20:12.257 Error cgeo 18728  	at java.net.URLDecoder.decode(URLDecoder.java:60)
23:20:12.257 Error cgeo 18728  	at cgeo.geocaching.network.Network.decode(Network.java:479)
23:20:12.257 Error cgeo 18728  	at cgeo.geocaching.connector.gc.GCParser.parseCacheFromText(GCParser.java:479)
23:20:12.257 Error cgeo 18728  	at cgeo.geocaching.connector.gc.GCParser.parseCache(GCParser.java:372)
23:20:12.257 Error cgeo 18728  	at cgeo.geocaching.connector.gc.GCConnector.searchByGeocode(GCConnector.java:187)
23:20:12.257 Error cgeo 18728  	at cgeo.geocaching.models.Geocache.searchByGeocode(Geocache.java:1739)
23:20:12.257 Error cgeo 18728  	at cgeo.geocaching.CacheDetailActivity$2.call(CacheDetailActivity.java:331)
23:20:12.257 Error cgeo 18728  	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
```

**Comment by UniQP** [comment]
I think there are two problems:

1. We don't handle the InvalidStateException when decoding invalid URLs
2. We accidentally match the invalid URL, when searching for the owner's real name

**Comment by Bananeweizen** [comment]
@UniQP thanks for mentioning the second problem. I have an idea how to fix this without reintroducing the english strings in the regex.
