### ISSUE TITLE
Event cache cannot be added to calendar

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5820]
##### Detailed steps causing the problem:
- Open GC6AK3C
- Select Menu -> Add to calendar from cache details screen (plugin installed)

##### Actual behavior after performing these steps:
Nothing happens

##### Expected behavior after performing these steps:
Calendar app is called

##### Version of c:geo used:
2016.06.09 (from support mail)

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
Specific to this cache

**Comment by Lineflyer** [comment]
Here is the log:
```
22:49:37.472 Error cgeo.calendar 26406  Invalid % sequence at 42: <h1 style="background:none repeat scroll 0% 0% rgb(238, 238, 238);border:1px solid rgb(204, 204, 204);padding:5px 10px;text-align:center;"><strong><font color="red">Das Zweite Rad´l Rast Event auf der schönen Insel Föhr</font></strong></h1> <h2 style="text-align:center;">Bayern in der friesischen Karibik</h2>
22:49:37.472 Error cgeo.calendar 26406  java.lang.IllegalArgumentException: Invalid % sequence at 42: <h1 style="background:none repeat scroll 0% 0% rgb(238, 238, 238);border:1px solid rgb(204, 204, 204);padding:5px 10px;text-align:center;"><strong><font color="red">Das Zweite Rad´l Rast Event auf der schönen Insel Föhr</font></strong></h1> <h2 style="text-align:center;">Bayern in der friesischen Karibik</h2>
22:49:37.473 Error cgeo.calendar 26406  	at libcore.net.UriCodec.decode(UriCodec.java:169)
22:49:37.473 Error cgeo.calendar 26406  	at java.net.URLDecoder.decode(URLDecoder.java:60)
22:49:37.473 Error cgeo.calendar 26406  	at cgeo.calendar.CalendarEntry.getParameter(CalendarEntry.java:52)
22:49:37.473 Error cgeo.calendar 26406  	at cgeo.calendar.CalendarEntry.<init>(CalendarEntry.java:30)
22:49:37.473 Error cgeo.calendar 26406  	at cgeo.calendar.CalendarActivity.onCreate(CalendarActivity.java:28)
22:49:37.473 Error cgeo.calendar 26406  	at android.app.Activity.performCreate(Activity.java:6550)
22:49:37.473 Error cgeo.calendar 26406  	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
22:49:37.473 Error cgeo.calendar 26406  	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3077)
22:49:37.473 Error cgeo.calendar 26406  	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3233)
22:49:37.473 Error cgeo.calendar 26406  	at android.app.ActivityThread.access$1000(ActivityThread.java:197)
22:49:37.473 Error cgeo.calendar 26406  	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
22:49:37.473 Error cgeo.calendar 26406  	at android.os.Handler.dispatchMessage(Handler.java:102)
22:49:37.473 Error cgeo.calendar 26406  	at android.os.Looper.loop(Looper.java:145)
22:49:37.473 Error cgeo.calendar 26406  	at android.app.ActivityThread.main(ActivityThread.java:6873)
22:49:37.474 Error cgeo.calendar 26406  	at java.lang.reflect.Method.invoke(Native Method)
22:49:37.474 Error cgeo.calendar 26406  	at java.lang.reflect.Method.invoke(Method.java:372)
22:49:37.474 Error cgeo.calendar 26406  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
22:49:37.474 Error cgeo.calendar 26406  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by pstorch** [comment]
This Listing has HTML in the Short Description field:

```
<h1 style="background:none repeat scroll 0% 0% rgb(238, 238, 238);border:1px solid rgb(204, 204, 204);padding:5px 10px;text-align:center;"><strong><font color="red">Das Zweite Rad´l Rast Event auf der schönen Insel Föhr</font></strong></h1>
<h2 style="text-align:center;">Bayern in der friesischen Karibik</h2>
```
