### ISSUE TITLE
"Invite Friends" IllegalArgumentException

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#5851]
##### Detailed steps causing the problem:
- Open GC6NW52 (or GC5BRQK)
- menu -> Invite friends

##### Actual behavior after performing these steps:
App crash

##### Expected behavior after performing these steps:
Invite friend activity should start

##### Version of c:geo used:
master

##### Is the problem reproducible for you?
Yes

##### System information:
```
--- System information ---
Device: m8 (cm_m8, htc)
Android version: 5.1.1
Android build: cm_m8-userdebug 5.1.1 LMY48Y a4d1ba3b73 test-keys
Cgeo version: 2016.07.21-621ba36 developer build
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
Log date format: 7/22/2016
Debug mode active: no
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
Installed cgeo plugins: none
--- End of system information ---
```

##### Other comments and remarks:
Works with GC6EJJB

**Comment by kumy** [comment]
```
07-22 23:51:11.405 11656-11656/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: cgeo.geocaching, PID: 11656
                                                                 java.lang.IllegalArgumentException: Message must be 100 chars or less.
                                                                     at com.google.android.gms.appinvite.AppInviteInvitation$IntentBuilder.setMessage(Unknown Source)
                                                                     at cgeo.geocaching.playservices.AppInvite.sendInvite(AppInvite.java:36)
                                                                     at cgeo.geocaching.playservices.AppInvite.send(AppInvite.java:58)
                                                                     at cgeo.geocaching.CacheDetailActivity.onOptionsItemSelected(CacheDetailActivity.java:644)
                                                                     at android.app.Activity.onMenuItemSelected(Activity.java:2885)
                                                                     at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:325)
                                                                     at android.support.v7.app.ActionBarActivity.superOnMenuItemSelected(ActionBarActivity.java:245)
                                                                     at android.support.v7.app.ActionBarActivityDelegateICS.onMenuItemSelected(ActionBarActivityDelegateICS.java:164)
                                                                     at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:131)
                                                                     at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.onMenuItemSelected(ActionBarActivityDelegateICS.java:308)
                                                                     at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1184)
                                                                     at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
                                                                     at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
                                                                     at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
                                                                     at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
                                                                     at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:186)
                                                                     at android.widget.AdapterView.performItemClick(AdapterView.java:305)
                                                                     at android.widget.AbsListView.performItemClick(AbsListView.java:1148)
                                                                     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3059)
                                                                     at android.widget.AbsListView$3.run(AbsListView.java:3866)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5294)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
```
