### ISSUE TITLE
Intermittent crash when switching to Locus

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5874]
With current `master`. I may have switched to another application in the meantime, and then switched back to cgeo. I'm not certain.

```
08-03 11:18:40.913 E/AndroidRuntime(26556): FATAL EXCEPTION: main
08-03 11:18:40.913 E/AndroidRuntime(26556): Process: cgeo.geocaching, PID: 26556
08-03 11:18:40.913 E/AndroidRuntime(26556): Theme: themes:{}
08-03 11:18:40.913 E/AndroidRuntime(26556): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.os.Parcel.readException(Parcel.java:1626)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.content.ContentResolver.query(ContentResolver.java:493)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.content.ContentResolver.query(ContentResolver.java:435)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at locus.api.android.ActionTools.getLocusInfo(ActionTools.java:854)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at locus.api.android.utils.LocusUtils.getActiveVersion(LocusUtils.java:321)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at locus.api.android.utils.LocusUtils.getActiveVersion(LocusUtils.java:293)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at cgeo.geocaching.apps.AbstractLocusApp.isInstalled(AbstractLocusApp.java:48)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at cgeo.geocaching.apps.navi.NavigationAppFactory.getInstalledNavigationApps(NavigationAppFactory.java:206)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at cgeo.geocaching.apps.navi.NavigationAppFactory.getNavigationAppForId(NavigationAppFactory.java:344)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at cgeo.geocaching.apps.navi.NavigationAppFactory.getDefaultNavigationApplication(NavigationAppFactory.java:304)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at cgeo.geocaching.apps.navi.NavigationAppFactory.getDefaultNavigationApplication(NavigationAppFactory.java:339)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at cgeo.geocaching.CacheMenuHandler.onPrepareOptionsMenu(CacheMenuHandler.java:99)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at cgeo.geocaching.CacheMenuHandler.addMenuItems(CacheMenuHandler.java:112)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at cgeo.geocaching.CacheMenuHandler.addMenuItems(CacheMenuHandler.java:116)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at cgeo.geocaching.CacheDetailActivity.onCreateOptionsMenu(CacheDetailActivity.java:570)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.app.Activity.onCreatePanelMenu(Activity.java:2852)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:262)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.support.v7.app.ActionBarActivity.superOnCreatePanelMenu(ActionBarActivity.java:233)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.support.v7.app.ActionBarActivityDelegateICS.onCreatePanelMenu(ActionBarActivityDelegateICS.java:146)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.support.v7.app.ActionBarActivity.onCreatePanelMenu(ActionBarActivity.java:200)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.onCreatePanelMenu(ActionBarActivityDelegateICS.java:293)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at com.android.internal.policy.PhoneWindow.preparePanel(PhoneWindow.java:617)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at com.android.internal.policy.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:989)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at com.android.internal.policy.PhoneWindow$1.run(PhoneWindow.java:320)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.view.Choreographer.doFrame(Choreographer.java:603)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.os.Handler.handleCallback(Handler.java:739)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.os.Handler.dispatchMessage(Handler.java:95)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.os.Looper.loop(Looper.java:148)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at android.app.ActivityThread.main(ActivityThread.java:5461)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at java.lang.reflect.Method.invoke(Native Method)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-03 11:18:40.913 E/AndroidRuntime(26556):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by rsudev** [comment]
We have similar crash reports on Play as well. As this exception is out of our reach (either in the Android system or in the Locus api code) I would suggest to just catch it in ```isInstalled``` and return with false in this case?

**Comment by Lineflyer** [comment]
I do also see these kind of crashes in Google Play.
The proposal from @rsudev sound reasonable. Catch the error, rather than crash as it is outside our code.
