### ISSUE TITLE
Invalid Argument Exception

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5903]
Google play report with 2016.08.14:

```
java.lang.IllegalArgumentException: invalid pixelY coordinate 1024: -406.73785414891347
	at org.mapsforge.core.util.MercatorProjection.pixelYToLatitude(MercatorProjection.java:409)
	at org.mapsforge.core.util.MercatorProjection.fromPixels(MercatorProjection.java:91)
	at cgeo.geocaching.maps.mapsforge.v6.MfMapView.getLatitudeSpan(MfMapView.java:46)
	at cgeo.geocaching.maps.mapsforge.v6.MfMapView.getViewport(MfMapView.java:34)
	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.getVisibleItemsCount(AbstractCachesOverlay.java:54)
	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.getVisibleItemsCount(CachesBundle.java:156)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.countVisibleCaches(NewMap.java:872)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.calculateSubtitle(NewMap.java:852)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.setSubtitle(NewMap.java:832)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.access$300(NewMap.java:99)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap$DisplayHandler.handleMessage(NewMap.java:795)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6117)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

**Comment by Lineflyer** [comment]
Another one from today:
```
java.lang.IllegalArgumentException: invalid pixelY coordinate 384: -144.0
	at org.mapsforge.core.util.MercatorProjection.pixelYToLatitude(MercatorProjection.java:409)
	at org.mapsforge.core.util.MercatorProjection.fromPixels(MercatorProjection.java:91)
	at cgeo.geocaching.maps.mapsforge.v6.MfMapView.getLatitudeSpan(MfMapView.java:46)
	at cgeo.geocaching.maps.mapsforge.v6.MfMapView.getViewport(MfMapView.java:34)
	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.getVisibleItemsCount(AbstractCachesOverlay.java:54)
	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.getVisibleItemsCount(CachesBundle.java:153)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.countVisibleCaches(NewMap.java:872)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.calculateSubtitle(NewMap.java:852)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.setSubtitle(NewMap.java:832)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.access$300(NewMap.java:99)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap$DisplayHandler.handleMessage(NewMap.java:795)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5422)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:914)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:707)
```

**Comment by rsudev** [comment]
based on release and merged to master for testing
