### ISSUE TITLE
No such method error

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5904]
New error first reported with RC and now with 2016.08.14:

```
java.lang.NoSuchMethodError: No static method containsAny(Ljava/lang/CharSequence;[Ljava/lang/CharSequence;)Z in class Lorg/apache/commons/lang3/StringUtils; or its super classes (declaration of 'org.apache.commons.lang3.StringUtils' appears in /system/framework/framework.jar)
	at cgeo.geocaching.models.Geocache.getNonStaticImages(Geocache.java:1819)
	at cgeo.geocaching.CacheDetailActivity.getOrderedPages(CacheDetailActivity.java:2201)
	at cgeo.geocaching.activity.AbstractViewPagerActivity.reinitializeViewPager(AbstractViewPagerActivity.java:277)
	at cgeo.geocaching.CacheDetailActivity.notifyDataSetChanged(CacheDetailActivity.java:792)
	at cgeo.geocaching.CacheDetailActivity.access$500(CacheDetailActivity.java:167)
	at cgeo.geocaching.CacheDetailActivity$LoadCacheHandler.handleRegularMessage(CacheDetailActivity.java:745)
	at cgeo.geocaching.utils.CancellableHandler.handleMessage(CancellableHandler.java:51)
	at android.os.Handler.dispatchMessage(Handler.java)
	at android.os.Looper.loop(Looper.java)
	at android.app.ActivityThread.main(ActivityThread.java)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
```

**Comment by UniQP** [comment]
Duplicate of #5766.

**Comment by Lineflyer** [comment]
Closing here then.
