### ISSUE TITLE
Concurrent modification exception

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5906]
The use of `caches` in `CGeoMap` threads naturally leads to `ConcurrentModificationException` being thrown.

From 2016.06.09 (and thus also present in 2016.06.14).

```
java.util.ConcurrentModificationException
    at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:346)
    at java.util.LinkedHashMap$KeyIterator.next(LinkedHashMap.java:366)
    at java.util.AbstractCollection.toArrayList(AbstractCollection.java:349)
    at java.util.AbstractCollection.toArray(AbstractCollection.java:339)
    at java.util.ArrayList.<init>(ArrayList.java:97)
    at cgeo.geocaching.maps.CGeoMap.doDisplayRun(CGeoMap.java:1386)
    at cgeo.geocaching.maps.CGeoMap.access$2700(CGeoMap.java:103)
    at cgeo.geocaching.maps.CGeoMap$DisplayRunnable.runWithMap(CGeoMap.java:1376)
    at cgeo.geocaching.maps.CGeoMap$DoRunnable.run(CGeoMap.java:1450)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by eddiemuc** [comment]
Is this still an issue? It is quite old but nevertheless Labels as high prio

**Comment by bekuno** [comment]
@eddiemuc This is for the v3 map. I think this won't fix (or is somehow). See the discussion in #7836.
This label is not ok anymore, will remove it.

**Comment by moving-bits** [comment]
texted as "won't fix" more than three years ago, so let's close here finally :-)
