### ISSUE TITLE
Concurrent modification exception in new map

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5907]
It looks like the old  bogus unthread-safe model has been copied there (see #5906).

With release 2016.08.16.

```
java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:787)
	at java.util.HashMap$KeyIterator.next(HashMap.java:814)
	at java.util.AbstractCollection.toArrayList(AbstractCollection.java:349)
	at java.util.AbstractCollection.toArray(AbstractCollection.java:339)
	at java.util.ArrayList.<init>(ArrayList.java:97)
	at cgeo.geocaching.maps.mapsforge.v6.caches.GeoitemLayers.getGeocodes(GeoitemLayers.java:17)
	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.getGeocodes(AbstractCachesOverlay.java:169)
	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.getVisibleItemsCount(AbstractCachesOverlay.java:54)
	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.getVisibleItemsCount(CachesBundle.java:159)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.countVisibleCaches(NewMap.java:872)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.calculateSubtitle(NewMap.java:852)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.setSubtitle(NewMap.java:832)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.access$300(NewMap.java:99)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap$DisplayHandler.handleMessage(NewMap.java:795)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:5373)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
```

**Comment by rsudev** [comment]
While I copied quite some things from the CGeoMap implementation I specifically tried to address these concurrency topics - and obviously failed :-1:
