### ISSUE TITLE
NullPointerException in onFinishEditNoteDialog

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5908]
Stack trace from play console:

```
java.lang.NullPointerException: Attempt to invoke interface method 'void cgeo.geocaching.activity.AbstractViewPagerActivity$PageViewCreator.notifyDataSetChanged()' on a null object reference
    at cgeo.geocaching.CacheDetailActivity.onFinishEditNoteDialog(CacheDetailActivity.java:2373)
    at cgeo.geocaching.ui.EditNoteDialog$2.onClick(EditNoteDialog.java:101)
    at android.view.View.performClick(View.java:5702)
    at android.view.View$PerformClick.run(View.java:22541)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:158)
    at android.app.ActivityThread.main(ActivityThread.java:7229)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

App-Version: 201608161
Android-Version: Android 6.01
Gerät: Galaxy S6 Edge (zerolte)

**Comment by Lineflyer** [comment]
Not seen on Google Play reports for the last years
