### ISSUE TITLE
NewMap: IllegalArgumentException in v6.layers.PositionLayer.draw

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5909]
```
java.lang.IllegalArgumentException: scale factor must not < 1 0.75
    at org.mapsforge.core.util.MercatorProjection.getMapSizeWithScaleFactor(MercatorProjection.java:102)
    at org.mapsforge.core.util.MercatorProjection.calculateGroundResolutionWithScaleFactor(MercatorProjection.java:63)
    at org.mapsforge.core.util.MercatorProjection.metersToPixelsWithScaleFactor(MercatorProjection.java:313)
    at cgeo.geocaching.maps.mapsforge.v6.layers.PositionLayer.draw(PositionLayer.java:51)
    at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:94)
    at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140)
```

App-Version: 201608161
Android-Version: Android 2.3.3 - 2.3.71
Gerät:  Galaxy Y (GT-S5360)

**Comment by Lineflyer** [comment]
Due to the reported Android version and our recent split of legacy version this looks like a "Wont Fix".

**Comment by Lineflyer** [comment]
No longer relevant as we do not support the mentioned Android versions any more.
Also on Google Play I cannot find such a report for the current production versions.
