### ISSUE TITLE
java.lang.IllegalArgumentException: credentials are not valid in Credentials.guard

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5910]
Stacktrace from google play (sample, there are quite a number of them recently):

```
java.lang.IllegalArgumentException: credentials are not valid
	at cgeo.geocaching.settings.Credentials.guard(Credentials.java:93)
	at cgeo.geocaching.settings.Credentials.getUserName(Credentials.java:54)
	at cgeo.geocaching.settings.SettingsActivity.setConnectedUsernameTitle(SettingsActivity.java:609)
	at cgeo.geocaching.settings.SettingsActivity.setAuthTitle(SettingsActivity.java:539)
	at cgeo.geocaching.settings.CredentialsPreference.getOnPreferenceClickListener(CredentialsPreference.java:87)
	at cgeo.geocaching.settings.AbstractClickablePreference.onCreateView(AbstractClickablePreference.java:32)
	at cgeo.geocaching.settings.CredentialsPreference.onCreateView(CredentialsPreference.java:105)
	at android.preference.Preference.getView(Preference.java:564)
	at android.preference.PreferenceGroupAdapter.getView(PreferenceGroupAdapter.java:296)
	at android.widget.AbsListView.obtainView(AbsListView.java:2828)
	at android.widget.ListView.makeAndAddView(ListView.java:1932)
	at android.widget.ListView.fillDown(ListView.java:715)
	at android.widget.ListView.fillFromTop(ListView.java:781)
	at android.widget.ListView.layoutChildren(ListView.java:1723)
	at android.widget.AbsListView.onLayout(AbsListView.java:2626)
	at android.view.View.layout(View.java:16992)
	at android.view.ViewGroup.layout(ViewGroup.java:5409)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
	at android.view.View.layout(View.java:16992)
	at android.view.ViewGroup.layout(ViewGroup.java:5409)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1691)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1467)
	at android.view.View.layout(View.java:16992)
	at android.view.ViewGroup.layout(ViewGroup.java:5409)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1702)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1556)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1465)
	at android.view.View.layout(View.java:16992)
	at android.view.ViewGroup.layout(ViewGroup.java:5409)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:16992)
	at android.view.ViewGroup.layout(ViewGroup.java:5409)
	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
	at android.view.View.layout(View.java:16992)
	at android.view.ViewGroup.layout(ViewGroup.java:5409)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
	at android.view.View.layout(View.java:16992)
	at android.view.ViewGroup.layout(ViewGroup.java:5409)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2483)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2185)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1314)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7062)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:829)
	at android.view.Choreographer.doCallbacks(Choreographer.java:606)
	at android.view.Choreographer.doFrame(Choreographer.java:576)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:815)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6917)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by kumy** [comment]
hum, I think this should fix the issue, 
```
$ git diff
diff --git a/main/src/cgeo/geocaching/settings/SettingsActivity.java b/main/src/cgeo/geocaching/settings/SettingsActivity.java
index 8bbda24..eeaf24a 100644
--- a/main/src/cgeo/geocaching/settings/SettingsActivity.java
+++ b/main/src/cgeo/geocaching/settings/SettingsActivity.java
@@ -607,7 +607,7 @@ public class SettingsActivity extends PreferenceActivity {
         final Credentials credentials = Settings.getCredentials(connector);
 
         getPreference(prefKeyId)
-                .setSummary(StringUtils.isNotBlank(credentials.getUsernameRaw())
+                .setSummary(credentials.isValid()
                         ? getString(R.string.auth_connected_as, credentials.getUserName())
                         : getString(R.string.auth_unconnected));
     }
```

**Comment by rsudev** [comment]
Looks plausible IMO from a technical perspective.
The context seems to imply, that we have a non-empty username, but an empty password.
Can that be possible?

**Comment by kumy** [comment]
I think that was possible with the previous implementation.

**Comment by rsudev** [comment]
That would explain it.

**Comment by Lineflyer** [comment]
I pubslihed a RC version on the beta channel which includes this fix. IMHO this is the best thing we can do do get an impression.

**Comment by rsudev** [comment]
The closing happend because I merged release to master. Checking Play console reveals ~540 beta installs, only one crash so far, but not this one. So I guess this is solved.
