### ISSUE TITLE
IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5913]
This is also a new issue on play, but I currently have no idea how it can happen:

```
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5832)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference
	at butterknife.ButterKnife.findById(ButterKnife.java:343)
	at cgeo.geocaching.CacheDetailActivity.updateOfflineBox(CacheDetailActivity.java:2241)
	at cgeo.geocaching.CachePopupFragment$StoreCacheClickListener$3.call(CachePopupFragment.java:206)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 8 more
```

**Comment by rsudev** [comment]
I now found a way to reproduce:
* open the map and find some unstored cache
* tap it to open the popup
* tap on the store button
* select some target list and tap ok
* while the cache details are still loading, tap on back twice quickly

Remember that with debug log enabled the exception that is thrown leads to an ANR. The exception is nevertheless visible in the log.

This also leads to possible remedies, as it can happen that the popup just vanished before the store operation completes.
