### ISSUE TITLE
Not possible to search for GeoKrety code by scanning QR code from GK label

### ISSUE THREAD

**Issue by frodeseverin** [cgeo/cgeo#5931]
##### Detailed steps causing the problem:
Use case 1
- Tap search box on front page of c:geo
- Enter GeoKret Reference Number, i.e. GKE830, into search box

Use case 2
- Select 'Scan geocode' from droplet menu on frontpage
- Scan QR code from GeoKret label
    - Test label available [here](https://geokrety.org/labels.php?id=59440&nr=X534GL), just hit OK button on linked page.

Use case 3
- Scan QR code of GeoKret label with external app, e.g. Barcode Scanner
    - Test label available [here](https://geokrety.org/labels.php?id=59440&nr=X534GL), just hit OK button on linked page.
- Tap scanned link in Barcode Scanner, and select 'Open with c:geo'

##### Actual behavior after performing these steps:
Use case 1
- Toast displaying the tracking code and the text 'Loading trackable details'
- Opening details page for GeoKret trackable

Use case 2
-  Toast displaying the text

> Didn't find any geocodes in the scan result.
> 
> http://geokrety.org/m/qr.php?nr=X534GL
>         OK

Use case 3
- Toast displaying tracking code of GK, and the text 'Loading trackable details...'
- Return to scanning app.
- Toast displaying 'c:geo can't find that trackable'

##### Expected behavior after performing these steps:
Use case 1
- This is the expected behaviour

Use case 2
- Should behave similar to use case 1

Use case 3
- Should behave similar to use case 1

##### Version of c:geo used:
2016.08.27

##### Is the problem reproducible for you?
Yes/No

##### System information:
```
Device: D5503 (D5503, Sony)
Android version: 5.1.1
Android build: 14.6.A.1.236
Cgeo version: 2016.08.27
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: fast
HW acceleration: enabled (default state)
System language: nb_NO
Log date format: 8/30/2016
Debug mode active: no (cgeo forced to English)
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
   opencaching.de: Logged in (Login OK)
Installed cgeo plugins:  none
```

##### Other comments and remarks:

May be related to #5849 ?

**Comment by kumy** [comment]
Doh! I've never tested point 2!
Here, case 3 just hang the application :/

I'll look soon what's wrong here...

**Comment by kumy** [comment]
```
08-31 20:21:16.658 5678-5678/cgeo.geocaching E/cgeo: [main] unable to retrieve trackable information
                                                     java.lang.NullPointerException: Attempt to invoke virtual method 'void cgeo.geocaching.models.Trackable.setTrackingcode(java.lang.String)' on a null object reference
                                                         at cgeo.geocaching.TrackableActivity$3.call(TrackableActivity.java:223)
                                                         at cgeo.geocaching.TrackableActivity$3.call(TrackableActivity.java:219)
                                                         at rx.internal.util.ActionSubscriber.onNext(ActionSubscriber.java:39)
                                                         at rx.observers.SafeSubscriber.onNext(SafeSubscriber.java:134)
                                                         at rx.internal.producers.SingleProducer.request(SingleProducer.java:65)
                                                         at rx.Subscriber.setProducer(Subscriber.java:209)
                                                         at rx.Subscriber.setProducer(Subscriber.java:205)
                                                         at rx.internal.operators.OperatorSingle$ParentSubscriber.onCompleted(OperatorSingle.java:116)
                                                         at rx.android.app.OperatorConditionalBinding$1.onCompleted(OperatorConditionalBinding.java:59)
                                                         at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.checkTerminated(OperatorObserveOn.java:284)
                                                         at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.call(OperatorObserveOn.java:219)
                                                         at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                         at android.os.Handler.handleCallback(Handler.java:739)
                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                         at android.os.Looper.loop(Looper.java:148)
                                                         at android.app.ActivityThread.main(ActivityThread.java:5461)
                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by kumy** [comment]
Not a cgeo bug, but an api.geokretymap.org bug.
Closing here, and fixed there.

**Comment by frodeseverin** [comment]
@kumy : Thank you for fixing this.

Use case 3, Scanning with external app now works.

However, use case 2, scanning via 'Scan geocode' from droplet menu does not
work.

Internal parsing of URI, i.e. improper handling of domain name?

**Comment by andrixnet** [comment]
subscribe

**Comment by kumy** [comment]
(I've missed today's Nightly build for some minutes.)
@frodeseverin may you try next NB-2016-09-04 please?

**Comment by frodeseverin** [comment]
Tested.

Use case 2 works with NB-2016-09-04.

Now, for completeness, is it possible to search for the GeoKret by
'Tracking Code', e.g. X534GL, and not just 'Reference number', e.g. GKE830
from the search box on the top of the frontpage in c:geo?

Searching for X534GL yealds a toast saying 'c:geo can't find trackable
X534GL...' Seaching for Reverence number works fine.

**Comment by kumy** [comment]
It is technically possible to search GeoKrety by Tracking Code. The code is there but just "disabled" (it's just a matter of [regex](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/connector/trackable/GeokretyConnector.java#L89)). However it's not sufficient to activate as is, as patterns for GK Tracking and other connectors like Travel Bugs may overlap, see #4822.

Closing here.
