### ISSUE TITLE
NPE after editing personal note

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5934]
From Google Play starting with version 2016.08.16:

User comments:
Crash when saving personal note

```
java.lang.NullPointerException: Attempt to invoke interface method 'void cgeo.geocaching.activity.AbstractViewPagerActivity$PageViewCreator.notifyDataSetChanged()' on a null object reference
    at cgeo.geocaching.CacheDetailActivity.onFinishEditNoteDialog(CacheDetailActivity.java:2373)
    at cgeo.geocaching.ui.EditNoteDialog$2.onClick(EditNoteDialog.java:101)
    at android.view.View.performClick(View.java:5197)
    at android.view.View$PerformClick.run(View.java:20926)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:5951)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

**Comment by Lineflyer** [comment]
AFAIR we had another similar issue, which was fixed.
Anyhow I cannot see this crash reason on Google Play since some months. Therefore closing for now.
