### ISSUE TITLE
Live map crashing

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#5948]
Sine this morning we get complaints about freezing/crashing live map.
I can reproduce this after short usage of the live map.

As it wasnt the case last days I assume we have a server issue one again (or still) where cgeo crashes instead of catching the error and giving a proper error message.
Maybe someone can reproduce and provide a log.
IMHO we should urgently fix this because people blame cgeo for this.

**Comment by rsudev** [comment]
I just cross-checked (old mapsforge map), no crash for me. I see sometimes errors in the log, but those are in principal handled.
How this can lead to a crash of the application , I currently have no idea.
There are some instances of crash dumps in Play, where the crash is in the native SSL library. AFAIK we have no chance to catch those.

**Comment by Lineflyer** [comment]
Still happening on my tablet device. Need to take a log for that, which I can only do tomorrow evening earliest. 
The complaints on support mail and social media did not raise again. Seems for now it was something different (e.g. glitch on server side once again) or is unrelated to my finding.

Setting to Fieldtest for myself.

**Comment by Lineflyer** [comment]
@rsudev 
You mean e.g. regarding this reported crash there is nothing we can catch or work around?
```
java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "tiles.geocaching.com": No address associated with hostname
	at rx.exceptions.Exceptions.propagate(Exceptions.java:58)
	at rx.singles.BlockingSingle.value(BlockingSingle.java:93)
	at cgeo.geocaching.connector.gc.Tile.requestMapInfo(Tile.java:237)
	at cgeo.geocaching.connector.gc.GCMap.searchByGeocodes(GCMap.java:68)
	at cgeo.geocaching.maps.CachesOverlay$RequestDetailsThread.run(CachesOverlay.java:295)
Caused by: java.net.UnknownHostException: Unable to resolve host "tiles.geocaching.com": No address associated with hostname
	at java.net.InetAddress.lookupHostByName(InetAddress.java:479)
	at java.net.InetAddress.getAllByNameImpl(InetAddress.java:259)
	at java.net.InetAddress.getAllByName(InetAddress.java:221)
	at okhttp3.Dns$1.lookup(Dns.java:39)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:172)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:138)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:80)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:178)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at cgeo.geocaching.network.Network$HeadersInterceptor.intercept(Network.java:215)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.access$100(RealCall.java:33)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Posix.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
	at java.net.InetAddress.lookupHostByName(InetAddress.java:445)
	... 30 more
```

**Comment by rsudev** [comment]
This stacktrace is not from the live map per se, but from the map popup (I know, that is a technicians distinction, not a user one). There we seemingly do not have the exception handling in place we use for the core map tile download.
So this is definitely something we can address (with the result that the user sees missing info on popups) and I need to re-check whether the observations I made really are from the popup than the map is assumed.
Regarding the native crashes we can't handle, that are rather those (with the same network-level issues behind them, only showing the backtrace):
```
backtrace:
#00 pc 0001180c /system/lib/libc.so (dlfree+1191)
#01 pc 0000dd47 /system/lib/libc.so (free+10)
#02 pc 000823ad /system/lib/libcrypto.so (CRYPTO_free+24)
#03 pc 0002ab09 /system/lib/libssl.so (ssl_parse_serverhello_tlsext+244)
#04 pc 00016b3d /system/lib/libssl.so (ssl3_get_server_hello+924)
#05 pc 00019633 /system/lib/libssl.so (ssl3_connect+642)
#06 pc 00024fd1 /system/lib/libssl.so (SSL_do_handshake+72)
#07 pc 0000c5f9 /system/lib/libjavacrypto.so
#08 pc 0001eacc /system/lib/libdvm.so (dvmPlatformInvoke+112)
#09 pc 0004efab /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*)+398)
#10 pc 00027ee0 /system/lib/libdvm.so
#11 pc 0002ee88 /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
#12 pc 0002c534 /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
#13 pc 000613b3 /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+338)
#14 pc 000613d7 /system/lib/libdvm.so (dvmCallMethod(Thread*, Method const*, Object*, JValue*, ...)+20)
#15 pc 000560bb /system/lib/libdvm.so
#16 pc 0000d280 /system/lib/libc.so (__thread_entry+72)
#17 pc 0000d41c /system/lib/libc.so (pthread_create+240)
```
But they are much rarer now.
