### ISSUE TITLE
Gradle build daemon crash (or kill)

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#5963]
This also seem to make builds fail as tests are interrupted and no results are gathered.

```
Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
04:46.040  
04:46.040  * Try:
04:46.040  Run with --info or --debug option to get more log output.
04:46.040  
04:46.040  * Exception is:
04:46.122  org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
04:46.123  	at org.gradle.launcher.daemon.client.DaemonClient.handleDaemonDisappearance(DaemonClient.java:222)
04:46.123  	at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:198)
04:46.123  	at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:162)
04:46.124  	at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:55)
04:46.124  	at org.gradle.launcher.daemon.client.SingleUseDaemonClient.execute(SingleUseDaemonClient.java:37)
04:46.124  	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
04:46.124  	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
04:46.124  	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:244)
04:46.124  	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:217)
04:46.124  	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:33)
04:46.124  	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
04:46.124  	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
04:46.124  	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
04:46.125  	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:210)
04:46.125  	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:174)
04:46.125  	at org.gradle.launcher.Main.doAction(Main.java:33)
04:46.125  	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
04:46.125  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04:46.125  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
04:46.125  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:46.125  	at java.lang.reflect.Method.invoke(Method.java:483)
04:46.126  	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
04:46.126  	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
04:46.126  	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
04:46.126  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
04:46.126  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
04:46.166  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
04:46.166  	at java.lang.reflect.Method.invoke(Method.java:483)
04:46.166  	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
04:46.166  	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
04:46.167  	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

@Bananeweizen Any idea of what might be wrong?

Would there be a timeout somewhere in the Jenkins configuration that would kill the gradle daemon process?

**Comment by samueltardieu** [comment]
Mmm, it looks like the process might have been killed because the emulator needs more memory. I'll try to increase the alloted resources.

```
[  487.012644] emulator64-x86 invoked oom-killer: gfp_mask=0x2400040(GFP_NOFS), order=0, oom_score_adj=0
[  487.012647] emulator64-x86 cpuset=d4db6a713e3663576e3bd7ccd7381762373dfb4b4b145d01e64672c333e13a14 mems_allowed=0
[  487.012652] CPU: 11 PID: 2778 Comm: emulator64-x86 Tainted: G           O    4.7.2-1-ARCH #1
[  487.012653] Hardware name: Dell Inc. Precision Tower 5810/0K240Y, BIOS A09 09/26/2015
[  487.012654]  0000000000000286 0000000046695192 ffff880efb10bc68 ffffffff812eb132
[  487.012656]  ffff880efb10bd50 ffff880f592db900 ffff880efb10bcd8 ffffffff811f6e5c
[  487.012658]  ffff880f592db900 ffff8810162d7c00 ffff880efb10bca8 ffffffff811e69a5
[  487.012659] Call Trace:
[  487.012664]  [<ffffffff812eb132>] dump_stack+0x63/0x81
[  487.012668]  [<ffffffff811f6e5c>] dump_header+0x60/0x1e8
[  487.012671]  [<ffffffff811e69a5>] ? get_mem_cgroup_from_mm+0x75/0xe0
[  487.012674]  [<ffffffff811762fa>] oom_kill_process+0x22a/0x440
[  487.012675]  [<ffffffff811e9b59>] ? mem_cgroup_iter+0x129/0x3d0
[  487.012677]  [<ffffffff811ec148>] mem_cgroup_out_of_memory+0x308/0x350
[  487.012679]  [<ffffffff811ecd60>] mem_cgroup_oom_synchronize+0x360/0x370
[  487.012680]  [<ffffffff811e78b0>] ? __mem_cgroup_insert_exceeded+0x80/0x80
[  487.012682]  [<ffffffff81176a54>] pagefault_out_of_memory+0x44/0xc0
[  487.012685]  [<ffffffff810652d6>] mm_fault_error+0x86/0x1b0
[  487.012687]  [<ffffffff810658b8>] __do_page_fault+0x4b8/0x510
[  487.012689]  [<ffffffff81065932>] do_page_fault+0x22/0x30
[  487.012692]  [<ffffffff815e07b8>] page_fault+0x28/0x30
[  487.012693] Task in /docker/d4db6a713e3663576e3bd7ccd7381762373dfb4b4b145d01e64672c333e13a14 killed as a result of limit of /docker/d4db6a713e3663576e3bd7ccd7381762373dfb4b4b145d01e64672c333e13a14
[  487.012696] memory: usage 4194304kB, limit 4194304kB, failcnt 314774
[  487.012697] memory+swap: usage 4194304kB, limit 8388608kB, failcnt 0
[  487.012698] kmem: usage 10584kB, limit 9007199254740988kB, failcnt 0
[  487.012698] Memory cgroup stats for /docker/d4db6a713e3663576e3bd7ccd7381762373dfb4b4b145d01e64672c333e13a14: cache:976KB rss:4182648KB rss_huge:1150976KB mapped_file:412KB dirty:24KB writeback:24KB swap:0KB inactive_anon:16KB active_anon:4182648KB inactive_file:540KB active_file:372KB unevictable:0KB
[  487.012707] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
[  487.012771] [ 2167]  1000  2167     1112       20       8       3        0             0 sh
[  487.012773] [ 2197]  1000  2197     4492       65      14       3        0             0 start.sh
[  487.012775] [ 2217]  1000  2217    29029       43      17       3        0             0 adb
[  487.012777] [ 2256]  1000  2256  5308727    63847     275      10        0             0 java
[  487.012790] [ 2774]  1000  2774     1112       21       8       3        0             0 sh
[  487.012791] [ 2778]  1000  2778   839713   314978     644       6        0             0 emulator64-x86
[  487.012793] [ 2782]  1000  2782  1092941    30536     180       7        0             0 java
[  487.012794] [ 2830]  1000  2830  3029372   633572    1505      15        0             0 java
[  487.012804] Memory cgroup out of memory: Kill process 2830 (java) score 605 or sacrifice child
```

**Comment by kumy** [comment]
HUm, looks like what's wrong with executor running on my nas. with limited ram.
Build and tests are passing, but all the stuff to get the "results" fails...

**Comment by samueltardieu** [comment]
Fixed by increasing memory from 4GB to 8GB per slave.
