### ISSUE TITLE
java.lang.SecurityException accessing location through gms

### ISSUE THREAD

**Issue by rsudev** [cgeo/cgeo#5965]
We regularly get such crashes fro Android 6.0 and 7.0 devices. I could reproduce it by denying location access for c:geo in the app settings.
Perhaps we should try to expect this, capture it and inform the user accordingly.

```
java.lang.SecurityException: Client must have ACCESS_FINE_LOCATION permission to request PRIORITY_HIGH_ACCURACY locations.
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.os.Parcel.readException(Parcel.java:1573)
	at com.google.android.gms.location.internal.zzi$zza$zza.zza(Unknown Source)
	at com.google.android.gms.location.internal.zzk.zza(Unknown Source)
	at com.google.android.gms.location.internal.zzl.zza(Unknown Source)
	at com.google.android.gms.location.internal.zzd$7.zza(Unknown Source)
	at com.google.android.gms.location.internal.zzd$7.zza(Unknown Source)
	at com.google.android.gms.internal.zzpr$zza.zzb(Unknown Source)
	at com.google.android.gms.internal.zzqa.zzf(Unknown Source)
	at com.google.android.gms.internal.zzqa.zzd(Unknown Source)
	at com.google.android.gms.internal.zzqf.zzd(Unknown Source)
	at com.google.android.gms.internal.zzqd.zzd(Unknown Source)
	at com.google.android.gms.location.internal.zzd.requestLocationUpdates(Unknown Source)
	at cgeo.geocaching.playservices.LocationProvider.updateRequest(LocationProvider.java:54)
	at cgeo.geocaching.playservices.LocationProvider.onConnected(LocationProvider.java:140)
	at com.google.android.gms.common.internal.zzl.zzo(Unknown Source)
	at com.google.android.gms.internal.zzqd.zzm(Unknown Source)
	at com.google.android.gms.internal.zzqb.zzapm(Unknown Source)
	at com.google.android.gms.internal.zzqb.onConnected(Unknown Source)
	at com.google.android.gms.internal.zzqf.onConnected(Unknown Source)
	at com.google.android.gms.internal.zzpu.onConnected(Unknown Source)
	at com.google.android.gms.common.internal.zzk$1.onConnected(Unknown Source)
	at com.google.android.gms.common.internal.zzd$zzj.zzarz(Unknown Source)
	at com.google.android.gms.common.internal.zzd$zza.zzc(Unknown Source)
	at com.google.android.gms.common.internal.zzd$zza.zzx(Unknown Source)
	at com.google.android.gms.common.internal.zzd$zze.zzasb(Unknown Source)
	at com.google.android.gms.common.internal.zzd$zzd.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5461)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by samueltardieu** [comment]
And we should use the new priority model.
