### ISSUE TITLE
Crash on start of compass

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6087]
##### Detailed steps causing the problem:
- Save a cache to a list
- Open cache details
- Select default navigation icon to start the compass

##### Actual behavior after performing these steps:
- App freezes, 

##### Expected behavior after performing these steps:
- Compass should work normal

##### Version of c:geo used:
2016.11.05-NB-23c5988

##### Is the problem reproducible for you?
Yes

##### System information:
```
Samsung Galaxy S4
Android 5.0.1
```

##### Other comments and remarks:
Screenshot:
![screenshot_2016-11-05-15-17-28](https://cloud.githubusercontent.com/assets/949669/20030767/0ea7e012-a36c-11e6-89f9-967c3aecf41f.png)

Log:
```
15:21:08.680 Error cgeo 15089  [main] UncaughtException
15:21:08.680 Error cgeo 15089  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
15:21:08.680 Error cgeo 15089  	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:113)
15:21:08.680 Error cgeo 15089  	at android.os.Handler.handleCallback(Handler.java:739)
15:21:08.680 Error cgeo 15089  	at android.os.Handler.dispatchMessage(Handler.java:95)
15:21:08.680 Error cgeo 15089  	at android.os.Looper.loop(Looper.java:145)
15:21:08.680 Error cgeo 15089  	at android.app.ActivityThread.main(ActivityThread.java:5951)
15:21:08.680 Error cgeo 15089  	at java.lang.reflect.Method.invoke(Native Method)
15:21:08.680 Error cgeo 15089  	at java.lang.reflect.Method.invoke(Method.java:372)
15:21:08.680 Error cgeo 15089  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
15:21:08.680 Error cgeo 15089  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
15:21:08.680 Error cgeo 15089  Caused by: java.lang.IllegalArgumentException: delay < 0: -134000000
15:21:08.680 Error cgeo 15089  	at io.reactivex.android.schedulers.HandlerScheduler$HandlerWorker.schedule(HandlerScheduler.java:60)
15:21:08.680 Error cgeo 15089  	at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:307)
15:21:08.680 Error cgeo 15089  	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
15:21:08.680 Error cgeo 15089  	... 8 more
15:21:08.680 Error cgeo 15089  [main] UncaughtException
15:21:08.680 Error cgeo 15089  java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
15:21:08.680 Error cgeo 15089  	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:113)
15:21:08.680 Error cgeo 15089  	at android.os.Handler.handleCallback(Handler.java:739)
15:21:08.680 Error cgeo 15089  	at android.os.Handler.dispatchMessage(Handler.java:95)
15:21:08.680 Error cgeo 15089  	at android.os.Looper.loop(Looper.java:145)
15:21:08.680 Error cgeo 15089  	at android.app.ActivityThread.main(ActivityThread.java:5951)
15:21:08.680 Error cgeo 15089  	at java.lang.reflect.Method.invoke(Native Method)
15:21:08.680 Error cgeo 15089  	at java.lang.reflect.Method.invoke(Method.java:372)
15:21:08.680 Error cgeo 15089  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
15:21:08.680 Error cgeo 15089  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
15:21:08.680 Error cgeo 15089  Caused by: java.lang.IllegalArgumentException: delay < 0: -134000000
15:21:08.680 Error cgeo 15089  	at io.reactivex.android.schedulers.HandlerScheduler$HandlerWorker.schedule(HandlerScheduler.java:60)
15:21:08.680 Error cgeo 15089  	at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:307)
15:21:08.680 Error cgeo 15089  	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
15:21:08.680 Error cgeo 15089  	... 8 more
```

**Comment by Lineflyer** [comment]
Update: 
Also reproducible with seconds device (not after new installation). So I guess it should be reproducible also for others.

**Comment by samueltardieu** [comment]
This looks like a bug in RxJava or RxAndroid. I should be able to install a workaround easily enough until this is fixed.

**Comment by samueltardieu** [comment]
I've labeled this issue with "Workaround installed" and will let it open until this is resolved in RxAndroid.
