### ISSUE TITLE
cgeo crashes when refreshing certain caches

### ISSUE THREAD

**Issue by alex7654** [cgeo/cgeo#6092]
##### Detailed steps causing the problem:
- Save either GC2MCW3 or GC90D6 to an empty list
- select "Refresh all" caches in this list
- cgeo crashes

##### Actual behavior after performing these steps:
cgeo crashes

##### Expected behavior after performing these steps:
the caches should get refreshed

##### Version of c:geo used:
2016.11.06-NB-cc2aae8

##### Is the problem reproducible for you?
Yes, crashes occur every time I try to refresh one of the both caches listed above

##### System information:
```
Android 4.4.2
tried on N7100 (Galaxy Note II) and Galaxy Tab 10.1 2014 edition
```

##### Other comments and remarks:
Refreshing both caches works well using release 2016.11.05

**Comment by pstorch** [comment]
Can reproduce, got the following error in the logs:

```
E/AndroidRuntime: FATAL EXCEPTION: RxComputationThreadPool-4
                  Process: cgeo.geocaching, PID: 3076
                  java.lang.NullPointerException: onNext called with null. Null values are generally not allowed in 2.x operators and sources.
                      at io.reactivex.internal.operators.observable.ObservableCreate$CreateEmitter.onNext(ObservableCreate.java:63)
                      at cgeo.geocaching.network.HtmlImage$3$2.run(HtmlImage.java:235)
                      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
                      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                      at java.lang.Thread.run(Thread.java:818)
E/AbstractTracker: Can't create handler inside thread that has not called Looper.prepare()
```
