### ISSUE TITLE
Reappearance of empty logbooks in nightly build

### ISSUE THREAD

**Issue by alex7654** [cgeo/cgeo#6130]
##### Detailed steps causing the problem:
cgeo shows an empty logbook, for example when opening GC6RDC2. The issue with empty logbooks seemed to be resolved, but now reappeared in nightly build 2016.11.16-NB-d2c2bc9 (or one day before).

##### Actual behavior after performing these steps:
No log entries are shown, even after refreshing the cache.

##### Expected behavior after performing these steps:
Log entries should be dislayed

##### Version of c:geo used:
2016.11.16-NB-d2c2bc9

##### Is the problem reproducible for you?
Yes

##### System information:
Galaxy Note II, Galaxy Tab 10.1 214 Edition, Android 4.4.2

##### Other comments and remarks:
none

**Comment by alex7654** [comment]
PS: Date format 16.11.2016 is selected in my account preferences.

**Comment by samueltardieu** [comment]
```
11-16 09:23:34.204 W/cgeo    (29213): java.io.IOException: closed
11-16 09:23:34.204 W/cgeo    (29213): 	at okio.RealBufferedSource$1.read(RealBufferedSource.java:405)
11-16 09:23:34.204 W/cgeo    (29213): 	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:522)
11-16 09:23:34.204 W/cgeo    (29213): 	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:129)
11-16 09:23:34.204 W/cgeo    (29213): 	at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:246)
11-16 09:23:34.204 W/cgeo    (29213): 	at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1271)
11-16 09:23:34.204 W/cgeo    (29213): 	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:810)
11-16 09:23:34.204 W/cgeo    (29213): 	at com.fasterxml.jackson.databind.ObjectReader.readTree(ObjectReader.java:1331)
11-16 09:23:34.204 W/cgeo    (29213): 	at cgeo.geocaching.connector.gc.GCParser$4.subscribe(GCParser.java:1813)
11-16 09:23:34.204 W/cgeo    (29213): 	at io.reactivex.internal.operators.observable.ObservableCreate.subscribeActual(ObservableCreate.java:40)
11-16 09:23:34.204 W/cgeo    (29213): 	at io.reactivex.Observable.subscribe(Observable.java:10179)
11-16 09:23:34.204 W/cgeo    (29213): 	at io.reactivex.internal.operators.observable.ObservableDefer.subscribeActual(ObservableDefer.java:39)
11-16 09:23:34.204 W/cgeo    (29213): 	at io.reactivex.Observable.subscribe(Observable.java:10179)
11-16 09:23:34.204 W/cgeo    (29213): 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
11-16 09:23:34.204 W/cgeo    (29213): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
11-16 09:23:34.204 W/cgeo    (29213): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-16 09:23:34.204 W/cgeo    (29213): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
11-16 09:23:34.204 W/cgeo    (29213): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
11-16 09:23:34.204 W/cgeo    (29213): 	at java.lang.Thread.run(Thread.java:761)
```

**Comment by rsudev** [comment]
Interestingly enough there is a 200 response right in front of this (at least in my log)

**Comment by samueltardieu** [comment]
The stream is closed early. While adding the missing stream close operations to free up resources, I think I've misplaced one of them (while the operation on the stream is done asynchronously).

**Comment by samueltardieu** [comment]
A new nightly build has been launched. -NB1 should be available shortly.

**Comment by Lineflyer** [comment]
This is an issue only valid on `master`, so no impact on release, right?
