### ISSUE TITLE
App freezes when I enter "live map" and leave it again

### ISSUE THREAD

**Issue by AndersBillLinden** [cgeo/cgeo#6140]
##### Detailed steps causing the problem:
- Debug app in Android Studio
- Press "live map", the maps tiles builds up
- Go backwards

##### Actual behavior after performing these steps:
No button presses will result in anything

##### Expected behavior after performing these steps:
Buttons should work as normal

##### Version of c:geo used:
https://github.com/cgeo/cgeo/commit/f5c9f7801ab56f785c28ae748a8155768c41bb3f

##### Is the problem reproducible for you?
Yes

##### System information:
```
Version 2016.11.17-f5c9f78 developer build
```

##### Other comments and remarks:
Output follows

````
11/17 22:12:26: Launching main
$ adb push D:\projekt\cgeo\main\build\outputs\apk\cgeo-debug.apk /data/local/tmp/cgeo.geocaching
$ adb shell pm install -r "/data/local/tmp/cgeo.geocaching"
	pkg: /data/local/tmp/cgeo.geocaching
Success


$ adb shell am start -n "cgeo.geocaching/cgeo.geocaching.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Connecting to cgeo.geocaching
W/ResourcesManager: Asset path '/system/framework/com.google.android.maps.jar' does not exist or contains no resources.
W/ActivityThread: Application cgeo.geocaching is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/art: Debugger is active
Connected to the target VM, address: 'localhost:8607', transport: 'socket'
I/System.out: Debugger has connected
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1406)
I/InstantRun: Instant Run Runtime started. Android package is cgeo.geocaching, real application class is cgeo.geocaching.CgeoApplication.
W/art: Failed to find OatDexFile for DexFile /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_9-classes.dex ( canonical path /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_9-classes.dex) with checksum 0xe536b365 in OatFile /data/data/cgeo.geocaching/cache/slice-slice_9-classes.dex
W/art: Failed to find OatDexFile for DexFile /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_8-classes.dex ( canonical path /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_8-classes.dex) with checksum 0x2f60317c in OatFile /data/data/cgeo.geocaching/cache/slice-slice_8-classes.dex
W/art: Failed to find OatDexFile for DexFile /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_7-classes.dex ( canonical path /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_7-classes.dex) with checksum 0xbc7f9a20 in OatFile /data/data/cgeo.geocaching/cache/slice-slice_7-classes.dex
W/art: Failed to find OatDexFile for DexFile /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_6-classes.dex ( canonical path /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_6-classes.dex) with checksum 0x5a2e08b5 in OatFile /data/data/cgeo.geocaching/cache/slice-slice_6-classes.dex
W/art: Failed to find OatDexFile for DexFile /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_5-classes.dex ( canonical path /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_5-classes.dex) with checksum 0x237a4b00 in OatFile /data/data/cgeo.geocaching/cache/slice-slice_5-classes.dex
W/art: Failed to find OatDexFile for DexFile /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_4-classes.dex ( canonical path /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_4-classes.dex) with checksum 0xacf22913 in OatFile /data/data/cgeo.geocaching/cache/slice-slice_4-classes.dex
W/art: Failed to find OatDexFile for DexFile /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_3-classes.dex ( canonical path /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_3-classes.dex) with checksum 0x59a44dc5 in OatFile /data/data/cgeo.geocaching/cache/slice-slice_3-classes.dex
W/art: Failed to find OatDexFile for DexFile /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_2-classes.dex ( canonical path /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_2-classes.dex) with checksum 0xc082e38d in OatFile /data/data/cgeo.geocaching/cache/slice-slice_2-classes.dex
W/art: Failed to find OatDexFile for DexFile /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_1-classes.dex ( canonical path /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_1-classes.dex) with checksum 0xa217b7bb in OatFile /data/data/cgeo.geocaching/cache/slice-slice_1-classes.dex
W/art: Failed to find OatDexFile for DexFile /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_0-classes.dex ( canonical path /data/data/cgeo.geocaching/files/instant-run/dex/slice-slice_0-classes.dex) with checksum 0x5ca935ac in OatFile /data/data/cgeo.geocaching/cache/slice-slice_0-classes.dex
I/Configs: The framework log level is 1.
D/ContextHelper: convertTheme. context->name=cgeo.geocaching themeResourceId=2131492934
I/Timeline: Timeline: Activity_launch_request id:cgeo.geocaching time:85477942
D/OpenGLRenderer: Render dirty regions requested: true
I/Adreno-EGL: <qeglDrvAPI_eglInitialize:410>: EGL 1.4 QUALCOMM build:  ()
              OpenGL ES Shader Compiler Version: E031.25.03.00
              Build Date: 12/12/14 금
              Local Branch: LA.BF.1.1_RB1.05.00.00.002.031_20141212_01821442
              Remote Branch: 
              Local Patches: 
              Reconstruct Branch: 
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Enabling debug mode 0
D/Atlas: Validating map...
D/ContextHelper: convertTheme. context->name=cgeo.geocaching themeResourceId=2131492875
D/ContextHelper: convertTheme. context->name=cgeo.geocaching themeResourceId=2131493056
I/CliptrayUtils: CliptrayUtils created!! mTextView = android.support.v7.widget.SearchView$SearchAutoComplete{14918360 VFED..C. ......I. 0,0-0,0 #7f0f0046 app:id/search_src_text}
D/BubblePopupHelper: isShowingBubblePopup : false
I/Choreographer: Skipped 41 frames!  The application may be doing too much work on its main thread.
D/ShowcaseView: Recalculated
I/CliptrayUtils: CliptrayUtils created!! mTextView = android.widget.TextView{255c84d1 V.ED.... ......I. 0,0-0,0 #7f0f005f app:id/system}
D/BubblePopupHelper: isShowingBubblePopup : false
D/BubblePopupHelper: isShowingBubblePopup : false
W/Java7Support: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
D/BubblePopupHelper: isShowingBubblePopup : false
D/BubblePopupHelper: isShowingBubblePopup : false
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3abe1d6e time:85479918
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3c10f415 time:85479918
I/art: Background sticky concurrent mark sweep GC freed 82776(8MB) AllocSpace objects, 127(3MB) LOS objects, 18% free, 47MB/58MB, paused 2.063ms total 143.252ms
I/ViewRootImpl: ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=85484209, downTime=85484209, deviceId=-1, source=0x101 } to com.android.internal.policy.impl.PhoneWindow$DecorView{de9968e V.E..... R....... 0,0-1440,2392}
I/ViewRootImpl: ViewRoot's KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=85484221, downTime=85484209, deviceId=-1, source=0x101 } to com.android.internal.policy.impl.PhoneWindow$DecorView{de9968e V.E..... R....... 0,0-1440,2392}
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3c10f415 time:85484338
I/ViewRootImpl: ViewRoot's Touch Event : ACTION_DOWN
I/ViewRootImpl: ViewRoot's Touch Event : ACTION_UP
W/cgeo: [main] No Google API key available.
I/Timeline: Timeline: Activity_launch_request id:cgeo.geocaching time:85488592
D/ContextHelper: convertTheme. context->name=cgeo.geocaching themeResourceId=2131492875
D/ContextHelper: convertTheme. context->name=cgeo.geocaching themeResourceId=2131493056
I/art: Background partial concurrent mark sweep GC freed 58127(2MB) AllocSpace objects, 54(3MB) LOS objects, 37% free, 54MB/86MB, paused 4.806ms total 128.211ms
I/SensorManager: registerListenerImpl() [Sensor: LGE Rotation Vector Sensor, Rate: 200000, SensorEventListener: cgeo.geocaching.sensors.RotationProvider$1$1@1f570fdb] bycgeo.geocaching.sensors.RotationProvider$1.subscribe():80
I/art: Background sticky concurrent mark sweep GC freed 1483(124KB) AllocSpace objects, 3(48KB) LOS objects, 0% free, 112MB/112MB, paused 5.572ms total 79.207ms
I/art: Background partial concurrent mark sweep GC freed 11436(585KB) AllocSpace objects, 4(544KB) LOS objects, 22% free, 111MB/143MB, paused 6.405ms total 101.110ms
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@1e02a7f4 time:85489694
I/ViewRootImpl: ViewRoot's KeyEvent { action=ACTION_DOWN, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=85495656, downTime=85495656, deviceId=-1, source=0x101 } to com.android.internal.policy.impl.PhoneWindow$DecorView{3100c316 V.E..... R....... 0,0-1440,2392}
I/ViewRootImpl: ViewRoot's KeyEvent { action=ACTION_UP, keyCode=KEYCODE_BACK, scanCode=0, metaState=0, flags=0x48, repeatCount=0, eventTime=85495665, downTime=85495656, deviceId=-1, source=0x101 } to com.android.internal.policy.impl.PhoneWindow$DecorView{3100c316 V.E..... R....... 0,0-1440,2392}
I/SensorManager: unregisterListenerImpl() [Sensor: LGE Rotation Vector Sensor, SensorEventListener: cgeo.geocaching.sensors.RotationProvider$1$1@1f570fdb] bycgeo.geocaching.sensors.RotationProvider$1$2.run():85
I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@3c10f415 time:85495736
W/System.err: java.io.InterruptedIOException
W/System.err:     at com.android.okio.Deadline.throwIfReached(Deadline.java:56)
W/System.err:     at com.android.okio.Okio$2.read(Okio.java:110)
W/System.err:     at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:48)
W/System.err:     at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:442)
W/System.err:     at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
W/System.err:     at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
W/System.err:     at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:635)
W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:611)
W/System.err:     at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:649)
W/System.err:     at org.mapsforge.v3.android.maps.mapgenerator.tiledownloader.TileDownloader.executeJob(TileDownloader.java:60)
W/System.err:     at org.mapsforge.v3.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:73)
W/System.err:     at org.mapsforge.v3.android.maps.PausableThread.run(PausableThread.java:94)
D/skia: ---- read threw an exception
D/skia: --- SkImageDecoder::Factory returned null
Disconnected from the target VM, address: 'localhost:8607', transport: 'socket'
````

**Comment by AndersBillLinden** [comment]
The tile loading is a lot slower when I debug the app compared to when I run it from google play. Maybe thats something to expect. I do not even see tiles when I run the release version.

**Comment by samueltardieu** [comment]
Which map are you using?

**Comment by AndersBillLinden** [comment]
I did not select a map. Looks like OSM.

**Comment by AndersBillLinden** [comment]
When I go into cgeo:settings and go to Map and Select Map Source, I can read OSM: Mapnik.

**Comment by AndersBillLinden** [comment]
To clarify, I can go backwards from the map, coming back to the main menu, then the app is dead fish.

**Comment by samueltardieu** [comment]
This has been fixed in da67b8fb5735894f8fed5177a7a0c1db5bc09d3e.

**Comment by AndersBillLinden** [comment]
Should we report to the project https://github.com/mapsforge/mapsforge that we had to do a substring search in one of their exceptions to be able to use the lib?

**Comment by rsudev** [comment]
To clarify: the exception we choose to ignore comes from the OkHttp library. Furthermore do I guess the will not address issues against the (very old) version 0.3.0, which still in use in this context,
