### ISSUE TITLE
ConcurrentModificationException in new map

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#6151]
Master as of 3895e6479f4b97029286eb98d67f6f0671b54041. Concurrent modification of the tile cache between UI and background threads (coming back from a cache description).

```
11-20 23:22:23.407 7389-7389/cgeo.geocaching W/cgeo: [main] UncaughtException
                                                     java.lang.RuntimeException: Unable to resume activity {cgeo.geocaching/cgeo.geocaching.maps.mapsforge.v6.NewMap}: java.util.ConcurrentModificationException
                                                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3400)
                                                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440)
                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510)
                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                         at android.os.Looper.loop(Looper.java:154)
                                                         at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                      Caused by: java.util.ConcurrentModificationException
                                                         at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:411)
                                                         at java.util.LinkedHashMap$ValueIterator.next(LinkedHashMap.java:426)
                                                         at org.mapsforge.map.layer.cache.InMemoryTileCache.purge(InMemoryTileCache.java:82)
                                                         at org.mapsforge.map.layer.cache.TwoLevelTileCache.purge(TwoLevelTileCache.java:80)
                                                         at cgeo.geocaching.maps.mapsforge.v6.NewMap.switchTileLayer(NewMap.java:638)
                                                         at cgeo.geocaching.maps.mapsforge.v6.NewMap.initializeLayers(NewMap.java:669)
                                                         at cgeo.geocaching.maps.mapsforge.v6.NewMap.onStart(NewMap.java:664)
                                                         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
                                                         at android.app.Activity.performStart(Activity.java:6681)
                                                         at android.app.Activity.performRestart(Activity.java:6755)
                                                         at android.app.Activity.performResume(Activity.java:6760)
                                                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3377)
                                                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3440) 
                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510) 
                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                         at android.os.Looper.loop(Looper.java:154) 
                                                         at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by rsudev** [comment]
I was not able to reproduce it, but have a suspicion. Could you possible cross-check, if my change in 876a136b8aa3 (branch issue_6151) fixes this for you?
