### ISSUE TITLE
Crash when opening logbook of certain cache

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6191]
##### Detailed steps causing the problem:
- Open GC1YX6F
- Swipe to logbook

##### Actual behavior after performing these steps:
Crash

##### Expected behavior after performing these steps:
Normal operation

##### Version of c:geo used:
2016.12.09-RC / 2016.12.13-NB

##### Is the problem reproducible for you?
No

Happend for a user on FB.
I can reproduce it on 1 out of 5 devices, sadly only on the one which offers no logging.

Can someone reproduce and provide a log?

**Comment by Lineflyer** [comment]
I was finally able to get a log of this crash.
It seems related to trackable loading.

```
W/cgeo    (32370): [main] UncaughtException
W/cgeo    (32370): java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
W/cgeo    (32370): 	at cgeo.geocaching.ui.TrackableListAdapter.getItemCount(TrackableListAdapter.java:46)
W/cgeo    (32370): 	at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:1843)
W/cgeo    (32370): 	at android.view.View.measure(View.java:20151)
W/cgeo    (32370): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1489)
W/cgeo    (32370): 	at android.view.View.measure(View.java:20151)
W/cgeo    (32370): 	at android.widget.LinearLayout.measureVertical(LinearLayout.java:900)
W/cgeo    (32370): 	at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
W/cgeo    (32370): 	at android.view.View.measure(View.java:20151)
W/cgeo    (32370): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
W/cgeo    (32370): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
W/cgeo    (32370): 	at android.view.View.measure(View.java:20151)
W/cgeo    (32370): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
W/cgeo    (32370): 	at com.android.internal.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:446)
W/cgeo    (32370): 	at android.view.View.measure(View.java:20151)
W/cgeo    (32370): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
W/cgeo    (32370): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
W/cgeo    (32370): 	at android.view.View.measure(View.java:20151)
W/cgeo    (32370): 	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6328)
W/cgeo    (32370): 	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
W/cgeo    (32370): 	at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3158)
W/cgeo    (32370): 	at android.view.View.measure(View.java:20151)
W/cgeo    (32370): 	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2594)
W/cgeo    (32370): 	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1549)
W/cgeo    (32370): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1841)
W/cgeo    (32370): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1437)
W/cgeo    (32370): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7403)
W/cgeo    (32370): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:920)
W/cgeo    (32370): 	at android.view.Choreographer.doCallbacks(Choreographer.java:695)
W/cgeo    (32370): 	at android.view.Choreographer.doFrame(Choreographer.java:631)
W/cgeo    (32370): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:906)
W/cgeo    (32370): 	at android.os.Handler.handleCallback(Handler.java:739)
W/cgeo    (32370): 	at android.os.Handler.dispatchMessage(Handler.java:95)
W/cgeo    (32370): 	at android.os.Looper.loop(Looper.java:158)
W/cgeo    (32370): 	at android.app.ActivityThread.main(ActivityThread.java:7229)
W/cgeo    (32370): 	at java.lang.reflect.Method.invoke(Native Method)
W/cgeo    (32370): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
W/cgeo    (32370): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by Lineflyer** [comment]
It seems related to having Geokrety activated.

**Comment by Lineflyer** [comment]
Another cache where this happens (just reported via support mail by a user):
GC2J3GZ

**Comment by Lineflyer** [comment]
@kumy This seems to affect all GC-caches where geokretymap.org returns a GK inventory which is not empty.

**Comment by kumy** [comment]
I'm sorry I'm not available until next year, I can't do anything. I've looked rapidly at the history of `TrackableListAdapter.java`. It seems that @Bananeweizen has done some work to "convert trackable list to recyclerview ". (don't know what it mean). See: https://github.com/cgeo/cgeo/commit/b930a5d5aec41a91c51b29a3c179422a1f253d51#diff-e08afae56fe71bfe724a71575aabb1d8R45

**Comment by pstorch** [comment]
The `TrackableListAdapter` expects an NonNull trackables List. But the source class `Geocache` doesn't provide this constraint. All other places check for null when getting the inventory from Geocache.

Either we check for null in `TrackableListAdapter`, too and remove the `@NonNull` annotation or we make sure `Geocache.getInventory()` returns always a non null List.

**Comment by pstorch** [comment]
I would prefer to change `Geocache.getInventory()` to return a NonNull List. But that would mean some more changes.
