### ISSUE TITLE
Concurrent modification exception 

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6205]
Beta feedback:
- Samsung S7
- 2016.12.09-RC

User message:
langsam reicht es ich habe 1500 caches gespeichert u d ein anzeigen aller auf der Karte führt jedesmal zu absturz der App. so kann man hier nicht arbeiten!!!!
English: User tries to map a list of 1500 caches on map, which makes it crash all the time.

Looks similar to #5907 which was fixed by @rsudev , but the fix should already by included in the used version of this user.

```
java.lang.RuntimeException: Unable to resume activity {cgeo.geocaching/cgeo.geocaching.maps.mapsforge.v6.NewMap}: java.util.ConcurrentModificationException
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4221)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4323)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1865)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:7325)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:346)
	at java.util.LinkedHashMap$ValueIterator.next(LinkedHashMap.java:370)
	at org.mapsforge.map.layer.cache.InMemoryTileCache.purge(InMemoryTileCache.java:82)
	at org.mapsforge.map.layer.cache.TwoLevelTileCache.purge(TwoLevelTileCache.java:80)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.switchTileLayer(NewMap.java:647)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.initializeLayers(NewMap.java:686)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.onStart(NewMap.java:681)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1266)
	at android.app.Activity.performStart(Activity.java:6943)
	at android.app.Activity.performRestart(Activity.java:7002)
	at android.app.Activity.performResume(Activity.java:7007)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4210)
	... 8 more
```

**Comment by rsudev** [comment]
This is another instance of #6151, which is a different thing than the mentioned #5907. I could not reproduce it, therefore my fix in 876a136 waits for test, not on any branch yet.
As the change is not very intrusive I could put it to release (and the beta channel) for cross-check (I still cannot reproduce it).

**Comment by Lineflyer** [comment]
@rsudev 
> As the change is not very intrusive I could put it to release (and the beta channel) for cross-check (I still cannot reproduce it).

Go for it!

**Comment by Lineflyer** [comment]
Fix has been merged.
