### ISSUE TITLE
NPE - Attempt to get length of null array (DirectionDrawer)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6206]
Beta feedback of current beta versions on Google Play:

Crash when opening the map for a cache

```
java.lang.NullPointerException: Attempt to get length of null array
	at cgeo.geocaching.maps.DirectionDrawer.drawDirection(DirectionDrawer.java:63)
	at cgeo.geocaching.maps.PositionAndScaleOverlay.drawInternal(PositionAndScaleOverlay.java:78)
	at cgeo.geocaching.maps.PositionAndScaleOverlay.drawOverlayBitmap(PositionAndScaleOverlay.java:67)
	at cgeo.geocaching.maps.mapsforge.MapsforgeOverlay.drawOverlayBitmap(MapsforgeOverlay.java:32)
	at org.mapsforge.v3.android.maps.overlay.Overlay.redrawOverlay(Overlay.java:313)
	at org.mapsforge.v3.android.maps.overlay.Overlay.run(Overlay.java:250
```

Can this be caused by the new brouter implementation (I guess those users wont have it installed).

**Comment by Lineflyer** [comment]
We do now have four of these crashes for 2016.12.28 (as well as the correpsonding beta versions).

**Comment by Lineflyer** [comment]
Set to high as this bug makes all map interaction impossible for the affected users.

**Comment by samueltardieu** [comment]
I could not reproduce, but by reading the code I could see how that could happen.

**Comment by schafma** [comment]
testing version: 2017.01.08-RC2
With disable option "show direction" the map can be open for a cache.
With enabled option or when enabling the option while the map for a cache is open, c:geo stops.
Shall I create a debug log?

**Comment by schafma** [comment]
Forgot to mention: I've installed BRouter

**Comment by Lineflyer** [comment]
@schafma Yes please. With reference to this issue #6206

**Comment by Lineflyer** [comment]
Did you create a crash report?

**Comment by Lineflyer** [comment]
Closing again as the log received from @schafma reveals a different problem.
