### ISSUE TITLE
NegativeArraySizeException when opening map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6240]
From Google Play Beta crash reports for version 2017.01.08-RC2 and one beta earlier as well:

```
java.lang.NegativeArraySizeException: -4
	at cgeo.geocaching.utils.CanvasUtils.drawPath(CanvasUtils.java:25)
	at cgeo.geocaching.maps.DirectionDrawer.drawDirection(DirectionDrawer.java:69)
	at cgeo.geocaching.maps.PositionAndScaleOverlay.drawInternal(PositionAndScaleOverlay.java:78)
	at cgeo.geocaching.maps.PositionAndScaleOverlay.drawOverlayBitmap(PositionAndScaleOverlay.java:67)
	at cgeo.geocaching.maps.mapsforge.MapsforgeOverlay.drawOverlayBitmap(MapsforgeOverlay.java:32)
	at org.mapsforge.v3.android.maps.overlay.Overlay.redrawOverlay(Overlay.java:313)
	at org.mapsforge.v3.android.maps.overlay.Overlay.run(Overlay.java:250)
```

User coments like:
Crash when opening map for a cache

**Comment by samueltardieu** [comment]
This one is likely to have been fixed at the same time as #6241. The offending line is

``` java
  final float[] pointData = new float[(pixelPoints.size() - 1) * 4];
```
and the fix for #6241 ensures that a path as returned by brouter has always two components. Zero components indeed led to a size of -4.

Please reopen if it reappears.
