### ISSUE TITLE
org.apache.harmony.xml.ExpatParser$ParseException when opening map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6241]
Outcome of #6236 (put into a new issue):

Beta version: 2016.01.08-RC2

```
java.lang.RuntimeException: Aborting on Log.e()
	at cgeo.geocaching.utils.Log.e(Log.java:108)
	at cgeo.geocaching.maps.routing.Routing.parseGpxTrack(Routing.java:143)
	at cgeo.geocaching.maps.routing.Routing.calculateRouting(Routing.java:115)
	at cgeo.geocaching.maps.routing.Routing.getTrack(Routing.java:95)
	at cgeo.geocaching.maps.DirectionDrawer.drawDirection(DirectionDrawer.java:62)
	at cgeo.geocaching.maps.PositionAndScaleOverlay.drawInternal(PositionAndScaleOverlay.java:78)
	at cgeo.geocaching.maps.PositionAndScaleOverlay.drawOverlayBitmap(PositionAndScaleOverlay.java:67)
	at cgeo.geocaching.maps.mapsforge.MapsforgeOverlay.drawOverlayBitmap(MapsforgeOverlay.java:32)
	at org.mapsforge.v3.android.maps.overlay.Overlay.redrawOverlay(Overlay.java:313)
	at org.mapsforge.v3.android.maps.overlay.Overlay.run(Overlay.java:250)
Caused by: org.apache.harmony.xml.ExpatParser$ParseException: At line 1, column 0: syntax error
	at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:499)
	at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
	at android.util.Xml.parse(Xml.java:57)
	at cgeo.geocaching.maps.routing.Routing.parseGpxTrack(Routing.java:122)
	... 8 more
```
Comment of @schafma

testing version: 2017.01.08-RC2
With disable option "show direction" the map can be open for a cache.
With enabled option or when enabling the option while the map for a cache is open, c:geo stops.
Forgot to mention: I've installed BRouter

System information (taken from #6236):
```
--- System information ---
Device: SM-G800F (kminiltexx, samsung)
Android version: 5.1.1
Android build: LMY47X.G800FXXU1BOK7
Cgeo version:  see above (removed here by @Lineflyer as not matching anymore)
Google Play services: enabled
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: auto
HW acceleration: enabled (default state)
System language: de_DE (cgeo forced to English)
Log date format: 1/8/2017
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd MMM yy
Installed cgeo plugins: calendar, contacts
--- End of system information ---
```

@schafma
Aborting on log.e in the crash report is suspicious for me.
Can you please now doublecheck if you enabled the debug logging in c:geo Menu - Settings - System?
Does the problem disappear if you **disable**  the debug logging?

**Comment by schafma** [comment]
The debug logging was enabled when sending the Crash Report.
When disabling the debug logging the issue still persists.
Shall I send a Crash Report with disabled debug logging?
Could it be a problem with the interaction of c:geo and BRouter? Maybe uninstalling BRouter and trying again will give a hint?

**Comment by Lineflyer** [comment]
@schafma 
No it is OK.
I was just asking as I know that having debug logging activated will stop c:geo forcefully in some error cases which would otherwise just happen in the background without crashing. 
But as you confirmed it crashes also without debug logging the case is clear.

**Comment by rsudev** [comment]
The callstack clearly indicates that there is an issue parsing the gpx response from BRouter, so removing that or switching to 'straight line' might mitigate that.

**Comment by Lineflyer** [comment]
@rsudev 
Switching to straight line is a problem as he will not reach the menu as the map is crashing instantly.

Anyway if Brouter might produce failures we should try to catch them here.
Hard to find our what happend?

@schafma 
Did you download maps in BRouter or just installed it without loading maps there?

**Comment by samueltardieu** [comment]
Given that the error is supposed to be at "line 1, column 0", I assume that the GPX response is empty.

**Comment by schafma** [comment]
I'm quite sure that I've download something. But as I wanted to look it up now, BRouter asked me again for an SDCard base dir and tells me that the preciously selected basedir contains no "brouter" subfolder.
Thus I think that no maps have been downloaded.
I'll download again and will report

**Comment by schafma** [comment]
I've downloaded a segment, started Brouter again and selected the "car-test" routing profile.
Next I've selected the Server-Mode and didn't change anything by the choosen service-modes (=motorcar_short and motorcar_fast are checked).
And now c:geo works find with the show direction setting enabled.
Stupid me, that I installed Brouter wrong :) and sorry for that.
But anyway I think its an issue to deal with.
Please let me know if I could help you any further (e.g. reinstall brouter wrong again :) )

**Comment by schafma** [comment]
A final comment: Brouter was update on my phone 3 days ago. Since I'm 99.9% sure I'd downloaded a map and setup up Brouter correctly, I assume that due to the update the database got deleted.

**Comment by Lineflyer** [comment]
Thanks @schafma for your insights and detailed report.
This was important feedback which helped us solve a possible problem..no matter if you did not use Brouter as intended...this might happen to all users and must not have cgeo crashing.

**Comment by Lineflyer** [comment]
I am afraid I have to reopen this issue:
I just tested with a fresh brewed 2016.01.10-RC (should inlcude 2f4cecea42dc1fbea653911cf4dc21c4e74e2bfa)

Steps:
- Install brouter and do nothing with it after installation (no config, no maps loaded)
- Start c:geo
- Open a saved cache
- Select Navigate -> Map

Result:
- Crash

According to the log attached from my tests it looks like the issue is still there.

I would also like to make another suggestion:
Wouldn't it be more on the safe side to set the default routing mode to "Straight line"? This would mean in addition to installing Brouter the used would need to explicitly enable the routing use.
Of course this makes finding that feature even more complicated...but this could be solved by always showing the Routing menu (AFAIK it is currently only shown if Brouter is installed) but guiding the user to download Brouter (e.g. link to FAQ) in case he selects a routing mode other than "straight line".
This would make the feature available to more users, guide them to use it and avoid any interworking problems the user might run in totally unaware (also for possible future problems with Brouter).

Log:
```
21:51:37.667 Error cgeo 11217  [main] cannot parse brouter output
21:51:37.667 Error cgeo 11217  org.apache.harmony.xml.ExpatParser$ParseException: At line 1, column 0: syntax error
21:51:37.667 Error cgeo 11217  	at org.apache.harmony.xml.ExpatParser.parseFragment(ExpatParser.java:499)
21:51:37.667 Error cgeo 11217  	at org.apache.harmony.xml.ExpatParser.parseDocument(ExpatParser.java:484)
21:51:37.667 Error cgeo 11217  	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:309)
21:51:37.667 Error cgeo 11217  	at org.apache.harmony.xml.ExpatReader.parse(ExpatReader.java:267)
21:51:37.667 Error cgeo 11217  	at android.util.Xml.parse(Xml.java:57)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.routing.Routing.parseGpxTrack(Routing.java:138)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.routing.Routing.calculateRouting(Routing.java:131)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.routing.Routing.getTrack(Routing.java:105)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.DirectionDrawer.drawDirection(DirectionDrawer.java:62)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.PositionAndScaleOverlay.drawInternal(PositionAndScaleOverlay.java:78)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.PositionAndScaleOverlay.draw(PositionAndScaleOverlay.java:73)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.google.v1.GoogleOverlay.draw(GoogleOverlay.java:31)
21:51:37.667 Error cgeo 11217  	at com.google.android.maps.Overlay.draw(Overlay.java:179)
21:51:37.667 Error cgeo 11217  	at com.google.android.maps.OverlayBundle.draw(OverlayBundle.java:42)
21:51:37.667 Error cgeo 11217  	at com.google.android.maps.MapView.onDraw(MapView.java:532)
21:51:37.667 Error cgeo 11217  	at android.view.View.draw(View.java:16219)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.google.v1.GoogleMapView.draw(GoogleMapView.java:69)
21:51:37.667 Error cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15139)
21:51:37.667 Error cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Error cgeo 11217  	at android.view.View.draw(View.java:15940)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
21:51:37.667 Error cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15134)
21:51:37.667 Error cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Error cgeo 11217  	at android.view.View.draw(View.java:15940)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
21:51:37.667 Error cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15134)
21:51:37.667 Error cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Error cgeo 11217  	at android.view.View.draw(View.java:15940)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
21:51:37.667 Error cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15134)
21:51:37.667 Error cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Error cgeo 11217  	at android.view.View.draw(View.java:15940)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
21:51:37.667 Error cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15134)
21:51:37.667 Error cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Error cgeo 11217  	at android.view.View.draw(View.java:15940)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
21:51:37.667 Error cgeo 11217  	at com.android.internal.policy.impl.MultiPhoneWindow$MultiPhoneDecorView.dispatchDraw(MultiPhoneWindow.java:900)
21:51:37.667 Error cgeo 11217  	at android.view.View.draw(View.java:16222)
21:51:37.667 Error cgeo 11217  	at android.widget.FrameLayout.draw(FrameLayout.java:592)
21:51:37.667 Error cgeo 11217  	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2932)
21:51:37.667 Error cgeo 11217  	at com.android.internal.policy.impl.MultiPhoneWindow$MultiPhoneDecorView.draw(MultiPhoneWindow.java:906)
21:51:37.667 Error cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15139)
21:51:37.667 Error cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Error cgeo 11217  	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
21:51:37.667 Error cgeo 11217  	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)
21:51:37.667 Error cgeo 11217  	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)
21:51:37.667 Error cgeo 11217  	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2751)
21:51:37.667 Error cgeo 11217  	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2584)
21:51:37.667 Error cgeo 11217  	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2176)
21:51:37.667 Error cgeo 11217  	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
21:51:37.667 Error cgeo 11217  	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
21:51:37.667 Error cgeo 11217  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
21:51:37.667 Error cgeo 11217  	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
21:51:37.667 Error cgeo 11217  	at android.view.Choreographer.doFrame(Choreographer.java:560)
21:51:37.667 Error cgeo 11217  	at android.view.Choreographer$FrameDisplayEven
21:51:37.667 Error cgeo 11217  [main] GoogleMapView.draw
21:51:37.667 Error cgeo 11217  java.lang.RuntimeException: Aborting on Log.e()
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.utils.Log.e(Log.java:108)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.routing.Routing.parseGpxTrack(Routing.java:159)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.routing.Routing.calculateRouting(Routing.java:131)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.routing.Routing.getTrack(Routing.java:105)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.DirectionDrawer.drawDirection(DirectionDrawer.java:62)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.PositionAndScaleOverlay.drawInternal(PositionAndScaleOverlay.java:78)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.PositionAndScaleOverlay.draw(PositionAndScaleOverlay.java:73)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.google.v1.GoogleOverlay.draw(GoogleOverlay.java:31)
21:51:37.667 Error cgeo 11217  	at com.google.android.maps.Overlay.draw(Overlay.java:179)
21:51:37.667 Error cgeo 11217  	at com.google.android.maps.OverlayBundle.draw(OverlayBundle.java:42)
21:51:37.667 Error cgeo 11217  	at com.google.android.maps.MapView.onDraw(MapView.java:532)
21:51:37.667 Error cgeo 11217  	at android.view.View.draw(View.java:16219)
21:51:37.667 Error cgeo 11217  	at cgeo.geocaching.maps.google.v1.GoogleMapView.draw(GoogleMapView.java:69)
21:51:37.667 Error cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15139)
21:51:37.667 Error cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Error cgeo 11217  	at android.view.View.draw(View.java:15940)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
21:51:37.667 Error cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15134)
21:51:37.667 Error cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Error cgeo 11217  	at android.view.View.draw(View.java:15940)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
21:51:37.667 Error cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15134)
21:51:37.667 Error cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Error cgeo 11217  	at android.view.View.draw(View.java:15940)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
21:51:37.667 Error cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15134)
21:51:37.667 Error cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Error cgeo 11217  	at android.view.View.draw(View.java:15940)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
21:51:37.667 Error cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15134)
21:51:37.667 Error cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Error cgeo 11217  	at android.view.View.draw(View.java:15940)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
21:51:37.667 Error cgeo 11217  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
21:51:37.667 Error cgeo 11217  	at com.android.internal.policy.impl.MultiPhoneWindow$MultiPhoneDecorView.dispatchDraw(MultiPhoneWindow.java:900)
21:51:37.667 Error cgeo 11217  	at android.view.View.draw(View.java:16222)
21:51:37.667 Error cgeo 11217  	at android.widget.FrameLayout.draw(FrameLayout.java:592)
21:51:37.667 Error cgeo 11217  	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2932)
21:51:37.667 Error cgeo 11217  	at com.android.internal.policy.impl.MultiPhoneWindow$MultiPhoneDecorView.draw(MultiPhoneWindow.java:906)
21:51:37.667 Error cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15139)
21:51:37.667 Error cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Error cgeo 11217  	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
21:51:37.667 Error cgeo 11217  	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)
21:51:37.667 Error cgeo 11217  	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)
21:51:37.667 Error cgeo 11217  	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2751)
21:51:37.667 Error cgeo 11217  	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2584)
21:51:37.667 Error cgeo 11217  	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2176)
21:51:37.667 Error cgeo 11217  	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
21:51:37.667 Error cgeo 11217  	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
21:51:37.667 Error cgeo 11217  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
21:51:37.667 Error cgeo 11217  	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
21:51:37.667 Error cgeo 11217  	at android.view.Choreographer.doFrame(Choreographer.java:560)
21:51:37.667 Error cgeo 11217  	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
21:51:37.667 Error cgeo 11217  	at android.os.Handler.handleCallback(Handler.java:739)
21:51:37.667 Error cgeo 11217  	at android.os.Handler.dispatchMessage(Handler.java:95)
21:51:37.667 Error cgeo 11217  	at android.os.Looper.loop(Looper.java:145)
21:51:37.667 Error cgeo 11217  	at android.app.ActivityThread.main(ActivityThread.java:5951)
21:51:37.667 Error cgeo 11217  	at java.lang.reflect.Method.invoke(Native Method)
21:51:37.667 Error cgeo 11217  	at java.lang.ref
21:51:37.667 Warning cgeo 11217  [main] UncaughtException
21:51:37.667 Warning cgeo 11217  java.lang.RuntimeException: Aborting on Log.e()
21:51:37.667 Warning cgeo 11217  	at cgeo.geocaching.utils.Log.e(Log.java:108)
21:51:37.667 Warning cgeo 11217  	at cgeo.geocaching.maps.routing.Routing.parseGpxTrack(Routing.java:159)
21:51:37.667 Warning cgeo 11217  	at cgeo.geocaching.maps.routing.Routing.calculateRouting(Routing.java:131)
21:51:37.667 Warning cgeo 11217  	at cgeo.geocaching.maps.routing.Routing.getTrack(Routing.java:105)
21:51:37.667 Warning cgeo 11217  	at cgeo.geocaching.maps.DirectionDrawer.drawDirection(DirectionDrawer.java:62)
21:51:37.667 Warning cgeo 11217  	at cgeo.geocaching.maps.PositionAndScaleOverlay.drawInternal(PositionAndScaleOverlay.java:78)
21:51:37.667 Warning cgeo 11217  	at cgeo.geocaching.maps.PositionAndScaleOverlay.draw(PositionAndScaleOverlay.java:73)
21:51:37.667 Warning cgeo 11217  	at cgeo.geocaching.maps.google.v1.GoogleOverlay.draw(GoogleOverlay.java:31)
21:51:37.667 Warning cgeo 11217  	at com.google.android.maps.Overlay.draw(Overlay.java:179)
21:51:37.667 Warning cgeo 11217  	at com.google.android.maps.OverlayBundle.draw(OverlayBundle.java:42)
21:51:37.667 Warning cgeo 11217  	at com.google.android.maps.MapView.onDraw(MapView.java:532)
21:51:37.667 Warning cgeo 11217  	at android.view.View.draw(View.java:16219)
21:51:37.667 Warning cgeo 11217  	at cgeo.geocaching.maps.google.v1.GoogleMapView.draw(GoogleMapView.java:69)
21:51:37.667 Warning cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15139)
21:51:37.667 Warning cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Warning cgeo 11217  	at android.view.View.draw(View.java:15940)
21:51:37.667 Warning cgeo 11217  	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
21:51:37.667 Warning cgeo 11217  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
21:51:37.667 Warning cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15134)
21:51:37.667 Warning cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Warning cgeo 11217  	at android.view.View.draw(View.java:15940)
21:51:37.667 Warning cgeo 11217  	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
21:51:37.667 Warning cgeo 11217  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
21:51:37.667 Warning cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15134)
21:51:37.667 Warning cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Warning cgeo 11217  	at android.view.View.draw(View.java:15940)
21:51:37.667 Warning cgeo 11217  	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
21:51:37.667 Warning cgeo 11217  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
21:51:37.667 Warning cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15134)
21:51:37.667 Warning cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Warning cgeo 11217  	at android.view.View.draw(View.java:15940)
21:51:37.667 Warning cgeo 11217  	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
21:51:37.667 Warning cgeo 11217  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
21:51:37.667 Warning cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15134)
21:51:37.667 Warning cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Warning cgeo 11217  	at android.view.View.draw(View.java:15940)
21:51:37.667 Warning cgeo 11217  	at android.view.ViewGroup.drawChild(ViewGroup.java:3703)
21:51:37.667 Warning cgeo 11217  	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3497)
21:51:37.667 Warning cgeo 11217  	at com.android.internal.policy.impl.MultiPhoneWindow$MultiPhoneDecorView.dispatchDraw(MultiPhoneWindow.java:900)
21:51:37.667 Warning cgeo 11217  	at android.view.View.draw(View.java:16222)
21:51:37.667 Warning cgeo 11217  	at android.widget.FrameLayout.draw(FrameLayout.java:592)
21:51:37.667 Warning cgeo 11217  	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2932)
21:51:37.667 Warning cgeo 11217  	at com.android.internal.policy.impl.MultiPhoneWindow$MultiPhoneDecorView.draw(MultiPhoneWindow.java:906)
21:51:37.667 Warning cgeo 11217  	at android.view.View.updateDisplayListIfDirty(View.java:15139)
21:51:37.667 Warning cgeo 11217  	at android.view.View.getDisplayList(View.java:15162)
21:51:37.667 Warning cgeo 11217  	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:275)
21:51:37.667 Warning cgeo 11217  	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:281)
21:51:37.667 Warning cgeo 11217  	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:320)
21:51:37.667 Warning cgeo 11217  	at android.view.ViewRootImpl.draw(ViewRootImpl.java:2751)
21:51:37.667 Warning cgeo 11217  	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2584)
21:51:37.667 Warning cgeo 11217  	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2176)
21:51:37.667 Warning cgeo 11217  	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1191)
21:51:37.667 Warning cgeo 11217  	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6642)
21:51:37.667 Warning cgeo 11217  	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
21:51:37.667 Warning cgeo 11217  	at android.view.Choreographer.doCallbacks(Choreographer.java:590)
21:51:37.667 Warning cgeo 11217  	at android.view.Choreographer.doFrame(Choreographer.java:560)
21:51:37.667 Warning cgeo 11217  	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
21:51:37.667 Warning cgeo 11217  	at android.os.Handler.handleCallback(Handler.java:739)
21:51:37.667 Warning cgeo 11217  	at android.os.Handler.dispatchMessage(Handler.java:95)
21:51:37.667 Warning cgeo 11217  	at android.os.Looper.loop(Looper.java:145)
21:51:37.667 Warning cgeo 11217  	at android.app.ActivityThread.main(ActivityThread.java:5951)
21:51:37.667 Warning cgeo 11217  	at java.lang.reflect.Method.invoke(Native Method)
21:51:37.667 Warning cgeo 11217  	at java.lang.refl
```

**Comment by schafma** [comment]
Can't you catch the above exception and than fall back to straight line? A MsgBox could tell the user that BRouter is not installed correctly. This way the exception is handled and the user knows how to resolve the not working routing.

**Comment by Lineflyer** [comment]
That would be even more user friendly.

**Comment by Lineflyer** [comment]
@samueltardieu Can you take a look at why your fix seems not to work (see above).

**Comment by abrensch** [comment]
Error handling in BRouter API is quite sloppy:

If there's an error, an error message is returned instead of a GPX-Track.

So for correct error handling, you have to check the response syntactically to decide whether it's an error-message or a valid GPX-response.

I guess when displaying the error-messages in clear text, some of the confusion due to incomplete setups will go way.

**Comment by samueltardieu** [comment]
@Lineflyer The fix works, but if you try with debug enabled, there is a `Log.e()` remaining. I'll make it into a `Log.w()`. Without debug enabled, it should work fine already.

**Comment by samueltardieu** [comment]
@Lineflyer Please retest (with debug enabled) and close issue if it is indeed fixed.

**Comment by Lineflyer** [comment]
Will do, but I am not at home until Friday and the phone with this constellation is at home.
Will report back on the next weekend.

**Comment by Lineflyer** [comment]
I can confirm that with my installation tested above (2016.01.10-RC (should inlcude 2f4cece)) the crash is no longer happening when switching of debug logging.

After upgrading to 2016.01.12-RC1 (which includes 88d16fe969fb962f89892494646229effe5dff04) the crash is there again, but this time it is related to #6255 (which is meanwhile fixed)

Will now produce a new RC or even a release and test once again.

**Comment by Lineflyer** [comment]
With a new RC (head: 421a48fb93cc06b3df67396ad1f20fbfd309acfb) the process runs smooth now.
