### ISSUE TITLE
Negative Array Size Exception

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6255]
From Google Play for current beta (and the one before):

'''
java.lang.NegativeArraySizeException: -4

	at cgeo.geocaching.utils.CanvasUtils.drawPath(CanvasUtils.java:25)

	at cgeo.geocaching.maps.DirectionDrawer.drawDirection(DirectionDrawer.java:69)

	at cgeo.geocaching.maps.PositionAndScaleOverlay.drawInternal(PositionAndScaleOverlay.java:78)

	at cgeo.geocaching.maps.PositionAndScaleOverlay.drawOverlayBitmap(PositionAndScaleOverlay.java:67)

	at cgeo.geocaching.maps.mapsforge.MapsforgeOverlay.drawOverlayBitmap(MapsforgeOverlay.java:32)

	at org.mapsforge.v3.android.maps.overlay.Overlay.redrawOverlay(Overlay.java:313)

	at org.mapsforge.v3.android.maps.overlay.Overlay.run(Overlay.java:250)

'''

Posted from mobile phone

**Comment by samueltardieu** [comment]
What is *current beta* exactly?
