### ISSUE TITLE
Crash while posting text-less log

### ISSUE THREAD

**Issue by WIPocket** [cgeo/cgeo#6273]
##### Detailed steps causing the problem:
- Step 1
Go into the Log-visit menu on a cache
- Step 2
Dont enter any text
(I have set the date to before, not sure if it matters)

##### Actual behavior after performing these steps:
The app exits of the log submit menu, than crashes

##### Expected behavior after performing these steps:
Show a message saying the user needs to enter something, and stop the upload action.

##### Version of c:geo used:
2017.01.15

##### Is the problem reproducible for you?
Yes

##### System information:
```
Attach system information here if available (see c:geo menu -> About c:geo -> System)
Keep the apostrophe at beginning and end to have it properly formatted
`--- System information ---
Device: GT-I9195I (serranoveltexx, samsung)
Android version: 4.4.4
Android build: KTU84P.I9195IXXU1AOB1
Cgeo version: 2017.01.15
Google Play services: enabled - 10.0.84 (034-137749526)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: en_GB
Log date format: 18/01/2017
Debug mode active: yes
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: d.MM.yyyy
Installed cgeo plugins:  none
--- End of system information ---
`

**Comment by Lineflyer** [comment]
Confirmed with current master

**Comment by Lineflyer** [comment]
@WIPocket The resulting crash is caused by the fact, that you enabled debug logging in c:geo menu -> Settings -> System. This is to be used for development purposes only and will stop the app in case of unusual events (e.g. an empty log).

Removing that logging c:geo will work normal.


Still we could think about not logging this as an exception:
```
21:46:32.023 Error cgeo 2825  [AsyncTask #1] GCParser.postLog: No log text given
21:46:32.134 Error cgeo 2825  [AsyncTask #1] GCLoggingManager.postLog
21:46:32.134 Error cgeo 2825  java.lang.RuntimeException: Aborting on Log.e()
21:46:32.134 Error cgeo 2825  	at cgeo.geocaching.utils.Log.e(Log.java:98)
21:46:32.134 Error cgeo 2825  	at cgeo.geocaching.connector.gc.GCParser.postLog(GCParser.java:1122)
21:46:32.135 Error cgeo 2825  	at cgeo.geocaching.connector.gc.GCLoggingManager.postLog(GCLoggingManager.java:105)
21:46:32.135 Error cgeo 2825  	at cgeo.geocaching.log.LogCacheActivity$Poster.doInBackgroundInternal(LogCacheActivity.java:551)
21:46:32.135 Error cgeo 2825  	at cgeo.geocaching.log.LogCacheActivity$Poster.doInBackgroundInternal(LogCacheActivity.java:537)
21:46:32.135 Error cgeo 2825  	at cgeo.geocaching.utils.AbstractAsyncTaskWithProgress.doInBackground(AbstractAsyncTaskWithProgress.java:132)
21:46:32.135 Error cgeo 2825  	at android.os.AsyncTask$2.call(AsyncTask.java:288)
21:46:32.135 Error cgeo 2825  	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
21:46:32.135 Error cgeo 2825  	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
21:46:32.135 Error cgeo 2825  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
21:46:32.135 Error cgeo 2825  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
21:46:32.135 Error cgeo 2825  	at java.lang.Thread.run(Thread.java:818)
21:46:32.245 Error cgeo 2825  [AsyncTask #1] LogCacheActivity.Poster.doInBackgroundInternal
21:46:32.245 Error cgeo 2825  java.lang.RuntimeException: Aborting on Log.e()
21:46:32.245 Error cgeo 2825  	at cgeo.geocaching.utils.Log.e(Log.java:98)
21:46:32.245 Error cgeo 2825  	at cgeo.geocaching.connector.gc.GCParser.postLog(GCParser.java:1122)
21:46:32.245 Error cgeo 2825  	at cgeo.geocaching.connector.gc.GCLoggingManager.postLog(GCLoggingManager.java:105)
21:46:32.245 Error cgeo 2825  	at cgeo.geocaching.log.LogCacheActivity$Poster.doInBackgroundInternal(LogCacheActivity.java:551)
21:46:32.246 Error cgeo 2825  	at cgeo.geocaching.log.LogCacheActivity$Poster.doInBackgroundInternal(LogCacheActivity.java:537)
21:46:32.246 Error cgeo 2825  	at cgeo.geocaching.utils.AbstractAsyncTaskWithProgress.doInBackground(AbstractAsyncTaskWithProgress.java:132)
21:46:32.246 Error cgeo 2825  	at android.os.AsyncTask$2.call(AsyncTask.java:288)
21:46:32.246 Error cgeo 2825  	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
21:46:32.246 Error cgeo 2825  	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
21:46:32.246 Error cgeo 2825  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
21:46:32.246 Error cgeo 2825  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
21:46:32.246 Error cgeo 2825  	at java.lang.Thread.run(Thread.java:818)
21:46:32.246 Warning cgeo 2825  [AsyncTask #1] UncaughtException
21:46:32.246 Warning cgeo 2825  java.lang.RuntimeException: An error occured while executing doInBackground()
21:46:32.246 Warning cgeo 2825  	at android.os.AsyncTask$3.done(AsyncTask.java:300)
21:46:32.246 Warning cgeo 2825  	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
21:46:32.246 Warning cgeo 2825  	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
21:46:32.247 Warning cgeo 2825  	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
21:46:32.247 Warning cgeo 2825  	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
21:46:32.247 Warning cgeo 2825  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
21:46:32.247 Warning cgeo 2825  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
21:46:32.247 Warning cgeo 2825  	at java.lang.Thread.run(Thread.java:818)
21:46:32.247 Warning cgeo 2825  Caused by: java.lang.RuntimeException: Aborting on Log.e()
21:46:32.247 Warning cgeo 2825  	at cgeo.geocaching.utils.Log.e(Log.java:98)
21:46:32.247 Warning cgeo 2825  	at cgeo.geocaching.connector.gc.GCParser.postLog(GCParser.java:1122)
21:46:32.247 Warning cgeo 2825  	at cgeo.geocaching.connector.gc.GCLoggingManager.postLog(GCLoggingManager.java:105)
21:46:32.247 Warning cgeo 2825  	at cgeo.geocaching.log.LogCacheActivity$Poster.doInBackgroundInternal(LogCacheActivity.java:551)
21:46:32.247 Warning cgeo 2825  	at cgeo.geocaching.log.LogCacheActivity$Poster.doInBackgroundInternal(LogCacheActivity.java:537)
21:46:32.247 Warning cgeo 2825  	at cgeo.geocaching.utils.AbstractAsyncTaskWithProgress.doInBackground(AbstractAsyncTaskWithProgress.java:132)
21:46:32.247 Warning cgeo 2825  	at android.os.AsyncTask$2.call(AsyncTask.java:288)
21:46:32.248 Warning cgeo 2825  	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
21:46:32.248 Warning cgeo 2825  	... 4 more
```

**Comment by pstorch** [comment]
It doesn't make sense to log this as an error. It's just an input validation error.
I'll change it to `Log.w()`.
