### ISSUE TITLE
Index Out Of Bounds in Mapsforge map (old)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6301]
From Google Play (partly discussed in #5690 already):

This is the most frequent crash report on Google Play (but "only" 9 reports per week) currently:

```
java.lang.IndexOutOfBoundsException: Invalid index 46, size is 46
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at cgeo.geocaching.maps.CachesOverlay.createItem(CachesOverlay.java:269)
	at cgeo.geocaching.maps.mapsforge.MapsforgeCacheOverlay.createItem(MapsforgeCacheOverlay.java:39)
	at cgeo.geocaching.maps.mapsforge.MapsforgeCacheOverlay.createItem(MapsforgeCacheOverlay.java:20)
	at org.mapsforge.v3.android.maps.overlay.ItemizedOverlay.drawOverlayBitmap(ItemizedOverlay.java:220)
	at cgeo.geocaching.maps.mapsforge.MapsforgeCacheOverlay.superDrawOverlayBitmap(MapsforgeCacheOverlay.java:86)
	at cgeo.geocaching.maps.AbstractItemizedOverlay.drawOverlayBitmap(AbstractItemizedOverlay.java:50)
	at cgeo.geocaching.maps.CachesOverlay.drawOverlayBitmap(CachesOverlay.java:123)
	at cgeo.geocaching.maps.mapsforge.MapsforgeCacheOverlay.drawOverlayBitmap(MapsforgeCacheOverlay.java:55)
	at org.mapsforge.v3.android.maps.overlay.Overlay.redrawOverlay(Overlay.java:313)
	at org.mapsforge.v3.android.maps.overlay.Overlay.run(Overlay.java:250)
```

```
ava.lang.IndexOutOfBoundsException: Invalid index 329, size is 108
	at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
	at java.util.ArrayList.get(ArrayList.java:308)
	at cgeo.geocaching.maps.CachesOverlay.createItem(CachesOverlay.java:269)
	at cgeo.geocaching.maps.mapsforge.MapsforgeCacheOverlay.createItem(MapsforgeCacheOverlay.java:39)
	at cgeo.geocaching.maps.mapsforge.MapsforgeCacheOverlay.createItem(MapsforgeCacheOverlay.java:20)
	at org.mapsforge.v3.android.maps.overlay.ItemizedOverlay.drawOverlayBitmap(ItemizedOverlay.java:220)
	at cgeo.geocaching.maps.mapsforge.MapsforgeCacheOverlay.superDrawOverlayBitmap(MapsforgeCacheOverlay.java:86)
	at cgeo.geocaching.maps.AbstractItemizedOverlay.drawOverlayBitmap(AbstractItemizedOverlay.java:50)
	at cgeo.geocaching.maps.CachesOverlay.drawOverlayBitmap(CachesOverlay.java:123)
	at cgeo.geocaching.maps.mapsforge.MapsforgeCacheOverlay.drawOverlayBitmap(MapsforgeCacheOverlay.java:55)
	at org.mapsforge.v3.android.maps.overlay.Overlay.redrawOverlay(Overlay.java:313)
	at org.mapsforge.v3.android.maps.overlay.Overlay.run(Overlay.java:250)
```

Wasn't there a protection introduced recently to avoid this?

**Comment by pstorch** [comment]
This Exception is usually caught. But we log an error there. Maybe these users have the debug log enabled and then the app crashes because of the error log. 
Maybe we should change it to a warning.

**Comment by Lineflyer** [comment]
But this means we already degraded it to a warning (according to the other issue). Did you notice different in the code?

**Comment by pstorch** [comment]
No, it is still Log.e(). Maybe this was at another place in the other issue.

**Comment by pstorch** [comment]
Just looked into #5690 there is no commit referencing this issue and the `Log.e()` is still in the code. There was no downgrade of the loglevel either.

**Comment by pstorch** [comment]
Here is the `Log.e()`: https://github.com/cgeo/cgeo/blob/62620d15044f48978e6b1401f2db068abe17b325/main/src/cgeo/geocaching/maps/CachesOverlay.java#L271

**Comment by Lineflyer** [comment]
Lets ake this a warning then. Obviously the map keeps working and we avoid a crash.
