### ISSUE TITLE
RejectedExecutionException

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6388]
From Google Play for beta version 2017.02.28-RC:

User message:
Clicking on icons on the map

Samsung S7 with Android 7.0

```
io.reactivex.exceptions.UndeliverableException: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@50077de rejected from java.util.concurrent.ScheduledThreadPoolExecutor@d71ec00[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 12]
	at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
	at io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:134)
	at io.reactivex.internal.schedulers.NewThreadWorker.schedule(NewThreadWorker.java:51)
	at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:400)
	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@50077de rejected from java.util.concurrent.ScheduledThreadPoolExecutor@d71ec00[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 12]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2049)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:814)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:305)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:550)
	at io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:127)
	... 9 more
```

**Comment by Lineflyer** [comment]
@samueltardieu Any idea whether this could be critical or not? Its hard to judge as we only have one single report on Google Play, but the beta version is also currently only about 2% of user base.

**Comment by samueltardieu** [comment]
I have no idea, it's the first time I see this exception raised from RxJava.

**Comment by Lineflyer** [comment]
This is the second most crash event on Google Play:
Reports this week: 400
Reports total: 3.563
Affected users: 3.026

Mixed devices, mixed Android versions

**Comment by samueltardieu** [comment]
I think this was benign and happened when the application was shutdown for another reason. Let's see if this reduces the number of occurrences.
