### ISSUE TITLE
ConcurrentModificationException on new map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6406]
From Google Play reports:
```
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:346)
	at java.util.LinkedHashMap$ValueIterator.next(LinkedHashMap.java:370)
	at org.mapsforge.map.layer.cache.InMemoryTileCache.purge(InMemoryTileCache.java:82)
	at org.mapsforge.map.layer.cache.TwoLevelTileCache.purge(TwoLevelTileCache.java:80)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.setMapTheme(NewMap.java:585)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.switchTileLayer(NewMap.java:624)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.setMapSource(NewMap.java:593)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.onOptionsItemSelected(NewMap.java:464)
	at android.app.Activity.onMenuItemSelected(Activity.java:3201)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361)
	at android.support.v7.app.ActionBarActivity.superOnMenuItemSelected(ActionBarActivity.java:245)
	at android.support.v7.app.ActionBarActivityDelegateICS.onMenuItemSelected(ActionBarActivityDelegateICS.java:164)
	at android.support.v7.app.ActionBarActivity.onMenuItemSelected(ActionBarActivity.java:131)
	at android.support.v7.app.ActionBarActivityDelegateICS$WindowCallbackWrapper.onMenuItemSelected(ActionBarActivityDelegateICS.java:308)
	at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1232)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:801)
	at com.android.internal.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:81)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:155)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:954)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:944)
	at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:411)
	at android.widget.AdapterView.performItemClick(AdapterView.java:340)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1532)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3700)
	at android.widget.AbsListView$3.run(AbsListView.java:5684)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6934)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

IRC user jorgixhallo can provide more details

**Comment by Jorgixhallo** [comment]
Unfortunately, this seems to be a very specific crash and I'm sure most of the users won't have this problem but it could eventually happen. It's very hard to reproduce but it happens sometimes for sure.
Conditions that it lead to this:
Live mode ON
High zoom into the map (not sure if this actually have a role in the crash)
Theme Enabled (In my case Elevate 4)
2 offline maps

How to reproduce (only happens sometimes if I "force" it):
Live mode
Zoom in to a cache
Change between offline maps, themes (it's rare to happen in the first time. Change between them randomly)

**Comment by Lineflyer** [comment]
No longer seen on Google crash reporter.
