### ISSUE TITLE
App stops to respond

### ISSUE THREAD

**Issue by naoliv** [cgeo/cgeo#6417]
##### Detailed steps causing the problem:

Seems to be reproducible most of the time when:

- Entering `Live map`
- Getting back to the main menu
- Trying to press `Stored`

##### Actual behavior after performing these steps:
The app freezes, without entering the `Stored` section.
Android says `The app is not responding`.

##### Expected behavior after performing these steps:
The app shouldn't freeze and open the `Stored` part.

##### Version of c:geo used:
`2017.03.19`

##### Is the problem reproducible for you?
Yes

##### System information:
```
Device: XT1069 (titan_retbr_dstv, motorola)
Android version: 6.0
Android build: MPB24.65-34-3
Cgeo version: 2017.03.19
Google Play services: enabled - 10.2.98 (436-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: pt_BR (cgeo forced to English)
System date format: dd/MM/yy
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: dd/MM/yyyy
Installed cgeo plugins:  none
```

##### Other comments and remarks:
While trying to prepare some places for the next weekend (and also verify #6217) I am seeing c:geo freezing.

In logcat I can see:
```
03-21 08:32:30.588  1783  2314 I InputDispatcher: Application is not responding: AppWindowToken{e7c8dad token=Token{1ae5ac4 ActivityRecord{33761d7 u0 cgeo.geocaching/.MainActivity t18894}}} - Window{93ffcf4 u0 cgeo.geocaching/cgeo.geocaching.MainActivity}.  It has been 5016.4ms since event, 5001.3ms since wait started.  Reason: Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it.  Outbound queue length: 0.  Wait queue length: 3.
03-21 08:32:30.595  1783  2314 I WindowManager: Input event dispatching timed out sending to cgeo.geocaching/cgeo.geocaching.MainActivity.  Reason: Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it.  Outbound queue length: 0.  Wait queue length: 3.
(...)
03-21 08:32:35.618  1783  2314 W InputDispatcher: Asynchronous input event injection failed.
03-21 08:32:35.618  1783  2314 I InputDispatcher: Dropped event because it is stale.
03-21 08:32:36.900  1783  2311 V AlarmManager: sending alarm {6d22914 type 3 *alarm*:com.google.android.location.fused.LOCATION_STATUS_ALARM_ACTION_0}
03-21 08:32:37.317  1783  1854 I Process : Sending signal. PID: 3395 SIG: 3
03-21 08:32:37.317  3395  3407 I art     : Thread[2,tid=3407,WaitingInMainSignalCatcherLoop,Thread*=0xb7da3490,peer=0x12c640a0,"Signal Catcher"]: reacting to signal 3
03-21 08:32:37.542  1783  1854 E ActivityManager: ANR in cgeo.geocaching (cgeo.geocaching/.MainActivity)
03-21 08:32:37.542  1783  1854 E ActivityManager: PID: 9907
03-21 08:32:37.542  1783  1854 E ActivityManager: Reason: Input dispatching timed out (Waiting to send key event because the focused window has not finished processing all of the input events that were previously delivered to it.  Outbound queue length: 0.  Wait queue length: 3.)
```

I can make tests or try to send more logs if needed.

**Comment by samueltardieu** [comment]
What map are you using?

**Comment by naoliv** [comment]
In `Live map` I am using `OSM: Mapnik`
If there is something else that I can do to give more info about this.
Debug log from c:geo maybe?

**Comment by naoliv** [comment]
More info:
`Scale Map Text` is enabled, `Show Waypoints` is at `30`, `Show direction` is enabled too.
`Strategy` is `Detailed`

**Comment by naoliv** [comment]
[trace.txt](https://github.com/cgeo/cgeo/files/859058/trace.txt) created by ANR

Taking a look in logcat with debug enabled I see:

```
03-21 14:13:00.939 30058 30433 D cgeo    : [OkHttp] 200 (1280 ms) GET https://www.geocaching.com/map/default.aspx (http/1.1)
03-21 14:13:01.196 30058 30552 D cgeo    : [network--5] GCMap.searchByViewport(S 21° 48,910 · W 048° 11,941,S 21° 47,915 · W 048° 11,200)
03-21 14:13:01.204 30058 30433 D cgeo    : [OkHttp] GET https://tiles.geocaching.com/map.png?x=5998&y=9208&z=14&ep=1&app=cgeo&k=HZlT5&st=-yUQd3_Uul2T3C4tE0HCkXePe7NWnG4poCh0M0RsKk84PIx4iBXrIYz0Wk31lv_Msw4luTIk9INJnggM9PLo-4jHp6WBLmxdxXq-a2a52CBV9hGevynY6Yhl59kRYDsgAfT585XMpN697cjxZz65dw2
03-21 14:13:01.265 30058 30497 E TileDownloader: null
03-21 14:13:01.265 30058 30497 E TileDownloader: java.io.InterruptedIOException: thread interrupted
03-21 14:13:01.265 30058 30497 E TileDownloader:        at com.android.okhttp.okio.Timeout.throwIfReached(Timeout.java:145)
03-21 14:13:01.265 30058 30497 E TileDownloader:        at com.android.okhttp.okio.Okio$1.write(Okio.java:73)
03-21 14:13:01.265 30058 30497 E TileDownloader:        at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
03-21 14:13:01.265 30058 30497 E TileDownloader:        at com.android.okhttp.okio.RealBufferedSink.flush(RealBufferedSink.java:221)
03-21 14:13:01.265 30058 30497 E TileDownloader:        at com.android.okhttp.internal.http.HttpConnection.flush(HttpConnection.java:141)
03-21 14:13:01.265 30058 30497 E TileDownloader:        at com.android.okhttp.internal.http.HttpTransport.finishRequest(HttpTransport.java:52)
03-21 14:13:01.265 30058 30497 E TileDownloader:        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:902)
03-21 14:13:01.265 30058 30497 E TileDownloader:        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:788)
03-21 14:13:01.265 30058 30497 E TileDownloader:        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
03-21 14:13:01.265 30058 30497 E TileDownloader:        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
03-21 14:13:01.265 30058 30497 E TileDownloader:        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:231)
03-21 14:13:01.265 30058 30497 E TileDownloader:        at java.net.URL.openStream(URL.java:470)
03-21 14:13:01.265 30058 30497 E TileDownloader:        at org.mapsforge.v3.android.maps.mapgenerator.tiledownloader.TileDownloader.executeJob(TileDownloader.java:59)
03-21 14:13:01.265 30058 30497 E TileDownloader:        at org.mapsforge.v3.android.maps.mapgenerator.MapWorker.doWork(MapWorker.java:73)
03-21 14:13:01.265 30058 30497 E TileDownloader:        at org.mapsforge.v3.android.maps.PausableThread.run(PausableThread.java:94)
```

After this:
```03-21 14:13:04.378 30058 30433 D cgeo    : [OkHttp] 200 (3174 ms) GET https://tiles.geocaching.com/map.png?x=5998&y=9208&z=14&ep=1&app=cgeo&k=HZlT5&st=-yUQd3_Uul2T3C4tE0HCkXePe7NWnG4poCh0M0RsKk84PIx4iBXrIYz0Wk31lv_Msw4luTIk9INJnggM9PLo-4jHp6WBLmxdxXq-a2a52CBV9hGevynY6Yhl59kRYDsgAfT585XMpN697cjxZz65dw2 (http/1.1)
03-21 14:13:04.384 30058 30433 D cgeo    : [OkHttp] GET https://tiles.geocaching.com/map.info?x=5998&y=9208&z=14&ep=1&app=cgeo&k=HZlT5&st=-yUQd3_Uul2T3C4tE0HCkXePe7NWnG4poCh0M0RsKk84PIx4iBXrIYz0Wk31lv_Msw4luTIk9INJnggM9PLo-4jHp6WBLmxdxXq-a2a52CBV9hGevynY6Yhl59kRYDsgAfT585XMpN697cjxZz65dw2
03-21 14:13:05.750 30058 30433 D cgeo    : [OkHttp] 204 (1366 ms) GET https://tiles.geocaching.com/map.info?x=5998&y=9208&z=14&ep=1&app=cgeo&k=HZlT5&st=-yUQd3_Uul2T3C4tE0HCkXePe7NWnG4poCh0M0RsKk84PIx4iBXrIYz0Wk31lv_Msw4luTIk9INJnggM9PLo-4jHp6WBLmxdxXq-a2a52CBV9hGevynY6Yhl59kRYDsgAfT585XMpN697cjxZz65dw2 (http/1.1)
03-21 14:13:05.760 30058 30601 W cgeo    : [RxComputationThreadPool-3] GCMap.searchByViewport: No data from server for tile (5998/9208)
03-21 14:13:05.763 30058 30433 D cgeo    : [OkHttp] GET https://tiles.geocaching.com/map.png?x=5998&y=9209&z=14&ep=1&app=cgeo&k=HZlT5&st=-yUQd3_Uul2T3C4tE0HCkXePe7NWnG4poCh0M0RsKk84PIx4iBXrIYz0Wk31lv_Msw4luTIk9INJnggM9PLo-4jHp6WBLmxdxXq-a2a52CBV9hGevynY6Yhl59kRYDsgAfT585XMpN697cjxZz65dw2
03-21 14:13:06.117 30058 30433 D cgeo    : [OkHttp] 200 (354 ms) GET https://tiles.geocaching.com/map.png?x=5998&y=9209&z=14&ep=1&app=cgeo&k=HZlT5&st=-yUQd3_Uul2T3C4tE0HCkXePe7NWnG4poCh0M0RsKk84PIx4iBXrIYz0Wk31lv_Msw4luTIk9INJnggM9PLo-4jHp6WBLmxdxXq-a2a52CBV9hGevynY6Yhl59kRYDsgAfT585XMpN697cjxZz65dw2 (http/1.1)
03-21 14:13:06.119 30058 30433 D cgeo    : [OkHttp] GET https://tiles.geocaching.com/map.info?x=5998&y=9209&z=14&ep=1&app=cgeo&k=HZlT5&st=-yUQd3_Uul2T3C4tE0HCkXePe7NWnG4poCh0M0RsKk84PIx4iBXrIYz0Wk31lv_Msw4luTIk9INJnggM9PLo-4jHp6WBLmxdxXq-a2a52CBV9hGevynY6Yhl59kRYDsgAfT585XMpN697cjxZz65dw2
03-21 14:13:06.256  1783 28973 D NetlinkSocketObserver: NeighborEvent{elapsedMs=1075773124, fe80::21e:c1ff:fee1:b5aa, [001EC1E1B5AA], RTM_NEWNEIGH, NUD_STALE}
03-21 14:13:06.464 30058 30433 D cgeo    : [OkHttp] 204 (345 ms) GET https://tiles.geocaching.com/map.info?x=5998&y=9209&z=14&ep=1&app=cgeo&k=HZlT5&st=-yUQd3_Uul2T3C4tE0HCkXePe7NWnG4poCh0M0RsKk84PIx4iBXrIYz0Wk31lv_Msw4luTIk9INJnggM9PLo-4jHp6WBLmxdxXq-a2a52CBV9hGevynY6Yhl59kRYDsgAfT585XMpN697cjxZz65dw2 (http/1.1)
03-21 14:13:06.471 30058 30602 W cgeo    : [RxComputationThreadPool-4] GCMap.searchByViewport: No data from server for tile (5998/9209)
03-21 14:13:06.473 30058 30552 D cgeo    : [network--5] GCMap: returning 0 caches from search
03-21 14:13:06.473 30058 30506 D cgeo    : [pool-5-thread-1] Filtering out 0 caches: []
03-21 14:13:07.272  1783  2314 I InputDispatcher: Application is not responding: Window{facc0a5 u0 cgeo.geocaching/cgeo.geocaching.MainActivity}.  It has been 5078.8ms since event, 5005.6ms since wait started.  Reason: Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 2.  Wait queue head age: 6114.5ms.
03-21 14:13:07.281  1783  2314 I WindowManager: Input event dispatching timed out sending to cgeo.geocaching/cgeo.geocaching.MainActivity.  Reason: Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 2.  Wait queue head age: 6114.5ms.
03-21 14:13:07.310  1783  1854 I Process : Sending signal. PID: 30058 SIG: 3
03-21 14:13:07.319 30058 30066 I art     : Thread[2,tid=30066,WaitingInMainSignalCatcherLoop,Thread*=0xb8e53268,peer=0x22c070a0,"Signal Catcher"]: reacting to signal 3
03-21 14:13:07.413  1783  2311 V AlarmManager: sending alarm {1cd510f type 2 *walarm*:com.google.android.location.ALARM_WAKEUP_LOCATOR}
03-21 14:13:07.510  1783  1854 I Process : Sending signal. PID: 1783 SIG: 3
03-21 14:13:07.510  1783  1788 I art     : Thread[2,tid=1788,WaitingInMainSignalCatcherLoop,Thread*=0xb802ddd0,peer=0x12c010a0,"Signal Catcher"]: reacting to signal 3
03-21 14:13:07.654 30058 30066 I art     : Wrote stack traces to '/data/anr/traces.txt'
(...)
03-21 14:13:14.718  1783  1854 E ActivityManager: ANR in cgeo.geocaching (cgeo.geocaching/.MainActivity)
03-21 14:13:14.718  1783  1854 E ActivityManager: PID: 30058
03-21 14:13:14.718  1783  1854 E ActivityManager: Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 2.  Wait queue head age: 6114.5ms.)
```

**Comment by Lineflyer** [comment]
@naoliv Thanks for the detailed info.
How long was the time between step 1 and step 2 (Opening time of Live map)? Does it only happen if live map is still loading caches (spinner on the top), or independently of the time you spent on live map?

**Comment by naoliv** [comment]
Indeed.
Clicking `Live map` and waiting for everything to load, getting back to main menu and then `Stored` works without any problem.

Clicking `Live map`, getting back without loading everything (like the example below) and just waiting (it seems that it's not even necessary to click on `Stored`), makes the app to not respond.

![](https://cloud.githubusercontent.com/assets/982338/24171336/cf15fc92-0e62-11e7-90c1-42e04759106c.png)

**Comment by Lineflyer** [comment]
We do indeed have 9 ANR events also in our Google Play reports.
7 of them are occuring on MainActivity (1 in Compass, 1 in MapsforgeMap).

**Comment by Lineflyer** [comment]
Addon:
Most of them are reported from a Motorola Android 6.0 device.
@naoliv Was that possibly you?

**Comment by naoliv** [comment]
Most of them are reported from a Motorola Android 6.0 device.
@naoliv <https://github.com/naoliv> Was that possibly you?


Most probably they are all mine.

**Comment by Lineflyer** [comment]
Closing due to no update.
Additionally are about to change to new mapsforge library versions, where the problem might have changed / disappeared.
Feel free to open a new issue or reopen this issue with new information.

**Comment by naoliv** [comment]
I can still reproduce it with c:geo 2018.02.05
I also don't know what else I can do to try to help with this.

**Comment by Lineflyer** [comment]
Could you please try to activate "Mapsforge Beta" in Settings/System and try again?

**Comment by naoliv** [comment]
Great!
It's properly working with Mapsforge Beta.
I couldn't see a single freeze even after multiple tests.

**Comment by Lineflyer** [comment]
So as this will get live in future we can close this issue then.
Thanks for the feedback.
