### ISSUE TITLE
App crashs while trying to move a stored cache to another list

### ISSUE THREAD

**Issue by naoliv** [cgeo/cgeo#6419]
##### Detailed steps causing the problem:
- Select one stored cache
- Ask to move to another list

##### Actual behavior after performing these steps:
The app crashes

##### Expected behavior after performing these steps:
The cache should be moved to the other list

##### Version of c:geo used:
`2017.03.19`

##### Is the problem reproducible for you?
Yes

##### System information:
```
Device: XT1069 (titan_retbr_dstv, motorola)
Android version: 6.0
Android build: MPB24.65-34-3
Cgeo version: 2017.03.19
Google Play services: enabled - 10.2.98 (436-146496160)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: detailed
HW acceleration: enabled (default state)
System language: pt_BR (cgeo forced to English)
System date format: dd/MM/yy
Debug mode active: no
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
Geocaching.com date format: dd/MM/yyyy
Installed cgeo plugins:  none
```

##### Other comments and remarks:
From logcat:

```
03-21 09:07:36.814 12037 17477 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
03-21 09:07:36.814 12037 17477 E AndroidRuntime: Process: cgeo.geocaching, PID: 12037
03-21 09:07:36.814 12037 17477 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at android.os.AsyncTask$3.done(AsyncTask.java:309)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:242)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
03-21 09:07:36.814 12037 17477 E AndroidRuntime: Caused by: java.lang.UnsupportedOperationException
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at java.util.Collections$SingletonSet$1.remove(Collections.java:260)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at java.util.AbstractCollection.remove(AbstractCollection.java:229)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at cgeo.geocaching.storage.DataStore.moveToList(DataStore.java:2939)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at cgeo.geocaching.command.MoveToListCommand.doCommand(MoveToListCommand.java:47)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at cgeo.geocaching.CacheListActivity$14.doCommand(CacheListActivity.java:965)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at cgeo.geocaching.command.AbstractCommand$ActionAsyncTask.doInBackgroundInternal(AbstractCommand.java:110)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at cgeo.geocaching.command.AbstractCommand$ActionAsyncTask.doInBackgroundInternal(AbstractCommand.java:103)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at cgeo.geocaching.utils.AsyncTaskWithProgress.doInBackground(AsyncTaskWithProgress.java:104)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-21 09:07:36.814 12037 17477 E AndroidRuntime:        ... 4 more
03-21 09:07:36.830  1783  4144 W ActivityManager:   Force finishing activity cgeo.geocaching/.CacheListActivity
```

```
03-21 09:07:37.350 12037 12037 E WindowManager: android.view.WindowLeaked: Activity cgeo.geocaching.CacheListActivity has leaked window com.android.internal.policy.PhoneWindow$DecorView{3dbce2b V.E...... R.....ID 0,0-684,192} that was originally added here
03-21 09:07:37.350 12037 12037 E WindowManager:         at android.view.ViewRootImpl.<init>(ViewRootImpl.java:375)
03-21 09:07:37.350 12037 12037 E WindowManager:         at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
03-21 09:07:37.350 12037 12037 E WindowManager:         at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
03-21 09:07:37.350 12037 12037 E WindowManager:         at android.app.Dialog.show(Dialog.java:319)
03-21 09:07:37.350 12037 12037 E WindowManager:         at cgeo.geocaching.activity.Progress.show(Progress.java:45)
03-21 09:07:37.350 12037 12037 E WindowManager:         at cgeo.geocaching.utils.AsyncTaskWithProgress.onPreExecute(AsyncTaskWithProgress.java:67)
03-21 09:07:37.350 12037 12037 E WindowManager:         at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:604)
03-21 09:07:37.350 12037 12037 E WindowManager:         at android.os.AsyncTask.execute(AsyncTask.java:551)
03-21 09:07:37.350 12037 12037 E WindowManager:         at cgeo.geocaching.command.AbstractCommand.execute(AbstractCommand.java:96)
03-21 09:07:37.350 12037 12037 E WindowManager:         at cgeo.geocaching.command.MoveToListCommand.access$101(MoveToListCommand.java:16)
03-21 09:07:37.350 12037 12037 E WindowManager:         at cgeo.geocaching.command.MoveToListCommand$1.call(MoveToListCommand.java:39)
03-21 09:07:37.350 12037 12037 E WindowManager:         at cgeo.geocaching.command.MoveToListCommand$1.call(MoveToListCommand.java:29)
03-21 09:07:37.350 12037 12037 E WindowManager:         at cgeo.geocaching.list.StoredList$UserInterface$3.call(StoredList.java:229)
03-21 09:07:37.350 12037 12037 E WindowManager:         at cgeo.geocaching.list.StoredList$UserInterface$3.call(StoredList.java:215)
03-21 09:07:37.350 12037 12037 E WindowManager:         at cgeo.geocaching.list.StoredList$UserInterface$5.call(StoredList.java:275)
03-21 09:07:37.350 12037 12037 E WindowManager:         at cgeo.geocaching.list.StoredList$UserInterface$5.call(StoredList.java:268)
03-21 09:07:37.350 12037 12037 E WindowManager:         at cgeo.geocaching.ui.dialog.Dialogs$2.onClick(Dialogs.java:404)
03-21 09:07:37.350 12037 12037 E WindowManager:         at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:163)
03-21 09:07:37.350 12037 12037 E WindowManager:         at android.os.Handler.dispatchMessage(Handler.java:102)
03-21 09:07:37.350 12037 12037 E WindowManager:         at android.os.Looper.loop(Looper.java:148)
03-21 09:07:37.350 12037 12037 E WindowManager:         at android.app.ActivityThread.main(ActivityThread.java:5443)
03-21 09:07:37.350 12037 12037 E WindowManager:         at java.lang.reflect.Method.invoke(Native Method)
03-21 09:07:37.350 12037 12037 E WindowManager:         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
03-21 09:07:37.350 12037 12037 E WindowManager:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
03-21 09:07:37.389  1783  2377 W WindowManager: Failed looking up window
03-21 09:07:37.389  1783  2377 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@cfad71f does not exist
03-21 09:07:37.389  1783  2377 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8803)
03-21 09:07:37.389  1783  2377 W WindowManager:         at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8794)
03-21 09:07:37.389  1783  2377 W WindowManager:         at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2740)
03-21 09:07:37.389  1783  2377 W WindowManager:         at com.android.server.wm.Session.remove(Session.java:187)
03-21 09:07:37.389  1783  2377 W WindowManager:         at android.view.IWindowSession$Stub.onTransact(IWindowSession.java:242)
03-21 09:07:37.389  1783  2377 W WindowManager:         at com.android.server.wm.Session.onTransact(Session.java:130)
03-21 09:07:37.389  1783  2377 W WindowManager:         at android.os.Binder.execTransact(Binder.java:453)
```

**Comment by samueltardieu** [comment]
@naoliv Did you load the cache using send2cgeo?

**Comment by naoliv** [comment]
Yes, I did use send2cgeo.

**Comment by samueltardieu** [comment]
Ok, this is being fixed. Thanks for the very detailed bug report!
