### ISSUE TITLE
IllegalStateException (Theme.AppCompat)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6430]
From Google Play.
At the moment only a single report from Android 6.0 Motorola device.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.MainActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
	at android.support.v7.app.ActionBarActivityDelegate.onCreate(ActionBarActivityDelegate.java:110)
	at android.support.v7.app.ActionBarActivityDelegateICS.onCreate(ActionBarActivityDelegateICS.java:57)
	at android.support.v7.app.ActionBarActivity.onCreate(ActionBarActivity.java:99)
	at cgeo.geocaching.activity.AbstractActivity.onCreate(AbstractActivity.java:123)
	at cgeo.geocaching.activity.AbstractActionBarActivity.onCreate(AbstractActionBarActivity.java:28)
	at cgeo.geocaching.MainActivity.onCreate(MainActivity.java:219)
	at android.app.Activity.performCreate(Activity.java:6245)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
	... 9 more
```

**Comment by Lineflyer** [comment]
No longer appearing.
