### ISSUE TITLE
NoSuchMethodError (StringUtils.isNoneEmpty)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6431]
From Google Play starting with November 2016 release:
Users are all on Xiaomi devices (running Andoird 4.4 - 6.0). So I assume this is a fault in Xiamo again, but I would like you to confirm and evaluate the possibility of a workaround.

Seems to be related to trackable activities.

Log:
```
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.isNoneEmpty
	at cgeo.geocaching.log.LogTrackableActivity$Poster.doInBackgroundInternal(LogTrackableActivity.java:510)
	at cgeo.geocaching.log.LogTrackableActivity$Poster.doInBackgroundInternal(LogTrackableActivity.java:480)
	at cgeo.geocaching.utils.AsyncTaskWithProgress.doInBackground(AsyncTaskWithProgress.java:104)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by samueltardieu** [comment]
This is not only easily fixable, but also I think this method is not the one the author of this line wanted to use :-)
