### ISSUE TITLE
NoSuchMethodError (onTrimMemory)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6445]
On Google Play reported for our new legacy version 2017.02.30-legacy with devices on Android 2.3x

```
java.lang.NoSuchMethodError: android.app.Application.onTrimMemory
	at cgeo.geocaching.CgeoApplication.onTrimMemory(CgeoApplication.java:116)
	at cgeo.geocaching.CgeoApplication.onLowMemory(CgeoApplication.java:110)
	at android.app.ActivityThread.handleLowMemory(ActivityThread.java:3110)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1021)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.app.ActivityThread.main(ActivityThread.java:3687)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:507)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:625)
	at dalvik.system.NativeStart.main(Native Method)`
```

According to [Android Developer Guide](https://developer.android.com/reference/android/content/ComponentCallbacks2.html#onTrimMemory(int)) it has only been implemented in API 14.

**Comment by samueltardieu** [comment]
Fixed in `cgeo-legacy` branch.
