### ISSUE TITLE
NullPointerException (Mapsforge V3)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6446]
Appearing on Google Play crash reports starting with November 2016 releases.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.isRecycled()' on a null object reference
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1307)
	at android.graphics.Canvas.drawBitmap(Canvas.java:1363)
	at org.mapsforge.v3.android.maps.FrameBuffer.drawBitmap(FrameBuffer.java:101)
	at org.mapsforge.v3.android.maps.MapView.redrawTiles(MapView.java:402)
	at org.mapsforge.v3.android.maps.inputhandling.MultiTouchHandler.onActionMove(MultiTouchHandler.java:91)
	at org.mapsforge.v3.android.maps.inputhandling.MultiTouchHandler.handleMotionEvent(MultiTouchHandler.java:186)
	at org.mapsforge.v3.android.maps.inputhandling.TouchEventHandler.handleTouchEvent(TouchEventHandler.java:149)
	at org.mapsforge.v3.android.maps.MapView.onTouchEvent(MapView.java:349)
	at cgeo.geocaching.maps.mapsforge.MapsforgeMapView.onTouchEvent(MapsforgeMapView.java:277)
	at android.view.View.dispatchTouchEvent(View.java:9187)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2680)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2351)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2691)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2366)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2743)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1836)
	at android.app.Activity.dispatchTouchEvent(Activity.java:3043)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2704)
	at android.view.View.dispatchPointerEvent(View.java:9397)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5082)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4899)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4356)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4409)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4375)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4501)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4383)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4558)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4356)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4409)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4375)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4383)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4356)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6979)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6852)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6823)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7069)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7040)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7092)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:829)
	at android.view.Choreographer.doCallbacks(Choreographer.java:606)
	at android.view.Choreographer.doFrame(Choreographer.java:574)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:815)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6934)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

**Comment by Lineflyer** [comment]
A report from the new "Android vitals" looks related.

Crashes: 4800   Users: 2180

```

java.lang.NullPointerException: 
  at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1270)
  at android.graphics.Canvas.drawBitmap(Canvas.java:1336)
  at org.mapsforge.v3.android.maps.FrameBuffer.drawBitmap(FrameBuffer.java:101)
  at org.mapsforge.v3.android.maps.MapView.redrawTiles(MapView.java:402)
  at org.mapsforge.v3.android.maps.inputhandling.MultiTouchHandler.onActionMove(MultiTouchHandler.java:91)
  at org.mapsforge.v3.android.maps.inputhandling.MultiTouchHandler.handleMotionEvent(MultiTouchHandler.java:186)
  at org.mapsforge.v3.android.maps.inputhandling.TouchEventHandler.handleTouchEvent(TouchEventHandler.java:149)
  at org.mapsforge.v3.android.maps.MapView.onTouchEvent(MapView.java:349)
  at cgeo.geocaching.maps.mapsforge.MapsforgeMapView.onTouchEvent(MapsforgeMapView.java:277)
  at android.view.View.dispatchTouchEvent(View.java:10011)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2665)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2344)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
  at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2671)
  at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2358)
  at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:447)
  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
  at android.app.Activity.dispatchTouchEvent(Activity.java:3213)
  at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:409)
  at android.view.View.dispatchPointerEvent(View.java:10231)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4851)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4711)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4244)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4297)
  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4263)
  at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4390)
  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4271)
  at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4447)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4244)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4297)
  at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4263)
  at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4271)
  at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4244)
  at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6671)
  at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6645)
  at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6606)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6798)
  at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:192)
  at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method:0)
  at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:181)
  at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:6745)
  at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6826)
  at android.view.Choreographer$CallbackRecord.run(Choreographer.java:923)
  at android.view.Choreographer.doCallbacks(Choreographer.java:735)
  at android.view.Choreographer.doFrame(Choreographer.java:661)
  at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:909)
  at android.os.Handler.handleCallback(Handler.java:761)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at android.os.Looper.loop(Looper.java:156)
  at android.app.ActivityThread.main(ActivityThread.java:6524)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

**Comment by Lineflyer** [comment]
Looking into the current and older crash reports on Google Play this problem is definitly the most occuring crash:
Reports in this week: 566
Reports total: 5600
Affected users: 2500

It seems to be happening on Samsung Galaxy and LG devices only, on several supported Android versions.

**Comment by Lineflyer** [comment]
Closing as wont fix, as we are about to phase out the mapsforge v0.3 anyway.
