### ISSUE TITLE
ArithmeticException (Division by zero)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6447]
Starting with December 2016 release on Google Play:

```
java.lang.ArithmeticException: divide by zero
	at cgeo.geocaching.maps.CGeoMap$LoadDetailsHandler.handleRegularMessage(CGeoMap.java:328)
	at cgeo.geocaching.utils.DisposableHandler.handleMessage(DisposableHandler.java:58)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5942)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
```

Rare occurence
User note: "when offline downloaded"

**Comment by samueltardieu** [comment]
I just read the corresponding code and it is such a mess! Global variables used everywhere, between the handler and the code, open to race conditions. I'll reinstate defensive code around this, but this *must* be rewritten at some point.
