### ISSUE TITLE
RunTimeException (doInBackground)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6458]
From Google Play.
Is this due to people having activated debug logging?
Anyhow, can this be avoided?

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:318)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.RuntimeException: Aborting on Log.e()
	at cgeo.geocaching.utils.Log.e(Log.java:98)
	at cgeo.geocaching.connector.gc.GCLogin.getLoginStatus(GCLogin.java:211)
	at cgeo.geocaching.connector.gc.GCLogin.postRequestLogged(GCLogin.java:506)
	at cgeo.geocaching.connector.gc.GCParser.postLog(GCParser.java:1172)
	at cgeo.geocaching.connector.gc.GCLoggingManager.postLog(GCLoggingManager.java:105)
	at cgeo.geocaching.log.LogCacheActivity$Poster.doInBackgroundInternal(LogCacheActivity.java:606)
	at cgeo.geocaching.log.LogCacheActivity$Poster.doInBackgroundInternal(LogCacheActivity.java:592)
	at cgeo.geocaching.utils.AbstractAsyncTaskWithProgress.doInBackground(AbstractAsyncTaskWithProgress.java:132)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

**Comment by samueltardieu** [comment]
Yes. This can be avoided by not activating debug when you are not a developer. This behaviour has been done on purpose to avoid cases where an exception is silently logged and missed by the developers.

Maybe add a FAQ entry saying "do not activate debug unless cgeo support ask you so".

**Comment by pstorch** [comment]
Just an idea: should we present a dialog in `Log.e()` to inform the user that debug logging is enabled and that we now stop c:geo because an error has been logged?

**Comment by samueltardieu** [comment]
We are not always in the context of an activity. We might even be in a background thread.

**Comment by samueltardieu** [comment]
But I'm open to any idea to implement this or render it less painful to the end user.

**Comment by Bananeweizen** [comment]
One simple thing might be resetting the debug flag on every application start. However, that would reduce its usage to reproducing a certain use case, but no longer the "explorative finding" of bugs.

**Comment by samueltardieu** [comment]
This would defeat the purpose of being always active for developers who want to catch fatal errors to fix them. We may want to be more explicit in the settings when we describe this option though.

**Comment by Lineflyer** [comment]
Debug log setting is IMHO fine as it is. I will check the setting text and see if it could be improved though.
