### ISSUE TITLE
Illegal state exception (SQLiteConnectionPool)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6488]
From google play for version 2017.03.29 (also present in older versions but higher occurence now):
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.CacheListActivity}: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3255)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3351)
	at android.app.ActivityThread.access$1100(ActivityThread.java:222)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1796)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7230)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: java.lang.IllegalStateException: Cannot perform this operation because the connection pool has been closed.
	at android.database.sqlite.SQLiteConnectionPool.throwIfClosedLocked(SQLiteConnectionPool.java:1027)
	at android.database.sqlite.SQLiteConnectionPool.waitForConnection(SQLiteConnectionPool.java:742)
	at android.database.sqlite.SQLiteConnectionPool.acquireConnection(SQLiteConnectionPool.java:397)
	at android.database.sqlite.SQLiteSession.acquireConnection(SQLiteSession.java:905)
	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:834)
	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
	at cgeo.geocaching.storage.DataStore.cursorToColl(DataStore.java:2302)
	at cgeo.geocaching.storage.DataStore.getListsFromCursor(DataStore.java:2765)
	at cgeo.geocaching.storage.DataStore.getList(DataStore.java:2786)
	at cgeo.geocaching.CacheListActivity.onCreateLoader(CacheListActivity.java:1778)
	at android.support.v4.app.LoaderManagerImpl.createLoader(LoaderManager.java:539)
	at android.support.v4.app.LoaderManagerImpl.createAndInstallLoader(LoaderManager.java:548)
	at android.support.v4.app.LoaderManagerImpl.initLoader(LoaderManager.java:602)
	at cgeo.geocaching.CacheListActivity.onCreate(CacheListActivity.java:470)
	at android.app.Activity.performCreate(Activity.java:6877)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3208)
	... 9 more
```

According to user comments it happens on startup of c:geo or short after.

**Comment by Lineflyer** [comment]
This specific crash report can not be found in the history of the last 30 days. Closing for now.
