### ISSUE TITLE
App crashes with loss of database

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6525]
On support mail we have a user, who claims that c:geo constantly crashes when accessing the live map or the list of saved caches. After the crash the DB is empty.
Version used: 2017.03.29

The user send me his DB and I can reproduce it by opening the list "PQs" (using 2017.04.25-NB)
This is the log of the crash:
```
---- 26.04.2017 13:55:33 ----
04-26 13:55:36.685  3097  3097 E SQLiteDatabase: PRAGMA integrity_check on /data/user/0/cgeo.geocaching/databases/data returned: *** in database main ***
04-26 13:55:37.712  3097  3097 E SQLiteDatabase: PRAGMA integrity_check on /data/user/0/cgeo.geocaching/databases/data returned: *** in database main ***
04-26 13:55:37.719  3097  3097 E DefaultDatabaseErrorHandler: !@ Back up corrupted DB File : /data/user/0/cgeo.geocaching/databases/data
04-26 13:55:37.731  3097  3097 W cgeo    : [main] UncaughtException
04-26 13:55:37.731  3097  3097 W cgeo    : android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 11)
04-26 13:55:37.731  3097  3097 W cgeo    : #################################################################
04-26 13:55:37.731  3097  3097 W cgeo    : Error Code : 11 (SQLITE_CORRUPT)
04-26 13:55:37.731  3097  3097 W cgeo    : Caused By : The database disk image is malformed.
04-26 13:55:37.731  3097  3097 W cgeo    : 	(database disk image is malformed (code 11))
04-26 13:55:37.731  3097  3097 W cgeo    : #################################################################
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:927)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:143)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:132)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:219)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:268)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at cgeo.geocaching.storage.DataStore.loadCachesFromGeocodes(DataStore.java:1743)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at cgeo.geocaching.storage.DataStore.loadCaches(DataStore.java:1688)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at cgeo.geocaching.SearchResult.getCachesFromSearchResult(SearchResult.java:251)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at cgeo.geocaching.CacheListActivity.onLoadFinished(CacheListActivity.java:1914)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at cgeo.geocaching.CacheListActivity.onLoadFinished(CacheListActivity.java:132)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.support.v4.content.Loader.deliverResult(Loader.java:126)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:249)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:77)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:466)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.os.Looper.loop(Looper.java:154)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:6688)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
04-26 13:55:37.731  3097  3097 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
04-26 13:55:37.731  3097  3097 E AndroidRuntime: Process: cgeo.geocaching, PID: 3097
04-26 13:55:37.731  3097  3097 E AndroidRuntime: 	at cgeo.geocaching.storage.DataStore.loadCachesFromGeocodes(DataStore.java:1743)
04-26 13:55:37.731  3097  3097 E AndroidRuntime: 	at cgeo.geocaching.storage.DataStore.loadCaches(DataStore.java:1688)
04-26 13:55:37.731  3097  3097 E AndroidRuntime: 	at cgeo.geocaching.SearchResult.getCachesFromSearchResult(SearchResult.java:251)
04-26 13:55:37.731  3097  3097 E AndroidRuntime: 	at cgeo.geocaching.CacheListActivity.onLoadFinished(CacheListActivity.java:1914)
04-26 13:55:37.731  3097  3097 E AndroidRuntime: 	at cgeo.geocaching.CacheListActivity.onLoadFinished(CacheListActivity.java:132)
04-26 13:55:37.734  4967  6619 W ActivityManager:   Force finishing activity cgeo.geocaching/.CacheListActivity
04-26 13:55:37.737  4967  6619 W ActivityManager:   Force finishing activity cgeo.geocaching/.MainActivity
04-26 13:55:39.575  4967  6619 W ActivityManager:   Force finishing activity cgeo.geocaching/.CacheListActivity
04-26 13:55:39.609  4967  6619 I WindowManager: Destroying surface Surface(name=cgeo.geocaching/cgeo.geocaching.CacheListActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2838 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1069 com.android.server.wm.WindowState.removeLocked:1776 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2876 com.android.server.wm.WindowManagerService.removeWindowLocked:2826 com.android.server.wm.WindowManagerService.removeWindowLocked:2641 com.android.server.wm.AppWindowToken.removeAllWindows:596 com.android.server.wm.AppWindowToken.removeAppFromTaskLocked:358 
04-26 13:55:39.636  4967  6619 W ActivityManager:   Force finishing activity cgeo.geocaching/.MainActivity
04-26 13:55:39.640  4967  6619 I WindowManager: Destroying surface Surface(name=cgeo.geocaching/cgeo.geocaching.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2838 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1069 com.android.server.wm.WindowState.removeLocked:1776 com.android.server.wm.WindowManagerService.removeWindowInnerLocked:2876 com.android.server.wm.WindowManagerService.removeWindowLocked:2826 com.android.server.wm.WindowManagerService.removeWindowLocked:2641 com.android.server.wm.AppWindowToken.removeAllWindows:596 com.android.server.wm.AppWindowToken.removeAppFromTaskLocked:358 
04-26 13:55:39.659  4967  6619 I ActivityManager: Killing 3097:cgeo.geocaching/u0a171 (adj 900): crash
04-26 13:55:39.927  4967  5051 I WindowManager: Destroying surface Surface(name=Application Error: cgeo.geocaching) called by com.android.server.wm.WindowStateAnimator.destroySurface:2838 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:1069 com.android.server.wm.WindowState.destroyOrSaveSurface:2534 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementInner:499 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacementLoop:274 com.android.server.wm.WindowSurfacePlacer.performSurfacePlacement:222 com.android.server.wm.WindowManagerService$H.handleMessage:9161 android.os.Handler.dispatchMessage:102 
---- 26.04.2017 13:55:40 ----
```

It seems the DB is corrupted. The user tells, that this often happens to him after importing/saving caches.
So it might be worth taking a look what exactly is broken here, why this might have happend and if we can either avoid the corrupt data or handle it better than crashing and reseting.

I will send a link to the DB file via cgeo-dev mailing list.

**Comment by pstorch** [comment]
I can reproduce it:

Most of it is working, but when selecting the List named `PQ`, I get the crash: 
```
04-26 22:10:51.326 25221-25221/cgeo.geocaching E/SQLiteLog: (11) database corruption at line 56220 of [bda77dda96]
04-26 22:10:51.326 25221-25221/cgeo.geocaching E/SQLiteLog: (11) database corruption at line 56262 of [bda77dda96]
04-26 22:10:51.327 25221-25221/cgeo.geocaching E/SQLiteLog: (11) statement aborts at 1519: [SELECT cg_caches.updated,cg_caches.reason,cg_caches.detailed,cg_caches.detailedupdate,cg_caches.visiteddate,cg_caches.geocode,cg_caches.cacheid,cg_caches.guid,cg_caches.type,cg_cache
04-26 22:10:51.327 25221-25221/cgeo.geocaching E/DefaultDatabaseErrorHandler: Corruption reported by sqlite on database: /data/user/0/cgeo.geocaching/databases/data
04-26 22:10:51.328 25221-25221/cgeo.geocaching E/DefaultDatabaseErrorHandler: deleting the database file: /data/user/0/cgeo.geocaching/databases/data
04-26 22:10:51.329 25221-25221/cgeo.geocaching D/AndroidRuntime: Shutting down VM
04-26 22:10:51.330 25221-25221/cgeo.geocaching W/cgeo: [main] UncaughtException
                                                       android.database.sqlite.SQLiteDatabaseCorruptException: database disk image is malformed (code 11)
                                                           at android.database.sqlite.SQLiteConnection.nativeExecuteForCursorWindow(Native Method)
                                                           at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:845)
```

I tried to open it with a desktop tool `DB Browser for SQLite` and it can't display the `cg_caches` table.

**Comment by pstorch** [comment]
I was able to recover the DB with this method: https://stackoverflow.com/questions/18259692/how-to-recover-a-corrupt-sqlite3-database
First answer: `$ sqlite3 cgeo_issue6525.sqlite ".dump" | sqlite3 cgeo_corrected.sqlite`
Additionally I had to open the DB with "DB Browser for SQLite" and set the `User Version` to `72` (as it was).

@Lineflyer if the user likes to have the recovered DB, I can send it to you.

**Comment by Lineflyer** [comment]
> First answer: $ sqlite3 cgeo_issue6525.sqlite ".dump" | sqlite3 cgeo_corrected.sqlite

That does not answer why it got corrupted....but I guess its difficult to find out anyway.
Wouldn't it be then an option to firstly try to recover a corruption by this before finally deleting it on permanent error?

Of course, please send it to our support address, so that I can C&P it directly to the user.
Did you check what the repair action did...have datasets been deleted?

**Comment by pstorch** [comment]
No, sorry, this was not an analysis of possible causes. I first tried to recover it. The answer in the linked article says that most often the indices get corrupted. But I don't know why. 
And I haven't had time to exactly compare the result with the original. I just opened it and switched through the lists. 
You asked if we can do the recovery directly in c:geo? I don't know if the Java api supports this. I have used the sqlite3 command line tool. But I can have a look. 
I'll also send a link to the recovered file.

**Comment by samueltardieu** [comment]
And since we are using an ill-method to do database save, the corruption will persist in backups if it is present when the backup is being made. See #2380.

**Comment by pstorch** [comment]
Yes, we are just copying the db file on the file system to the backup location. So it is 1:1 the same. 
If we would export the data as GPX the backup would also crash if the source db file is corrupted.

**Comment by alan666notb** [comment]
I don't know if this is any help but I used to see this fairly often on my old phone (Xperia Z3), I haven't seen it at all on my current phone (Xperia Z5).
Possible difference is that my old phone didn't have much memory to spare so I used the FolderMount app to mount the .cgeo folder on the SDcard (The phone was rooted), the Z5 has plenty of memory spare so I don't need to do that.
I guess I should have raised an issue but I couldn't reproduce it reliably, it just happened every now & again. I got used to making a backup each time I loaded a lot of caches so I could just reload that.

**Comment by Lineflyer** [comment]
Should we keep this open?
IMHO we know, that this happend due to a method which was implemented on purpose.
Despite finding and avoiding the cause of corruption (not this issue) is there anything we can do to try to repair the DB before deleting it?

And from users perspective:
Shouldn't we at least give an information to the user like: "Your database was broken and could not be recovered. To get c:geo working again your database was reset." (might be including a FAQ link (tbc))?

**Comment by pstorch** [comment]
Just followed up on this one. We actually don't delete the corrupted DB, we are copying it into the Backup directory with extension ".corrupted". What is missing is an information to the user that this just happened and where this file can be found.
Should we offer the possibility to send such a corrupted DB file to our support address?

**Comment by Lineflyer** [comment]
As there was no other case, than the single user mentioned in the original post I suggest to close this. No change needed. Feel free to reopen.
