### ISSUE TITLE
IndexOutOfBoundsException in Settings

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6555]
From Google Play first seen with 2017.05.09 (only one report up to now).

Samsung S4 Mini
Android 4.4

```
java.lang.ExceptionInInitializerError
	at cgeo.geocaching.CgeoApplication.initApplicationLocale(CgeoApplication.java:128)
	at cgeo.geocaching.CgeoApplication.onCreate(CgeoApplication.java:57)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4729)
	at android.app.ActivityThread.access$1600(ActivityThread.java:174)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1367)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:146)
	at android.app.ActivityThread.main(ActivityThread.java:5593)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IndexOutOfBoundsException
	at android.content.res.StringBlock.nativeGetString(Native Method)
	at android.content.res.StringBlock.get(StringBlock.java:82)
	at android.content.res.AssetManager.getResourceText(AssetManager.java:155)
	at android.content.res.Resources.getText(Resources.java:1424)
	at android.content.res.Resources.getString(Resources.java:1525)
	at android.content.Context.getString(Context.java:363)
	at cgeo.geocaching.settings.Settings.getKey(Settings.java:283)
	at cgeo.geocaching.settings.Settings.getInt(Settings.java:295)
	at cgeo.geocaching.settings.Settings.migrateSettings(Settings.java:120)
	at cgeo.geocaching.settings.Settings.<clinit>(Settings.java:104)
	... 14 more
```

**Comment by pstorch** [comment]
That's strange. It fails looking up the String for the preference key `R.string.pref_settingsversion`. But it definitely in the resource file.
Don't know if we should at all catch this or do some kind of fallback. 

Any other opinions?

**Comment by Bananeweizen** [comment]
This looks fishy. I don't expect that this issue comes up again and would not try to handle this. If we cannot access _that_ resource string, we will probably fail for all others afterwards, too. This is probably just the first one (the settings version key).

**Comment by Bananeweizen** [comment]
Any chance this is related to the [wrong strings shown in the settings](https://github.com/cgeo/cgeo/issues/5592) issue? The commonality is accessing wrong resources.

**Comment by Lineflyer** [comment]
I'll watch out, if there are more reports like this. At the moment - as stated before - its only a single report.

**Comment by Lineflyer** [comment]
There is one user on support mail, stating that since installation of the recent update (207.05.09) c:geo looses all its settings on every start. So he needs to reenter login data, etc. everytime (no crash however according to his report).

I recommended to delete all data of c:geo (via app manager) to have a clean start and try again.
Don't know if this can be related to this issue?!

**Comment by Lineflyer** [comment]
No more occurences on Google Play and no user reports similar to this.
