### ISSUE TITLE
NPE in Trackables

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6559]
From Google Play
Not new but happening since release 20161208 in rare occassions.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String cgeo.geocaching.models.Trackable.getGuid()' on a null object reference
	at cgeo.geocaching.log.LogTrackableActivity.onCreateLoader(LogTrackableActivity.java:118)
	at android.support.v4.app.LoaderManagerImpl.createLoader(LoaderManager.java:539)
	at android.support.v4.app.LoaderManagerImpl.createAndInstallLoader(LoaderManager.java:548)
	at android.support.v4.app.LoaderManagerImpl.initLoader(LoaderManager.java:602)
	at cgeo.geocaching.log.LogTrackableActivity.startLoader(LogTrackableActivity.java:236)
	at cgeo.geocaching.log.LogTrackableActivity.access$000(LogTrackableActivity.java:75)
	at cgeo.geocaching.log.LogTrackableActivity$3.run(LogTrackableActivity.java:228)
	at io.reactivex.internal.operators.maybe.MaybeCallbackObserver.onComplete(MaybeCallbackObserver.java:92)
	at io.reactivex.internal.operators.maybe.MaybeFilter$FilterMaybeObserver.onSuccess(MaybeFilter.java:91)
	at io.reactivex.internal.operators.maybe.MaybeObserveOn$ObserveOnMaybeObserver.run(MaybeObserveOn.java:104)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by Bananeweizen** [comment]
@samueltardieu can you check why [line 228](https://github.com/cgeo/cgeo/blob/master/main/src/cgeo/geocaching/log/LogTrackableActivity.java#L228) initializes a loader with a null trackable?

**Comment by samueltardieu** [comment]
I think this was more or less a translation of existing code. Before, `loadTrackable()` could either return a trackable or `null`, and then passed that to `startLoader()`. Now, `loadTrackable()` returns a `Maybe<Trackable>`, that is one or zero value (corresponding respectively to a non-`null` and a `null` answer).

**Comment by Bananeweizen** [comment]
From the git history I also included that your latest commit was basically just adaptation of the RX API, without any actual changes in our code (so I did not want to indicate you caused the issue). I was merely asking if invoking a loader with a null value makes sense at all from your point of view (to me it looks a bit confusing, I was thinking that if I knew we don't want to load anything, I could immediately set the related member variables instead of starting a loader, which indirectly sets all these members).

**Comment by samueltardieu** [comment]
This is probably just wrong, as the activity will terminate right away in `displayTrackable`. I'll remove this path.
