### ISSUE TITLE
RejectedExecutionException in RxJava

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6580]
From the Google Play consoles new "Android vitals" section (crashes not explicitly reported by users but collected by the system).
Reports: 3500  Users: 2942

Happening since version 20170320 on Anroid versions 4.x - 7.0.

```

io.reactivex.exceptions.UndeliverableException: 
  at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:366)
  at io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:136)
  at io.reactivex.internal.schedulers.NewThreadWorker.schedule(NewThreadWorker.java:51)
  at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:392)
  at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
  at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  at java.lang.Thread.run(Thread.java:841)
Caused by: java.util.concurrent.RejectedExecutionException: 
  at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2011)
  at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:793)
  at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:298)
  at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:519)
  at io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:129)
```

**Comment by Lineflyer** [comment]
Duplicate of #6388
