### ISSUE TITLE
OC cache export fails

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6634]
From support mail (untested):

- Load and save OC12BE3
- Try to export a GPX

Result:
c:geo crashes / shuts down

Remark:
The text contains copyright chars, not translated to HTML-entities. May that be the problem?

**Comment by pstorch** [comment]
It's the music symbol in the cache title: Vom Gasthaus zur Pyramide aus Glas

```
07-12 23:07:16.270 22805-23094/cgeo.geocaching D/cgeo: [AsyncTask #4] Loading OC12BE3 Vom Gasthaus zur Pyramide aus Glas from DB
07-12 23:07:16.282 22805-23094/cgeo.geocaching W/cgeo: [AsyncTask #4] UncaughtException
                                                       java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                           at android.os.AsyncTask$3.done(AsyncTask.java:325)
                                                           at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                           at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                           at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                           at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                           at java.lang.Thread.run(Thread.java:761)
                                                        Caused by: java.lang.IllegalArgumentException: Illegal character (b)
                                                           at cgeo.org.kxml2.io.KXmlSerializer.reportInvalidCharacter(KXmlSerializer.java:165)
                                                           at cgeo.org.kxml2.io.KXmlSerializer.writeEscaped(KXmlSerializer.java:151)
                                                           at cgeo.org.kxml2.io.KXmlSerializer.text(KXmlSerializer.java:561)
                                                           at cgeo.geocaching.utils.XmlUtils.simpleText(XmlUtils.java:24)
                                                           at cgeo.geocaching.utils.XmlUtils.multipleTexts(XmlUtils.java:39)
                                                           at cgeo.geocaching.export.GpxSerializer.exportBatch(GpxSerializer.java:125)
                                                           at cgeo.geocaching.export.GpxSerializer.writeGPX(GpxSerializer.java:97)
```

**Comment by pstorch** [comment]
The musical symbol was just what I saw in chrome. The debugger shows me a unicode character 000B which is a LINE TABULATION control character and not allowed in XML.

**Comment by pstorch** [comment]
Could be a copy&paste from MS Word according to https://web.archive.org/web/20080325092316/http://support.microsoft.com/kb/59096 and http://unicode.org/reports/tr13/tr13-9.html.

**Comment by pstorch** [comment]
Wouldn't it be better (more user friendly) to just strip illegal characters instead of throwing an Exception?

**Comment by pstorch** [comment]
Or instead of silently stripping illegal character use the replacement character U+FFFD � like GitHub is using here.

**Comment by pstorch** [comment]
Looks like OC is stripping this character when exporting to GPX from the website.

**Comment by Bananeweizen** [comment]
Silently replacing it will lead to never finding the original problems anymore, in this case OC delivering invalid XML via OKAPI. That's why I vote for not replacing the invalid characters. Our architecture around GPX is such that invalid content should not be possible, and by following that closely we have been able to report multiple errors against other tools and websites already before.
I'm aware that this means we depend on active users to report such a problem then instead, but by doing so, we have a chance to actually fix the root cause.

**Comment by pstorch** [comment]
OC is not sending invalid XML. OKAPI is based on JSON at this point where this character is valid.

**Comment by SammysHP** [comment]
Let's just escape these characters correctly, e.g. `&#x000b;`. Thus we create valid XML (that might not be parsed correctly by some XML readers, though).

**Comment by pstorch** [comment]
`&#x000b;` is invalid XML

**Comment by SammysHP** [comment]
Only in XML 1.0. ;)

> Therefore, XML 1.1 allows the use of character references to the control characters #x1 through #x1F, most of which are forbidden in XML 1.0.

https://www.w3.org/TR/xml11/

**Comment by pstorch** [comment]
Oh man, you are right. Maybe it was too late yesterday evening :D

But we should be careful:
"which are only valid in certain contexts in XML 1.1 documents, and whose usage is restricted and highly discouraged:"

**Comment by pstorch** [comment]
We are writing XML 1.0 at the moment. Can't find a statement if GPX allows XML 1.1. 
I don't know if it is a good idea to move to XML 1.1. Maybe we cause more incompatibilities with other devices.

**Comment by Bananeweizen** [comment]
If that is actually coming from OC in a somewhat valid way via JSON, then I'm also in favor of just skipping such control characters on our side. I cannot imagine any additional benefit for the user by replacing such control characters with fancy other characters.
