### ISSUE TITLE
ConcurrentModificationException in testImportOcGpx

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#6701]
Exception found in unit tests http://ci.cgeo.org/job/cgeo%20pull%20request/1061/testReport/junit/cgeo.geocaching.files/GPXImporterTest/testImportOcGpx/

Stacktrace:

```
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.next(ArrayList.java:831)
at org.assertj.core.presentation.StandardRepresentation.format(StandardRepresentation.java:367)
at org.assertj.core.presentation.StandardRepresentation.singleLineFormat(StandardRepresentation.java:390)
at org.assertj.core.presentation.StandardRepresentation.smartFormat(StandardRepresentation.java:404)
at org.assertj.core.presentation.StandardRepresentation.toStringOf(StandardRepresentation.java:137)
at org.assertj.core.error.MessageFormatter.asText(MessageFormatter.java:77)
at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:68)
at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:61)
at org.assertj.core.error.BasicErrorMessageFactory.create(BasicErrorMessageFactory.java:110)
at org.assertj.core.internal.Failures.failure(Failures.java:116)
at org.assertj.core.internal.CommonValidations.checkSizes(CommonValidations.java:119)
at org.assertj.core.internal.Iterables.assertHasSize(Iterables.java:173)
at org.assertj.core.api.AbstractIterableAssert.hasSize(AbstractIterableAssert.java:160)
at cgeo.geocaching.files.GPXImporterTest.testImportOcGpx(GPXImporterTest.java:100)
at java.lang.reflect.Method.invoke(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:205)
at junit.framework.TestCase.runBare(TestCase.java:134)
at junit.framework.TestResult$1.protect(TestResult.java:115)
at android.support.test.internal.runner.junit3.AndroidTestResult.runProtected(AndroidTestResult.java:77)
at junit.framework.TestResult.run(TestResult.java:118)
at android.support.test.internal.runner.junit3.AndroidTestResult.run(AndroidTestResult.java:55)
at junit.framework.TestCase.run(TestCase.java:124)
at android.support.test.internal.runner.junit3.NonLeakyTestSuite$NonLeakyTest.run(NonLeakyTestSuite.java:63)
at junit.framework.TestSuite.runTest(TestSuite.java:243)
at junit.framework.TestSuite.run(TestSuite.java:238)
at android.support.test.internal.runner.junit3.DelegatingTestSuite.run(DelegatingTestSuite.java:103)
at android.support.test.internal.runner.junit3.AndroidTestSuite.run(AndroidTestSuite.java:69)
at android.support.test.internal.runner.junit3.JUnit38ClassRunner.run(JUnit38ClassRunner.java:103)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1941)
```

I've seen it multiple times, it seems more frequent when screen in off.

**Comment by Bananeweizen** [comment]
in fact, this is not an exception in the test, but in the assertion message creation (since assertj tries to print the content of the list or something like that). I'm not sure if this needs to be avoided by assertj (and then would be a bug there) or if we have to make sure the object to be asserted can be iterated concurrently.
