### ISSUE TITLE
Couldn't rename file /data/user/0/cgeo.geocaching/shared_prefs/cgeo.geocaching_preferences.xml

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#6706]
```
08-22 23:17:32.213  3183  3220 E SharedPreferencesImpl: Couldn't rename file /data/user/0/cgeo.geocaching/shared_prefs/cgeo.geocaching_preferences.xml to backup file /data/user/0/cgeo.geocaching/shared_prefs/cgeo.geocaching_preferences.xml.bak
08-22 23:18:16.493  3183  3220 E SharedPreferencesImpl: Couldn't create directory for SharedPreferences file /data/user/0/cgeo.geocaching/shared_prefs/cookies.xml
```

On current release, I get bunch message like this. Maybe @pstorch know more about it?
```

--- System information ---
Device: m8 (lineage_m8, htc)
Android version: 7.1.2
Android build: lineage_m8-userdebug 7.1.2 NJH47B da85f61e38
c:geo version: 2017.08.22-2f1a321 developer build
Google Play services: disabled - 11.3.02 (438-161239932)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_US
System date format: M/d/yy
Debug mode active: yes
System internal c:geo dir: /data/user/0/cgeo.geocaching (8.1 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (8.1 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (8.1 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (224.0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by pstorch** [comment]
Hmm, I'm not aware that we move around the preferences files. But I can have a look.

**Comment by pstorch** [comment]
@kumy is it on your real device or on an emulator? Can you try to uninstall the App and try with a fresh build?

**Comment by kumy** [comment]
It s on a real device. The one behind kumy-3 jenkins executor. I ll try again...

On August 23, 2017 8:51:01 PM GMT+02:00, Peter Storch <notifications@github.com> wrote:
>@kumy is it on your real device or on an emulator? Can you try to
>uninstall the App and try with a fresh build?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/cgeo/cgeo/issues/6706#issuecomment-324428890

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kumy** [comment]
Not able to reproduce on 2017.08.23. Closing then.

Only one log related to storage on the start, @pstorch in case you're interested ;)

Thanks for looking at it, and sorry for the noise.

```
08-23 21:32:19.360 25666 25666 W cgeo    : [main] Chosen extCgeoDir null is not an available external dir, falling back to default extCgeoDir
08-23 21:32:19.363 25666 25666 W cgeo    : [main] Couldn't create the .nomedia file in /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData
08-23 21:32:19.363 25666 25666 W cgeo    : java.io.IOException: No such file or directory
08-23 21:32:19.363 25666 25666 W cgeo    : 	at java.io.UnixFileSystem.createFileExclusively0(Native Method)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:280)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at java.io.File.createNewFile(File.java:948)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at cgeo.geocaching.storage.LocalStorage.initGeocacheDataDir(LocalStorage.java:378)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at cgeo.geocaching.MainActivity.onCreate(MainActivity.java:249)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at android.app.Activity.performCreate(Activity.java:6684)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at android.os.Looper.loop(Looper.java:154)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:6186)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
08-23 21:32:19.363 25666 25666 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by pstorch** [comment]
@kumy thanks for reporting: fixed it
