### ISSUE TITLE
New build error?

### ISSUE THREAD

**Issue by kumy** [cgeo/cgeo#6756]
@pstorch do you also have those tests failing?

```
02:57.864  cgeo.geocaching.CgeoApplicationTest > testSearchByGeocodeNotExisting[m8 - 7.1.2] [31mFAILED [0m
02:57.864  	org.junit.ComparisonFailure: expected:<C[ACHE_NOT_FOUND]> but was:<C[OMMUNICATION_ERROR]>
02:57.864  	at java.lang.reflect.Constructor.newInstance0(Native Method)

03:07.609  
03:07.609  cgeo.geocaching.CgeoApplicationTest > testSearchByGeocodeNotExisting[GT-I9305 - 4.4.4] [31mFAILED [0m
03:07.610  	org.junit.ComparisonFailure: expected:<C[ACHE_NOT_FOUND]> but was:<C[OMMUNICATION_ERROR]>
03:07.610  	at java.lang.reflect.Constructor.constructNative(Native Method)
```

**Comment by pstorch** [comment]
@kumy haven't seen it yet, but I'll check tonight

**Comment by pstorch** [comment]
@kumy yes, have them, too.

Interestingly when running in emulator I have another one:
```
cgeo.geocaching.CgeoApplicationTest > testSearchByGeocodeBasis[Nexus_5_API_22_x86(AVD) - 6.0] FAILED 
        org.junit.ComparisonFailure: [Cache GC3XX5J: found status] expected:<[tru]e> but was:<[fals]e>
        at cgeo.test.Compare.assertCompareCaches(Compare.java:46)

cgeo.geocaching.CgeoApplicationTest > testSearchByGeocodeNotExisting[Nexus_5_API_22_x86(AVD) - 6.0] FAILED 
        org.junit.ComparisonFailure: expected:<C[ACHE_NOT_FOUND]> but was:<C[OMMUNICATION_ERROR]>
        at cgeo.geocaching.CgeoApplicationTest.testSearchByGeocodeNotExisting(CgeoApplicationTest.java:132)
```

Were on my physical phone I only get this one:
```
cgeo.geocaching.CgeoApplicationTest > testSearchByGeocodeNotExisting[ONEPLUS A3003 - 7.1.1] FAILED 
        org.junit.ComparisonFailure: expected:<C[ACHE_NOT_FOUND]> but was:<C[OMMUNICATION_ERROR]>
        at java.lang.reflect.Constructor.newInstance0(Native Method)
```

**Comment by kumy** [comment]
@pstorch thanks for checking. I may have got it too... Are you "interested" in fixing it?

**Comment by pstorch** [comment]
I'm firing up the test in AS to debug right now. Let's see if I can find the cause.
