### ISSUE TITLE
Calculator can crash on fast click on coordinate buttons

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6781]
I could cause an exception by fast clicking on the coordinate buttons:

```
10-16 21:11:28.798 10999-10999/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
  Process: cgeo.geocaching, PID: 10999
  java.lang.ArrayIndexOutOfBoundsException: length=3; index=3
  at cgeo.geocaching.ui.dialog.CoordinatesCalculateDialog.areCurrentCoordinatesValid(CoordinatesCalculateDialog.java:600)
  at cgeo.geocaching.ui.dialog.CoordinatesCalculateDialog.updateResult(CoordinatesCalculateDialog.java:961)
  at cgeo.geocaching.ui.dialog.CoordinatesCalculateDialog.onClickCompleteCallback(CoordinatesCalculateDialog.java:148)
  at cgeo.geocaching.ui.EditButton.handleClick(EditButton.java:125)
  at cgeo.geocaching.ui.CalculateButton.handleClick(CalculateButton.java:173)
  at cgeo.geocaching.ui.CalculateButton$CoordDigitClickListener.onClick(CalculateButton.java:156)
  at android.view.View.performClick(View.java:5669)
  at android.view.View$PerformClick.run(View.java:22549)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6321)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by S-Bartfast** [comment]
I'm not able to re-produce this error myself, either on my own device nor an emulated one.

Were you experiencing this issue with the build featuring the "tri-state buttons" or the previous "two-state" ones?

**Comment by pstorch** [comment]
Now I'm on latest master commit including "tri-state buttons" and I can't reproduce either.
So let's close here.

**Comment by S-Bartfast** [comment]
While working on #6783 (Calculator crash on a waypoint with calculated coordinates) I discovered that making all the buttons in a section blank leads to exactly this error.  Is it possable that in you frenzied clicking you'd managed to blank out all longitude the decimal point buttons?

As in attempting to set the latitude buttons to something like:
>`[W][1][2][2]°[0][5].[ ][ ][ ]`

**Comment by pstorch** [comment]
Ah, even in slow motion (had to look up what "frenzied" means :wink: ) it is possible to cause the crash when blanking out all decimal point buttons.

**Comment by Matze2** [comment]
Right. It crashes as soon as you blank any group. Also DDD or MM.

**Comment by S-Bartfast** [comment]
Alright, fix is in:
![image](https://user-images.githubusercontent.com/6573522/31769071-9008870a-b519-11e7-9b9d-20e626b8d951.png)
