### ISSUE TITLE
Add own waypoint fails when geocache has already >100 waypoints defined

### ISSUE THREAD

**Issue by pstorch** [cgeo/cgeo#6784]
From german geocaching forum:
https://geoclub.de/forum/viewtopic.php?f=155&t=67870&start=700#p1276867

- open https://coord.info/GC6HH0B 
- goto waypoints
- add an own wapoint
- c:geo crashes

Maybe related to #6243 

I could reproduce the bug, but couldn't yet look into the logs what happens.

**Comment by pstorch** [comment]
Looks like we don't support more than 100 waypoints:

```
Caused by: java.lang.IllegalStateException: too many waypoints, unable to assign unique prefix
  at cgeo.geocaching.models.Geocache.assignUniquePrefix(Geocache.java:1409)
  at cgeo.geocaching.models.Geocache.addOrChangeWaypoint(Geocache.java:1366)
  at cgeo.geocaching.EditWaypointActivity$1SaveWptTask.doInBackground(EditWaypointActivity.java:659)
  at cgeo.geocaching.EditWaypointActivity$1SaveWptTask.doInBackground(EditWaypointActivity.java:637)
  at android.os.AsyncTask$2.call(AsyncTask.java:305)
  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
  at java.lang.Thread.run(Thread.java:761) 
```

**Comment by pstorch** [comment]
Here we only test 2 digit prefix `17` - `99`:
https://github.com/cgeo/cgeo/blob/30e87fb5bd60a5f6a9421f2bb9daa14bffca3cb2/main/src/cgeo/geocaching/models/Geocache.java#L1390-L1394

But this example Geocache and http://coord.info/GC6TT3C, too have also characters as prefix.
So I guess we could use `0-9A-Z` and iterate from `17` to `ZZ`.
