### ISSUE TITLE
Crash on starting WP Calc

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#6816]
##### Detailed steps causing the problem:
- Saved GC4F9N0 in c:geo
- Open waypoint tab
- Open empty final WP
- Click coordinates and select "Calculate coordinates"

##### Actual behavior after performing these steps:
Crash:
```
11-01 15:30:54.452  5889  5889 W cgeo    : [main] UncaughtException

11-01 15:30:54.452  5889  5889 W cgeo    : java.lang.NullPointerException: Attempt to read from field 'cgeo.geocaching.settings.Settings$CoordInputFormatEnum cgeo.geocaching.models.CalcState.format' on a null object reference

11-01 15:30:54.452  5889  5889 W cgeo    : 	at cgeo.geocaching.models.CalcState.<init>(CalcState.java:62)

11-01 15:30:54.452  5889  5889 W cgeo    : 	at cgeo.geocaching.EditWaypointActivity.fetchCalculatorState(EditWaypointActivity.java:476)

11-01 15:30:54.452  5889  5889 W cgeo    : 	at cgeo.geocaching.ui.dialog.CoordinatesInputDialog$CalculateListener.onClick(CoordinatesInputDialog.java:578)

11-01 15:30:54.452  5889  5889 W cgeo    : 	at android.view.View.performClick(View.java:6213)

11-01 15:30:54.452  5889  5889 W cgeo    : 	at android.widget.TextView.performClick(TextView.java:11074)

11-01 15:30:54.452  5889  5889 W cgeo    : 	at android.view.View$PerformClick.run(View.java:23645)

11-01 15:30:54.452  5889  5889 W cgeo    : 	at android.os.Handler.handleCallback(Handler.java:751)

11-01 15:30:54.452  5889  5889 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:95)

11-01 15:30:54.452  5889  5889 W cgeo    : 	at android.os.Looper.loop(Looper.java:154)

11-01 15:30:54.452  5889  5889 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:6692)

11-01 15:30:54.452  5889  5889 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)

11-01 15:30:54.452  5889  5889 W cgeo    : 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)

11-01 15:30:54.452  5889  5889 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

11-01 15:30:54.453  5889  5889 E AndroidRuntime: Process: cgeo.geocaching, PID: 5889

11-01 15:30:54.453  5889  5889 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'cgeo.geocaching.settings.Settings$CoordInputFormatEnum cgeo.geocaching.models.CalcState.format' on a null object reference

11-01 15:30:54.453  5889  5889 E AndroidRuntime: 	at cgeo.geocaching.models.CalcState.<init>(CalcState.java:62)

11-01 15:30:54.453  5889  5889 E AndroidRuntime: 	at cgeo.geocaching.EditWaypointActivity.fetchCalculatorState(EditWaypointActivity.java:476)

11-01 15:30:54.453  5889  5889 E AndroidRuntime: 	at cgeo.geocaching.ui.dialog.CoordinatesInputDialog$CalculateListener.onClick(CoordinatesInputDialog.java:578)

11-01 15:30:54.456  4970  7854 W ActivityManager:   Force finishing activity cgeo.geocaching/.EditWaypointActivity_
```

##### Expected behavior after performing these steps:
WP Calc should open

##### Version of c:geo used:
2017.11.01-RC (the planned beta version freshly build from `release` after `master` has been merged

##### Is the problem reproducible for you?
At least not reproducible on another device (but this is running 2017.10.28-NB-62c16a3) with the same cache

##### System information:
Samsung Galaxy S7
Android 7

##### Other comments and remarks:
Could there be any problem associated with the fact, that I restored a backup done with 2017.10.29-NB after freshly installing the 2017.11.01-RC version....should be on the same DB version, shouldn't it.
The mentioned cache was also only downloaded later while already running 2017.11.01-RC

**Comment by Lineflyer** [comment]
Addon:
Seems to happen on every stored cache. I can simply not open the WP Calc....

**Comment by Lineflyer** [comment]
Addon:
I just tested on a device where I followed the normal upgrade path:
2017.10.23 (current market version) -> 2017.11.01-RC

Also there I am unable to start the WP calc.

**Comment by pstorch** [comment]
That's my fault. I'll fix it this evening.
See: https://github.com/cgeo/cgeo/pull/6804#pullrequestreview-73445194

**Comment by pstorch** [comment]
Sorry, this was a last minute change I didn't carefully test.

**Comment by Lineflyer** [comment]
Thanks for the fast fix. Confirmed working now in 2017.11.01-RC2 (just built some hours ago).
