### ISSUE TITLE
App crashes on pause with calculator

### ISSUE THREAD

**Issue by SammysHP** [cgeo/cgeo#6904]
- open calculator
- press app switch button
- c:geo crashes

```
--- System information ---
Device: Redmi Note 4 (lineage_mido, Xiaomi)
Android version: 7.1.2
Android build: lineage_mido-userdebug 7.1.2 NJH47F ce829446e0
c:geo version: 2018.01.07-NB-5367dce
Google Play services: disabled - 11.9.51 (448-177350961)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: true
Map strategy: fast
HW acceleration: enabled (default state)
System language: de_DE
System date format: dd.MM.yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (12,6 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (12,6 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (12,6 GB free) external non-removable
Database: /data/user/0/cgeo.geocaching/databases/data (260,0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Anmeldung OK) / PREMIUM
   opencaching.de: Logged in (Anmeldung OK)
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment]
Confirmed.

**Comment by pstorch** [comment]
Here is the Stacktrace for this issue:

```java
01-07 22:03:21.217 2051-2051/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
   Process: cgeo.geocaching, PID: 2051
   java.lang.IllegalStateException: Failure saving state: CoordinatesCalculateDialog{a7ad8de #1 wpcalcdialog} has target not in fragment manager: CoordinatesInputDialog{e162abf}
   at android.support.v4.app.FragmentManagerImpl.saveAllState(FragmentManager.java:1839)
   at android.support.v4.app.FragmentController.saveAllState(FragmentController.java:125)
   at android.support.v4.app.FragmentActivity.onSaveInstanceState(FragmentActivity.java:523)
   at cgeo.geocaching.EditWaypointActivity.onSaveInstanceState(EditWaypointActivity.java:492)
   at cgeo.geocaching.EditWaypointActivity_.onSaveInstanceState(EditWaypointActivity_.java:125)
   at android.app.Activity.performSaveInstanceState(Activity.java:1415)
   at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1301)
   at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4578)
   at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3893)
   at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3952)
   at android.app.ActivityThread.-wrap25(ActivityThread.java)
   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1530)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:154)
   at android.app.ActivityThread.main(ActivityThread.java:6186)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
```

**Comment by pstorch** [comment]
I'm looking into it, not sure, if I understand the problem yet.
