### ISSUE TITLE
Crash after deleting GPX file using 'import' list.

### ISSUE THREAD

**Issue by alan666notb** [cgeo/cgeo#6912]
CGEO consistantly crashes after deleting a GPX file using the 'import' list.

##### Detailed steps causing the problem:
- Open a stored list
- Goto  Import/Import GPS (A list of files is shown)
- Long-press on one of the files (Pop-up: "Do you want to delete xxxx.GPX?"
- Choose 'OK'
- Long-press on another file (I think files have to be in the same folder)

##### Actual behavior after performing these steps:
CGEO Stops

##### Expected behavior after performing these steps:
You should be able to delete a series of files.

##### Is the problem reproducible for you?
Yes

##### System information:
--- System information ---
Device: E6683 (E6683, Sony)
Android version: 7.1.1
Android build: 32.4.A.0.160
c:geo version: 2018.01.14-RC
Google Play services: enabled - 11.9.51 (448-177350961)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide own/found: false
Map strategy: auto
HW acceleration: enabled (default state)
System language: en_GB
System date format: dd/MM/y
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (10.6 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (10.6 GB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (10.6 GB free) external non-removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (25.0 MB) on user storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd MMM yy
Installed c:geo plugins:  none
--- End of system information ---
```

**Comment by Lineflyer** [comment]
This could(!) be a matching strack trace (retrieved from Google Play):
```
java.lang.IndexOutOfBoundsException: 
   at java.util.ArrayList.get (ArrayList.java:411)
   at cgeo.geocaching.files.GPXListAdapter$2.onLongClick (GPXListAdapter.java:61)
   at android.view.View.performLongClickInternal (View.java:6290)
   at android.view.View.performLongClick (View.java:6248)
   at android.view.View.performLongClick (View.java:6266)
   at android.view.View$CheckForLongPress.run (View.java:23614)
   at android.os.Handler.handleCallback (Handler.java:751)
   at android.os.Handler.dispatchMessage (Handler.java:95)
   at android.os.Looper.loop (Looper.java:154)
   at android.app.ActivityThread.main (ActivityThread.java:6692)
   at java.lang.reflect.Method.invoke (Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1468)
   at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1358)
```

**Comment by alan666notb** [comment]
just a side question: How does that stack-trace get onto google play, and can anyone see it?

**Comment by SammysHP** [comment]
Uploaded by Google crash reporter and can be seen only by core developers.

**Comment by UniQP** [comment]
I could reproduce the crash. Adapted steps to reproduce:
1. Export two lists to GPX files
2. In the list menu select Import → Import GPX (A list of files is shown)
3. Long-press on **the first** file (Pop-up: "Do you want to delete xxxx.GPX?")
4. Choose 'OK'
5. Long-press on **the last** file

```
java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
  at java.util.ArrayList.get(ArrayList.java:411)
  at cgeo.geocaching.files.GPXListAdapter$2.onLongClick(GPXListAdapter.java:61)
  at android.view.View.performLongClickInternal(View.java:5714)
  at android.view.View.performLongClick(View.java:5672)
  at android.view.View.performLongClick(View.java:5690)
  at android.view.View$CheckForLongPress.run(View.java:22398)
  at android.os.Handler.handleCallback(Handler.java:751)
  at android.os.Handler.dispatchMessage(Handler.java:95)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6119)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

It seems that we access the file list with the old index of the file.
