### ISSUE TITLE
Crash on map

### ISSUE THREAD

**Issue by Bananeweizen** [cgeo/cgeo#7043]
Be aware this is from a binary of 2018-05-08 (3 weeks ago). However, I've not immediately seen a related commit after that in the history.
```
java.lang.IllegalArgumentException: invalid pixelX coordinate 768: -156.0
	at org.mapsforge.core.util.MercatorProjection.pixelXToLongitude(MercatorProjection.java:355)
	at org.mapsforge.core.util.MercatorProjection.fromPixels(MercatorProjection.java:92)
	at cgeo.geocaching.maps.mapsforge.v6.MfMapView.getLongitudeSpan(MfMapView.java:72)
	at cgeo.geocaching.maps.mapsforge.v6.MfMapView.getViewport(MfMapView.java:38)
	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.getVisibleGeocodes(AbstractCachesOverlay.java:59)
	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.getVisibleGeocodes(CachesBundle.java:178)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.onPrepareOptionsMenu(NewMap.java:272)
```
Same exception is available for Y coordinates.

**Comment by Lineflyer** [comment]
Regarding the severity:
Does this result in a crash or malfunction obvious to the user or only happening in the background?
How often did this occur?

**Comment by Lineflyer** [comment]
Closing due to lack of feedback and changes in the code since then. 
Feel free to reopen.
