### ISSUE TITLE
c:geo keeps crashing on greek locale

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7116]
##### Detailed steps causing the problem:
- Switch your phone language to Greek
- Start c:geo 
- Open live map or saved caches

##### Actual behavior after performing these steps:
Crash

##### Expected behavior after performing these steps:
Working normal

##### Version of c:geo used:
2018.08.14 and 2018.08.14-NB1

##### Is the problem reproducible for you?
Reported on support mail and reproduced on my phone

##### Other comments and remarks:
What I see in the log (not sure if this is the cause):
```
08-15 11:07:47.367 28611 28611 W cgeo    : [main] UncaughtException
08-15 11:07:47.367 28611 28611 W cgeo    : java.util.UnknownFormatConversionException: Conversion = '€'
08-15 11:07:47.367 28611 28611 W cgeo    : 	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2781)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2811)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2624)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at java.util.Formatter.parse(Formatter.java:2557)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at java.util.Formatter.format(Formatter.java:2504)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at java.util.Formatter.format(Formatter.java:2458)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at java.lang.String.format(String.java:2814)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at android.content.res.Resources.getQuantityString(Resources.java:505)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.NewMap.calculateSubtitle(NewMap.java:1031)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.NewMap.setSubtitle(NewMap.java:1004)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.NewMap.access$600(NewMap.java:108)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.NewMap$DisplayHandler.handleMessage(NewMap.java:966)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:105)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at android.os.Looper.loop(Looper.java:164)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:6944)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
08-15 11:07:47.367 28611 28611 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by UniQP** [comment]
Looks like a synchronization problem with Crowdin. 2bcdd2f8ec9c60ada439f88b42628b4063e8710c reintroduced the problem after 582dae00bc4104dd90365eb9a6c59d1e4c049b24 fixed it.

**Comment by Lineflyer** [comment]
Could it be the translation of export_persnotes_upload_success [other] ?

**Comment by Lineflyer** [comment]
@UniQP Yes, same problem other string.
I corrected it on Crowdin and will correct it here additionally.

**Comment by Lineflyer** [comment]
I informed the greek translator to take special care in future.
I am wondering that those wrong specifiers still compile but only produce crashes on runtime. Any chance we can detect while compiling?
