### ISSUE TITLE
Invalid argument exception in Live Map

### ISSUE THREAD

**Issue by UniQP** [cgeo/cgeo#7337]
With 883235a11811b097f2a18306cb161bac264c543b, I see the following two exceptions when opening the Live Map with the emulator (API 27):

```
W/cgeo: [RxNewThreadScheduler-3] Exception when calculating latitude span
    java.lang.IllegalArgumentException: invalid pixelY coordinate 256: -664.0
        at org.mapsforge.core.util.MercatorProjection.pixelYToLatitude(MercatorProjection.java:409)
        at org.mapsforge.core.util.MercatorProjection.fromPixels(MercatorProjection.java:91)
        at cgeo.geocaching.maps.mapsforge.v6.MfMapView.getLatitudeSpan(MfMapView.java:51)
        at cgeo.geocaching.maps.mapsforge.v6.MfMapView.getViewport(MfMapView.java:38)
        at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.getViewport(CachesBundle.java:221)
        at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.getViewport(AbstractCachesOverlay.java:232)
        at cgeo.geocaching.maps.mapsforge.v6.caches.StoredCachesOverlay$LoadTimerAction.run(StoredCachesOverlay.java:54)
        at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:533)
        at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:480)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

```
W/cgeo: [RxNewThreadScheduler-3] Exception when calculating longitude span
    java.lang.IllegalArgumentException: invalid pixelX coordinate 256: -412.0
        at org.mapsforge.core.util.MercatorProjection.pixelXToLongitude(MercatorProjection.java:355)
        at org.mapsforge.core.util.MercatorProjection.fromPixels(MercatorProjection.java:92)
        at cgeo.geocaching.maps.mapsforge.v6.MfMapView.getLongitudeSpan(MfMapView.java:72)
        at cgeo.geocaching.maps.mapsforge.v6.MfMapView.getViewport(MfMapView.java:38)
        at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.getViewport(CachesBundle.java:221)
        at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.getViewport(AbstractCachesOverlay.java:232)
        at cgeo.geocaching.maps.mapsforge.v6.caches.StoredCachesOverlay$LoadTimerAction.run(StoredCachesOverlay.java:54)
        at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:533)
        at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:480)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

Looks related to #5903.

**Comment by Lineflyer** [comment]
No related crash reports on Google Play. Maybe fixed implicitly when fixing the related #5903
