### ISSUE TITLE
Crash when adding new photo to log

### ISSUE THREAD

**Issue by samueltardieu** [cgeo/cgeo#7341]
When logging a cache, add a new picture. Instead of opening the camera application, cgeo crashes.

Reproduced with nightly on Android 9 and with stable on Android 8.

**Comment by Lineflyer** [comment]
Reproducible for me on Android 8. I think I missed testing this, as I mostly attach existing pictures (which works).
Thanks for reporting!

**Comment by samueltardieu** [comment]
@UniQP Looks like this was merged two days ago, however the current nightly still exhibits a bogus behaviour: the first click on "New" (supposedly, "Nouveau" in French) just does nothing at all. Reattaching an image, selecting "New" again, leads to an application crash. Both attempts log the same exception:

```
03-07 18:52:16.597 25364 25364 W cgeo    : [main] UncaughtException
03-07 18:52:16.597 25364 25364 W cgeo    : android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/cgeo/IMG_20190307_185216.jpg exposed beyond app through ClipData.Item.getUri()
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.os.StrictMode.onFileUriExposed(StrictMode.java:1978)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.net.Uri.checkFileUriExposed(Uri.java:2371)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.content.ClipData.prepareToLeaveProcess(ClipData.java:963)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.content.Intent.prepareToLeaveProcess(Intent.java:10228)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.content.Intent.prepareToLeaveProcess(Intent.java:10213)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1854)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.app.Activity.startActivityForResult(Activity.java:4599)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.app.Activity.startActivityForResult(Activity.java:4557)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:856)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at cgeo.geocaching.ImageSelectActivity.selectImageFromCamera(ImageSelectActivity.java:237)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at cgeo.geocaching.ImageSelectActivity.access$000(ImageSelectActivity.java:40)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at cgeo.geocaching.ImageSelectActivity$1.onClick(ImageSelectActivity.java:99)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.view.View.performClick(View.java:6669)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.view.View.performClickInternal(View.java:6638)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.view.View.access$3100(View.java:789)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.view.View$PerformClick.run(View.java:26145)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.os.Handler.handleCallback(Handler.java:873)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.os.Looper.loop(Looper.java:193)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at android.app.ActivityThread.main(ActivityThread.java:6863)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at java.lang.reflect.Method.invoke(Native Method)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
03-07 18:52:16.597 25364 25364 W cgeo    : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

I'm reopening the issue, please reclose it if for any reason I was mistaken and this was not supposed to be fixed on nightly.

Cc/ @moving-bits

**Comment by UniQP** [comment]
I was merged to release. I just merged it back to master, so it's not contained in the current nightly.

**Comment by samueltardieu** [comment]
My bad, thanks!
