### ISSUE TITLE
UnsupportedOperationException on Android 4.3 (Google Pre Launch Report)

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#7473]
On publishing a new (beta) release Google Play automatically runs robo tests on some device.
This pre launch report now came back with a crash report for an Android 4.3 device with the following stacktrace for beta version 2019.04.08-RC:

```
FATAL EXCEPTION: ControllerMessenger
android.content.res.Resources$NotFoundException: File res/drawable/border_straight.xml from drawable resource ID #0x7f0700da. If the resource you are trying to use is a vector resource, you may be referencing it in an unsupported way. See AppCompatDelegate.setCompatVectorFromResourcesEnabled() for more info.
	at android.content.res.Resources.loadDrawable(Resources.java:2974)
	at android.content.res.Resources.getDrawable(Resources.java:1558)
	at com.android.internal.policy.impl.PhoneWindow.generateLayout(PhoneWindow.java:3573)
	at com.android.internal.policy.impl.PhoneWindow.installDecor(PhoneWindow.java:3616)
	at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:357)
	at com.android.internal.app.AlertController.installContent(AlertController.java:259)
	at android.app.AlertDialog.onCreate(AlertDialog.java:337)
	at android.app.ProgressDialog.onCreate(ProgressDialog.java:198)
	at android.app.Dialog.dispatchOnCreate(Dialog.java:362)
	at android.app.Dialog.show(Dialog.java:266)
	at cgeo.geocaching.activity.Progress.show(Progress.java:46)
	at cgeo.geocaching.CacheListActivity.importWeb(CacheListActivity.java:1431)
	at cgeo.geocaching.CacheListActivity.onOptionsItemSelected(CacheListActivity.java:894)
	at android.app.Activity.onMenuItemSelected(Activity.java:2640)
	at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:406)
	at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
	at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:103)
	at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:667)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:810)
	at android.support.v7.view.menu.SubMenuBuilder.dispatchMenuItemSelected(SubMenuBuilder.java:85)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:957)
	at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
	at android.widget.AdapterView.performItemClick(AdapterView.java:301)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1510)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3339)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:19)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:166)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:158)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:138)
	at androidx.test.espresso.action.Tap$1.a(Tap.java:6)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:22)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:9)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:79)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:96)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:3)
	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:5419)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.UnsupportedOperationException: Can't convert to color: type=0x2
	at android.content.res.TypedArray.getColor(TypedArray.java:327)
	at android.graphics.drawable.GradientDrawable.inflate(GradientDrawable.java:967)
```

**Comment by moving-bits** [comment]
Can reproduce on Android 4.2.2 (API 17) and 4.4 (API 19) devices, API 22 and API 26 work. Don't know the reason yet. Source is #7440

**Comment by moving-bits** [comment]
Looks like I cannot use a parametrized vector button styling with those old Android versions. I can distinguish between Android version, so use "full featured" dialog border for Android API 22+, and a reduced one for older version with a specific color instead of a parametrized one.

For that I could either use black, white (or any other color) or transparent for the part between the dialog window itself and it's border. Which one should I use? (this is for API level < 22 only)

**Comment by Lineflyer** [comment]
I can also reproduce now on my 4.1.2 test device.

I am not sure what you mean with "between dialog window itself and border" and how thick this area is. If its small I would give it the same color as the border (AFAIK white) else as the background (AFAIK black).

**Comment by Lineflyer** [comment]
Whatever you think looks nicer :)
