### ISSUE TITLE
cannot install from F-Droid 

### ISSUE THREAD

**Issue by muelli** [cgeo/cgeo#7516]
##### Detailed steps causing the problem:
- try to install cgeo via fdroid with `fdroid.cgeo.org` repository

##### Actual behavior after performing these steps:
it fails:

```
04-17 11:38:09.275 19980  8004 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/org.fdroid.fdroid/cache/apks/fdroid.cgeo.org--1/cgeo-release-2019.04.16.apk Binary XML file line #46
```

##### Expected behavior after performing these steps:

it installs fine

##### Version of c:geo used:

2019-04-16

##### Is the problem reproducible for you?
Yes

##### Other comments and remarks:
e.g. Reference to other issues, projects, sources, etc.

**Comment by Lineflyer** [comment]
@kumy Could it be caused by the latest changes to metadata?

**Comment by kumy** [comment]
Maybe I'll check at home

**Comment by kumy** [comment]
@Lineflyer may you assign this to me please.

**Comment by kumy** [comment]
I have successfully updated my app using Nightly channel :/ I'll check also with Release channel

**Comment by kumy** [comment]
Release is not working

**Comment by kumy** [comment]
Hum it was failing because I had to uninstall nightly first. So i m not able to reproduce.

**Comment by kumy** [comment]
I definitely cannot reproduce. There is no `manifest` string in all the repo metadata files. Seems to be a problem when downloading.

FTR: The file checksum on server is:
```
bf31f3ba1531e3b857f418c331df1a31  ./repos/mainline/repo/cgeo-release-2019.04.16.apk
```

@muelli Could it be possible to send us the downloaded file `/data/user/0/org.fdroid.fdroid/cache/apks/fdroid.cgeo.org--1/cgeo-release-2019.04.16.apk` from your phone?

**Comment by muelli** [comment]
hrm. I can't access that file, it seems.  My adb shell does not have enough permissions. Just like the file manager on the device :-/

But it's reproducible on my end.

```
04-18 21:28:20.835 22927 23539 W PackageParser: Unknown element under <manifest>: meta-data at /data/user/0/org.fdroid.fdroid/cache/apks/fdroid.cgeo.org--1/cgeo-release-2019.04.16.apk Binary XML file line #46
04-18 21:28:20.842  2734   750 I ActivityManager: START u0 {act=org.fdroid.fdroid.installer.DefaultInstaller.action.INSTALL_PACKAGE dat=content://org.fdroid.fdroid.installer.ApkFileProvider/files/cgeo-2019.04.16.apk cmp=org.fdroid.fdroid/.installer.DefaultInstallerActivity (has extras)} from uid 10002 on display 0
04-18 21:28:20.842  2734   750 W ActivityManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { act=org.fdroid.fdroid.installer.DefaultInstaller.action.INSTALL_PACKAGE dat=content://org.fdroid.fdroid.installer.ApkFileProvider/files/cgeo-2019.04.16.apk cmp=org.fdroid.fdroid/.installer.DefaultInstallerActivity (has extras) }
04-18 21:28:20.851  2734   750 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
04-18 21:28:20.859  2734  2734 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:877 com.android.server.notification.BQNotificationManagerService.enableBatteryChargingLed:128 com.android.server.notification.BQNotificationManagerService.updateLightsLocked:165 com.android.server.notification.NotificationManagerService$8.run:3574 android.os.Handler.handleCallback:751 
04-18 21:28:20.859  2734  2734 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:877 com.android.server.notification.NotificationManagerService.enableBatteryChargingLed:3736 com.android.server.notification.NotificationManagerService.-wrap21:-1 com.android.server.notification.NotificationManagerService$8.run:3575 android.os.Handler.handleCallback:751 
04-18 21:28:20.914  2734 14845 I ActivityManager: START u0 {act=android.intent.action.INSTALL_PACKAGE dat=content://org.fdroid.fdroid.installer.ApkFileProvider/files/cgeo-2019.04.16.apk flg=0x1 cmp=com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity (has extras)} from uid 10002 on display 0
04-18 21:28:20.920  2734 14845 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
04-18 21:28:21.116  2734  2754 I ActivityManager: Displayed com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity: +176ms (total +221ms)
04-18 21:28:21.122 23050 23050 W PackageParser: Unknown element under <manifest>: meta-data at /data/user_de/0/com.google.android.packageinstaller/cache/package1591014573.apk Binary XML file line #46


04-18 21:28:24.565  2734 15753 I ActivityManager: START u0 {dat=file:///data/user_de/0/com.google.android.packageinstaller/cache/package1591014573.apk flg=0x2000000 cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallAppProgress (has extras)} from uid 10017 on display 0

04-18 21:28:24.629 23050 23050 W InstallAppProgress: Replacing package:cgeo.geocaching
04-18 21:28:24.744  2734  4171 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
04-18 21:28:24.783 23050 23068 D OpenGLRenderer: endAllActiveAnimators on 0x91b7eb00 (RippleDrawable) with handle 0x903cdaf0
04-18 21:28:24.824  2734  3548 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
04-18 21:28:24.876 22927 22927 E AppDetailsActivity: install aborted with errorMessage: Failed to install due to an unknown error

```

What's the URL of the apk? I can download that and install it.

**Comment by kumy** [comment]
> Failed to install due to an unknown error

This is the [same error](https://github.com/cgeo/cgeo/issues/7516#issuecomment-484041341) I got before uninstalled cgeo nightly. @muelli do you have another version already installed?

**Comment by muelli** [comment]
no.
I've only ever used f-droid.
And it's the first time I'm seeing this. On any app I install through f-droid.

**Comment by kumy** [comment]
> What's the URL of the apk?

You may find current release at https://fdroid.cgeo.org/cgeo-release-2019.04.16.apk and older under `archive` like https://fdroid.cgeo.org/archive/cgeo-release-2018.10.13.apk

**Comment by kumy** [comment]
> I've only ever used f-droid.

Even a NB or RC version downloaded directly from https://cgeo.org ?

**Comment by muelli** [comment]
> Even a NB or RC version downloaded directly from https://cgeo.org ?

nope. I have the app installed for relatively long time. I may have downloaded an APK directly in the distant past, but I've upgraded through F-Droid for quite a while, i.e. two years.



> You may find current release at https://fdroid.cgeo.org/cgeo-release-2019.04.16.apk

cool, thanks. One last question before I try that file: Does that use the same signing key as the F-Droid version I have installed (which is 2019-04-04)? IoW: Does that get me into trouble to keep using f-droid for the app?

**Comment by kumy** [comment]
Really strange. @Lineflyer were you able to reproduce?

> Does that use the same signing key as the F-Droid version I have installed

This are **the** links f-droid will use when is it get download url via indexes. Those apk are exactly the as same the one uploaded to Play store.

**Comment by kumy** [comment]
Here is how I'm able to reproduce https://we.tl/t-0HEnsTHvIg but it doesn't seems to be your case

**Comment by kumy** [comment]
In my case I can't downgrade at all even in the same release branch

**Comment by muelli** [comment]
Hrm. I've tried to install that APK directly, without success:

```
04-18 22:12:29.620  2734  2754 I ActivityManager: Displayed com.google.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity: +247ms
04-18 22:12:29.652 25338 25338 W PackageParser: Unknown element under <manifest>: meta-data at /data/user_de/0/com.google.android.packageinstaller/cache/package85139712.apk Binary XML file line #46
04-18 22:12:29.997  2734  2747 D ActivityTrigger: ActivityTrigger activityStopTrigger 
04-18 22:12:30.558 24347 24347 I ServiceManager: Waiting for service AtCmdFwd...
04-18 22:12:31.080  2734  2743 I art     : Background partial concurrent mark sweep GC freed 77520(3MB) AllocSpace objects, 0(0B) LOS objects, 20% free, 63MB/79MB, paused 1.446ms total 108.751ms
04-18 22:12:31.565 24347 24347 I ServiceManager: Waiting for service AtCmdFwd...
04-18 22:12:31.635   605 29077 I AudioPolicyManagerCustom: FLAG None hence request for a primary output
04-18 22:12:31.635   605  6248 I AudioPolicyManagerCustom: FLAG None hence request for a primary output
04-18 22:12:31.636  2734  4167 I ActivityManager: START u0 {dat=file:///data/user_de/0/com.google.android.packageinstaller/cache/package85139712.apk cmp=com.google.android.packageinstaller/com.android.packageinstaller.InstallAppProgress (has extras)} from uid 10017 on display 0
04-18 22:12:31.645  2734  4167 D ActivityTrigger: ActivityTrigger activityPauseTrigger 
04-18 22:12:31.695 25338 25338 W InstallAppProgress: Replacing package:cgeo.geocaching
04-18 22:12:31.759 25338 25338 D InstallAppProgress: Installation error code: 1
04-18 22:12:31.814  2734  2754 I ActivityManager: Displayed com.google.android.packageinstaller/com.android.packageinstaller.InstallAppProgress: +154ms
04-18 22:12:31.835 25338 25352 D OpenGLRenderer: endAllActiveAnimators on 0x92447280 (RippleDrawable) with handle 0x9177dca0
```
I'm pretty confident that I have tried to install this file: `6fb76dd1096bf858ed99e5e890aad32e0128f064  /tmp/cgeo-release-2019.04.16.apk`

It fails pretty quickly. Note that the message in the log about the manifest appears as soon as I press "the apk file", i.e. before I press the "install" button on the package installer.

![image](https://user-images.githubusercontent.com/322807/56388567-93893480-6227-11e9-9f52-90586f0ac612.png)

I'd record a screencast, but I don't know how to.

**Comment by kumy** [comment]
> I'd record a screencast, but I don't know how to.

I've used `ScreenCam` from f-droid ;)

**Comment by muelli** [comment]
okay. it works now. sorry for the noise.
A reboot made it work.
I noticed that I couldn't install ScreenCam. Which is funny, because I've updated several apps through f-droid and c:geo was not working.
The android log also made me think that there's a problem with the APK file. It seems, however, that it's been a local problem.
Again, sorry for having wasted your time.
Now I can report the crashers that I'm seeing ;-)

Is that coming from c:geo and worth filing a bug or has some other app crashed at the same time as c:geo?

```
https://www.overleaf.com?r=8901425e&rm=d&rs=b


 , Sven
3leet



04-18 22:27:02.980  9722  9722 I DynamiteModule: Considering local module com.google.android.gms.crash:0 and remote module com.google.android.gms.crash:215
04-18 22:27:02.980  9722  9722 I DynamiteModule: Selected remote version of com.google.android.gms.crash, version >= 215
04-18 22:27:02.984  9722  9722 W System  : ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/0000008d/DynamiteModulesC.apk
04-18 22:27:02.985  9722  9722 W ChimeraFileApk: Failed to validate PathClassLoader for /data/user_de/0/com.google.android.gms/app_chimera/m/0000008d/DynamiteModulesC.apk: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.chimera.DynamiteModuleInitializer" on path: DexPathList[[],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/0000008d/DynamiteModulesC.apk!/lib/armeabi-v7a, /data/user_de/0/com.google.android.gms/app_chimera/m/0000008d/DynamiteModulesC.apk!/lib/armeabi, /system/lib, /vendor/lib]]
04-18 22:27:02.986  9722  9722 W System  : ClassLoader referenced unknown path: /data/user_de/0/com.google.android.gms/app_chimera/m/0000008d/DynamiteModulesC.apk
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: Failed to validate DexClassLoader.
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.chimera.DynamiteModuleInitializer" on path: DexPathList[[],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/0000008d/DynamiteModulesC.apk!/lib/armeabi-v7a, /data/user_de/0/com.google.android.gms/app_chimera/m/0000008d/DynamiteModulesC.apk!/lib/armeabi, /system/lib, /vendor/lib]]
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at dyp.loadClass(:com.google.android.gms@16089018@16.0.89 (040308-239467275):3)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at dww.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):22)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at dzu.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):88)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at dzu.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):14)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at dzu.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):137)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at dzu.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):133)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at vjv.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):19)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.android.gms.chimera.container.DynamiteLoaderImpl.createModuleContextNoCrashUtils(:com.google.android.gms@16089018@16.0.89 (040308-239467275):15)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.android.gms.chimera.container.DynamiteLoaderImpl.createModuleContext(:com.google.android.gms@16089018@16.0.89 (040308-239467275):3)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at vjq.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):33)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at crc.onTransact(:com.google.android.gms@16089018@16.0.89 (040308-239467275):3)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at android.os.Binder.transact(Binder.java:499)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.android.gms.dynamite.zza$zza$zza.zza(Unknown Source)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.android.gms.dynamite.DynamiteModule.zzc(Unknown Source)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.android.gms.dynamite.DynamiteModule$1.zza(Unknown Source)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.android.gms.internal.zzbks.zzao(Unknown Source)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.firebase.crash.FirebaseCrash.<init>(Unknown Source)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.firebase.crash.FirebaseCrash.getInstance(Unknown Source)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.firebase.FirebaseApp.zza(Unknown Source)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at android.app.ActivityThread.installProvider(ActivityThread.java:5853)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5445)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5384)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at android.os.Looper.loop(Looper.java:154)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-18 22:27:02.987  9722  9722 E ChimeraFileApk: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: Failed to load code for module FileApk(/data/user_de/0/com.google.android.gms/app_chimera/m/0000008d/DynamiteModulesC.apk)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: dzw: Can't load code for DynamiteModulesC.apk
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at dww.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):25)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at dzu.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):88)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at dzu.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):14)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at dzu.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):137)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at dzu.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):133)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at vjv.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):19)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.android.gms.chimera.container.DynamiteLoaderImpl.createModuleContextNoCrashUtils(:com.google.android.gms@16089018@16.0.89 (040308-239467275):15)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.android.gms.chimera.container.DynamiteLoaderImpl.createModuleContext(:com.google.android.gms@16089018@16.0.89 (040308-239467275):3)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at vjq.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):33)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at crc.onTransact(:com.google.android.gms@16089018@16.0.89 (040308-239467275):3)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at android.os.Binder.transact(Binder.java:499)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.android.gms.dynamite.zza$zza$zza.zza(Unknown Source)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.android.gms.dynamite.DynamiteModule.zzc(Unknown Source)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.android.gms.dynamite.DynamiteModule$1.zza(Unknown Source)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.android.gms.internal.zzbks.zzao(Unknown Source)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.firebase.crash.FirebaseCrash.<init>(Unknown Source)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.firebase.crash.FirebaseCrash.getInstance(Unknown Source)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.firebase.FirebaseApp.zza(Unknown Source)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at android.app.ActivityThread.installProvider(ActivityThread.java:5853)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5445)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5384)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at android.os.Looper.loop(Looper.java:154)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-18 22:27:02.988  9722  9722 E ChimeraModuleLdr: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
04-18 22:27:02.989  9722  9722 W ChimeraDebugLogger: Singleton logger instance not set.
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: Failed to create module context.
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: dzw: Can't load code for DynamiteModulesC.apk
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at dww.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):25)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at dzu.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):88)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at dzu.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):14)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at dzu.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):137)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at dzu.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):133)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at vjv.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):19)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.android.gms.chimera.container.DynamiteLoaderImpl.createModuleContextNoCrashUtils(:com.google.android.gms@16089018@16.0.89 (040308-239467275):15)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.android.gms.chimera.container.DynamiteLoaderImpl.createModuleContext(:com.google.android.gms@16089018@16.0.89 (040308-239467275):3)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at vjq.a(:com.google.android.gms@16089018@16.0.89 (040308-239467275):33)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at crc.onTransact(:com.google.android.gms@16089018@16.0.89 (040308-239467275):3)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at android.os.Binder.transact(Binder.java:499)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.android.gms.dynamite.zza$zza$zza.zza(Unknown Source)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.android.gms.dynamite.DynamiteModule.zzc(Unknown Source)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.android.gms.dynamite.DynamiteModule$1.zza(Unknown Source)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.android.gms.dynamite.DynamiteModule.zza(Unknown Source)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.android.gms.internal.zzbks.zzao(Unknown Source)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.firebase.crash.FirebaseCrash.<init>(Unknown Source)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.firebase.crash.FirebaseCrash.getInstance(Unknown Source)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.firebase.FirebaseApp.zza(Unknown Source)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.firebase.FirebaseApp.initializeApp(Unknown Source)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1751)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at android.content.ContentProvider.attachInfo(ContentProvider.java:1726)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at android.app.ActivityThread.installProvider(ActivityThread.java:5853)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5445)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5384)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1545)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at android.os.Looper.loop(Looper.java:154)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at java.lang.reflect.Method.invoke(Native Method)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-18 22:27:02.989  9722  9722 E DynamiteLoaderV2Impl: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
04-18 22:27:02.990  9722  9722 W DynamiteModule: Failed to load remote module: Failed to load remote module.
04-18 22:27:02.991  9722  9722 E FirebaseCrash: Failed to initialize crash reporting: com.google.android.gms.dynamite.DynamiteModule$zza: Remote load failed. No local fallback found.
04-18 22:27:02.991  9722  9722 D FirebaseCrash: Cannot register Firebase Analytics listener since Firebase Crash Reporting is not enabled
```
that happened when I opened the live map.
opening c:geo a second time seems to work, though.

**Comment by kumy** [comment]
Argh, however it's better like this…

@Lineflyer is cgeo generally downgradable without uninstalling first?

**Comment by moving-bits** [comment]
@kumy I don't know about all cases, but for sure you cannot downgrade if there's been a database upgrade for c:geo (as we have in current master branch: v76 in master / v75 in release).

**Comment by Lineflyer** [comment]
Technically the database downgrade is the problem as said by @moving-bits .

Google Play (or Android Installer itself??) does not allow installing a version with a lower versio code as the installed one. Not sure if this is Android process in general.
