### ISSUE TITLE
build fails with gradle error ... can't find referenced class ... ActivityCompat21

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7548]
After upgrading Android Studio to current version 3.4 build fails with error message `android.support.v4.app.FragmentActivity: can't find referenced class android.support.v4.app.ActivityCompat21`

In AS 3.3 this has been a warning only (with no apparent consequences), but now build stops:

![image](https://user-images.githubusercontent.com/3754370/56679549-9ff90b80-66c5-11e9-8fc6-9af9b0d0fb4a.png)

(I've done "clean" and "rebuild project")

Besides updating AS there has been no change on my side.
Do we have to adjust gradle settings or is there anything else I need to configure on my side?

**Comment by moving-bits** [comment]
Build can be completed by adding `-dontwarn android.support.v4.**` to `proguard-project.txt`, but I'm unsure about the consequences, so it's better if someone could review this.

**Comment by moving-bits** [comment]
A follow-up error is this one:

```
cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: network--1
    Process: cgeo.geocaching, PID: 4602
    java.lang.AssertionError: impossible
        at java.lang.Enum$1.create(Enum.java:269)
        at java.lang.Enum$1.create(Enum.java:260)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
        at java.lang.Enum.getSharedConstants(Enum.java:286)
        at java.lang.Class.getEnumConstantsShared(Class.java:2291)
        at java.lang.Class.getEnumConstants(Class.java:2279)
        at com.fasterxml.jackson.databind.cfg.MapperConfig.collectFeatureDefaults(MapperConfig.java:99)
        at com.fasterxml.jackson.databind.cfg.MapperConfigBase.<clinit>(MapperConfigBase.java:32)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:565)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:480)
        at cgeo.geocaching.network.Network.<clinit>(Network.java:71)
        at cgeo.geocaching.network.Network.requestJSON(Network.java:496)
        at cgeo.geocaching.network.StatusUpdater$1.run(StatusUpdater.java:99)
        at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:532)
...
```

which (according to `https://stackoverflow.com/questions/20651575/android-release-apk-crash-with-java-lang-assertionerror-impossible-in-java-lang`) can be fixed by adding the following lines to `proguard-project.txt`:

```
# For enumeration classes, see http://proguard.sourceforge.net/manual/examples.html#enumerations
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
```

This seems to work (at least c:geo now fires up again without crashing instantly), but again, I'm unsure about side effects.

**Comment by rsudev** [comment]
I upgraded to AS 3.4 as well some days ago and didn't have any build errors. Did you upgrade gradle/the gradle plugin as well?

**Comment by moving-bits** [comment]
no, I upgraded AS only

**Comment by rsudev** [comment]
Very strange. I just tried with current master...
I didn't get the warning before and don't get an error now.

**Comment by moving-bits** [comment]
Strange, indeed.

I also cannot call the authentification functions for (eg) opencaching.pl, geocaching.su etc. (*) - c:geo fails with fatal exception while inflating a Button layout. Does this work for you?
(Tested with current master.)

(*) activate a yet unused connector like opencaching.pl, tap on "Authorize c:geo" => c:geo crashes with:
```
cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 6115
    java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.connector.oc.OCAuthorizationActivity}: android.view.InflateException: Binary XML file line #43: Binary XML file line #43: Error inflating class Button
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
     Caused by: android.view.InflateException: Binary XML file line #43: Binary XML file line #43: Error inflating class Button
     Caused by: android.view.InflateException: Binary XML file line #43: Error inflating class Button
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.widget.AppCompatBackgroundHelper.onSetBackgroundDrawable$130e17e7()' on a null object reference
        at android.support.v7.widget.AppCompatButton.setBackgroundDrawable(AppCompatButton.java:83)
        at android.view.View.setBackground(View.java:18124)
        at android.view.View.<init>(View.java:4573)
        at android.widget.TextView.<init>(TextView.java:710)
        at android.widget.Button.<init>(Button.java:109)
        at android.widget.Button.<init>(Button.java:105)
        at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:61)
        at android.support.v7.widget.AppCompatButton.<init>(AppCompatButton.java:57)
        at android.support.v7.app.AppCompatDelegateImplV9.onCreateView(AppCompatDelegateImplV9.java:14109)
        at android.support.v4.view.LayoutInflaterCompatHC$FactoryWrapperHC.onCreateView(LayoutInflaterCompatHC.java:47)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at cgeo.geocaching.activity.AbstractActivity.setContentView(AbstractActivity.java:151)
        at cgeo.geocaching.activity.AbstractActivity.onCreate(AbstractActivity.java:125)
        at cgeo.geocaching.activity.OAuthAuthorizationActivity.onCreate(OAuthAuthorizationActivity.java:131)
        at cgeo.geocaching.connector.oc.OCAuthorizationActivity.onCreate(OCAuthorizationActivity.java:42)
        at android.app.Activity.performCreate(Activity.java:6662)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6077)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
```

**Comment by rsudev** [comment]
Just installed a new (release) build on my phone - works

**Comment by UniQP** [comment]
I upgraded and it works fine.

@moving-bits Have you imported your old settings?

**Comment by moving-bits** [comment]
IMHO AS does this automatically during upgrade. (I do not remember doing this explicitly. As last step during upgrade AS asks me to delete the old version specific directory, which I always accept.)

Which settings should I check? (Which could be responsible for such a behaviour? Looks to me like some sort of version clash.)

**Comment by Bananeweizen** [comment]
I'm also not seeing any build errors from the AS 3.4 upgrade (but AS 3.4 is completely broken for me, exceptions on every key stroke). I also cannot remember any warnings in that area in 3.4.

But what exactly are you doing to get that error? Which specific menu or shortcut and which selection? I tend to use _only_ the commands from the gradle tool window, while others may use only the make dropdown, the make toolbar buttons etc.

That being said, have you done a "git reset --hard origin/master" at a point where you should not have any local changes, just to be safe? And do you get the same errors on command line using "gradlew clean runBasicDebug" or similar?

**Comment by rsudev** [comment]
Another area to possibly look at: the build cache (not sure if 'clean' deals with that, my impression when checking some things a while ago was not)

**Comment by moving-bits** [comment]
> Another area to possibly look at: the build cache (not sure if 'clean' deals with that, my impression when checking some things a while ago was not)

Will have a look at it, thanks for pointing me to this. To my understanding the `build` subdirectory can be emptied without negative consequences (besides performance on next build) and will be rebuilt automatically - correct?

**Comment by Bananeweizen** [comment]
"reset hard" modifies both working area and index, so it will reset the current branch to the content of the tracking branch for origin/master. Both uncommitted changes of the working area and unpushed changes of the current branch are lost.
And yes, you can delete the build directory at any time.

Build cache is definitely not deleted by the clean command, that would be counter productive. Since the build cache maps identical inputs to the same already stored output, there is generally no need to ever remove something from build cache (unless someone implemented a gradle task wrongly).

Also to my understanding you can delete the "build" directory at any time.

On the command line I see a similar warning like you (but without affecting the build result in any kind):
```
C:\dev\cgeo\main\build\intermediates\transforms\proguard\basic\debug\0.jar: D8: Type `org.conscrypt.Conscrypt` was not found, it is required for default or static interface methods desugaring of `java.security.Provider okhttp3.internal.platform.ConscryptPlatform.getProvider()`
C:\dev\cgeo\main\build\intermediates\transforms\proguard\basic\debug\0.jar: D8: Type `java.nio.file.Paths` was not found, it is required for default or static interface methods desugaring of `java.nio.file.Path com.fasterxml.jackson.databind.ext.NioPathDeserializer.deserialize(com.fasterxml.jackson.core.JsonParser, com.fasterxml.jackson.databind.DeserializationContext)`
C:\dev\cgeo\main\build\intermediates\transforms\proguard\basic\debug\0.jar: D8: Type `android.support.v4.app.ActivityCompat21` was not found, it is required for default or static interface methods desugaring of `void android.support.v4.app.FragmentActivity.setSupportMediaController(android.support.v4.media.session.MediaControllerCompat)`
```
The last of those 3 looks similar to your first warning, but not identical. Have you eventually disabled D8 as described here? https://android-developers.googleblog.com/2018/04/android-studio-switching-to-d8-dexer.html

**Comment by moving-bits** [comment]
Thanks for your suggestions. I've tried a couple:
- I have not modified any of the gradle files (AFAIK), and the string `enableD8` is nowhere in the project files.
- Deleting the `build` directories did not help.
- using command line gradlew results in a couple of note and warning messages. If I filter the output to warnings only, it results in:

```
Warning: android.support.v4.app.FragmentActivity: can't find referenced class android.support.v4.app.ActivityCompat21
Warning: android.support.v4.app.FragmentActivity: can't find referenced class android.support.v4.app.ActivityCompat21
Warning: there were 2 unresolved references to classes or interfaces.
         You may need to add missing library jars or update their versions.
         If your code works fine without the missing classes, you can suppress
         the warnings with '-dontwarn' options.
         (http://proguard.sourceforge.net/manual/troubleshooting.html#unresolvedclass)
Warning: Exception while processing task java.io.IOException: Please correct the above warnings first.
Thread(Tasks limiter_2): destruction
> Task :main:transformClassesAndResourcesWithProguardForBasicDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':main:transformClassesAndResourcesWithProguardForBasicDebug'.
> Job failed, see logs for details
```
I do not want to reset my local git, so I'll skip the `git reset --hard origin/master` part. But I'm going to compare the `.AndroidStudio3.3` (from backup) and `.AndroidStudio3.4` directories next to check if AS has transferred all settings during update.

**Comment by moving-bits** [comment]
> But I'm going to compare the `.AndroidStudio3.3` (from backup) and `.AndroidStudio3.4` directories next to check if AS has transferred all settings during update.

Hm, no obvious differences jump to me...

**Comment by moving-bits** [comment]
Same behavior after downgrade of IDE to 3.3...
(How can I downgrade the other components (like gradle)? - they are not shown in the installed programs list. Just delete their directories?)

**Comment by moving-bits** [comment]
I'm back in the game...

A complete uninstall of AndroidStudio, manually deleting the .AndroidStudio33 and .gradle directories, followed by a fresh install of AndroidStudio33 seems to work. I'll stick with 3.3 for now.

Thanks for your help 👍
