### ISSUE TITLE
(all) Authorization does not work anymore

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7668]
**Describe the bug:**
Authorization does not work anymore

**To Reproduce:**
try to login/connect to one of the platforms or services

**Actual behavior/state after performing these steps:**
The login breaks or hangs or c:geo craches
(e.g. geocaching.com, oc.de -> appcrash, 
  geokrety.org -> hang - see screenshot)

**Expected behavior/state after performing these steps:**
login success

**Version of c:geo used:**
current master

**Is the problem reproducible:**
Yes 

**Screenshots:**
![20190609_174600](https://user-images.githubusercontent.com/32555742/59161560-95170080-8ae4-11e9-932a-9ccd1295b7ba.png)

**System information:**
Samsung S6

**Additional information**
Maybe a problem with the lambda code form in the *AuthorizationActivity classes?

Stack trace when reattaching to the hanging app:
```
E/AndroidRuntime: FATAL EXCEPTION: network--1
    Process: cgeo.geocaching, PID: 4360
    java.lang.AssertionError: impossible
        at java.lang.Enum$1.create(Enum.java:269)
        at java.lang.Enum$1.create(Enum.java:260)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
        at java.lang.Enum.getSharedConstants(Enum.java:286)
        at java.lang.Class.getEnumConstantsShared(Class.java:2291)
        at java.lang.Class.getEnumConstants(Class.java:2279)
        at com.fasterxml.jackson.databind.cfg.MapperConfig.collectFeatureDefaults(MapperConfig.java:99)
        at com.fasterxml.jackson.databind.cfg.MapperConfigBase.<clinit>(MapperConfigBase.java:32)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:565)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:480)
        at cgeo.geocaching.network.Network.<clinit>(Network.java:71)
        at cgeo.geocaching.network.Network.requestJSON(Network.java:496)
        at cgeo.geocaching.network.StatusUpdater.lambda$static$0(StatusUpdater.java:95)
        at cgeo.geocaching.network.-$$Lambda$StatusUpdater$Dl9oq5EHQ1l7w5i7L9s1Ft_3XTo.run(lambda)
        at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:532)
        at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:479)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: java.lang.NoSuchMethodException: values []
        at java.lang.Class.getMethod(Class.java:1981)
        at java.lang.Class.getDeclaredMethod(Class.java:1960)
        at java.lang.Enum$1.create(Enum.java:265)
        at java.lang.Enum$1.create(Enum.java:260) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58) 
        at java.lang.Enum.getSharedConstants(Enum.java:286) 
        at java.lang.Class.getEnumConstantsShared(Class.java:2291) 
        at java.lang.Class.getEnumConstants(Class.java:2279) 
        at com.fasterxml.jackson.databind.cfg.MapperConfig.collectFeatureDefaults(MapperConfig.java:99) 
        at com.fasterxml.jackson.databind.cfg.MapperConfigBase.<clinit>(MapperConfigBase.java:32) 
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:565) 
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:480) 
        at cgeo.geocaching.network.Network.<clinit>(Network.java:71) 
        at cgeo.geocaching.network.Network.requestJSON(Network.java:496) 
        at cgeo.geocaching.network.StatusUpdater.lambda$static$0(StatusUpdater.java:95) 
        at cgeo.geocaching.network.-$$Lambda$StatusUpdater$Dl9oq5EHQ1l7w5i7L9s1Ft_3XTo.run(lambda) 
        at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:532) 
        at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:479) 
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288) 
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
        at java.lang.Thread.run(Thread.java:762) 

```

**Comment by rsudev** [comment]
'Current master' is not really a version. Is is a nightly? Or a developer build? In the latter case, please name the commit hash.
Android version could also be helpful.

**Comment by rsudev** [comment]
(I tested yesterday 6516610f5e09178e50096902a203e3bf23bade70 on an Api 24 and 26 emulator - worked)

**Comment by jakedot** [comment]
IIRC, the possible Lambda problems (those arising just from using
auto-generated ones without manual refactoring which my team did at work)
can be averted in some way, possibly by setting javac compiler options -
you may want to look for 1.6 compatibility vor similar for oder devices.

Quick fix I'd recommend: just roll back all auto generated parts of the
commits in the PR and see if it gets better.

Best regards from family vacation without working equipment - my 2mo old
Blackview P6000 doesn't want to charge properly and I'm in semi-working SG
Ace II with Android 4.4.4 (still cyanogenmod from the old days... ;)
Am 09.06.2019 18:43 schrieb "Bernd" <notifications@github.com>:

**Comment by moving-bits** [comment]
No problem here with a new authorization for geokrety.org on a physical device with tonight's version at master branch + PR 7670.

**Comment by moving-bits** [comment]
Also just tried opencaching.de and opencaching.nl on the same device, with same developer version - no problems here as well.

**Comment by bekuno** [comment]
@rsudev @moving-bits 
Thanks for the feedback.
Mmm, then it is probaly a AS problem (I installed the latest updates before compiled my changes).
I will investigate this later.

**Comment by Lineflyer** [comment]
No problem here.

Android 9
2019.06.10-NB-951b2b0

**Comment by okainov** [comment]
I got report from my friend that su authorization doesn't work for him (I believe, he is either on nightlies or release builds)....

**Comment by bekuno** [comment]
tested now with  951b2b0586489178322485b2ab13e22ffe6b93d6
on Samsung S3+S6 (Android 4.3 und 7.0)
same problem on both devices
downgraded jackson to 2.9.8 also not successful
WS and Smartphones rebooted

**Comment by Lineflyer** [comment]
[This page](https://www.techjini.com/blog/using-lambda-expressions-android/) states something about support starting with Android 7. 
I have no idea about build environments and minimum requirements for those lambda functions, but please be reminded that our minSDK is currently 16.

**Comment by Lineflyer** [comment]
BTW:
Working on my Samsung Galaxy S4 with Android 5.0.1 using 2019.06.10-NB-951b2b0 without a problem to authorize geokrety and gc.com.

**Comment by jakedot** [comment]
> [This page](https://www.techjini.com/blog/using-lambda-expressions-android/) states something about support starting with Android 7.
> I have no idea about build environments and minimum requirements for those lambda functions, but please be reminded that our minSDK is currently 16.

I do think I have heard about problems with them especially on Android (completely different compiler/jvm/ecosystem than Desktop Oracle JVM), and that they are managable/fixable.

**Comment by rsudev** [comment]
As there are numerous examples of the current version working on a wide variety of Android versions and devices, it looks to me rather like an environmental issue for @bekuno than a real bug.

**Comment by Lineflyer** [comment]
I agree. After having read the linked page it is only required to target minimum Android 7 (and have set related Java options) but does not limit any minSDK.

**Comment by bekuno** [comment]
> I got report from my friend that su authorization doesn't work for him (I believe, he is either on nightlies or release builds)....

Nigthly works fine for me - opens the website. Maybe he did not realized that this happens?

**Comment by bekuno** [comment]
Nightly is ok for me on both devices.

**Comment by bekuno** [comment]
Hooray, I get to play again.
I deleted .gradle and build cache directories. Now they are created again and the login is possible.
