### ISSUE TITLE
Prevent ProGuard from cutting out enum class members

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7762]
Sometimes after upgrading my dev laptop to a new version of Android Studio I get strange results. This time I'm constantly receiving the following fatal error directly after installing the APK and launching the main activity:

```
2019-08-01 12:53:14.244 10119-10151/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: network--1
    Process: cgeo.geocaching, PID: 10119
    java.lang.AssertionError: impossible
        at java.lang.Enum$1.create(Enum.java:272)
        at java.lang.Enum$1.create(Enum.java:262)
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58)
        at java.lang.Enum.getSharedConstants(Enum.java:289)
        at java.lang.Class.getEnumConstantsShared(Class.java:2423)
        at java.lang.Class.getEnumConstants(Class.java:2409)
        at com.fasterxml.jackson.databind.cfg.MapperConfig.collectFeatureDefaults(MapperConfig.java:99)
        at com.fasterxml.jackson.databind.cfg.MapperConfigBase.<clinit>(MapperConfigBase.java:32)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:565)
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:480)
        at cgeo.geocaching.network.Network.<clinit>(Network.java:71)
        at cgeo.geocaching.network.Network.requestJSON(Network.java:496)
        at cgeo.geocaching.network.StatusUpdater.lambda$static$0(StatusUpdater.java:95)
        at cgeo.geocaching.network.-$$Lambda$StatusUpdater$Dl9oq5EHQ1l7w5i7L9s1Ft_3XTo.run(Unknown Source:0)
        at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:532)
        at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:479)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NoSuchMethodException: values []
        at java.lang.Class.getMethod(Class.java:2068)
        at java.lang.Class.getDeclaredMethod(Class.java:2047)
        at java.lang.Enum$1.create(Enum.java:268)
        at java.lang.Enum$1.create(Enum.java:262) 
        at libcore.util.BasicLruCache.get(BasicLruCache.java:58) 
        at java.lang.Enum.getSharedConstants(Enum.java:289) 
        at java.lang.Class.getEnumConstantsShared(Class.java:2423) 
        at java.lang.Class.getEnumConstants(Class.java:2409) 
        at com.fasterxml.jackson.databind.cfg.MapperConfig.collectFeatureDefaults(MapperConfig.java:99) 
        at com.fasterxml.jackson.databind.cfg.MapperConfigBase.<clinit>(MapperConfigBase.java:32) 
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:565) 
        at com.fasterxml.jackson.databind.ObjectMapper.<init>(ObjectMapper.java:480) 
        at cgeo.geocaching.network.Network.<clinit>(Network.java:71) 
        at cgeo.geocaching.network.Network.requestJSON(Network.java:496) 
        at cgeo.geocaching.network.StatusUpdater.lambda$static$0(StatusUpdater.java:95) 
        at cgeo.geocaching.network.-$$Lambda$StatusUpdater$Dl9oq5EHQ1l7w5i7L9s1Ft_3XTo.run(Unknown Source:0) 
        at io.reactivex.Scheduler$PeriodicDirectTask.run(Scheduler.java:532) 
        at io.reactivex.Scheduler$Worker$PeriodicTask.run(Scheduler.java:479) 
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288) 
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

I've already tried clean build, different SDK versions, clearing build caches, even a fresh install of AS - nothing works. 

After some research I found info that this is related to some ProGuard config, which may cut out some enums during shrinking process, which leads to the error shown above. To solve this you have to add the following to your ProGuard config:

```
# For enumeration classes, see http://proguard.sourceforge.net/manual/examples.html#enumerations
-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}
```

I'll create a PR for this.

**Comment by rsudev** [comment]
Do you know since when is this rule should be necessary or where a change came from, that triggers this?

**Comment by moving-bits** [comment]
I cannot say specifically what triggers this error. So far it has happened only on my dev laptop, not on my desktop PC, but several times already, always after upgrading AS. Last time (a couple of months ago) I was able to fix it by reinstalling AS + clearing build caches, but this time this did not work, so I started doing some more internet research. There I found several people having the same problem, not always with a solution at hand. Finally I found the solution that worked for me (extending proguard config) here: https://github.com/serso/android-checkout/issues/138 (It also includes a possible cause: ProGuard config of another component being to agressive.) Since I have added those lines to my local proguard config, every build is stable again, and without those lines every build directly crashed with the error shown in the first post.

**Comment by moving-bits** [comment]
Just returned to my desktop dev machine today, and having the same problem here now, and the same fix.

Android Studio 3.4.2
Build #AI-183.6156.11.34.5692245, built on June 27, 2019
JRE: 1.8.0_152-release-1343-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
latest CheckStyle and platform tools, but not yet activated most recent Gradle version.

**Comment by moving-bits** [comment]
Yesterday, this issue reappeared again, out of the blue (or nearly so). I had updated the AndroidAnnotation lib to v4.7 and a clean build. Starting the APK it immediately crashed with the same error described above.

This time it's using AS 3.6.3, gradle plugin 3.6.3, and different Android versions from API level 17 to 29 in the emulator.

As I did not remember the workaround at once I did a lot of research on the web as well as some debugging, but all to no avail, until I remembered the workaround. Which worked again. But I still don't know what's causing the problem. :-((
