### ISSUE TITLE
Unable to start CacheListActivity from map (targetSDK28)

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#7865]
**To Reproduce:**
- use a version with targetSDK28
- open live map
- select "show as list"

**Actual behavior/state after performing these steps:**
c:geo crashes with LogCat as follows:
```
2019-09-22 17:31:13.457 5521-5521/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 5521
    java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.CacheListActivity}: java.lang.IllegalArgumentException: Object returned from onCreateLoader must not be null
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3270)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
[...]
```

**Version of c:geo used:**
Today's master branch + PR #7653

**Is the problem reproducible:**
Yes

**Additional context:**
see https://github.com/cgeo/cgeo/issues/7860#issuecomment-533871209

**Comment by moving-bits** [comment]
Crash results from `CacheListActivity.OnCreateLoader()` returning null, since variable `loader` does not get set for `MAP` switch value:

_(around line 1993)_
```
case MAP:
    //TODO Build Null loader
    title = res.getString(R.string.map_map);
    markerId = ListMarker.NO_MARKER.markerId;
    search = (SearchResult) extras.get(Intents.EXTRA_SEARCH);
    replaceCacheListFromSearch();
    loadCachesHandler.sendMessage(Message.obtain());
    break;
```

called by
- LoaderManagerImpl.createAndInstallLoader
- LoaderManagerImpl.initLoader
- CacheListActivity.onCreate (line 524)

which results from creating the intent in
- CacheListActivity.startActivityMap (line 1864)

which itself is the result from selecting the menu entry `show as list`
