### ISSUE TITLE
Tests with live caches fail if they are disabled

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#7886]
**Describe the bug:**
Tests with live caches fail if they are disabled.

**Samples:**
~~~
1) testSearchByGeocodeBasis(cgeo.geocaching.CgeoApplicationTest)
org.junit.ComparisonFailure: [Cache GC3FJ5F: disabled] expected:<[fals]e> but was:<[tru]e>
at cgeo.test.Compare.assertCompareCaches(Compare.java:27)
at cgeo.geocaching.CgeoApplicationTest.testSearchByGeocodeBasis(CgeoApplicationTest.java:306)
~~~
~~~
2) testSearchFromMap(cgeo.geocaching.connector.gc.GCBaseTest)
org.junit.ComparisonFailure: [Cache GC3FJ5F: disabled] expected:<[fals]e> but was:<[tru]e>
at cgeo.test.Compare.assertCompareCaches(Compare.java:27)
at cgeo.geocaching.connector.gc.GCBaseTest.testSearchFromMap(GCBaseTest.java:26)
~~~

**Comment by bekuno** [comment]
In cgeo.geocaching.test.mock.MockedCache we check against 5 caches.
~~~
        MOCKED_CACHES = Collections.unmodifiableList(Arrays.asList(new GC2CJPF(), new GC1ZXX2(), new GC2JVEH(), new GC3XX5J(), new GC3FJ5F()));
~~~
Only GC3FJ5F is a active cache, all other are archived.

**Comment by bekuno** [comment]
Let the risk for this situation, but test works correct without exceptions.
