### ISSUE TITLE
use LeakCanary 2.x for instrumentation tests

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8109]
see
https://square.github.io/leakcanary/upgrading-to-leakcanary-2.0/

after configure in main/build.gradle:
~~~
dependencies {
  androidTestImplementation "com.squareup.leakcanary:leakcanary-android-instrumentation:$leakCanaryVersion"
}

android {
  defaultConfig {
    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    testInstrumentationRunnerArgument "listener", "leakcanary.FailTestOnLeakRunListener"
  }
}
~~~

we got in the instrumentation tests:
~~~
RemoteAndroidTest: Running am instrument -w -r   -e coverageFile /data/data/cgeo.geocaching/coverage.ec -e notAnnotation cgeo.geocaching.test.NotForIntegrationTests -e listener leakcanary.FailTestOnLeakRunListener -e coverage true cgeo.geocaching.test/androidx.test.runner.AndroidJUnitRunner on android-23(AVD) - 6.0
execute: running am instrument -w -r   -e coverageFile /data/data/cgeo.geocaching/coverage.ec -e notAnnotation cgeo.geocaching.test.NotForIntegrationTests -e listener leakcanary.FailTestOnLeakRunListener -e coverage true cgeo.geocaching.test/androidx.test.runner.AndroidJUnitRunner
 
 There was 1 failure:
 1) Fatal exception when running tests
 java.lang.NoSuchMethodError: No static method copy$default(Lleakcanary/AppWatcher$Config;ZZZZJILjava/lang/Object;)Lleakcanary/AppWatcher$Config; in class Lleakcanary/AppWatcher$Config; or its super classes (declaration of 'leakcanary.AppWatcher$Config' appears in /data/app/cgeo.geocaching-2/base.apk)
 at leakcanary.InstrumentationLeakDetector$Companion.updateConfig(InstrumentationLeakDetector.kt:195)
 at leakcanary.FailTestOnLeakRunListener.testRunStarted(FailTestOnLeakRunListener.kt:92)
 at org.junit.runner.notification.SynchronizedRunListener.testRunStarted(SynchronizedRunListener.java:35)
 at org.junit.runner.notification.RunNotifier$1.notifyListener(RunNotifier.java:91)
 at org.junit.runner.notification.RunNotifier$SafeNotifier.run(RunNotifier.java:72)
 at org.junit.runner.notification.RunNotifier.fireTestRunStarted(RunNotifier.java:88)
 at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
 at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
 at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
 at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
 at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)
~~~

So it needs more changes. 

(check https://ci.cgeo.org/job/cgeo%20pull%20request/2543/console)

**Comment by bekuno** [comment]
LeakCanary 2.x was integrated in #8108
