### ISSUE TITLE
okhttp call fails with "Unable to load publicsuffixes.gz resource from the classpath"

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8159]
Starting at some point in time, I frequently receive the following error message in LogCat, leading to errors like "unable to log in" etc.:

```
2020-03-28 22:29:55.370 26200-26246/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: cgeo.geocaching, PID: 26200
    java.lang.IllegalStateException: Unable to load publicsuffixes.gz resource from the classpath.
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.findMatchingRule(PublicSuffixDatabase.java:123)
        at okhttp3.internal.publicsuffix.PublicSuffixDatabase.getEffectiveTldPlusOne(PublicSuffixDatabase.java:85)
        at okhttp3.Cookie.parse(Cookie.java:311)
        at okhttp3.Cookie.parse(Cookie.java:219)
        at okhttp3.Cookie.parseAll(Cookie.java:445)
        at okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.java:315)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:127)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at cgeo.geocaching.network.Network$LoggingInterceptor.intercept(Network.java:351)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at cgeo.geocaching.network.Network$HeadersInterceptor.intercept(Network.java:336)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:257)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

Some sources suggest to add the following line to proguard-project.txt:
```
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase
```
but that does not work for me, even after completely rebuilding the project.

Tested with emulator and Android 10.

Anyone else encountering this error? Anyone knows how to fix it?

**Comment by Lineflyer** [comment]
We still have random reports of login issues from the field, where it can be solved by reinstalling in 100% of the cases (there should be one rather old issue about that here).
Can this be related?

**Comment by moving-bits** [comment]
May be, don't know.
Currently the error seems to be gone, after upgrading to AS 3.6, at least in the emulated device I currently use. Will keep an eye on it.

Also haven't found anything in the okhttp release notes between 3.12.6 (which we use on release), 3.12.8 (master) and 3.12.10 (most up to date 3.x okhttp version).

**Comment by moving-bits** [comment]
hasn't resurfaced so far, so let's close for the time being

**Comment by tuanvn91** [comment]
anyone can resolve this?

**Comment by moving-bits** [comment]
> anyone can resolve this?

is this something you have experienced with c:geo, or are you looking for a solution for one of your own projects?
(A proposed solution, haven't tested, though, is mentioned in this article: https://stackoverflow.com/questions/46168012/understand-okhttp-publicsuffixes-gz)
