### ISSUE TITLE
Crash when modifying filtered list

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8167]
To Reproduce:
- Open a list with many caches
- Set a filter so that a subset is remaining (I used: Status=archived)
- On the filtered list, select Menu - Manage caches - Delete all

Result:
Filtered caches are deleted as expected, but app crashes immediately afterwards

Expected:
No crash, filtered caches deleted

Version:
2020.03.29-NB1

**Comment by Lineflyer** [comment]
FYI: 
While smoke testing the release 2020.03.30 I tried to reproduce this and failed.
So it seems the bug is somewhere in the commits between `release` and `master`.

Even more I would say, that the problem came in within the last 2-3 weeks as I perform such sequence rather often while cleaning found caches from my lists and it worked last time I cleaned up.

**Comment by moving-bits** [comment]
Error log is:

```
2020-03-30 20:43:45.480 11192-11192/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 11192
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/jensdriller/libs/undobar/R$layout;
        at com.jensdriller.libs.undobar.UndoBar$Style.<clinit>(UndoBar.java:23)
        at com.jensdriller.libs.undobar.UndoBar.<init>(UndoBar.java:115)
        at com.jensdriller.libs.undobar.UndoBar$Builder.create(UndoBar.java:609)
        at com.jensdriller.libs.undobar.UndoBar$Builder.show(UndoBar.java:635)
        at com.jensdriller.libs.undobar.UndoBar$Builder.show(UndoBar.java:625)
        at cgeo.geocaching.command.AbstractCommand$ActionAsyncTask.showUndoToast(AbstractCommand.java:128)
        at cgeo.geocaching.command.AbstractCommand$ActionAsyncTask.onPostExecuteInternal(AbstractCommand.java:119)
        at cgeo.geocaching.command.AbstractCommand$ActionAsyncTask.onPostExecuteInternal(AbstractCommand.java:104)
        at cgeo.geocaching.utils.AbstractAsyncTaskWithProgress.onPostExecute(AbstractAsyncTaskWithProgress.java:72)
        at android.os.AsyncTask.finish(AsyncTask.java:755)
        at android.os.AsyncTask.access$900(AsyncTask.java:192)
        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
[...]
```

Looks like coming from the integration of undobar, see PR #8153.

@bekuno  Can you have a look at it?

**Comment by Lineflyer** [comment]
Also reported from users of nightly versions:

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/jensdriller/libs/undobar/R$layout;
at com.jensdriller.libs.undobar.UndoBar$Style.(UndoBar.java:23)
at com.jensdriller.libs.undobar.UndoBar.(UndoBar.java:115)
at com.jensdriller.libs.undobar.UndoBar$Builder.create(UndoBar.java:609)
at com.jensdriller.libs.undobar.UndoBar$Builder.show(UndoBar.java:635)
at com.jensdriller.libs.undobar.UndoBar$Builder.show(UndoBar.java:625)
at cgeo.geocaching.command.AbstractCommand$ActionAsyncTask.showUndoToast(AbstractCommand.java:128)
at cgeo.geocaching.command.AbstractCommand$ActionAsyncTask.onPostExecuteInternal(AbstractCommand.java:119)
at cgeo.geocaching.command.AbstractCommand$ActionAsyncTask.onPostExecuteInternal(AbstractCommand.java:104)
at cgeo.geocaching.utils.AbstractAsyncTaskWithProgress.onPostExecute(AbstractAsyncTaskWithProgress.java:72)
at android.os.AsyncTask.finish(AsyncTask.java:755)
at android.os.AsyncTask.access$900(AsyncTask.java:192)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:224)
at android.app.ActivityThread.main(ActivityThread.java:7520)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.ClassNotFoundException: com.jensdriller.libs.undobar.R$layout
... 18 more
```

**Comment by bekuno** [comment]
Thr R*.java/classes were dynamicly generated.
Eg. in build\intermediates\javac\basicNightly\classes\com\jensdriller\libs\undobar 
I will look how to integrate it.

**Comment by bekuno** [comment]
Primary reason is a changed behavior in gradle 6.

After long research I found that the problem for including undobar is a missing *.pom.
This was alredy earlier a problem (https://github.com/cgeo/cgeo/issues/7027), but the "solution" for this issue could not help for the current fails.
I found then the article
https://discuss.gradle.org/t/how-to-fetch-maven-artifact-without-pom-file-in-gradle-6-0/33836
and so the solution here https://docs.gradle.org/current/userguide/upgrading_version_5.html?_ga=2.99613598.1698678510.1585695059-360782094.1573990706#maven_or_ivy_repositories_are_no_longer_queried_for_artifacts_without_metadata_by_default
