### ISSUE TITLE
CI Instrumentation Tests output missing

### ISSUE THREAD

**Issue by bekuno** [cgeo/cgeo#8175]
No instrumentation tests since PR #8153 / CI Build 2581

Edit: only the output is gone

**Comment by bekuno** [comment]
It seams that only the output is gone.
The call is there:
~~~
> Task :main:connectedBasicDebugAndroidTest
Starting 500 tests on android-23(AVD) - 6.0
~~~
The build duration is in the same region.

**Comment by bekuno** [comment]
And it works, e.g. in test build 2608:
~~~
> Task :main:connectedBasicDebugAndroidTest
Starting 500 tests on android-23(AVD) - 6.0

cgeo.geocaching.activity.ProgressTest > testProgressWrapper[android-23(AVD) - 6.0] [31mFAILED [0m
	java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x14000000 cmp=cgeo.geocaching/.AboutActivity } within 45 seconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1585772099296 and now the last time the queue went idle was: 1585772099296. If these numbers are the same your activity might be hogging the event queue.
	at androidx.test.runner.MonitoringInstrumentation.startActivitySync(MonitoringInstrumentation.java:481)

cgeo.geocaching.address.GeocoderTest > testAndroidGeocoder[android-23(AVD) - 6.0] [31mFAILED [0m
	java.lang.RuntimeException: java.io.IOException: grpc failed
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)

~~~

**Comment by bekuno** [comment]
The "instrumentation" output was a bug since gradle plugin 3.2.1, see
`https://stackoverflow.com/questions/53539370/how-can-you-disable-the-v-instrumentationresultparser-output-when-running-instru`
I do not remember any discussion on this subject in the cgeob team.
But now it is as long before (PR #7177).
