### ISSUE TITLE
NPE at  isGotoHistoryUDC

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8257]
Triggers:
- Click an unsaved cache on map, from the popup select "More details"
- Perform nearby search, click on unsaved cache to open details

Version:
2020.04.26-NB  (not on release)

Result:
```
12:27:43.487 Warning cgeo 10867  [main] UncaughtException
12:27:43.487 Warning cgeo 10867  java.lang.NullPointerException: Attempt to invoke virtual method 'boolean cgeo.geocaching.models.Geocache.isGotoHistoryUDC()' on a null object reference
12:27:43.487 Warning cgeo 10867  	at cgeo.geocaching.CacheDetailActivity.onPrepareOptionsMenu(CacheDetailActivity.java:686)
12:27:43.487 Warning cgeo 10867  	at android.app.Activity.onPreparePanel(Activity.java:2881)
12:27:43.487 Warning cgeo 10867  	at androidx.fragment.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:502)
12:27:43.487 Warning cgeo 10867  	at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:488)
12:27:43.487 Warning cgeo 10867  	at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
12:27:43.487 Warning cgeo 10867  	at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:2857)
12:27:43.487 Warning cgeo 10867  	at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1773)
12:27:43.487 Warning cgeo 10867  	at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2026)
12:27:43.487 Warning cgeo 10867  	at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:263)
12:27:43.487 Warning cgeo 10867  	at android.os.Handler.handleCallback(Handler.java:739)
12:27:43.487 Warning cgeo 10867  	at android.os.Handler.dispatchMessage(Handler.java:95)
12:27:43.487 Warning cgeo 10867  	at android.os.Looper.loop(Looper.java:135)
12:27:43.487 Warning cgeo 10867  	at android.app.ActivityThread.main(ActivityThread.java:5219)
12:27:43.487 Warning cgeo 10867  	at java.lang.reflect.Method.invoke(Native Method)
12:27:43.487 Warning cgeo 10867  	at java.lang.reflect.Method.invoke(Method.java:372)
12:27:43.487 Warning cgeo 10867  	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
12:27:43.487 Warning cgeo 10867  	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

**Comment by geocachermgo** [comment]
I got a NPE also while handling a saved cache with 2020.04.26-NB-8614b4d. Error log was send by mail to support@cgeo.org

**Comment by Lineflyer** [comment]
@moving-bits 
Did you notice this issue? It seems one of the recently merged PRs broke the nightly build in some main functions.

**Comment by moving-bits** [comment]
I'm currently scanning the incoming issues, have been out caching this afternoon :-)

**Comment by Lineflyer** [comment]
This is the stack trace mentioned by @geocachermgo 

ˋˋˋ
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean cgeo.geocaching.models.Geocache.isGotoHistoryUDC()' on a null object reference
at cgeo.geocaching.CacheDetailActivity.onPrepareOptionsMenu(CacheDetailActivity.java:686)
at android.app.Activity.onPreparePanel(Activity.java:4158)
at androidx.fragment.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:502)
at androidx.fragment.app.FragmentActivity.onPreparePanel(FragmentActivity.java:488)
at androidx.appcompat.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:99)
at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onPreparePanel(AppCompatDelegateImpl.java:2857)
at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:1773)
at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2026)
at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:263)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1058)
at android.view.Choreographer.doCallbacks(Choreographer.java:865)
at android.view.Choreographer.doFrame(Choreographer.java:796)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:224)
at android.app.ActivityThread.main(ActivityThread.java:7520)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
ˋˋˋ

**Comment by Lineflyer** [comment]
Fix merged and nightly build triggered.
Fixed for me

@geocachermgo Feel free to test the new nightly and provide feedback about your use case.

**Comment by geocachermgo** [comment]
Worked, no NPE. But it was not really reproducable before.
