### ISSUE TITLE
NPE in map initialization

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8319]
Another NPW from Google Play:

```
java.lang.NullPointerException: 
  at cgeo.geocaching.maps.CGeoMap.initializeMap (CGeoMap.java:490)
  at cgeo.geocaching.maps.CGeoMap.lambda$onCreate$0$CGeoMap (CGeoMap.java:577)
  at cgeo.geocaching.maps.-$$Lambda$CGeoMap$G7bmzyR-PaaunjyTQ5jHInO_IEU.mapReady (Unknown Source:4)
  at cgeo.geocaching.maps.google.v2.GoogleMapView.onMapReady (GoogleMapView.java:138)
...
```

**Comment by MagpieFourtyTwo** [comment]
Don't think so, but to be on the safe side:
Is this related to the immediate crash of the latest nightly when opening Google Map or Sat view?

**Comment by Lineflyer** [comment]
For me latest nightly works normal. So, incidentally it could be the same.. any chance you can provide a stacktrace?

**Comment by MagpieFourtyTwo** [comment]
If I can do so with nothing else at my hands than the smartphone ...

**Comment by MagpieFourtyTwo** [comment]
BTW: This happened to both of our mobiles:
- Huawei P30 Pro, Android 10, and
- Sony Xperia Z5 Premium, Android 7.1.1, IIRC.

**Comment by MagpieFourtyTwo** [comment]
Just uninstalled c:geo and reinstalled previous nightly (2020.05.08-NB-36889f5) - with this version Google Map and Sat view work perfectly fine.

Then I again installed yesterday's nightly (2020.05.09-NB-10018fa) - switching to Sat view - crash.

Thus must be s/th that has been changed between 2020.05.08-NB-36889f5 and 2020.05.09-NB-10018fa.

After that a new nightly appeared (2020.05.10-NB-244e62c) - installed - switching to Sat view - crashes, too.

**Comment by MagpieFourtyTwo** [comment]
After a few starts Sat view suddenly works with 2020.05.09-NB-10018fa - I'm confused.
Again installed 2020.05.10-NB-244e62c - crash ... \*örgs*
Rebooting device ... GM and Sat still crash c:geo ... \*grrmbl*

**Comment by MagpieFourtyTwo** [comment]
FYI: 2020.05.11-NB-1af53d9 - crashes with GM and Sat view, too.

**Comment by moving-bits** [comment]
> Is this related to the immediate crash of the latest nightly when opening Google Map or Sat view?

Cannot say - I'm not able to reproduce the behavior you describe. Switching between standard and sat view works flawlessly here. Tested in emulator with current master and different map settings (live map, single cache map, cache list map) - no problems here.

The NPE described in this issue should make no difference between standard and sat view, BTW.

**Comment by MagpieFourtyTwo** [comment]
Over here it crashes as soon as we ...
- switch from OSM (offline) to Google Maps or Sat view, no matter which map context
- start Live Map from start screen afterwards, i. e. if GM or Sat view is selected
After that we have to change map selection in map options, to get a map at all.
Only thing that helps is to downgrade to 2020.05.08-NB-36889f5.

With "no difference between standard and sat view" you mean
- "Google Map and Google Sat view" or
- "OSM and Google Sat view"?
The first does not make a difference over here, too, whereas the latter does:
OSM (on- and offline) works, as well as CyclOSM, but both from Google do not.

Would a Debug Log help?  Otherwise I would downgrade again and then wait and see ...

**Comment by Lineflyer** [comment]
> Would a Debug Log help? Otherwise I would downgrade again and then wait and see ...

Sure, this would help. That was what I meant with stacktrace above.

**Comment by MagpieFourtyTwo** [comment]
Hmm. LogCat doesn't work anymore, thus installed MatLog, granted read access to logs, as it demanded (adb pm grant com.pluscubed.matlog android.permission.READ_LOGS), but I don't see anything from c:geo - anything else left to be done? Or is there a better way to get the trace?

**Comment by geocachermgo** [comment]
True also for me:
java.lang.NullPointerException: Attempt to invoke virtual method 'float android.location.Location.distanceTo(android.location.Location)' on a null object reference
	at cgeo.geocaching.maps.google.v2.GooglePositionAndHistory.drawHistory(GooglePositionAndHistory.java:279)
	at cgeo.geocaching.maps.google.v2.GooglePositionAndHistory.repaintRequired(GooglePositionAndHistory.java:176)
	at cgeo.geocaching.maps.google.v2.GooglePositionAndHistory.updateRoute(GooglePositionAndHistory.java:168)
	at cgeo.geocaching.maps.routing.Route.clearRouteInternal(Route.java:179)
	at cgeo.geocaching.maps.routing.Route.reloadRoute(Route.java:158)
	at cgeo.geocaching.maps.CGeoMap.initializeMap(CGeoMap.java:481)
	at cgeo.geocaching.maps.CGeoMap.lambda$onCreate$0$CGeoMap(CGeoMap.java:578)
	at cgeo.geocaching.maps.-$$Lambda$CGeoMap$G7bmzyR-PaaunjyTQ5jHInO_IEU.mapReady(Unknown Source:4)
	at cgeo.geocaching.maps.google.v2.GoogleMapView.onMapReady(GoogleMapView.java:143)
	at com.google.android.gms.maps.zzac.zza(Unknown Source:2)
	at com.google.android.gms.maps.internal.zzaq.dispatchTransaction(Unknown Source:12)
	at com.google.android.gms.internal.maps.zzb.onTransact(Unknown Source:12)
	at android.os.Binder.transact(Binder.java:914)
	at cg.b(:com.google.android.gms.policy_maps_dynamite@201512001@201512001057.308330177.308330177:2)
	at com.google.maps.api.android.lib6.impl.be.run(:com.google.android.gms.policy_maps_dynamite@201512001@201512001057.308330177.308330177:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by Lineflyer** [comment]
> Hmm. LogCat doesn't work anymore, thus installed MatLog, granted read access to logs, as it demanded (adb shell pm grant com.pluscubed.matlog android.permission.READ_LOGS), but I don't see anything from c:geo - anything else left to be done? Or is there a better way to get the trace?

Yes, actually using on-board tools to trace has become really difficult. I have to admit, that I did not find any solution up to now due to limited time.

But I think @geocachermgo has already catched it.

@moving-bits Looking at the trace I assume its another problem (history line)?
@MagpieFourtyTwo Do you have the position history line on map set to active?

**Comment by moving-bits** [comment]
I created a separate issue for the new NPE happening on GM map init when trying to draw the history trail. - Will look into it.

**Comment by MagpieFourtyTwo** [comment]
> @MagpieFourtyTwo Do you have the position history line on map set to active?

Yep. And after deactivating it, GM and Sat view are allowed to survive again. ;)
