### ISSUE TITLE
NPE in map initialization - drawHistory

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#8328]
from https://github.com/cgeo/cgeo/issues/8319#issuecomment-626654238 by @geocachermgo:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'float android.location.Location.distanceTo(android.location.Location)' on a null object reference
	at cgeo.geocaching.maps.google.v2.GooglePositionAndHistory.drawHistory(GooglePositionAndHistory.java:279)
	at cgeo.geocaching.maps.google.v2.GooglePositionAndHistory.repaintRequired(GooglePositionAndHistory.java:176)
	at cgeo.geocaching.maps.google.v2.GooglePositionAndHistory.updateRoute(GooglePositionAndHistory.java:168)
	at cgeo.geocaching.maps.routing.Route.clearRouteInternal(Route.java:179)
	at cgeo.geocaching.maps.routing.Route.reloadRoute(Route.java:158)
	at cgeo.geocaching.maps.CGeoMap.initializeMap(CGeoMap.java:481)
	at cgeo.geocaching.maps.CGeoMap.lambda$onCreate$0$CGeoMap(CGeoMap.java:578)
	at cgeo.geocaching.maps.-$$Lambda$CGeoMap$G7bmzyR-PaaunjyTQ5jHInO_IEU.mapReady(Unknown Source:4)
	at cgeo.geocaching.maps.google.v2.GoogleMapView.onMapReady(GoogleMapView.java:143)
	at com.google.android.gms.maps.zzac.zza(Unknown Source:2)
	at com.google.android.gms.maps.internal.zzaq.dispatchTransaction(Unknown Source:12)
	at com.google.android.gms.internal.maps.zzb.onTransact(Unknown Source:12)
	at android.os.Binder.transact(Binder.java:914)
	at cg.b(:com.google.android.gms.policy_maps_dynamite@201512001@201512001057.308330177.308330177:2)
	at com.google.maps.api.android.lib6.impl.be.run(:com.google.android.gms.policy_maps_dynamite@201512001@201512001057.308330177.308330177:2)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7520)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

occurring in current nightlies starting with 2020-05-08-NB

**Comment by MagpieFourtyTwo** [comment]
Thx a lot - it's working again now.  👍
