### ISSUE TITLE
[CI + Testing] Suppress or rewrite fishy test class ProgressTest

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#8764]
This is about test case `cgeo.geocaching.activity.ProgressTest.testProgressWrapper`

When this test cases is run locally bundled with all instrumented test cases it reports ok. However, when it is run locally and solely (=not in bundle with all Instrumented test cases but only test class ProgressTest), then it produces following exception:
```
java.lang.RuntimeException: Can't create handler inside thread Thread[Instr: androidx.test.runner.AndroidJUnitRunner,5,main] that has not called Looper.prepare()
at android.os.Handler.<init>(Handler.java:207)
at android.os.Handler.<init>(Handler.java:119)
at android.app.Dialog.<init>(Dialog.java:133)
at android.app.AlertDialog.<init>(AlertDialog.java:204)
at android.app.AlertDialog.<init>(AlertDialog.java:200)
at android.app.ProgressDialog.<init>(ProgressDialog.java:112)
at cgeo.geocaching.activity.Progress.createProgressDialog(Progress.java:61)
at cgeo.geocaching.activity.Progress.show(Progress.java:46)
at cgeo.geocaching.activity.ProgressTest.testProgressWrapper(ProgressTest.java:32)
at java.lang.reflect.Method.invoke(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:220)
````

Also, this test cases produces CI failures on a regular basis with following exception:
````
java.lang.RuntimeException: Could not launch intent Intent { act=android.intent.action.MAIN flg=0x14000000 cmp=cgeo.geocaching/.AboutActivity } within 45 seconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1596791777541 and now the last time the queue went idle was: 1596791777541. If these numbers are the same your activity might be hogging the event queue.
at androidx.test.runner.MonitoringInstrumentation.startActivitySync(MonitoringInstrumentation.java:481)
at android.test.InstrumentationTestCase.launchActivityWithIntent(InstrumentationTestCase.java:119)
at android.test.InstrumentationTestCase.launchActivity(InstrumentationTestCase.java:97)
at android.test.ActivityInstrumentationTestCase2.getActivity(ActivityInstrumentationTestCase2.java:104)
at cgeo.geocaching.activity.ProgressTest.testProgressWrapper(ProgressTest.java:25)
at java.lang.reflect.Method.invoke(Native Method)
at android.test.InstrumentationTestCase.runMethod(InstrumentationTestCase.java:214)
at android.test.InstrumentationTestCase.runTest(InstrumentationTestCase.java:199)
at android.test.ActivityInstrumentationTestCase2.runTest(ActivityInstrumentationTestCase2.java:192)
at junit.framework.TestCase.runBare(TestCase.java:134)
````
(lots of "retest this please" going on for this)

The test uses a deprecated API for instrumented activity tests and probably needs complete rewrite. This might not be easy or quick to do.
Thus my proposal is to `@Suppress` this test case for now (as it is already done with lots of other test cases in the area, e.g. many Waypoint activity test cases).

**Comment by moving-bits** [comment]
We do have #8764 (suppressing the test) as a workaround, thanks to @eddiemuc, but I'd like to keep this issue open anyway as a reminder to fix this test / our test framework (whatever is needed).

**Comment by eddiemuc** [comment]
This is meanwhile solved with refactoring espresso tests.
