### ISSUE TITLE
Color picker seems to be broken

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#8813]
**Describe the bug:**
c:geo crashes when using the color picker in settings/map/map line customization

I realized this while testing the fix of #8783 (by the way the first PR fixes that issue for me, but that's another topic)

**System information:**
```
--- System information ---
Device: Telekom Puls (Telekom_Puls, T-Mobile)
Android version: 5.0.1
Android build: LRX21M.vC29-0 release-keys
c:geo version: 2020.08.16-a7ca533 developer build
Google Play services: enabled - 20.26.14 (020300-320008519)
Low power mode: inactive
Compass capabilities: no
Rotation vector sensor: absent
Orientation sensor: absent
Magnetometer & Accelerometer sensor: absent
Direction sensor used: magnetometer & accelerometer
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en_US
System date format: dd/MM/yyyy
Debug mode active: no
System internal c:geo dir: /data/data/cgeo.geocaching (9.0 GB free) internal
User storage c:geo dir: /storage/sdcard0/cgeo (8.9 GB free) external non-removable
Geocache data: /storage/sdcard0/Android/data/cgeo.geocaching/files/GeocacheData (8.9 GB free) external non-removable
Database: /data/data/cgeo.geocaching/databases/data (228.0 KB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / BASIC
   opencaching.de: Not logged in (Not authorized)
Geocaching.com date format: dd.MM.yyyy
Installed c:geo plugins:  none
--- End of system information ---

```

**Additional context:** the error message
```
E/InputEventReceiver: Exception dispatching input event.
E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI: android.view.InflateException: Binary XML file line #103: Error inflating class <unknown>
        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:414)
        at com.android.internal.app.AlertController.installContent(AlertController.java:238)
        at android.app.AlertDialog.onCreate(AlertDialog.java:356)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:387)
        at android.app.Dialog.show(Dialog.java:288)
        at android.preference.DialogPreference.showDialog(DialogPreference.java:316)
        at cgeo.geocaching.settings.ColorpickerPreference.showDialog(ColorpickerPreference.java:185)
        at android.preference.DialogPreference.onClick(DialogPreference.java:274)
        at android.preference.Preference.performClick(Preference.java:1013)
        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
        at android.widget.AdapterView.performItemClick(AdapterView.java:305)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1185)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3222)
        at android.widget.AbsListView.onTouchUp(AbsListView.java:4149)
        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3867)
        at android.view.View.dispatchTouchEvent(View.java:8491)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2540)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2225)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2400)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1761)
        at android.app.Dialog.dispatchTouchEvent(Dialog.java:779)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2361)
        at android.view.View.dispatchPointerEvent(View.java:8692)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4490)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4348)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3889)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3942)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3908)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4018)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3916)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4075)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3889)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3942)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3908)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3916)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3889)
    	at android.view.ViewRootImpl.deliverInputEvent(V
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 11767
    android.view.InflateException: Binary XML file line #103: Error inflating class <unknown>
        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
        at com.android.internal.policy.impl.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:55)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:682)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:414)
        at com.android.internal.app.AlertController.installContent(AlertController.java:238)
        at android.app.AlertDialog.onCreate(AlertDialog.java:356)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:387)
        at android.app.Dialog.show(Dialog.java:288)
        at android.preference.DialogPreference.showDialog(DialogPreference.java:316)
        at cgeo.geocaching.settings.ColorpickerPreference.showDialog(ColorpickerPreference.java:185)
        at android.preference.DialogPreference.onClick(DialogPreference.java:274)
        at android.preference.Preference.performClick(Preference.java:1013)
        at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:214)
        at android.widget.AdapterView.performItemClick(AdapterView.java:305)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1185)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3222)
        at android.widget.AbsListView.onTouchUp(AbsListView.java:4149)
        at android.widget.AbsListView.onTouchEvent(AbsListView.java:3867)
        at android.view.View.dispatchTouchEvent(View.java:8491)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2540)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2225)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2546)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2239)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2400)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1761)
        at android.app.Dialog.dispatchTouchEvent(Dialog.java:779)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2361)
        at android.view.View.dispatchPointerEvent(View.java:8692)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4490)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4348)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3889)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3942)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3908)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4018)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3916)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4075)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3889)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3942)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3908)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3916)
    	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.jav

```

**Comment by moving-bits** [comment]
Can reproduce in the emulator, seems to be attribute `text_color` missing on that API level.
