### ISSUE TITLE
ClassCast Exception on launching NewMap or CGeoMap

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#8941]
New crash report for 2020.09.02-RC.
There are several similar crash reports / stack traces, one example:

```
java.lang.RuntimeException: 

at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2822)

at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2897)

at android.app.ActivityThread.-wrap11 (Unknown Source)

at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1598)

at android.os.Handler.dispatchMessage (Handler.java:105)

at android.os.Looper.loop (Looper.java:251)

at android.app.ActivityThread.main (ActivityThread.java:6572)

at java.lang.reflect.Method.invoke (Native Method)

at com.android.internal.os.Zygote$MethodAndArgsCaller.run (Zygote.java:240)

at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:767)

Caused by: java.lang.ClassCastException: 

at cgeo.geocaching.maps.mapsforge.v6.NewMap.onCreate (NewMap.java:223)

at android.app.Activity.performCreate (Activity.java:6975)

at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1214)

at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2775)


```

**Comment by moving-bits** [comment]
Also happening with other map type:

```
java.lang.RuntimeException: 
 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2919)
 
  at android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:3054)
 
  at android.app.servertransaction.LaunchActivityItem.execute (LaunchActivityItem.java:78)
 
  at android.app.servertransaction.TransactionExecutor.executeCallbacks (TransactionExecutor.java:108)
 
  at android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:68)
 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1814)
 
  at android.os.Handler.dispatchMessage (Handler.java:106)
 
  at android.os.Looper.loop (Looper.java:280)
 
  at android.app.ActivityThread.main (ActivityThread.java:6706)
 
  at java.lang.reflect.Method.invoke (Native Method)
 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
 
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:858)
Caused by: java.lang.ClassCastException: 
 
  at cgeo.geocaching.maps.CGeoMap.onCreate (CGeoMap.java:552)
 
  at cgeo.geocaching.maps.google.v2.GoogleMapActivity.onCreate (GoogleMapActivity.java:50)
 
  at android.app.Activity.performCreate (Activity.java:7145)
 
  at android.app.Activity.performCreate (Activity.java:7136)
 
  at android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1272)
 
  at android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2899)
```

**Comment by moving-bits** [comment]
Both reports direct to unparcelling a `ManualRoute` object => I need to look into this.

**Comment by moving-bits** [comment]
Cannot reproduce in the emulator, but found an unparcelling error in `RouteSegment` - let's see if that fixes it.

**Comment by Lomanic** [comment]
I saw two crashes with the beta, they occurred when going back to cgeo from another application after a while. On the last crash (don't remember for the first one), the crash occurred when I pressed the back arrow in the upper left corner on a geocache listing, to go back to the Live Map.   

```
09-06 00:42:31.044 31668 31668 I cgeo : [Log] Logging set: minLevel=WARN, minAddCallerInfo=NONE, throwOnError=false
09-06 00:42:31.044 31668 31668 I cgeo : [Log] No logging config found at /storage/emulated/0/cgeo/logfiles/log.properties, using defaults
09-06 00:42:31.044 31668 31668 I cgeo : [Log] Logging set: minLevel=WARN, minAddCallerInfo=NONE, throwOnError=false
09-06 00:42:32.129 31668 31668 W cgeo : [main] Couldn't get active Locus version
09-06 00:42:35.649 31668 31668 E AndroidRuntime: FATAL EXCEPTION: main
09-06 00:42:35.649 31668 31668 E AndroidRuntime: Process: cgeo.geocaching, PID: 31668
09-06 00:42:35.649 31668 31668 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.maps.google.v2.GoogleMapActivity}: java.lang.ClassCastException: cgeo.geocaching.models.Route cannot be cast to cgeo.geocaching.models.ManualRoute
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2684)
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2751)
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1496)
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6186)
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
09-06 00:42:35.649 31668 31668 E AndroidRuntime: Caused by: java.lang.ClassCastException: cgeo.geocaching.models.Route cannot be cast to cgeo.geocaching.models.ManualRoute
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	at cgeo.geocaching.maps.CGeoMap.onCreate(CGeoMap.java:552)
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	at cgeo.geocaching.maps.google.v2.GoogleMapActivity.onCreate(GoogleMapActivity.java:50)
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6684)
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2637)
09-06 00:42:35.649 31668 31668 E AndroidRuntime: 	... 9 more
```

```
--- System information ---
Device: Redmi Note 4 (lineage_mido, Xiaomi)
Android version: 7.1.2
Android build: lineage_mido-userdebug 7.1.2 NJH47F 535058185f
c:geo version: 2020.09.02-RC
Google Play services: enabled - 20.30.19 (040408-326531024)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: orientation
Hide caches: -
Hide waypoints: -
HW acceleration: enabled (default state)
System language: en (c:geo forced to English)
System date format: M/d/yy
Debug mode active: no
System internal c:geo dir: /mnt/expand/e7f5e9a5-68de-4d46-bbf5-dddb77784e00/user/0/cgeo.geocaching (28.7 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (461.5 MB free) external non-removable
Geocache data: /storage/emulated/0/Android/data/cgeo.geocaching/files/GeocacheData (461.5 MB free) external non-removable
Database: /mnt/expand/e7f5e9a5-68de-4d46-bbf5-dddb77784e00/user/0/cgeo.geocaching/databases/data (7.9 MB) on system internal storage
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: MM/dd/yyyy
Installed c:geo plugins:  none
BRouter connection available: false
--- End of system information ---
```

**Comment by moving-bits** [comment]
I have been able to reproduce it once in the meantime, and added some code yesterday to mitigate it. I'll merge this to `release` and then `master`, so it should be in the next nightly.

@Lomanic 
Can to test this with the next nightly, if you have the time?

**Comment by Lomanic** [comment]
@moving-bits my brand new sd card, where I moved cgeo, died after only two weeks of usage and I'm not on vacation anymore, so can't test it. As I'm already lacking free space (hence buying and installing an sd card), I don't think I will be able to test nightlies anytime soon, I'm staying on beta for the moment.
