### ISSUE TITLE
Live Map Cache Refreshs may trigger HTTP 429 "Too many requests" for geocaching.com

### ISSUE THREAD

**Issue by eddiemuc** [cgeo/cgeo#9354]
When using Live Map (OSM, Offline or GoogleMap) while quickly moving in a low-zoom map (=when moving more than or close to 1/4 of the viewport per second), then frequently issued viewport cache searchs may trigger HTTP 429 ("Too many requests") for GC.com. This results both in a not updated map and may also lead to blockage by server over time.

Reproduce as follows:
* Open c:geo, select Live Map
* Choose a zoom level not too broad (such that it is possible to move 1/4 of the viewport per second)
* Use some tool to simulate driving along some route (e.g. using an Autobahn from Munich to Frankfurt using Emulator and replaying at 5x the speed. Maybe same can be acomplished with apps like Lockito?)
* Wait a while
* At some point you will no longer see refreshed Geocaching-caches). Check logcat for HTTP429 errors

Places to fix
* For OSM/Offline: cgeo.geocaching.maps.mapsforge.v6.caches.LiveCachesOverlay.LoadTimerAction
* For GoogleMaps: cgeo.geocaching.maps.CgeoMap.LoadTimerAction

A typical exception in the log when problem happens:
```
2020-11-06 14:56:43.009 30829-31052/cgeo.geocaching D/cgeo: [network--10] GCMap.searchPlayMapByViewport(N 48° 27,316' · E 011° 34,438',N 48° 29,056' · E 011° 35,955') {GCMap.searchPlayMapByViewport:125/GCMap.searchByViewport:105/GCConnector.searchByViewport:261/ConnectorFactory.lambda$searchByViewport$0:346/-$$Lambda$ConnectorFactory$xlYIDnOeDkjd0u5VT0oIRtPq6Zk.apply:4/SearchResult.lambda$null$0:327/-$$Lambda$SearchResult$S4Ub23vsnqWr5X8nr-1svPn50lg.call:4/MaybeFromCallable.subscribeActual:47/Maybe.subscribe:5317/MaybeSubscribeOn$SubscribeTask.run:54}
2020-11-06 14:56:43.013 30829-31626/cgeo.geocaching D/cgeo: [OkHttp] GET https://www.geocaching.com/api/proxy/web/search?box=48.484266%2C11.573968%2C48.455274%2C11.599252&take=500&asc=true&skip=0&sort=distance&origin=48.46977%2C11.58661&app=cgeo {Network$LoggingInterceptor.intercept:358/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:346/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641/Thread.run:919}
2020-11-06 14:56:43.029 30829-30898/cgeo.geocaching D/cgeo: [OkHttp] GET https://geocaching.su/api/list.php?maxlat=48.484266&maxlng=11.599252&minlat=48.455274&minlng=11.573968&oauth_consumer_key=b32876bd62c0b0841005cf6e4e6f38e10583547c7&oauth_nonce=825fbd1c7db71f960df501658faaa2fa&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1604671003&oauth_token=03ffe9c2134584b3a82413e4863c8f1505f6d8b55&oauth_version=1.0&oauth_signature=qbxEHhbdNfgDYROfa1KUR0EWu5g%3D {Network$LoggingInterceptor.intercept:358/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:346/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641/Thread.run:919}
2020-11-06 14:56:43.031 30829-31624/cgeo.geocaching D/cgeo: [OkHttp] GET https://www.opencaching.de/okapi/services/caches/shortcuts/search_and_retrieve?langpref=de%7Cen&oauth_consumer_key=q7HSGzELA2hjEvCVLh4W&oauth_nonce=7047c01782c2b963e52027d4082b5c23&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1604671003&oauth_token=6RQeTdgpY8QjsQmDyZSQ&oauth_version=1.0&retr_method=services%2Fcaches%2Fgeocaches&retr_params=%7B%22fields%22%3A%20%22code%7Cname%7Clocation%7Ctype%7Cstatus%7Cdifficulty%7Cterrain%7Csize%7Csize2%7Cdate_hidden%7Ctrackables_count%7Cis_found%22%7D&search_method=services%2Fcaches%2Fsearch%2Fbbox&search_params=%7B%22bbox%22%3A%2248.455274%7C11.573968%7C48.484266%7C11.599252%22%2C%22status%22%3A%22Available%7CTemporarily%20unavailable%22%2C%22ignored_status%22%3A%22notignored_only%22%7D&wrap=true&oauth_signature=yVl%2BHUsXtbDEaq10r8gbtN%2BInSM%3D {Network$LoggingInterceptor.intercept:358/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:346/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641/Thread.run:919}
2020-11-06 14:56:43.105 30829-31624/cgeo.geocaching D/cgeo: [OkHttp] 200 (74 ms) GET https://www.opencaching.de/okapi/services/caches/shortcuts/search_and_retrieve?langpref=de%7Cen&oauth_consumer_key=q7HSGzELA2hjEvCVLh4W&oauth_nonce=7047c01782c2b963e52027d4082b5c23&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1604671003&oauth_token=6RQeTdgpY8QjsQmDyZSQ&oauth_version=1.0&retr_method=services%2Fcaches%2Fgeocaches&retr_params=%7B%22fields%22%3A%20%22code%7Cname%7Clocation%7Ctype%7Cstatus%7Cdifficulty%7Cterrain%7Csize%7Csize2%7Cdate_hidden%7Ctrackables_count%7Cis_found%22%7D&search_method=services%2Fcaches%2Fsearch%2Fbbox&search_params=%7B%22bbox%22%3A%2248.455274%7C11.573968%7C48.484266%7C11.599252%22%2C%22status%22%3A%22Available%7CTemporarily%20unavailable%22%2C%22ignored_status%22%3A%22notignored_only%22%7D&wrap=true&oauth_signature=yVl%2BHUsXtbDEaq10r8gbtN%2BInSM%3D (http/1.1) {Network$LoggingInterceptor.intercept:366/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:346/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641/Thread.run:919}
2020-11-06 14:56:43.107 30829-30892/cgeo.geocaching D/cgeo: [network--4] OC returning 0 caches from search by viewport {OCApiLiveConnector.searchByViewport:65/ConnectorFactory.lambda$searchByViewport$0:346/-$$Lambda$ConnectorFactory$xlYIDnOeDkjd0u5VT0oIRtPq6Zk.apply:4/SearchResult.lambda$null$0:327/-$$Lambda$SearchResult$S4Ub23vsnqWr5X8nr-1svPn50lg.call:4/MaybeFromCallable.subscribeActual:47/Maybe.subscribe:5317/MaybeSubscribeOn$SubscribeTask.run:54/ScheduledDirectTask.call:41/ScheduledDirectTask.call:28}
2020-11-06 14:56:43.152 30829-30898/cgeo.geocaching D/cgeo: [OkHttp] 200 (122 ms) GET https://geocaching.su/api/list.php?maxlat=48.484266&maxlng=11.599252&minlat=48.455274&minlng=11.573968&oauth_consumer_key=b32876bd62c0b0841005cf6e4e6f38e10583547c7&oauth_nonce=825fbd1c7db71f960df501658faaa2fa&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1604671003&oauth_token=03ffe9c2134584b3a82413e4863c8f1505f6d8b55&oauth_version=1.0&oauth_signature=qbxEHhbdNfgDYROfa1KUR0EWu5g%3D (h2) {Network$LoggingInterceptor.intercept:366/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:346/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641/Thread.run:919}
2020-11-06 14:56:43.608 30829-31626/cgeo.geocaching D/cgeo: [OkHttp] 429 [] (594 ms) GET https://www.geocaching.com/api/proxy/web/search?box=48.484266%2C11.573968%2C48.455274%2C11.599252&take=500&asc=true&skip=0&sort=distance&origin=48.46977%2C11.58661&app=cgeo (http/1.1) {Network$LoggingInterceptor.intercept:368/RealInterceptorChain.proceed:109/Network$HeadersInterceptor.intercept:346/RealInterceptorChain.proceed:109/RealCall.getResponseWithInterceptorChain$okhttp:201/RealCall$AsyncCall.run:517/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641/Thread.run:919}
2020-11-06 14:56:43.609 30829-31052/cgeo.geocaching W/cgeo: [network--10] parallelCombineActive: swallowing error from connector cgeo.geocaching.connector.gc.GCConnector@f55cfdd {SearchResult.lambda$null$0:329/-$$Lambda$SearchResult$S4Ub23vsnqWr5X8nr-1svPn50lg.call:4/MaybeFromCallable.subscribeActual:47/Maybe.subscribe:5317/MaybeSubscribeOn$SubscribeTask.run:54/ScheduledDirectTask.call:41/ScheduledDirectTask.call:28/FutureTask.run:266/ThreadPoolExecutor.runWorker:1167/ThreadPoolExecutor$Worker.run:641}
    java.lang.RuntimeException: java.io.IOException: request was not successful: Response{protocol=http/1.1, code=429, message=, url=https://www.geocaching.com/api/proxy/web/search?box=48.484266%2C11.573968%2C48.455274%2C11.599252&take=500&asc=true&skip=0&sort=distance&origin=48.46977%2C11.58661&app=cgeo}
        at io.reactivex.rxjava3.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
        at io.reactivex.rxjava3.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:94)
        at io.reactivex.rxjava3.core.Single.blockingGet(Single.java:3645)
        at cgeo.geocaching.connector.gc.GCWebAPI.searchMap(GCWebAPI.java:414)
        at cgeo.geocaching.connector.gc.GCMap.searchPlayMapByViewport(GCMap.java:133)
        at cgeo.geocaching.connector.gc.GCMap.searchByViewport(GCMap.java:105)
        at cgeo.geocaching.connector.gc.GCConnector.searchByViewport(GCConnector.java:261)
        at cgeo.geocaching.connector.ConnectorFactory.lambda$searchByViewport$0(ConnectorFactory.java:346)
        at cgeo.geocaching.connector.-$$Lambda$ConnectorFactory$xlYIDnOeDkjd0u5VT0oIRtPq6Zk.apply(Unknown Source:4)
        at cgeo.geocaching.SearchResult.lambda$null$0(SearchResult.java:327)
        at cgeo.geocaching.-$$Lambda$SearchResult$S4Ub23vsnqWr5X8nr-1svPn50lg.call(Unknown Source:4)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeFromCallable.subscribeActual(MaybeFromCallable.java:47)
        at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5317)
        at io.reactivex.rxjava3.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:41)
        at io.reactivex.rxjava3.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: request was not successful: Response{protocol=http/1.1, code=429, message=, url=https://www.geocaching.com/api/proxy/web/search?box=48.484266%2C11.573968%2C48.455274%2C11.599252&take=500&asc=true&skip=0&sort=distance&origin=48.46977%2C11.58661&app=cgeo}
        at cgeo.geocaching.network.Network.lambda$static$6(Network.java:621)
        at cgeo.geocaching.network.-$$Lambda$Network$S1n6XPPgWcknnAjXJlYG-giT7W4.apply(Unknown Source:2)
        at io.reactivex.rxjava3.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:77)
        at io.reactivex.rxjava3.internal.operators.single.SingleCreate$Emitter.onSuccess(SingleCreate.java:68)
        at cgeo.geocaching.utils.RxOkHttpUtils$1.onResponse(RxOkHttpUtils.java:48)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
2020-11-06 14:56:43.610 30829-31082/cgeo.geocaching D/cgeo: [RxNewThreadScheduler-3] Filtering out 0 caches: [] {LiveCachesOverlay.download:115/LiveCachesOverlay.access$100:28/LiveCachesOverlay$LoadTimerAction.run:85/Scheduler$PeriodicDirectTask.run:566/Scheduler$Worker$PeriodicTask.run:513/ScheduledRunnable.run:65/ScheduledRunnable.call:56/FutureTask.run:266/ScheduledThreadPoolExecutor$ScheduledFutureTask.run:301/ThreadPoolExecutor.runWorker:1167}
```

Note: this issue as created after discussion in #8682

**Comment by fm-sys** [comment]
A 10s-20s minimum delay between requests would be ok for GPS tracking (because many requests need to be done over a long time), but not for manual movements. For second, users want to see a quick response. 

So if we want to fix this issue we need to distinguish if `followMyLocation` is activated. The `NewMap` instance is available inside the `LiveCachesOverlay`, so we can check the value of the `followMyLocation` filed from `NewMap`

**Comment by eddiemuc** [comment]
Since now we are not talking release any more for this one, we can think of more elaborate solutions for this than simply wait 10s on movement. I have different ideas:

* Idea 1: react upon actually received HTTP429: take a break for all requests to gc.com e.g. for 20s as soon as we get a HTTP429 and display a warning to user during that time
* Idea 2: differentiate between "movement time" and "staying-still-time". Introduce a flag "currentlyMoving" in the cycle which is false when during last e.g. 4 cycles (=1s) neither viewport nor zoom level has changed, true otherwise (viewport changes within GPS tolerance e.g. +/-30m are still considered "not moved"). Only when "currentlyMoving" is true, we restrict any update to max. 1 per 10s. When "currentlyMOving" is false, all updates are done immediately (that way, if the user moves manually quickly back and forth or zooms in and out without pause, updates are "restricted" and as soon as user stops doing that the update is actually triggered)

**Comment by fm-sys** [comment]
Idea 2 sounds good 👍

**Comment by geocachermgo** [comment]
If there is a update limitation, will this also help for  #9027?

**Comment by eddiemuc** [comment]
> If there is a update limitation, will this also help for #9027?

Hm I am not completely sure, but I think this is something different

**Comment by Lineflyer** [comment]
I did a short test today by simulating a north to south movement, looking at the debug log in parallel.
I used the current release version 2020.11.03 with GMaps.

There seems to be a problem, that the caching mechanism implemented by @moving-bits some months ago does (no longer?) work as intended. At least this would be my interpretation of looking at the debug log.

I did not in detail check the viewports of each movement and the viewports requested from server, still something IMHO unexpected can be seen:
- I start the live map and its populated via request from server
- After concurrent movements I do see further map updates with `cached=true`, which means the caching mechanism calculated, that the moved viewport is still within the original viewport requested from server (and some other conditions as added by @moving-bits )
- After the viewport has moved even further, I do see a new server request and the debug message containing `cached=false`

- This looks normal  until that point, but after that first new request from server I do never again see a `cached=true` on further movement but only server requests with `cached=false`. I would have expected a caching behavior similar to the initial phase

So without looking deeper I would suspect that either the viewport calculation for the requests towards the server and/or the caching mechanism might have a bug here. 
It could however also be the case, that I am totally wrong as e.g. the caching was set to `false` as the last online request returned maximum results in which case AFAIR we consider a high potential for even more caches in viewport and do subsequent requests on viewport changes.

@moving-bits Could you test if your cachign mechanism works OK with 2020.11.03 on GMaps? I can also try to repeat the test and provide the debug log (if you can read something from it).

**Comment by eddiemuc** [comment]
@Lineflyer if I understand you correctly, then you assume that there should already be a caching mechanism in place preventing tooany server calls, and you fear that this mechanism may be broken somehow. Is my understanding correct?

**Comment by Lineflyer** [comment]
@eddiemuc Correct. AFAIR @moving-bits implemented a method like this:
- Request a viewport from server which is x-times bigger than shown viewport 
- If the request returns less than max. caches, consider the whole bigger viewport as cached and do not request from server while user moves within this bigger viewport.
- There was also some fine tuning involved for edge cases...dont remember.

There should be an older closed issue dealing with server load, where this was developed and discussed. Or @moving-bits can enlighten us about the working mode.

**Comment by Lineflyer** [comment]
See #8225 and #8260

**Comment by moving-bits** [comment]
> Or @moving-bits can enlighten us about the working mode.

The description is pretty accurate, thanks @Lineflyer.

The "magic" happens in `maps/mapsforge/v6/LiveCachesOverlay:download()` and `maps/CGeoMap:doDownloadRun()`.

If you activate debug mode in c:geo, you'll see a red bounding box around the new viewport (GM only).

**Comment by Lineflyer** [comment]
@moving-bits 
Any chance you could take a look whether there is a bug in here preventing from further "caching magic" after the map got moved?
If there is such a bug we should include a fix into the next beta...

**Comment by moving-bits** [comment]
> @moving-bits
> Any chance you could take a look whether there is a bug in here preventing from further "caching magic" after the map got moved?
> If there is such a bug we should include a fix into the next beta...

I'll try to look into it over the weekend.

**Comment by moving-bits** [comment]
I've debugged into it and the original caching mechanism introduced by the above mentioned PR is still in place. Relevant code sequence is like this:

```
final boolean useLastSearchResult = null != lastSearchResult && null != lastViewport && lastViewport.includes(mapView.getViewport());
final Viewport newViewport = mapView.getViewport().resize(3.0);
final SearchResult searchResult = useLastSearchResult ? lastSearchResult : ConnectorFactory.searchByViewport(newViewport);
downloaded = true;

final Set<Geocache> result = searchResult.getCachesFromSearchResult(LoadFlags.LOAD_CACHE_OR_DB);

[...]

lastSearchResult = searchResult;
if (null == lastViewport || (!caches.isEmpty() && lastSearchResult.getCount() > 400)) {
    lastViewport = containingGCliveCaches(caches.getAsList());
    if (Settings.isDebug() && overlayPositionAndScale instanceof GooglePositionAndHistory) {
        ((GooglePositionAndHistory) overlayPositionAndScale).drawViewport(lastViewport);
    }
}
Log.d("searchByViewport: cached=" + useLastSearchResult + ", results=" + lastSearchResult.getCount() + ", viewport=" + lastViewport);
```

From playing around with it a bit caching still works. - But only as long as you stay within or return to the area the first cached data comes from... So the culprit seems to be that the cached viewport does not get updated if a new request to the server was needed.

I'll create a PR for testing which changes
`if (null == lastViewport || (!caches.isEmpty() && lastSearchResult.getCount() > 400)) {` to 
`if (null == lastViewport || !useLastSearchResult || (!caches.isEmpty() && lastSearchResult.getCount() > 400)) {`

(and similar for `LiveCachesOverlay`).

**Comment by Lineflyer** [comment]
The fix seems to work pretty well, see comments in PR #9378 
I think this will fix this issue most of the time unless the user uses rather low zoom or scrolls a lot. But for such cases IMHO the server throttling is meaningful. The only thing we could (re)introduce for such cases is a out-zoom limit, but lets refrain from that for now.
