### ISSUE TITLE
crash when adding current position WP to not offline stored caches 

### ISSUE THREAD

**Issue by geocachermgo** [cgeo/cgeo#9463]
**Describe the bug:**
crash when adding current position as WP to an not saved geocache

**To Reproduce:**
1. Search for GC40N20 or other GC number (w or w/o waypoints)
2. Swipe left to WP page
3. Click on Add current position

**Actual behavior/state after performing these steps:**
c:geo closes

**Expected behavior/state after performing these steps:**
WP with current postion is created

**Version of c:geo used:**
2020.11.30-NB-5108dbf

**Is the problem reproducible:**
Yes

**Additional context:**
If cache is stored, no crash, but WP is created.
Logfile sent to support

**Comment by Lineflyer** [comment]
@geocachermgo 
Shall the logfile be kept confidential (I would pass it around to devs via mail) or can I attach it here?

**Comment by geocachermgo** [comment]
I did a coarse check and the nick is in the log, but no password nor position. If this is correct you can add it here. Is this also true for the extended log?

**Comment by Lineflyer** [comment]
I took out the crash part only for now:

```
--------- beginning of crash
11-19 23:40:23.644  9488 10291 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
11-19 23:40:23.644  9488 10291 E AndroidRuntime: Process: cgeo.geocaching, PID: 9488
11-19 23:40:23.644  9488 10291 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: Caused by: java.lang.RuntimeException: Can't create handler inside thread Thread[AsyncTask #1,5,main] that has not called Looper.prepare()
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at android.os.Handler.<init>(Handler.java:207)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at android.os.Handler.<init>(Handler.java:119)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at cgeo.geocaching.utils.SimpleHandler.<init>(SimpleHandler.java:16)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity$ChangeNotificationHandler.<init>(CacheDetailActivity.java:2548)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity.notifyDataSetChanged(CacheDetailActivity.java:886)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity.ensureSaved(CacheDetailActivity.java:1859)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity.access$4500(CacheDetailActivity.java:183)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator$3.doInBackground(CacheDetailActivity.java:1951)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator$3.doInBackground(CacheDetailActivity.java:1947)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-19 23:40:23.644  9488 10291 E AndroidRuntime: 	... 4 more
11-19 23:40:33.234 12171 12247 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
11-19 23:40:33.234 12171 12247 E AndroidRuntime: Process: cgeo.geocaching, PID: 12171
11-19 23:40:33.234 12171 12247 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: Caused by: java.lang.RuntimeException: Can't create handler inside thread Thread[AsyncTask #1,5,main] that has not called Looper.prepare()
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at android.os.Handler.<init>(Handler.java:207)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at android.os.Handler.<init>(Handler.java:119)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at cgeo.geocaching.utils.SimpleHandler.<init>(SimpleHandler.java:16)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity$ChangeNotificationHandler.<init>(CacheDetailActivity.java:2548)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity.notifyDataSetChanged(CacheDetailActivity.java:886)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity.ensureSaved(CacheDetailActivity.java:1859)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity.access$4500(CacheDetailActivity.java:183)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator$3.doInBackground(CacheDetailActivity.java:1951)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at cgeo.geocaching.CacheDetailActivity$WaypointsViewCreator$3.doInBackground(CacheDetailActivity.java:1947)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11-19 23:40:33.234 12171 12247 E AndroidRuntime: 	... 4 more
```

**Comment by geocachermgo** [comment]
Still there with current nightly. @MagpieFourtyTwo could you reproduce

**Comment by Lineflyer** [comment]
I can reproduce.

**Comment by MagpieFourtyTwo** [comment]
Same over here.

Nevertheless, "To Reproduce" and poss. even subject should be changed, IMO,
cause it happens to caches only which are *not* stored offline.
What I would not consider as "Additional Context", but as fundamental prerequisite.  ;)

Most regretfully can't tell for how long this bug already exists, cause I never use this function.
As the resulting WPs are usually way to imprecise, I use [Add Waypoint] instead and click [My coordinates] multiple times, until the signal stops jumping around ...

Note to self: Perhaps the [Add current location] button may be changed to the perhaps some day implemented WP averaging ...?

**Comment by geocachermgo** [comment]
Allready there with 2020.11.14-RC

**Comment by geocachermgo** [comment]
No crash, but cache is stored in "Standardliste".
Thank for the fix!

**Comment by MagpieFourtyTwo** [comment]
In order to store additional stuff, it has to go somewhere ...
And ``Stored`` is the normal place to put it into.
So what do you think is wrong with that?

**Comment by geocachermgo** [comment]
In principal I do not want the cache to be stored unless I press "store". On the other hand I want the waypoint to be stored (which is not possible w/o the cache being stored). So creating a waypoint leads inevitably to storing the cache. So nothing is wrong with the solution but it has this side effect.

**Comment by Lineflyer** [comment]
It was like that also before. As soon as you add custom information to a cache it will be stored. Years ago this was not the case leading to losing information after 72h.
The only active change here is, that it now works as before the regression occurred.

**Comment by MagpieFourtyTwo** [comment]
It's the very same with personal notes ...

**Comment by moving-bits** [comment]
> It's the very same with personal notes ...

You mean "unsaved cache gets saved on editing a personal note" or "unsaved cache leads to crash on editing a personal note"?

**Comment by MagpieFourtyTwo** [comment]
The first: Unsaved cache gets saved on clicking the [Edit PN] button.
