### ISSUE TITLE
Live Map crashes 

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9493]
**Describe the bug:**
Today the OSM live map crashed about 5 times with following exception. I would guess this is a regression as I never noticed it before... 

```
FATAL EXCEPTION: main
Process: cgeo.geocaching, PID: 12120
java.lang.IllegalStateException: layer already assigned
	at org.mapsforge.map.layer.Layer.assign(Layer.java:172)
	at org.mapsforge.map.layer.Layers.add(Layers.java:88)
	at org.mapsforge.map.layer.Layers.add(Layers.java:73)
	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.switchCircles(AbstractCachesOverlay.java:127)
	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.switchCircles(CachesBundle.java:281)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.onMapSettingsPopupFinished(NewMap.java:456)
	at cgeo.geocaching.maps.mapsforge.v6.NewMap.lambda$J0MyIITAKy7vcf9Q7vCS5j2YtgE(Unknown Source:0)
	at cgeo.geocaching.maps.mapsforge.v6.-$$Lambda$NewMap$J0MyIITAKy7vcf9Q7vCS5j2YtgE.run(Unknown Source:2)
	at cgeo.geocaching.maps.MapSettingsUtils.lambda$showSettingsPopup$0(MapSettingsUtils.java:78)
	at cgeo.geocaching.maps.-$$Lambda$MapSettingsUtils$JTmmRsB8m0fRgBuoWfuoJawB4ZA.onDismiss(Unknown Source:8)
	at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1575)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:213)
	at android.app.ActivityThread.main(ActivityThread.java:8178)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Comment by moving-bits** [comment]
Is this with release version or a nightly?

**Comment by rsudev** [comment]
Did this happen right when opening or in response to some action?

**Comment by rsudev** [comment]
Ah, I see - MapSettingsPopup...

**Comment by moving-bits** [comment]
@rsudev
In #9490 I moved the line `caches.switchCircles()` from `onOptionItemsSelected()` to the new `onMapSettingsPopupFinished()` being called on leaving the new popup by either pressing the back button or tapping somewhere on the map.

**Comment by fm-sys** [comment]
> Is this with release version or a nightly?

Sorry, I forgot to mention the c:geo version. It's 2020.12.05-NB of course. Would be bad if I couldn't test our newest features in real-life ;-)

**Comment by fm-sys** [comment]
Steps to reproduce:

1. Make sure show circles is activated 
2. Open map settings pop-up 
3. Double tab  "show circles" (disable, re-enable) 
4. Close map settings pop-up
5. Crash! 

But IIRC it was also happening in other situations...

**Comment by MagpieFourtyTwo** [comment]
Same while trying to change routing strategy - see #9500 which may be considered as duplicate ...?

**Comment by moving-bits** [comment]
After lots of debugging... Looks like `switchCircles()` _must not_ be called if circle setting is unchanged. Added a flag for this with PR #9501.

**Comment by MagpieFourtyTwo** [comment]
Just tested with the debug-apk: No crash anymore, no matter which state for "show circles" is set.

Thx a lot!

**Comment by MagpieFourtyTwo** [comment]
BTW: Used the debug-apk-version for the rest of the afternoon - and it seemed to eat battery like crazy.
Was that deceptive or is the little canary really *that* voracious?

**Comment by moving-bits** [comment]
might very well be, as LeakCanary analyzes each and every step to watch for leakages etc. - but haven't tried to compare, so cannot really say.
