### ISSUE TITLE
Crash on starting navigation

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9508]
While debugging for #9463 I've stumbled upon another crash:

```
2020-12-06 19:39:04.706 12267-12267/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 12267
    java.lang.NumberFormatException: For input string: "cgeo.geocaching.maps.google.v2.GoogleMapProvider$GoogleMapSource"
        at java.lang.Integer.parseInt(Integer.java:615)
        at java.lang.Integer.parseInt(Integer.java:650)
        at cgeo.geocaching.settings.Settings.getConvertedMapId(Settings.java:983)
        at cgeo.geocaching.settings.Settings.getMapSource(Settings.java:960)
        at cgeo.geocaching.settings.Settings.getMapProvider(Settings.java:587)
        at cgeo.geocaching.apps.navi.InternalMap.navigate(InternalMap.java:46)
        at cgeo.geocaching.apps.navi.NavigationSelectionActionProvider.lambda$onPrepareSubMenu$0(NavigationSelectionActionProvider.java:45)
        at cgeo.geocaching.apps.navi.NavigationSelectionActionProvider.lambda$onPrepareSubMenu$0$NavigationSelectionActionProvider(Unknown Source:0)
        at cgeo.geocaching.apps.navi.-$$Lambda$NavigationSelectionActionProvider$l2m28m9JSRNOj6T5Evk69_6mABk.onMenuItemClick(Unknown Source:4)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:154)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:985)
        at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
        at android.widget.AdapterView.performItemClick(AdapterView.java:330)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1190)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3198)
        at android.widget.AbsListView$3.run(AbsListView.java:4116)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

Steps to reproduce:
- open a cache from cache list
- select "navigate => map" from action bar
- c:geo crashes and returns to cache list

**Comment by MagpieFourtyTwo** [comment]
WFM

**Comment by eddiemuc** [comment]
@moving-bits this can happen as a result of switching back and forth between release and master c:geo version on same device (since release is using integers for storing last map w/o any safeguard and master is using strings). It should not happen in other situations.

If this is a problem for development we can introduce some developer-safeguard in release.

**Comment by moving-bits** [comment]
@eddiemuc 
Thanks for the clarification. Since you'd added the safeguards for db upgrade/downgrade some time ago I'm so used to being able to switch between release and master that it did not cross my mind this being the culprit here.
No need to add an extra safeguard, IMHO, as it's a temporary problem, therefore closing the issue.
