### ISSUE TITLE
NPE on editing PN for GoTo UDC

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9710]
Found by Google Play automated devices tests and reproducible for me:

- Start c:geo
- Select "Go to"
- Select Menu - Personal Note
- Enter some note text
- Press OK (Tick mark)

```
FATAL EXCEPTION: Thread-1917
Process: cgeo.geocaching, PID: 947
java.lang.NullPointerException: Attempt to invoke interface method 'void cgeo.geocaching.activity.AbstractViewPagerActivity$PageViewCreator.notifyDataSetChanged()' on a null object reference
	at cgeo.geocaching.activity.AbstractViewPagerActivity.reinitializePage(AbstractViewPagerActivity.java:270)
	at cgeo.geocaching.CacheDetailActivity.setNewPersonalNote(CacheDetailActivity.java:2630)
	at cgeo.geocaching.CacheDetailActivity.onFinishEditNoteDialog(CacheDetailActivity.java:2558)
	at cgeo.geocaching.ui.EditNoteDialog.lambda$onCreateDialog$1(EditNoteDialog.java:91)
	at cgeo.geocaching.ui.EditNoteDialog.lambda$onCreateDialog$1$EditNoteDialog(EditNoteDialog.java)
	at cgeo.geocaching.ui.-$$Lambda$EditNoteDialog$21Wqj5hcRhEKvTHNPBOthYPs7Cw.onClick(lambda)
	at android.view.View.performClick(View.java:4766)
	at android.view.View$PerformClick.run(View.java:19683)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:11)
	at androidx.test.espresso.base.UiControllerImpl.n(UiControllerImpl.java:6)
	at androidx.test.espresso.base.UiControllerImpl.m(UiControllerImpl.java:1)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:6)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:15)
	at androidx.test.espresso.action.Tap.b(Tap.java)
	at androidx.test.espresso.action.Tap$1.sendTap(Tap.java:1)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:4)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:4)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5538)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by moving-bits** [comment]
Do we need to have a PN for GoTo UDC?

**Comment by Lineflyer** [comment]
Not really IMHO. I cannot judge whether we should either repair or remove it.

**Comment by moving-bits** [comment]
Probably both. Disable some of the regular cache functions not needed in the "goto" menu (eg.: text output), and add a check for notifyDatasetChanged whether the requested view exists at all.

**Comment by eddiemuc** [comment]
PR #9714 fixes the second part (adds nullpointerexception check guards)

**Comment by moving-bits** [comment]
PR #9718 takes care of the menu entries
