### ISSUE TITLE
IllegalArgumentException on zoomToViewport in NewMap (new in latest RC)

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9738]
Checked the error status in Play Console this morning for our latest release candidate (2021.01.05-RC). Situation is mostly fine, but there is one error marked as "new in current beta 2021.01.05-RC". It has 10 occurrences yet, and is the error with highest frequency if I filter on current RC only.

Crash in `zoomToViewport` in NewMap in this line:
`getModel().mapViewPosition.setCenter(new LatLong(viewport.getCenter().getLatitude(), viewport.getCenter().getLongitude()));`

Mapsforge validates the given `LatLong` and throws the exception.

While we can easily catch that exception and continue without setting the new center, I do not understand what change suddenly leads to that invalid viewport coordinates.

Full error info is like this:
```
java.lang.IllegalArgumentException: 
  at org.mapsforge.core.util.LatLongUtils.validateLatitude (LatLongUtils.java:305)
  at org.mapsforge.core.model.LatLong.<init> (LatLong.java:52)
  at cgeo.geocaching.maps.mapsforge.v6.MfMapView.zoomToViewport (MfMapView.java:123)
  at cgeo.geocaching.maps.mapsforge.v6.NewMap.lambda$postZoomToViewport$2 (NewMap.java:333)
  at cgeo.geocaching.maps.mapsforge.v6.NewMap.lambda$postZoomToViewport$2$NewMap (Unknown Source)
  at cgeo.geocaching.maps.mapsforge.v6.-$$Lambda$NewMap$MESnzzfskHYh2Mzio2FZXY0mGyY.run (Unknown Source:4)
  at android.os.Handler.handleCallback (Handler.java:938)
  at android.os.Handler.dispatchMessage (Handler.java:99)
  at android.os.Looper.loop (Looper.java:246)
  at android.app.ActivityThread.main (ActivityThread.java:8414)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:596)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1130)
```

Does anyone have an idea what could cause this?

**Comment by Lineflyer** [comment]
It seems the user also contacted us:

Keeps crashing from either search for gc code or open cache via map mode. 

When I try to select map from within the cache, it crashes pretty much every time.

```
--- System information ---
Device: SM-G986B (y2sxxx, samsung)
Android version: 11
Android build: RP1A.200720.012.G986BXXU5CTKG
c:geo version: 2021.01.06-RC1
Google Play services: enabled - 20.47.14 (150400-349456378)
Low power mode: inactive
Compass capabilities: yes
Rotation vector sensor: present
Orientation sensor: present
Magnetometer & Accelerometer sensor: present
Direction sensor used: rotation vector
Hide caches: -
Hide waypoints: parking visited
HW acceleration: enabled (default state)
System language: en_AU / user-defined language: en
System date format: d/M/yy
Debug mode active: no
System internal c:geo dir: /data/user/0/cgeo.geocaching (73.3 GB free) internal
User storage c:geo dir: /storage/emulated/0/cgeo (73.3 GB free) external non-removable
Geocache data: /storage/0788-8FD5/Android/data/cgeo.geocaching/files/GeocacheData (72.2 GB free) external removable
Database: /storage/emulated/0/Android/data/cgeo.geocaching/files/databases/data (173.7 MB) on user storage
Last backup: 27 Jul 2020, 6:13 pm
GPX import path: /storage/emulated/0/cgeo/gpx
GPX export path: /storage/emulated/0/cgeo/gpx
Offline maps path: /storage/0788-8FD5/Download/Maps
Map render theme path:
Live map mode: true
Global filter: display all caches
Sailfish OS detected: false
Fine location permission: granted
Write external storage permission: granted
Geocaching sites enabled:
   geocaching.com: Logged in (Login OK) / PREMIUM
Geocaching.com date format: dd/MMM/yyyy
Installed c:geo plugins:  none
BRouter connection available: false
--- End of system information ---
```

**Comment by moving-bits** [comment]
Anything special to the cache the user is searching for / opening on the map? Like having no coordinates?

**Comment by Lineflyer** [comment]
He also supplied his log, I will pass it around via mail rather than posting the file here (not sure if personal data contained).

I have seen this in there so far:
```
1-09 17:53:24.038  1471 17125 W cgeo    : [RxNewThreadScheduler-6] CachesOverlay.LoadTimer.run
01-09 17:53:24.038  1471 17125 W cgeo    : java.lang.IllegalArgumentException: invalid latitude: -180.0
01-09 17:53:24.038  1471 17125 W cgeo    : 	at org.mapsforge.core.util.LatLongUtils.validateLatitude(LatLongUtils.java:305)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at org.mapsforge.core.model.LatLong.<init>(LatLong.java:52)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.getWaypointItem(AbstractCachesOverlay.java:387)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.addItem(AbstractCachesOverlay.java:197)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.WaypointsOverlay.showWaypoints(WaypointsOverlay.java:70)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesBundle.handleWaypoints(CachesBundle.java:319)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.AbstractCachesOverlay.update(AbstractCachesOverlay.java:174)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesOverlay.display(CachesOverlay.java:92)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesOverlay.access$300(CachesOverlay.java:21)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at cgeo.geocaching.maps.mapsforge.v6.caches.CachesOverlay$LoadTimerAction.run(CachesOverlay.java:68)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at io.reactivex.rxjava3.core.Scheduler$PeriodicDirectTask.run(Scheduler.java:566)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at io.reactivex.rxjava3.core.Scheduler$Worker$PeriodicTask.run(Scheduler.java:513)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-09 17:53:24.038  1471 17125 W cgeo    : 	at java.lang.Thread.run(Thread.java:923)
```

**Comment by moving-bits** [comment]
Looks like an waypoint with invalid coordinates. Did the user state whether this is a waypoint coming from the original cache listing, is imported via one of our import functions or is user-created? (And if so, with what values?)

Can the user try to identify which waypoint is leading to the crash (if there are multiple waypoints), maybe by going to the cache's waypoint page and starting navigation for a single waypoint?

**Comment by Lineflyer** [comment]
He has a corrected coordinate as he said.
I asked him to check it and provide it to us.

**Comment by eddiemuc** [comment]
Just FYI: there is a second entry in the log for an invalid latitude bnut with another number:

```
01-09 17:53:24.077  1471  1471 E AndroidRuntime: java.lang.IllegalArgumentException: invalid latitude: -108.977373
01-09 17:53:24.077  1471  1471 E AndroidRuntime: 	at org.mapsforge.core.util.LatLongUtils.validateLatitude(LatLongUtils.java:305)
01-09 17:53:24.077  1471  1471 E AndroidRuntime: 	at org.mapsforge.core.model.LatLong.<init>(LatLong.java:52)
01-09 17:53:24.077  1471  1471 E AndroidRuntime: 	at cgeo.geocaching.maps.mapsforge.v6.MfMapView.zoomToViewport(MfMapView.java:123)

```

**Comment by Lineflyer** [comment]
The user stated it is GC8KB41 causing it and stated it was indeed a invalid coordinate.
I asked him about the exact coordinate (what showed up in c:geo) and the source of it (self created, imported corrected coords, etc.).

I wonder how he managed to set an invalid coordinate after all.

**Comment by Lineflyer** [comment]
Feedback from the user:
It was caused by a waypoint auto-parsed from the personal note. Sadly he deleted the personal note to get rid of the coordinate, so he cannot tell us the the content anymore.

IMHO we should safeguard to remove invalid coordinates before opening the map for it or (even better) to ensure coordinates from the parsed note are not created when invalid.

**Comment by moving-bits** [comment]
Thanks for clarifying. I'll look into it and provide a safeguard. Will additionally try to reproduce and adapt the waypoints from note parsing.

**Comment by moving-bits** [comment]
As part 1 - adding safeguard in map painting - is added with #9738, I changed the issue title to point to part 2 - add safeguard to "waypoint from note" routines to skip waypoints with invalid coordinates. (IIRC we need to accept empty, though, but I'm not sure.)
