### ISSUE TITLE
c:geo crashed when starting map

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9789]
Two mails on support today:
- 2021.01.10
- Staring live map crashed c:geo
- Invoking map navigation from cache details crash c:geo

Delivered logfiles show:
```
--------- beginning of crash
01-10 19:30:57.081  6115  6863 E AndroidRuntime: FATAL EXCEPTION: LayerManager
01-10 19:30:57.081  6115  6863 E AndroidRuntime: Process: cgeo.geocaching, PID: 6115
01-10 19:30:57.081  6115  6863 E AndroidRuntime: java.lang.IllegalArgumentException: invalid tileX number on zoom level 32: 2147483647
01-10 19:30:57.081  6115  6863 E AndroidRuntime: 	at org.mapsforge.core.model.Tile.<init>(Tile.java:130)
01-10 19:30:57.081  6115  6863 E AndroidRuntime: 	at org.mapsforge.map.util.LayerUtil.getTilePositions(LayerUtil.java:49)
01-10 19:30:57.081  6115  6863 E AndroidRuntime: 	at org.mapsforge.map.layer.TileLayer.draw(TileLayer.java:72)
01-10 19:30:57.081  6115  6863 E AndroidRuntime: 	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
01-10 19:30:57.081  6115  6863 E AndroidRuntime: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
01-10 19:33:18.228 18529 18598 E AndroidRuntime: FATAL EXCEPTION: LayerManager
01-10 19:33:18.228 18529 18598 E AndroidRuntime: Process: cgeo.geocaching, PID: 18529
01-10 19:33:18.228 18529 18598 E AndroidRuntime: java.lang.IllegalArgumentException: invalid tileX number on zoom level 32: 2147483647
01-10 19:33:18.228 18529 18598 E AndroidRuntime: 	at org.mapsforge.core.model.Tile.<init>(Tile.java:130)
01-10 19:33:18.228 18529 18598 E AndroidRuntime: 	at org.mapsforge.map.util.LayerUtil.getTilePositions(LayerUtil.java:49)
01-10 19:33:18.228 18529 18598 E AndroidRuntime: 	at org.mapsforge.map.layer.TileLayer.draw(TileLayer.java:72)
01-10 19:33:18.228 18529 18598 E AndroidRuntime: 	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
01-10 19:33:18.228 18529 18598 E AndroidRuntime: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
01-10 19:38:11.069 18665 19301 E AndroidRuntime: FATAL EXCEPTION: LayerManager
01-10 19:38:11.069 18665 19301 E AndroidRuntime: Process: cgeo.geocaching, PID: 18665
01-10 19:38:11.069 18665 19301 E AndroidRuntime: java.lang.IllegalArgumentException: invalid tileX number on zoom level 32: 2147483647
01-10 19:38:11.069 18665 19301 E AndroidRuntime: 	at org.mapsforge.core.model.Tile.<init>(Tile.java:130)
01-10 19:38:11.069 18665 19301 E AndroidRuntime: 	at org.mapsforge.map.util.LayerUtil.getTilePositions(LayerUtil.java:49)
01-10 19:38:11.069 18665 19301 E AndroidRuntime: 	at org.mapsforge.map.layer.TileLayer.draw(TileLayer.java:72)
01-10 19:38:11.069 18665 19301 E AndroidRuntime: 	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
01-10 19:38:11.069 18665 19301 E AndroidRuntime: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
01-10 19:38:24.130 19337 19394 E AndroidRuntime: FATAL EXCEPTION: LayerManager
01-10 19:38:24.130 19337 19394 E AndroidRuntime: Process: cgeo.geocaching, PID: 19337
01-10 19:38:24.130 19337 19394 E AndroidRuntime: java.lang.IllegalArgumentException: invalid tileX number on zoom level 32: 2147483647
01-10 19:38:24.130 19337 19394 E AndroidRuntime: 	at org.mapsforge.core.model.Tile.<init>(Tile.java:130)
01-10 19:38:24.130 19337 19394 E AndroidRuntime: 	at org.mapsforge.map.util.LayerUtil.getTilePositions(LayerUtil.java:49)
01-10 19:38:24.130 19337 19394 E AndroidRuntime: 	at org.mapsforge.map.layer.TileLayer.draw(TileLayer.java:72)
01-10 19:38:24.130 19337 19394 E AndroidRuntime: 	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
01-10 19:38:24.130 19337 19394 E AndroidRuntime: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
01-10 21:01:03.390 25112 25185 E AndroidRuntime: FATAL EXCEPTION: LayerManager
01-10 21:01:03.390 25112 25185 E AndroidRuntime: Process: cgeo.geocaching, PID: 25112
01-10 21:01:03.390 25112 25185 E AndroidRuntime: java.lang.IllegalArgumentException: invalid tileX number on zoom level 32: 2147483647
01-10 21:01:03.390 25112 25185 E AndroidRuntime: 	at org.mapsforge.core.model.Tile.<init>(Tile.java:130)
01-10 21:01:03.390 25112 25185 E AndroidRuntime: 	at org.mapsforge.map.util.LayerUtil.getTilePositions(LayerUtil.java:49)
01-10 21:01:03.390 25112 25185 E AndroidRuntime: 	at org.mapsforge.map.layer.TileLayer.draw(TileLayer.java:72)
01-10 21:01:03.390 25112 25185 E AndroidRuntime: 	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
01-10 21:01:03.390 25112 25185 E AndroidRuntime: 	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
--------- beginning of main
```

One user confirmed, that the problem is gone if he changes the map to Google via c:geo Menu - Settings - Map.
I asked him, whether the problem occurs again once he reverts back to a OSM based map.

**Comment by Lineflyer** [comment]
> One user confirmed, that the problem is gone if he changes the map to Google via c:geo Menu - Settings - Map.
I asked him, whether the problem occurs again once he reverts back to a OSM based map.

The user told, that the problem did not occur again after reverting back to his normal OSM map (for now),

**Comment by moving-bits** [comment]
Looks like somehow a too high zoom level was reached (for whatever reason). But with the recent fixes to map zoom level this shouldn't be possible any longer by manually zooming (#9801), and even if someone forces it using settings => system => view settings or if it happens due to some technical problem, it should not cause any harm any longer (as long as min/max level are set correctly for offline or online map), as the new PR #9810 enforces those limits, even if current value exceeds them. So I propose closing this issue.

**Comment by fm-sys** [comment]
If it will be fixed implicitly, we can close this issue...

**Comment by Lineflyer** [comment]
Lets close and monitor, whether it shows up again.
