### ISSUE TITLE
Crash when starting live map

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9821]
**Describe the bug:**
Crash with latest nightly when starting live map

**Log:**
```
E/AndroidRuntime: FATAL EXCEPTION: LayerManager
    Process: cgeo.geocaching, PID: 10439
    java.lang.IllegalArgumentException: invalid radius: -2147463.8
        at org.mapsforge.map.layer.overlay.Circle.setRadiusInternal(Circle.java:186)
        at org.mapsforge.map.layer.overlay.Circle.<init>(Circle.java:67)
        at org.mapsforge.map.layer.overlay.Circle.<init>(Circle.java:50)
        at cgeo.geocaching.maps.mapsforge.v6.layers.PositionLayer.draw(PositionLayer.java:58)
        at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:95)
        at org.mapsforge.map.util.PausableThread.run(PausableThread.java:149)
```

**Comment by fm-sys** [comment]
Fix was merged to `release` and `release` back to `master`. Close it manually, since the automatic closing seems to have failed again... Apparently the "closing word" must be included in the commit message (not only in the PR) when targeting release or github is just asleep 🙃
