### ISSUE TITLE
SAF: Crash on selecting "Downloads" when granting SAF access

### ISSUE THREAD

**Issue by moving-bits** [cgeo/cgeo#9903]
Taken from https://github.com/cgeo/cgeo/issues/9868#issuecomment-770183465 by @baiti:

For completeness, here is the FATAL ABORT for the Grant, do nothin scenario
`2021-01-30 10:25:05.079 12279-12279/cgeo.geocaching D/AndroidRuntime: Shutting down VM
2021-01-30 10:25:05.080 12279-12279/cgeo.geocaching E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 12279
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=59372, result=-1, data=Intent { dat=content://com.android.providers.downloads.documents/tree/downloads flg=0xc3 }} to activity {cgeo.geocaching/cgeo.geocaching.MainActivity}: java.lang.IllegalArgumentException: mimeType can't be null
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: mimeType can't be null
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.call(ContentProviderNative.java:658)
        at android.content.ContentResolver.call(ContentResolver.java:2042)
        at android.provider.DocumentsContract.createDocument(DocumentsContract.java:1327)
        at cgeo.geocaching.storage.DocumentContentAccessor.createInternal(DocumentContentAccessor.java:111)
        at cgeo.geocaching.storage.DocumentContentAccessor.create(DocumentContentAccessor.java:98)
        at cgeo.geocaching.storage.ContentStorage.create(ContentStorage.java:169)
        at cgeo.geocaching.storage.ContentStorage.tryTestReadWriteToFolder(ContentStorage.java:426)
        at cgeo.geocaching.storage.ContentStorage.ensureFolder(ContentStorage.java:133)
        at cgeo.geocaching.storage.ContentStorageActivityHelper.handleResultPersistableFolderSelection(ContentStorageActivityHelper.java:338)
        at cgeo.geocaching.storage.ContentStorageActivityHelper.onActivityResult(ContentStorageActivityHelper.java:210)
        at cgeo.geocaching.activity.AbstractActivity.onActivityResult(AbstractActivity.java:300)
        at cgeo.geocaching.MainActivity.onActivityResult(MainActivity.java:571)
        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
`

**Comment by eddiemuc** [comment]
I will check it out

**Comment by baiti** [comment]
"Downloads" was where I was taken by default. "cgeo" as a folder at the same level as Downloads existed at that time.

**Comment by eddiemuc** [comment]
OK, seems like when selecting "Download" folder via "Download Document Provider" it has problems with my mimeType-hack. 

When you choose the very same "Download" folder via the "internal storage document provider" it works for me.

If you don't know what a "document provider" is: those are the selection possibilities you have on the left-side menu in the systems folder choosing dialog. In the following screenshot there are three "document providers" I can select from named "Downloads", "Android SDK build-in" and "SD Card". "Android SDK buil-in" points to the "internal storage".

![image](https://user-images.githubusercontent.com/6909759/106353820-9c100980-62ed-11eb-83bf-6f63387f4baf.png)

Yes we will have lots of more fun with SAF... Will continue to investigate this

**Comment by eddiemuc** [comment]
Another fun fact: if you use "Downloads" document provider but select a subdir inside it (e.g. "cgeo") then it works.

**Comment by fm-sys** [comment]
Maybe we should create a subfolder "cgeo" inside the choosen directory, when the directory is not already called "cgeo". (for example when the user chooses documents or downloads as directory)

**Comment by Lineflyer** [comment]
> Maybe we should create a subfolder "cgeo" inside the choosen directory

I hate apps doing such things while previously stating to select the folder I want to use. This often ends up with things like `/storage/emulated/0/MyAppStorage/The_folder_I_created_for_this_app/The_unneccessary_folder_the_app_creates/*`

**Comment by Lineflyer** [comment]
Addition:
I think for this special type folder Documents things might be advised to handle different (i.e. indeed to create a subfolder). That might indeed be the reason why Downloads itself is not selectable, right?

**Comment by eddiemuc** [comment]
With the PR, Downloads will be selectable. It is just that the document provider for "Downloads" behaves differently from the ones I have tested before. It is more strict about mime types.

That reminds me: haven't tested the PR against APi21 yet, will to this immediately.
