### ISSUE TITLE
Crash when opening live map

### ISSUE THREAD

**Issue by fm-sys** [cgeo/cgeo#9915]
**Describe the bug:**
Don't know if it's already tracked somewhere, but this crash happened to me in the emulator. No Idea what causes this and after opening the live map again everything was fine...

Version: Latest master (2021.01.30-1424046 developer build)

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: cgeo.geocaching, PID: 8277
    java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
        at android.app.SharedPreferencesImpl.getString(SharedPreferencesImpl.java:288)
        at cgeo.geocaching.settings.Settings.getStringDirect(Settings.java:311)
        at cgeo.geocaching.settings.Settings.getString(Settings.java:307)
        at cgeo.geocaching.settings.Settings.getMapSource(Settings.java:929)
        at cgeo.geocaching.settings.Settings.getMapProvider(Settings.java:600)
        at cgeo.geocaching.maps.DefaultMap.getDefaultMapClass(DefaultMap.java:19)
        at cgeo.geocaching.maps.DefaultMap.getLiveMapIntent(DefaultMap.java:27)
        at cgeo.geocaching.MainActivity.cgeoFindOnMap(MainActivity.java:736)
        at cgeo.geocaching.-$$Lambda$JZP-rTqVaK4wqIQ2XBHeLI-Ss6c.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7125)
        at android.view.View.performClickInternal(View.java:7102)
        at android.view.View.access$3500(View.java:801)
        at android.view.View$PerformClick.run(View.java:27336)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Comment by moving-bits** [comment]
@fm-sys 
Did it happen ever again? Or can we close the issue?

**Comment by fm-sys** [comment]
No, so let's close. No idea what was wrong with shared preferences at this point 🤷‍♂️
