### ISSUE TITLE
Crash when trying to log PM-only cache as BM

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9974]
Found in 2021.02,07-NB, Google Pixel 3a, Android 11:

- Use c:geo as BM
- Perform nearby search 
- Select an unsaved PM-only cache from the result list
- c:geo will report correctly, that you cannot view it as it is a PM-only cache and offers to post a log instead
- Select "Log Visit"

Result:
Crash in background and c:geo returning to nearby result but showing 20 caches in Paris/France.

Expected result:
Be able to log the PM-only cache

```
02-07 12:12:12.505  2933  2933 E AndroidRuntime: FATAL EXCEPTION: main
02-07 12:12:12.505  2933  2933 E AndroidRuntime: Process: cgeo.geocaching, PID: 2933
02-07 12:12:12.505  2933  2933 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.log.LogCacheActivity}: java.lang.ClassCastException: androidx.appcompat.widget.ContentFrameLayout cannot be cast to android.widget.ScrollView
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: Caused by: java.lang.ClassCastException: androidx.appcompat.widget.ContentFrameLayout cannot be cast to android.widget.ScrollView
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at cgeo.geocaching.databinding.LogcacheActivityBinding.bind(LogcacheActivityBinding.java:202)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at cgeo.geocaching.log.LogCacheActivity.onCreate(LogCacheActivity.java:210)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8000)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7984)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
02-07 12:12:12.505  2933  2933 E AndroidRuntime: 	... 11 more
02-07 12:12:26.620  3689  3689 E AndroidRuntime: FATAL EXCEPTION: main
02-07 12:12:26.620  3689  3689 E AndroidRuntime: Process: cgeo.geocaching, PID: 3689
02-07 12:12:26.620  3689  3689 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.log.LogCacheActivity}: java.lang.ClassCastException: androidx.appcompat.widget.ContentFrameLayout cannot be cast to android.widget.ScrollView
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: Caused by: java.lang.ClassCastException: androidx.appcompat.widget.ContentFrameLayout cannot be cast to android.widget.ScrollView
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at cgeo.geocaching.databinding.LogcacheActivityBinding.bind(LogcacheActivityBinding.java:202)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at cgeo.geocaching.log.LogCacheActivity.onCreate(LogCacheActivity.java:210)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8000)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7984)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
02-07 12:12:26.620  3689  3689 E AndroidRuntime: 	... 11 more
```

**Comment by Lineflyer** [comment]
Same happens if you try via direct search:

- Search for geocode GC6JY29 (a PM-only cache)
- c:geo will report correctly, that you cannot view it as it is a PM-only cache and offers to post a log instead
- Select "Log Visit"

```
2-07 12:19:28.924  4522  4522 E AndroidRuntime: FATAL EXCEPTION: main
02-07 12:19:28.924  4522  4522 E AndroidRuntime: Process: cgeo.geocaching, PID: 4522
02-07 12:19:28.924  4522  4522 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.log.LogCacheActivity}: java.lang.ClassCastException: androidx.appcompat.widget.ContentFrameLayout cannot be cast to android.widget.ScrollView
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3431)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: Caused by: java.lang.ClassCastException: androidx.appcompat.widget.ContentFrameLayout cannot be cast to android.widget.ScrollView
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at cgeo.geocaching.databinding.LogcacheActivityBinding.bind(LogcacheActivityBinding.java:202)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at cgeo.geocaching.log.LogCacheActivity.onCreate(LogCacheActivity.java:210)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8000)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7984)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
02-07 12:19:28.924  4522  4522 E AndroidRuntime: 	... 11 more
```

**Comment by fm-sys** [comment]
I can reproduce the problem. Something must have changed in the last few months, because until at least November it worked properly...

**Comment by Lineflyer** [comment]
In fact its a more generic issue. All logging crashes with todays nightly.

**Comment by Lineflyer** [comment]
Seems to be a specific caase out of a generic problem in our nightlies: #9975
