### ISSUE TITLE
Cannot log cache [NIGHTLY]

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo#9975]
Reported by nightly users and reproducible for me with 2021.02.07-NB

- Open a cache
- Select log visit

Crash:
```
02-07 12:00:10.718  5539  5539 E AndroidRuntime: FATAL EXCEPTION: main
02-07 12:00:10.718  5539  5539 E AndroidRuntime: Process: cgeo.geocaching, PID: 5539
02-07 12:00:10.718  5539  5539 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{cgeo.geocaching/cgeo.geocaching.log.LogCacheActivity}: java.lang.ClassCastException: androidx.appcompat.widget.ContentFrameLayout cannot be cast to android.widget.ScrollView
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3763)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3939)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2278)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:246)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8419)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: Caused by: java.lang.ClassCastException: androidx.appcompat.widget.ContentFrameLayout cannot be cast to android.widget.ScrollView
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at cgeo.geocaching.databinding.LogcacheActivityBinding.bind(LogcacheActivityBinding.java:202)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at cgeo.geocaching.log.LogCacheActivity.onCreate(LogCacheActivity.java:210)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8171)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8155)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3736)
02-07 12:00:10.718  5539  5539 E AndroidRuntime: 	... 11 more
```

**Comment by Lineflyer** [comment]
@moving-bits Looks like a problem with your butterknife replacement?

**Comment by Lineflyer** [comment]
I created a message for `versionCode >= 30210207` on our notification system to inform nightly users.

**Comment by moving-bits** [comment]
> @moving-bits Looks like a problem with your butterknife replacement?

May very well be possible. I'll have a look at it.
